/* ================================================
   CHAPTERS METADATA
   ================================================
   Contains basic info for all 114 Quran chapters.
   This is loaded once and used for the chapter list.
   Each chapter's detailed verse data is in a separate
   file under data/chapter_XXX.js
   
   Fields:
   - number: Chapter number (1-114)
   - name_ar: Arabic name
   - name_en: English transliteration
   - meaning: English meaning of the name
   - verses: Total number of verses
   - type: "Makkan" or "Medinan" (revelation location)
================================================ */

const chaptersData = [
  { number: 1, name_ar: "الفاتحة", name_en: "Al-Fatihah", meaning: "The Opening", verses: 7, type: "Makkan" },
  { number: 2, name_ar: "البقرة", name_en: "Al-Baqarah", meaning: "The Cow", verses: 286, type: "Medinan" },
  { number: 3, name_ar: "آل عمران", name_en: "Ali 'Imran", meaning: "Family of Imran", verses: 200, type: "Medinan" },
  { number: 4, name_ar: "النساء", name_en: "An-Nisa", meaning: "The Women", verses: 176, type: "Medinan" },
  { number: 5, name_ar: "المائدة", name_en: "Al-Ma'idah", meaning: "The Table Spread", verses: 120, type: "Medinan" },
  { number: 6, name_ar: "الأنعام", name_en: "Al-An'am", meaning: "The Cattle", verses: 165, type: "Makkan" },
  { number: 7, name_ar: "الأعراف", name_en: "Al-A'raf", meaning: "The Heights", verses: 206, type: "Makkan" },
  { number: 8, name_ar: "الأنفال", name_en: "Al-Anfal", meaning: "The Spoils of War", verses: 75, type: "Medinan" },
  { number: 9, name_ar: "التوبة", name_en: "At-Tawbah", meaning: "The Repentance", verses: 129, type: "Medinan" },
  { number: 10, name_ar: "يونس", name_en: "Yunus", meaning: "Jonah", verses: 109, type: "Makkan" },
  { number: 11, name_ar: "هود", name_en: "Hud", meaning: "Hud", verses: 123, type: "Makkan" },
  { number: 12, name_ar: "يوسف", name_en: "Yusuf", meaning: "Joseph", verses: 111, type: "Makkan" },
  { number: 13, name_ar: "الرعد", name_en: "Ar-Ra'd", meaning: "The Thunder", verses: 43, type: "Medinan" },
  { number: 14, name_ar: "إبراهيم", name_en: "Ibrahim", meaning: "Abraham", verses: 52, type: "Makkan" },
  { number: 15, name_ar: "الحجر", name_en: "Al-Hijr", meaning: "The Rocky Tract", verses: 99, type: "Makkan" },
  { number: 16, name_ar: "النحل", name_en: "An-Nahl", meaning: "The Bee", verses: 128, type: "Makkan" },
  { number: 17, name_ar: "الإسراء", name_en: "Al-Isra", meaning: "The Night Journey", verses: 111, type: "Makkan" },
  { number: 18, name_ar: "الكهف", name_en: "Al-Kahf", meaning: "The Cave", verses: 110, type: "Makkan" },
  { number: 19, name_ar: "مريم", name_en: "Maryam", meaning: "Mary", verses: 98, type: "Makkan" },
  { number: 20, name_ar: "طه", name_en: "Taha", meaning: "Ta-Ha", verses: 135, type: "Makkan" },
  { number: 21, name_ar: "الأنبياء", name_en: "Al-Anbiya", meaning: "The Prophets", verses: 112, type: "Makkan" },
  { number: 22, name_ar: "الحج", name_en: "Al-Hajj", meaning: "The Pilgrimage", verses: 78, type: "Medinan" },
  { number: 23, name_ar: "المؤمنون", name_en: "Al-Mu'minun", meaning: "The Believers", verses: 118, type: "Makkan" },
  { number: 24, name_ar: "النور", name_en: "An-Nur", meaning: "The Light", verses: 64, type: "Medinan" },
  { number: 25, name_ar: "الفرقان", name_en: "Al-Furqan", meaning: "The Criterion", verses: 77, type: "Makkan" },
  { number: 26, name_ar: "الشعراء", name_en: "Ash-Shu'ara", meaning: "The Poets", verses: 227, type: "Makkan" },
  { number: 27, name_ar: "النمل", name_en: "An-Naml", meaning: "The Ant", verses: 93, type: "Makkan" },
  { number: 28, name_ar: "القصص", name_en: "Al-Qasas", meaning: "The Stories", verses: 88, type: "Makkan" },
  { number: 29, name_ar: "العنكبوت", name_en: "Al-Ankabut", meaning: "The Spider", verses: 69, type: "Makkan" },
  { number: 30, name_ar: "الروم", name_en: "Ar-Rum", meaning: "The Romans", verses: 60, type: "Makkan" },
  { number: 31, name_ar: "لقمان", name_en: "Luqman", meaning: "Luqman", verses: 34, type: "Makkan" },
  { number: 32, name_ar: "السجدة", name_en: "As-Sajdah", meaning: "The Prostration", verses: 30, type: "Makkan" },
  { number: 33, name_ar: "الأحزاب", name_en: "Al-Ahzab", meaning: "The Confederates", verses: 73, type: "Medinan" },
  { number: 34, name_ar: "سبأ", name_en: "Saba", meaning: "Sheba", verses: 54, type: "Makkan" },
  { number: 35, name_ar: "فاطر", name_en: "Fatir", meaning: "Originator", verses: 45, type: "Makkan" },
  { number: 36, name_ar: "يس", name_en: "Ya-Sin", meaning: "Ya Sin", verses: 83, type: "Makkan" },
  { number: 37, name_ar: "الصافات", name_en: "As-Saffat", meaning: "Those in Ranks", verses: 182, type: "Makkan" },
  { number: 38, name_ar: "ص", name_en: "Sad", meaning: "Sad", verses: 88, type: "Makkan" },
  { number: 39, name_ar: "الزمر", name_en: "Az-Zumar", meaning: "The Troops", verses: 75, type: "Makkan" },
  { number: 40, name_ar: "غافر", name_en: "Ghafir", meaning: "The Forgiver", verses: 85, type: "Makkan" },
  { number: 41, name_ar: "فصلت", name_en: "Fussilat", meaning: "Explained in Detail", verses: 54, type: "Makkan" },
  { number: 42, name_ar: "الشورى", name_en: "Ash-Shura", meaning: "The Consultation", verses: 53, type: "Makkan" },
  { number: 43, name_ar: "الزخرف", name_en: "Az-Zukhruf", meaning: "The Ornaments", verses: 89, type: "Makkan" },
  { number: 44, name_ar: "الدخان", name_en: "Ad-Dukhan", meaning: "The Smoke", verses: 59, type: "Makkan" },
  { number: 45, name_ar: "الجاثية", name_en: "Al-Jathiyah", meaning: "The Crouching", verses: 37, type: "Makkan" },
  { number: 46, name_ar: "الأحقاف", name_en: "Al-Ahqaf", meaning: "The Wind-Curved Sandhills", verses: 35, type: "Makkan" },
  { number: 47, name_ar: "محمد", name_en: "Muhammad", meaning: "Muhammad", verses: 38, type: "Medinan" },
  { number: 48, name_ar: "الفتح", name_en: "Al-Fath", meaning: "The Victory", verses: 29, type: "Medinan" },
  { number: 49, name_ar: "الحجرات", name_en: "Al-Hujurat", meaning: "The Rooms", verses: 18, type: "Medinan" },
  { number: 50, name_ar: "ق", name_en: "Qaf", meaning: "Qaf", verses: 45, type: "Makkan" },
  { number: 51, name_ar: "الذاريات", name_en: "Adh-Dhariyat", meaning: "The Winnowing Winds", verses: 60, type: "Makkan" },
  { number: 52, name_ar: "الطور", name_en: "At-Tur", meaning: "The Mount", verses: 49, type: "Makkan" },
  { number: 53, name_ar: "النجم", name_en: "An-Najm", meaning: "The Star", verses: 62, type: "Makkan" },
  { number: 54, name_ar: "القمر", name_en: "Al-Qamar", meaning: "The Moon", verses: 55, type: "Makkan" },
  { number: 55, name_ar: "الرحمن", name_en: "Ar-Rahman", meaning: "The Beneficent", verses: 78, type: "Medinan" },
  { number: 56, name_ar: "الواقعة", name_en: "Al-Waqi'ah", meaning: "The Inevitable", verses: 96, type: "Makkan" },
  { number: 57, name_ar: "الحديد", name_en: "Al-Hadid", meaning: "The Iron", verses: 29, type: "Medinan" },
  { number: 58, name_ar: "المجادلة", name_en: "Al-Mujadila", meaning: "The Pleading Woman", verses: 22, type: "Medinan" },
  { number: 59, name_ar: "الحشر", name_en: "Al-Hashr", meaning: "The Exile", verses: 24, type: "Medinan" },
  { number: 60, name_ar: "الممتحنة", name_en: "Al-Mumtahanah", meaning: "She That is Examined", verses: 13, type: "Medinan" },
  { number: 61, name_ar: "الصف", name_en: "As-Saf", meaning: "The Ranks", verses: 14, type: "Medinan" },
  { number: 62, name_ar: "الجمعة", name_en: "Al-Jumu'ah", meaning: "The Congregation", verses: 11, type: "Medinan" },
  { number: 63, name_ar: "المنافقون", name_en: "Al-Munafiqun", meaning: "The Hypocrites", verses: 11, type: "Medinan" },
  { number: 64, name_ar: "التغابن", name_en: "At-Taghabun", meaning: "The Mutual Disillusion", verses: 18, type: "Medinan" },
  { number: 65, name_ar: "الطلاق", name_en: "At-Talaq", meaning: "The Divorce", verses: 12, type: "Medinan" },
  { number: 66, name_ar: "التحريم", name_en: "At-Tahrim", meaning: "The Prohibition", verses: 12, type: "Medinan" },
  { number: 67, name_ar: "الملك", name_en: "Al-Mulk", meaning: "The Sovereignty", verses: 30, type: "Makkan" },
  { number: 68, name_ar: "القلم", name_en: "Al-Qalam", meaning: "The Pen", verses: 52, type: "Makkan" },
  { number: 69, name_ar: "الحاقة", name_en: "Al-Haqqah", meaning: "The Reality", verses: 52, type: "Makkan" },
  { number: 70, name_ar: "المعارج", name_en: "Al-Ma'arij", meaning: "The Ascending Stairways", verses: 44, type: "Makkan" },
  { number: 71, name_ar: "نوح", name_en: "Nuh", meaning: "Noah", verses: 28, type: "Makkan" },
  { number: 72, name_ar: "الجن", name_en: "Al-Jinn", meaning: "The Jinn", verses: 28, type: "Makkan" },
  { number: 73, name_ar: "المزمل", name_en: "Al-Muzzammil", meaning: "The Enshrouded One", verses: 20, type: "Makkan" },
  { number: 74, name_ar: "المدثر", name_en: "Al-Muddaththir", meaning: "The Cloaked One", verses: 56, type: "Makkan" },
  { number: 75, name_ar: "القيامة", name_en: "Al-Qiyamah", meaning: "The Resurrection", verses: 40, type: "Makkan" },
  { number: 76, name_ar: "الإنسان", name_en: "Al-Insan", meaning: "The Human", verses: 31, type: "Medinan" },
  { number: 77, name_ar: "المرسلات", name_en: "Al-Mursalat", meaning: "The Emissaries", verses: 50, type: "Makkan" },
  { number: 78, name_ar: "النبأ", name_en: "An-Naba", meaning: "The Tidings", verses: 40, type: "Makkan" },
  { number: 79, name_ar: "النازعات", name_en: "An-Nazi'at", meaning: "Those Who Drag Forth", verses: 46, type: "Makkan" },
  { number: 80, name_ar: "عبس", name_en: "Abasa", meaning: "He Frowned", verses: 42, type: "Makkan" },
  { number: 81, name_ar: "التكوير", name_en: "At-Takwir", meaning: "The Overthrowing", verses: 29, type: "Makkan" },
  { number: 82, name_ar: "الانفطار", name_en: "Al-Infitar", meaning: "The Cleaving", verses: 19, type: "Makkan" },
  { number: 83, name_ar: "المطففين", name_en: "Al-Mutaffifin", meaning: "The Defrauding", verses: 36, type: "Makkan" },
  { number: 84, name_ar: "الانشقاق", name_en: "Al-Inshiqaq", meaning: "The Sundering", verses: 25, type: "Makkan" },
  { number: 85, name_ar: "البروج", name_en: "Al-Buruj", meaning: "The Mansions of the Stars", verses: 22, type: "Makkan" },
  { number: 86, name_ar: "الطارق", name_en: "At-Tariq", meaning: "The Morning Star", verses: 17, type: "Makkan" },
  { number: 87, name_ar: "الأعلى", name_en: "Al-A'la", meaning: "The Most High", verses: 19, type: "Makkan" },
  { number: 88, name_ar: "الغاشية", name_en: "Al-Ghashiyah", meaning: "The Overwhelming", verses: 26, type: "Makkan" },
  { number: 89, name_ar: "الفجر", name_en: "Al-Fajr", meaning: "The Dawn", verses: 30, type: "Makkan" },
  { number: 90, name_ar: "البلد", name_en: "Al-Balad", meaning: "The City", verses: 20, type: "Makkan" },
  { number: 91, name_ar: "الشمس", name_en: "Ash-Shams", meaning: "The Sun", verses: 15, type: "Makkan" },
  { number: 92, name_ar: "الليل", name_en: "Al-Layl", meaning: "The Night", verses: 21, type: "Makkan" },
  { number: 93, name_ar: "الضحى", name_en: "Ad-Duhaa", meaning: "The Morning Hours", verses: 11, type: "Makkan" },
  { number: 94, name_ar: "الشرح", name_en: "Ash-Sharh", meaning: "The Relief", verses: 8, type: "Makkan" },
  { number: 95, name_ar: "التين", name_en: "At-Tin", meaning: "The Fig", verses: 8, type: "Makkan" },
  { number: 96, name_ar: "العلق", name_en: "Al-Alaq", meaning: "The Clot", verses: 19, type: "Makkan" },
  { number: 97, name_ar: "القدر", name_en: "Al-Qadr", meaning: "The Power", verses: 5, type: "Makkan" },
  { number: 98, name_ar: "البينة", name_en: "Al-Bayyinah", meaning: "The Clear Proof", verses: 8, type: "Medinan" },
  { number: 99, name_ar: "الزلزلة", name_en: "Az-Zalzalah", meaning: "The Earthquake", verses: 8, type: "Medinan" },
  { number: 100, name_ar: "العاديات", name_en: "Al-Adiyat", meaning: "The Courser", verses: 11, type: "Makkan" },
  { number: 101, name_ar: "القارعة", name_en: "Al-Qari'ah", meaning: "The Calamity", verses: 11, type: "Makkan" },
  { number: 102, name_ar: "التكاثر", name_en: "At-Takathur", meaning: "The Rivalry in Worldly Increase", verses: 8, type: "Makkan" },
  { number: 103, name_ar: "العصر", name_en: "Al-Asr", meaning: "The Declining Day", verses: 3, type: "Makkan" },
  { number: 104, name_ar: "الهمزة", name_en: "Al-Humazah", meaning: "The Traducer", verses: 9, type: "Makkan" },
  { number: 105, name_ar: "الفيل", name_en: "Al-Fil", meaning: "The Elephant", verses: 5, type: "Makkan" },
  { number: 106, name_ar: "قريش", name_en: "Quraysh", meaning: "Quraysh", verses: 4, type: "Makkan" },
  { number: 107, name_ar: "الماعون", name_en: "Al-Ma'un", meaning: "The Small Kindnesses", verses: 7, type: "Makkan" },
  { number: 108, name_ar: "الكوثر", name_en: "Al-Kawthar", meaning: "The Abundance", verses: 3, type: "Makkan" },
  { number: 109, name_ar: "الكافرون", name_en: "Al-Kafirun", meaning: "The Disbelievers", verses: 6, type: "Makkan" },
  { number: 110, name_ar: "النصر", name_en: "An-Nasr", meaning: "The Divine Support", verses: 3, type: "Medinan" },
  { number: 111, name_ar: "المسد", name_en: "Al-Masad", meaning: "The Palm Fiber", verses: 5, type: "Makkan" },
  { number: 112, name_ar: "الإخلاص", name_en: "Al-Ikhlas", meaning: "The Sincerity", verses: 4, type: "Makkan" },
  { number: 113, name_ar: "الفلق", name_en: "Al-Falaq", meaning: "The Daybreak", verses: 5, type: "Makkan" },
  { number: 114, name_ar: "الناس", name_en: "An-Nas", meaning: "Mankind", verses: 6, type: "Makkan" }
];
