var tafsirData_114 = {
  1: {
    "Say, ˹O Prophet,˺": "This is a direct command from Allah to Prophet Muhammad (peace be upon him), and by extension to all believers, to make this supplication. Allah is teaching us the exact words to use when seeking His protection. This shows Allah's care for us—He doesn't just tell us to seek refuge, He teaches us precisely how to do it. Just as a loving parent teaches a child the right words to say in difficult situations, Allah teaches us these powerful words of protection.",
    "\"I seek refuge": "This is a declaration of complete dependence on Allah for safety and protection. To seek refuge means to flee from something harmful toward something that can protect you. When a person says these words sincerely, they are acknowledging their own weakness and Allah's absolute power to shield them from harm. It is like a child running to their parent when scared—we run to Allah when we need protection from spiritual dangers.",
    "in the Lord of humankind": "Allah describes Himself here as the Lord (Rabb) of all humanity. The term 'Lord' encompasses being the Creator, Sustainer, Nurturer, and Caretaker of all people. By using this attribute, Allah reminds us that He is the One who brought all humans into existence, provides for them, and has complete authority over their affairs. When we seek refuge in the 'Lord of humankind,' we are turning to the One who knows humanity best because He created them, and therefore He knows exactly what harms them and how to protect them."
  },
  2: {
    "the Master of humankind": "After describing Himself as the Lord, Allah now emphasizes that He is the King and Master of all people. While earthly kings have limited power and their authority ends at death, Allah's kingship is absolute, eternal, and encompasses every single human being who ever lived or will live. No one can escape His dominion. This attribute reassures us that when we seek His protection, we are seeking it from the ultimate authority—the One whose command cannot be overruled by anyone. A king protects his subjects; how much more will the King of all kings protect those who turn to Him? The Prophet (peace be upon him) said that on the Day of Judgment, Allah will say, 'I am the King, where are the kings of the earth?' (Sahih Muslim). This reminds us that all worldly power is temporary, and true kingship belongs only to Allah."
  },
  3: {
    "the God of humankind": "This completes the three magnificent attributes: Lord, Master, and God. As the God (Ilah) of humankind, Allah is the only One worthy of worship, devotion, and complete submission. He is the only true deity for all people, regardless of whether they acknowledge Him or not. This attribute establishes that our protection comes from the One who alone deserves to be called upon, the One to whom all prayers should be directed. These three attributes together—Lord (Rabb), Master (Malik), and God (Ilah)—cover every aspect of Allah's relationship with humanity: He creates and sustains us, He rules over us with absolute authority, and He alone is worthy of our worship. This powerful beginning reminds us that we are seeking protection from the most powerful Being in existence, and this connects beautifully with the opening of the Quran (Al-Fatiha) which also emphasizes these same attributes, bringing the Quran full circle."
  },
  4: {
    "from the evil of the lurking whisperer": "Now Allah specifies what we are seeking protection from: the whisperer who lurks and retreats. The term 'whisperer' refers to Satan and his helpers who whisper evil suggestions, doubts, and temptations into the hearts of people. The word 'lurking' (or 'retreating') describes how this whisperer operates—he whispers his evil suggestions and then withdraws, making the person think the thought came from their own mind. This is his deceptive strategy. When a person remembers Allah and seeks His protection, the whisperer retreats and hides. But when a person becomes heedless and forgets Allah, the whisperer returns to continue his evil work. The Prophet (peace be upon him) explained that Satan flows through the human being like blood flows through the veins (Sahih Bukhari). This shows how close and constant this threat is. The evil of this whisperer is described as something we need Allah's protection from because we cannot defeat it on our own—it is an invisible enemy that attacks us from within, targeting our thoughts and desires."
  },
  5: {
    "who whispers into the hearts of humankind": "This verse clarifies exactly where the whisperer attacks—the hearts (or chests) of people. The heart in Islamic understanding is the center of thoughts, intentions, emotions, and decisions. By whispering into the heart, Satan tries to corrupt a person's thinking, create doubts about faith, make sins seem attractive, and make good deeds seem difficult or unnecessary. He doesn't force anyone to sin; rather, he plants suggestions and beautifies evil until the person willingly chooses to disobey Allah. For example, he might whisper to someone praying, 'Did you really make proper ablution? Maybe you should start over,' causing unnecessary doubt and distraction. Or he might whisper, 'You can pray later, just finish watching this first,' gradually pulling a person away from obedience. The Prophet (peace be upon him) told us that Satan even tries to whisper doubts about Allah Himself, trying to make people question their faith (Sahih Muslim). This is why we need constant protection—the attack is ongoing and targets the very core of who we are."
  },
  6: {
    "from among jinn and humankind": "This final verse reveals a crucial truth: the whisperers who try to lead us astray come from two sources—the jinn (including Satan and his followers) and also from human beings. Many people only think of Satan as the enemy, but Allah makes clear that evil humans also act as whisperers, tempting others toward sin, spreading corruption, and encouraging disobedience to Allah. Just as Satan whispered to Adam and Eve, some humans whisper evil to their friends, colleagues, or through media, trying to normalize sin and make people comfortable with disobedience. The Quran mentions in Surah Al-An'am (6:112) that Allah has made for every prophet enemies from among devils of humans and jinn, who inspire one another with decorated speech in order to deceive. This verse teaches us to be cautious of evil influence from both seen and unseen sources. We must be careful about who we take as close friends and what influences we allow into our hearts and minds. By ending the Quran with this comprehensive protection against both human and jinn whisperers, Allah gives us a powerful tool to safeguard our faith and hearts until the Day we meet Him."
  }
};