var tafsirData_98 = {
  1: {
    "The disbelievers from the People of the Book": "This refers to those among the Jews and Christians who rejected faith. The People of the Book are called so because they received divine scriptures—the Torah and the Gospel. However, some of them fell into disbelief by denying the truth that came after their scriptures, or by distorting their own teachings. Allah distinguishes them here because they had prior knowledge of prophets and revelation, yet some still chose to reject the final message.",
    "and the polytheists": "These are the idol worshippers, particularly the Arabs of Makkah and surrounding areas who worshipped multiple gods alongside or instead of Allah. They had no previous scripture but followed the traditions of their ancestors in associating partners with Allah. Both groups—despite their differences—shared one thing in common: disbelief and rejection of pure monotheism.",
    "were not going to desist ˹from disbelief˺": "They were not going to abandon their false beliefs, their misguidance, or their corrupt practices on their own. They were stuck in their ways, generation after generation, with no clear path out of their spiritual darkness. This shows that without divine intervention and clear guidance, people often remain trapped in the errors they inherit or adopt.",
    "until the clear proof came to them": "The clear proof refers to Prophet Muhammad (ﷺ) and the Quran he brought. Allah sent this undeniable evidence so that people would have no excuse to remain in disbelief. Before the Prophet (ﷺ) came, the People of the Book had corrupted their scriptures, and the polytheists had no guidance at all. The arrival of the Prophet (ﷺ) was the turning point—a mercy and a warning for all of humanity."
  },
  2: {
    "a messenger from Allah": "This messenger is Prophet Muhammad (ﷺ), sent directly by Allah to guide humanity. He was not self-appointed, nor did he speak from his own desires. He was chosen by Allah and given the responsibility of conveying the final message to all people. The Prophet (ﷺ) said: \"Every prophet was sent specifically to his own people, but I have been sent to all of humanity\" (Sahih al-Bukhari). His coming was foretold in previous scriptures, and he is the seal of all prophets.",
    "reciting scrolls of ˹utmost˺ purity": "The Prophet (ﷺ) recited the Quran, which is described as pure and purified scriptures. These scrolls (pages of revelation) are free from any falsehood, error, contradiction, or corruption. Unlike previous scriptures that were altered over time by human hands, the Quran remains exactly as it was revealed. It purifies the hearts of those who listen to it with sincerity and guides them to the straight path. The purity here means the Quran is untouched by lies, protected by Allah Himself, as He says: \"Indeed, it is We who sent down the reminder, and indeed, We will be its guardian\" (Quran 15:9)."
  },
  3: {
    "containing upright commandments": "Within these purified scriptures are laws, teachings, and commandments that are perfectly upright, just, and balanced. These are not man-made rules that favor one group over another or change with time based on desires. They are divine laws that establish justice, promote goodness, and forbid evil. The word 'upright' means they are straight, correct, and lead directly to success in this life and the next. Every ruling in the Quran—whether about worship, family, business, or society—is designed to bring people closer to Allah and to create harmony in human life. There is nothing crooked, unjust, or outdated in these commandments."
  },
  4: {
    "It was not until this clear proof came to the People of the Book": "Before the Prophet Muhammad (ﷺ) arrived, the Jews and Christians were actually waiting for him. Their scriptures contained descriptions of the final prophet, and their scholars knew he would come. They even used to tell the Arab polytheists that a prophet would soon arrive and they would follow him. However, when he actually came, something unexpected happened among them.",
    "that they became divided ˹about his prophethood˺": "Instead of uniting upon the truth they had been anticipating, they split into factions. Some believed in the Prophet (ﷺ) and accepted Islam, recognizing him as the one foretold in their books. But many others rejected him out of jealousy, pride, or worldly interests. They could not accept that the final prophet came from the Arabs rather than from their own lineage. This division was not due to lack of evidence—the proof was clear. Rather, it was due to their own desires and refusal to submit to the truth. Allah criticizes this because division after clear guidance is a sign of following ego rather than following truth."
  },
  5: {
    "even though they were only commanded to worship Allah ˹alone˺": "The core message given to all people—including the People of the Book—was always the same: worship Allah alone. This was the message of every prophet, from Adam to Noah to Abraham to Moses to Jesus, and finally to Muhammad (peace be upon them all). Allah says in another verse: \"And We certainly sent into every nation a messenger, saying: Worship Allah and avoid false gods\" (Quran 16:36). The command was never complicated or confusing.",
    "with sincere devotion to Him in all uprightness": "Worship must be done with sincerity, meaning the intention behind every act of worship should be purely for Allah's pleasure, not for showing off, not for worldly gain, and not mixed with any form of associating partners with Him. Uprightness means turning away from all false religions and false gods, following the pure monotheism of Prophet Ibrahim (Abraham). A person who is sincere does not worship to impress others or to gain status—they worship because Allah alone deserves worship.",
    "establish prayer": "Prayer is the most important act of worship after belief itself. To establish prayer means more than just performing it—it means praying consistently, on time, with proper focus and humility, and fulfilling all its conditions. The Prophet (ﷺ) said: \"The covenant between us and them (the disbelievers) is prayer; whoever abandons it has disbelieved\" (Sunan al-Tirmidhi). Prayer was commanded in every religion, though its form may have varied.",
    "and pay alms-tax": "Zakat is the obligatory charity that purifies wealth and helps those in need. It teaches Muslims to be generous, to care for the poor, and to recognize that all wealth ultimately belongs to Allah. Paying zakat was also commanded to previous nations. It builds a society where the wealthy support the needy, reducing poverty and resentment.",
    "That is the upright Way": "These simple commands—sincere worship of Allah alone, prayer, and charity—constitute the true, straight, and correct religion. This is the path that all prophets taught. It is not complicated, nor is it burdensome. It is the natural way that leads to success in this world and salvation in the Hereafter. Anyone who follows this path is upon the religion that Allah is pleased with."
  },
  6: {
    "Indeed, those who disbelieve from the People of the Book and the polytheists": "Allah now clearly states the fate of those who reject the truth after it has been made clear to them. This includes both groups mentioned earlier: the disbelievers among the Jews and Christians who refused to accept Prophet Muhammad (ﷺ) despite recognizing him, and the idol worshippers who persisted in their polytheism. The key factor here is disbelief—rejecting Allah's guidance after it has been presented with clear evidence.",
    "will be in the Fire of Hell": "Their destination is the Hellfire, the place of severe punishment prepared for those who reject Allah and His messengers. The Hellfire is described in many verses and hadiths as a place of unimaginable torment—its fuel is people and stones, its flames are intensely hot, and its punishments are beyond human comprehension. This is the consequence of turning away from the Creator and refusing His mercy.",
    "to stay there forever": "This is not a temporary punishment. For those who die upon disbelief, the Hellfire is their eternal abode. There is no escape, no end, and no relief. This should serve as the most serious warning for anyone considering rejecting the truth. Allah's mercy is vast, but those who deliberately reject it condemn themselves to eternal loss.",
    "They are the worst of ˹all˺ beings": "Allah declares that these disbelievers are the worst of all creation. This may seem like a strong statement, but it reflects a profound truth: human beings were created with intellect, given clear guidance, and honored above other creatures. When they use these gifts to reject their Creator and worship false gods or deny His messengers, they fall lower than any other creation. Animals follow their natural instincts and do not rebel against Allah's design, but a disbelieving human actively chooses to reject the One who created them, which is the greatest injustice and the worst possible choice a person can make."
  },
  7: {
    "Indeed, those who believe": "True faith means accepting Allah as the only God worthy of worship, believing in all His messengers including the final Prophet Muhammad (ﷺ), believing in the angels, the divine books, the Day of Judgment, and divine decree. But belief is not just words—it must settle in the heart and manifest in actions. A person who truly believes will naturally want to obey Allah and follow His guidance.",
    "and do good": "Faith must be accompanied by righteous actions. This includes all forms of obedience to Allah—prayers, charity, kindness to parents, honesty in dealings, helping others, avoiding sins, and striving to please Allah in every aspect of life. The Prophet (ﷺ) said: \"Faith has over seventy branches, the highest of which is saying 'There is no god but Allah,' and the lowest is removing something harmful from the road\" (Sahih Muslim). Good deeds are the proof and fruit of genuine faith.",
    "they are the best of ˹all˺ beings": "Just as the disbelievers were called the worst of creation, the believers who do good deeds are declared the best of all creation. This is an incredible honor from Allah. These believers have used their intellect, freedom, and abilities for their intended purpose: to know, worship, and obey their Creator. They have fulfilled the very purpose for which they were created. Because of this, they are elevated above all other beings, including even the angels according to some scholars, because they chose faith despite facing temptations and challenges that angels do not face."
  },
  8: {
    "Their reward with their Lord": "The reward for the believers is not from any human or any limited source—it comes directly from their Lord, the Creator of all things. When Allah gives a reward, it is beyond anything we can imagine. He is the Most Generous, and His treasures never decrease. The fact that it is \"with their Lord\" also indicates the honor and closeness these believers will have with Allah.",
    "will be Gardens of Eternity": "Paradise is described as gardens—places of beauty, peace, shade, and abundance. The word 'eternity' emphasizes that this is not a temporary vacation but a permanent home. These gardens contain everything the heart could desire: beautiful homes, delicious food and drink, loving companionship, and most importantly, the pleasure of Allah. The Prophet (ﷺ) said: \"In Paradise there is what no eye has seen, no ear has heard, and no human heart has ever imagined\" (Sahih al-Bukhari).",
    "under which rivers flow": "Beneath these gardens, rivers flow continuously. The Quran describes rivers of pure water, rivers of milk, rivers of honey, and rivers of wine that does not intoxicate. These rivers provide endless refreshment and add to the beauty and tranquility of Paradise. Unlike the rivers of this world that can dry up or become polluted, the rivers of Paradise flow eternally, pure and perfect.",
    "to stay there for ever and ever": "The believers will remain in Paradise forever. There is no death, no aging, no sickness, and no end. This eternal bliss is the ultimate success. Imagine the most perfect moment of happiness you have ever experienced, then imagine it never ending and always increasing—this gives only a glimpse of what eternal Paradise means.",
    "Allah is pleased with them": "This is perhaps the greatest reward of all—Allah's pleasure. When Allah is pleased with someone, it means they have succeeded in the ultimate sense. The Prophet (ﷺ) said that Allah will say to the people of Paradise: \"I will give you something better than all of this.\" They will ask, \"What could be better?\" And He will say: \"I bestow upon you My pleasure, and I will never be angry with you after this\" (Sahih al-Bukhari and Muslim). This divine pleasure is the source of all the blessings of Paradise.",
    "and they are pleased with Him": "The believers will be completely content and satisfied with their Lord. They will have no complaints, no regrets, and no unfulfilled desires. They will recognize and appreciate everything Allah has given them, and they will be grateful for every blessing. This mutual pleasure—Allah pleased with them and they pleased with Him—represents the most perfect relationship possible.",
    "This is ˹only˺ for those in awe of their Lord": "All these incredible rewards are reserved for those who have true reverence and fear of Allah. This is not a terrifying fear but a profound awareness of Allah's greatness, power, and justice that motivates a person to obey Him and avoid displeasing Him. Those who are in awe of Allah live their lives conscious of His presence, careful about their actions, and eager to earn His pleasure. This awe is what distinguishes the sincere believers from those who are heedless. It is the foundation of true faith and the key to attaining Paradise."
  }
};