var tafsirData_62 = {
  1: {
    "Whatever is in the heavens and whatever is on the earth constantly glorifies Allah": "Every single creation in the universe—whether in the skies or on the ground, from the largest stars to the smallest particles, from angels to animals, plants, and even inanimate objects—is in a continuous state of praising and glorifying Allah. This glorification happens in ways we may or may not perceive. The birds sing, the trees sway, the mountains stand firm, and all of creation submits to Allah in its own unique way. This teaches us that as human beings, we should join this universal chorus of praise consciously and willingly.",
    "the King": "Allah is Al-Malik, the absolute Sovereign and Ruler over all that exists. Unlike earthly kings whose dominion is limited and temporary, Allah's kingdom encompasses everything—the seen and unseen, this world and the hereafter. He has complete authority over all affairs, and nothing happens without His permission.",
    "the Most Holy": "Allah is Al-Quddus, completely pure and free from any imperfection, defect, or shortcoming. He is far above any deficiency that creation might have. His holiness means He is perfect in every way and transcends all limitations.",
    "the Almighty": "Allah is Al-Aziz, possessing absolute power and might that cannot be overcome or challenged. No one can resist His will, and no force can oppose Him. His strength is complete and His authority is unchallengeable.",
    "the All-Wise": "Allah is Al-Hakeem, whose every action, command, and decree is filled with perfect wisdom. Nothing He does is without purpose. Even when we don't understand why something happens, we trust that Allah's wisdom is behind it."
  },
  2: {
    "He is the One Who raised for the illiterate people a messenger from among themselves": "Allah sent Prophet Muhammad (ﷺ) to the Arabs, who were largely an unlettered nation without a scripture of their own. The Prophet himself could not read or write, which actually serves as a proof of the divine origin of the Quran—how could an unlettered man produce such a miraculous book? Allah chose to send a messenger from among the very people he was sent to, someone who spoke their language, understood their culture, and shared their experiences. This made the message more relatable and removed any excuse for rejection. The Prophet Ibrahim (ﷺ) had prayed for this very messenger centuries earlier, as mentioned in Surah Al-Baqarah (2:129).",
    "reciting to them His revelations": "The Prophet's first duty was to convey the verses of Allah to the people. He would recite the Quran to them—the direct words of Allah revealed through Angel Jibreel. This recitation was not just reading; it was a transformative experience that touched hearts and changed lives. The Quran's beauty, eloquence, and profound message captivated listeners and continues to do so today.",
    "purifying them": "The Prophet (ﷺ) purified people both outwardly and inwardly. He cleansed their hearts from the diseases of polytheism, arrogance, hatred, and immorality. He taught them to purify their souls through worship, good character, and righteous deeds. Before Islam, the Arabs engaged in practices like burying daughters alive, constant tribal warfare, and idol worship. The Prophet transformed them into a noble, just, and God-conscious community.",
    "and teaching them the Book and wisdom": "Beyond just reciting, the Prophet (ﷺ) explained the Quran's meanings and taught people how to apply it in their daily lives. The 'wisdom' (hikmah) refers to the Sunnah—the Prophet's teachings, actions, and approvals—which show us the practical application of Quranic principles. For example, the Quran commands us to pray, but the Prophet taught us exactly how to pray.",
    "for indeed they had previously been clearly astray": "Before the Prophet's mission, the Arabs were in obvious misguidance. They worshipped hundreds of idols, committed grave injustices, had no unified moral code, and lived in ignorance (jahiliyyah). This verse highlights the tremendous transformation that Islam brought—taking people from darkness into light, from misguidance to guidance."
  },
  3: {
    "along with others of them who have not yet joined them in faith": "The Prophet's mission was not limited to just the Arabs of his time. This verse indicates that his message would reach future generations and other nations who would also benefit from his teachings. When this verse was revealed, the companions asked the Prophet (ﷺ) who these 'others' were. He placed his hand on Salman Al-Farisi (a Persian companion) and said: 'If faith were near the Pleiades (a distant star cluster), men from among these would attain it.' This hadith (found in Sahih Bukhari and Muslim) shows that Islam would spread to non-Arabs, including the Persians and beyond. Every Muslim who came after the first generation is included in this verse—we are all beneficiaries of the Prophet's mission.",
    "For He is the Almighty, All-Wise": "Allah repeats these two names to emphasize that sending this messenger was an act of His supreme power and perfect wisdom. It was through His might that He established Islam despite all opposition, and it was through His wisdom that He chose the right messenger, the right time, and the right message for all of humanity."
  },
  4: {
    "This is the favour of Allah": "The sending of Prophet Muhammad (ﷺ) and the guidance of Islam is a tremendous favor from Allah. Being guided to Islam, having the Quran, and being part of the Prophet's ummah (community) is not something we earned through our own merit—it is purely Allah's grace and blessing upon us. We should never take this gift for granted.",
    "He grants it to whoever He wills": "Allah chooses whom He guides based on His infinite wisdom and knowledge. He knows who deserves guidance and who has a sincere heart seeking truth. This doesn't mean guidance is arbitrary; rather, Allah guides those who genuinely seek Him. As He says elsewhere: 'And those who strive for Us, We will surely guide them to Our ways' (29:69). However, ultimately, guidance is in Allah's hands, and we should always ask Him to keep us guided.",
    "And Allah is the Lord of infinite bounty": "Allah's favors and blessings have no limit. His generosity encompasses all things—material blessings like health, wealth, and family, and spiritual blessings like faith, guidance, and forgiveness. No matter how much He gives, His treasures never diminish. This should fill us with gratitude and motivate us to seek more of His bounty through worship and good deeds."
  },
  5: {
    "The example of those who were entrusted with observing the Torah but failed to do so": "Allah gave the Children of Israel the Torah through Prophet Musa (Moses, ﷺ) and commanded them to follow its teachings, uphold its laws, and live by its guidance. However, many of them failed to fulfill this responsibility. They had the scripture but didn't truly follow it. They read the words but didn't implement the meanings. They were proud of having the Book but ignored its commands. This refers specifically to those Jewish scholars and rabbis who knew the Torah contained prophecies about Prophet Muhammad (ﷺ) but refused to acknowledge him out of pride, jealousy, or worldly interests.",
    "is that of a donkey carrying books": "Allah gives a powerful and somewhat harsh example to illustrate the point. A donkey that carries heavy books on its back gains nothing from them—it doesn't understand what's written in them, cannot benefit from their knowledge, and is completely unaware of their value. The books are just a burden to the donkey, nothing more. Similarly, people who have religious knowledge but don't act upon it or don't follow its guidance are like this donkey. They carry the weight of responsibility but receive none of the benefits. This example is a wake-up call for anyone who has religious knowledge—memorizing Quran, studying Islamic sciences—but fails to practice what they learn. The Prophet (ﷺ) sought refuge from knowledge that does not benefit (Sunan Ibn Majah).",
    "How evil is the example of those who reject Allah's signs": "Allah expresses His displeasure at those who deny His revelations despite having access to them. How terrible is the state of someone who has the truth right in front of them but chooses to reject it! This is worse than someone who never received guidance at all. Knowledge brings responsibility, and rejecting truth after knowing it is a grave sin.",
    "For Allah does not guide the wrongdoing people": "Those who persist in wrongdoing—whether by rejecting Allah's signs, distorting His scripture, or failing to act upon divine guidance—will find themselves deprived of Allah's guidance. This is not because Allah is unable to guide them, but because they have chosen to close their hearts to the truth. Guidance is a gift that Allah gives to those who sincerely seek it and are willing to follow it. When someone continuously chooses wrongdoing over righteousness, they build barriers around their own hearts that prevent guidance from entering."
  },
  6: {
    "Say, O Prophet, \"O Jews!\"": "Allah instructs Prophet Muhammad (ﷺ) to address the Jewish community directly. This direct address shows the importance of the message that follows and creates a formal challenge that cannot be ignored.",
    "If you claim to be Allah's chosen people out of all humanity": "Some among the Jewish community at the time of the Prophet claimed exclusive closeness to Allah, believing they were His special favorites simply because of their lineage as descendants of Prophet Ibrahim (ﷺ) and Yaqub (Jacob, ﷺ). They felt entitled to Paradise regardless of their deeds. This sense of superiority led them to reject Prophet Muhammad (ﷺ), thinking guidance was only meant for their people. Allah challenges this claim directly.",
    "then wish for death, if what you say is true": "Here is the test of sincerity: if someone truly believes they are Allah's beloved and are guaranteed Paradise, they should have no fear of death. In fact, they should welcome it as a gateway to eternal bliss. The challenge is simple—if you are so sure of your special status with Allah, then wish for death and prove your sincerity. This is similar to the challenge Allah issued in Surah Al-Baqarah (2:94-96). A person who truly believes in the afterlife and is confident of their salvation would not fear leaving this temporary world for eternal happiness."
  },
  7: {
    "But they will never wish for that": "Allah declares with certainty that they will never take up this challenge. Despite their claims of being Allah's chosen ones, they will not wish for death. This is a prophecy that proved true—none of them accepted the challenge. Their refusal exposed the hollowness of their claims. Deep down, they knew their relationship with Allah was not what they publicly proclaimed.",
    "because of what their hands have done": "The reason for their reluctance is clear: they are aware of their sins and wrongdoings. They know they have rejected prophets, distorted scripture, and disobeyed Allah's commands. Their conscience bears witness against them. They fear facing Allah because they know they will have to answer for their deeds. This is a profound psychological insight—those who truly have a clear conscience and genuine faith do not fear meeting their Lord, while those burdened with unrepented sins dread the Day of Judgment.",
    "And Allah has perfect knowledge of the wrongdoers": "Nothing is hidden from Allah. He knows every sin committed, every good deed neglected, every intention in the heart. The wrongdoers may deceive people with their outward claims, but they cannot deceive Allah. This serves as a warning to all who commit injustice while pretending to be righteous."
  },
  8: {
    "Say, \"The death you are running away from will inevitably come to you\"": "The Prophet (ﷺ) is instructed to deliver this sobering reminder: no one can escape death. No matter how much people try to avoid it, deny it, or distract themselves from thinking about it, death will find them. Every soul shall taste death (3:185). Whether someone lives in a fortified palace or a humble hut, death reaches everyone. This is a universal truth that applies to all humanity, not just those being addressed. Running from death is futile—it is an appointment that cannot be postponed.",
    "Then you will be returned to the Knower of the seen and unseen": "After death comes resurrection and accountability. Every person will be brought back to Allah, Who knows everything—both what is apparent (the seen) and what is hidden (the unseen). He knows public actions and private thoughts. He knows what people displayed and what they concealed. No secret will remain hidden on that Day.",
    "and He will inform you of what you used to do": "On the Day of Judgment, every person will be shown a complete record of their deeds. Nothing will be forgotten or overlooked. Every good deed, every sin, every word spoken, and every intention harbored will be presented. This is not just information—it is a confrontation with one's own reality. The Prophet (ﷺ) said: 'Be mindful of Allah, and you will find Him in front of you' (Tirmidhi). Those who lived righteously will rejoice, while those who persisted in wrongdoing will face regret."
  },
  9: {
    "O believers!": "Allah addresses those who have faith directly, indicating that what follows is a command specifically for the Muslim community. This address creates a sense of identity and responsibility—because you believe, you must act accordingly.",
    "When the call to prayer is made on Friday": "The adhan (call to prayer) for Jumu'ah (Friday) prayer signals the beginning of this sacred obligation. When the muezzin calls out the adhan for the Friday prayer, Muslims are commanded to respond. Friday is the best day of the week according to the Prophet (ﷺ), who said: 'The best day on which the sun rises is Friday. On it Adam was created, on it he was admitted to Paradise, and on it he was expelled from it' (Sahih Muslim). It is a day of gathering, remembrance, and special blessings.",
    "then proceed diligently to the remembrance of Allah": "Muslims are commanded to go to the mosque for the Friday prayer. The word 'proceed' (fas'aw) means to go with purpose and determination, though not necessarily running—the scholars explain it means to go with your heart focused on worship while your body walks calmly. The 'remembrance of Allah' here refers to both the Friday sermon (khutbah) and the prayer itself. Listening to the khutbah is an integral part of the Friday obligation.",
    "and leave off your business": "Whatever worldly activities you are engaged in—buying, selling, trading, working—must be put aside when the call to Friday prayer is made. Business transactions conducted during this time are considered impermissible by many scholars. This command teaches us that worship takes priority over worldly pursuits. It's a weekly reminder that no matter how busy we are with making a living, we must never neglect our spiritual obligations.",
    "That is best for you, if only you knew": "Attending the Friday prayer and leaving worldly affairs is better for believers in every way—spiritually, socially, and even materially. Allah's blessings and barakah (divine blessing) in one's provision come through obedience to Him, not through disobedience. The Prophet (ﷺ) said: 'Whoever takes a bath on Friday, goes early to the mosque, walks and does not ride, sits close to the imam, listens attentively and does not engage in idle talk, will have for every step he takes the reward of a year's fasting and praying' (Abu Dawud, Tirmidhi). If people truly understood the value of Friday prayer, they would never miss it."
  },
  10: {
    "Once the prayer is over, disperse throughout the land": "After completing the Friday prayer, Muslims are free—and even encouraged—to return to their worldly activities. Islam is a balanced religion; it does not require people to abandon the world entirely. There is a time for worship and a time for work. This verse gives permission to resume business, travel, and other lawful activities after the prayer is concluded. Some companions used to stay in the mosque after prayer, so this verse encouraged them that going out to earn a living is also praiseworthy.",
    "and seek the bounty of Allah": "Go out and work to earn your livelihood, for this too is seeking Allah's bounty. Islam dignifies honest work and earning. The Prophet (ﷺ) said: 'No one has ever eaten any food that is better than eating what his hands have earned' (Bukhari). Seeking lawful provision is an act of worship when done with the right intention. The 'bounty of Allah' includes both material provision and spiritual rewards that come from engaging in beneficial activities.",
    "And remember Allah often": "While engaging in worldly activities, believers should not forget Allah. Remembrance of Allah should permeate all aspects of life—while working, traveling, buying, selling, and in every situation. This is achieved through keeping the tongue moist with dhikr (remembrance), being conscious of halal and haram in transactions, and maintaining a heart connected to Allah even while hands are busy with the world. The Prophet (ﷺ) used to remember Allah at all times (Sahih Muslim).",
    "so you may be successful": "True success (falah) in this life and the hereafter comes from balancing worldly responsibilities with constant remembrance of Allah. Success is not just material prosperity; it is achieving Allah's pleasure, entering Paradise, and being saved from Hellfire. Those who remember Allah frequently, attend to their prayers, and earn their living lawfully—these are the truly successful people."
  },
  11: {
    "When they saw the fanfare along with the caravan, they almost all flocked to it": "This verse was revealed regarding a specific incident. While the Prophet (ﷺ) was delivering the Friday sermon, a trade caravan arrived in Medina with much noise and commotion—drums beating and announcements being made. The people of Medina, eager to buy goods (as caravans were infrequent and supplies were needed), rushed out of the mosque to see and buy from the caravan. According to narrations, only about twelve people remained with the Prophet (ﷺ). This shows how even the companions, despite their high status, were human and sometimes made mistakes. The verse gently corrects this behavior.",
    "leaving you, O Prophet, standing on the pulpit": "The Prophet (ﷺ) was left standing alone on the minbar (pulpit), still delivering his sermon. This was indeed a hurtful and disrespectful situation, though unintentional. The companions didn't mean to disrespect the Prophet; they were caught up in the excitement and the practical need for supplies. But Allah corrects them, teaching all Muslims for all time that nothing should take precedence over attending to the Prophet's teachings and the remembrance of Allah during prayer times.",
    "Say, \"What is with Allah is far better than amusement and merchandise\"": "The Prophet (ﷺ) is instructed to remind the people of this profound truth: the rewards, blessings, and provisions that come from Allah far exceed any temporary entertainment or business profit. The goods from a caravan are temporary and will perish; the rewards from attending the Friday prayer and listening to the sermon are eternal. The amusement of this world is fleeting; the joy of Paradise is everlasting. When we prioritize worldly gains over spiritual obligations, we are essentially trading something precious for something cheap.",
    "And Allah is the Best Provider": "Whatever provision people were hoping to get from that caravan, Allah is the ultimate source of all provision. He is Khayr ar-Raziqeen—the Best of Providers. If someone leaves a business opportunity for the sake of Allah and His worship, Allah will compensate them with something better. The Prophet (ﷺ) said: 'You will never leave something for the sake of Allah, but Allah will give you something better in return' (Ahmad). This verse reassures believers that their sustenance is not dependent on a single transaction or opportunity; it is guaranteed by Allah, and obeying Him never leads to loss."
  }
};