var tafsirData_42 = {
  1: {
    "Ḥâ-Mĩm": "These are among the mysterious letters (huroof muqatta'at) that appear at the beginning of certain surahs in the Quran. Their exact meaning is known only to Allah. These letters serve to capture the attention of the listeners and demonstrate that the Quran, though composed of the same Arabic letters people use daily, is a miraculous revelation that no human could produce. The Meccan pagans, despite being masters of the Arabic language, could not replicate even a single surah of this Book."
  },
  2: {
    "'Aĩn-Sĩn-Qãf": "These are additional mysterious letters that continue to emphasize the miraculous nature of the Quran. Together with 'Ḥâ-Mĩm,' they form a unique opening that distinguishes this surah. Some scholars suggest these letters remind us that while we understand much of the Quran, some knowledge remains with Allah alone, teaching us humility before His infinite wisdom."
  },
  3: {
    "And so you ˹O Prophet˺ are sent revelation, just like those before you": "The revelation you receive, O Muhammad, is not something new or strange. It follows the same divine tradition that Allah established with previous prophets like Noah, Abraham, Moses, and Jesus. This continuity proves that the message is from the same God and reassures the Prophet that he is part of a noble chain of messengers. It also answers those who questioned why Muhammad was receiving revelation—this is Allah's way with all His chosen prophets.",
    "by Allah—the Almighty, All-Wise": "This revelation comes from Allah who is Al-Aziz (the Almighty)—possessing absolute power that none can challenge, and Al-Hakeem (the All-Wise)—doing everything with perfect wisdom and purpose. His might ensures His message will be preserved and His wisdom ensures every word of the Quran serves a purpose. When you know the Quran comes from such a source, you trust it completely."
  },
  4: {
    "To Him belongs whatever is in the heavens and whatever is on the earth": "Allah is the absolute Owner of everything that exists—every star, every planet, every creature, every atom. Nothing exists outside His dominion. This ownership is not like human ownership which is temporary and limited. Allah's ownership means He created everything, sustains everything, and has complete authority over everything. Knowing this, why would anyone turn to anything other than Him for help or worship?",
    "And He is the Most High, the Greatest": "He is Al-Ali (the Most High)—elevated above all creation in His essence, His attributes, and His authority. He is Al-Azeem (the Greatest)—possessing infinite greatness that human minds cannot fully comprehend. Everything else, no matter how powerful it seems, is small and dependent compared to Him. This should fill our hearts with awe and motivate us to worship Him alone."
  },
  5: {
    "The heavens nearly burst, one above the other, ˹in awe of Him˺": "The vastness and magnificence of Allah is so immense that even the mighty heavens—enormous structures that seem unshakeable to us—are nearly splitting apart from the overwhelming awareness of His greatness. If the heavens themselves tremble in awe of Allah, how much more should we, as weak human beings, humble ourselves before Him? This powerful imagery teaches us the proper attitude toward our Creator.",
    "And the angels glorify the praises of their Lord": "The angels, who are noble and pure beings created from light, continuously praise and glorify Allah. They never tire, never become distracted, and never disobey. This is their nature and their joy. When we praise Allah in our prayers and daily lives, we join this cosmic symphony of worship.",
    "and seek forgiveness for those on earth": "Out of Allah's mercy, He has the angels pray for the forgiveness of those on earth. This shows Allah's immense care for humanity—He has assigned His noble angels to intercede for us! The Prophet ﷺ said that the angels spread their wings for the seeker of knowledge, pleased with what he does. Imagine having such pure beings praying for your forgiveness.",
    "Surely Allah alone is the All-Forgiving, Most Merciful": "This is a profound reassurance. Despite our sins and shortcomings, Allah is Al-Ghafoor (the All-Forgiving)—He covers sins and pardons them completely, and Ar-Raheem (the Most Merciful)—His mercy is endless for those who turn to Him. No sin is too great for His forgiveness if one sincerely repents. This should give hope to every sinner while also motivating them to seek His mercy."
  },
  6: {
    "As for those who take other protectors besides Him": "This refers to those who turn to idols, false gods, or anything other than Allah for protection, help, or worship. They believe these things can benefit or harm them independently. This is the fundamental error of polytheism—placing trust and devotion in created things that have no real power. Whether it was the stone idols of Mecca or anything people rely on today besides Allah, the mistake is the same.",
    "Allah is Watchful over them": "Allah sees everything they do, records every action, and knows every intention. Nothing escapes His knowledge. This is both a warning to the polytheists that they will be held accountable and a comfort to believers that Allah is aware of all injustice and will address it.",
    "And you ˹O Prophet˺ are not a keeper over them": "The Prophet's role is to deliver the message, not to force people to believe or to be responsible for their choices. This relieves the Prophet of the burden of their disbelief. Allah is essentially saying: your job is to warn, their choices are their own, and I am the One who watches over them. This principle applies to all who call others to Islam—we convey the message with wisdom and leave the results to Allah."
  },
  7: {
    "And so We have revealed to you a Quran in Arabic": "The Quran was revealed in clear Arabic so that the first recipients—the Arabs of Mecca—could understand it directly without translation. This was essential for the message to take root. Arabic was also chosen because of its richness and precision, making it perfect for conveying the nuances of divine guidance. This doesn't limit the Quran to Arabs; rather, it started with them and spread to all humanity.",
    "so you may warn the Mother of Cities": "The 'Mother of Cities' (Umm al-Qura) refers to Mecca, called this because it is the location of the Kaaba, the first house of worship built for humanity, and the spiritual center of the earth. The warning began there because Mecca was the heart of Arabia, and transforming it would transform the region.",
    "and everyone around it": "The message was not limited to Mecca but extended to all surrounding areas and, by extension, to the entire world. The Prophet ﷺ was sent as a mercy to all of mankind, not just to one city or one people.",
    "and warn of the Day of Gathering—about which there is no doubt": "This is the Day of Resurrection when all of humanity, from the first person to the last, will be gathered before Allah for judgment. There is absolutely no uncertainty about this event—it will happen. Denying it doesn't change its reality. The certainty is emphasized because people tend to live as if this Day will never come.",
    "˹when˺ a group will be in Paradise and another in the Blaze": "On that Day, humanity will be divided into only two groups—no middle ground, no escape. One group will be admitted to Paradise (Jannah) to enjoy eternal bliss, and another will be cast into the Blaze (Sa'eer) to face eternal punishment. This stark division should motivate everyone to strive for the first group through faith and good deeds."
  },
  8: {
    "Had Allah willed, He could have easily made all ˹humanity˺ into a single community ˹of believers˺": "Allah has the absolute power to make everyone believe—He could have created humans without free will, like angels who never disobey. But that is not the purpose of this worldly test. Allah created humans with the ability to choose, and this choice is what gives faith its value. Forced belief has no merit; chosen belief demonstrates true devotion.",
    "But He admits into His mercy whoever He wills": "Allah's mercy and guidance are granted according to His wisdom. Those who sincerely seek truth, humble themselves, and strive for guidance—Allah opens their hearts to faith. This is not random; it is based on His perfect knowledge of who deserves His mercy. The Prophet ﷺ said: 'Allah does not wrong anyone; it is people who wrong themselves.'",
    "And the wrongdoers will have no protector or helper": "Those who persist in wrongdoing—particularly the wrong of associating partners with Allah or rejecting His guidance—will find themselves utterly alone on the Day of Judgment. The idols they worshipped, the powerful people they followed, the wealth they accumulated—none of it will help them. This is a severe warning to reconsider one's path while there is still time."
  },
  9: {
    "How can they take protectors besides Him?": "This is a question expressing astonishment and disapproval. How can rational people turn to powerless idols, false gods, or created beings for protection when the One True God is available to them? It's like someone dying of thirst next to a pure spring but choosing to drink from a muddy puddle. The logic of polytheism completely breaks down when examined.",
    "Allah alone is the Protector": "Only Allah (Al-Wali) is the true Protector who can genuinely help, support, and defend. Every other 'protector' people turn to is ultimately powerless. He protects not just from physical harm but also spiritually guides, supports, and cares for His servants.",
    "He ˹alone˺ gives life to the dead": "Allah alone has the power to bring the dead back to life—both in this world (as He did with certain individuals in previous nations) and on the Day of Resurrection when all will be raised. This power belongs exclusively to Him. No idol, no human, no force of nature can do this. This demonstrates His absolute power over the most fundamental aspect of existence—life and death.",
    "And He ˹alone˺ is Most Capable of everything": "There is nothing beyond Allah's ability. He is Al-Qadeer—the All-Powerful. When He decides something, He simply says 'Be' and it is. Recognizing this power should make it obvious why He alone deserves worship and why turning to anyone else is futile."
  },
  10: {
    "˹Say to the believers, O Prophet,˺ \"Whatever you may differ about, its judgment rests with Allah": "When believers disagree on any matter—whether religious rulings, interpretations of texts, or even worldly disputes—the final authority is Allah's Book and His Messenger's guidance. This principle protects the community from following personal opinions or cultural traditions that contradict divine guidance. Instead of arguing endlessly, Muslims are to return to the Quran and Sunnah for resolution. This maintains unity and ensures justice.",
    "That is Allah—my Lord": "The Prophet declares that Allah, the One who judges all matters, is his Lord. This is a testimony and a model for all believers to follow. Acknowledging Allah as our Rabb (Lord, Master, Sustainer) means accepting His authority in all aspects of life.",
    "In Him I put my trust": "Tawakkul (trust in Allah) means relying on Him completely while also taking appropriate action. It's not passive resignation but active faith—doing your part and trusting Allah with the outcome. The Prophet ﷺ exemplified this: he took every precaution but ultimately relied on Allah for success.",
    "and to Him I ˹always˺ turn": "Inaba means turning to Allah in repentance, devotion, and all matters. This is a continuous state, not a one-time act. A believer constantly returns to Allah—when they sin, they repent; when they succeed, they thank Him; when they face difficulty, they seek His help. This keeps the heart attached to its Creator."
  },
  11: {
    "˹He is˺ the Originator of the heavens and the earth": "Allah is Al-Fatir—the One who originated and created the heavens and earth from nothing, without any prior model or material. No one taught Him how to create; no one assisted Him. This original creation demonstrates power and creativity beyond human comprehension. We humans can only reshape existing materials; Allah creates from absolute nothing.",
    "He has made for you spouses from among yourselves": "Allah, in His wisdom and mercy, created human beings as pairs—male and female—so they may find comfort, love, and companionship in marriage. This is one of His greatest blessings to humanity. The spouse is described as coming 'from yourselves,' emphasizing the shared humanity and compatibility between spouses. Marriage is not just for procreation but for emotional and spiritual fulfillment.",
    "and ˹made˺ mates for cattle ˹as well˺—multiplying you ˹both˺": "Just as He created pairs among humans, Allah also created pairs among livestock (cattle, sheep, camels, goats). Through this pairing system, both humans and animals multiply and continue their species. This displays Allah's perfect design—a system that sustains life across generations. The livestock also serve human needs, providing food, transportation, and other benefits.",
    "There is nothing like Him": "This is one of the most important verses about Allah's nature. Nothing in creation resembles Allah in any way—not in His essence, His attributes, or His actions. When the Quran describes Allah as 'hearing' or 'seeing,' it is not like human hearing or seeing. He is utterly unique and beyond comparison. This protects us from the error of imagining Allah in human or created terms.",
    "for He ˹alone˺ is the All-Hearing, All-Seeing": "Allah hears everything—every whisper, every thought spoken aloud, every prayer, every cry for help—without any limitation. He sees everything—every action, every hidden deed, every movement in the depths of the ocean or the darkness of night. His hearing and seeing are perfect, comprehensive, and unlike any created being's perception. This should make us mindful of our words and actions, knowing He is always aware."
  },
  12: {
    "To Him belong the keys ˹of the treasuries˺ of the heavens and the earth": "Allah possesses the 'keys' (maqalid)—complete control over all the treasures and resources of the heavens and earth. Every blessing, every provision, every opportunity is in His hand. He opens doors of provision for some and restricts them for others according to His wisdom. No one can access these treasures except by His permission, and no one can withhold what He grants.",
    "He gives abundant or limited provisions to whoever He wills": "Allah expands provision (wealth, health, opportunities) for some people and restricts it for others. This is not random or unfair—it is based on His perfect wisdom. Sometimes abundance is a test (will the person be grateful or arrogant?), and sometimes restriction is a test (will the person be patient or despairing?). The Prophet ﷺ was often given little in terms of worldly wealth but was the richest in contentment. We should never judge someone's status with Allah by their material wealth.",
    "Indeed, He has ˹perfect˺ knowledge of all things": "Allah's decisions about provision are based on His complete knowledge of everything—past, present, and future. He knows what is best for each person. Sometimes what we want would actually harm us, and what we dislike would benefit us. Trusting Allah's distribution means trusting His knowledge, which far exceeds our limited understanding."
  },
  13: {
    "He has ordained for you ˹believers˺ the Way which He decreed for Noah": "The core religion (deen) given to you, O Muslims, is the same essential faith that was given to Prophet Noah—the first major messenger after Adam. This includes believing in One God, worshipping Him alone, and following His guidance. The fundamental message has never changed across thousands of years.",
    "and what We have revealed to you ˹O Prophet˺ and what We decreed for Abraham, Moses, and Jesus": "This same essential religion was given to Prophet Ibrahim (Abraham), Musa (Moses), and Isa (Jesus)—peace be upon them all. These great prophets, though separated by centuries and sent to different peoples, all preached the same core message: worship Allah alone. This demonstrates that Islam is not a new religion invented by Muhammad ﷺ but the continuation and completion of the eternal divine message.",
    "˹commanding:˺ \\"Uphold the faith, and make no divisions in it\\"": "The central command to all prophets and their followers was twofold: (1) Establish the religion—practice it fully, implement it in your lives, and uphold its principles; and (2) Do not divide into sects—remain united as one community. Sectarianism, where people break into groups that oppose each other over the same religion, is explicitly forbidden. The Prophet ﷺ warned that his ummah would split into many sects, and he encouraged Muslims to stick to the main body of believers.",
    "What you call the polytheists to is unbearable for them": "The message of pure monotheism (Tawheed)—that there is only One God worthy of worship—is extremely difficult for the polytheists to accept. It requires them to abandon the idols their ancestors worshipped, change their entire worldview, and give up the false sense of control that comes from having multiple gods for different needs. Yet this difficulty doesn't make the truth any less true.",
    "Allah chooses for Himself whoever He wills": "Allah selects certain individuals for special closeness to Him, for prophethood, or for exceptional guidance. This selection is His prerogative, based on His infinite wisdom and knowledge of who is worthy.",
    "and guides to Himself whoever turns ˹to Him˺": "While Allah chooses whom He wills, He also guides those who actively seek Him—who turn to Him sincerely (yunib). This shows the balance between divine will and human effort. If you genuinely seek Allah's guidance with humility and sincerity, He will guide you. The door is open to anyone who knocks with a sincere heart."
  },
  14: {
    "They did not split ˹into sects˺ out of mutual envy until knowledge came to them": "The division of previous religious communities into sects did not happen out of ignorance—it happened after clear knowledge came to them. They knew the truth, yet they divided anyway. Why? Out of 'baghy'—mutual envy, rivalry, and the desire to dominate. This is a sobering warning: even knowledge doesn't protect from division if hearts are corrupted by jealousy and arrogance. The scholars and leaders of past nations competed for worldly status and followers, and this tore their communities apart.",
    "Had it not been for a prior decree from your Lord for an appointed term": "Allah had already decreed that judgment would be postponed until the Day of Resurrection. He set an appointed time for the final reckoning, giving people time to live out their lives, make choices, and potentially repent.",
    "the matter would have certainly been settled between them ˹at once˺": "If not for this delay granted by Allah, He would have immediately destroyed those who divided and corrupted the religion. His restraint is actually mercy—giving people time to return to the truth. But this delay is not indefinite; the appointed time will come.",
    "And surely those who were made to inherit the Scripture after them are truly in alarming doubt about this ˹Quran˺": "The later generations of Jews and Christians who inherited the Torah and Gospel are in deep, troubling doubt about the Quran. Despite the clear signs that it is from Allah—matching the core message of their own scriptures—they remain uncertain. This doubt is 'muriyb'—suspicious and disturbing, not honest inquiry. Their confusion stems partly from the divisions and alterations that occurred in their own traditions over time."
  },
  15: {
    "Because of that, you ˹O Prophet˺ will invite ˹all˺": "Because of the divisions and confusion among previous religious communities, and because of the need for clear guidance, you, O Muhammad, are commanded to call all people—Arabs and non-Arabs, People of the Book and pagans—to the pure, unified religion of Allah. Your mission is universal and urgent.",
    "Be steadfast as you are commanded": "Remain firm and consistent on the straight path as Allah has commanded you. This steadfastness (istiqama) means not wavering in principles despite pressure, criticism, or temptation. The Prophet ﷺ said: 'Say: I believe in Allah, then be steadfast.' Consistency in faith and practice is essential, especially when facing opposition.",
    "and do not follow their desires": "Do not compromise the truth to please people or accommodate their wishes when those wishes contradict divine guidance. This is crucial for anyone calling others to Islam: the message must remain pure, not shaped by what people want to hear. Allah's guidance is not negotiable.",
    "And say, \\"I believe in every Scripture Allah has revealed": "The Prophet is commanded to declare his belief in all divine scriptures—the Torah, the Gospel, the Psalms, and other revelations—in their original, uncorrupted forms. This shows Islam's respect for previous revelations and its position as their continuation and confirmation, not their rejection.",
    "And I am commanded to judge fairly among you": "The Prophet's role includes being a just judge. Islam emphasizes absolute justice—even toward enemies, even when it goes against personal interest. This command applies to all Muslims: fairness and justice are non-negotiable principles.",
    "Allah is our Lord and your Lord": "This statement establishes common ground: Muslims and the People of the Book worship the same God, the Creator of all. This shared foundation should be a starting point for dialogue and understanding.",
    "We will be accountable for our deeds and you for yours": "Each person and community is responsible for their own actions. Muslims are not responsible for what others choose to believe or do, and vice versa. This releases people from trying to control others and focuses attention on personal accountability.",
    "There is no ˹need for˺ contention between us": "There is no point in endless arguing or hostility. The truth has been made clear; people are free to accept or reject it. Muslims are not to engage in hostile disputes but to convey the message with wisdom and then leave the judgment to Allah.",
    "Allah will gather us together ˹for judgment˺": "On the Day of Resurrection, all disputes will be resolved. Allah will gather everyone and make the truth absolutely clear. Those who were right will be vindicated, and those who were wrong will face the consequences.",
    "And to Him is the final return": "Everyone, without exception, will return to Allah. Death is not the end but a transition to standing before our Creator. This reality should influence how we live our lives today."
  },
  16: {
    "As for those who dispute about Allah after He is ˹already˺ acknowledged ˹by many˺": "Some people continue to argue against Allah, His religion, and His Messenger even after Islam has been accepted by many and its truth has been established. They see the evidence, they witness people accepting the message, yet they persist in opposition out of stubbornness, not genuine inquiry.",
    "their argument is futile in the sight of their Lord": "Their objections, however clever they may seem to themselves, are worthless before Allah. He is not impressed by sophistry or rhetorical tricks. Truth is truth regardless of how many people argue against it.",
    "Upon them is wrath": "Such people have earned Allah's anger by their stubborn rejection of clear truth. This is not arbitrary; they chose to fight against guidance despite knowing better.",
    "and they will suffer a severe punishment": "In the Hereafter, they will face a painful punishment for their willful opposition to truth. This should serve as a warning to anyone who considers arguing against obvious truth out of pride or self-interest."
  },
  17: {
    "It is Allah Who has revealed the Book with the truth": "Allah is the One who sent down this Quran containing absolute truth—truth about Himself, about creation, about the purpose of life, about the unseen, and about what awaits humanity. Every word of this Book is true; there is no falsehood in it from any direction.",
    "and the balance ˹of justice˺": "Along with the Book, Allah sent the 'Mizan' (balance)—the standard of justice and fairness by which all matters should be weighed. This includes laws, ethical principles, and the criteria for distinguishing right from wrong. Islam provides not just belief but a complete system of justice for individual and social life.",
    "You never know, perhaps the Hour is near": "No one knows exactly when the Day of Judgment will occur—not even the Prophet ﷺ. It could be very soon. This uncertainty is intentional; it keeps believers alert and prevents the complacency that would come from knowing the exact time. The Prophet ﷺ said: 'The Hour and I have been sent like these two,' holding up his two fingers close together, indicating how close the Day of Judgment is in the grand scheme of things."
  },
  18: {
    "Those who disbelieve in it ˹ask to˺ hasten it ˹mockingly˺": "The disbelievers, in their arrogance and mockery, challenge: 'If the Hour is real, bring it now!' They ask for it to be hastened as a way of denying it—thinking that since it doesn't happen immediately, it must be false. This is a foolish argument; Allah's timing is based on His wisdom, not human demands.",
    "But the believers are fearful of it": "In contrast, true believers are filled with fear and awe when they think about the Hour. They know its reality and understand that they will stand before Allah to account for every deed, every word, even every thought. This healthy fear (ishfaq) is not paralyzing terror but motivating concern that drives righteous action.",
    "knowing that it is the truth": "The believers' fear comes from certain knowledge—they know the Hour is absolutely true, as certain as the sunrise. This certainty shapes their lives, their priorities, and their choices.",
    "Surely those who dispute about the Hour have gone far astray": "Anyone who doubts, denies, or argues against the reality of the Day of Judgment is in deep misguidance (dalal ba'eed—literally 'far astray'). They have wandered so far from the truth that finding their way back requires serious effort and divine help. This is a warning to take the Hereafter seriously."
  },
  19: {
    "Allah is Ever Kind to His servants": "Allah is Al-Latif—subtle, gentle, and kind in ways we often don't even notice. His kindness operates in hidden ways, guiding events for our benefit, protecting us from unseen harms, and providing for us through unexpected means. A person might miss a flight only to later learn the plane crashed—this is Allah's subtle kindness. He cares for His servants with a gentleness that a loving parent can only partially mirror.",
    "He provides ˹abundantly˺ to whoever He wills": "Allah grants provision—which includes wealth, health, family, knowledge, and all blessings—to whomever He wills. His giving is based on His wisdom, not on who seems to deserve it most by human standards. Sometimes He tests with abundance, sometimes with restriction, but both are ultimately from His kindness.",
    "And He is the All-Powerful, Almighty": "Despite His gentleness and kindness, Allah is also Al-Qawiy (the All-Powerful) and Al-Aziz (the Almighty). His power is unlimited, and no one can resist His will. This combination of kindness and power is perfect—He has the ability to do anything, yet He chooses to be gentle with His servants. Those who harm His believers should remember His power."
  },
  20: {
    "Whoever desires the harvest of the Hereafter": "The word 'harvest' (harth) is beautifully used here—just as a farmer plants seeds expecting a future harvest, we plant deeds in this life expecting results in the Hereafter. Those who work and live with the Hereafter as their goal are like farmers investing in the best possible land.",
    "We will increase their harvest": "For those whose intention and focus is the eternal reward, Allah will multiply their harvest—increasing their good deeds, blessing their efforts, and granting them far more than they could have earned on their own. This multiplication can be ten times, seven hundred times, or even more, as Allah mentions elsewhere in the Quran.",
    "And whoever desires ˹only˺ the harvest of this world, We will give them some of it": "Those whose sole focus is worldly gain—wealth, status, pleasure—may indeed receive some of what they seek. Allah may grant them success in their worldly pursuits. But notice it says 'some of it' (minha)—they won't even get everything they want in this world, let alone the next.",
    "but they will have no share in the Hereafter": "The devastating consequence for those who only pursue worldly gains: they will have absolutely no portion of the eternal rewards of Paradise. They traded infinity for a few fleeting years. The Prophet ﷺ said: 'The world is the prison of the believer and the paradise of the disbeliever.' The believer sacrifices some worldly pleasures for eternal ones; the disbeliever enjoys now but loses forever."
  },
  21: {
    "Or do they have associate-gods who have ordained for them some ˹polytheistic˺ beliefs, which Allah has not authorized?": "This is a rhetorical question challenging the polytheists: Do their false gods have the right to make religious laws? Have these idols prescribed practices and beliefs? Of course not—they are lifeless, powerless objects or imaginary beings. Only Allah has the authority to legislate religion. Any religious practice or belief not authorized by Allah is innovation (bid'ah) at best and disbelief at worst. This applies to all false religions and man-made religious rules that contradict divine revelation.",
    "Had it not been for ˹prior˺ decree on Judgment, the matter would have certainly been settled between them ˹at once˺": "If Allah had not already decided to postpone final judgment until the Day of Resurrection, He would have immediately destroyed these wrongdoers for their fabricated religion. His delay is mercy, giving time for repentance, not approval of their actions.",
    "And surely the wrongdoers will suffer a painful punishment": "Those who practice and promote unauthorized religion—who legislate based on their desires rather than divine guidance—will face severe punishment. The word 'aleem' (painful) emphasizes the intensity of their suffering. This is a warning to all who invent religious practices or follow man-made ideologies as if they were divine."
  },
  22: {
    "You will see the wrongdoers fearful ˹of the punishment˺ for what they committed": "On the Day of Judgment, the same people who mocked the warnings, who arrogantly persisted in wrongdoing, will be trembling with fear. They will finally understand the reality of what they earned through their sins. The fear they should have felt in this life—which would have led to repentance—will overwhelm them when it's too late.",
    "but it will be inevitable for them": "Their punishment is 'waqi' bihim'—literally 'falling upon them.' It is certain, inescapable, and already decreed. No amount of fear at that moment will save them. This is why the time to fear and repent is now, in this life.",
    "whereas those who believe and do good will be in the lush Gardens of Paradise": "The complete opposite awaits the believers who combined faith with righteous action. They will be in 'rawdat al-jannat'—the luxuriant, beautiful meadows and gardens of Paradise. These are described with plural forms to indicate their vastness and variety.",
    "They will have whatever they desire from their Lord": "In Paradise, the believers will have everything they wish for—and more. Every pleasure, every joy, every satisfaction—without any pain, boredom, or dissatisfaction. The Prophet ﷺ described Paradise as containing what no eye has seen, no ear has heard, and no human heart has imagined.",
    "That is ˹truly˺ the greatest bounty": "This reward—Paradise with its eternal pleasures and the pleasure of Allah—is 'al-fadl al-kabir,' the greatest bounty possible. Nothing in this temporary world can compare. This is what the believers are working toward, and it makes every sacrifice in this life worthwhile."
  },
  23: {
    "That ˹reward˺ is the good news which Allah gives to His servants who believe and do good": "This promise of Paradise is 'bushra'—glad tidings, good news directly from Allah. It's not speculation or wishful thinking; it's a divine promise to those who believe and act righteously. This good news should fill believers with hope and motivation.",
    "Say, ˹O Prophet,˺ \\"I do not ask you ˹Meccans˺ for a reward for this ˹message˺": "The Prophet ﷺ is commanded to clarify that he seeks no payment, no wealth, no status in return for delivering the message. This is a mark of true prophethood—prophets never exploited their position for personal gain. This should silence those who accused him of preaching for worldly benefit.",
    "only honour for ˹our˺ kinship": "The only thing the Prophet asks is 'al-mawaddah fil qurba'—love and good treatment based on their family relationship. The Prophet ﷺ was from the Quraysh tribe, related to the Meccans by blood. He's essentially saying: 'At minimum, respect the family ties between us, even if you reject my message.' This is not asking for reward but for basic human decency.",
    "Whoever earns a good deed, We will increase it in goodness for them": "This is beautiful encouragement: any good deed a person performs, Allah will multiply and increase in reward. The more good you do, the more reward you receive, and it compounds. A single sincere act of charity could be multiplied into mountains of reward on the Day of Judgment.",
    "Surely Allah is All-Forgiving, Most Appreciative": "Allah is Al-Ghafoor (the All-Forgiving)—ready to forgive sins for those who repent. And He is Ash-Shakoor (Most Appreciative)—He appreciates even small acts of worship and rewards them generously. Imagine: the Creator of the universe appreciates your small good deeds! This should encourage us never to consider any good deed too small."
  },
  24: {
    "Or do they say, \\"He has fabricated a lie about Allah!\\"?": "Some of the Meccan pagans accused the Prophet ﷺ of inventing the Quran himself and falsely attributing it to Allah. This was a serious accusation—claiming that the Prophet was a deliberate liar who used God's name to deceive people. This verse addresses that accusation directly.",
    "˹If you had,˺ Allah would have sealed your heart, if He willed": "If the Prophet had truly been lying about Allah, Allah would have punished him by sealing his heart—removing guidance, blocking him from any good. The fact that the Prophet continued to receive revelation, to grow in faith, and to guide others is itself proof that he was truthful. Allah does not support liars.",
    "And Allah wipes out falsehood and establishes the truth by His Words": "This is a universal principle: falsehood is always temporary, no matter how powerful it seems. Allah will ultimately erase it. And truth, no matter how weak it appears initially, will be established by Allah's decree. History has proven this repeatedly—empires built on lies have crumbled while the truth of Islam has spread across the globe and endured for over 1400 years.",
    "He certainly knows best what is ˹hidden˺ in the heart": "Allah knows everything in the hearts of people—the sincerity of the Prophet, the jealousy of the accusers, the doubts of the skeptics. Nothing is hidden from Him. He knows who is genuinely seeking truth and who is merely arguing to protect ego or interests. This knowledge will be the basis of His judgment."
  },
  25: {
    "He is the One Who accepts repentance from His servants": "Despite how much people sin, Allah is always ready to accept their repentance. The door of tawbah (repentance) is always open until the sun rises from the west or until death approaches. This is tremendous hope for anyone burdened by past mistakes. The Prophet ﷺ said: 'Allah extends His hand at night so that the sinner of the day may repent, and extends His hand during the day so that the sinner of the night may repent.' No sin is too great for Allah's forgiveness if one sincerely repents.",
    "and pardons ˹their˺ sins": "Not only does Allah accept repentance, but He also 'pardons' (ya'fu)—He completely erases the sin as if it never happened. Some scholars say true repentance turns bad deeds into good deeds. This is the generosity of Allah—He doesn't just forgive, He honors the repentant person.",
    "And He knows whatever you do": "This is both a warning and a comfort. A warning: you cannot hide anything from Allah, so why persist in sin? A comfort: Allah knows your struggles, your genuine efforts to improve, your internal battles against temptation. He sees the good you do secretly, and He will reward it."
  },
  26: {
    "He responds to those who believe and do good": "Allah answers the prayers and supplications of believers who combine faith with righteous action. This response isn't always in the way we expect—sometimes He gives what we ask, sometimes He gives something better, and sometimes He saves the reward for the Hereafter. But He always responds. The Prophet ﷺ said: 'No Muslim makes a supplication except that Allah gives him what he asks, or averts from him an equivalent harm, or stores it for him as a reward in the Hereafter.'",
    "and increases their reward out of His grace": "Beyond just answering their prayers and rewarding their deeds, Allah adds to their reward from His own grace (fadl). This is a bonus, an extra gift that they did not earn—simply because of Allah's generosity. The believers' rewards are never just what they 'deserve'; they are always multiplied and enhanced by divine kindness.",
    "As for the disbelievers, they will suffer a severe punishment": "In stark contrast, those who reject faith and die in that state will face a severe, painful punishment. There is no 'fade' (grace) for them in the Hereafter because they rejected the very source of that grace. This isn't cruelty; it's justice. They were given countless opportunities, clear signs, and an entire lifetime to turn to Allah, but they chose to reject Him."
  },
  27: {
    "Had Allah given abundant provisions to ˹all˺ His servants, they would have certainly transgressed throughout the land": "If Allah gave everyone unlimited wealth and resources, most people would become arrogant, oppressive, and corrupt. Human nature often turns abundance into a source of pride and transgression. We see this pattern repeatedly—when people become very wealthy without spiritual grounding, they often become tyrants, exploit others, or indulge in every forbidden pleasure. Pharaoh, Qarun (Korah), and many others are examples of how excessive wealth led to corruption. Allah, knowing human weakness, limits provision as a protection.",
    "But He sends down whatever He wills in perfect measure": "Allah distributes provision with precise wisdom—'bi qadar' means in exact measure, perfectly calculated. Some receive more, some less, but each amount is tailored to what is best for that person's spiritual state and life circumstances. What seems like limitation is actually divine calibration. A person might need restriction to stay humble, while another might handle abundance well. Allah knows the perfect amount for each soul.",
    "He is truly All-Aware, All-Seeing of His servants": "Allah is Al-Khabeer (All-Aware)—knowing the hidden aspects of every person's character, and Al-Baseer (All-Seeing)—observing how each person would behave with more or less wealth. His distribution is based on complete knowledge, not randomness. When you feel financially restricted, remember that Allah sees what you cannot see about yourself. Perhaps abundance would have ruined you."
  },
  28: {
    "He is the One Who sends down rain after people have given up hope": "When drought strikes and the land is parched, when farmers have exhausted all hope and despair sets in, Allah sends the rain. The word 'ghayth' specifically refers to rain that comes as relief and rescue. This teaches us never to despair of Allah's mercy. Just when you think your situation is hopeless—financially, emotionally, spiritually—Allah can send relief from sources you never imagined. The Prophet ﷺ would make special prayers during drought, and when rain came, he would say: 'We have been given rain by the mercy of Allah.'",
    "spreading out His mercy": "Rain is described as Allah spreading His mercy across the land. It doesn't fall in just one spot; it spreads out, reviving vegetation, filling wells, giving life to everything. Similarly, Allah's mercy spreads into every aspect of our lives—health, family, opportunities—if we recognize it. Every blessing is a drop from His vast ocean of mercy.",
    "He is the Guardian, the Praiseworthy": "Allah is Al-Wali (the Guardian, Protector, Friend)—the One who takes care of His servants' affairs and watches over them with love. And He is Al-Hameed (the Praiseworthy)—deserving of all praise in His essence, His names, His attributes, and His actions. Everything He does is worthy of thanks, even when we don't immediately understand the wisdom behind it."
  },
  29: {
    "And among His signs is the creation of the heavens and the earth": "The existence of the heavens—with their countless stars, galaxies, and perfect order—and the earth—with its precise conditions for life—are among the clearest signs of Allah's existence and power. Scientists estimate there are over 100 billion galaxies, each containing billions of stars. This unimaginable vastness didn't create itself. Every aspect, from the distance of the sun to the composition of our atmosphere, points to a deliberate Creator.",
    "and all living beings He dispersed throughout both": "Allah has spread living creatures throughout the heavens and earth. On earth, life exists in the deepest oceans, the highest mountains, scorching deserts, and frozen poles—an incredible diversity of millions of species. The mention of 'both' (heavens and earth) also suggests life exists elsewhere in the universe, known fully only to Allah. This dispersal of life in such variety and balance is another proof of His creative power.",
    "And He is Most Capable of bringing all together whenever He wills": "The same Allah who created and dispersed all these creatures can easily gather them all on the Day of Resurrection. If creating them initially was easy for Him, reassembling them is even easier. This addresses those who doubt resurrection—if you accept that Allah created everything from nothing, why doubt He can recreate it? As He says elsewhere: 'The creation of the heavens and earth is greater than the creation of mankind, but most people do not know.'"
  },
  30: {
    "Whatever affliction befalls you is because of what your own hands have committed": "This profound verse teaches us to look inward when calamity strikes. Afflictions—illness, loss, hardship—often come as consequences of our own sins and misdeeds. This isn't to say every specific tragedy is punishment for a specific sin, but generally, our actions have consequences. The Prophet ﷺ said: 'A person is deprived of provision because of sins they commit.' This understanding should lead to self-reflection and repentance rather than blaming others or complaining against Allah.",
    "And He pardons much": "Despite our many sins deserving punishment, Allah forgives and overlooks most of them. If He punished us for everything we did wrong, we would be destroyed. This shows His immense mercy—He only allows some consequences to reach us as reminders, while forgiving far more. The Prophet ﷺ said: 'By the One in Whose hand is my soul, if you did not sin, Allah would replace you with people who would sin and then seek His forgiveness, and He would forgive them.' Allah's pardon far exceeds His punishment."
  },
  31: {
    "You can never escape ˹Him˺ on earth": "No matter where you run, no matter how you try to hide, you cannot escape Allah's power or evade His decree. The entire earth is His domain. This applies to both punishment in this life and in the Hereafter. Some criminals might escape human justice, but no one escapes divine justice. This should make us live with awareness that we are always in Allah's presence.",
    "nor do you have any protector or helper besides Allah": "Without Allah's protection, you are utterly vulnerable. No government, no army, no wealth, no powerful connection can truly protect you if Allah has decreed something. And conversely, if Allah protects you, nothing can harm you. The Prophet ﷺ taught Ibn Abbas: 'Know that if the whole nation were to gather together to benefit you, they would not benefit you except with what Allah has already written for you. And if they gathered to harm you, they would not harm you except with what Allah has already written against you.'"
  },
  32: {
    "And among His signs are the ships like mountains ˹sailing˺ in the sea": "Massive ships, towering like mountains or tall landmarks, sailing across the vast oceans are signs of Allah's power and blessing. These ships carry people and goods across waters that humans cannot cross otherwise. The fact that such heavy vessels float on water, propelled by winds Allah controls, demonstrates His creative design and the laws of nature He established. For the Arabs, who witnessed trading ships sailing to distant lands, this was a powerful reminder of Allah's provision and the miracle of maritime travel."
  },
  33: {
    "If He wills, He can calm the wind, leaving the ships motionless on the water": "Allah controls the winds that propel ships. If He wills, He can still the winds completely, leaving even the mightiest ships stranded in the middle of the ocean, helpless and unable to move. Sailors throughout history have experienced the terror of being becalmed—no wind, no movement, supplies dwindling. This reminds us that our technology and plans are all subject to Allah's will. He can disable our systems whenever He chooses.",
    "Surely in this are signs for whoever is steadfast, grateful": "These lessons in Allah's power are particularly understood by two types of people: the 'sabbar' (steadfastly patient)—those who endure hardships with patience and faith, and the 'shakur' (constantly grateful)—those who recognize and thank Allah for blessings. Patient people learn from difficulties that Allah is in control. Grateful people recognize that even favorable winds are gifts from Allah. Together, patience and gratitude are the twin responses a believer should have to every situation."
  },
  34: {
    "Or He can wreck the ships for what the people have committed": "Beyond just stilling the wind, Allah can cause the ships to be destroyed—through storms, collisions, or other disasters. These wrecks can be consequences of the sins people have committed, a form of divine punishment even in this world. How many ships have sunk throughout history, and how many lives lost at sea? Each incident is by Allah's permission and often connected to human actions in ways we may not fully understand.",
    "though He forgives much": "Yet again, Allah reminds us that He forgives more than He punishes. Despite people's sins, He doesn't send constant disasters. Most ships reach their destinations safely. Most travelers return home. This forbearance is Allah's mercy—giving people time to repent rather than punishing immediately for every transgression."
  },
  35: {
    "so those who dispute about Our signs may know that they have no refuge": "Those who argue against Allah's signs, who deny His power, or who mock His warnings should understand through these examples that there is absolutely no escape from Him. When a ship is in the middle of a stormy sea, where can anyone flee? There is no refuge, no safe place to hide from Allah. This realization should humble the arrogant and silence the disputers. On the Day of Judgment, this truth will be even more apparent—no one will have anywhere to run."
  },
  36: {
    "Whatever ˹pleasure˺ you have been given is ˹no more than a fleeting˺ enjoyment of this worldly life": "Everything we possess in this world—wealth, health, status, relationships, pleasures—is merely 'mata' (temporary enjoyment). Like luggage a traveler carries, it serves a purpose for the journey but is not the destination. The finest house, the most luxurious car, the highest position—all will be left behind at death. This perspective helps believers avoid being too attached to worldly things or too devastated when they're lost.",
    "But what is with Allah is far better and more lasting": "The rewards Allah has prepared in the Hereafter are infinitely superior (khayr) and eternal (abqa). Paradise is not temporary enjoyment but permanent bliss. Its pleasures don't fade, its beauty doesn't diminish, and its inhabitants never age or tire. Comparing worldly pleasures to Paradise is like comparing a drop to an ocean. Smart investors put their resources where returns are greatest—the Hereafter is the ultimate investment.",
    "for those who believe and put their trust in their Lord": "This superior, eternal reward is specifically for believers who have tawakkul (complete trust) in Allah. They believe in His promises, rely on His support, and aren't anxious about worldly outcomes because they know Allah is in control. This trust isn't passive—it's active faith combined with rightful action, then leaving the results to Allah."
  },
  37: {
    "who avoid major sins and shameful deeds": "True believers actively stay away from major sins (kaba'ir)—like shirk, murder, adultery, usury, stealing, false testimony—and shameful deeds (fawahish)—indecent acts that human nature finds repulsive. The Prophet ﷺ listed seven destructive sins and warned against them. Avoiding these sins requires constant vigilance, as they destroy one's relationship with Allah and corrupt society. This is not passive avoidance but active guarding of one's faith and character.",
    "and forgive when angered": "When these believers become angry—and everyone gets angry sometimes—they choose to forgive rather than retaliate or hold grudges. This is tremendous self-control. The Prophet ﷺ said: 'The strong person is not the one who can wrestle someone down. The strong person is the one who can control himself when angry.' Forgiving while angry is mentioned specifically because it's hardest to forgive in the heat of the moment, yet true believers master even this."
  },
  38: {
    "who respond to their Lord": "True believers answer Allah's call—when He commands, they obey; when He prohibits, they abstain; when He invites to faith, they believe. This responsiveness (istijaba) is the essence of being a Muslim (one who submits). They don't pick and choose which commands to follow based on convenience but respond to Allah comprehensively.",
    "establish prayer": "They don't merely pray occasionally but 'establish' (iqama) the prayer—performing it regularly, on time, with proper form, concentration, and humility. Prayer is the pillar of religion and the first thing people will be asked about on Judgment Day. The believers make it a central, non-negotiable part of their daily lives.",
    "conduct their affairs by mutual consultation": "This is the verse that gives the surah its name: Ash-Shura (Consultation). Believers consult each other in their affairs rather than acting dictatorially or independently when decisions affect others. This applies to families, communities, and governments. The Prophet ﷺ regularly consulted his companions, even though he had divine guidance. Consultation brings wisdom, prevents mistakes, creates buy-in, and honors the dignity of others. Islam was practicing participatory decision-making 1400 years ago.",
    "and donate from what We have provided for them": "They spend generously from their wealth, recognizing that everything they have is ultimately from Allah. This includes obligatory charity (zakat), voluntary charity (sadaqah), and supporting family and community needs. The phrase 'what We have provided them' reminds us we're just trustees, not ultimate owners—making generosity more logical and easier."
  },
  39: {
    "and who enforce justice when wronged": "When these believers are oppressed or treated unjustly, they don't simply accept injustice passively—they stand up for their rights and seek justice. Islam doesn't teach believers to be doormats. There is a balance: while forgiveness is praised (as will be mentioned), seeking legitimate justice is also a right. Standing against oppression is noble, and allowing oneself to be continuously wronged without response can encourage the oppressor to harm others."
  },
  40: {
    "The reward of an evil deed is its equivalent": "If someone wrongs you, you have the right to respond with an equivalent action—no more, no less. This establishes justice: eye for an eye, tooth for a tooth (in legal contexts with proper authority). You cannot exceed what was done to you. If someone insults you, you can respond with similar words, but not more severely. This prevents escalation and endless cycles of revenge.",
    "But whoever pardons and seeks reconciliation, then their reward is with Allah": "While retaliation is permitted, pardoning is superior. The one who forgives and works toward reconciliation (islah) receives a special reward directly from Allah. This reward is unspecified—left vague to indicate its greatness. Sometimes forgiving heals communities, reforms the wrongdoer, and elevates the forgiver spiritually. The Prophet ﷺ said: 'Charity does not decrease wealth; Allah increases the honor of one who forgives; and no one humbles himself for Allah's sake except that Allah raises him.'",
    "He certainly does not like the wrongdoers": "While pardoning is encouraged, this clause clarifies that Allah does not love those who initiate wrongdoing. The wrongdoer who started the injustice is not honored—only the victim who chooses to forgive is praised. This prevents misunderstanding: Islam isn't saying 'let wrongdoers do whatever they want.' The wrongdoer is still accountable; it's just that the victim gains more by forgiving."
  },
  41: {
    "There is no blame on those who enforce justice after being wronged": "Those who seek justice after being wronged—through proper legal channels or proportionate response—bear no sin or blame. They are exercising a legitimate right that Islam grants them. This clarification ensures that people understand seeking justice is not condemned. Whether taking a matter to court, demanding compensation, or defending oneself, the victim has every right to do so without feeling guilty."
  },
  42: {
    "Blame is only on those who wrong people and transgress in the land unjustly": "The true culprits—those who deserve blame, punishment, and accountability—are those who initiate oppression against people and spread corruption on earth without right. They are the aggressors, the tyrants, the oppressors who abuse their power to harm others. Islam firmly stands against oppression in all its forms.",
    "It is they who will suffer a painful punishment": "These oppressors will face severe punishment from Allah—both potentially in this life and certainly in the Hereafter. Oppression is one of the gravest sins. The Prophet ﷺ said: 'Beware of the supplication of the oppressed, for there is no barrier between it and Allah.' The cry of the wronged reaches Allah directly, and He responds."
  },
  43: {
    "And whoever endures patiently and forgives—surely this is a resolve to aspire to": "This verse praises the highest path: combining patience (sabr) with forgiveness. After explaining that retaliation is permitted and seeking justice is blameless, Allah now states that patience and forgiveness represent 'azm al-umur'—matters of great resolve, determination, and strong will. This is the path of the prophets and the righteous. It takes more strength to forgive than to retaliate. This doesn't mean accepting continuous abuse—context matters—but when one can afford to forgive without enabling further harm, it is the noble choice."
  },
  44: {
    "And whoever Allah leaves to stray will have no guide after Him": "When Allah withdraws His guidance from someone—due to their persistent rejection, arrogance, or love of misguidance—no one else can guide them. No teacher, no book, no experience can lead them to truth if Allah has abandoned them to their choices. This 'abandonment' is not arbitrary; it comes after repeated rejection of guidance. Allah says elsewhere: 'When they turned away, Allah turned their hearts away.' It's a consequence, not a random punishment.",
    "You will see the wrongdoers, when they face the torment, pleading, \\"Is there any way back ˹to the world˺?\\"": "On the Day of Judgment, when the wrongdoers finally see the punishment they had denied, they will desperately ask if there's any chance to return to the worldly life—to have another opportunity. They would give anything for another chance to believe and do good. But that door is closed forever. The time for action was in the world; now is only the time for consequences. This scene should terrify anyone who procrastinates on repentance."
  },
  45: {
    "And you will see them exposed to the Fire, fully humbled out of disgrace": "The wrongdoers will be brought before Hellfire, completely humiliated and broken. The arrogance they showed in the world will be replaced by total disgrace. Those who walked proudly in their disbelief, who looked down on believers, will now be utterly humbled—not the humility of worship, but the humiliation of punishment.",
    "stealing glances ˹at it˺": "They will look at the Fire with 'tarf khafi'—hidden, sidelong glances. They cannot bear to look at it directly because of its horror, yet they cannot look away entirely because it is their destination. This is the terrified glance of someone who knows what awaits them but wishes desperately it weren't real. The imagery is psychologically powerful—capturing the moment of horrified realization.",
    "And the believers will say, \\"The ˹true˺ losers are those who have lost themselves and their families on Judgment Day\\"": "The believers, witnessing this scene, will make a declaration: the real losers are not those who lost wealth or status in the world, but those who lost their own souls (condemned to Hell) and their families (either separated from them or their families also in Hell). Worldly loss is temporary and recoverable; this loss is eternal and total. The ultimate bankruptcy is spiritual bankruptcy on that Day.",
    "The wrongdoers will certainly be in everlasting torment": "Their punishment is 'muqeem'—permanent, established, never-ending. Unlike worldly punishments which eventually end, the punishment of the Hereafter for those who die in disbelief is eternal. This is not temporary detention but everlasting consequence."
  },
  46: {
    "They will have no protectors to help them against Allah": "All the allies, supporters, and protectors they relied on in the world will abandon them on that Day. Their idols will be powerless, their powerful friends will be busy with their own judgment, their wealth will not ransom them. Against Allah's judgment, there is no defender. This should make us question: who are we really relying on?",
    "And whoever Allah leaves to stray, for them there is no way": "This repeats and emphasizes the earlier point: once Allah withdraws guidance as a consequence of someone's persistent rejection, there is no alternative path to salvation. All roads to guidance are closed. This is the ultimate loss—to have the door to mercy permanently shut because one refused to walk through it when it was open."
  },
  47: {
    "Respond to your Lord before the coming of a Day from Allah that cannot be averted": "This is an urgent call: answer Allah's invitation to faith and obedience NOW, before a Day comes that nothing and no one can prevent or postpone. That Day—the Day of Judgment—is coming with absolute certainty. No power in existence can delay it even for a moment when Allah decrees it. The time to respond is while you're alive and capable of change.",
    "There will be no refuge for you then": "On that Day, there will be nowhere to hide, no shelter to run to, no protection to seek. The entire creation will stand exposed before Allah. Mountains will crumble, the sky will split, and every creature will face its Lord. The time to seek refuge in Allah's mercy is now, in this life.",
    "nor ˹grounds for˺ denial ˹of sins˺": "You will have no ability to deny your sins because they will all be recorded and presented as evidence. Your own body parts will testify against you. The angels who recorded your deeds will present their books. There will be no defense attorney, no technicalities, no plausible deniability. The only preparation is to repent now and accumulate good deeds."
  },
  48: {
    "But if they turn away, We have not sent you ˹O Prophet˺ as a keeper over them": "If people reject the message after hearing it clearly, the Prophet is not responsible for their choices. He was not sent to force people to believe or to guard them from their own decisions. This relieves the Prophet of the anguish of others' disbelief—he did his part.",
    "Your duty is only to deliver ˹the message˺": "The Prophet's responsibility—and by extension, every caller to Islam—is simply to convey the message clearly and completely (balagh). The results are in Allah's hands. Success in da'wah is not measured by how many people accept, but by how faithfully the message was delivered. This protects callers from despair when people reject the truth.",
    "And indeed, when We let someone taste a mercy from Us, they become prideful ˹because˺ of it": "When Allah blesses humans with good things—health, wealth, success—many become proud and attribute it to their own merit. They forget the Giver and become arrogant. 'I earned this,' they think, forgetting that every blessing is from Allah. This pride is a spiritual disease that blinds people to their dependence on their Creator.",
    "But when afflicted with evil because of what their hands have done, then one becomes totally ungrateful": "When difficulties strike—often as consequences of their own sins—the same people become utterly ungrateful, complaining, questioning, even denying Allah's goodness. They remember Allah only to blame Him. This is the sad reality of human nature: proud when blessed, ungrateful when tested. The believer strives to be thankful when blessed and patient when tested."
  },
  49: {
    "To Allah ˹alone˺ belongs the kingdom of the heavens and the earth": "Allah is the absolute sovereign over all existence. The heavens with their vastness and the earth with all it contains belong entirely to Him. He owns it, rules it, and controls it without any partner. No one shares His dominion or challenges His authority.",
    "He creates whatever He wills": "Allah's creative power is unlimited and unrestricted. He creates what He wants, how He wants, when He wants. This applies to everything—the laws of nature, the variety of creatures, and each individual human being with their unique circumstances.",
    "He blesses whoever He wills with daughters": "Having daughters is described as a gift (hiba) from Allah. This directly challenged the pre-Islamic Arab culture that viewed daughters as a burden and sometimes buried them alive. Allah puts daughters first in the list, honoring them and correcting the jahili (pre-Islamic) mentality. The Prophet ﷺ said: 'Whoever raises two daughters properly will be close to me in Paradise like this'—and he joined his two fingers together.",
    "and blesses whoever He wills with sons": "Sons are also a gift from Allah, not something humans 'produce' on their own. Whether one has sons or daughters is entirely in Allah's hands—no amount of technology, preference, or effort can override His will."
  },
  50: {
    "or grants both, sons and daughters, ˹to whoever He wills˺": "Some people are blessed with both sons and daughters. This is also from Allah's wisdom and distribution. A family might have sons, then daughters, then more sons—all according to Allah's plan, not human planning.",
    "and leaves whoever He wills infertile": "Some couples are unable to have children despite their desire and efforts. This too is Allah's decree. Rather than seeing infertility only as a trial, we should understand it within this list of Allah's gifts—He is the one who decides, and His decision is based on His wisdom and what is ultimately best. Many prophets were tested with delayed or no children for portions of their lives (like Zakariya and Ibrahim).",
    "He is indeed All-Knowing, Most Capable": "Allah's decisions about who gets what kind of children (or no children) are based on His complete knowledge (Aleem) of what is best for each person, and His complete capability (Qadeer) to implement His will. We may not understand why we received what we received, but we trust His knowledge is greater than ours. Some people wouldn't handle sons well; others wouldn't handle daughters well; some would be harmed by having children at all. Allah knows."
  },
  51: {
    "It is not ˹possible˺ for a human being to have Allah communicate with them": "Direct, face-to-face conversation between Allah and humans in this life is not the way revelation works. Humans, in their current state, cannot bear such direct communication. When Musa asked to see Allah, he was told: 'You cannot see Me.' When the mountain received even a glimpse of Allah's manifestation, it crumbled. This establishes the transcendence and majesty of Allah.",
    "except through inspiration": "The first mode of divine communication is 'wahy'—inspiration or revelation cast directly into the heart and mind of the prophet. This is internal, without words being heard, yet it is certain knowledge from Allah. The Prophet ﷺ described this type of revelation as sometimes being like the ringing of a bell, which was the most intense form.",
    "or from behind a veil": "The second mode is Allah speaking to someone from behind a barrier, without the person seeing Allah. This is how Allah spoke to Musa at Mount Sinai—Musa heard Allah's words directly but did not see Him. This was a special honor given to Musa, earning him the title 'Kalimullah' (the one Allah spoke to).",
    "or by sending a messenger-angel to reveal whatever He wills by His permission": "The third and most common mode is through angel Jibreel (Gabriel), who brings the revelation from Allah to the prophet. Jibreel would come to Prophet Muhammad ﷺ, sometimes in human form, sometimes in his angelic form, conveying the exact words of Allah. This is how most of the Quran was revealed.",
    "He is surely Most High, All-Wise": "Allah is Al-Ali (the Most High)—elevated beyond direct access by His creation, and Al-Hakeem (the All-Wise)—choosing the mode of communication that is best suited for each situation. His transcendence doesn't mean He is distant in care—only that His nature is beyond what creation can directly encounter in this life."
  },
  52: {
    "And so We have sent to you ˹O Prophet˺ a revelation by Our command": "Allah sent down to Muhammad ﷺ a 'ruh' (spirit/revelation) by His command. The Quran is called 'ruh' (spirit) because just as the soul gives life to the body, the Quran gives spiritual life to hearts that were dead in ignorance and disbelief. This revelation came by Allah's direct command, not by any human effort or desire.",
    "You did not know of ˹this˺ Book and faith ˹before˺": "Before revelation came to him at age 40, the Prophet ﷺ did not know the detailed contents of this Book or the specifics of faith. He was known for his excellent character and rejection of idolatry, but the detailed knowledge of scripture and religious law came only through revelation. This proves the Quran is not his own composition—how could an unlettered man who never studied with scholars suddenly produce such a detailed, consistent, profound book?",
    "But We have made it a light, by which We guide whoever We will of Our servants": "The Quran is described as 'nur' (light) because it illuminates the darkness of ignorance, shows the path to salvation, and exposes the reality of this life and the next. Just as physical light reveals what was hidden in darkness, the Quran reveals spiritual truths that human intellect alone could never discover. Allah guides through this light whomever He wills—particularly those who sincerely seek guidance.",
    "And you are truly leading ˹all˺ to the Straight Path": "The Prophet ﷺ guides people to the Straight Path (Sirat al-Mustaqeem)—the path of truth, righteousness, and salvation. This doesn't contradict the idea that only Allah guides; rather, the Prophet is the means through which Allah's guidance reaches people. He guides by conveying the message, living the example, and calling people to Allah."
  },
  53: {
    "the Path of Allah": "This Straight Path is not just any path—it is specifically 'the Path of Allah.' It is the path He has ordained, the path that leads to Him, the path that reflects His commands and pleasure. There are many paths people follow, but only one leads to Allah's acceptance and Paradise.",
    "to Whom belongs whatever is in the heavens and whatever is on the earth": "Everything in existence belongs to Allah—He created it, He owns it, and He controls it. This is repeated throughout the surah to emphasize His absolute sovereignty. When we walk His path, we are aligning ourselves with the Owner of everything. When we deviate, we are rebelling against the One who owns us and all that surrounds us.",
    "Surely to Allah all matters will return ˹for judgment˺": "The surah concludes with a powerful reminder: every matter, every affair, every deed, every dispute will ultimately return to Allah for final judgment. Nothing is lost or forgotten. Every injustice will be addressed, every good deed rewarded, every question answered. This is both a warning to those who wrong others and a comfort to those who suffer—Allah will settle all accounts. Our job is to live in awareness of this return, preparing to meet our Lord with a sound heart and a record of faith and good deeds."
  }
};