var tafsirData_56 = {
  1: {
    "When the Inevitable Event takes place": "This refers to the Day of Judgment, which is called 'Al-Waqi'ah' (The Inevitable Event) because it will absolutely occur without any doubt. Allah uses this powerful name to emphasize that this Day is coming with certainty, just as surely as the sun rises. No one can stop it, delay it, or escape it. The Prophet Muhammad (peace be upon him) said: 'Whoever wishes to see the Day of Judgment as if he is seeing it with his own eyes, let him recite: When the sun is wrapped up (Surah 81), When the sky breaks apart (Surah 82), and When the sky has split (Surah 84).' This shows how vivid the Quran's descriptions of that Day are."
  },
  2: {
    "then no one can deny it has come": "When the Day of Judgment arrives, there will be no possibility of denial or rejection. Unlike today, where some people doubt the resurrection, on that Day the reality will be so clear and overwhelming that denial becomes impossible. Everyone will witness it with their own eyes. This is similar to how no one can deny the sun when it is shining brightly above them. The disbelievers who mocked the idea of resurrection will have no choice but to accept what they once rejected."
  },
  3: {
    "It will debase ˹some˺ and elevate ˹others˺": "This Day will completely reverse the status of people. Those who were arrogant, wealthy, and powerful in this world but rejected faith will be humiliated and brought low. Meanwhile, those who were humble believers, perhaps poor or oppressed in this life, will be raised to the highest honors. Think of a proud king who oppressed people—on that Day he may be among the lowest. And think of a poor righteous person who was looked down upon—on that Day they may be among the most honored. This is the ultimate justice of Allah."
  },
  4: {
    "When the earth will be violently shaken": "The earth that we walk on, which feels so stable and firm, will shake with an intensity never experienced before. This will not be like ordinary earthquakes that affect certain regions—this shaking will encompass the entire earth. Everything built upon it will collapse. Allah describes this in another verse: 'When the earth is shaken with its [final] earthquake' (Quran 99:1). Imagine the most powerful earthquake multiplied countless times—that is what this Day will bring."
  },
  5: {
    "and the mountains will be crushed to pieces": "The mighty mountains, which seem eternal and unshakeable to us, will be completely crushed and broken apart. These same mountains that humans cannot move or destroy will crumble like they are nothing. This shows Allah's immense power. In this world, mountains symbolize strength and permanence, yet on that Day, they will be utterly powerless before Allah's command. This reminds us that nothing in creation, no matter how strong it appears, can withstand Allah's will."
  },
  6: {
    "becoming scattered ˹particles of˺ dust": "After being crushed, the mountains will become like fine dust particles floating in the air—like the tiny specks you see floating in a beam of sunlight coming through a window. These massive structures that took millions of years to form will be reduced to nothing more than scattered dust. Allah says elsewhere: 'And the mountains will be like wool, fluffed up' (Quran 101:5). This complete transformation shows that the entire physical world as we know it will be fundamentally changed."
  },
  7: {
    "you will ˹all˺ be ˹divided into˺ three groups": "On the Day of Judgment, all of humanity—from the first person ever created to the last—will be sorted into three categories. There will be no fourth group, and no one will escape this classification. This sorting will be based on their faith and deeds in this worldly life. Just as a teacher separates students based on their performance, Allah will separate people based on how they lived their lives. This division is final and determines each person's eternal destination."
  },
  8: {
    "the people of the right, how ˹blessed˺ will they be": "The first group mentioned is 'the people of the right' (Ashaab al-Maymanah). They will receive their records of deeds in their right hands, which is a sign of success and honor. The phrase 'how blessed will they be' is an expression of amazement at their wonderful state—their reward is so great that words cannot fully describe it. These are the believers who followed Allah's guidance, though they may have had some shortcomings. They will enter Paradise and enjoy eternal happiness."
  },
  9: {
    "the people of the left, how ˹miserable˺ will they be": "The second group is 'the people of the left' (Ashaab al-Mash'amah). They will receive their records in their left hands, which is a sign of failure and disgrace. The phrase 'how miserable will they be' expresses amazement at their terrible state—their punishment is so severe that it is beyond description. These are the disbelievers and those who rejected Allah's guidance. They will face the torment of Hellfire. The contrast between the two groups could not be more stark."
  },
  10: {
    "and the foremost ˹in faith˺ will be the foremost ˹in Paradise˺": "The third and most honored group is 'the foremost' (As-Sabiqoon). These are the people who were ahead of everyone else in faith, good deeds, and racing toward Allah's pleasure. Just as they were first in doing good in this world, they will be first in receiving rewards in the Hereafter. They include the prophets, the truthful ones, the martyrs, and those who excelled in worship and obedience. The Prophet (peace be upon him) and his closest companions like Abu Bakr are examples of this elite group. Being 'foremost' means they didn't just do the minimum—they strived to excel in every aspect of faith."
  },
  11: {
    "They are the ones nearest ˹to Allah˺": "The foremost will be granted the closest proximity to Allah in Paradise. This nearness is the greatest honor any created being can receive. It means they will have special access to Allah's mercy, pleasure, and blessings that others won't have. In this world, being close to a king brings honor and privilege—imagine then being close to the King of all kings, the Lord of the universe. The Prophet (peace be upon him) mentioned that the inhabitants of Paradise will see their Lord, and this is the greatest blessing of all."
  },
  12: {
    "in the Gardens of Bliss": "These foremost believers will dwell in 'Jannaat an-Na'eem'—Gardens of complete pleasure and delight. The word 'gardens' is plural, indicating multiple gardens of varying beauty and levels. 'Na'eem' means every type of blessing and comfort one can imagine—and far beyond what we can imagine. The Prophet (peace be upon him) said: 'In Paradise there is what no eye has seen, no ear has heard, and no human heart has ever imagined' (Bukhari and Muslim). These gardens represent the ultimate reward for those who gave their best in this life."
  },
  13: {
    "˹They will be˺ a multitude from earlier generations": "A large group of these foremost believers will come from the earlier nations and generations—those who believed in the previous prophets like Noah, Abraham, Moses, and Jesus (peace be upon them all). The early generations had many foremost believers because they accepted faith when it was new and faced severe persecution, yet remained steadfast. Their sacrifices and early acceptance of truth earned them this high rank. This includes the early companions of each prophet who supported them from the beginning."
  },
  14: {
    "and a few from later generations": "From the later generations—including the nation of Prophet Muhammad (peace be upon him) and those who came after—only a smaller number will reach this highest rank of 'the foremost.' This doesn't mean later believers are less worthy, but rather that achieving this top tier becomes more challenging over time as faith becomes tested in different ways. Some scholars say this refers to how, as time passes, trials and temptations increase, making it harder to maintain that exceptional level of faith. However, the 'few' from later generations who do achieve this rank will be equally honored."
  },
  15: {
    "˹All will be˺ on jewelled thrones": "These honored believers will recline on magnificent thrones (surur) that are woven and decorated with gold, precious gems, and jewels. The word 'mawdoonah' means intricately woven or decorated, suggesting craftsmanship beyond anything we can imagine. In this world, thrones symbolize royalty and honor—in Paradise, every one of the foremost will have their own royal seat. These are not ordinary chairs but seats of honor befitting the guests of the Most Generous Lord."
  },
  16: {
    "reclining face to face": "They will recline comfortably on these thrones, facing one another in friendly gatherings. This posture of reclining indicates complete relaxation, comfort, and the absence of any worry or need to work. Facing each other suggests beautiful social gatherings where they enjoy each other's company, share conversations, and experience the joy of companionship. Unlike in this world where friends are sometimes separated, in Paradise, believers will enjoy eternal togetherness. There will be no jealousy, ill feelings, or conflicts—only pure love and enjoyment of each other's presence."
  },
  17: {
    "They will be waited on by eternal youths": "Young servants will circulate among them, serving their every need. These servants (wildaan) are described as 'mukhalladoon'—eternally youthful, never aging or changing. They will always remain in the prime of youth, beautiful and energetic. This service is not like servitude in this world which can be degrading—rather, it is an honor and part of the perfect system of Paradise. Some scholars say these are special beings created for this purpose, while others say they are the children of believers who died young."
  },
  18: {
    "with cups, pitchers, and a drink ˹of pure wine˺ from a flowing stream": "These young servants will carry cups (akwaab—cups without handles), pitchers (abaareeq—vessels with handles and spouts for pouring), and goblets (ka's—drinking glasses) filled with pure wine from a continuously flowing stream. This wine of Paradise is nothing like the wine of this world. It flows from springs that never run dry. While wine in this world is forbidden because of its harmful effects, the wine of Paradise is pure and blessed, causing only pleasure and no harm whatsoever."
  },
  19: {
    "that will cause them neither headache nor intoxication": "Unlike the wine of this world, the wine of Paradise will not cause any headaches (sudaa') or loss of senses (yunzifoon—becoming intoxicated or losing one's mind). Worldly alcohol causes hangovers, health problems, loss of control, and leads people to commit sins and make foolish decisions. The wine of Paradise has none of these negative effects—only pure pleasure and enjoyment. This shows how everything in Paradise is perfected, with all the enjoyment and none of the harm."
  },
  20: {
    "˹They will also be served˺ any fruit they choose": "The inhabitants of Paradise will have access to any fruit they desire, whenever they want it. The word 'yatakhayyaroon' emphasizes personal choice—they can select whatever appeals to them at any moment. Unlike in this world where fruits are seasonal and some are rare or expensive, in Paradise every fruit is always available and within reach. The Prophet (peace be upon him) described that the fruits of Paradise hang low so that one can pick them while reclining. There are also fruits in Paradise that have no equivalent in this world."
  },
  21: {
    "and meat from any bird they desire": "In addition to fruits, they will have access to the meat of any bird they wish for. The word 'yashtahoon' means whatever they crave or desire—as soon as they think of a particular type of meat, it will be available for them. This shows that Paradise caters to every permissible desire of its inhabitants. Some narrations mention that birds in Paradise are of extraordinary beauty and taste. Imagine the finest, most delicious meal you've ever had—the food of Paradise surpasses it beyond comparison."
  },
  22: {
    "And ˹they will have˺ maidens with gorgeous eyes": "Among the rewards for the foremost will be 'Hoor al-'Een'—beautiful maidens with large, captivating eyes. The word 'Hoor' refers to the intense contrast between the white of their eyes and the deep black of their pupils, a description of extraordinary beauty. These are special beings created by Allah for Paradise, pure and devoted companions for the believers. This reward, while often discussed, is part of the complete joy Allah has prepared for those who earn His pleasure."
  },
  23: {
    "like pristine pearls": "These maidens are compared to 'preserved pearls' (lu'lu' maknoon)—pearls that have been protected and never touched or exposed to the elements. Preserved pearls have a special luster and purity because they haven't been handled or worn. This comparison emphasizes the purity, beauty, and untouched nature of these companions. Just as a protected pearl maintains its perfect shine, these maidens are created in a state of perfect beauty and purity."
  },
  24: {
    "˹all˺ as a reward for what they used to do": "All of these blessings—the thrones, the drinks, the fruits, the companions—are given as a direct reward for the good deeds these believers performed in their worldly lives. Nothing is given without reason; it is earned through faith, worship, patience, and righteous actions. This reminds us that every prayer we pray, every act of kindness we do, every temptation we resist is building our reward in Paradise. The Prophet (peace be upon him) said: 'Paradise is surrounded by hardships, and Hellfire is surrounded by desires' (Muslim). The effort made in this life leads to these eternal rewards."
  },
  25: {
    "There they will never hear any idle or sinful talk": "In Paradise, there will be no 'laghw' (idle, useless, or vain talk) and no 'ta'theem' (sinful speech, lies, backbiting, or anything that leads to sin). In this world, we are often surrounded by gossip, arguments, hurtful words, lies, and meaningless chatter that wastes time and sometimes leads to sin. Paradise is free from all of this negativity. The atmosphere is pure, peaceful, and uplifting. No one will say anything that causes discomfort or harm to another. This is part of what makes Paradise truly blissful—complete peace in every interaction."
  },
  26: {
    "only good and virtuous speech": "The only speech heard in Paradise will be 'Salaam, Salaam'—words of peace, blessings, and goodness. 'Salaam' means peace, safety, and well-being. Imagine every conversation being positive, every greeting being warm, and every word bringing joy. Allah says elsewhere that angels will greet the believers saying: 'Peace be upon you for what you patiently endured. How excellent is the final home!' (Quran 13:24). The repetition of 'Salaam' emphasizes the abundance and constancy of this peaceful speech. This is in stark contrast to the arguments and harsh words that trouble people in this world."
  },
  27: {
    "And the people of the right—how ˹blessed˺ will they be!": "Now Allah turns to describe the second blessed group—the people of the right (Ashaab al-Yameen). The repetitive, questioning style 'What are the people of the right?' expresses amazement at their blessed state, emphasizing that their condition is wonderful beyond easy description. While they may not reach the level of 'the foremost,' they are still successful, saved from Hell, and granted entry into Paradise. These are the general believers who fulfilled their basic obligations and avoided major sins, earning salvation and eternal happiness."
  },
  28: {
    "˹They will be˺ amid thornless lote trees": "They will enjoy lote trees (sidr) that are 'makhdood'—without thorns. The lote tree was known to the Arabs as a beneficial tree providing shade and fruit, but it typically has thorns. In Paradise, these trees have all the benefits without any of the discomfort. This symbolizes how everything in Paradise is perfected—all pleasure without any pain. Just as a rose without thorns would be ideal, these trees offer only comfort. This is a pattern in Paradise: every good thing is purified of any negative aspect."
  },
  29: {
    "clusters of bananas": "They will also have 'talh mandood'—banana trees (or some scholars say a type of acacia tree) laden with fruits arranged in layers. The word 'mandood' means piled up or layered, suggesting abundant clusters of fruit hanging heavily from the branches. The Arabs knew the beauty and value of such fruit-laden trees. Imagine trees so full of fruit that the branches bend with their weight, and this abundance never diminishes. Whatever specific fruit this refers to, the meaning is clear: endless, beautiful, abundant provision."
  },
  30: {
    "extended shade": "They will enjoy 'dhillin mamdood'—shade that is extended, continuous, and never-ending. In the Arabian desert, shade was precious and often limited as the sun moved across the sky. In Paradise, the shade is permanent, extending as far as one could want, providing constant comfort and coolness. The Prophet (peace be upon him) mentioned that in Paradise there is a tree so large that a rider could travel in its shade for a hundred years and not cross it (Bukhari). This perpetual shade represents eternal comfort and protection from any discomfort."
  },
  31: {
    "flowing water": "They will have 'maa'in maskoob'—water that is constantly flowing and pouring. This is not stagnant water that needs to be fetched from a well, but water that flows freely and abundantly wherever they wish. Water is the source of life, and having unlimited access to pure, flowing water represents the ultimate comfort and abundance. In the desert environment of Arabia, flowing water was the height of luxury. In Paradise, this luxury is the standard for all its inhabitants."
  },
  32: {
    "abundant fruit": "They will have 'faakihatin katheerah'—fruits in great abundance and variety. The word 'katheerah' emphasizes that the quantity is enormous, never running out, and the variety is endless. Unlike in this world where fruits can be expensive, rare, or out of season, in Paradise there is always more than enough for everyone. Every type of fruit imaginable, and types we cannot imagine, will be freely available at all times."
  },
  33: {
    "never out of season nor forbidden": "These fruits are 'la maqtoo'atin wa la mamnoo'ah'—never cut off (out of season or unavailable) and never forbidden (no restrictions on taking them). In this world, we wait for certain seasons to enjoy certain fruits, and sometimes fruits are forbidden due to belonging to someone else or being unripe. In Paradise, every fruit is always in season, always ripe, always available, and always permissible to take. There are no restrictions, no waiting, and no limitations. This represents complete freedom and abundance."
  },
  34: {
    "and elevated furnishings": "They will recline on 'furushim marfoo'ah'—furnishings (beds, couches) that are elevated and raised high. This elevation signifies honor and dignity. In ancient times, having an elevated seat was a sign of status and importance. These are not just ordinary beds but luxurious, raised platforms befitting honored guests. Some scholars say these beds are raised so high that if one wishes to sit on them, they lower themselves, indicating the miraculous nature of everything in Paradise. The believers will rest in comfort and honor."
  },
  35: {
    "Indeed, We will have perfectly created their mates": "Allah affirms that He has specially created (ansha'na) these companions—meaning the wives of Paradise—in a unique creation. The word 'inshaa' implies bringing something into existence in a new and special way. These companions are not simply transformed from their worldly state but are created in a new, perfect form specifically for Paradise. This applies to both the Hoor al-'Een (created for Paradise) and the believing women of this world who are recreated in perfection. This is a promise from the Creator Himself."
  },
  36: {
    "making them virgins": "Allah has made these companions 'abkaar'—virgins. This is part of their new, perfect creation. Even those who were married in this world will be restored to a state of virgin purity. The Prophet (peace be upon him) was asked about this verse and explained that the women of Paradise will be restored to this state, eternally. This emphasizes the complete renewal and perfection that Allah grants to the inhabitants of Paradise—everything is fresh, new, and perfect forever."
  },
  37: {
    "loving and of equal age": "These companions will be 'uruban atraaban.' 'Urub' means devoted, loving, and affectionate toward their husbands—they will have deep love and attraction. 'Atraab' means they will all be of equal age—in the prime of youth, around thirty-three years old according to some narrations, which is considered the peak of youth and beauty. There will be no age gaps or issues related to aging. Everyone will be at the perfect age, eternally youthful, and filled with love for their companions. This represents perfect compatibility and eternal romance."
  },
  38: {
    "for the people of the right": "All of these blessings—the perfect companions who are virgins, loving, and youthful—are specifically prepared 'li-ashaab al-yameen' (for the people of the right). This connects the reward to the recipients, emphasizing that these blessings are earned rewards for their faith and good deeds. The people of the right, though they may not have reached the level of the foremost, still receive magnificent rewards. This should motivate believers to strive to be at least among this blessed group."
  },
  39: {
    "˹who will be˺ a multitude from earlier generations": "A large group (thullah) of the people of the right will come from the earlier generations—the nations before Prophet Muhammad (peace be upon him). Every prophet's nation had righteous believers who, while perhaps not among the 'foremost,' were still faithful and obedient. These people earned their place among the people of the right through their faith in their respective prophets and their sincere worship of Allah. The communities of Noah, Abraham, Moses, Jesus, and all other prophets contribute to this blessed group."
  },
  40: {
    "and a multitude from later generations": "Importantly, unlike the 'foremost' where only 'a few' come from later generations, for the people of the right, 'a multitude' (thullah) will also come from later generations—including the nation of Prophet Muhammad (peace be upon him). This is encouraging news for us. While reaching the level of 'the foremost' is rare in later times, many people from the later generations can still achieve the status of 'people of the right' and enter Paradise. The door to this blessed group remains wide open for those who believe and do righteous deeds. This gives hope to every believer who strives for Allah's pleasure."
  },
  41: {
    "And the people of the left—how ˹miserable˺ will they be!": "Now Allah turns to describe the third group—the people of the left (Ashaab ash-Shimaal). The repetitive, questioning style 'What are the people of the left?' expresses shock and horror at their terrible state. While the same phrasing was used for the people of the right to express amazement at their blessings, here it expresses amazement at their misery and punishment. These are the disbelievers who rejected Allah, denied the prophets, and lived lives of sin and disobedience. Their fate is the complete opposite of the blessed groups."
  },
  42: {
    "˹They will be˺ in scorching heat and boiling water": "They will be surrounded by 'samoom'—an extremely hot, scorching wind that penetrates the body and burns from inside. This is not like any heat we experience on Earth; it is a punishment specifically designed by Allah. Additionally, they will have 'hameem'—boiling water so hot that it burns everything it touches. While the people of Paradise enjoy cool drinks and flowing streams, the people of the left have only burning wind and scalding water. The contrast is meant to make us reflect and choose wisely."
  },
  43: {
    "in the shade of black smoke": "Instead of the pleasant, extended shade enjoyed by the people of Paradise, these people will have 'shade' from 'yahmoom'—intensely black smoke. This is a bitter irony; they have shade, but it provides no relief. The smoke is thick, dark, and suffocating. Imagine being trapped under a canopy of choking black smoke with no escape. This 'shade' is itself a form of torment, not comfort. It blocks out light and fills the air with darkness and difficulty in breathing."
  },
  44: {
    "neither cool nor refreshing": "This shade is 'la baaridin wa la kareem'—neither cool nor pleasant. Normal shade provides coolness and comfort from the heat. But this smoke-shade offers nothing positive whatsoever. It is not cool to provide relief from the scorching heat, and it is not 'kareem' (noble, pleasant, or beneficial) in any way. Everything in Hell is designed to maximize suffering. Even things that appear to offer relief, like shade, turn out to be additional sources of torment. This is the reality of rejecting Allah's guidance."
  },
  45: {
    "Indeed, before this ˹torment˺ they were spoiled by luxury": "Allah explains why these people deserve such punishment. 'Before this'—meaning in their worldly lives—they were 'mutrafeen' (spoiled by excessive luxury and comfort). They had wealth, ease, and every worldly pleasure, but instead of being grateful to Allah and using these blessings in His obedience, they became arrogant and heedless. Their comfortable lives made them forget death, the Hereafter, and their responsibilities to their Creator. Wealth and comfort, when they lead to forgetfulness of Allah, become a curse rather than a blessing."
  },
  46: {
    "and persisted in the worst of sin": "They 'yuṣirroon' (persisted, insisted upon, stubbornly continued) in 'al-hinth al-'atheem' (the great sin). The greatest sin is shirk—associating partners with Allah—and also includes major sins like denial of resurrection, mockery of the prophets, and persistent disobedience without repentance. The key word is 'persisted'—they didn't just commit sins occasionally but stubbornly continued in them without remorse or intention to stop. When a person is warned but refuses to change, when they are given opportunities to repent but choose not to, they earn this severe punishment."
  },
  47: {
    "They used to ask ˹mockingly˺, \"When we are dead and reduced to dust and bones, will we really be resurrected?": "One of their greatest sins was denying the resurrection. They would mockingly ask: 'After we die and our bodies decompose into dust and scattered bones, will we really be brought back to life?' This question was not asked sincerely seeking knowledge—it was asked in mockery and disbelief. They thought resurrection was impossible and ridiculous. This denial allowed them to live without accountability, doing whatever they pleased since they believed there would be no Day of Judgment. Many people today have similar doubts, but the Quran repeatedly provides evidence for resurrection."
  },
  48: {
    "And our forefathers as well?": "They extended their mockery further: 'And even our ancient forefathers who died long ago—will they also be resurrected?' They found it even more absurd that people who died thousands of years ago, whose remains have completely disintegrated, could be brought back. This shows their limited understanding of Allah's power. They judged Allah's ability by their own limited capabilities. For humans, recreating someone from ancient dust seems impossible. But for Allah, Who created everything from nothing, recreating from existing matter is even easier—though nothing is 'difficult' for Allah."
  },
  49: {
    "Say, ˹O Prophet,˺ \"Most certainly, earlier and later generations": "Allah commands the Prophet Muhammad (peace be upon him) to respond to their mockery with a firm declaration. 'Indeed, the earlier ones (al-awwaleen)'—all those who came before, from Adam until now—'and the later ones (al-aakhireen)'—all who will come after until the Day of Judgment—everyone without exception will be gathered. This comprehensive statement leaves no room for doubt. No one escapes, no matter how long ago they lived or how completely their bodies have decayed. Allah's knowledge encompasses every particle of every person who ever existed."
  },
  50: {
    "will surely be gathered ˹together˺ for the appointed Day": "All these people 'lamajmoo'oon' (will certainly be gathered together) 'ilaa meeqaati yawmin ma'loom' (for an appointed Day that is known). This Day is fixed in Allah's knowledge; its timing is already decreed. The word 'majmoo'oon' emphasizes that everyone will be collected and assembled together—there will be no absentees. Just as a school gathers all students for an exam, Allah will gather all of humanity for the ultimate test—the Day of Judgment. This is a certainty, not a possibility."
  },
  51: {
    "Then you, O misguided deniers": "Allah directly addresses the wrongdoers, calling them 'ad-daaloon' (those who have gone astray, deviated from the truth) and 'al-mukadhdhiboon' (those who deny and reject the truth). These two descriptions capture their essence: they are lost because they refuse to follow guidance, and they are deniers because they reject what the prophets brought. This direct address makes the warning personal and immediate. It is as if Allah is speaking directly to every person who chooses denial and misguidance, warning them of what awaits."
  },
  52: {
    "will certainly eat from ˹the fruit of˺ the trees of Zaqqûm": "While the people of Paradise eat delicious fruits of their choosing, the deniers will be forced to eat from the tree of Zaqqum. This is a cursed tree that grows in the depths of Hell. The Prophet (peace be upon him) described that if a single drop from Zaqqum fell into the oceans of this world, it would spoil the lives of everyone on Earth (Tirmidhi). Allah describes it elsewhere: 'It is a tree that grows in the bottom of Hellfire. Its fruits are like the heads of devils' (Quran 37:64-65). This is their 'food'—not for nourishment but for increased torment."
  },
  53: {
    "filling up ˹your˺ bellies with it": "They will fill their stomachs with this Zaqqum. This is not a small taste but a forced filling of their bellies. Their hunger will be so severe that despite its horrific nature, they will be compelled to eat it until their stomachs are full. But this eating will bring no satisfaction or relief—only more pain, as this cursed food burns and tears through their insides. The image is one of complete desperation and suffering, eating something terrible out of extreme hunger, only to suffer more because of it."
  },
  54: {
    "Then on top of that you will drink boiling water": "After eating the burning Zaqqum, they will drink 'hameem'—water so hot that it is boiling. Their thirst after eating such horrible food will be unbearable, and the only drink available will be this scalding water. While the people of Paradise drink cool, pure beverages from flowing streams, the people of Hell drink boiling water that will scald their throats and melt their insides. Allah says elsewhere: 'They will be given water like murky oil, which will scald their faces' (Quran 18:29)."
  },
  55: {
    "and you will drink ˹it˺ like thirsty camels do": "They will drink this boiling water like 'al-heem'—camels that are extremely thirsty due to a disease that makes them drink excessively without ever being satisfied. Such camels drink and drink but their thirst is never quenched. Similarly, these people will drink the boiling water desperately, in huge quantities, but will never find relief from their thirst. It is a cycle of unending torment—the Zaqqum creates thirst, the boiling water fails to quench it, and the suffering continues forever. This vivid imagery warns us of the reality of Hell."
  },
  56: {
    "This will be their accommodation on the Day of Judgment": "This is their 'nuzul'—their welcome accommodation, their hospitality—on the Day of Judgment. The word 'nuzul' is typically used for the initial hospitality given to guests, implying this is just the beginning of their treatment. When a guest arrives, they are welcomed with food and drink—for these people, their 'welcome' is Zaqqum and boiling water. This is bitter irony and a severe warning. While the people of Paradise are welcomed with the finest of blessings, the people of Hell are 'welcomed' with the worst of punishments. And this is only the start of their eternal torment."
  },
  57: {
    "It is We Who created you. Will you not then believe ˹in resurrection˺?": "Allah now presents logical proofs for resurrection by pointing to His power demonstrated in creation. 'We created you'—this is an undeniable fact that even the disbelievers accepted. 'So why do you not believe?'—if Allah created you the first time from nothing, why is it hard to believe He can recreate you? The One who did something once can certainly do it again. This simple logic is presented to make people reflect. If you accept that Allah created you initially, it is inconsistent to deny that He can bring you back to life. The first creation is actually more remarkable than the recreation."
  },
  58: {
    "Have you considered what you ejaculate?": "Allah draws attention to human reproduction as proof of His creative power. 'Have you considered'—really thought deeply about—'what you emit' (the sperm during reproduction)? Every person comes from this humble fluid. This is something so common that we take it for granted, yet it is a profound miracle. From a tiny drop of fluid, a complete human being is formed—with eyes, ears, brain, heart, bones, and countless complex systems. This should make anyone reflect on the power of the Creator."
  },
  59: {
    "Is it you who create ˹a child out of˺ it, or is it We Who do so?": "Allah poses a rhetorical question: 'Do you create it (the human being), or are We the Creators?' Obviously, humans cannot create life. A couple may come together, but they have no power to transform a drop of fluid into a living, breathing, conscious human being. They cannot choose the gender, the features, or ensure that the child will even be formed properly. All of this is entirely in Allah's hands. Medical science can only observe and describe what happens; it cannot replicate or control the process of creating life. This proves Allah's exclusive power over creation."
  },
  60: {
    "We have ordained death for ˹all of˺ you, and We cannot be prevented": "Allah has decreed (qaddarna) death for every one of you. Death is not random or accidental—it is precisely planned by Allah for each person. Every person's time and manner of death is already determined. And 'We are not to be outdone' (ma nahnu bimasbooqeen)—no one can prevent Allah from doing what He wills. No human, no technology, no power can stop Allah's decree or escape His plan. This applies to death and equally to resurrection. If Allah decrees that you will be brought back to life, nothing can prevent that either."
  },
  61: {
    "from transforming and recreating you in forms unknown to you": "Allah has full power 'to replace you with others like you' (nubaddila amthaalakum) and 'to recreate you in forms you do not know' (nunshi'akum feema la ta'lamoon). This has two meanings: First, Allah can replace you with other people entirely if He wills—you are not indispensable. Second, Allah can recreate you in a completely new form for the Hereafter—a form you cannot currently comprehend or imagine. The bodies of the Hereafter will be different from our current bodies, suited for eternal life in Paradise or Hell. Allah's power is unlimited, and He is not restricted by what we consider possible."
  },
  62: {
    "You already know how you were first created. Will you not then be mindful?": "Allah reminds them: 'You already know the first creation (an-nash'at al-oola).' Everyone knows they were once nothing, then a baby, then grew to adulthood. This first creation happened—it's an observable fact. 'So why don't you remember and reflect (tadhakkaroon)?' If you acknowledge the first creation, the second creation (resurrection) should be even easier to accept. The Prophet (peace be upon him) mentioned that Allah says: 'The son of Adam denies Me, and he has no right to do so... As for his denying Me, it is his saying: He will not remake me as He made me at first—but the initial creation is not easier for Me than remaking him' (Bukhari). Reflection on our own existence should lead to faith in resurrection."
  },
  63: {
    "Have you considered what you sow?": "Allah presents another proof of His power by drawing attention to agriculture. 'Have you considered' (deeply reflected upon) 'what you cultivate and plant?' Farming is a daily activity that people often take for granted. A farmer plants seeds and expects crops to grow. But have they truly thought about the miracle involved? A small, dry seed is placed in the soil, and from it emerges a living plant that produces food. This process involves countless factors—soil composition, water, sunlight, temperature—all perfectly coordinated. Who arranges all of this?"
  },
  64: {
    "Is it you who cause it to grow, or is it We Who do so?": "Allah asks: 'Do you make it grow, or are We the ones who make it grow?' The farmer can only plant the seed and water it—but they have absolutely no power to make it germinate, sprout, develop roots, grow stems, produce leaves, flower, and bear fruit. All of this happens through Allah's will and design. Scientists can describe photosynthesis and plant biology, but they cannot create life in a seed or replicate the growth process from scratch. The farmer is merely a participant; the real Grower is Allah. This should humble anyone who thinks they are self-sufficient."
  },
  65: {
    "If We willed, We could simply reduce this ˹harvest˺ to chaff, leaving you to lament": "Allah reminds them of His complete control: 'If We willed, We could turn it into hutaaman (dry, broken chaff, useless debris).' After all the planting, watering, and waiting, Allah could destroy the entire harvest in an instant—through drought, pests, disease, storms, or any other means. 'And you would be left tafakkahoon'—either lamenting your loss or mockingly blaming each other, wondering what went wrong. This is a warning not to take Allah's blessings for granted. Every successful harvest is a gift from Allah that could be withheld at any moment."
  },
  66: {
    "\"We have truly suffered a ˹great˺ loss": "This is what the people would say if their crops were destroyed: 'Indeed, we are mughramoon'—we are ruined, we have suffered a great loss, we are burdened with debt. All their effort, investment, and hope would be gone. They would realize their complete dependence on Allah. Interestingly, people often only recognize their need for Allah when calamity strikes. This verse shows what would happen without Allah's continuous blessing—total loss and despair. It should make us grateful every day for the food we have."
  },
  67: {
    "In fact, we have been deprived ˹of our livelihood˺": "They would continue saying: 'Rather, we are mahroomoon'—we are completely deprived, we are denied everything. This is an even stronger expression of loss. First they say they've suffered loss, then they realize they've been completely deprived of any benefit. This is the reality of life without Allah's blessing—all human effort amounts to nothing. The farmer cannot guarantee a single grain of wheat without Allah's permission. This should make every person humble, grateful, and constantly aware of their dependence on Allah for every morsel of food they eat."
  },
  68: {
    "Have you considered the water you drink?": "Allah presents yet another proof of His power by directing attention to water. 'Have you considered' (truly reflected upon) 'the water that you drink?' Water is essential for life—without it, we cannot survive more than a few days. We drink it daily, use it constantly, yet rarely think about where it comes from or how it reaches us. Every glass of water is a miracle and a blessing from Allah. The human body is mostly water, and every living thing depends on it. This simple, clear liquid is one of Allah's greatest gifts to creation."
  },
  69: {
    "Is it you who bring it down from the clouds, or is it We Who do so?": "Allah asks: 'Did you bring it down from the clouds, or are We the ones who send it down?' Humans cannot create water or make it rain. The entire water cycle—evaporation, cloud formation, wind patterns, and precipitation—is controlled by Allah. Scientists can describe the process, but they cannot make it rain when they want or stop it when they don't. Cloud seeding and other technologies have extremely limited effectiveness compared to natural rainfall. Every drop of rain is sent down by Allah's command, at the time and place He decrees. This is power that no human possesses."
  },
  70: {
    "If We willed, We could make it salty. Will you not then give thanks?": "Allah could easily make all fresh water 'ujaajan'—bitter, salty, and undrinkable. The majority of water on Earth is already salty seawater, which humans cannot drink. The fresh water we depend on is a small fraction of Earth's water, and it comes purely by Allah's mercy. If Allah willed, even this fresh water could become salty or bitter, making life impossible. 'So will you not be grateful (tashkuroon)?' This question demands a response. Every sip of clean water should remind us to thank Allah. Gratitude is the least we can offer for such essential blessings that we often take completely for granted."
  },
  71: {
    "Have you considered the fire you kindle?": "Allah continues presenting proofs of His power by drawing attention to fire. 'Have you considered' (deeply reflected upon) 'the fire that you ignite and start?' Fire was essential for ancient peoples—for cooking, warmth, light, and protection. Even today, fire remains crucial for countless human activities. We strike a match or flip a switch and expect fire, but have we truly thought about where this ability comes from? The capacity for certain materials to burn and produce fire is something Allah designed into creation. Fire is both a blessing (when controlled for our benefit) and a reminder of punishment (Hellfire)."
  },
  72: {
    "Is it you who produce its trees, or is it We Who do so?": "Allah asks: 'Did you create the trees from which fire is produced, or are We the Creators?' In ancient times, fire was commonly made by rubbing certain types of wood together. These trees that produce fire-starting wood—who created them? Who put the property of combustibility into wood? Who designed the chemical process by which wood burns and releases heat and light? Humans did not create any of this. They simply discovered and used what Allah had already created and designed. Every campfire, every cooking flame, every source of warmth testifies to Allah's creative power and provision."
  },
  73: {
    "We have made it ˹as˺ a reminder ˹of the Hellfire˺ and a provision for the travellers": "Allah explains the dual purpose of fire. First, it is a 'tadhkirah' (reminder)—when you see fire and feel its heat, remember the Hellfire that awaits the disbelievers. The fire of this world is only a fraction of the heat of Hellfire. The Prophet (peace be upon him) said: 'Your fire is one-seventieth part of the Fire of Hell' (Bukhari and Muslim). Second, fire is a 'mataa'an lil-muqween' (provision for travelers and those in need). Travelers in the desert needed fire for warmth at night, for cooking, and for protection. Allah made fire both a spiritual reminder and a practical blessing."
  },
  74: {
    "So glorify the Name of your Lord, the Greatest": "After presenting all these proofs of Allah's power—in human creation, agriculture, water, and fire—the natural response is commanded: 'Glorify the name of your Lord, the Most Great (al-'Atheem).' Tasbeeh (glorification) means declaring Allah free from any imperfection, partner, or weakness. When you reflect on Allah's creative power in everything around you, the only appropriate response is to glorify Him. The Prophet (peace be upon him) recommended saying 'SubhanAllah' (Glory be to Allah) frequently, and said it is one of the most beloved phrases to Allah. This verse teaches us that reflection on creation should lead to worship of the Creator."
  },
  75: {
    "So I do swear by the positions of the stars": "Allah takes an oath by 'mawaqi' an-nujoom'—the positions or locations of the stars. Some scholars say this refers to where the stars set, others say it refers to their positions in the sky, and others say it refers to the stages in which the Quran was revealed. Stars were significant to the Arabs for navigation, marking seasons, and their sheer beauty. The positions and movements of billions of stars, each in its precise orbit, demonstrate Allah's perfect design and control. When Allah swears by something in His creation, it draws attention to its significance and serves as an introduction to an important statement."
  },
  76: {
    "and this, if only you knew, is indeed a great oath": "Allah emphasizes the magnitude of this oath: 'And indeed, it is an oath—if only you knew—most great ('atheem).' This is remarkable because Allah is highlighting the significance of His own oath. The positions of the stars are not a trivial matter—they represent the vastness of the universe, the precision of Allah's creation, and mysteries that humans are only beginning to understand. If people truly understood the magnitude of the cosmos and the stars, they would realize how significant this oath is. What comes after such a tremendous oath must be of the utmost importance."
  },
  77: {
    "that this is truly a noble Quran": "The object of this great oath is revealed: 'Indeed, it is a Quran most noble (kareem).' The Quran is described as 'kareem'—noble, generous, honorable, and precious. This word indicates that the Quran is from a noble source (Allah), contains noble guidance (the best teachings), and leads to noble outcomes (success in both worlds). The Quran is the greatest miracle given to Prophet Muhammad (peace be upon him), and it remains preserved and accessible to all of humanity. Its nobility is in its words, its meanings, its effects, and its origin."
  },
  78: {
    "in a well-preserved Record": "This noble Quran exists 'in a Book well-protected (maknoon).' This refers to the Preserved Tablet (al-Lawh al-Mahfooth), where the Quran is recorded and guarded in the heavens. The word 'maknoon' means hidden, protected, and safeguarded from any corruption or tampering. Before the Quran was revealed to Prophet Muhammad (peace be upon him), it was already preserved with Allah. And even after its revelation to Earth, Allah has guaranteed its preservation: 'Indeed, it is We who sent down the Reminder, and indeed, We will be its guardian' (Quran 15:9). No other scripture has this divine guarantee of preservation."
  },
  79: {
    "touched by none except the purified ˹angels˺": "This preserved record is 'touched by none except the purified ones (mutahharoon).' In the context of the Preserved Tablet, this refers to the angels who are pure and honored servants of Allah—they are the ones who handle this heavenly record. Some scholars also apply this to the physical Quran on Earth, deriving the ruling that one should be in a state of ritual purity (wudu) when touching the Quran, as a sign of respect for the sacred text. Either way, the verse emphasizes the sanctity and purity associated with Allah's words—it is protected from any impurity, whether physical or spiritual."
  },
  80: {
    "˹It is˺ a revelation from the Lord of all worlds": "The Quran is 'a revelation (tanzeel) from the Lord of all worlds (Rabb al-'Aalameen).' This clearly states the source of the Quran—it is not human poetry, not Muhammad's own composition, not borrowed from other sources—it is a direct revelation from Allah, the Lord and Sustainer of everything that exists. The word 'tanzeel' emphasizes that it was sent down from above, from Allah to Jibreel (Gabriel) to the Prophet (peace be upon him). When you read the Quran, you are reading the actual words of Allah, the Creator of the universe. This should inspire awe and reverence."
  },
  81: {
    "How can you then take this message lightly": "Allah rebukes those who are careless about the Quran: 'Is it this discourse (hadeeth) that you treat with mudahanah?' The word 'mudhinoon' comes from 'mudahanah' which means to be lax, careless, insincere, or to take something lightly. After knowing that this Quran is noble, preserved, pure, and from the Lord of all worlds—how can anyone be indifferent to it? How can people hear its verses and not take them seriously? This is a stern warning against complacency regarding the Quran. Many people acknowledge the Quran verbally but don't truly reflect on it, follow it, or give it the attention it deserves. This is a form of 'mudahanah' that is being criticized."
  },
  82: {
    "and repay ˹Allah for˺ your provisions with denial?": "Allah asks: 'And do you make your share (rizqakum) denial (tukadhdhiboon)?' This verse has been interpreted in several ways. One meaning is: 'Do you make your gratitude for Allah's provision to be denial of His message?' In other words, instead of thanking Allah for His blessings—including the blessing of the Quran—you respond with rejection and denial. This is the height of ingratitude. Another interpretation relates to the pre-Islamic practice where Arabs would attribute rain to stars rather than to Allah. Either way, the meaning is clear: responding to Allah's blessings with denial and rejection is deeply wrong. Every blessing should increase our faith and gratitude, not our arrogance and denial."
  },
  83: {
    "Why then ˹are you helpless˺ when the soul ˹of a dying person˺ reaches ˹their˺ throat": "Allah now presents a powerful challenge to the deniers by describing the moment of death. 'Why, when the soul reaches the throat (hulqoom)...' This refers to the final moments of death when the soul is being extracted and has reached the throat—the person is on the verge of death. This is a moment everyone will experience. At this critical moment, when life is slipping away, all the power, wealth, and technology in the world become useless. The person can do nothing to stop what is happening. This scene is set up to challenge human arrogance."
  },
  84: {
    "while you are looking on?": "At that moment, the family and loved ones are 'looking on (tanthuroon)'—watching helplessly as their loved one dies. They can see the person's life fading, the breathing becoming labored, the color draining from the face. Despite all their love and desire to help, they can do absolutely nothing to prevent death. Doctors, family members, friends—everyone stands powerless. This is a scene that plays out countless times every day around the world. It is a vivid reminder of human weakness and Allah's absolute control over life and death."
  },
  85: {
    "And We are nearer to such a person than you, but you cannot see": "Allah declares: 'And We are nearer to him than you, but you do not see.' This nearness is through Allah's angels who are present to take the soul—they are right there, closer to the dying person than any human, but invisible to human eyes. Some scholars also say this refers to Allah's nearness through His knowledge and power. At that moment, while family members watch helplessly from outside, Allah's angels are conducting the extraction of the soul from within. This invisible reality is happening constantly around us—we simply cannot perceive it with our limited senses."
  },
  86: {
    "Now, if you are not subject to Our Will ˹as you claim˺": "Allah challenges the deniers: 'If you are not subject to recompense (madeen)'—if you are truly independent of Allah, if you will not be held accountable, if you are not under Allah's authority as you claim—then prove it! The word 'madeeneen' comes from the same root as 'Deen' (Day of Judgment/recompense) and implies being subject to judgment and authority. The disbelievers lived as if they were not accountable to anyone, as if they were masters of their own fate. This challenge exposes their false sense of independence."
  },
  87: {
    "bring that soul back, if what you say is true": "The challenge is completed: 'Return it (the soul)—if you are truthful!' If you are truly independent and powerful, if there is no God controlling life and death, then bring the soul back into the body. Stop death from happening. Reverse what has occurred. This is an impossible challenge that exposes human powerlessness. No human being has ever been able to return a departed soul. All the medical advances in history cannot bring back a dead person. This unanswerable challenge proves that humans are completely subject to Allah's will, whether they acknowledge it or not. Death is the ultimate proof of human weakness and divine power."
  },
  88: {
    "So, if the deceased is one of those brought near ˹to Us˺": "Now Allah describes what happens to each of the three groups at the moment of death and beyond. First, 'if the dying person is among the muqarrabeen (those brought near to Allah)'—this is the first group mentioned earlier, the foremost, the elite of believers. These are the people who excelled in faith, worship, and good deeds throughout their lives. At their death, they receive immediate good news of their special status with Allah. The use of 'in kaana' (if he was) indicates that their status was determined by how they lived their lives before this moment."
  },
  89: {
    "then ˹such a person will have˺ serenity, fragrance, and a Garden of Bliss": "For the foremost (muqarrabeen), there will be 'rawh' (serenity, rest, peace, mercy), 'rayhaan' (fragrance, sweet-smelling plants, provision), and 'Jannatu na'eem' (Garden of Bliss). At the moment of death, instead of pain and fear, they experience peace and tranquility. They smell the fragrance of Paradise even as they leave this world. And ultimately, they are destined for the Gardens of Bliss—the highest levels of Paradise. The Prophet (peace be upon him) said that when the soul of a believer is taken, it comes out easily like water flows from a vessel, and the angels wrap it in shrouds from Paradise with fragrances from Paradise (Ahmad)."
  },
  90: {
    "And if the deceased is one of the people of the right": "Second, 'if the dying person is among the people of the right (ashaab al-yameen)'—the second blessed group of righteous believers. These are the good believers who may not have reached the level of the foremost but were still faithful and obedient to Allah. They fulfilled their duties and avoided major sins. At their death, they too receive good news, though their rank is below the foremost. Their path to Paradise is also assured, and they have nothing to fear."
  },
  91: {
    "then ˹they will be told,˺ \"Greetings to you from the people of the right.\"": "They will be greeted with 'Peace be upon you (salaamun laka), from the people of the right.' The angels will greet them with words of peace and reassurance. They will be told that they belong to the blessed group—the people of the right—and have nothing to worry about. This greeting of 'salaam' signifies safety, security, and peace. It is a confirmation at the moment of death that they have succeeded. Imagine the comfort of hearing this greeting as one leaves this world—knowing that eternal peace awaits. This is the reward for a life lived in faith and obedience."
  },
  92: {
    "But if such person is one of the misguided deniers": "Third, 'if the dying person is among the deniers (mukadhdhibeen), the astray (daaalleen)'—these are the people of the left, who rejected truth and wandered in misguidance throughout their lives. They denied Allah's signs, rejected the prophets, and refused to follow guidance despite having the opportunity. At their death, they face the terrible consequences of their choices. Note that they are described with two qualities: denial of truth (takdheeb) and being astray from the right path (dalaal). Both qualities together led to their destruction."
  },
  93: {
    "then their accommodation will be boiling water ˹to drink˺": "For the deniers, their 'nuzul' (welcoming accommodation, hospitality) will be 'hameem' (boiling, scalding water). Earlier in this surah (verse 56), this same word 'nuzul' was used sarcastically—while guests are normally welcomed with good food and drink, these people are 'welcomed' with boiling water. This is not hospitality but torment disguised in the language of hospitality, emphasizing the severity of their situation. Instead of the cool drinks and pure water of Paradise, they receive water so hot it burns everything it touches. This is the beginning of their eternal punishment."
  },
  94: {
    "and burning in Hellfire": "In addition to the boiling water, they will have 'tasliyatu jaheem'—burning in the blazing Hellfire. They will be made to enter and burn in the most intense fire. The word 'jaheem' refers to a blazing, fierce fire—one of the names used for Hell, indicating its extreme heat. This fire is not like any fire of this world; it is far more intense and it punishes without destroying, so the punishment continues eternally. This is the ultimate consequence for those who denied Allah's signs and lived in persistent disobedience. It is a sobering reminder for all who hear it."
  },
  95: {
    "Indeed, this is the absolute truth": "Allah concludes the surah with a powerful affirmation: 'Indeed, this is the truth of certainty (haqq al-yaqeen).' Everything that has been described in this surah—the three groups, the rewards of Paradise, the punishments of Hell, the proofs of Allah's power, the nobility of the Quran—all of this is 'haqq al-yaqeen,' the most certain truth. There is no doubt whatsoever in any of it. This is not speculation, mythology, or theory—it is absolute reality from the Creator who knows all things. The phrase 'haqq al-yaqeen' represents the highest level of certainty possible. Those who doubt these realities do so at their own peril."
  },
  96: {
    "So glorify the Name of your Lord, the Greatest": "The surah ends as it reached its middle point (verse 74)—with a command to glorify Allah: 'So glorify the Name of your Lord, the Most Great (al-'Atheem).' After hearing about the majesty of Allah's creation, the certainty of the Day of Judgment, the rewards for the righteous, the punishments for the wicked, and the absolute truth of the Quran—the only appropriate response is glorification of Allah. 'SubhaanAllah' (Glory be to Allah) should flow from our tongues and hearts. This repetition of the command to glorify Allah at both the middle and end of the surah emphasizes its importance. The Prophet (peace be upon him) said that 'SubhaanAllah al-'Atheem wa bihamdihi' (Glory be to Allah the Most Great, and praise be to Him) is light on the tongue, heavy on the scales, and beloved to the Most Merciful (Bukhari and Muslim)."
  }
};