var tafsirData_31 = {
  1: {
    "Alif-Lãm-Mĩm": "These are Arabic letters that appear at the beginning of some chapters of the Quran. Their exact meaning is known only to Allah. They serve to capture attention and demonstrate that the Quran, despite being composed of the same letters Arabs use daily, is a miraculous book that no human can replicate. These letters remind us that there are aspects of divine knowledge that remain beyond human comprehension, teaching us humility before Allah's wisdom."
  },
  2: {
    "These are the verses of the Book": "This refers to the verses of the Quran that follow. Allah is drawing attention to the significance and importance of what is about to be recited. The word 'verses' (ayat) also means 'signs,' indicating that each verse is a sign pointing to Allah's truth and guidance.",
    "rich in wisdom": "The Quran is filled with profound wisdom in every aspect—its laws, stories, guidance, and teachings. It provides solutions for all of life's problems and guides humanity to what is best in this world and the Hereafter. Unlike human books that may contain errors or outdated information, the Quran's wisdom is timeless and perfect because it comes from the All-Wise Creator."
  },
  3: {
    "˹It is˺ a guide": "The Quran serves as a comprehensive guide that shows people the correct path in all matters—beliefs, worship, dealings with others, and personal conduct. Just as a traveler needs a map to reach their destination, humans need the Quran to navigate through life and reach success in the Hereafter.",
    "and mercy": "The Quran is a mercy because it saves those who follow it from misguidance, confusion, and eternal punishment. It provides comfort to troubled hearts, answers to life's biggest questions, and a clear way to earn Allah's pleasure and Paradise.",
    "for the good-doers": "The good-doers (muhsineen) are those who worship Allah with excellence—as if they see Him, or knowing that He sees them. They are sincere in their faith and strive to do good in all aspects of life. The Quran's guidance and mercy are especially for them because they approach it with open hearts and willingness to follow its teachings."
  },
  4: {
    "those who establish prayer": "Establishing prayer means more than just performing the physical movements. It means praying consistently at their proper times, with full concentration (khushu), understanding what is being recited, and allowing the prayer to positively affect one's behavior. The Prophet ﷺ said that prayer is the first thing a person will be asked about on the Day of Judgment. Prayer is the direct connection between a servant and their Lord.",
    "pay alms-tax": "The alms-tax (Zakat) is the obligatory charity that purifies one's wealth and soul. It is given to those in need and is a fundamental pillar of Islam. By paying Zakat, Muslims acknowledge that their wealth ultimately belongs to Allah and that they have a responsibility to help the less fortunate. This prevents greed and creates a caring society.",
    "and have sure faith in the Hereafter": "This means having absolute certainty—not just belief, but unshakeable conviction—that the Day of Judgment will come, that we will be resurrected, and that we will be held accountable for every deed. This certainty motivates a person to do good and avoid evil. Someone who truly believes in the Hereafter lives their life preparing for that eternal destination."
  },
  5: {
    "It is they who are ˹truly˺ guided by their Lord": "Those who possess the qualities mentioned in the previous verse—establishing prayer, paying Zakat, and believing firmly in the Hereafter—are the ones who are genuinely upon guidance from Allah. This guidance is not self-made; it is a gift from their Lord. They are walking on the straight path that leads to Allah's pleasure.",
    "and it is they who will be successful": "True success (falah) is not measured by worldly achievements like wealth, fame, or power. Real success is achieving salvation in the Hereafter—being saved from Hellfire and admitted into Paradise. These righteous individuals will achieve this ultimate success because they followed Allah's guidance sincerely. This is the success that lasts forever, unlike temporary worldly gains."
  },
  6: {
    "But there are some who employ theatrics": "This refers to people who engage in idle, distracting talk or entertainment that has no benefit and keeps people away from remembering Allah. This verse was revealed about certain individuals who would use storytelling, music, or other distractions to compete with the Quran's message. They would 'purchase' or invest in these distractions, spending their time, money, and effort on things that lead people away from the truth.",
    "only to lead others away from Allah's Way": "Their purpose, whether intentional or through negligence, is to divert people from following the path of Islam. They create distractions that make people forget about their prayers, their duties to Allah, and their preparation for the Hereafter. This is extremely dangerous because they not only harm themselves but also lead others astray.",
    "without any knowledge": "They do this while having no real knowledge or understanding of the consequences of their actions. They don't know what true guidance is, nor do they understand the severity of leading people away from Allah. Ignorance does not excuse them because they chose to remain ignorant rather than seek the truth.",
    "and to make a mockery of it": "They mock Allah's verses and His religion, treating the Quran as a joke or something unimportant. This attitude of ridicule shows their arrogance and disrespect for divine guidance. Making fun of any aspect of Islam is a serious matter that can take a person outside the fold of faith.",
    "They will suffer a humiliating punishment": "Because they humiliated the truth and mocked Allah's guidance, their punishment will be one of humiliation. Allah will repay them in a manner befitting their crimes. On the Day of Judgment, they will be disgraced before all of creation, and in Hell, they will face a punishment that degrades them—a fitting consequence for those who degraded Allah's message."
  },
  7: {
    "Whenever Our revelations are recited to them": "When the verses of the Quran are read to these arrogant individuals, they have a particular reaction. The Quran should soften hearts and bring people closer to Allah, but their hearts are hardened by their arrogance and love of falsehood.",
    "they turn away in arrogance": "Instead of listening with humility and an open heart, they physically and spiritually turn away. Their turning is motivated by pride—they consider themselves too important or too sophisticated to accept guidance. Arrogance is one of the greatest barriers to faith because it prevents a person from submitting to the truth.",
    "as if they did not hear them": "They pretend not to hear, acting as though the powerful words of Allah have no effect on them. This is willful ignorance—they choose not to listen because listening would require them to change their ways.",
    "as if there is deafness in their ears": "Allah compares their state to someone who is physically deaf. However, their deafness is not physical but spiritual. Their ears work fine, but their hearts are sealed. This is worse than physical deafness because it is self-imposed.",
    "So give them good news ˹O Prophet˺ of a painful punishment": "This is said sarcastically. Instead of good news (which is what 'bushra' usually means), the Prophet ﷺ is told to inform them of a painful punishment awaiting them. This is a warning that their arrogance and rejection of the truth will result in severe consequences in the Hereafter."
  },
  8: {
    "Surely those who believe": "Faith (iman) is the foundation of everything in Islam. This refers to those who believe in Allah, His angels, His books, His messengers, the Day of Judgment, and divine decree. True belief is not just words on the tongue but conviction in the heart that manifests in actions.",
    "and do good": "Faith must be accompanied by righteous actions. Belief alone is not enough; it must be proven through good deeds. This includes all acts of worship, kindness to others, fulfilling obligations, and staying away from what is forbidden. Faith and good deeds are like two wings of a bird—both are needed to fly.",
    "will have the Gardens of Bliss": "Their reward is Paradise—gardens of absolute pleasure and happiness. These gardens contain everything the soul desires: beautiful dwellings, pure companions, delicious food and drink, and most importantly, the pleasure of Allah. The Prophet ﷺ described Paradise as containing what no eye has seen, no ear has heard, and no human mind has imagined."
  },
  9: {
    "staying there forever": "Unlike worldly pleasures that are temporary and always end, the bliss of Paradise is eternal. There is no fear of it ending, no aging, no sickness, and no death. The inhabitants of Paradise will live in permanent happiness forever. This is the ultimate dream—everlasting joy without any worry of it being taken away.",
    "Allah's promise is true": "This is Allah's guarantee, and Allah never breaks His promises. When Allah promises something, it will certainly happen. This should give believers complete confidence and motivation to work for Paradise. Unlike human promises that may be broken, Allah's promise is absolutely reliable.",
    "And He is the Almighty": "Allah has complete power to fulfill this promise. Nothing can prevent Him from giving Paradise to the believers. His might ensures that His promise will be carried out without any obstacle.",
    "All-Wise": "Allah's wisdom means that His decisions and promises are based on perfect knowledge and justice. He knows exactly who deserves Paradise and who doesn't. His wisdom ensures that the reward is given to those who truly earned it through faith and good deeds."
  },
  10: {
    "He created the heavens without pillars—as you can see": "Look up at the sky and observe its vastness. The heavens—the sky, the stars, the galaxies—are suspended without any visible support. No pillars or columns hold them up. This is a magnificent display of Allah's power. Modern science confirms that celestial bodies are held in place by gravitational forces, but ultimately, it is Allah who created and maintains these forces.",
    "and placed firm mountains upon the earth so it does not shake with you": "Mountains serve as stabilizers for the earth, like pegs that hold a tent in place. Without them, the earth's surface would be much more unstable. Allah placed these massive structures to make the earth habitable and safe for us. This shows Allah's care for His creation and His precise design of the earth.",
    "and scattered throughout it all types of creatures": "Allah spread across the earth an incredible diversity of animals—mammals, birds, insects, fish, and countless other species. Each creature has its own unique design, habitat, and purpose. This diversity is a sign of Allah's creativity and power. From the smallest ant to the largest whale, each creature testifies to Allah's existence and wisdom.",
    "And We send down rain from the sky": "Rain is one of Allah's greatest blessings. Without it, life on earth would be impossible. Allah sends down rain in precise amounts—not too much to cause floods, and not too little to cause drought. The water cycle that brings rain is a perfect system designed by Allah.",
    "causing every type of fine plant to grow on earth": "From the rain, Allah causes beautiful and beneficial plants to grow—fruits, vegetables, grains, flowers, and trees. Each plant is 'fine' or 'noble' (kareem) because it serves a purpose and displays beauty. This vegetation sustains all life on earth and is a sign of Allah's generosity and care."
  },
  11: {
    "This is Allah's creation": "Everything mentioned—the heavens, mountains, creatures, rain, and plants—all of this is the work of Allah alone. He created it all from nothing, designed it perfectly, and sustains it continuously. This is undeniable evidence of His existence and power.",
    "Now show Me what those ˹gods˺ other than Him have created": "This is a powerful challenge to those who worship others besides Allah. What have their false gods created? Can they point to any heavens, mountains, or creatures that their idols made? The answer is obviously nothing. This rhetorical question exposes the absurdity of worshipping anything other than the Creator.",
    "In fact, the wrongdoers are clearly astray": "Those who worship false gods are not just mistaken; they are clearly and obviously lost. Their misguidance is evident because they worship things that have no power to create anything. Calling them 'wrongdoers' (zalimoon) indicates that they are wronging themselves by choosing falsehood over truth and thereby earning Allah's punishment."
  },
  12: {
    "Indeed, We blessed Luqmân with wisdom": "Luqman was a wise man mentioned in the Quran—some scholars say he was a prophet, while others say he was a righteous servant of Allah. What is certain is that Allah blessed him with hikma (wisdom), which is the ability to understand things correctly and act appropriately. Wisdom is one of the greatest gifts a person can receive because it guides them to make right decisions in all matters of life.",
    "˹saying˺, \"Be grateful to Allah": "The first and most important aspect of wisdom is gratitude to Allah. Luqman's wisdom led him to thank Allah for all His blessings. Gratitude is not just saying 'thank you' but using Allah's blessings in ways that please Him. A grateful person recognizes that every good thing comes from Allah and responds with worship, obedience, and praise.",
    "for whoever is grateful, it is only for their own good": "When a person is grateful, the benefit returns to them, not to Allah. Allah does not need our thanks. Gratitude brings more blessings, as Allah says elsewhere: 'If you are grateful, I will surely increase you' (Quran 14:7). Being grateful also brings peace of heart and contentment.",
    "And whoever is ungrateful, then surely Allah is Self-Sufficient": "If someone chooses to be ungrateful, they only harm themselves. Allah is completely independent and needs nothing from anyone. He is Self-Sufficient (Ghani)—our gratitude does not benefit Him, and our ingratitude does not harm Him. He remains perfect and praised regardless of what His creation does.",
    "Praiseworthy": "Allah is Hameed—worthy of all praise whether people praise Him or not. His perfection, beauty, and generosity deserve praise. All of creation, in its own way, praises Allah, even if some humans foolishly refuse to do so."
  },
  13: {
    "And ˹remember˺ when Luqmân said to his son, while advising him": "This begins Luqman's beautiful advice to his son, which serves as a model for how parents should guide their children. Notice the tender way Luqman approaches his son—with love and wisdom, not harshness. Good parenting involves teaching children the most important lessons of life with care and patience.",
    "\"O my dear son!": "The Arabic word 'bunayya' is an affectionate diminutive form meaning 'my little son' or 'my dear son.' This shows the love and tenderness with which Luqman addresses his child. When giving advice, especially about serious matters, beginning with love and affection makes the listener more receptive.",
    "Never associate ˹anything˺ with Allah ˹in worship˺": "The very first piece of advice Luqman gives is about Tawheed—the oneness of Allah. This is the foundation of Islam and the most important thing any parent can teach their child. Shirk (associating partners with Allah) is the opposite of Tawheed and the gravest sin possible. This includes worshipping idols, but also anything given the love, fear, or obedience that should only be for Allah.",
    "for associating ˹others with Him˺ is truly the worst of all wrongs": "Shirk is described as 'thulm adheem'—a great injustice or wrongdoing. It is an injustice to Allah, who alone deserves worship; an injustice to oneself, as it leads to eternal punishment; and an injustice to the objects worshipped, which are given a status they don't deserve. The Prophet ﷺ said that shirk is the greatest sin in Allah's sight."
  },
  14: {
    "And We have commanded people to ˹honour˺ their parents": "Allah Himself commands us to honor and be good to our parents. This is not just a suggestion but a divine command that comes right after the command to worship Allah alone. In fact, in many places in the Quran, kindness to parents is mentioned immediately after Tawheed, showing its great importance. The Prophet ﷺ said that the pleasure of Allah is in the pleasure of parents, and His anger is in their anger.",
    "Their mothers bore them through hardship upon hardship": "Allah specifically mentions the sacrifices of mothers to highlight their special status. Pregnancy is extremely difficult—the mother experiences weakness upon weakness (wahnan ala wahn) as her body works tirelessly to nurture the growing child. She endures morning sickness, physical discomfort, emotional changes, and the pain of childbirth. This is why the Prophet ﷺ, when asked who deserves the best treatment, said 'your mother' three times before mentioning the father.",
    "and their weaning takes two years": "After birth, the mother continues her sacrifice through breastfeeding, which ideally lasts two years. During this time, she provides nutrition, comfort, and care to the helpless infant. The mention of these specific hardships reminds children of the tremendous debt they owe their mothers.",
    "So be grateful to Me and your parents": "Allah connects gratitude to Him with gratitude to parents. Just as we must thank Allah for all His blessings, we must thank our parents for their sacrifices. This gratitude is shown through respect, obedience (in what is good), kind words, and taking care of them, especially in old age.",
    "To Me is the final return": "This reminder that everyone will return to Allah serves as a warning and motivation. We will be asked about how we treated our parents. Those who honored their parents will be rewarded, and those who mistreated them will face consequences."
  },
  15: {
    "But if they pressure you to associate with Me what you have no knowledge of": "This verse establishes an important limit to parental obedience. If parents command their child to commit shirk or any sin, the child must not obey. The phrase 'what you have no knowledge of' emphasizes that shirk has no basis in truth or evidence—it is baseless falsehood. No matter how much parents may pressure or insist, obedience to Allah comes first.",
    "do not obey them": "This is a clear command: do not obey anyone—even your beloved parents—in disobedience to Allah. The Prophet ﷺ said: 'There is no obedience to any created being if it involves disobedience to the Creator.' This principle protects a person's faith from being compromised by family pressure.",
    "Still keep their company in this world courteously": "Even if parents are non-believers or try to lead their child astray, the child must still treat them with kindness, respect, and good manners in worldly matters. This is remarkable—Islam commands us to be good to parents even when they oppose our faith. We should speak to them gently, provide for them if they need help, and not cut ties with them.",
    "and follow the way of those who turn to Me ˹in devotion˺": "While maintaining family ties, a believer must follow the path of the righteous believers—those who have turned to Allah in sincere repentance and devotion. This means seeking righteous company and guidance in religious matters from those who are upon the truth.",
    "Then to Me you will ˹all˺ return, and then I will inform you of what you used to do": "Everyone—believers and non-believers, obedient children and disobedient ones—will return to Allah for judgment. On that Day, Allah will reveal everything people did and reward or punish accordingly. This serves as both a warning and a comfort: wrongdoers will be held accountable, and the patient believers will be rewarded."
  },
  16: {
    "˹Luqmân added,˺ \"O my dear son!": "Luqman continues his loving advice, again using the affectionate term for his son. Each piece of advice builds upon the previous one, creating a comprehensive guide for a righteous life.",
    "˹Even˺ if a deed were the weight of a mustard seed": "A mustard seed is one of the tiniest seeds known—almost invisible to the naked eye. Luqman uses this example to show that even the smallest deed, whether good or bad, is recorded and will be accounted for. Nothing escapes Allah's knowledge, no matter how insignificant it may seem to us.",
    "be it ˹hidden˺ in a rock or in the heavens or the earth": "Even if this tiny deed were hidden inside a solid rock, or lost somewhere in the vast heavens, or buried deep in the earth—places where humans could never find it—Allah knows exactly where it is. There is no hiding from Allah. This should make a person conscious of every action, word, and even thought.",
    "Allah will bring it forth": "On the Day of Judgment, Allah will bring forth every single deed. Nothing will be forgotten or overlooked. This gives hope to those who do small good deeds that go unnoticed by people—Allah sees and will reward them. It also warns those who commit sins in secret—Allah knows and will hold them accountable.",
    "Surely Allah is Most Subtle": "Allah is Lateef—meaning He is subtle, gentle, and aware of the finest details. He knows the secrets of hearts, the hidden intentions, and the most minute matters. His subtlety also means He takes care of His servants in ways they may not even realize.",
    "All-Aware": "Allah is Khabeer—fully informed and aware of everything. Nothing is hidden from His knowledge. He knows what has happened, what is happening, and what will happen. This complete awareness means perfect justice on the Day of Judgment."
  },
  17: {
    "\"O my dear son! Establish prayer": "After teaching about belief and accountability, Luqman instructs his son about action—starting with prayer. Prayer is the pillar of Islam and the first thing a person will be asked about on the Day of Judgment. Establishing prayer means performing it correctly, on time, with focus and humility, not just going through the motions.",
    "encourage what is good": "A believer doesn't just do good themselves but also encourages others to do good. This is part of caring for the community and wanting the best for others. Encouraging good can be through words, actions, or setting a good example. The Prophet ﷺ said that whoever guides someone to good will have a reward equal to the one who does it.",
    "and forbid what is evil": "Similarly, a believer should discourage and prevent evil when possible. This must be done wisely—with the hand if one has authority, with the tongue through advice, or at least by hating it in the heart if nothing else is possible. This creates a society where good is promoted and evil is minimized.",
    "and endure patiently whatever befalls you": "When a person stands for truth, encourages good, and forbids evil, they will face opposition and difficulties. Luqman prepares his son for this reality: be patient. Patience (sabr) is essential for maintaining faith and righteousness in the face of life's tests. Without patience, a person might give up when things get hard.",
    "Surely this is a resolve to aspire to": "These matters—prayer, enjoining good, forbidding evil, and patience—require strong determination and resolve. They are not easy, but they represent the noble path that great people follow. Having 'azm (firm resolve) in these matters distinguishes the strong believers from the weak."
  },
  18: {
    "\"And do not turn your nose up to people": "The Arabic expression refers to turning one's cheek away from people in arrogance, like someone who thinks they are too important to look at others directly. This is a sign of pride and looking down on others. A believer should face people with humility and respect, treating everyone with dignity regardless of their status.",
    "nor walk pridefully upon the earth": "Walking with excessive pride and arrogance—strutting, showing off, or acting superior—is forbidden. This type of walking reflects an inner arrogance and self-importance that Allah despises. The way a person walks reveals a lot about their character.",
    "Surely Allah does not like whoever is arrogant": "Arrogance is one of the most hated traits to Allah. The Prophet ﷺ said that anyone with even an atom's weight of arrogance in their heart will not enter Paradise. Arrogance is essentially rejecting the truth and looking down on people. It was the sin of Iblis (Satan) that caused his eternal downfall.",
    "boastful": "Boasting about one's achievements, wealth, beauty, or status is also disliked. A boastful person attributes their blessings to themselves rather than to Allah and makes others feel inferior. True believers are humble, knowing that all good things come from Allah and can be taken away at any moment."
  },
  19: {
    "Be moderate in your pace": "Walk in a balanced way—not too fast as if rushing anxiously, and not too slow as if showing off or being lazy. A moderate pace reflects a calm, confident, and humble personality. The Prophet ﷺ was known to walk with purpose and dignity, neither rushing nor dragging his feet.",
    "And lower your voice": "Speaking in a moderate tone is a sign of good manners and respect for others. Shouting unnecessarily, speaking too loudly, or being obnoxious with one's voice is inappropriate. This doesn't mean whispering but rather speaking at an appropriate volume that conveys respect and self-control.",
    "for the ugliest of all voices is certainly the braying of donkeys": "This vivid comparison drives home the point about loud, harsh voices. The donkey's bray is considered one of the most unpleasant sounds—loud, harsh, and without any beauty. Allah uses this comparison to discourage people from raising their voices unnecessarily. No one wants to sound like a donkey, so this imagery encourages refined speech and moderation in volume."
  },
  20: {
    "Have you not seen that Allah has subjected for you whatever is in the heavens and whatever is on the earth": "Everything in the universe has been placed at the service of humanity. The sun provides light and warmth, the moon marks time, the stars guide travelers, the animals provide food and transportation, the plants give nourishment and medicine. All of this is by Allah's design for human benefit. This should inspire gratitude, not arrogance.",
    "and has lavished His favours upon you, both seen and unseen": "Allah's blessings are both apparent (zahira) and hidden (batina). Apparent blessings include health, family, wealth, food, and shelter—things we can see and recognize. Hidden blessings include things like the immune system protecting us from diseases, angels recording our deeds, and guidance to faith that we may not fully appreciate. The unseen blessings may actually be greater than what we can perceive.",
    "˹Still˺ there are some who dispute about Allah without knowledge": "Despite all these evident favors, some people still argue against Allah's existence, His oneness, or His right to be worshipped. They have no knowledge—no sound reasoning or evidence—to support their claims.",
    "or guidance": "They also lack divine guidance. They haven't followed any prophet or accepted any revelation. They argue from their own whims and desires.",
    "or an enlightening scripture": "They have no authoritative scripture to base their arguments on. Their disputes are baseless, built on ignorance and stubbornness rather than any legitimate foundation."
  },
  21: {
    "When it is said to them, \"Follow what Allah has revealed,\"": "When these people are invited to follow the Quran and the guidance sent by Allah through His Messenger ﷺ, they refuse. The truth is presented clearly to them, but they reject it.",
    "they reply, \"No! We ˹only˺ follow what we found our forefathers practicing.\"": "Their excuse is blind following of ancestors. They choose tradition over truth, the ways of their fathers over the way of Allah. This is a common excuse throughout history—people reject prophets because their message differs from what their ancestors believed.",
    "˹Would they still do so˺ even if Satan is inviting them to the torment of the Blaze?": "Allah poses a rhetorical question: Would they still follow their ancestors if they knew that path leads to Hellfire? Following ancestors who were misguided means following Satan, because it is Satan who originally misled those ancestors. This verse exposes the danger of blind following without questioning whether the path is correct according to Allah's guidance."
  },
  22: {
    "Whoever fully submits themselves to Allah": "Submitting one's 'face' (wajh) to Allah means directing oneself entirely to Allah—one's intentions, actions, hopes, and fears are all for Allah alone. It means complete surrender to Allah's will and guidance. This is the essence of Islam: submission to the One True God.",
    "and is a good-doer": "Submission must be accompanied by excellence in doing good (ihsan). It's not enough to just believe; one must act upon that belief by doing good deeds with sincerity and quality. The Prophet ﷺ defined ihsan as worshipping Allah as if you see Him, or knowing that He sees you.",
    "they have certainly grasped the firmest hand-hold": "This is a beautiful metaphor. Imagine a person hanging over a cliff—they would grab the strongest, most reliable handhold available. Faith in Allah combined with righteous deeds is that firmest handhold. It will never break or let a person down. Everything else in life may fail, but holding onto Allah's guidance is the most secure thing possible.",
    "And with Allah rests the outcome of ˹all˺ affairs": "All matters ultimately return to Allah for final judgment. Those who held onto the firmest handhold will find safety, while those who grabbed onto weak supports will fall. This reminder emphasizes that our choices in this life determine our outcome in the next."
  },
  23: {
    "But whoever disbelieves, do not let their disbelief grieve you ˹O Prophet˺": "The Prophet ﷺ cared deeply about people accepting the truth and was saddened when they rejected it. Allah consoles him: don't let their disbelief cause you grief. A messenger's job is to convey the message, not to force belief. People have free will, and some will choose to reject.",
    "To Us is their return": "Allah reminds the Prophet ﷺ and all believers that everyone will return to Allah. No one escapes death and the subsequent accounting. This should bring comfort to believers and serve as a warning to disbelievers.",
    "and We will inform them of all they did": "On the Day of Judgment, Allah will tell everyone exactly what they did—every deed, every word, every intention. Nothing will be hidden or forgotten. This full disclosure will precede the final judgment.",
    "Surely Allah knows best what is ˹hidden˺ in the heart": "Allah has complete knowledge of what is inside people's hearts—their secret intentions, hidden beliefs, and unexpressed thoughts. People may deceive others, but they cannot deceive Allah. He will judge based on this complete knowledge."
  },
  24: {
    "We allow them enjoyment for a little while": "Allah may allow disbelievers to enjoy this worldly life for a short time. This enjoyment is not a sign of Allah's approval; it is simply part of the test of life. The pleasures of this world are temporary and will soon end. Compared to eternity, even a lifetime of worldly pleasure is nothing.",
    "then ˹in time˺ We will force them into a harsh torment": "After their brief enjoyment, they will be driven—without escape—into a severe and harsh punishment. The word 'force' (nadtaruhum) indicates they will have no choice or ability to resist. The punishment will be intense and overwhelming, completely unlike the comfortable life they enjoyed in this world."
  },
  25: {
    "And if you ask them who created the heavens and the earth, they will definitely say, \"Allah!\"": "Even the polytheists of Mecca, when asked about the Creator, would acknowledge that Allah created everything. They knew deep down that their idols didn't create anything. This shows that belief in a Creator is natural (fitrah) and even those who worship others besides Allah often acknowledge Him as the ultimate Creator.",
    "Say, \"Praise be to Allah!\"": "Say 'Alhamdulillah'—all praise belongs to Allah. This is an expression of relief and gratitude that even the misguided acknowledge Allah as Creator. It also serves as an argument: if you admit Allah created everything, then why worship anything else?",
    "In fact, most of them do not know": "Despite acknowledging Allah as Creator, most of them don't truly understand what this means. If they truly understood, they would worship Allah alone. Their knowledge is incomplete and doesn't translate into proper action. This is a warning against superficial knowledge that doesn't lead to correct behavior."
  },
  26: {
    "To Allah belongs whatever is in the heavens and the earth": "Everything in existence belongs to Allah as its Creator, Owner, and Sustainer. Every atom, every creature, every star—all belong to Him. We don't truly own anything; we are merely trustees of what Allah has lent us temporarily.",
    "Allah is truly the Self-Sufficient": "Allah is Al-Ghani—completely free from any need. He does not need our worship, our obedience, or anything from His creation. He is perfect and complete in Himself. Our worship benefits us, not Him. This understanding should humble us and increase our appreciation for His mercy in guiding us.",
    "Praiseworthy": "Allah is Al-Hameed—worthy of all praise in His essence, His names, His attributes, and His actions. Whether creation praises Him or not, He remains praiseworthy. All the good that exists is from Him and reflects His praiseworthy nature."
  },
  27: {
    "If all the trees on earth were pens": "Imagine every single tree on earth—millions upon millions of them—being transformed into pens for writing. This is a massive, almost unimaginable quantity of writing instruments.",
    "and the ocean ˹were ink˺, refilled by seven other oceans": "Now imagine the entire ocean as ink, and then add seven more oceans worth of ink to it. The oceans contain an unfathomable amount of water—and this is multiplied by eight.",
    "the Words of Allah would not be exhausted": "Even with all those pens and all that ink, writing out Allah's words—His knowledge, His decrees, His wisdom—would never exhaust them. The pens would break and the ink would run dry long before Allah's words could be fully recorded. This is a powerful image showing the infinite nature of Allah's knowledge.",
    "Surely Allah is Almighty": "Allah has the power to possess such infinite knowledge. His might is limitless.",
    "All-Wise": "All of Allah's infinite words and knowledge are characterized by perfect wisdom. Nothing from Allah is without purpose or meaning."
  },
  28: {
    "The creation and resurrection of you ˹all˺ is as simple ˹for Him˺ as that of a single soul": "For Allah, creating all of humanity and then resurrecting everyone on the Day of Judgment is as easy as creating or resurrecting a single person. There is no difference in difficulty—everything is equally easy for Allah. We might think billions of people are harder to manage than one, but for Allah, numbers are irrelevant. This answers those who doubted resurrection, thinking it too difficult.",
    "Surely Allah is All-Hearing": "Allah hears everything—every voice, every whisper, every thought. He can hear the prayers of billions simultaneously without any confusion or overwhelm.",
    "All-Seeing": "Allah sees everything at all times—every person, every action, every hidden deed. His sight encompasses all of creation perfectly and simultaneously."
  },
  29: {
    "Do you not see that Allah causes the night to merge into the day": "Observe how night gradually transitions into day. The darkness slowly gives way to light in a beautiful, gradual process. This daily occurrence that we often take for granted is actually a magnificent sign of Allah's control over the universe.",
    "and the day into the night": "Similarly, day merges into night. The daylight gradually fades as darkness takes over. This constant cycle has continued perfectly since creation without any malfunction.",
    "and has subjected the sun and the moon": "The sun and moon are under Allah's command, serving humanity. The sun provides light, warmth, and energy, while the moon provides light at night and helps mark the months. These massive celestial bodies obey Allah perfectly.",
    "each orbiting for an appointed term": "Both the sun and moon follow precise orbits, and both have an appointed end time. Nothing in creation is eternal except Allah. One day, even the sun and moon will cease to exist when Allah decrees the end of this world.",
    "and that Allah is All-Aware of what you do": "After describing cosmic phenomena, Allah reminds us that He is also fully aware of human actions. The same God who controls the universe also knows every deed we do. We cannot escape His knowledge."
  },
  30: {
    "That is because Allah ˹alone˺ is the Truth": "The preceding signs prove that Allah alone is Al-Haqq—the True, the Real. He is truth in His existence, His divinity, His attributes, and His actions. Everything about Allah is absolute truth and reality.",
    "and what they invoke besides Him is falsehood": "In contrast, everything worshipped besides Allah—whether idols, people, objects, or concepts—is batil (falsehood, vanity, worthless). They have no real power, no ability to benefit or harm. Worshipping them is following a lie.",
    "and ˹because˺ Allah ˹alone˺ is the Most High": "Allah is Al-'Ali—the Most High, supreme over all creation in His essence, His status, and His power. Nothing and no one is above Allah.",
    "All-Great": "Allah is Al-Kabeer—the Greatest, possessing ultimate greatness in every aspect. All other greatness pales in comparison to His. This should inspire awe, reverence, and worship of Allah alone."
  },
  31: {
    "Do you not see that the ships sail ˹smoothly˺ through the sea": "Consider how ships travel across vast oceans. These massive vessels can navigate through water, carrying people and goods across distances. The principles of buoyancy, wind, and navigation that make this possible are all from Allah's design.",
    "by the grace of Allah": "Ships sail only because Allah has made it possible. He created water with properties that allow vessels to float. He created winds that push sails. He gave humans the intelligence to build ships. Every successful voyage is by Allah's permission and grace.",
    "so that He may show you some of His signs": "Sea travel is meant to make us reflect on Allah's signs—His power over nature, His provision for human needs, and His control over all things. When we use these blessings, we should recognize the One who provided them.",
    "Surely in this are signs for whoever is steadfast, grateful": "The people who truly benefit from these signs are those who combine two qualities: patience (sabbar) and gratitude (shakur). They are patient during difficulties and grateful during ease. These two qualities are the hallmarks of true faith and enable a person to recognize Allah's signs everywhere."
  },
  32: {
    "And as soon as they are overwhelmed by waves like mountains": "Imagine being on a ship when huge waves—as tall as mountains or dark canopies—threaten to engulf the vessel. This is a moment of absolute terror and helplessness. In such moments, human pretense is stripped away.",
    "they cry out to Allah ˹alone˺ in sincere devotion": "In these terrifying moments, even those who normally worship others besides Allah instinctively call upon Allah alone. Their devotion becomes pure and sincere—no shirk, no calling upon idols. This reveals the natural human recognition (fitrah) that only Allah can save in times of true crisis. All false gods are forgotten.",
    "But when He delivers them ˹safely˺ to shore": "Allah, in His mercy, saves them. They reach land safely, the danger has passed, and they are alive. This is a tremendous blessing that should inspire lifelong gratitude.",
    "only some become relatively grateful": "Sadly, only some of them show any gratitude at all, and even that gratitude is limited (muqtasid—moderate, not full). They may acknowledge Allah's help briefly but then return to their old ways. This is a common human weakness: turning to Allah in desperation but forgetting Him in comfort.",
    "And none rejects Our signs except whoever is deceitful, ungrateful": "Those who completely reject Allah's signs after such clear experiences are described with two traits: khattar (treacherous, breaking promises and covenants) and kafur (extremely ungrateful). They promised to be grateful when in danger, but betrayed that promise once safe. This is the worst kind of ingratitude."
  },
  33: {
    "O humanity!": "This is a universal address to all human beings, regardless of time, place, or background. The message that follows is relevant to everyone.",
    "Be mindful of your Lord": "Have taqwa of Allah—consciousness of Him that leads to obedience and avoidance of sin. Remember that He is watching, that He will hold you accountable, and that His punishment is severe. Taqwa is the shield that protects a person from wrongdoing.",
    "and beware of a Day when no parent will be of any benefit to their child": "On the Day of Judgment, the strongest worldly bonds will be of no use. A parent cannot help their child escape punishment or share their good deeds with them. Each person stands alone before Allah.",
    "nor will a child be of any benefit to their parent": "Similarly, children cannot help their parents. No matter how much they love each other, no one can take responsibility for another's sins or transfer their rewards. Everyone is individually accountable.",
    "Surely Allah's promise is true": "The Day of Judgment is coming without any doubt. Allah's promise cannot be broken. Everything He has said about that Day will happen exactly as He described.",
    "So do not let the life of this world deceive you": "The pleasures, distractions, and concerns of this temporary life should not make you forget the eternal Hereafter. This world is attractive but fleeting. Don't be tricked into prioritizing it over your eternal wellbeing.",
    "nor let the Chief Deceiver deceive you about Allah": "The 'Chief Deceiver' (Gharur) is Satan (Iblis). He constantly tries to deceive people about Allah—making them think they have plenty of time to repent, that their sins don't matter, or that Allah will forgive them without effort. Don't fall for his tricks."
  },
  34: {
    "Indeed, Allah ˹alone˺ has the knowledge of the Hour": "The exact timing of the Day of Judgment is known only to Allah. No angel, prophet, or any creation knows when it will occur. When asked about it, even the Prophet ﷺ and Angel Jibreel confirmed they did not know. This is exclusively Allah's knowledge.",
    "He sends down the rain": "Allah alone knows precisely when, where, and how much rain will fall. While modern meteorology can make predictions, the ultimate control and exact knowledge belongs to Allah. He sends rain as He wills—sometimes to bless and sometimes to test.",
    "and knows what is in the wombs": "Allah knows everything about what develops in the womb—not just whether it's male or female (which modern technology can detect), but also its complete future: its sustenance, lifespan, actions, and ultimate destiny. This comprehensive knowledge of the unborn is exclusively Allah's.",
    "No soul knows what it will earn for tomorrow": "No person knows what tomorrow holds for them—what opportunities, trials, provisions, or deeds await. We make plans, but only Allah knows what will actually happen. This humbles us and keeps us dependent on Allah.",
    "and no soul knows in what land it will die": "Death is inevitable, but its location is unknown. A person might die in their hometown, in a foreign land, on a journey, or anywhere else. This uncertainty reminds us that death can come at any moment and anywhere, so we must always be prepared.",
    "Surely Allah is All-Knowing, All-Aware": "Allah's knowledge encompasses everything—past, present, and future, seen and unseen, large and small. He is fully aware of every detail of existence. These five areas of unseen knowledge mentioned in this verse highlight aspects of Allah's exclusive omniscience that no creation shares."
  }
};