var tafsirData_108 = {
  1: {
    "Indeed, We have granted you": "Allah begins with a powerful affirmation using \"Indeed\" (إنّا) to emphasize the certainty and greatness of this gift. The use of \"We\" reflects Allah's majesty and royal plural, highlighting that this gift comes from the Most High Himself. This was revealed at a time when the Prophet (ﷺ) was being mocked by his enemies for having no surviving sons. Al-'Ās ibn Wā'il, a prominent Meccan pagan, called the Prophet \"abtar\" (cut off), implying he would have no legacy. Allah responds directly to this mockery, assuring the Prophet that far from being cut off, he has been given something far greater than any worldly lineage.",
    "˹O Prophet˺ abundant goodness": "The word \"Al-Kawthar\" means abundant goodness, overflowing blessings, and immense good. Scholars have interpreted this in several ways: (1) A river in Paradise specifically for the Prophet (ﷺ). The Prophet (ﷺ) said: \"Al-Kawthar is a river in Paradise, its banks are of gold, and it flows over pearls and sapphires. Its soil is more fragrant than musk, its water is sweeter than honey and whiter than milk.\" (Reported by Tirmidhi). (2) The prophethood and the Quran itself. (3) The vast number of followers the Prophet would have. (4) All goodness combined - his intercession, his message, his community. Today, Muhammad (ﷺ) is the most common name in the world, with over 1.8 billion followers. This verse beautifully shows how Allah defends His beloved Prophet and turns the mockery of enemies into a testimony of divine favor."
  },
  2: {
    "So pray": "The word \"So\" (فَ) indicates a logical consequence - because Allah has given you such abundant blessings, the natural response should be gratitude expressed through prayer. Prayer (Salah) is the greatest act of worship in Islam, a direct connection between the servant and his Lord. This command reminds the Prophet (ﷺ) and all believers that when we receive blessings, our first response should be turning to Allah in worship, not becoming arrogant or forgetful. The pagans of Mecca would pray to idols and seek their favor. Here, Allah clarifies that all prayer must be directed to Him alone.",
    "and sacrifice to your Lord ˹alone˺": "The word \"nahr\" specifically refers to the sacrifice of camels and large animals, though it encompasses all sacrificial offerings. This command has multiple meanings: (1) To sacrifice animals as an act of worship during Eid al-Adha and other occasions, dedicating the sacrifice to Allah alone, not to idols as the pagans did. (2) Some scholars say it also refers to placing the hands on the chest during prayer. The phrase \"to your Lord alone\" is crucial - it establishes pure monotheism (Tawhid). The pagans would sacrifice to their idols, but the believer sacrifices only for Allah. This verse establishes that both prayer and sacrifice - the two greatest acts of worship - must be exclusively for Allah. The Prophet (ﷺ) said: \"Allah curses the one who sacrifices to other than Allah.\" (Sahih Muslim). This teaches us that true gratitude for blessings is shown through sincere, exclusive worship of the One who gave them."
  },
  3: {
    "Only the one who hates you": "The word \"shāni'ak\" (شَانِئَكَ) refers to someone who harbors deep hatred, animosity, and enmity toward the Prophet (ﷺ). This was revealed specifically about Al-'Ās ibn Wā'il, but it applies to all who hate the Prophet throughout history. Al-'Ās had mocked the Prophet when his son died, calling him \"abtar\" (cut off), suggesting his name and legacy would end with no male heir to carry it forward. Allah turns this insult completely around. The hatred of the Prophet's enemies is a sign of their own spiritual disease and ultimate loss. History has proven this verse true - those who opposed and hated the Prophet are barely remembered except in disgrace, while the Prophet's name is called out five times daily from every minaret across the world.",
    "is truly cut off ˹from any goodness˺": "The word \"abtar\" (الْأَبْتَرُ) means cut off, severed, without continuation or legacy. Allah declares that the very insult hurled at the Prophet actually describes his enemies perfectly. They are the ones truly cut off - cut off from Allah's mercy, cut off from any lasting legacy, cut off from goodness in this world and the next. Al-'Ās ibn Wā'il died as a disbeliever, and his name is only remembered in the context of this Surah as an example of failure. Meanwhile, millions of people are named Muhammad in his honor. This is a profound lesson: those who oppose Allah's chosen messengers and His truth will ultimately be forgotten and lose everything, while those who follow the truth will be elevated and remembered with honor. The Surah that begins with abundant blessings ends by showing that the enemies of truth are the real losers, despite their temporary arrogance."
  }
};