var tafsirData_97 = {
  1: {
    "Indeed, it is We Who sent this Quran down": "Allah uses the majestic plural 'We' to emphasize His greatness and the magnitude of this act. This refers to the Quran being sent down from the Preserved Tablet (Al-Lawh Al-Mahfuz) to the lowest heaven in its entirety, from where it was then revealed to Prophet Muhammad (ﷺ) gradually over 23 years through Angel Jibreel. The use of 'We' highlights that this was not a random event but a deliberate, divine decision made by the Lord of all creation. This is a tremendous honor for humanity—that Allah chose to communicate with us through His final Book.",
    "on the Night of Glory": "This refers to a specific blessed night in the month of Ramadan, known as Laylat al-Qadr (the Night of Decree/Power/Glory). The Prophet (ﷺ) said: 'Seek it in the last ten nights of Ramadan' (Bukhari & Muslim). Most scholars believe it falls on one of the odd nights of the last ten days, with the 27th night being most commonly identified. The word 'Qadr' carries meanings of honor, power, and decree—indicating that this night holds immense value and that divine decrees for the coming year are determined on it."
  },
  2: {
    "And what will make you realize what the Night of Glory is?": "This is a rhetorical question used in the Quran to create a sense of awe and to indicate that the subject being discussed is beyond ordinary human comprehension. It is as if Allah is saying: 'O Muhammad, O reader—you cannot fully grasp the true magnitude of this night.' This style appears elsewhere in the Quran when describing Paradise, Hellfire, and the Day of Judgment. It serves to humble us and make us appreciate that some realities are so great that our limited minds cannot fully comprehend them. The question invites reflection and prepares the reader for the magnificent description that follows."
  },
  3: {
    "The Night of Glory is better than a thousand months": "This single night is more valuable in reward and blessing than a thousand months of worship—which is approximately 83 years and 4 months, longer than most human lifespans! This means that a believer who spends this night in sincere worship earns more reward than someone who worshipped continuously for over eight decades. The Prophet (ﷺ) said: 'Whoever stands in prayer on Laylat al-Qadr out of faith and seeking reward, his previous sins will be forgiven' (Bukhari & Muslim). This is an extraordinary mercy from Allah, allowing believers to earn immense rewards in a short time. It also shows Allah's generosity—He gives us opportunities to maximize our good deeds despite our short lives."
  },
  4: {
    "That night the angels and the holy spirit descend": "On this blessed night, angels descend to earth in great numbers—more than on any other night of the year. The 'holy spirit' refers to Angel Jibreel (Gabriel), who is mentioned separately to honor his elevated status among the angels. He is the same angel who brought the Quran to the Prophet (ﷺ). The descent of these noble beings brings mercy, blessings, and tranquility to the earth. The Prophet (ﷺ) said: 'The angels on that night are more numerous than pebbles on earth' (Ahmad). Their presence is a sign of the night's tremendous honor and sanctity.",
    "by the permission of their Lord": "The angels do not act independently; they descend only with Allah's command and authorization. This emphasizes that everything in the universe operates under Allah's sovereign will. Nothing happens without His permission. This phrase teaches us that even the most powerful and noble of Allah's creatures—the angels—are completely obedient and subservient to Him.",
    "for every decreed matter": "On this night, the divine decrees for the coming year are carried down by the angels. Matters such as sustenance, life, death, and various events are assigned to be executed throughout the year. This connects to the concept of divine decree (Qadr) in Islam. Allah, in His infinite wisdom, has already written everything in the Preserved Tablet, but the angels receive the detailed instructions for the year ahead on this night. This reminds us that our lives are in Allah's hands, and we should trust His plan while striving to do good."
  },
  5: {
    "It is all peace": "The entire night, from sunset to dawn, is enveloped in peace, tranquility, and safety. This peace is both spiritual and physical—the angels greet the believers with peace, and the atmosphere is filled with divine serenity. Satan and evil are subdued, and mercy descends abundantly. Some scholars say the angels say 'Salam' (peace) to every believer they encounter who is engaged in worship. This is a night free from harm and full of goodness. Believers who experience this night often describe a unique sense of calm and spiritual closeness to Allah.",
    "until the break of dawn": "This blessed state continues throughout the entire night until the light of Fajr (dawn) appears. The believer is encouraged to spend the whole night—or as much of it as possible—in prayer, recitation of the Quran, supplication, and remembrance of Allah. The Prophet (ﷺ) would exert himself in worship during the last ten nights of Ramadan more than at any other time (Muslim). Aisha (may Allah be pleased with her) asked the Prophet (ﷺ) what supplication she should make if she found this night, and he taught her: 'Allahumma innaka 'afuwwun tuhibbul-'afwa fa'fu 'anni' (O Allah, You are the Pardoner, You love to pardon, so pardon me) (Tirmidhi). This simple yet profound supplication captures the essence of what we should seek on this magnificent night."
  }
};