var tafsirData_76 = {
  1: {
    "Is there not a period of time": "Allah begins this surah with a rhetorical question that invites deep reflection. The answer is obviously 'yes.' This style of questioning is meant to awaken the listener and make them ponder their own existence. Before you were born, before your parents even knew you would exist, there was a time when you were absolutely nothing.",
    "when each human is nothing yet worth mentioning?": "There was a stage in everyone's existence when they had no name, no form, no identity, and no one even spoke about them. Think about it: go back a hundred years, and you were not even a thought in anyone's mind. You were not mentioned in any conversation, not remembered by anyone. This profound reflection should humble every human being. If Allah brought you from complete non-existence to existence, He can certainly resurrect you after death. This verse dismantles human arrogance by reminding us of our humble origins."
  },
  2: {
    "˹For˺ indeed, We ˹alone˺ created humans from a drop of mixed fluids,": "Allah emphasizes that He alone is the Creator. The 'mixed fluids' refers to the combination of male and female reproductive cells that unite to form a new human being. From something so tiny and seemingly insignificant, Allah creates a complete human with bones, muscles, organs, intellect, and emotions. This miraculous process should remind us of Allah's power and wisdom. The One who created you from such humble beginnings is fully capable of recreating you on the Day of Judgment.",
    "˹in order˺ to test them,": "This is the purpose of human creation: to be tested. Life is an examination hall. Allah did not create humans for entertainment or without purpose. Every blessing, every hardship, every choice you face is part of this test. Will you be grateful or ungrateful? Will you obey or disobey? Will you remember your Creator or forget Him? The Prophet Muhammad (ﷺ) said: 'The world is a prison for the believer and a paradise for the disbeliever' (Sahih Muslim). This life is temporary, and our choices here determine our eternal destination.",
    "so We made them hear and see.": "Allah equipped humans with the essential tools needed to pass this test. Hearing and seeing are mentioned because they are the primary means through which humans receive guidance and learn. Through hearing, you can listen to the Quran, to good advice, and to the call to prayer. Through seeing, you can observe the signs of Allah in creation and read His Book. These faculties are gifts that come with responsibility. On the Day of Judgment, your ears, eyes, and skin will testify about how you used them (Quran 41:20-22). A person who has these abilities but does not use them to seek truth is worse than one who lacks them."
  },
  3: {
    "We already showed them the Way,": "Allah did not leave humans to figure out the truth on their own. He sent prophets, revealed scriptures, and placed within human nature an innate recognition of right and wrong (fitrah). The 'Way' refers to the straight path of Islam, the path of worshipping Allah alone and living according to His guidance. No one can claim on the Day of Judgment that they did not know, because Allah made the truth clear through multiple means. The Quran itself is called 'guidance for mankind' (Quran 2:185).",
    "whether they ˹choose to˺ be grateful or ungrateful.": "After being shown the Way, humans are given the freedom to choose. This is the essence of the test. You can choose to be grateful—accepting the truth, worshipping Allah, and living righteously. Or you can choose to be ungrateful—rejecting the truth, following your desires, and turning away from your Creator. Notice that gratitude here is equated with faith, and ingratitude is equated with disbelief. This is because true gratitude means acknowledging the source of all blessings (Allah) and living accordingly. The choice is yours, but so are the consequences."
  },
  4: {
    "Indeed, We have prepared for the disbelievers": "Allah states with certainty that punishment is already prepared and waiting. The word 'prepared' indicates that Hell and its torments already exist; they are not something to be created later. This should serve as a serious warning. The disbelievers mentioned here are those who knowingly reject the truth after it has been made clear to them, choosing ingratitude over gratitude.",
    "chains, shackles, and a blazing Fire.": "These are three elements of punishment that restrict movement and cause intense suffering. Chains will bind them, preventing any escape. Shackles will restrain their hands to their necks, adding to their humiliation and helplessness. And a blazing Fire will surround and burn them. This brief mention of punishment contrasts sharply with the detailed description of Paradise that follows, showing Allah's preference for mercy and encouragement over fear. The next surah (Al-Mursalat) will elaborate on the punishment in greater detail, while this surah focuses on the rewards of the believers."
  },
  5: {
    "Indeed, the virtuous will have a drink ˹of pure wine˺—": "The 'virtuous' (al-abrar) are those who fulfill their duties to Allah and to His creation. They are the people of goodness, righteousness, and piety. In Paradise, they will enjoy drinks that are pure, unlike the intoxicating and harmful wine of this world. The wine of Paradise brings pleasure without any negative effects—no headaches, no loss of senses, no sin. This is a reward for those who avoided forbidden drinks in this world out of obedience to Allah.",
    "flavoured with camphor—": "Camphor (kafur) gives the drink a cool, fragrant, and refreshing quality. In this world, camphor is known for its pleasant scent and cooling sensation. The drinks of Paradise will have the finest flavors and aromas, beyond anything experienced in this life. Every detail of Paradise is designed for perfect enjoyment and comfort."
  },
  6: {
    "˹from˺ a spring where Allah's servants will drink,": "This camphor-flavored drink comes from a special spring in Paradise. The fact that they are called 'Allah's servants' (ibad Allah) is a title of honor. These are people who lived their lives in willing submission to Allah, and now they are being served from exclusive springs reserved for them.",
    "flowing at their will.": "The believers will have complete control over this spring. Wherever they wish it to flow, it will flow. They can direct it to their homes, their gardens, anywhere they desire. In this world, water is often scarce, and people struggle to access it. In Paradise, the righteous will have springs that obey their commands. This represents the ultimate honor and ease that awaits the patient believers."
  },
  7: {
    "They ˹are those who˺ fulfil ˹their˺ vows": "Now Allah describes the qualities that earned these people Paradise. The first quality is fulfilling vows. When they make a promise to Allah—whether a specific vow or the general covenant of faith—they keep it. This reflects their integrity, sincerity, and commitment. In a world where people easily break promises, the believers stand out by honoring their word, especially to their Lord. The Prophet (ﷺ) said: 'The signs of a hypocrite are three: when he speaks, he lies; when he promises, he breaks it; and when he is trusted, he betrays' (Sahih Bukhari).",
    "and fear a Day of sweeping horror,": "The second quality is their fear of the Day of Judgment. They live with an awareness that a terrifying Day is coming—a Day whose horror will spread everywhere, affecting all of creation. This fear is not paralyzing; rather, it motivates them to do good and avoid evil. They understand that this life is temporary and that their actions have eternal consequences. This consciousness of the Hereafter shapes their daily choices."
  },
  8: {
    "and give food—despite their desire for it—": "The third quality is selfless generosity. They give food even when they themselves want it and need it. This is not giving from surplus; this is giving from what they love and desire. It is easy to give away what you don't need, but true virtue is giving what you yourself would want to keep. Allah says elsewhere: 'You will never attain righteousness until you spend from what you love' (Quran 3:92).",
    "to the poor, the orphan, and the captive,": "They feed three categories of vulnerable people. The poor (miskeen) are those who cannot meet their basic needs. The orphan (yateem) is a child who has lost their father and has no provider. The captive (aseer) could refer to prisoners of war or anyone in a state of helplessness and captivity. The believers care for all of them without discrimination. Feeding the hungry is one of the most beloved acts to Allah. The Prophet (ﷺ) said: 'The best of you is the one who feeds others' (Ahmad). This verse teaches that charity should reach the most vulnerable, not just those who are easy to help."
  },
  9: {
    "˹saying to themselves,˺ \"We feed you only for the sake of Allah,": "This verse reveals the intention behind their charity—the most important aspect of any good deed. They are not seeking fame, social status, or worldly benefit. Their sole motivation is to please Allah. This purity of intention (ikhlas) is what makes their deed truly valuable. A deed done for show has no value with Allah, but a deed done sincerely for His sake, even if small, is immensely rewarded.",
    "seeking neither reward nor thanks from you.": "They do not expect anything in return from those they help—no payment, no favor, not even a word of thanks. This is the highest level of generosity. Many people give charity but then expect gratitude, recognition, or favors in return. The truly virtuous give without any strings attached, knowing that their reward is with Allah alone. This also means they do not make the recipients feel indebted or humiliated."
  },
  10: {
    "We fear from our Lord a horribly distressful Day.\"": "Their motivation is further explained: they fear the Day of Judgment. The Day is described as 'aboos' (causing faces to frown with distress) and 'qamtareer' (extremely harsh and severe). On that Day, people's faces will be contorted with fear and anxiety. The believers work hard in this life because they understand the severity of that Day. This fear is healthy and productive—it drives them to good deeds and keeps them away from sin. Unlike the disbelievers who are heedless of that Day, the believers live with constant awareness of it."
  },
  11: {
    "So Allah will deliver them from the horror of that Day,": "Because of their sincere faith and righteous deeds, Allah will protect them from the terrors of the Day of Judgment. While others are drowning in fear and regret, these believers will be safe and secure. The very Day they feared becomes a Day of joy for them. This is the fruit of their conscious effort to please Allah in this world.",
    "and grant them radiance and joy,": "Instead of faces frowning with distress, their faces will be radiant and glowing with happiness. 'Nadrah' refers to the brightness and beauty that will appear on their faces, reflecting their inner joy. 'Suroor' is deep happiness and delight. Allah will replace their fear with peace, their anxiety with joy. This is the ultimate transformation—from fearing a Day to celebrating it."
  },
  12: {
    "and reward them for their perseverance": "Allah specifically mentions patience (sabr) as the quality being rewarded. Throughout their lives, they were patient in worshipping Allah, patient in avoiding sins, patient in facing hardships, and patient in dealing with difficult people. Patience is one of the most emphasized virtues in Islam. The Prophet (ﷺ) said: 'No one is given a gift better and more comprehensive than patience' (Sahih Bukhari). Their patience in this temporary life earns them eternal rewards.",
    "with a Garden ˹in Paradise˺ and ˹garments of˺ silk.": "Their reward is twofold: a Garden (Paradise) to live in, and silk garments to wear. In this world, silk was forbidden for Muslim men as a test, and it was expensive and rare. In Paradise, all believers will wear the finest silk. The Garden represents their home, and the silk represents their honor and luxury. Every comfort they delayed in this world will be given to them in a far superior form forever."
  },
  13: {
    "There they will be reclining on ˹canopied˺ couches,": "The believers will be in a state of complete relaxation and comfort. They will recline on luxurious couches with canopies, a sign of royalty and honor. In this world, people work hard and rarely get to truly rest. In Paradise, there is no work, no stress, no deadlines—only eternal comfort and enjoyment. The image of reclining suggests peace, dignity, and the absence of any need to rush or struggle.",
    "never seeing scorching heat or bitter cold.": "Paradise has a perfect climate. There will be no extreme heat of the sun to cause discomfort, and no bitter cold to make them shiver. The temperature will always be ideal. In this world, weather extremes cause suffering—heatwaves, freezing winters, droughts, and storms. In Paradise, all such discomfort is eliminated. Every aspect of the environment is designed for perfect pleasure."
  },
  14: {
    "The Garden's shade will be right above them,": "The shade of Paradise will be close and comforting, providing perfect cover. Unlike this world where shade can be hard to find on a hot day, in Paradise the shade comes to the believers. It is always near, always protective, always comfortable.",
    "and its fruit will be made very easy to reach.": "The fruit trees of Paradise will bend down to the believers, making it effortless to pick their fruits. Whether a person is standing, sitting, or reclining, the fruit will come within easy reach. There is no climbing, no stretching, no effort required. This illustrates how everything in Paradise is made convenient for its inhabitants. The phrase 'made very easy' (dhullilat tadhleelan) emphasizes that the trees are completely submissive to the will of the believers."
  },
  15: {
    "They will be waited on with silver vessels and cups of crystal—": "The believers will be served like royalty. Servants will circulate among them carrying vessels made of silver and cups made of crystal. Silver represents purity and beauty, while crystal represents clarity and elegance. In this world, eating from silver vessels was prohibited to prevent extravagance and arrogance. In Paradise, believers will enjoy what was restricted in this world as a reward for their obedience. They will be served, not serving—a complete reversal of the struggles of worldly life."
  },
  16: {
    "crystalline silver, filled precisely as desired.": "These cups combine the beauty of crystal (transparent and sparkling) with the value of silver—something not found in this world. They are a unique creation of Paradise. Furthermore, these cups will be filled exactly to the amount desired by each person. Not too much, not too little—perfectly measured according to individual preference. This shows the personalized nature of Paradise, where every detail caters to the wishes of its inhabitants. Allah knows exactly what each person wants and provides it perfectly."
  },
  17: {
    "And they will be given a drink ˹of pure wine˺ flavoured with ginger": "Another type of drink is described—this one flavored with ginger. In contrast to the camphor-flavored drink mentioned earlier (which has cooling properties), ginger provides warmth and a spicy, invigorating flavor. The Arabs valued ginger for its pleasant taste and its ability to aid digestion. The drinks of Paradise offer variety and pleasure, with different flavors for different preferences. Each drink is pure and beneficial, unlike the harmful drinks of this world."
  },
  18: {
    "from a spring there, called Salsabîl.": "This ginger-flavored drink comes from a spring named Salsabil. The name itself sounds smooth and flowing, suggesting a drink that flows easily and pleasantly down the throat. Some scholars say the name comes from the Arabic root meaning 'smooth flowing' or 'easy to swallow.' Just as Zamzam is a blessed spring in this world, Salsabil is a blessed spring in Paradise, reserved exclusively for the righteous."
  },
  19: {
    "They will be waited on by eternal youths.": "Young servants will circulate among the believers, serving them. These youths are 'mukhalladoon'—eternal, meaning they will never age, grow old, or die. They will always remain in the perfect state of youth and beauty, serving the inhabitants of Paradise forever. This is another aspect of the eternal bliss of Paradise, where nothing fades or deteriorates.",
    "If you saw them, you would think they were scattered pearls.": "These young servants are so beautiful and radiant that they resemble scattered pearls. Pearls are known for their luminous beauty, purity, and value. The image of 'scattered pearls' suggests many of them moving gracefully in all directions, their beauty catching the eye everywhere you look. This vivid imagery helps us understand the extraordinary beauty of everything in Paradise."
  },
  20: {
    "And if you looked around, you would see ˹indescribable˺ bliss and a vast kingdom.": "Wherever you turn your gaze in Paradise, you will see nothing but blessing, luxury, and pleasure (naeem). Additionally, you will see a vast kingdom (mulk kabeer)—endless in its expanse and grandeur. Each believer will have a kingdom so vast that it would take years to traverse. The Prophet (ﷺ) said that the lowest person in Paradise will have ten times the size of this world. This verse captures the overwhelming abundance that awaits the believers—blessings beyond imagination and a kingdom beyond measure."
  },
  21: {
    "The virtuous will be ˹dressed˺ in garments of fine green silk and rich brocade,": "The believers will wear the finest clothing: 'sundus' (fine, thin silk) and 'istabraq' (thick, rich brocade). The color green is specifically mentioned—green is associated with Paradise, life, and freshness. These are not ordinary clothes; they are garments of honor, far superior to any fabric in this world. The variety (thin and thick silk) suggests that believers will have multiple types of luxurious garments to choose from.",
    "and adorned with bracelets of silver,": "They will also be adorned with silver bracelets as jewelry. In other verses, gold bracelets are also mentioned. This shows that believers will be decorated with precious ornaments, symbols of royalty and honor. What was restricted or unattainable in this world becomes freely available in Paradise.",
    "and their Lord will give them a purifying drink.": "The most special drink of all—one given directly by their Lord. This drink is 'tahoor' (purifying), meaning it cleanses them both physically and spiritually. Some scholars say this drink purifies them of any remaining worldly attachments or negative feelings, preparing them for the ultimate pleasure: seeing Allah's Face. The fact that Allah Himself gives them this drink is the greatest honor imaginable, showing the closeness between the Lord and His righteous servants."
  },
  22: {
    "˹And they will be told,˺ \"All this is surely a reward for you.": "The believers will be informed that everything they are enjoying—the gardens, the clothes, the drinks, the servants, the palaces—is their earned reward. It is not random or undeserved; it is compensation for their faith, patience, and good deeds in the worldly life. This acknowledgment will increase their joy, knowing that their struggles were not in vain.",
    "Your striving has been appreciated.\"": "Allah appreciates their efforts. The word 'mashkoora' means appreciated, valued, and thanked. Imagine the Creator of the universe thanking you for your efforts! This is the ultimate validation. Every prayer they prayed, every fast they kept, every charity they gave, every temptation they resisted, every hardship they endured—all of it was seen, recorded, and appreciated by Allah. Nothing was wasted. This statement is one of the greatest rewards itself: to know that your Lord is pleased with you and grateful for your striving."
  },
  23: {
    "Indeed, it is We Who have revealed the Quran to you ˹O Prophet˺ in stages.": "Allah affirms that He is the One who revealed the Quran to Prophet Muhammad (ﷺ). The emphasis on 'We' (nahnu) highlights that this is a direct communication from the Almighty. The Quran was revealed 'tanzeelan'—gradually, in stages, over 23 years. This gradual revelation had many wisdoms: it made memorization easier, it allowed rulings to be revealed as situations arose, and it provided continuous support and guidance to the Prophet (ﷺ) and the believers. This reminder reassures the Prophet that his mission is divinely supported and his message is authentic."
  },
  24: {
    "So be patient with your Lord's decree,": "Allah commands the Prophet (ﷺ) to be patient. The early years of prophethood in Mecca were extremely difficult—the Prophet (ﷺ) faced rejection, mockery, persecution, and the torture of his followers. Despite all this, he is told to remain patient with whatever Allah has decreed. Patience here means continuing the mission without giving up, trusting Allah's timing, and not being discouraged by opposition. This command applies to all believers facing hardship in the path of truth.",
    "and do not yield to any evildoer or ˹staunch˺ disbeliever from among them.": "The Prophet (ﷺ) is warned not to obey or give in to the demands of sinners (those who commit evil) or disbelievers (those who reject faith). The enemies of Islam tried various tactics to make the Prophet (ﷺ) compromise his message—they offered wealth, power, and marriage alliances if he would just tone down his message. Allah commands him to stand firm and not compromise the truth to please anyone. This is a lesson for all Muslims: never compromise your faith to appease those who oppose Allah's guidance."
  },
  25: {
    "˹Always˺ remember the Name of your Lord morning and evening,": "The antidote to difficulty is the remembrance of Allah. The Prophet (ﷺ) is instructed to remember Allah throughout the day—in the morning (bukrah) and in the evening (aseelan). This includes the daily prayers, morning and evening adhkar (remembrances), and maintaining constant awareness of Allah. When you remember Allah frequently, you gain strength, peace, and perspective. Hardships become easier to bear when you are connected to the One who controls all affairs. The Prophet (ﷺ) himself said: 'The example of the one who remembers his Lord and the one who does not is like the example of the living and the dead' (Sahih Bukhari)."
  },
  26: {
    "and prostrate before Him during part of the night,": "Night prayer (tahajjud) is specifically commanded. There is something special about praying in the depths of the night when the world is asleep. It is a time of solitude, sincerity, and closeness to Allah. The Prophet (ﷺ) was known for his long night prayers, standing until his feet would swell. Night prostration demonstrates true devotion—when no one is watching, when it's difficult to leave the comfort of sleep, the believer still rises to worship.",
    "and glorify Him long at night.": "In addition to prostration (physical prayer), the Prophet (ﷺ) is told to glorify Allah (tasbeeh) for long periods during the night. This includes saying 'SubhanAllah' (Glory be to Allah), reciting Quran, making dua (supplication), and engaging in various forms of worship. The word 'long' (taweela) emphasizes that this is not just a quick act but an extended period of devotion. The night is a treasure trove of opportunity for those who wish to draw closer to Allah."
  },
  27: {
    "Surely those ˹pagans˺ love this fleeting world,": "Allah exposes the root problem of the disbelievers: they are obsessed with this temporary world (al-aajilah—the immediate, fleeting life). They prioritize worldly pleasures, wealth, status, and enjoyment over eternal success. This world, no matter how long one lives, is like a brief moment compared to eternity. Yet they pursue it as if it's all that matters.",
    "˹totally˺ neglecting a weighty Day ahead of them.": "In their pursuit of worldly pleasures, they completely ignore the Day of Judgment—a Day described as 'thaqeel' (heavy, weighty, significant). It is heavy because of its length (50,000 years), its terrors, and its consequences. Ignoring such a Day is the height of foolishness. It's like a student enjoying parties while ignoring a final exam that determines their entire future. The believers, in contrast, live with awareness of that Day and prepare for it."
  },
  28: {
    "It is We Who created them and perfected their ˹physical˺ form.": "Allah reminds the disbelievers that He is their Creator. He designed their bodies, made their joints firm, and gave them their physical form and abilities. Every muscle, bone, and organ is from Allah's creation. This reminder should humble them and make them recognize their dependence on Allah.",
    "But if We will, We can easily replace them with others.": "Allah has no need of them. If they persist in their disbelief, Allah can easily destroy them and replace them with other people who will be grateful and obedient. This is a warning against arrogance. No individual or nation is indispensable to Allah. History is full of examples of civilizations that were destroyed when they rejected their prophets and were replaced by others. This threat should shake anyone who thinks they can defy Allah without consequence."
  },
  29: {
    "Surely this is a reminder.": "This surah—indeed the entire Quran—is a reminder (tadhkirah). Its purpose is to wake people up from heedlessness, remind them of their purpose, and guide them to their Lord. Allah in His mercy keeps sending reminders through various means: verses, prophets, signs in nature, life experiences. The question is: will people pay attention?",
    "So let whoever wills take the ˹Right˺ Way to their Lord.": "The choice is presented clearly: whoever wants guidance can take the path to Allah. The door is open. The invitation is extended to everyone. There is no compulsion—each person must decide for themselves whether to accept or reject. This verse emphasizes human agency and responsibility. You cannot blame anyone else for your choices; the path has been shown, and the decision is yours."
  },
  30: {
    "But you cannot will ˹to do so˺ unless Allah wills.": "This verse clarifies the relationship between human will and divine will. Yes, humans have free will and can choose, but this ability to choose is itself granted by Allah. Nothing happens in the universe except by Allah's permission. This does not mean humans are forced—rather, Allah's will encompasses everything, including allowing humans to make choices. When someone wants to be guided, that desire itself is from Allah's mercy enabling them. This balance prevents both fatalism (\"I have no choice\") and arrogance (\"I did this all by myself\").",
    "Indeed, Allah is All-Knowing, All-Wise.": "Allah knows everything—every person's heart, every intention, every action, past, present, and future. He is also All-Wise (Hakeem)—every decree, every law, every event happens according to His perfect wisdom. Nothing is random or purposeless. Those who reject guidance do so despite Allah's knowledge that they will reject, and those who accept do so through His mercy and wisdom. Trusting in Allah's knowledge and wisdom brings peace, even when we don't understand why certain things happen."
  },
  31: {
    "He admits whoever He wills into His mercy.": "Allah's mercy is vast, but He grants it to whomever He wills—and His will is based on His knowledge and wisdom. Those who sincerely seek guidance, who humble themselves, who strive to obey—these are the ones Allah admits into His mercy. His mercy is not arbitrary; it goes to those who deserve it through their faith and actions. The righteous should never despair of Allah's mercy, and the sinners should never assume they will receive it without repentance.",
    "As for the wrongdoers, He has prepared for them a painful punishment.": "The surah ends with a final warning. Those who wrong themselves by disbelief, injustice, and sin—for them, a painful punishment is already prepared. The word 'prepared' (a'adda) indicates that the punishment exists and is waiting. This is not an empty threat; it is a certain reality. The 'wrongdoers' (dhalimeen) includes anyone who commits injustice—whether against Allah (by disbelief or shirk), against others (by oppression), or against themselves (by sinning). The only escape is through repentance and returning to Allah before it is too late."
  }
};