var tafsirData_73 = {
  1: {
    "O you wrapped ˹in your clothes˺!": "This is a tender and affectionate address from Allah to Prophet Muhammad (ﷺ). At the time of this revelation, the Prophet (ﷺ) had wrapped himself in his garment, possibly seeking comfort after the overwhelming experience of receiving revelation. This gentle call shows Allah's care for His messenger, like a loving parent calling to their child. It also marks the beginning of his prophetic duties—Allah is essentially saying, 'Rise up from your rest, for great work awaits you.' This teaches us that moments of rest are temporary, and we must prepare ourselves for the responsibilities Allah assigns to us."
  },
  2: {
    "Stand all night ˹in prayer˺ except a little—": "Allah commands the Prophet (ﷺ) to spend the night in prayer, with some allowance for rest. Night prayer (Qiyam al-Layl) was made obligatory for the Prophet (ﷺ) at this early stage of his mission. The night is a special time when the world is quiet, distractions are minimal, and the heart can focus entirely on connecting with Allah. This was preparation for the immense task ahead—carrying the message of Islam to all of humanity. Just as an athlete trains intensively before a competition, the Prophet (ﷺ) was being spiritually strengthened through worship before facing the challenges of prophethood."
  },
  3: {
    "˹pray˺ half the night, or a little less,": "Allah provides flexibility in the duration of night prayer. The Prophet (ﷺ) could pray for half the night or slightly less. This shows Allah's mercy—He does not burden His servants beyond their capacity. Even in obligatory worship, there is room for human limitation. This teaches us that Islam is a practical religion; it sets high standards while acknowledging human needs for rest and balance."
  },
  4: {
    "or a little more—": "The Prophet (ﷺ) also had the option to pray more than half the night if he wished. This flexibility allowed him to adjust based on his energy and circumstances. It demonstrates that worship should not become a burden that harms the worshipper, but rather a source of spiritual nourishment.",
    "and recite the Quran ˹properly˺ in a measured way.": "Allah instructs that the Quran should be recited with Tarteel—slowly, clearly, and thoughtfully, giving each word its due right. This is not about rushing through verses, but about pondering their meanings and allowing them to penetrate the heart. The Prophet (ﷺ) said: 'Beautify the Quran with your voices.' (Abu Dawud) When we recite slowly, we absorb the message, feel its weight, and allow it to transform us. Imagine reading a heartfelt letter from someone you love—you would read it slowly, savoring every word. This is how we should approach Allah's words."
  },
  5: {
    "˹For˺ We will soon send upon you a weighty revelation.": "Allah informs the Prophet (ﷺ) that the Quran being revealed to him is 'heavy' or 'weighty.' This refers to several aspects: the profound nature of its message, the responsibilities it brings, the impact it will have on humanity, and even the physical experience of receiving revelation (the Prophet (ﷺ) would sweat even on cold days when revelation came). The night prayers were preparation for carrying this tremendous burden. Just as a weightlifter trains before lifting heavy weights, the Prophet (ﷺ) was being spiritually conditioned. This also reminds us that the Quran is not light reading—it carries serious guidance that demands our attention and action."
  },
  6: {
    "Indeed, worship in the night is more impactful": "Allah explains why night prayer is so valuable. The Arabic word 'ashaddu wat'an' means it has a stronger impact on the soul. During the night, when the world sleeps, there are fewer distractions. The soul and body are more aligned, and worship becomes more sincere and focused. The Prophet (ﷺ) said: 'Our Lord descends every night to the lowest heaven when the last third of the night remains, and says: Who is calling upon Me that I may answer him? Who is asking of Me that I may give him? Who is seeking My forgiveness that I may forgive him?' (Bukhari & Muslim) This makes night prayer incredibly special.",
    "and suitable for recitation.": "The night hours are also better for recitation because it is quieter and the heart can focus on the words being recited. During the day, we have many responsibilities—work, family, errands—that compete for our attention. But at night, we can give the Quran our undivided attention, allowing the words to truly resonate within us."
  },
  7: {
    "For during the day you are over-occupied ˹with worldly duties˺.": "Allah acknowledges that daytime is filled with activities—spreading the message of Islam, meeting people, attending to needs, earning a livelihood, and managing daily affairs. This is a realistic acknowledgment of human life. We are not expected to pray all day and neglect our responsibilities. Rather, Islam teaches balance: fulfill your worldly duties during the day, and dedicate special time for intensive worship at night. This verse comforts anyone who feels overwhelmed—Allah understands that we have busy lives, and He provides times like the night for deeper spiritual connection."
  },
  8: {
    "˹Always˺ remember the Name of your Lord,": "Allah commands continuous remembrance (dhikr) of Him. This means keeping Allah in our thoughts throughout our daily activities—saying His name, praising Him, thanking Him, and being mindful of Him. Remembrance of Allah brings peace to the heart, as Allah says elsewhere: 'Verily, in the remembrance of Allah do hearts find rest.' (Quran 13:28) It is like staying connected to a power source that keeps us spiritually energized.",
    "and devote yourself to Him wholeheartedly.": "The word 'tabattul' means to cut off from everything else and dedicate oneself entirely to Allah. This doesn't mean abandoning worldly responsibilities, but rather making Allah the ultimate priority in your heart. Everything else—work, family, possessions—should be secondary to your relationship with Allah. When you pray, give yourself fully to that prayer. When you worship, let nothing distract your heart from Him."
  },
  9: {
    "˹He is the˺ Lord of the east and the west.": "Allah owns and controls everything from where the sun rises to where it sets—meaning the entire world and all that is in it. Nothing is outside His domain. This reminds us of His absolute power and sovereignty over all creation. When we understand that Allah controls everything, we realize that He alone deserves our worship and trust.",
    "There is no god ˹worthy of worship˺ except Him,": "This is the declaration of Tawheed—the oneness of Allah. No other deity, idol, or being deserves worship. Only Allah created us, sustains us, and will judge us. He alone has the power to benefit or harm. This fundamental truth is the foundation of Islam.",
    "so take Him ˹alone˺ as a Trustee of Affairs.": "Since Allah controls everything, we should entrust all our affairs to Him. A 'Wakeel' is someone you trust to handle your matters on your behalf. Allah is the best Trustee—He never sleeps, never forgets, and always knows what is best for us. When you face difficulties, delegate your worries to Allah. When you plan, rely on Allah for success. This brings immense peace because you know the Most Powerful is taking care of you."
  },
  10: {
    "Be patient ˹O Prophet˺ with what they say,": "Allah commands the Prophet (ﷺ) to exercise patience in the face of mockery, insults, and rejection from the disbelievers of Mecca. They called him names, accused him of being a madman or a sorcerer, and ridiculed his message. Patience (Sabr) is one of the most important qualities for anyone calling people to Allah. It means enduring hardship without losing faith or giving up. The Prophet (ﷺ) faced severe persecution, yet he remained steadfast. This teaches us that when we face criticism for our faith, we should not lose heart—patience is our shield.",
    "and depart from them courteously.": "The phrase 'beautiful departure' (Hijran Jameelan) means to distance yourself from harmful people without being rude, vengeful, or aggressive. The Prophet (ﷺ) was not to stoop to their level by responding with insults or anger. Instead, he was to maintain his dignity and character. This is a profound lesson in dealing with difficult people—you can disagree and distance yourself while still maintaining good manners. Think of it like walking away from an argument gracefully, without slamming doors or saying hurtful words."
  },
  11: {
    "And leave to Me the deniers—the people of luxury—": "Allah tells the Prophet (ﷺ) to leave the matter of the deniers to Him. The 'people of luxury' refers to the wealthy, arrogant leaders of Quraysh who rejected Islam. They were proud of their wealth, status, and comfortable lives, which made them dismiss the message of a simple, humble messenger. Allah is essentially saying, 'Don't worry about punishing them—that's My job.' This is reassuring because it removes the burden of seeking revenge or justice from the Prophet (ﷺ). He only needed to deliver the message; Allah would handle the rest.",
    "and bear with them for a little while.": "Allah asks the Prophet (ﷺ) to give them some time—but this time is not for their benefit. It is a respite before their punishment. Allah often gives wrongdoers time to repent, but if they persist, their punishment becomes more severe. The 'little while' indicates that their enjoyment of this world is temporary. No matter how long oppressors seem to prosper, their end is certain. This gives hope to the oppressed and serves as a warning to the oppressors."
  },
  12: {
    "˹For˺ We certainly have shackles,": "Allah describes what awaits the deniers in Hell. Shackles (Ankal) are heavy iron chains that will bind the disbelievers, preventing any escape. Imagine being bound so tightly that you cannot move—this is the humiliation and torment that awaits those who arrogantly rejected Allah's message. The same people who walked freely on earth, proud of their power, will be completely helpless.",
    "a ˹raging˺ Fire,": "Jahannam, the Hellfire, is described as raging and fierce—not an ordinary fire but one created by Allah specifically for punishment. The Prophet (ﷺ) said: 'The fire that the children of Adam kindle is one-seventieth part of the Fire of Hell.' (Muslim) This should inspire fear in our hearts and motivate us to avoid anything that leads to it."
  },
  13: {
    "choking food,": "Even the food in Hell will be a form of torture. It will be so bitter, thorny, or vile that it gets stuck in the throat, neither going down nor coming up. This is the opposite of the delicious, comfortable food the 'people of luxury' enjoyed in the world. Everything in Hell is designed to cause suffering—even what would normally bring comfort, like eating, becomes torment.",
    "and a painful punishment ˹in store for them˺": "Beyond the specific tortures mentioned, Allah describes a general painful punishment that encompasses all forms of suffering. The word 'Aleem' means intensely painful. This comprehensive punishment affects every part of the body and soul. It is a complete contrast to the temporary pleasures the deniers chose over eternal guidance."
  },
  14: {
    "on the Day the earth and mountains will shake ˹violently˺,": "This describes the Day of Judgment when the entire earth will tremble violently. The same ground we walk on with confidence will shake uncontrollably. Mountains, which symbolize stability and permanence, will not be spared. This cosmic upheaval shows that nothing in this world is truly permanent—only Allah's kingdom lasts forever.",
    "and mountains will be ˹reduced to˺ dunes of shifting sand.": "The mighty, solid mountains will become like loose sand dunes that scatter with the wind. Imagine the tallest, most majestic mountains you know turning into piles of sand blowing away—this is the power of that Day. If mountains cannot stand firm, how will arrogant humans who rejected Allah fare? This imagery humbles us and reminds us that our worldly power and structures mean nothing before Allah."
  },
  15: {
    "Indeed, We have sent to you a messenger as a witness over you,": "Allah addresses the people of Mecca, reminding them that Muhammad (ﷺ) has been sent as a messenger who will witness their deeds and testify about their response to his message on the Day of Judgment. A witness is someone who observes and reports—the Prophet (ﷺ) will report how his people received the truth. This should make us conscious that our acceptance or rejection of guidance is being recorded.",
    "just as We sent a messenger to Pharaoh.": "Allah draws a parallel between the Prophet (ﷺ) being sent to the Quraysh and Prophet Musa (Moses) being sent to Pharaoh. This comparison serves as a warning: 'Look at what happened when Pharaoh rejected his messenger!' The Quraysh knew the story of Pharaoh—how he was the most powerful ruler of his time yet was destroyed when he arrogantly rejected Allah's message. History was about to repeat itself if they did not take heed."
  },
  16: {
    "But Pharaoh disobeyed the messenger,": "Pharaoh's crime is summarized in one word: disobedience. Despite witnessing clear miracles—the staff turning into a snake, the plagues, the parting of the sea—Pharaoh stubbornly refused to believe and obey. His arrogance, pride, and love of power blinded him to the truth. This is a warning to all who let worldly status prevent them from submitting to Allah.",
    "so We seized him with a stern grip.": "Allah's punishment of Pharaoh was severe and decisive. He was drowned in the Red Sea along with his army—a humiliating end for someone who claimed to be a god. The phrase 'stern grip' (Akhzan Wabeelan) indicates an overwhelming, crushing punishment from which there was no escape. This shows that no matter how powerful someone appears, they are utterly helpless before Allah. The Quraysh leaders were being warned: 'Your fate will be similar if you follow Pharaoh's path.'"
  },
  17: {
    "If you ˹pagans˺ persist in disbelief, then how will you guard yourselves against ˹the horrors of˺ a Day": "Allah poses a rhetorical question to the disbelievers: If you reject faith now, what protection will you have on the Day of Judgment? In this world, the wealthy could buy protection, hire guards, or hide in fortresses. But on that Day, nothing will help. No wealth, no army, no connections—nothing will save a person from facing Allah. This question forces reflection: What is your plan for that Day?",
    "which will turn children's hair grey?": "This powerful imagery describes the sheer terror of the Day of Judgment. Young children, who naturally have dark hair, will be so horrified that their hair turns grey—something that normally only happens with old age and stress. If innocent children are affected this way, imagine how the guilty will feel! This metaphor conveys unimaginable fear and dread. The Day of Judgment is not something to take lightly."
  },
  18: {
    "It will ˹even˺ cause the sky to split apart.": "The sky, which appears so solid and unchanging above us, will crack and split on that Day. Everything we consider permanent and stable—the earth, the mountains, the sky—will fall apart. This shows the overwhelming nature of the Day of Judgment. The entire universe as we know it will be transformed. Allah's power extends over all creation, and He can undo everything He created.",
    "His promise ˹of judgment˺ must be fulfilled.": "Allah's promise of the Day of Judgment is certain and inevitable. Unlike human promises that can be broken, Allah's word is absolute. He has promised accountability, resurrection, and judgment—and it will happen exactly as He said. This statement closes the door on any false hope that maybe the Day of Judgment won't come. It will, and we must prepare."
  },
  19: {
    "Surely this is a reminder.": "Allah describes this surah—and the Quran as a whole—as a reminder. It reminds us of what we already know deep inside: that we have a Creator, that we will be accountable, and that we need guidance. Human beings are forgetful, and the Quran serves to wake us up from our heedlessness. It's not introducing completely new information; rather, it's reminding us of truths our souls recognize.",
    "So let whoever wills take the ˹Right˺ Way to their Lord.": "After delivering the reminder and warning, Allah leaves the choice to each individual. He does not force anyone to believe. Every person has free will to accept guidance or reject it. However, this freedom comes with responsibility—you will bear the consequences of your choice. This verse emphasizes human agency: the path to Allah is open, but you must choose to walk it. No one can make that decision for you."
  },
  20: {
    "Surely your Lord knows that you ˹O Prophet˺ stand ˹in prayer˺ for nearly two-thirds of the night, or ˹sometimes˺ half of it, or a third, as do some of those with you.": "Allah acknowledges the sincere efforts of the Prophet (ﷺ) and his companions. They took the earlier command so seriously that they would pray for extensive hours at night—sometimes two-thirds, sometimes half, sometimes a third of the night. They didn't have accurate clocks, so they estimated. Allah sees all their efforts, even when no human witness is present. This acknowledgment shows that Allah appreciates sincere worship, even when we struggle to fulfill it perfectly.",
    "Allah ˹alone˺ keeps a ˹precise˺ measure of the day and night.": "Only Allah knows exactly how long the night and day are at any given time of year. Humans in that era couldn't precisely measure time, especially without modern technology. Allah understands this limitation and doesn't hold us accountable for what we cannot accurately measure. This shows His fairness and understanding of human capabilities.",
    "He knows that you ˹believers˺ are unable to endure this, and has turned to you in mercy.": "Here comes the relief! Allah recognizes that maintaining such lengthy night prayers indefinitely would be too difficult for the believers. They have families, jobs, health concerns, and other responsibilities. So out of His mercy, Allah lightens the obligation. This is a beautiful example of how Allah never burdens a soul beyond its capacity (Quran 2:286). When something becomes genuinely difficult, Allah provides ease. This verse brought great comfort to the early Muslims who had been striving so hard.",
    "So recite ˹in prayer˺ whatever you can from the Quran.": "The obligation is now eased—pray whatever amount is easy and manageable for you. This doesn't mean abandoning night prayer altogether, but rather finding a sustainable practice. Even a small amount of sincere worship is valuable. The Prophet (ﷺ) said: 'The most beloved deed to Allah is the most regular and constant even if it were little.' (Bukhari) Consistency in a small amount is better than occasional bursts of intensive worship followed by burnout.",
    "He knows that some of you will be sick,": "Allah mentions legitimate reasons why people cannot maintain lengthy prayers. Illness weakens the body and may prevent long standing in prayer. Islam accommodates this—the sick can pray sitting, lying down, or even with gestures if necessary. This shows that Allah's religion is realistic about human limitations.",
    "some will be travelling throughout the land seeking Allah's bounty,": "Travelers and businesspeople are also given consideration. Those who travel for trade and livelihood face exhaustion and irregular schedules. Seeking halal (permissible) income is itself a form of worship when done with the right intention. Allah does not expect someone exhausted from travel to pray all night.",
    "and some fighting in the cause of Allah.": "Warriors and defenders of the Muslim community face unique challenges. They need rest to be effective in protecting others. Sleep deprivation could endanger their lives and the community's safety. Allah considers all circumstances when easing religious obligations.",
    "So recite whatever you can from it.": "Allah repeats the ease—pray whatever amount you can manage. This repetition emphasizes that the concession is real and meant to be acted upon. There's no guilt in taking the easier option when Allah Himself has offered it.",
    "And ˹continue to˺ perform ˹regular˺ prayers,": "While the lengthy night prayers are eased, the five daily obligatory prayers remain. These are the non-negotiable foundation of a Muslim's worship. They are spread throughout the day and take only a short time, making them manageable for everyone.",
    "pay alms-tax,": "Zakat, the obligatory charity, is paired with prayer. Worship of Allah includes both spiritual acts (prayer) and social responsibility (charity). Giving zakat purifies wealth and helps the needy. It ensures that wealth circulates in society rather than accumulating only with the rich.",
    "and lend to Allah a good loan.": "This refers to voluntary charity beyond the obligatory zakat. When we give for Allah's sake, it's like giving Allah a loan that He will repay with enormous interest. Allah doesn't need our money—He is using this metaphor to encourage generosity. Any good deed 'loaned' to Allah will be multiplied many times over.",
    "Whatever good you send forth for yourselves, you will find it with Allah far better and more rewarding.": "Everything good we do in this life—prayers, charity, kindness, patience—is deposited in our account with Allah. We will find it waiting for us in the Hereafter, but in a far better form. A single date given in charity might become a mountain of reward. A moment of prayer might become eternal gardens. Invest in your afterlife now, while you have the chance.",
    "And seek Allah's forgiveness.": "Despite our best efforts, we will make mistakes and fall short. Therefore, always ask Allah for forgiveness. Istighfar (seeking forgiveness) cleanses us of sins and brings us closer to Allah. The Prophet (ﷺ) himself sought forgiveness more than 70 times a day, even though he was sinless. It keeps us humble and connected to Allah.",
    "Surely Allah is All-Forgiving, Most Merciful.": "The surah ends with hope and reassurance. No matter what sins we have committed or how much we have fallen short, Allah is ready to forgive. His mercy is vast, and His forgiveness is available to anyone who sincerely seeks it. This conclusion encourages believers to never despair of Allah's mercy and to keep trying, knowing that He is always ready to accept their repentance."
  }
};