var tafsirData_82 = {
  1: {
    "When the sky splits open": "On the Day of Judgment, the sky as we know it will tear apart and break open. The sky, which appears so stable and perfectly structured above us, will be completely destroyed. This is one of the first signs that the entire universe is coming to an end. Allah mentions the sky first because it represents the vastness and stability of creation—yet even this mighty structure will not survive that Day. This reminds us that everything in this world, no matter how permanent it seems, is temporary and will eventually come to an end by Allah's command."
  },
  2: {
    "and when the stars fall away": "The stars, which appear fixed and eternal in the night sky, will scatter and fall from their places. These massive celestial bodies that have guided travelers and amazed humanity for thousands of years will lose their positions and come crashing down. In Surah At-Takwir (81:2), Allah similarly says the stars will lose their light and fall. This shows that the entire cosmic order will collapse. The stars that people once worshipped or used for astrology will be rendered completely powerless, proving that only Allah has true and lasting power."
  },
  3: {
    "and when the seas burst forth": "The oceans and seas will explode and overflow, breaking all their natural boundaries. Some scholars explain this means the seas will merge together, while others say they will erupt with fire or flood the entire earth. The seas, which cover most of our planet and contain countless creatures, will no longer remain in the limits Allah set for them. In our daily life, we see how the ocean stays within its shores—this is by Allah's design. But on that Day, all these natural laws will cease to function. This is a powerful reminder that the systems we take for granted exist only because Allah maintains them."
  },
  4: {
    "and when the graves spill out": "The graves will be overturned and will release the dead bodies within them. Every human being who ever lived and died will be brought back to life and raised from their graves for judgment. This is the resurrection that many disbelievers denied. No matter where a person died—whether buried in the earth, drowned in the sea, or burned to ashes—Allah will reassemble them completely. The Prophet Muhammad (peace be upon him) said that between the two blows of the trumpet, people will remain dead for forty (years, months, or days—only Allah knows), and then they will be resurrected. This verse confirms that death is not the end; rather, it is a transition to the eternal life of the Hereafter."
  },
  5: {
    "˹then˺ each soul will know what it has sent forth or left behind": "When all these catastrophic events occur, every single person will finally come to know their complete record—both what they did during their lifetime (sent forth) and what they left behind. 'What it has sent forth' refers to all the deeds a person performed: prayers, charity, sins, kindness, and cruelty. 'What it left behind' refers to the ongoing effects of their actions—good or bad traditions they started, children they raised, knowledge they taught, or harm they caused that continued after their death. The Prophet (peace be upon him) said: \"When a person dies, their deeds end except for three: ongoing charity, beneficial knowledge, or a righteous child who prays for them\" (Sahih Muslim). On that Day, there will be no confusion or forgetfulness—every person will see their entire record with complete clarity, and they will have no excuse."
  },
  6: {
    "O humanity! What has emboldened you against your Lord, the Most Generous": "Allah addresses all of mankind with a profound question: What has deceived you and made you so bold as to disobey your Lord, Who is the Most Generous? This is a wake-up call to every human being who sins, ignores Allah's commands, or lives carelessly without thinking about their Creator. The fact that Allah describes Himself here as 'the Most Generous' (Al-Kareem) is deeply significant. Despite His generosity—giving us life, health, sustenance, and countless blessings—many people still turn away from Him and disobey His commands. It is as if Allah is saying: 'I have been so kind and generous to you, so what made you think you could disobey Me?' Some scholars say people are deceived by Allah's patience and the delay of punishment. Others say it is ignorance, false hopes, or the whispers of Shaytan. Whatever the cause, this verse forces us to reflect: How can we sin against the One Who has given us everything?"
  },
  7: {
    "Who created you, fashioned you, and perfected your design": "Allah reminds humanity of His immense favors by describing the stages of human creation. First, He created you from nothing—you did not exist, and He brought you into existence. Then He 'fashioned you' (sawwaka), meaning He shaped you in a balanced and proper form, giving you a complete body with all its parts in the right places. Finally, He 'perfected your design' (fa'adalak), meaning He proportioned you perfectly—your eyes, ears, hands, and feet are all in harmony and balance. Imagine if one arm was longer than the other, or if the eyes were placed on the back of the head—life would be impossible. But Allah, in His wisdom, designed the human body with perfect proportion. This should make us grateful and humble, not arrogant and disobedient."
  },
  8: {
    "moulding you in whatever form He willed": "Allah assembled and composed you in whatever form He chose. He decided your height, your features, your skin color, and every detail of your appearance. You had no say in how you would look—it was entirely Allah's decision. This is a reminder that we are completely dependent on Allah's will. He could have created us in any form—like animals, or with disabilities, or in a form considered unattractive—but He chose to honor humanity with the best of forms, as He says in Surah At-Tin (95:4): 'We have certainly created man in the best of stature.' This should inspire gratitude, not arrogance. No one should be proud of their beauty or ashamed of their appearance, because both are from Allah's decree."
  },
  9: {
    "But no! In fact, you deny the ˹final˺ Judgment": "After mentioning His favors, Allah exposes the real problem: despite all these blessings, you still deny the Day of Judgment! The word 'Kalla' (But no!) is a strong rejection and rebuke. The 'Deen' here refers to the Day of Recompense—the Day when everyone will be judged and rewarded or punished according to their deeds. Many people live as if there is no accountability, as if this life is all there is. They deny or ignore the reality that one day they will stand before Allah. This denial is the root of all disobedience. If someone truly believed they would be held accountable for every action, they would live very differently. The Quran repeatedly emphasizes belief in the Last Day because it transforms behavior."
  },
  10: {
    "while you are certainly observed by vigilant": "Allah informs us that we are constantly being watched by guardian angels who are assigned to record our deeds. The word 'Hafizeen' means protectors or guardians who carefully preserve and watch over something. These angels never leave us; they are with us day and night, in public and in private. Many people sin in secret, thinking no one can see them. But this verse reminds us that even when we are alone, we are never truly alone—angels are recording everything. This should make us conscious of our actions at all times. The Prophet (peace be upon him) said: \"Every person has angels taking turns watching over him, by night and by day\" (Bukhari and Muslim)."
  },
  11: {
    "honourable angels, recording ˹everything˺": "These angels who watch over us are described as 'Kiraman' (honorable, noble) and 'Katibeen' (writers, scribes). They are noble in their character and status with Allah, and they faithfully record every deed without error or omission. Nothing escapes their attention—whether it is a spoken word, a hidden thought that leads to action, or a deed done in complete secrecy. As Allah says in Surah Qaf (50:18): 'Not a word does he utter but there is a watcher by him ready to record.' The fact that these angels are 'honorable' also means they do not wrong anyone; they record only what actually happens, with complete accuracy and fairness."
  },
  12: {
    "They know whatever you do": "These recording angels have complete knowledge of all your actions. Nothing is hidden from them—not the obvious deeds nor the subtle ones, not the public actions nor the private ones. This verse emphasizes that the recording is comprehensive and precise. Some people might think they can hide their sins from others, and they might succeed in deceiving fellow humans. But they can never hide from the angels, and certainly never from Allah Who appointed these angels. This knowledge should inspire a sense of accountability in our hearts. A wise person lives knowing that every moment is being documented and that one day, this record will be presented before the Lord of all creation."
  },
  13: {
    "Indeed, the virtuous will be in bliss": "Allah now contrasts the two groups of people and their eternal destinations. The 'Abrar' (the righteous, the pious, the virtuous) are those who obeyed Allah, fulfilled their duties, and stayed away from sins. Their reward is 'Na'eem'—complete bliss, comfort, and pleasure in Paradise. This is not temporary happiness like the pleasures of this world; it is eternal joy without any pain, worry, or decline. The Prophet (peace be upon him) described Paradise as containing \"what no eye has ever seen, no ear has ever heard, and what has never occurred to a human heart\" (Bukhari and Muslim). This verse gives hope to the believers that their patience, struggles, and sacrifices in this world will be rewarded with unimaginable bliss."
  },
  14: {
    "and the wicked will be in Hell": "In contrast to the righteous, the 'Fujjar' (the wicked, the sinful, the rebellious) will be in 'Jaheem'—the blazing Hellfire. These are the people who rejected faith, lived lives of disobedience, and persisted in sin without repentance. Their destination is the opposite of bliss; it is severe punishment and torment. The Quran frequently pairs the mention of Paradise with Hell to give both hope and warning. This balance encourages believers to strive for Paradise while also warning them to avoid the path that leads to Hell. The wicked are not only disbelievers but also those who knew the truth and deliberately rejected it."
  },
  15: {
    "burning in it on Judgment Day": "The wicked will enter Hell and burn in its flames on the Day of Judgment. The word 'Yaslawnaha' means they will be exposed to its heat and burn in it directly. This punishment begins on the Day of Judgment and continues for eternity for those who deserve it. The Day of Judgment (Yawm al-Deen) is repeatedly mentioned to emphasize that it is real and unavoidable. On that Day, the truth will become clear to everyone, and the punishment will commence for those who rejected faith and lived in sin."
  },
  16: {
    "and they will have no escape from it": "Once the wicked enter Hell, they will never be able to leave or escape from it. They will not be absent from it even for a moment. There is no break, no vacation, no relief from the punishment. In this world, even prisoners get released eventually, and even the sick sometimes recover. But in Hell, the punishment is continuous and eternal for those who deserve eternal punishment. Allah says in Surah Al-Zukhruf (43:77) that the people of Hell will call out to be destroyed, but the punishment will remain. This verse removes any false hope that sinners might have about escaping accountability."
  },
  17: {
    "What will make you realize what Judgment Day is?": "Allah poses a powerful rhetorical question to emphasize the magnitude of the Day of Judgment. The phrase 'Wa ma adraka' (What will make you realize/know) is used in the Quran to highlight something extremely great and beyond human comprehension. It is as if Allah is saying: You cannot possibly imagine how tremendous this Day will be. No matter how much we read or hear about it, we cannot fully grasp its reality until we experience it. This question is meant to shake the listener out of heedlessness and make them take the Day of Judgment seriously."
  },
  18: {
    "Again, what will make you realize what Judgment Day is?": "Allah repeats the question for emphasis, adding the word 'Thumma' (then, again) to intensify the meaning. This repetition is a rhetorical device to stress the overwhelming nature of that Day. When something is repeated in the Quran, it indicates extreme importance. The Day of Judgment is so severe, so momentous, and so terrifying that even two questions cannot fully convey its reality. This should make every person stop and reflect deeply about their preparation for that Day. Are we ready to face it? Have we done enough good deeds? Have we sincerely repented from our sins?"
  },
  19: {
    "˹It is˺ the Day no soul will be of ˹any˺ benefit to another whatsoever": "After building up the question, Allah now provides the answer: Judgment Day is the Day when no person will be able to help another person in any way. In this world, we rely on family, friends, connections, and wealth to solve our problems. A rich person can bail out a relative, a powerful person can use their influence. But on that Day, all such support systems will be useless. Parents will not be able to help their children, and children will not be able to help their parents. As Allah says in Surah Abasa (80:34-37): 'On that Day, a man will flee from his brother, and his mother and father, and his wife and children.' Everyone will be concerned only with themselves. This should motivate us to build our own account of good deeds rather than relying on others.",
    "for all authority on that Day belongs to Allah ˹entirely˺": "On that Day, all command, sovereignty, and authority will belong exclusively to Allah. In this world, people have various levels of power and authority—kings, presidents, judges, and leaders. But on the Day of Judgment, all worldly power will be stripped away, and only Allah's authority will remain. He alone will judge, and no one can question His judgment or override His decisions. As Allah says in Surah Ghafir (40:16): 'Whose is the kingdom this Day? It is Allah's, the One, the Irresistible.' This final verse brings the surah to a powerful conclusion, reminding us that ultimately, we all return to Allah, and He alone will determine our eternal fate."
  }
};