var tafsirData_107 = {
  1: {
    "Have you seen": "This is a powerful rhetorical question from Allah to the Prophet (ﷺ) and to every listener. It draws attention and invites reflection, as if saying: 'Do you know who this type of person really is? Let Me show you their true nature.' It is meant to create awareness about a dangerous character that exists in society.",
    "the one who denies the ˹final˺ Judgment": "This refers to the person who rejects and disbelieves in the Day of Recompense—the Day when all people will stand before Allah to be held accountable for their deeds. This denial is not just a verbal rejection; it manifests in how they live their life. When someone truly believes in accountability before Allah, it transforms their behavior. But when they deny it, they feel free to act selfishly without fear of consequences. The verses that follow will show exactly how this denial appears in their actions toward others."
  },
  2: {
    "That is the one who repulses the orphan": "Here Allah reveals the first sign of someone who denies the Judgment: they push away, mistreat, and harshly reject the orphan. The word 'repulses' indicates forceful rejection—not just neglecting the orphan, but actively driving them away with harshness and contempt. The orphan, having lost their father, is among the most vulnerable in society and deserves compassion and care. The Prophet (ﷺ) himself was an orphan and showed immense care for orphans throughout his life. He said: 'I and the one who sponsors an orphan will be like this in Paradise,' and he held up his index and middle fingers close together (Sahih al-Bukhari). A person who believes in standing before Allah would never mistreat such a vulnerable person, knowing they will be questioned about it. But the one who denies that Day feels no accountability, so they oppress the weak without hesitation."
  },
  3: {
    "and does not encourage the feeding of the poor": "The second sign of the denier is that they neither feed the poor themselves nor encourage others to do so. Notice that Allah mentions 'encouraging' others—meaning even if this person cannot personally feed the poor, they should at least motivate and inspire others to help. But they do neither. Their heart is so hardened and self-centered that the suffering of hungry, needy people does not move them at all. They see poverty around them and feel no responsibility. This is a direct result of denying the Hereafter: if there is no Day of Judgment, why bother helping anyone? In contrast, believers are described in Surah Al-Insan (76:8-9) as feeding the poor, the orphan, and the captive, saying: 'We feed you only for the sake of Allah. We wish not from you reward or gratitude.' True faith produces compassion and generosity, while denial of the Hereafter produces coldness and stinginess."
  },
  4: {
    "So woe": "This is a severe warning and declaration of destruction. 'Woe' (Wayl) in Arabic indicates extreme loss, punishment, and ruin. Some scholars say it is also a valley in Hell reserved for certain sinners. This word should make every reader pause and reflect seriously on what follows.",
    "to those ˹hypocrites˺ who pray": "At first, this phrase seems shocking—how can there be 'woe' for those who pray? But Allah immediately clarifies in the next verses that this refers to a specific type of people who pray. They are called 'hypocrites' in the translation because they perform the outward act of prayer but lack sincerity. Their prayer is a shell without a soul. The following verses explain exactly what is wrong with their prayer. This teaches us that Islam is not about empty rituals; it is about genuine worship that transforms the heart and behavior."
  },
  5: {
    "yet are unmindful of their prayers": "These are people who are heedless, careless, and negligent regarding their prayers. This does not mean occasional distraction during prayer—which happens to everyone—but rather a persistent attitude of not caring about prayer at all. They delay their prayers beyond their proper times without valid excuse. They pray lazily and carelessly, rushing through it without any focus or humility. Their hearts are completely absent from the prayer. The Prophet (ﷺ) described the hypocrites' prayer: 'This is the prayer of the hypocrite: he sits watching the sun until it is between the two horns of Shaytan (close to setting), then he gets up and pecks four units, not remembering Allah in them except a little' (Sahih Muslim). Notice that Allah says they are unmindful 'of' their prayers (عَن صَلَاتِهِمْ), not 'in' their prayers. Being distracted 'in' prayer sometimes is human nature, but being heedless 'of' prayer—meaning not caring about its time, its quality, or its significance—is the sign of hypocrisy."
  },
  6: {
    "those who ˹only˺ show off": "This verse exposes their true intention: they pray only to be seen by people, not to worship Allah. Their prayer is a performance for human eyes, not a conversation with their Creator. This is called 'riya' (showing off), which is a form of hidden polytheism because the person is seeking the approval of creation rather than the Creator. The Prophet (ﷺ) said: 'The thing I fear most for you is minor shirk (polytheism).' The companions asked, 'What is minor shirk, O Messenger of Allah?' He said: 'Showing off (riya). Allah will say on the Day of Resurrection when people are being recompensed for their deeds: Go to those for whom you were showing off in the world and see if you find any reward with them' (Musnad Ahmad). When a person shows off in worship, their deed becomes worthless because it was not done sincerely for Allah. This is why sincerity (ikhlas) is the soul of every act of worship."
  },
  7: {
    "and refuse to give ˹even the simplest˺ aid": "The surah concludes by describing another trait of these hypocrites: they withhold even the smallest, most basic items of assistance from others. 'Al-Ma'un' refers to simple everyday items that neighbors and community members typically share or lend to one another—things like a pot, a bucket, salt, water, a knife, or similar household necessities. These items cost the lender nothing, yet these people refuse to share them. This reveals the extreme stinginess and selfishness in their hearts. If they refuse to give such small, insignificant things, imagine how they would behave regarding greater acts of charity! This verse connects back to the beginning of the surah: the one who denies the Day of Judgment has no motivation to help others because they see no benefit in it for themselves. Their lack of faith in accountability produces a completely self-centered existence. The surah thus paints a complete picture: denial of the Hereafter leads to cruelty toward the weak, neglect of the poor, hypocritical worship, showing off, and withholding even the simplest kindness from others. True faith, in contrast, produces genuine worship, sincere compassion, and generosity in both big and small matters."
  }
};