var tafsirData_95 = {
  1: {
    "By the fig and the olive ˹of Jerusalem˺": "Allah begins this surah by swearing an oath by the fig and the olive. These are blessed fruits associated with the land of Palestine and Jerusalem, where many prophets lived and preached, including Prophet Isa (Jesus), peace be upon him. When Allah swears by something in the Quran, it highlights the importance of what is being sworn upon and what follows. The fig and olive represent lands of revelation, sacred history, and divine guidance. Some scholars say these fruits themselves are symbols of blessing and benefit to humanity, reminding us of Allah's countless provisions."
  },
  2: {
    "and Mount Sinai": "Allah continues the oath by swearing by Mount Sinai, the sacred mountain where Prophet Musa (Moses), peace be upon him, received direct revelation from Allah and was given the Torah. This mountain witnessed one of the most significant events in human history—Allah speaking directly to a human being. By mentioning Mount Sinai, Allah connects this surah to the legacy of prophethood and divine communication, emphasizing that the message being delivered is part of the same chain of truth that came to previous prophets."
  },
  3: {
    "and this secure city ˹of Mecca˺!": "The oath concludes with Mecca, the city where Prophet Muhammad, peace be upon him, was born and received the Quran. Allah describes Mecca as 'secure' because it has been a sanctuary since the time of Prophet Ibrahim (Abraham), where fighting and hunting are forbidden. This city houses the Kaaba, the first house built for the worship of Allah. By swearing by these three sacred locations—Jerusalem, Mount Sinai, and Mecca—Allah connects the three major revelations (the Gospel, the Torah, and the Quran) and their prophets, showing the unity of the divine message throughout history."
  },
  4: {
    "Indeed, We created humans in the best form": "After the powerful oaths, Allah now reveals the purpose: to declare that human beings have been created in the most excellent and balanced form. This refers to both the physical beauty and upright stature of humans, as well as their intellectual, spiritual, and moral capacity. Unlike other creatures, humans were given reason, conscience, the ability to distinguish right from wrong, and the potential to know and worship Allah. Allah honored humanity by making them His representatives on earth, giving them faculties no other creation possesses. The Prophet Muhammad, peace be upon him, said: 'Allah created Adam in His image,' meaning with attributes like hearing, seeing, and knowledge, though in a limited human form. This verse reminds us of our noble origin and the dignity Allah bestowed upon us."
  },
  5: {
    "But We will reduce them to the lowest of the low ˹in Hell˺": "Despite being created in the best form, those who reject faith and disobey Allah will be cast down to the lowest depths of Hellfire. This is a stark warning that the honor Allah gave humanity can be lost through disbelief and wickedness. When people deny their Creator, reject the guidance sent to them, and live in sin and arrogance, they debase themselves from the highest potential to the lowest destination. Some scholars also interpret this as referring to the natural decline of old age, where a person becomes weak and dependent—but the majority view is that it refers to the spiritual and eternal downfall of the disbelievers in the Hereafter. It is like someone given a palace who chooses to live in a garbage dump—such is the person who abandons faith despite being given every faculty to recognize the truth."
  },
  6: {
    "except those who believe and do good": "Allah makes an exception for those who have faith in Him and accompany that faith with righteous deeds. True belief is not merely words; it must be demonstrated through actions. These are the people who fulfill the purpose of their creation—they recognize their Lord, follow His guidance, and live righteously. They maintain the honor Allah gave them by using their faculties for good.",
    "they will have a never-ending reward": "For such believers, there awaits a reward that will never be cut off or diminished. Unlike worldly rewards that eventually end, the reward of Paradise is eternal and continuous. The word 'غَيْرُ مَمْنُونٍ' means it will not be interrupted, reduced, or given with any reminder of favor that would diminish its joy. Allah will grant them blessings without limit, without end, and without any expectation of return. This is the ultimate success—eternal bliss with no fear of it ever being taken away."
  },
  7: {
    "Now, what makes you deny the ˹final˺ Judgment?": "This is a direct, rhetorical question to those who reject the Day of Judgment. After presenting such clear evidence—the sacred places of revelation, the noble creation of humanity, the consequences of disbelief, and the promise for believers—what possible excuse remains for denying the reality of accountability before Allah? The question exposes the irrationality of denial. You have been created in the best form, given intellect to reason, and sent messengers with clear signs. After all this, what could possibly make you reject the truth that you will stand before Allah and answer for your deeds? This verse addresses the stubborn disbelievers of Mecca, like Abu Jahl and others, who despite seeing the Prophet's character and the Quran's miracles, persisted in denial. The verse implies that such denial is not based on evidence but on arrogance and desire."
  },
  8: {
    "Is Allah not the most just of all judges?": "The surah concludes with another powerful rhetorical question affirming Allah's perfect justice. If Allah is the Most Just—and He certainly is—then how can there be no Day of Judgment? Justice demands that the oppressor and the oppressed, the believer and the disbeliever, the righteous and the wicked, cannot all end up the same way. There must be a day when accounts are settled and justice is served. This world is full of injustices that go unpunished and good deeds that go unrewarded. The existence of a Just God necessitates the existence of a Day of Judgment. The Prophet Muhammad, peace be upon him, taught that when one recites this verse, they should respond: 'بَلَى وَأَنَا عَلَى ذَٰلِكَ مِنَ الشَّاهِدِينَ' (Yes indeed, and I am a witness to that). This affirmation reminds the believer that Allah's justice will prevail, and no deed—good or bad—will be overlooked."
  }
};