var tafsirData_51 = {
  1: {
    "By the winds scattering ˹dust˺": "Allah swears by the winds that scatter dust, seeds, and particles across the earth. This is one of Allah's magnificent signs in nature. The winds are essential for life—they carry rain clouds, spread seeds for plants, and distribute pollen. Allah uses these powerful natural phenomena as oaths to draw attention to the truth that follows. When the Creator swears by His creation, it emphasizes the importance of what comes next. Just as you witness winds moving things from place to place daily, this reminds you of Allah's control over all things, including bringing souls back to life."
  },
  2: {
    "and ˹the clouds˺ loaded with rain": "Allah then swears by the clouds that carry heavy loads of water. These clouds travel across the sky, holding immense quantities of rain that bring life to dead lands. This is a powerful reminder of Allah's ability to give life. If Allah can send clouds carrying water to revive barren, lifeless earth, then surely He can bring the dead back to life on the Day of Judgment. The Prophet (ﷺ) said: 'Allah's mercy is divided into one hundred parts. He kept ninety-nine parts with Him and sent down one part to earth, and because of that one part, creatures are merciful to one another.' The rain is part of that mercy."
  },
  3: {
    "and ˹the ships˺ gliding with ease": "Allah swears by the ships that sail smoothly across the seas. Despite the ocean's vastness and the weight of ships, they glide effortlessly by Allah's design. He created water with properties that allow ships to float, and He created wind to push them forward. This demonstrates Allah's perfect planning and control over nature. Ships carrying goods and people across oceans show how Allah facilitates human life and trade. If Allah can make heavy vessels move smoothly on water, then organizing the Day of Judgment is certainly within His power."
  },
  4: {
    "and ˹the angels˺ administering affairs by ˹Allah's˺ command": "Finally, Allah swears by the angels who distribute and execute His commands throughout creation. Angels are assigned various tasks—some bring rain, some take souls, some record deeds, and some deliver revelation. Angel Jibreel (Gabriel) brought the Quran to Prophet Muhammad (ﷺ), while Angel Mikael (Michael) oversees provision and rain. These angels work in perfect obedience, carrying out Allah's orders without question. This organized system of angels managing the universe proves that the Day of Judgment, which angels will also administer, is absolutely real and will occur as promised."
  },
  5: {
    "Indeed, what you are promised is true": "After these powerful oaths, Allah delivers the conclusion: everything you have been promised—resurrection, judgment, paradise, and hellfire—is absolutely true. This is not mythology or ancient tales, but certain reality. The deniers of Mecca mocked the idea of being raised after death, but Allah confirms through these oaths that His promise is as real as the winds you feel, the rain you see, and the ships you watch sailing. The Prophet (ﷺ) conveyed this message with complete certainty because it came from the Lord of all creation."
  },
  6: {
    "And the Judgment will certainly come to pass": "The Day of Judgment—when every soul will be recompensed for its deeds—will definitely happen. There is no doubt, no possibility of it being cancelled or delayed beyond its appointed time. Just as day follows night with certainty, the Day of Recompense will arrive. Allah uses the word 'certainly' to emphasize that this is not a matter of 'if' but 'when.' Many people live as though this day will never come, but Allah confirms its absolute certainty. The Prophet (ﷺ) said: 'The Hour will not be established until... the sun rises from the west.' Every sign points to its coming."
  },
  7: {
    "˹And˺ by the heavens in their marvellous design": "Allah takes another oath, this time by the sky with its beautiful, intricate pathways and patterns. Look up at the sky—the orbits of celestial bodies, the layers of atmosphere, the stunning arrangement of stars and galaxies—all display perfect design and harmony. No chaos, no collision of systems, everything moves in precise order. This marvellous design points to a Designer with infinite wisdom. If Allah created such perfection in the heavens, would He leave humanity without purpose, without accountability? The magnificent sky itself testifies that there must be a Day when the purpose of creation is fulfilled."
  },
  8: {
    "Surely you are ˹lost˺ in conflicting views ˹regarding the truth˺": "Allah addresses those who oppose the message, pointing out that they hold contradictory and confused positions about the truth. Some called the Prophet (ﷺ) a poet, others a magician, others a madman—their accusations kept changing because they had no consistent argument. Similarly, about the afterlife, some denied it completely while others were unsure. This inconsistency reveals that their rejection is not based on genuine reasoning but on stubbornness and desire to avoid accountability. When people reject truth, their alternative explanations never make sense and keep contradicting each other."
  },
  9: {
    "Only those ˹destined to be˺ deluded are turned away from it": "Only those who are meant to be led astray—due to their own choice of misguidance—are diverted from this truth. Allah does not force anyone into disbelief, but when a person persistently chooses falsehood over truth, Allah allows them to remain in their delusion. It is like someone who keeps their eyes closed and then complains they cannot see the sun. The Quran is clear guidance, but those who refuse to open their hearts will remain deluded. This is a warning: do not be among those who turn away from obvious truth due to arrogance or worldly attachment."
  },
  10: {
    "Condemned are the liars": "Allah pronounces a curse and destruction upon those who lie about the truth—those who fabricate falsehood about Allah, deny His messengers, and spread confusion among people. The word used implies they deserve to be destroyed or cursed for their persistent lying. These are people who speak without knowledge, making up claims about religion, the afterlife, and Allah without any authority. In the time of the Prophet (ﷺ), soothsayers and false claimants would guess and lie. Allah declares their condemnation because lies lead people away from salvation."
  },
  11: {
    "those who are ˹steeped˺ in ignorance, totally heedless": "These condemned liars are described as being drowned in ignorance, completely unaware of reality. They are like someone submerged in deep water, unable to see anything around them. Their heedlessness is so deep that they are oblivious to the clear signs of Allah all around them—in nature, in revelation, in their own selves. They are preoccupied with worldly pleasures and distractions, never pausing to think about their purpose, their Creator, or their destination after death. This total heedlessness makes them easy targets for destruction."
  },
  12: {
    "They ask ˹mockingly˺, \"When is this Day of Judgment?\"": "Out of their ignorance and arrogance, these deniers sarcastically ask about the timing of the Day of Judgment. They do not ask sincerely to prepare for it; rather, they mock and challenge, implying it will never come. This is similar to how the disbelievers of Mecca would taunt the Prophet (ﷺ), saying: 'Bring upon us what you threaten if you are truthful.' Their question was meant to ridicule, not to learn. But little did they know that this Day will come suddenly, and their mockery will turn into regret."
  },
  13: {
    "˹It is˺ the Day they will be tormented over the Fire": "Allah answers their mocking question by describing what that Day will bring them: they will be burned and tormented over the Fire. The word 'tormented' implies they will be tested by fire, just as gold is tested in flames. On that Day, their mockery will end, and reality will strike them. The Fire they denied will become their abode. This is the ultimate answer to those who arrogantly asked when Judgment would come—they will experience it firsthand, and it will be unlike anything they imagined."
  },
  14: {
    "˹They will be told,˺ \"Taste your torment!": "On that Day, the angels or Allah Himself will address these deniers with harsh words: 'Taste your punishment!' This is the consequence of their rejection and mockery. They wanted to taste doubt and denial in the world; now they will taste the Fire. The word 'taste' is used because it implies direct, personal experience—there will be no escape, no intermediary, just their own suffering.",
    "This is what you sought to hasten.\"": "They will be reminded that this is exactly what they impatiently asked for. They sarcastically demanded the punishment be brought quickly, and now it has arrived. The irony is devastating—they rushed toward their own destruction. In life, they thought the warning was empty threats; now they realize it was absolute truth. This serves as a warning to anyone who takes Allah's promises lightly."
  },
  15: {
    "Indeed, the righteous will be amid Gardens and springs": "In contrast to the fate of the deniers, Allah describes the beautiful destiny of the righteous—those who lived their lives with consciousness of Allah and fear of His punishment. They will reside in lush Gardens of Paradise with flowing springs. Imagine the most beautiful garden you have ever seen, then multiply that beauty infinitely—that is just a glimpse of what awaits the believers. The springs provide endless pure water, adding to the tranquility and perfection of Paradise. The Prophet (ﷺ) described Paradise saying: 'In it is what no eye has seen, no ear has heard, and no human heart has conceived.'"
  },
  16: {
    "˹joyfully˺ receiving what their Lord will grant them": "These righteous believers will happily accept whatever blessings their Lord gives them in Paradise. They will not complain or desire more than what they receive because everything Allah grants will be perfect and satisfying. Their hearts will be content, free from jealousy or dissatisfaction. This is the ultimate success—being pleased with Allah and Allah being pleased with them.",
    "Before this ˹reward˺ they were truly good-doers ˹in the world˺": "Allah explains why they deserve this reward: in their worldly life, before entering Paradise, they were people of excellence (muhsineen). They did not just fulfill minimum requirements; they strived to perfect their worship and character. They worshipped Allah as if they could see Him, and if they could not see Him, they knew He saw them. This is the level of faith that earns such magnificent reward."
  },
  17: {
    "they used to sleep only little in the night": "One of the characteristics of these excellent believers is that they spent much of their nights in worship rather than sleep. While others slept comfortably, they stood in prayer, recited Quran, and sought closeness to Allah in the quiet, blessed hours of the night. The Prophet (ﷺ) would pray at night until his feet would swell, and he said: 'The best prayer after the obligatory prayers is the night prayer.' These believers sacrificed their rest for their Lord, and Allah will reward them with eternal rest and comfort in Paradise."
  },
  18: {
    "and pray for forgiveness before dawn": "In the last portion of the night, just before dawn (the time of suhoor/sahr), these righteous believers would seek Allah's forgiveness. This is the most blessed time for supplication, when Allah descends to the lowest heaven and asks: 'Is there anyone seeking forgiveness that I may forgive them? Is there anyone asking that I may give them?' Instead of sleeping through this precious time, the believers were awake, crying to Allah, seeking His pardon. Despite their excellence in worship, they remained humble, knowing they needed Allah's forgiveness. This combination of worship and humility defines true righteousness."
  },
  19: {
    "And in their wealth there was a rightful share ˹fulfilled˺ for the beggar and the poor": "Another quality of these righteous believers is their generosity. They recognized that the poor and needy had a right in their wealth—not just charity out of kindness, but an obligation. They gave to those who asked (the beggars) and those who did not ask out of dignity (the deprived poor who suffer silently). The Prophet (ﷺ) said: 'The upper hand (the giving hand) is better than the lower hand (the receiving hand).' These believers did not hoard wealth or ignore the suffering around them. Their nights were for worship, and their days included caring for others."
  },
  20: {
    "There are ˹countless˺ signs on earth for those with sure faith": "Allah draws attention to the earth beneath our feet—it is filled with signs pointing to His existence, power, and wisdom. The mountains, valleys, rivers, plants, animals, diverse landscapes, minerals, and ecosystems all testify to a Creator. But these signs are only recognized by those who have certainty in faith (yaqeen). A person with a closed heart can walk through the most magnificent scenery and see nothing but coincidence, while a believer sees Allah's handiwork everywhere. The earth's ability to bring forth life after death (rain reviving dry land) is a direct sign of resurrection."
  },
  21: {
    "as there are within yourselves.": "Beyond the external world, signs of Allah exist within your own body and soul. Consider the complexity of the human body—the heart that beats without your command, the eyes that see, the brain that processes information, the immune system that fights disease. Your creation from a single cell, your development in the womb, your emotions and consciousness—all point to a wise Creator. The soul itself is a mystery that science cannot fully explain, yet it gives you life.",
    "Can you not see?": "Allah poses a rhetorical question: after all these signs within and around you, do you still not see the truth? This is a gentle rebuke to those who ignore obvious evidence. Seeing here means understanding and reflecting, not just physical sight. Many people look but do not truly see because they do not ponder. Allah invites humanity to reflect on themselves—surely the One who created you so perfectly can recreate you after death."
  },
  22: {
    "In heaven is your sustenance and whatever you are promised": "Allah reminds humanity that their provision (rizq) comes from the sky—rain that produces crops, sunlight that enables growth, and the divine decree of sustenance that is written in the heavens. Everything you need for survival is controlled from above by Allah's command. Additionally, everything you are promised—Paradise, Hellfire, Judgment—is also decreed in the heavens. This verse teaches complete trust in Allah (tawakkul). Your sustenance is guaranteed by the Lord of the heavens; worrying excessively about provision shows weak faith. The Prophet (ﷺ) said: 'If you relied upon Allah with true reliance, He would provide for you as He provides for the birds.'"
  },
  23: {
    "Then by the Lord of heaven and earth!": "Allah takes a profound oath by Himself—the Lord and Master of the heavens and earth. This is the most powerful oath possible, emphasizing absolute truth. When the Creator of everything swears by Himself, there can be no doubt in what follows.",
    "˹All˺ this is certainly as true as ˹the fact that˺ you can speak!": "Everything mentioned—the resurrection, judgment, paradise, hell, and all promises—is as true and certain as the fact that you speak. You do not doubt that you can speak; it is obvious and undeniable. Similarly, Allah's promises are just as certain. This is a powerful comparison that brings abstract concepts down to everyday reality. Just as you are sure of your own voice, be sure of meeting your Lord."
  },
  24: {
    "Has the story of Abraham's honoured guests reached you ˹O Prophet˺?": "Allah asks Prophet Muhammad (ﷺ) if he has heard the story of the noble guests who visited Prophet Ibrahim (Abraham). This narrative style creates engagement and emphasizes the importance of the story. These guests were angels sent by Allah, and they are called 'honoured' because of their noble status and because Ibrahim treated them with great hospitality. The story illustrates several lessons: Ibrahim's generosity, the angels' mission, and Allah's power to grant miracles."
  },
  25: {
    "˹Remember˺ when they entered his presence and greeted ˹him with˺, \"Peace!\" He replied, \"Peace ˹be upon you˺!\"": "The angels entered upon Ibrahim and greeted him with 'Salam' (peace)—the greeting of the believers. Ibrahim immediately returned their greeting with an even better response, as is the Islamic etiquette. Allah says in the Quran: 'When you are greeted with a greeting, greet with one better than it or return it.' Ibrahim demonstrated perfect manners even with strangers.",
    "˹Then he said to himself,˺ \"˹These are˺ an unfamiliar people.\"": "Although he greeted them warmly, Ibrahim noticed something unusual about these visitors. He did not recognize them from his community or any traveling merchants. Something about their appearance or manner seemed unfamiliar. This subtle observation shows Ibrahim's alertness while maintaining hospitality. He did not let his uncertainty prevent him from welcoming them properly."
  },
  26: {
    "Then he slipped off to his family and brought a fat ˹roasted˺ calf": "Without making his guests wait or asking what they wanted, Ibrahim quietly went to his family and prepared the best meal he could offer—a fat, roasted calf. This was the finest hospitality of that time. Notice the generosity: he did not bring leftovers or simple food, but the best meat prepared excellently. He 'slipped off,' meaning he did it quietly without making a show or embarrassing his guests by asking if they were hungry. This is the model of Islamic hospitality—anticipating needs and serving generously without fanfare."
  },
  27: {
    "and placed it before them, asking, \"Will you not eat?\"": "Ibrahim personally brought the food and placed it near his guests, not leaving servants to do it. He then gently invited them to eat with a polite question: 'Will you not eat?' This gentle encouragement shows his concern for his guests' comfort. He did not command or pressure them but offered graciously. The Prophet (ﷺ) said: 'Whoever believes in Allah and the Last Day should honor his guest.' Ibrahim is the ultimate example of this teaching."
  },
  28: {
    "˹They did not eat,˺ so he grew fearful of them.": "When the guests did not touch the food, Ibrahim became worried. In that culture (and in Islamic teaching), refusing food from a host could indicate hostile intentions. Angels do not eat human food, but Ibrahim did not know they were angels yet. His fear was natural—these strangers refusing his hospitality was unusual and potentially threatening.",
    "They reassured ˹him˺, \"Do not be afraid,\"": "Sensing his fear, the angels immediately calmed him, revealing that they meant no harm. They said, 'Do not be afraid'—words of comfort that would soon be followed by amazing news. This shows the mercy in their mission; they did not leave Ibrahim in anxiety.",
    "and gave him good news of a knowledgeable son.": "The angels then delivered the wonderful news: Ibrahim would be blessed with a son who would be knowledgeable and wise. This was Prophet Ishaq (Isaac), who would continue the legacy of prophethood. For Ibrahim, who was very old and whose wife Sarah was elderly and barren, this was a miraculous promise. The son is described as 'knowledgeable,' indicating he would be a prophet with divine wisdom."
  },
  29: {
    "Then his wife came forward with a cry, clasping her forehead ˹in astonishment˺, exclaiming,": "When Sarah heard this news, she came forward crying out in shock. She struck her forehead with her hand—a natural human gesture of utter disbelief and amazement. This was not a cry of sadness but of astonishment. After decades of being unable to have children, hearing such news seemed impossible.",
    "\"˹A baby from˺ a barren, old woman!\"": "Sarah expressed her disbelief by pointing out the obvious: she was old and had been barren her entire life. How could she possibly have a child now? Her words reflect honest human reaction to miraculous news. She was not doubting Allah's power but expressing her amazement at being chosen for such a miracle at her age."
  },
  30: {
    "They replied, \"Such has your Lord decreed.": "The angels confirmed that this was not a mistake or exaggeration—it was exactly as Allah had decreed. Allah's decision overrides all natural limitations. Age, barrenness, human impossibility—none of these matter when Allah wills something. The angels spoke with certainty because they were delivering Allah's own command.",
    "He is truly the All-Wise, All-Knowing.\"": "The angels concluded by reminding Sarah of Allah's attributes: He is Al-Hakeem (the All-Wise) and Al-Aleem (the All-Knowing). Allah's wisdom means He does everything for perfect reasons, even if humans cannot understand them immediately. His knowledge means He knows exactly what He is doing and when. If Allah decrees a child for an elderly barren woman, there is profound wisdom behind it—and indeed, through Ishaq came a line of prophets. This ending reminds us that nothing is impossible for Allah, and we should never doubt His promises."
  },
  31: {
    "˹Later,˺ Abraham asked, \"What is your mission, O messengers?\"": "After receiving the good news about a son, Prophet Ibrahim (Abraham) realized these were no ordinary guests—they were angels sent on a mission. His curiosity and wisdom led him to ask about their purpose. He addressed them as 'messengers,' acknowledging their angelic status. This question shows Ibrahim's concern for the affairs of his community and his understanding that angels do not descend without important purposes. The Prophet (ﷺ) taught us that angels are sent for various missions—some bring revelation, some bring mercy, and some bring punishment."
  },
  32: {
    "They replied, \"We have actually been sent to a wicked people,": "The angels revealed their true mission: they were sent to destroy a criminal, sinful people. This refers to the people of Prophet Lut (Lot), who lived in the cities of Sodom and Gomorrah. These people had committed unprecedented sins—they practiced homosexuality openly, rejected their prophet, and committed highway robbery. The word 'mujrimeen' (wicked/criminal) indicates they were habitual sinners who had crossed all boundaries. Their crime was so severe that Allah sent angels specifically to annihilate them, demonstrating that persistent, unrepentant sin eventually brings divine punishment."
  },
  33: {
    "to send upon them stones of ˹baked˺ clay,": "The method of punishment is specified: stones made of baked clay would rain down upon them. These were not ordinary stones but specially prepared projectiles of divine punishment. Some scholars explain these were stones of heated, hardite clay that would strike with devastating force. This punishment suited their crime—they had turned natural order upside down with their sins, so Allah turned their world upside down with a rain of destruction from above. The ruins of these cities near the Dead Sea serve as a lasting reminder of this event."
  },
  34: {
    "marked by your Lord for the transgressors.\"": "Each stone was marked or designated by Allah for specific transgressors. This shows the precision of divine punishment—it was not random destruction but targeted justice. Every stone had a name, a destination. The word 'musrifeen' (transgressors/those who exceed limits) describes people who went beyond all bounds in their sins. They did not just sin privately; they celebrated their sins publicly and rejected all calls to repentance. When people become so brazen in transgression, they invite their own destruction. The marking of stones shows Allah's complete knowledge and control over every detail."
  },
  35: {
    "Then ˹before the torment˺ We evacuated the believers from the city.": "Before the punishment descended, Allah ensured that the believers were safely removed from the area. This demonstrates Allah's mercy and justice—He does not destroy the innocent along with the guilty. Prophet Lut and his believing family members were commanded to leave during the night before the punishment came at dawn. This principle appears throughout Islamic history: when divine punishment comes upon a community, the believers are either removed or protected. It also shows that living among sinful people does not doom the righteous, as long as they reject the sin and maintain their faith."
  },
  36: {
    "But We only found one family that had submitted ˹to Allah˺.": "A sobering reality is revealed: in that entire wicked city, only one household of true believers was found—the family of Prophet Lut. Despite Lut's years of preaching and warning, only his immediate family (excluding his wife, who sided with the disbelievers) accepted the truth. This shows how a society can become so corrupt that faith becomes extremely rare. The word 'Muslimeen' (those who submitted) is used, showing that true submission to Allah has always been the essence of religion from the beginning. This also warns communities: when believers become such a tiny minority, destruction may be near."
  },
  37: {
    "And We have left a sign there ˹as a lesson˺ for those who fear the painful punishment.": "Allah left the ruins of these destroyed cities as a permanent sign and lesson for future generations. The area around the Dead Sea, with its unusual geological features and the lowest elevation on earth, stands as testimony to this divine punishment. But this sign only benefits those who fear Allah's painful punishment—those whose hearts are receptive to warnings. For the heedless, even walking through the ruins means nothing. The Prophet (ﷺ) passed by the ruins of Thamud during the expedition to Tabuk and warned his companions not to enter such places except in a state of weeping and reflection, lest the same punishment befall them."
  },
  38: {
    "And in ˹the story of˺ Moses ˹was another lesson,˺ when We sent him to Pharaoh with compelling proof": "Allah presents another historical example of destroyed deniers: the story of Prophet Musa (Moses) and Pharaoh. Musa was not sent empty-handed; he carried 'sultan mubeen'—clear authority, compelling proof, and undeniable miracles. His staff turning into a serpent, his hand glowing white, and the nine plagues sent upon Egypt were all clear proofs of his prophethood. Despite this overwhelming evidence, Pharaoh rejected the truth. This teaches that rejection of faith is often not due to lack of evidence but due to arrogance and unwillingness to submit. Pharaoh had every reason to believe, but his pride prevented him."
  },
  39: {
    "but Pharaoh was carried away by his power,": "Pharaoh turned away arrogantly, relying on his power, his army, and his kingdom. The phrase 'bi ruknihi' (with his support/power) indicates he felt secure in his military might and political authority. He thought his worldly power could protect him from the Lord of the worlds. This is the delusion of tyrants throughout history—they believe their temporary authority makes them invincible. But no human power can stand against Allah's decree.",
    "saying ˹of Moses˺, \"A magician or a madman!\"": "Instead of addressing Musa's message, Pharaoh attacked his character with contradictory accusations. He called Musa either a magician (implying he was clever and deceptive) or a madman (implying he was insane and irrational). These accusations contradict each other—one cannot be both a skilled magician and a madman simultaneously. This shows that Pharaoh had no logical argument; he simply threw whatever insult came to mind. This pattern of attacking messengers with baseless accusations repeats throughout history."
  },
  40: {
    "So We seized him and his soldiers, casting them into the sea": "Allah's response to Pharaoh's arrogance was swift and complete. Allah seized Pharaoh and his entire army—the very power he relied upon—and threw them into the sea. The Red Sea, which had miraculously parted for Musa and the Israelites, crashed down upon Pharaoh's pursuing army. His chariots, horses, and soldiers were all drowned in moments. The one who claimed to be a god could not even save himself from water. This demonstrates that no matter how powerful a tyrant appears, Allah's power is infinitely greater.",
    "while he was blameworthy.": "Pharaoh drowned while being 'muleem'—blameworthy, deserving of blame, and guilty. He had no excuse for his disbelief. He had seen the miracles, heard the message, and witnessed Allah's signs, yet he persisted in arrogance and oppression. At the moment of drowning, he tried to declare faith, but it was too late—faith at the moment of certain death, when one has no choice, is not accepted. His preserved body, discovered in modern times, stands as a sign for those who reflect."
  },
  41: {
    "And in ˹the story of˺ 'Âd ˹was another lesson,˺ when We sent against them the devastating wind.": "Allah continues with another example: the people of 'Âd, to whom Prophet Hud was sent. They were a powerful civilization, known for their strength, tall stature, and impressive buildings. Despite Prophet Hud's warnings, they rejected him, saying: 'Who is mightier than us in strength?' So Allah sent against them a wind described as 'aqeem'—barren, devastating, and merciless. Unlike normal winds that bring rain and benefit, this wind brought only destruction. It blew for seven nights and eight days continuously, as mentioned in other verses. Their physical strength meant nothing against Allah's wind."
  },
  42: {
    "There was nothing it came upon that it did not reduce to ashes.": "This wind was so powerful and destructive that everything it touched was reduced to 'rameem'—ashes, dust, decayed remains. Their strong bodies, their magnificent buildings, their crops, their livestock—all became like dust and debris. The people who boasted of their power were left like hollow, uprooted palm trunks, as described elsewhere in the Quran. This complete annihilation shows that no human achievement can withstand Allah's punishment. The 'Âd thought their civilization was permanent; within days, it was as if they never existed. Their story remains as a warning carved in Arabian history."
  },
  43: {
    "And in ˹the story of˺ Thamûd ˹was another lesson,˺ when they were told, \"Enjoy yourselves ˹only˺ for a ˹short˺ while.\"": "The people of Thamûd, to whom Prophet Salih was sent, provide another lesson. They demanded a miracle, so Allah brought forth a she-camel from a rock. But instead of believing, they killed the camel in defiance. After this crime, Prophet Salih warned them: 'Enjoy yourselves in your homes for three days—that is a promise not to be denied.' This was their final deadline. The phrase 'enjoy yourselves for a while' is chilling—it means their time was up, and they were simply being given a few final days before inevitable destruction. How terrifying to know your exact deadline!"
  },
  44: {
    "Still they persisted in defying the commands of their Lord,": "Even after this clear warning with a specific deadline, the people of Thamûd did not repent. Instead, they 'ataw'—they arrogantly rebelled and persisted in defying Allah's commands. They challenged the punishment to come, perhaps thinking Salih was bluffing. This shows the depth of human arrogance—even facing certain destruction, some people refuse to humble themselves before Allah. Their stubbornness sealed their fate.",
    "so they were overtaken by a ˹mighty˺ blast while they were looking on.": "On the promised day, a devastating blast (sa'iqah—a thunderbolt or earthquake accompanied by a terrible sound) struck them while they were watching and waiting. They could see their doom approaching but could do nothing to escape it. The phrase 'while they were looking on' emphasizes their helplessness—they witnessed their own destruction in real-time. No running, no hiding, no defense was possible. This is the fate of those who mock divine warnings."
  },
  45: {
    "Then they were not able to rise up,": "After the blast struck, the Thamûd were left completely incapacitated. They could not even stand up—their bodies were frozen in death, found fallen in their homes. The people who carved magnificent homes in mountains, who thought they were safe and powerful, could not even rise to their feet when Allah's punishment came.",
    "nor were they helped.": "No one could help them—not their allies, not their gods, not their wealth, not their carved-mountain homes. All the support systems they relied upon were useless. This is a powerful reminder that on the day when Allah decides to punish, no worldly helper can intervene. The Prophet (ﷺ) passed by the ruins of Thamûd at Madain Salih and told his companions to learn from their fate."
  },
  46: {
    "And the people of Noah ˹had also been destroyed˺ earlier.": "Going further back in history, Allah mentions the people of Prophet Nuh (Noah), who were destroyed before all the previous nations mentioned. They were the first nation to receive a prophet after Adam, and their destruction by the great flood is one of the most famous events in human history. Nuh preached to them for 950 years, yet only a small number believed.",
    "They were truly a rebellious people.": "Allah describes them as 'fasiqeen'—rebellious, sinful people who departed from obedience to Allah. Despite having the longest-preaching prophet in history, they mocked him, rejected his message, and continued their idol worship and corruption. Their rebellion was persistent and defiant, so Allah drowned them all in the flood, saving only Nuh and the believers on the ark. This first great punishment in human history set a precedent: nations that reject their prophets face destruction."
  },
  47: {
    "We built the universe with ˹great˺ might,": "After recounting stories of destroyed nations, Allah draws attention to His creative power. He built the heavens with 'ayd'—great power, might, and strength. The construction of the universe—with its billions of galaxies, stars, and planets—demonstrates power beyond human comprehension. Scientists estimate the observable universe contains over 200 billion galaxies, each containing billions of stars. All of this was created by Allah with His infinite might, without fatigue or difficulty.",
    "and We are certainly expanding ˹it˺.": "This phrase is remarkable: 'We are certainly expanding it.' Modern science only discovered in the 20th century that the universe is continuously expanding—galaxies are moving away from each other. This scientific fact, discovered through advanced technology, was stated in the Quran over 1400 years ago. This is one of the scientific miracles of the Quran, confirming its divine origin. If Allah can create and expand the entire universe, resurrecting humans is certainly easy for Him."
  },
  48: {
    "As for the earth, We spread it out.": "Allah then describes how He spread out the earth, making it suitable for habitation. The earth's surface was prepared with flat plains, valleys, and gentle slopes that allow humans and animals to live, walk, build, and cultivate. Despite the earth being spherical, from any point on its surface, it appears spread out and accessible—a perfect design for inhabitants.",
    "How superbly did We smooth it out!": "Allah praises His own work: 'What an excellent spreader/preparer We are!' The earth is perfectly designed for life—not too hard, not too soft, with varied terrain for different purposes. Mountains provide stability, plains allow agriculture, and valleys channel water. This self-praise from Allah invites humans to recognize and appreciate His perfect design. The One who prepared such a perfect home for humanity certainly deserves worship and gratitude."
  },
  49: {
    "And We created pairs of all things": "Allah reveals a fundamental principle of creation: everything is created in pairs. Male and female among humans and animals, positive and negative charges in atoms, matter and antimatter, day and night, land and sea, sweet and bitter, hot and cold—the entire creation is based on pairs and complementary opposites. Modern science confirms this pairing extends to the subatomic level. This perfect balance in creation points to one Creator who designed everything with purpose.",
    "so perhaps you would be mindful.": "The purpose of this pairing is to make humans reflect and remember Allah. When you see the complementary nature of creation—how everything has an opposite that completes it—you should recognize the wisdom of the Creator. The existence of pairs also points to the uniqueness of Allah: He alone has no pair, no partner, no opposite. Everything else is created in pairs, but the Creator is One and unique. This reflection should lead to mindfulness (tathakkur) and ultimately to worship."
  },
  50: {
    "So ˹proclaim, O Prophet˺: \"Flee to Allah!": "After all the warnings and signs, Allah instructs the Prophet (ﷺ) to deliver this powerful message: 'Flee to Allah!' This is one of the most beautiful and urgent commands in the Quran. Flee from His punishment to His mercy, from His anger to His forgiveness, from ignorance to knowledge, from disbelief to faith. Unlike fleeing from a danger, fleeing to Allah means running toward the only source of true safety. There is no refuge from Allah except with Allah. This call remains relevant to every person in every era—flee to Allah through repentance, worship, and obedience.",
    "I am truly sent by Him with a clear warning to you.": "The Prophet (ﷺ) declares his role: he is a clear warner sent by Allah. His message is not ambiguous or complicated—it is a straightforward warning of consequences for disbelief and sin. A warner does not benefit from the warning; rather, he delivers it out of concern for others. The Prophet (ﷺ) warned his nation out of love and concern, hoping they would save themselves from destruction."
  },
  51: {
    "And do not set up another god with Allah.": "The core message is repeated: do not commit shirk (associating partners with Allah). This is the greatest sin and the one unforgivable crime if one dies upon it. Do not worship idols, do not give ultimate devotion to wealth, power, or desires, do not place anything alongside Allah in your heart. Tawheed (monotheism) is the foundation of Islam and the key to salvation. Every prophet came with this same message: worship Allah alone.",
    "I am truly sent by Him with a clear warning to you.": "The Prophet (ﷺ) repeats his credentials: he is a clear warner from Allah. This repetition emphasizes the urgency and importance of the message. The warning is clear, the evidence is clear, and the choice is clear. Whoever heeds the warning saves themselves; whoever ignores it faces the consequences documented in the stories of previous nations."
  },
  52: {
    "Similarly, no messenger came to those before them without being told: \"A magician or a madman!\"": "Allah consoles the Prophet (ﷺ) by revealing a historical pattern: every messenger before him faced the same accusations. Musa was called a magician, Nuh was called mad, and every prophet heard similar insults. The disbelievers throughout history have shown a remarkable lack of creativity—they always resort to the same baseless accusations: either the messenger is using magic to deceive, or he is insane. This repetition across centuries and civilizations shows that the problem is not with the messengers but with the arrogant hearts of disbelievers who refuse to accept truth."
  },
  53: {
    "Have they passed this ˹cliché˺ down to one another?": "Allah asks rhetorically: did these disbelievers across different times and places secretly communicate and agree to use the same insults? Did previous nations leave instructions for future disbelievers on how to reject prophets? The question highlights the absurd consistency of their accusations.",
    "In fact, they have ˹all˺ been a transgressing people.": "The answer is no—they did not coordinate. Rather, they all share the same disease: transgression (tughyan). Arrogance, rebellion against truth, and refusal to submit produce the same symptoms in every era. When the heart is diseased with pride, it naturally rejects prophets and makes the same excuses. This is why disbelievers throughout history sound the same—their spiritual illness is identical."
  },
  54: {
    "So ˹now˺ turn away from them ˹O Prophet˺, for you will not be blamed.": "Allah comforts the Prophet (ﷺ): if these people continue rejecting despite all your efforts, turn away from them. You have done your job; you have conveyed the message. You will not be blamed for their disbelief because guidance is from Allah, and you cannot force anyone to believe. The Prophet (ﷺ) would grieve over the disbelief of his people, and Allah reassures him that he is not responsible for their choices. This is an important lesson for all who call to Islam: our job is to convey, not to convert hearts—that is Allah's domain."
  },
  55: {
    "But ˹continue to˺ remind. For certainly reminders benefit the believers.": "Although turning away from stubborn disbelievers, the Prophet (ﷺ) is told to continue reminding. The reminder may not benefit the arrogant, but it certainly benefits the believers. Every reminder strengthens faith, increases knowledge, and renews commitment. The believing heart is soft and receptive—it benefits from reminders even if it already knows the truth. This is why Muslims continuously recite Quran, attend lectures, and remind each other—because reminders nourish the soul. The Quran itself is called 'The Reminder' (Al-Dhikr)."
  },
  56: {
    "I did not create jinn and humans except to worship Me.": "This is one of the most important verses in the Quran, answering humanity's fundamental question: Why do we exist? Allah declares that He created both jinn (unseen beings) and humans for one purpose: to worship Him. This worship ('ibadah) is comprehensive—it includes prayer, fasting, charity, and all rituals, but also extends to every action done with the intention to please Allah. Working honestly, treating family well, being kind to neighbors—all become worship when done for Allah. Life has meaning because it has purpose, and that purpose is to know, worship, and submit to the Creator."
  },
  57: {
    "I seek no provision from them, nor do I need them to feed Me.": "Allah clarifies that He needs nothing from His creation. He does not create humans to provide for Him or to feed Him—Allah is free from all needs. Some pagan traditions had rituals of 'feeding' their gods with sacrifices and offerings as though the gods needed sustenance. Allah corrects this misconception: He is the Provider, not the provided-for. Our worship does not benefit Allah; it benefits us. He is complete and self-sufficient whether we worship Him or not. This removes any notion that Allah created us out of His own need."
  },
  58: {
    "Indeed, Allah ˹alone˺ is the Supreme Provider—": "The roles are reversed: Allah is Al-Razzaq—the Supreme Provider who sustains all creation. Every morsel of food, every drop of water, every breath of air comes from Him. He provides for believers and disbelievers, for humans and animals, for seen and unseen creatures. His provision is constant and encompasses all needs—physical, emotional, and spiritual.",
    "Lord of all Power, Ever Mighty.": "Allah is 'Dhul-Quwwah'—possessor of all power, and 'Al-Mateen'—the Ever Mighty, Firm, and Strong. His power never diminishes, never tires, never needs replenishment. Unlike human strength that weakens with age or exertion, Allah's power is absolute and eternal. This combination of being the Provider and being All-Powerful means nothing can stop His provision and nothing can challenge His might. The One with such attributes deserves worship, not His weak, dependent creatures."
  },
  59: {
    "The wrongdoers will certainly have a share ˹of the torment˺ like that of their predecessors.": "Allah warns the disbelievers of Mecca (and all wrongdoers throughout time) that they will receive the same punishment their predecessors received. Just as the people of Nuh were drowned, 'Âd were destroyed by wind, Thamûd by the blast, and Pharaoh by the sea—the current wrongdoers have their share of punishment waiting. 'Dhanub' here means a portion or share of punishment, like a bucket's share of water from a well. Their punishment is already allocated; it is simply a matter of timing.",
    "So do not let them ask Me to hasten ˹it˺.": "Allah warns these mockers who sarcastically demand the punishment to come quickly: do not rush your own destruction. Their mockery—'Bring the punishment if you are truthful!'—is foolish. The punishment will come at its appointed time, and when it does, they will wish it had never come. This is a subtle threat: you want it hastened? Be careful what you wish for. The delay is mercy, giving them time to repent."
  },
  60: {
    "Woe then to the disbelievers when they face their Day which they are warned of!": "The surah concludes with a powerful declaration of doom: 'Wail' (woe, destruction, severe punishment) awaits the disbelievers on the Day they have been warned about—the Day of Judgment. This Day they mock, this Day they deny, this Day they ask to be hastened—when it actually arrives, they will face unimaginable terror and regret. The word 'wail' in Arabic (wayl) can also refer to a valley in Hell reserved for the worst sinners. This closing verse serves as a final, emphatic warning: the Day is coming, and woe to those who face it as disbelievers."
  }
};