var tafsirData_99 = {
  1: {
    "When the earth is shaken": "This refers to a time when the entire earth will be violently shaken. Unlike earthquakes we experience today which are localized and temporary, this shaking will encompass the whole planet simultaneously. It marks the beginning of the end of this world as we know it. The Prophet Muhammad (peace be upon him) said that the Hour will not come until earthquakes increase in frequency, which serves as a sign leading up to this final, all-encompassing quake.",
    "˹in˺ its ultimate quaking": "This is the final and most severe shaking the earth will ever experience. The word 'ultimate' indicates that this is not just any earthquake—it is THE earthquake that signals the Day of Judgment. Every previous earthquake in history was minor compared to this one. This quaking will be so intense that it will fundamentally transform the earth and everything on it."
  },
  2: {
    "and when the earth throws out": "The earth will expel and bring forth everything that has been buried within it. Just as a person might turn a bag inside out to empty its contents, the earth will release everything it has held inside for thousands of years. This is an act commanded by Allah, and the earth will obey completely.",
    "˹all˺ its contents": "This includes the bodies of the dead who will be resurrected, as well as hidden treasures, minerals, and everything that was ever buried or concealed within the earth. Some scholars mention this also includes the records of deeds that the earth has witnessed. The earth has been a silent witness and container of all that has happened upon it, and on this Day, it will give up everything. The Prophet (peace be upon him) mentioned that the earth will throw out its treasures like pillars of gold and silver, and a murderer will say 'For this I killed,' and a person who cut family ties will say 'For this I severed relations.'"
  },
  3: {
    "and humanity cries,": "At this moment, people will be overwhelmed with confusion and terror. They will cry out in shock, unable to comprehend what is happening around them. This cry represents the universal human reaction to witnessing something beyond all previous experience—an event so catastrophic that it defies understanding.",
    "\"What is wrong with it?\"": "People will ask this question about the earth, bewildered by its violent behavior. Throughout their lives, they had taken the stability of the earth for granted. They walked on it, built homes on it, and it remained firm beneath their feet. But now, the earth they knew is acting in a completely unfamiliar way. This question reflects human helplessness and the realization that something unprecedented and final is occurring. No scientist, no technology, no human power can explain or stop what is happening."
  },
  4: {
    "on that Day the earth will recount everything,": "On the Day of Judgment, the earth will speak and testify. It will narrate every single event that ever took place on its surface—every act of worship, every sin, every word spoken, every step taken. The earth has been recording everything like a witness. The Prophet Muhammad (peace be upon him) said: 'Do you know what its news is?' The companions said: 'Allah and His Messenger know best.' He said: 'Its news is that it will testify against every male and female servant about what they did on its surface. It will say: He did such and such on such and such day.' This is a profound reminder that we are never truly alone or unobserved. Even when no human sees us, the very ground beneath our feet is aware of our actions."
  },
  5: {
    "having been inspired by your Lord ˹to do so˺.": "The earth does not speak or testify of its own accord—it does so because Allah commands it. Allah will inspire the earth, giving it permission and the ability to speak. This shows that everything in creation obeys Allah completely. The earth, which we consider lifeless, is actually responsive to its Creator. Just as Allah commanded the fire to be cool and safe for Prophet Ibrahim (Abraham), and just as He commanded the sea to part for Prophet Musa (Moses), He will command the earth to speak, and it will obey instantly. This verse reminds us that Allah has complete control over all of creation, and nothing happens without His permission and command."
  },
  6: {
    "On that Day people will proceed in separate groups": "After resurrection, humanity will emerge from their graves and move forward in various groups. People will be divided and categorized based on their faith and deeds. The believers will be in one group, the disbelievers in another. Even among these, there will be further distinctions. Unlike this world where the righteous and the wicked live together, on that Day, everyone will be sorted and separated. Friends will be parted, families will be divided based on their beliefs and actions. Each person will be concerned only with themselves, as Allah says elsewhere in the Quran: 'On the Day a man will flee from his brother, and his mother and his father, and his wife and his children' (80:34-36).",
    "to be shown ˹the consequences of˺ their deeds.": "Every person will be shown the complete record of their actions and the results of what they did in their worldly life. Nothing will be hidden or forgotten. Good deeds will be displayed with their rewards, and bad deeds will be shown with their consequences. This is the ultimate moment of truth—no excuses, no denials, no hiding. The purpose of this display is justice. Allah will show everyone exactly what they earned so that no one can claim they were treated unfairly. This is why the Prophet (peace be upon him) advised us to take account of ourselves before we are taken to account."
  },
  7: {
    "So whoever does an atom's weight of good": "Even the tiniest good deed, as small as an atom or a speck of dust, will not be overlooked. This includes a kind word, a smile, removing something harmful from the road, or even a good intention in the heart. Allah's accounting is precise and generous—He does not miss or ignore any good, no matter how insignificant it might seem to us. The Prophet (peace be upon him) said: 'Do not belittle any good deed, even meeting your brother with a cheerful face.' This gives immense hope to believers: every small act of kindness, every moment of patience, every quiet prayer is recorded and will be rewarded.",
    "will see it.": "The person will see the reward of that good deed on the Day of Judgment. They will witness the fruit of their good actions, whether it is entry into Paradise, elevation in ranks, or other blessings from Allah. Some scholars say 'seeing it' means seeing the deed itself in their record, while others say it means seeing its reward. Both meanings are true. Nothing good is ever lost with Allah. This should motivate us to do good constantly, even in small ways, because everything counts."
  },
  8: {
    "And whoever does an atom's weight of evil": "Just as no good deed is lost, no evil deed is overlooked either. Even the smallest sin, the slightest wrongdoing, will be recorded and presented. A hurtful word, a moment of arrogance, a small lie, looking at something forbidden, backbiting—everything is noted. This is a serious warning against taking sins lightly. Many people dismiss 'small' sins, thinking they don't matter. But this verse makes clear that everything matters. The Prophet (peace be upon him) warned against belittling sins, saying: 'Beware of the sins that are belittled, for they accumulate upon a person until they destroy him'—like small sticks that come together to make a fire.",
    "will see it.": "The person will see the consequence of that evil deed. They will face it and be accountable for it. For the believer who repented, Allah may forgive and cover those sins. But for those who did not repent or who died upon disbelief, they will see the full consequence of their wrongdoing. This should fill us with a healthy sense of caution and encourage us to repent sincerely for our mistakes. The door of repentance is open, and Allah loves those who turn back to Him. But on the Day of Judgment, the time for repentance will have passed, and everyone will face what they earned."
  }
};