var tafsirData_34 = {
  1: {
    "All praise is for Allah": "This opening statement establishes that every form of gratitude, appreciation, and glorification belongs exclusively to Allah. He alone deserves praise because He is the source of all blessings. Just as employees thank their employer for their salary, all creation should thank Allah for every provision they receive—from the air they breathe to the food they eat.",
    "to Whom belongs whatever is in the heavens and whatever is on the earth": "Allah owns everything in existence—every star, planet, mountain, ocean, tree, animal, and human being. Nothing exists outside His dominion. This means that everything you see around you, including yourself, belongs to Him. A person may claim to own a house or car, but in reality, they are temporary custodians. Allah is the true Owner of all things.",
    "And praise be to Him in the Hereafter": "Just as Allah is praised in this world, He will be praised in the afterlife as well. When the believers enter Paradise, they will praise Allah for His mercy and guidance. The Quran mentions in Surah Yunus (10:10) that the people of Paradise will say, 'Our final call will be: Praise be to Allah, Lord of all worlds.' This shows that praising Allah is eternal and never ends.",
    "He is the All-Wise": "Allah possesses perfect wisdom in everything He does, creates, and decrees. Nothing happens randomly or without purpose. When something difficult happens in your life, remember that Allah's wisdom is behind it, even if you cannot understand it at the moment. A child may not understand why medicine tastes bitter, but the parent knows it brings healing.",
    "All-Aware": "Allah knows every detail of everything—past, present, and future. He is aware of the secrets in your heart, your intentions, and even thoughts you have not yet formed. Nothing is hidden from Him. This should bring comfort to the believer because Allah knows their struggles, and it should bring caution because He also knows their sins."
  },
  2: {
    "He knows whatever goes into the earth": "Allah knows every seed planted in the soil, every drop of rain that seeps into the ground, every root that grows, and every creature that burrows underground. He knows the ants in their tunnels, the dead bodies buried in graves, and the minerals deep within the earth. Nothing that enters the earth escapes His knowledge.",
    "and whatever comes out of it": "Allah knows every plant that sprouts, every spring of water that emerges, every mineral extracted, and every creature that comes out from the earth. He even knows when a tiny seedling pushes through the soil. The Prophet Muhammad (peace be upon him) said that Allah divided mercy into one hundred parts, and He sent down one part to earth—this is the mercy through which creatures show compassion to one another, including the plants that grow for their sustenance.",
    "and whatever descends from the sky": "Allah knows every drop of rain, every ray of sunlight, every decree that comes down from Him, and every angel that descends with His commands. He knows the exact destination of each raindrop and which piece of land it will nourish. Nothing falls from the sky without His knowledge and permission.",
    "and whatever ascends into it": "Allah knows every prayer that rises to Him, every deed that ascends to be recorded, every soul that is taken up at death, and every angel that returns to the heavens. Your supplications, your good deeds, and even your sincere intentions—all of these ascend to Allah, and He is fully aware of them.",
    "And He is the Most Merciful, All-Forgiving": "Despite knowing everything—including all our sins and shortcomings—Allah is still the Most Merciful and the One who constantly forgives. This is deeply comforting. Allah's knowledge of our sins does not lead to immediate punishment; rather, His mercy gives us time to repent. The Prophet (peace be upon him) said that Allah is more pleased with the repentance of His servant than a man who loses his camel in the desert and then finds it again."
  },
  3: {
    "The disbelievers say, \"The Hour will never come to us.\"": "The disbelievers mockingly denied the Day of Resurrection. They could not imagine that after death and complete decomposition, they would be brought back to life. This denial was convenient for them because it meant they could live however they wanted without accountability. Many people today also live as if there is no afterlife, focusing only on worldly pleasures without considering the consequences of their actions.",
    "Say, ˹O Prophet,˺ \"Yes—by my Lord, the Knower of the unseen—it will certainly come to you!\"": "Allah commands the Prophet Muhammad (peace be upon him) to respond to their denial with an emphatic oath. The Prophet swears by Allah Himself that the Hour will definitely come. This is not a matter of opinion or speculation—it is a certainty. Allah uses the description 'Knower of the unseen' because the timing of the Hour is among the unseen knowledge that only He possesses.",
    "Not ˹even˺ an atom's weight is hidden from Him in the heavens or the earth": "Allah's knowledge is so precise that even the smallest particle—smaller than what the human eye can see—is known to Him. Whether it is in the vastness of space or deep within the earth, nothing escapes His awareness. This emphasizes that on the Day of Judgment, every tiny deed will be accounted for.",
    "nor anything smaller or larger than that, but is ˹written˺ in a perfect Record": "Everything, regardless of its size, is recorded in a clear book—the Preserved Tablet (Al-Lawh Al-Mahfuz). This record contains all that has happened and all that will happen. It is perfect, with no errors or omissions. The Quran states in another verse (Surah Al-Kahf 18:49) that this record 'leaves nothing small or large except that it has enumerated it.' This should make us mindful of even our smallest actions."
  },
  4: {
    "So He may reward those who believe and do good": "This verse explains the purpose of the detailed record-keeping and the coming of the Hour: so that those who combined faith with righteous actions can be rewarded. Notice that both belief and good deeds are mentioned together—faith alone without action, or actions without sincere faith, are incomplete. True believers demonstrate their faith through their actions.",
    "It is they who will have forgiveness": "Despite their best efforts, believers still make mistakes. Allah, in His mercy, promises to forgive their sins. This forgiveness wipes away their shortcomings and purifies them for Paradise. The Prophet (peace be upon him) said that a person who repents from sin is like one who has no sin at all.",
    "and an honourable provision": "The reward for believers is not just any provision—it is described as 'honourable' or 'generous.' This refers to Paradise and its endless blessings: food, drink, companionship, and pleasures that no eye has seen, no ear has heard, and no heart has imagined. This provision is given with dignity and honor, not as charity, but as a deserved reward."
  },
  5: {
    "As for those who strive to discredit Our revelations": "Some people do not simply disbelieve—they actively work to undermine Allah's message. They mock the Quran, spread doubts, and try to prevent others from accepting the truth. Their opposition is deliberate and persistent. History has seen many such individuals who dedicated their lives to fighting against divine guidance.",
    "it is they who will suffer the ˹worst˺ torment of agonizing pain": "The punishment for those who actively oppose Allah's revelations is severe. The word 'agonizing' emphasizes that this is not ordinary suffering but extreme torment. This is because their crime is not just personal disbelief—they tried to lead others astray as well, multiplying their sin."
  },
  6: {
    "Those gifted with knowledge ˹clearly˺ see": "In contrast to those who deny and oppose, there are people of knowledge—scholars and sincere seekers of truth—who recognize the Quran's authenticity. Their knowledge gives them insight and clarity. This includes those who studied previous scriptures and found them pointing to the Prophet Muhammad, as well as those who reflected deeply on the Quran's message and recognized its divine origin.",
    "that what has been revealed to you from your Lord ˹O Prophet˺ is the truth": "The Quran is not fabricated, nor is it the product of human imagination. People of knowledge see clearly that it is the absolute truth from Allah. Its internal consistency, its guidance, its prophecies that came true, and its transformative effect on individuals and societies all testify to its truthfulness.",
    "and that it guides to the Path of the Almighty, the Praiseworthy": "The Quran does not just contain truth—it actively guides to the straight path that leads to Allah. Allah is described as 'Almighty'—possessing absolute power—and 'Praiseworthy'—deserving all praise for His perfection. Following the Quran means following the path that leads to the One who has all power and all praise."
  },
  7: {
    "The disbelievers say ˹mockingly to one another˺, \"Shall we show you a man": "The disbelievers of Mecca used to mock the Prophet Muhammad (peace be upon him) among themselves. Instead of addressing him respectfully, they referred to him dismissively as 'a man,' trying to diminish his status. This is how arrogant people behave—they mock what they cannot refute with logic.",
    "who claims that when you have been utterly disintegrated you will be raised as a new creation?\"": "They found the concept of resurrection absurd. How could bodies that have completely decomposed, turned to dust, and scattered be brought back together? To their limited understanding, this was impossible. They failed to consider that the One who created them from nothing the first time can certainly recreate them."
  },
  8: {
    "Has he fabricated a lie against Allah or is he insane?\"": "The disbelievers could only come up with two explanations for the Prophet's message: either he was lying about receiving revelation, or he was mentally unstable. They could not accept a third possibility—that he was telling the truth. This shows how bias blinds people from seeing reality. The Prophet (peace be upon him) was known before his prophethood as 'Al-Amin' (the trustworthy), yet they now accused him of lying.",
    "In fact, those who do not believe in the Hereafter are bound for torment": "Allah responds by redirecting the focus. The problem is not with the Prophet—it is with those who reject the Hereafter. They are the ones heading toward punishment. Their denial does not change reality; it only seals their fate.",
    "and have strayed farthest ˹from the truth˺": "Not only are they wrong, but they have gone to the extreme of error. They are not slightly off course—they have completely lost their way. This is the consequence of rejecting the afterlife: it leads to a life of misguidance and ultimately to punishment."
  },
  9: {
    "Have they not then seen all that surrounds them of the heavens and the earth?": "Allah invites them to look around themselves—above and below, in front and behind. The heavens stretch endlessly above them, and the earth is beneath their feet. They are completely surrounded by Allah's creation, yet they fail to reflect on His power. If He created all of this, resurrection is easy for Him.",
    "If We willed, We could cause the earth to swallow them up": "Allah demonstrates His power by pointing out that He could destroy them instantly. The earth that they walk on could open up and swallow them, as it did with Qarun (Korah) who was arrogant about his wealth. This is a warning that their safety is not guaranteed—it is only by Allah's mercy that they continue to exist.",
    "or cause ˹deadly˺ pieces of the sky to fall upon them": "Similarly, Allah could send down destruction from above—meteors, stones, or any form of punishment from the sky. History records nations that were destroyed this way, such as the people of Lut (Lot), upon whom stones rained from the sky. The disbelievers should recognize their vulnerability.",
    "Surely in this is a sign for every servant who turns ˹to Allah˺": "The key to benefiting from these signs is having a heart that turns to Allah in repentance and reflection. A person who is arrogant and dismissive will see these signs but not benefit from them. But someone who sincerely seeks the truth will recognize Allah's power and submit to Him."
  },
  10: {
    "Indeed, We granted David a ˹great˺ privilege from Us": "Prophet David (Dawud, peace be upon him) was blessed with many special favors from Allah. He was given prophethood, kingship, wisdom, and a beautiful voice. These were not earned through his own power but were gifts from Allah. This teaches us that all our abilities and talents are ultimately from Allah.",
    "˹commanding:˺ \"O mountains! Echo his hymns! And the birds as well.\"": "When David would praise and glorify Allah, the mountains would echo back his hymns, and the birds would join him in glorification. Imagine the scene: a prophet praising Allah, and all of nature—mountains and birds—responding in worship. This shows that all of creation glorifies Allah, even if we cannot perceive it. The Quran states in Surah Al-Isra (17:44) that everything glorifies Allah, but we do not understand their glorification.",
    "We made iron mouldable for him": "Allah gave David the ability to shape iron with his bare hands, without needing fire to soften it. Iron, which is normally hard and requires intense heat to mold, became soft like dough in his hands. This was a miracle and also a practical skill that he used to serve his people by making armor for their protection."
  },
  11: {
    "instructing: \"Make full-length armour, ˹perfectly˺ balancing the links.": "Allah guided David to make coats of armor that were both protective and well-crafted. The links had to be balanced—not too loose that they would not protect, and not too tight that they would be heavy and restrictive. This teaches the importance of excellence and precision in one's work. David was a prophet and a king, yet he worked with his hands. The Prophet Muhammad (peace be upon him) said that the best food a person eats is that which he earns with his own hands, and David used to eat from the work of his own hands.",
    "And work righteousness ˹O family of David!˺": "Allah commanded not just David, but his entire family, to do righteous deeds. Blessings come with responsibilities. The family of a prophet is not exempt from doing good—in fact, more is expected of them. This is a reminder that lineage alone does not guarantee salvation; righteous action is required.",
    "Indeed, I am All-Seeing of what you do.\"": "Allah concludes with a reminder that He sees everything they do. This should motivate them to work sincerely and avoid cutting corners. Whether they are making armor or doing any other task, Allah is watching. This applies to us as well—Allah sees our work, our intentions, and our efforts."
  },
  12: {
    "And to Solomon ˹We subjected˺ the wind: its morning stride was a month's journey and so was its evening stride": "Prophet Solomon (Sulayman, peace be upon him) was given control over the wind. It would carry him and his army a distance that would normally take a month of travel—in just one morning or one evening. This was an extraordinary power that allowed him to rule a vast kingdom efficiently. It demonstrates that Allah can give miraculous abilities to His chosen servants.",
    "And We caused a stream of molten copper to flow for him": "Just as iron was made soft for David, Allah caused molten copper to flow for Solomon like a spring of water. This allowed him to create various tools, structures, and items needed for his kingdom. Copper was valuable, and having an endless flow of it was a tremendous blessing.",
    "and ˹We subjected˺ some of the jinn to work under him by his Lord's Will": "Allah placed certain jinn under Solomon's command. The jinn are beings created from smokeless fire, and they possess abilities that humans do not have. Having them serve him allowed Solomon to accomplish tasks that would be impossible for humans alone.",
    "And whoever of them deviated from Our command, We made them taste the torment of the blaze": "The jinn were not free to disobey. If any of them stepped out of line or refused to follow Allah's commands given through Solomon, they faced punishment. This shows that these jinn were under divine supervision, and their service to Solomon was by Allah's decree, not their own choice."
  },
  13: {
    "They made for him whatever he desired of sanctuaries, statues,": "The jinn built grand structures for worship (sanctuaries or prayer halls) and statues. Some scholars explain that these statues were not of living beings or for worship—they may have been decorative figures, images of trees, or other permissible forms. It is important to note that this was permissible in Solomon's law, while in the law of Prophet Muhammad (peace be upon him), making statues of living beings is prohibited.",
    "basins as large as reservoirs, and cooking pots fixed ˹into the ground˺": "The jinn also made enormous basins, so large they were like ponds, and massive cooking pots that were fixed in place because of their size. These were used to feed the armies and guests of Solomon's kingdom. The scale of these items shows the grandeur of his rule.",
    "˹We ordered:˺ \"Work gratefully, O family of David!\"": "Allah commanded the family of David—including Solomon—to express gratitude through their work and worship. Gratitude is not just saying 'thank you' with words; it is shown through obedience to Allah and using His blessings in ways that please Him.",
    "˹Only˺ a few of My servants are ˹truly˺ grateful": "Despite all the blessings Allah gives, only a small number of people are truly grateful. This is a profound statement. Many people take blessings for granted or attribute them to their own efforts. True gratitude involves recognizing that all blessings come from Allah and using them to serve Him."
  },
  14: {
    "When We decreed Solomon's death, nothing indicated to the ˹subjected˺ jinn that he was dead": "When Solomon died, he passed away while leaning on his staff in a standing position. The jinn who worked under him did not realize he had died. They continued their labor, thinking he was still watching over them. This situation continued for a considerable time.",
    "except the termites eating away his staff": "The only thing that eventually revealed Solomon's death was a small creature—termites. They slowly ate through the wooden staff he was leaning on. When the staff finally broke and Solomon's body fell to the ground, only then did everyone realize he had been dead for some time.",
    "So when he collapsed, the jinn realized that if they had ˹really˺ known the unseen, they would not have remained in ˹such˺ humiliating servitude": "This event exposed an important truth: the jinn do not know the unseen. Before this, some people believed that jinn had knowledge of the unseen world. But if they truly had such knowledge, they would have known Solomon was dead and would not have continued working in difficult servitude. This story corrects the false belief that jinn possess knowledge of the unseen. Only Allah knows the unseen."
  },
  15: {
    "Indeed, there was a sign for ˹the tribe of˺ Sheba in their homeland": "The people of Sheba (Saba) lived in Yemen, in a land that was blessed with abundance. Their prosperity itself was a sign from Allah—evidence of His power to provide and His expectation of gratitude. Signs are meant to lead people to recognize and worship Allah.",
    "two orchards—one to the right and the other to the left": "They had lush gardens on both sides of their valley, producing abundant fruits and crops. This created a beautiful and prosperous environment. Walking through their land, one would see greenery and bounty on every side.",
    "˹They were told:˺ \"Eat from the provision of your Lord, and be grateful to Him.\"": "Allah invited them to enjoy His blessings and to respond with gratitude. The condition for continued blessings is thankfulness. When a person is grateful, Allah increases His favors, as He says in Surah Ibrahim (14:7): 'If you are grateful, I will surely increase you.'",
    "˹Yours is˺ a good land and a forgiving Lord.\"": "They had the best of both worlds—a fertile land that provided for their physical needs and a Forgiving Lord who would pardon their sins if they repented. What more could anyone ask for? Yet despite this, they failed to appreciate these blessings."
  },
  16: {
    "But they turned away": "Instead of being grateful and obedient, the people of Sheba turned away from Allah. They became arrogant and ungrateful, attributing their success to their own efforts rather than to Allah's blessings. This is a common mistake—when things are going well, people forget the source of their blessings.",
    "So We sent against them a devastating flood": "Allah punished them with the flood of the dam (the Ma'rib Dam). This massive dam, which had provided water for their agriculture, burst and flooded their land. The very infrastructure that had been a source of blessing became the means of destruction. This is a lesson: blessings can be taken away as quickly as they were given.",
    "and replaced their orchards with two others producing bitter fruit, fruitless bushes, and a few ˹sparse˺ thorny trees": "The beautiful, fruit-bearing gardens were replaced with thorny, bitter vegetation. Where there was once abundance, there was now scarcity. Where there was sweetness, there was now bitterness. The transformation was complete—their punishment matched their ingratitude."
  },
  17: {
    "This is how We rewarded them for their ingratitude": "Allah makes clear that this punishment was a direct consequence of their ingratitude. The word 'rewarded' is used ironically—just as good deeds are rewarded with good, ingratitude is 'rewarded' with punishment. Cause and effect are at work in both directions.",
    "Would We ever punish ˹anyone in such a way˺ except the ungrateful?": "This rhetorical question emphasizes that severe punishment is reserved for those who are persistently ungrateful. Allah does not punish without reason, and He does not punish the grateful. The lesson is clear: gratitude protects blessings, while ingratitude leads to their loss."
  },
  18: {
    "We had also placed between them and the cities We showered with blessings ˹many small˺ towns within sight of one another": "Allah blessed the people of Sheba with another favor: a network of towns between their homeland and the blessed lands of Syria. These towns were close enough that travelers could always see the next destination. This made travel easy and eliminated the fear of getting lost in the wilderness.",
    "And We set moderate travel distances in between, ˹saying,˺ \"Travel between them by day and night safely.\"": "The distances were manageable, and security was guaranteed. Travelers could journey at any time—day or night—without fear of bandits or hardship. This was a tremendous blessing, especially in ancient times when travel was dangerous. They had safety, convenience, and prosperity all at once."
  },
  19: {
    "But they said, \"Our Lord! Make ˹the distances of˺ our journeys longer,\" wronging themselves": "Astonishingly, the people of Sheba complained about the ease of their travels. They wanted longer, more difficult journeys—perhaps so they could charge more for trade or feel more important. This bizarre request shows how ingratitude distorts thinking. They did not appreciate the blessing of convenience and instead asked for hardship. In doing so, they wronged themselves.",
    "So We reduced them to ˹cautionary˺ tales": "Allah granted their wish in a way they did not expect. Their civilization collapsed, and they became scattered. Their story became a lesson for future generations—a warning about what happens when people reject Allah's blessings. Today, people mention the 'Dam of Ma'rib' as an example of a destroyed civilization.",
    "and scattered them utterly": "The once-unified people of Sheba were dispersed across the land. Their community was broken apart, and they lost their identity as a prosperous nation. This complete scattering was the consequence of their ingratitude.",
    "Surely in this are lessons for whoever is steadfast, grateful": "Allah concludes by highlighting who benefits from this story: those who are patient in hardship and grateful in ease. These two qualities—patience and gratitude—are essential for a believer. A grateful person appreciates blessings, and a patient person endures trials. Together, these qualities protect a person from the fate of the ungrateful."
  },
  20: {
    "Indeed, Iblîs' assumption about them has come true": "When Satan (Iblis) was expelled from Paradise, he made a bold claim: he would mislead most of humanity. This verse confirms that his assumption proved correct for many people. Most humans followed his whispers and strayed from the straight path. This is a sobering reality about the state of humanity.",
    "so they ˹all˺ follow him, except a group of ˹true˺ believers": "Satan succeeded with the majority, but not everyone. A group of true believers resisted his temptations and remained faithful to Allah. These are the people who sought Allah's protection, followed His guidance, and did not give in to Satan's deceptions. Being among this group requires conscious effort and constant vigilance."
  },
  21: {
    "He does not have any authority over them": "Satan has no real power to force anyone to sin. He cannot compel obedience or physically make someone commit evil. His only tool is whispering and suggestion. The Quran states in Surah Ibrahim (14:22) that on the Day of Judgment, Satan will say to those who followed him: 'I had no authority over you except that I invited you and you responded to me.' This means humans have the ability to resist his temptations.",
    "but ˹Our Will is˺ only to distinguish those who believe in the Hereafter from those who are in doubt about it": "Allah allowed Satan to exist as a test. Through Satan's temptations, the true believers are distinguished from those who merely claim faith. Those who truly believe in the afterlife behave differently from those who doubt it. The test reveals what is in people's hearts.",
    "And your Lord is a ˹vigilant˺ Keeper over all things": "Allah watches over everything with complete knowledge and care. He sees who resists Satan and who succumbs, who remains steadfast and who wavers. Nothing escapes His observation. This should comfort the believers—their efforts are seen—and warn the heedless—their actions are recorded."
  },
  22: {
    "Say, ˹O Prophet,˺ \"Call upon those you claim ˹to be divine˺ besides Allah.": "Allah commands the Prophet to challenge the polytheists. If their idols or false gods have any power, let them demonstrate it. This is a direct challenge that exposes the weakness of everything worshipped besides Allah.",
    "They do not possess ˹even˺ an atom's weight either in the heavens or the earth": "The false gods own absolutely nothing—not even the weight of a tiny atom anywhere in the universe. They have no property, no control, and no power over anything. This complete lack of ownership means they cannot benefit or harm anyone.",
    "nor do they have any share in ˹governing˺ them": "Not only do they not own anything, but they also have no partnership with Allah in managing the universe. Allah rules alone, creates alone, and sustains alone. The false gods are not junior partners or assistants—they have no role whatsoever.",
    "Nor is any of them a helper to Him.\"": "Finally, Allah does not need any help from these false gods. He is completely self-sufficient. Some might think that idols could at least assist Allah, but even this is false. Allah needs nothing and no one. This verse systematically removes every possible justification for worshipping anything besides Allah."
  },
  23: {
    "No intercession will be of any benefit with Him, except by those granted permission by Him": "Some people worship idols hoping they will intercede for them with Allah. This verse clarifies that intercession only happens with Allah's permission. No one can speak on behalf of another unless Allah allows it. On the Day of Judgment, even the prophets will only intercede for those whom Allah permits them to intercede for.",
    "˹At last,˺ when the dread ˹of Judgment Day˺ is relieved from their hearts ˹because they are permitted to intercede˺": "This describes a scene on the Day of Judgment. Those who are permitted to intercede experience intense fear and apprehension until they receive permission from Allah. When that permission is granted, their hearts are relieved of the dread.",
    "they will ˹excitedly˺ ask ˹the angels˺, \"What has your Lord ˹just˺ said?\"": "In their eagerness, those who receive permission will ask the angels what Allah has decreed. The excitement and anxiety of that moment are captured in this question. They want confirmation that they are indeed allowed to intercede.",
    "The angels will reply, \"The truth! And He is the Most High, All-Great.\"": "The angels confirm that Allah has spoken the truth—that permission has been granted. They also remind everyone of Allah's supreme status: He is the Most High, above all creation, and All-Great, possessing ultimate majesty. This exchange emphasizes that all authority rests with Allah."
  },
  24: {
    "Ask ˹them, O Prophet˺, \"Who provides for you from the heavens and the earth?\"": "The Prophet is commanded to ask a fundamental question: Who sends down rain from the sky and causes crops to grow from the earth? Who provides food, water, and sustenance? This is a question that even the polytheists of Mecca could not answer except by acknowledging Allah.",
    "Say, \"Allah!": "The answer is definitive—Allah alone provides. This is something even the polytheists admitted. If they agreed that Allah is the sole provider, how could they justify worshipping others besides Him?",
    "Now, certainly one of our two groups is ˹rightly˺ guided; the other is clearly astray.\"": "The Prophet presents a logical conclusion: either the Muslims are right and the polytheists are wrong, or vice versa. Both cannot be true. This statement is diplomatic yet firm—it invites reflection without being unnecessarily provocative. It challenges the polytheists to think seriously about which group is truly guided."
  },
  25: {
    "Say, \"You will not be accountable for our misdeeds\"": "The Prophet is instructed to tell the disbelievers that they will not be questioned about what the Muslims do. On the Day of Judgment, each person is responsible for their own actions. This separates the accountability—no one will bear the burden of another.",
    "nor will we be accountable for your deeds.\"": "Similarly, the Muslims will not be questioned about the actions of the disbelievers. This cuts both ways and emphasizes individual responsibility. It also implies a warning: you will face the consequences of your own choices, so choose wisely."
  },
  26: {
    "Say, \"Our Lord will gather us together\"": "On the Day of Judgment, Allah will bring everyone together—believers and disbelievers, Muslims and polytheists. No one will escape that gathering. The current disagreement will be resolved on that day.",
    "then He will judge between us with the truth": "Allah will make the final judgment, and His judgment will be based on truth and justice. There will be no bias, no error, and no appeal. The truth will become clear to everyone, and every dispute will be settled.",
    "For He is the All-Knowing Judge.\"": "Allah is described as the One who opens and decides all matters (Al-Fattah) and the One who knows everything (Al-Alim). His judgment is perfect because He has complete knowledge of all facts, intentions, and circumstances."
  },
  27: {
    "Say, \"Show me those ˹idols˺ you have joined with Him as partners.": "The Prophet challenges the polytheists to present their idols. Let them demonstrate what these false gods can do. Can they create? Can they provide? Can they protect? This challenge exposes the absurdity of polytheism.",
    "No!": "This is a firm rejection. The answer is emphatically negative—these idols have nothing to show. They are powerless objects that cannot help themselves, let alone help their worshippers.",
    "In fact, He ˹alone˺ is Allah—the Almighty, All-Wise.\"": "The reality is that only Allah deserves worship. He is Al-Aziz—the Almighty, possessing all power and honor. He is Al-Hakim—the All-Wise, doing everything with perfect wisdom. No idol, no false god, no created being shares these attributes. Therefore, worship belongs to Allah alone."
  },
  28: {
    "We have sent you ˹O Prophet˺ only as a deliverer of good news": "The Prophet Muhammad (peace be upon him) was sent with good news for those who believe and do righteous deeds. He brings the glad tidings of Paradise, Allah's forgiveness, and eternal happiness for those who follow the guidance. Unlike previous prophets who were sent to specific nations, his message of hope extends to all humanity.",
    "and a warner to all of humanity": "Alongside the good news, the Prophet also warns humanity about the consequences of disbelief and sin. He warns about the Day of Judgment, the punishment of Hell, and the fate of those who reject Allah's message. This dual role—bringing hope and warning—is essential for guiding people to make informed choices about their lives.",
    "but most people do not know": "Despite the clarity of the Prophet's message, most people remain unaware of its truth and significance. This ignorance is not due to any fault in the message but rather due to people's heedlessness, arrogance, or attachment to worldly distractions. The Prophet (peace be upon him) said that Islam began as something strange and will return to being strange, and blessed are the strangers who hold onto the truth when most people abandon it."
  },
  29: {
    "And they ask ˹the believers˺, \"When will this threat come to pass": "The disbelievers mockingly demanded to know the exact timing of the Day of Judgment. Their question was not sincere—they did not genuinely want to know so they could prepare. Rather, they asked sarcastically, implying that since it had not happened yet, it never would. This is a common tactic of those who deny the truth: demanding immediate proof while ignoring the evidence already before them.",
    "if what you say is true?\"": "They challenged the truthfulness of the believers' claims. By adding this condition, they suggested that the delay in punishment was proof that the believers were lying. However, Allah's delay is a mercy—giving people time to repent—not evidence that the Day will never come."
  },
  30: {
    "Say, ˹O Prophet,˺ \"A Day has ˹already˺ been appointed for you": "Allah commands the Prophet to respond that the Day of Judgment has already been fixed in Allah's knowledge. It is not a vague possibility but a certain appointment. Just as a person has an appointment with death that they cannot escape, humanity has an appointment with the Day of Reckoning.",
    "which you can neither delay nor advance by a ˹single˺ moment.\"": "When that appointed time arrives, no one can postpone it even by a second, nor can anyone bring it forward. Human beings have no control over this timing. This response puts the disbelievers in their place—their mockery will not delay the Day, and their denial will not prevent it from coming."
  },
  31: {
    "The disbelievers vow, \"We will never believe in this Quran, nor in those ˹Scriptures˺ before it.\"": "The stubborn disbelievers made a categorical declaration: they would reject the Quran and all previous scriptures. This shows their complete closure to guidance. They did not reject after careful examination—they rejected outright, refusing to even consider the truth. This kind of blind rejection is the most dangerous form of disbelief.",
    "If only you could see when the wrongdoers will be detained before their Lord, throwing blame at each other!": "Allah describes a scene from the Day of Judgment. The wrongdoers will stand before Allah, and instead of taking responsibility for their choices, they will blame one another. The unity they had in disbelief will dissolve into bitter accusations. This is the nature of relationships not built on truth—they fall apart when tested.",
    "The lowly ˹followers˺ will say to the arrogant ˹leaders˺, \"Had it not been for you, we would certainly have been believers.\"": "Those who followed their leaders blindly will blame those leaders for their misguidance. They will claim that they would have believed if not for the influence of their arrogant chiefs. This is a partial truth—they were indeed misled—but it does not absolve them of responsibility, as they chose to follow without thinking."
  },
  32: {
    "The arrogant will respond to the lowly, \"Did we ever hinder you from guidance after it came to you?": "The leaders will defend themselves by arguing that they did not physically prevent anyone from believing. The guidance was available; the message was clear. No one held a sword to their heads forcing them to disbelieve. This defense, while technically true in some cases, ignores the social pressure, mockery, and manipulation they used.",
    "In fact, you were wicked ˹on your own˺.\"": "The leaders will turn the blame back on the followers, saying they were criminals by their own choice. Each group tries to escape punishment by blaming the other. The reality is that both are guilty—the leaders for misleading, and the followers for choosing to be misled when truth was available."
  },
  33: {
    "The lowly will say to the arrogant, \"No! It was your plotting by day and night": "The followers will counter the leaders' argument by pointing out their continuous scheming. Day and night, the leaders worked to keep people away from the truth. They used propaganda, social pressure, economic incentives, and constant persuasion to maintain their followers' disbelief.",
    "—when you ordered us to disbelieve in Allah and to set up equals with Him.\"": "The followers will specifically accuse the leaders of commanding them to reject Allah and associate partners with Him. This was not passive influence but active instruction. The leaders promoted idol worship and fought against monotheism.",
    "They will ˹all˺ hide ˹their˺ remorse when they see the torment": "When they finally witness the punishment, both groups will be overwhelmed with regret. But this regret will be hidden—perhaps out of shame, or perhaps because they realize it is too late for it to benefit them. Internal regret without the possibility of repentance is a torment in itself.",
    "And We will put shackles around the necks of the disbelievers": "Allah describes the physical punishment awaiting the disbelievers—iron shackles around their necks. This imagery conveys humiliation and restriction. Those who were arrogant and free in their disbelief will be bound and constrained in punishment.",
    "Will they be rewarded except for what they used to do?": "This rhetorical question emphasizes divine justice. Their punishment is not arbitrary—it is the direct consequence of their actions. They earned this fate through their choices. Allah does not wrong anyone; people wrong themselves."
  },
  34: {
    "Whenever We sent a warner to a society, its elite would say, \"We truly reject what you have been sent with.\"": "Throughout history, the pattern has been consistent: when prophets came with guidance, the wealthy and powerful elite were the first to reject them. Their comfortable lives made them resistant to change. They feared losing their status and privilege if the social order changed. The poor and oppressed were often more receptive because they had less to lose and more to gain from divine justice."
  },
  35: {
    "Adding, \"We are far superior ˹to the believers˺ in wealth and children": "The elite boasted about their material advantages. They had more money, more children, more social standing. In their flawed reasoning, these blessings were proof of Allah's approval. If Allah was displeased with them, why would He give them so much? This is a dangerous misunderstanding of how blessings work.",
    "and we will never be punished.\"": "Based on their worldly success, they concluded that they were immune from punishment. This arrogant assumption ignored the reality that Allah tests people with both blessings and hardships. Wealth can be a test—will the person be grateful and generous, or arrogant and miserly? Many wealthy nations of the past were destroyed despite their prosperity."
  },
  36: {
    "Say, ˹O Prophet,˺ \"Surely ˹it is˺ my Lord ˹Who˺ gives abundant or limited provisions to whoever He wills.": "Allah commands the Prophet to clarify the truth about wealth. Allah is the One who decides who receives abundant provisions and who receives limited provisions. This distribution is based on His wisdom, not on a person's righteousness or wickedness. A disbeliever may be wealthy as a test, and a believer may be poor as a test.",
    "But most people do not know.\"": "Most people misunderstand the relationship between wealth and divine approval. They assume that prosperity indicates Allah's pleasure and poverty indicates His displeasure. This is incorrect. The Prophet (peace be upon him) was offered the treasures of the earth but chose to live humbly, eating one day and going hungry the next, to show that worldly wealth is not the goal."
  },
  37: {
    "It is not your wealth or children that bring you closer to Us.": "Allah directly refutes the assumption that material blessings indicate closeness to Him. Money and children, on their own, have no spiritual value. A person can be wealthy and far from Allah, or poor and beloved by Allah. What matters is not what you have, but what you do with what you have.",
    "But those who believe and do good—it is they who will have a multiplied reward for what they did": "The true criteria for closeness to Allah are faith and righteous action. Those who combine these two will receive multiplied rewards. Allah's generosity means that a single good deed can be rewarded ten times, or even seven hundred times, or more. This multiplication is a gift from Allah's mercy.",
    "and they will be secure in ˹elevated˺ mansions.": "The believers will dwell in high chambers in Paradise, safe from all fear and harm. While the arrogant elite boasted about their earthly mansions, the believers will inherit eternal mansions that far surpass anything in this world. Security and elevation—both physical and spiritual—await the righteous."
  },
  38: {
    "As for those who strive to discredit Our revelations": "Some people do not simply disbelieve—they actively work to undermine Allah's message. They spread doubts, mock the believers, and try to prevent others from accepting the truth. Their opposition is deliberate and sustained.",
    "it is they who will be confined in punishment.": "These active opponents of truth will be brought into punishment and held there. The word 'confined' suggests they will be imprisoned in torment with no escape. Their efforts to discredit Allah's signs will result in their own eternal confinement."
  },
  39: {
    "Say, ˹O Prophet,˺ \"Surely ˹it is˺ my Lord ˹Who˺ gives abundant or limited provisions to whoever He wills of His servants.": "This point is repeated for emphasis. Allah alone controls provision. Understanding this should remove both arrogance from the wealthy and despair from the poor. Everything comes from Allah, and He distributes according to His wisdom.",
    "And whatever you spend in charity, He will compensate ˹you˺ for it.": "This is a powerful promise: whatever you give in Allah's cause will be replaced. This compensation may come in this life through unexpected provisions, or in the next life through multiplied rewards. Charity does not decrease wealth—it increases it in ways we may not immediately see. The Prophet (peace be upon him) said that charity does not diminish wealth.",
    "For He is the Best Provider.\"": "Allah concludes by affirming that He is the best of all providers. No employer, no government, no system can provide like Allah provides. When you trust Him and give generously, He provides from sources you never expected. This should encourage believers to be generous without fear of poverty."
  },
  40: {
    "And ˹consider˺ the Day He will gather them all together": "On the Day of Judgment, Allah will gather all of creation—humans, jinn, and angels. No one will be absent from this gathering. The polytheists will be brought face to face with those they worshipped besides Allah.",
    "and then ask the angels, \"Was it you that these ˹polytheists˺ used to worship?\"": "Allah will question the angels in front of the polytheists. This is not because Allah does not know—He knows everything—but to establish the truth publicly and to humiliate the polytheists. The angels will be asked whether they commanded or approved of being worshipped."
  },
  41: {
    "They will say, \"Glory be to You! Our loyalty is to You, not them.": "The angels will immediately declare Allah's perfection and distance themselves from the polytheists. They will affirm that their allegiance is to Allah alone. They never asked to be worshipped and never approved of it. This declaration exposes the polytheists' error.",
    "In fact, they ˹only˺ followed the ˹temptations of evil˺ jinn, in whom most of them had faith.\"": "The angels will clarify who the polytheists were really following: the evil jinn (devils) who whispered to them and tempted them toward false worship. The jinn deceived them into thinking they were worshipping angels or other noble beings, when in reality they were following satanic influences. Most of these polytheists placed their faith in these deceptive jinn rather than in Allah."
  },
  42: {
    "So Today neither of you can benefit or protect each other.": "On that Day, all the false bonds between worshippers and the worshipped will be severed. Neither the idols, nor the angels wrongly worshipped, nor the jinn, nor any other object of false worship can help their followers. And the followers cannot help them either. Everyone stands alone before Allah.",
    "And We will say to the wrongdoers, \"Taste the torment of the Fire, which you used to deny.\"": "The wrongdoers will be told to experience the very punishment they rejected as impossible. They denied the Fire, mocked warnings about it, and lived as if it did not exist. Now they will taste it firsthand. The word 'taste' implies a direct, personal experience that cannot be denied or escaped."
  },
  43: {
    "When Our clear revelations are recited to them, they say, \"This is only a man who wishes to hinder you from what your forefathers used to worship.\"": "When the Quran was recited to the polytheists, they accused the Prophet of trying to turn them away from their ancestral religion. They valued tradition over truth. In their minds, anything that contradicted what their fathers did must be wrong. This blind attachment to tradition prevented them from accepting guidance.",
    "They also say, \"This ˹Quran˺ is no more than a fabricated lie.\"": "They accused the Prophet of inventing the Quran himself and attributing it to Allah. This accusation ignored the obvious: the Prophet was known for his honesty before prophethood, the Quran's style was unlike anything he or anyone else could produce, and its message was consistent with previous scriptures.",
    "And the disbelievers say of the truth when it has come to them, \"This is nothing but pure magic.\"": "Another accusation was that the Quran was magic. They could not explain its powerful effect on people's hearts, so they attributed it to sorcery. This accusation was self-defeating: if it was magic that captivated hearts toward good, then why not embrace it? Their accusations were inconsistent—sometimes calling it lies, sometimes magic—revealing their confusion."
  },
  44: {
    "˹They say so even though˺ We had never given them any scriptures to study": "Allah points out the irony: the Meccan polytheists had no previous scripture from Allah that they were following. They had no book to study or refer to. So on what basis were they rejecting the Quran? They were not defending a revealed religion—they were defending ignorance and invention.",
    "nor did We ever send them a warner before you ˹O Prophet˺": "Before Prophet Muhammad (peace be upon him), no messenger had been sent specifically to the Arabs. They were in a state of spiritual darkness. The Prophet came as the first divine messenger to them, and yet they rejected him. This ingratitude for a long-awaited blessing was remarkable."
  },
  45: {
    "Those ˹destroyed˺ before them denied as well": "The Meccan polytheists were not the first to deny Allah's messengers. Many nations before them—the people of Noah, 'Ad, Thamud, and others—rejected their prophets and faced destruction.",
    "—and these ˹Meccans˺ have not attained even one-tenth of what We had given their predecessors.": "The previous nations were far more powerful, wealthy, and numerous than the Meccans. If those mighty civilizations could not escape Allah's punishment, what chance did the comparatively weak Meccans have? This comparison should humble them.",
    "Yet ˹when˺ they denied My messengers, how severe was My response!": "Allah destroyed those nations completely. Their ruins remain as warnings. The severity of Allah's response should serve as a deterrent. The Meccans were being warned: do not follow in the footsteps of destroyed nations."
  },
  46: {
    "Say, ˹O Prophet,˺ \"I advise you to do ˹only˺ one thing": "The Prophet is commanded to offer a simple, clear advice. He does not ask for complicated rituals or blind acceptance. Just one thing is requested—and it is something anyone can do.",
    "stand up for ˹the sake of˺ Allah—individually or in pairs—then reflect.": "The advice is to stand up sincerely seeking truth—either alone or with a companion—and think deeply. Alone, a person is free from peer pressure and mob mentality. In pairs, they can discuss and reason together. The key is sincere reflection, not superficial reaction. When people think honestly, they often arrive at the truth.",
    "Your fellow man is not insane.": "The Prophet asks them to consider: is Muhammad really insane? They knew him for forty years before prophethood. He was known as trustworthy and wise. Insanity does not produce a book like the Quran or a movement that transformed the world. Simple reflection should lead them to realize he is not mad.",
    "He is only a warner to you before ˹the coming of˺ a severe punishment.\"": "The Prophet's role is clear: he warns of a severe punishment that is coming. He gains nothing personally from this warning. Like someone warning about a coming storm, he speaks out of concern for their welfare. Rejecting the warning does not stop the storm—it only leaves them unprepared."
  },
  47: {
    "Say, \"If I had ever asked you for a reward, you could keep it.": "The Prophet never sought payment for his message. He did not ask for money, status, or any worldly benefit. If he had, they could keep it—he has no need for it. This challenges any accusation that he was motivated by personal gain. His sincerity is proven by his sacrifice.",
    "My reward is only from Allah.": "The Prophet's compensation comes from Allah alone. He delivered the message for Allah's sake, and Allah will reward him. This purity of intention is what made his mission successful. He was not a businessman selling religion—he was a servant of Allah conveying truth.",
    "And He is a Witness over all things.\"": "Allah witnesses everything—the Prophet's sincerity, the people's response, and all that occurs. Nothing escapes His knowledge. This serves as a reminder that all parties are accountable for their actions."
  },
  48: {
    "Say, \"Surely my Lord hurls the truth ˹against falsehood˺.": "Allah casts the truth powerfully against falsehood, shattering it. The imagery is of something being thrown with force—truth is not weak or hesitant. It comes with divine power and destroys everything false in its path. The Quran came to dismantle the false beliefs of the polytheists.",
    "˹He is˺ the Knower of all unseen.\"": "Allah knows everything that is hidden—past, present, and future. His knowledge encompasses all secrets. The Prophet's message is not his own invention; it comes from the One who knows all things unseen. This should give the message credibility."
  },
  49: {
    "Say, \"The truth has come": "Truth has arrived in the form of the Quran and the Prophet's message. It is no longer absent or awaited—it is here, clear and accessible. This is a decisive announcement.",
    "and falsehood will vanish, never to return.\"": "Falsehood cannot stand against truth. Once truth arrives, falsehood is exposed, weakened, and eventually destroyed. It has no power to originate anything new or to restore itself once defeated. The idol worship and ignorance of the pre-Islamic era were destined to disappear with the coming of Islam."
  },
  50: {
    "Say, \"If I am astray, the loss is only mine.": "The Prophet presents a humble argument: if he is wrong, he bears the consequences himself. His misguidance would not harm them. This shows he is not asking them to take a risk on his behalf—he is the one taking responsibility.",
    "And if I am guided, it is ˹only˺ because of what my Lord reveals to me.": "If the Prophet is guided, it is due to Allah's revelation, not his own intelligence or invention. He credits all guidance to Allah. This humility and attribution to Allah characterize true prophets—they do not seek glory for themselves.",
    "He is indeed All-Hearing, Ever Near.\"": "Allah hears every prayer, every whisper, and every thought. He is near to His servants—not physically, but in His knowledge, awareness, and responsiveness. This closeness should comfort believers and concern those who think they can hide from Allah."
  },
  51: {
    "If only you could see when they will be horrified with no escape ˹on Judgment Day˺!": "Allah describes the terror the disbelievers will experience when they face the reality of the Day of Judgment. Their horror will be complete—no exit, no hiding place, no one to rescue them. The arrogance they displayed in this world will dissolve into absolute fear.",
    "And they will be seized from a nearby place.": "They will be caught from a place very close—perhaps from their graves, or from wherever they are when the Hour strikes. There will be no time to flee, no distance to create. The punishment will be immediate and inescapable."
  },
  52: {
    "They will ˹then˺ cry, \"We do ˹now˺ believe in it ˹all˺.\"": "When they see the punishment, they will suddenly declare their belief. They will claim to believe in Allah, the Day of Judgment, and everything they denied. But this is a desperate, insincere declaration made only because they have no other option.",
    "But how could they ˹possibly˺ attain faith from a place so far-off ˹from the world˺": "Their belief is now meaningless because they are too far from the world where faith could benefit them. The time for faith was during their earthly lives. Now that they have crossed into the afterlife, it is too late. Faith declared under compulsion, when punishment is visible, is not accepted."
  },
  53: {
    "while they had already rejected it before": "Their newfound faith is contradicted by their previous rejection. When they were in the world and had the opportunity to believe freely, they chose to deny. Their prior rejection cancels the value of their current declaration.",
    "guessing blindly from a place ˹equally˺ far-away ˹from the Hereafter˺?": "During their worldly life, they made baseless claims about the unseen—the afterlife, resurrection, and judgment. They spoke about things they had no knowledge of, making wild guesses from a position of complete ignorance. Just as they were far from the afterlife then (in their denial), they are now far from the world where faith could save them."
  },
  54: {
    "They will be sealed off from whatever they desire": "A barrier will be placed between them and everything they want—salvation, mercy, return to the world, or escape from punishment. All their desires will be blocked. In this life, they pursued their desires freely; in the next, they will be denied everything.",
    "as was done to their counterparts before.": "This is not a new occurrence—the same fate befell previous nations who denied their messengers. The people of Pharaoh, the people of 'Ad, and others all experienced this barrier between them and their wishes when punishment came. History repeats itself for those who repeat the same mistakes.",
    "Indeed, they were ˹all˺ in alarming doubt.": "The root cause of their destruction was doubt—not ordinary uncertainty, but a deep, unsettling doubt that they chose to ignore rather than investigate. They could have sought the truth, but they preferred to remain in doubt. This doubt led to rejection, and rejection led to punishment. The cycle is a warning for all who allow doubt to prevent them from seeking truth."
  }
};