var tafsirData_59 = {
  1: {
    "Whatever is in the heavens and whatever is on the earth glorifies Allah": "Every single creation in existence—whether in the skies above or on the earth below—constantly praises and declares the perfection of Allah. This includes the angels, humans, animals, plants, mountains, and even atoms. Everything in creation submits to Allah and acknowledges His greatness, whether we can perceive it or not. The Prophet Muhammad (peace be upon him) once told his companions that he could hear the tasbeeh (glorification) of food as it was being eaten. This opening reminds us that we are part of a universe that is in constant worship of its Creator, and we should join in that glorification consciously and willingly.",
    "For He is the Almighty": "Allah possesses absolute power and might. No one can overpower Him, resist His decree, or escape His authority. This attribute is especially relevant to the context of this surah, where Allah demonstrated His power over the Jewish tribe of Banu An-Nadir who thought they were untouchable in their fortresses.",
    "All-Wise": "Every action Allah takes, every decree He issues, and every law He legislates is based on perfect wisdom. Nothing happens randomly or without purpose. When Allah expelled Banu An-Nadir, it was done with complete wisdom—for the benefit of the Muslim community and as a lesson for all of humanity."
  },
  2: {
    "He is the One Who expelled the disbelievers of the People of the Book from their homes": "Allah directly attributes this expulsion to Himself, showing that it was His divine action and decree. The \"disbelievers of the People of the Book\" refers specifically to the Jewish tribe of Banu An-Nadir who lived in Medina. Despite having scriptures and knowledge of previous prophets, they rejected Prophet Muhammad (peace be upon him) and conspired against the Muslims. After the Battle of Uhud, they plotted to assassinate the Prophet by dropping a boulder on him while he sat near a wall. Allah revealed their plot to the Prophet, and they were subsequently besieged and expelled from Medina.",
    "for ˹their˺ first banishment ˹ever˺": "This was the first time this tribe had ever been driven out of their homes. They had lived securely in Medina for generations, and no one had ever displaced them before. Some scholars say \"first\" also indicates that a second banishment would come later (during the time of Umar ibn al-Khattab when Jews were expelled from the Arabian Peninsula entirely). This shows how quickly fortunes can change when one opposes Allah and His Messenger.",
    "You never thought they would go": "Even the Muslims were surprised at how easily Banu An-Nadir were expelled. This tribe was wealthy, well-armed, and had strong fortifications. Humanly speaking, removing them seemed nearly impossible. Yet Allah made it happen with minimal fighting, showing that victory comes from Him alone, not from military strength.",
    "And they thought their strongholds would put them out of Allah's reach": "Banu An-Nadir placed their trust in their fortresses, their wealth, and their alliances with the hypocrites of Medina. They believed these material defenses would protect them from any consequences. This is a timeless lesson: no amount of worldly security can protect anyone from Allah's decree. Many powerful nations throughout history have fallen despite their advanced defenses because they opposed the truth.",
    "But ˹the decree of˺ Allah came upon them from where they never expected": "Allah's plan unfolded in ways they could never have anticipated. They expected external military defeat, but instead, Allah struck terror into their hearts from within. The Prophet (peace be upon him) said: \"I have been given victory through terror (cast into the hearts of my enemies) from a distance of one month's journey.\" (Bukhari) When Allah decides a matter, no human calculation or preparation can prevent it.",
    "And He cast horror into their hearts": "Allah Himself placed overwhelming fear and terror in their hearts. This psychological defeat was more devastating than any physical attack. Their courage melted away, their unity broke down, and their will to resist collapsed—all because Allah willed it. This demonstrates that hearts are in Allah's control; He can turn the bravest into cowards and vice versa.",
    "so they destroyed their houses with their own hands and the hands of the believers": "In an act of spite and desperation, Banu An-Nadir began demolishing their own beautiful homes so that the Muslims could not benefit from them. They removed doors, windows, and even roof beams to take with them. Meanwhile, the Muslims also demolished parts of their structures during the siege. Imagine the humiliation: destroying with your own hands what you spent years building, all because you chose to oppose Allah's Messenger.",
    "So take a lesson ˹from this˺, O people of insight!": "Allah commands those with understanding and wisdom to reflect deeply on this event. The lesson is clear: no matter how powerful, wealthy, or secure you think you are, opposing Allah and His Messenger leads to destruction. Those with true insight see beyond the surface of events and recognize Allah's hand in history. This call to reflection applies to every generation—we should look at the fate of those who opposed the truth and take warning."
  },
  3: {
    "Had Allah not decreed exile for them": "Allah, in His wisdom, chose exile as their punishment in this world. Being forced to leave their homes, lands, and possessions was a severe humiliation, but it was actually a lighter punishment than what they truly deserved for their treachery and disbelief.",
    "He would have certainly punished them in this world": "If exile had not been decreed, Allah would have destroyed them completely in this life—perhaps through killing, as happened to Banu Qurayza later when they committed similar treachery. So their exile was actually a form of mercy compared to complete annihilation. Yet even this lighter punishment was devastating enough to serve as a lesson.",
    "And in the Hereafter they will suffer the punishment of the Fire": "Their worldly punishment of exile does not excuse them from accountability in the Hereafter. Because they died upon disbelief and treachery, they will face the eternal punishment of Hell. This is a sobering reminder that worldly consequences—no matter how severe—are temporary, but the punishment of the Hereafter is permanent. The real loss is losing one's eternal soul."
  },
  4: {
    "This is because they defied Allah and His Messenger": "The root cause of their punishment is clearly stated: they opposed and showed hostility to Allah and His Messenger. The word used implies they placed themselves on one side against Allah and His Messenger on the other. They had treaties with the Muslims but broke them. They had knowledge of prophethood from their scriptures but rejected Muhammad (peace be upon him). They plotted assassination. All of this constitutes defiance of the highest order.",
    "And whoever defies Allah, then Allah is truly severe in punishment": "This is a universal warning that extends beyond Banu An-Nadir to all of humanity until the Day of Judgment. Anyone who chooses to oppose Allah and stand against His religion will face severe consequences. Allah is patient and gives chances for repentance, but when His punishment comes, it is overwhelming. History is filled with examples of nations destroyed for their defiance—Pharaoh, the people of 'Ad, Thamud, and many others."
  },
  5: {
    "Whatever palm trees you ˹believers˺ cut down or left standing intact": "During the siege of Banu An-Nadir, the Muslims cut down some of their palm trees as a military strategy to pressure them into surrender and to clear lines of sight. Some companions wondered if this was permissible since destroying crops and trees was generally discouraged in Islam. This verse came to clarify the matter. Whether the Muslims cut trees or left them standing, both actions were valid and permissible in this specific context.",
    "it was ˹all˺ by Allah's Will": "Allah Himself authorized this action. It was not random destruction or transgression—it was a divinely sanctioned military tactic for this particular situation. The Prophet (peace be upon him) would not have allowed it without Allah's permission. This teaches us that what might seem like a general rule (not destroying trees in war) can have exceptions when Allah commands otherwise for a greater purpose.",
    "so that He might disgrace the rebellious": "The purpose behind allowing the cutting of palm trees was to humiliate Banu An-Nadir. Palm trees were extremely valuable—they represented years of cultivation, wealth, and livelihood. Seeing their precious trees cut down added to their psychological defeat and disgrace. Allah wanted to demonstrate that those who rebel against Him and His Messenger will be humiliated, and even their most prized possessions will not be spared."
  },
  6: {
    "As for the gains Allah has turned over to His Messenger from them": "The word \"fay'\" (translated as gains) refers to wealth obtained from enemies without actual fighting. Unlike \"ghanimah\" (war booty) which is gained through battle, \"fay'\" comes when enemies surrender or flee without combat. The wealth of Banu An-Nadir fell into this category because they surrendered after a siege without a major battle taking place.",
    "you did not ˹even˺ spur on any horse or camel for such gains": "Allah reminds the Muslims that they did not have to charge into battle on horses or ride camels into combat to obtain this wealth. There was no cavalry charge, no major military expedition requiring mounts. The fortresses of Banu An-Nadir were close to Medina, and the siege was relatively peaceful compared to actual warfare. This fact is significant because it affects how the wealth is distributed.",
    "But Allah gives authority to His messengers over whoever He wills": "The victory and the wealth came directly from Allah's decree, not primarily from Muslim military effort. Allah empowers His messengers and grants them authority over their enemies as He pleases. This was a direct divine intervention—Allah caused fear to enter the hearts of Banu An-Nadir and made them surrender.",
    "For Allah is Most Capable of everything": "Nothing is beyond Allah's power. He can grant victory without warfare, cause the downfall of fortified enemies, and transfer wealth from one people to another. This phrase reminds believers to place their trust in Allah's infinite capability rather than in military strength alone."
  },
  7: {
    "As for gains granted by Allah to His Messenger from the people of ˹other˺ lands": "This verse establishes a general principle for distributing fay' (wealth gained without fighting) from any conquered or surrendered lands, not just Banu An-Nadir. Unlike regular war booty (ghanimah) where fighters receive four-fifths of the spoils, fay' has a different distribution because it was obtained without military effort.",
    "they are for Allah and the Messenger": "Saying the gains are \"for Allah\" means they should be spent in ways that please Him and serve His cause. The Messenger (peace be upon him) was given authority to distribute this wealth according to the needs of the Muslim community and the categories mentioned. After the Prophet's death, this portion goes to the general treasury (bayt al-mal) for public benefit.",
    "his close relatives": "This refers to the family of the Prophet (peace be upon him)—specifically Banu Hashim and Banu al-Muttalib. They were forbidden from receiving regular charity (zakah), so this provision ensured they had a source of support. The Prophet's family played a crucial role in supporting Islam and deserved recognition.",
    "orphans": "Children who have lost their fathers and have no means of support. Islam places tremendous emphasis on caring for orphans. The Prophet (peace be upon him) said: \"I and the one who sponsors an orphan will be like this in Paradise\" and he held his index and middle fingers together. (Bukhari) Including orphans in this distribution ensures the most vulnerable members of society are cared for.",
    "the poor": "Those who do not have enough to meet their basic needs. Islam aims to create a society where wealth circulates to all levels, not just among the wealthy. The poor have a right in the wealth of the community.",
    "and ˹needy˺ travellers": "People who are stranded far from home without resources, even if they may be wealthy in their homeland. Travel in ancient times was dangerous and unpredictable, and wayfarers often found themselves in desperate situations. This provision ensures hospitality and support for travelers.",
    "so that wealth may not merely circulate among your rich": "This is one of the most profound economic principles in the Quran. Allah explicitly states that the purpose of this distribution system is to prevent wealth from becoming concentrated only among the wealthy elite. Islam seeks economic justice where resources flow throughout society, reaching those in need. This stands in contrast to systems where the rich get richer while the poor get poorer. The economy should serve all people, not just the privileged few.",
    "Whatever the Messenger gives you, take it": "This is a comprehensive command to obey the Prophet (peace be upon him) in everything he commands or permits. Whether it relates to distribution of wealth, religious practices, or any aspect of life, Muslims must accept and follow the Prophet's guidance. His authority comes from Allah, so obeying him is obeying Allah.",
    "And whatever he forbids you from, leave it": "Similarly, anything the Prophet prohibited must be avoided. This verse establishes the Sunnah (the Prophet's teachings and practices) as a binding source of Islamic law alongside the Quran. We cannot pick and choose—accepting some of his guidance while rejecting others. Complete submission to his rulings is required.",
    "And fear Allah": "Be conscious of Allah in all your affairs. When receiving or distributing wealth, maintain Allah-consciousness. Do not let greed, jealousy, or selfishness corrupt your heart. Remember that Allah sees everything.",
    "Surely Allah is severe in punishment": "This warning concludes the verse to emphasize the seriousness of disobeying the Messenger or misappropriating wealth meant for the needy. Those who hoard wealth, refuse to share, or disobey the Prophet's commands will face Allah's severe punishment."
  },
  8: {
    "˹Some of the gains will be˺ for poor emigrants": "The Muhajirin (emigrants) were the early Muslims from Mecca who left everything behind to migrate to Medina for the sake of their faith. Many of them arrived in Medina with nothing—they had abandoned their homes, businesses, and possessions. They deserved special consideration in the distribution of this wealth.",
    "who were driven out of their homes and wealth": "These emigrants did not leave voluntarily for economic opportunity—they were forced out by persecution. The Quraysh of Mecca made life impossible for Muslims, torturing them, boycotting them, and eventually plotting to kill the Prophet. The emigrants sacrificed their worldly possessions for Allah's sake.",
    "seeking Allah's bounty and pleasure": "Despite losing everything materially, their motivation was purely spiritual. They sought Allah's reward and His pleasure, not worldly compensation. This is the essence of true faith—prioritizing Allah's approval over material comfort. Their sacrifice was not for personal gain but for eternal reward.",
    "and standing up for Allah and His Messenger": "They actively supported the cause of Islam. They did not just passively believe—they defended the faith, fought alongside the Prophet, and worked to establish Allah's religion. Their support was both physical (in battles and daily work) and spiritual (through steadfastness and sacrifice).",
    "They are the ones true in faith": "Allah Himself testifies to their sincerity. The word \"sadiqoon\" (truthful/sincere) is the highest commendation. Their actions matched their words; their deeds proved their faith. When someone claims to believe but refuses to sacrifice, their claim is questionable. The Muhajirin proved their faith through action, earning this divine certification of their truthfulness."
  },
  9: {
    "As for those who had settled in the city and ˹embraced˺ the faith before ˹the arrival of˺ the emigrants": "The Ansar (Helpers) were the Muslims of Medina who had accepted Islam and established it in their city before the emigrants arrived from Mecca. They had made Medina a home for faith, preparing the ground for the Muslim community to flourish. The phrase beautifully shows they \"settled in\" both the physical city and in faith itself—they were firmly rooted in both.",
    "they love whoever immigrates to them": "The Ansar had genuine, heartfelt love for the Muhajirin. This was not mere tolerance or reluctant hospitality—it was true brotherhood. When the emigrants arrived with nothing, the Ansar opened their homes, shared their wealth, and even offered to divorce one of their wives so an emigrant brother could marry her (though this was declined). This love was so remarkable that Allah recorded it in the Quran for all generations to learn from.",
    "never having a desire in their hearts for whatever ˹of the gains˺ is given to the emigrants": "When the wealth of Banu An-Nadir was distributed primarily to the poor emigrants, the Ansar felt no jealousy or resentment whatsoever. Their hearts were completely pure of envy. They understood that their emigrant brothers needed it more and were genuinely happy to see them receive support. This level of selflessness is extremely rare and represents the ideal of Islamic brotherhood.",
    "They give ˹the emigrants˺ preference over themselves even though they may be in need": "This is known as \"eethaar\"—preferring others over yourself even when you yourself need something. The Ansar would give food to emigrants while going hungry themselves. They would provide shelter while cramped in their own homes. There is a famous hadith where a companion hosted a guest but had only enough food for one. He and his wife pretended to eat in the darkness while the guest ate, going to bed hungry. The Prophet (peace be upon him) said the next morning: \"Allah was amazed (pleased) by what you did last night.\" (Bukhari) This is the height of generosity.",
    "And whoever is saved from the selfishness of their own souls, it is they who are ˹truly˺ successful": "The human soul naturally inclines toward selfishness, greed, and hoarding. This is called \"shuhh\"—an intense, stingy attachment to what one has. But those who overcome this base tendency and become generous, sharing souls achieve true success. Success here means success in both worlds—a peaceful, blessed life in this world and Paradise in the Hereafter. The Ansar demonstrated this success, and their example should inspire every believer."
  },
  10: {
    "And those who come after them will pray": "This refers to all believers who come after the Muhajirin and Ansar—every generation of Muslims until the Day of Judgment. This includes us today. Allah describes the proper attitude later generations should have toward the early companions and all believers who preceded them. This verse sets the standard for how we should view and speak about those who came before us in faith.",
    "Our Lord! Forgive us and our fellow believers who preceded us in faith": "This is a beautiful supplication that connects all generations of believers. We ask Allah to forgive us for our shortcomings and also to forgive our brothers and sisters who accepted Islam before us. This includes the companions, the scholars, the righteous of every era, and even our own parents and grandparents who were believers. Praying for those who passed away is an act of love and connection that transcends death.",
    "and do not allow bitterness into our hearts towards those who believe": "The word \"ghill\" means rancor, hatred, resentment, or bitterness. We ask Allah to keep our hearts clean toward all believers—especially the early generations including the companions. Unfortunately, some groups throughout history have harbored hatred toward certain companions. This verse teaches that true believers pray against having any such negativity in their hearts. A believer's heart should be full of love for all who believe in Allah.",
    "Our Lord! Indeed, You are Ever Gracious, Most Merciful": "The supplication ends by calling upon Allah's attributes of kindness and mercy. We acknowledge that only through His grace can our hearts be purified of resentment, and only through His mercy can we and our predecessors be forgiven. These divine names give us hope that Allah will answer this beautiful prayer."
  },
  11: {
    "Have you ˹O Prophet˺ not seen the hypocrites": "Allah draws the Prophet's attention (and ours) to the behavior of the hypocrites in Medina. These were people who outwardly claimed to be Muslims but inwardly harbored disbelief and worked against the Muslim community. The leader of the hypocrites, Abdullah ibn Ubayy ibn Salul, and his followers had secret communications with Banu An-Nadir.",
    "who say to their fellow disbelievers from the People of the Book": "Allah calls Banu An-Nadir the \"brothers\" of the hypocrites because they shared the same essence—disbelief and opposition to Islam. Despite the hypocrites' outward claim to Islam, their true loyalty was with the enemies of Islam. This is a warning that hypocrites will always secretly align with those who oppose the truth.",
    "If you are expelled, we will certainly leave with you": "The hypocrites made grand promises to Banu An-Nadir, assuring them of solidarity. They promised that if the Muslims expelled them, the hypocrites would leave Medina too in protest and join them in exile. These were empty words meant to encourage Banu An-Nadir to resist the Muslims.",
    "and We will never obey anyone against you": "They promised absolute loyalty—that they would never follow any order against Banu An-Nadir, implying they would defy the Prophet and the Muslim community for their sake. This was essentially a pledge of treachery against the Muslim state they claimed to be part of.",
    "And if you are fought against, we will surely help you": "They also promised military support, saying they would fight alongside Banu An-Nadir if the Muslims attacked them. This was meant to give Banu An-Nadir false confidence to stand firm against the Muslims.",
    "But Allah bears witness that they are truly liars": "Allah Himself testifies against the hypocrites, declaring all their promises to be lies. They had no intention of fulfilling any of these commitments. When the siege actually happened, the hypocrites did nothing—they did not leave with Banu An-Nadir, they did not fight for them, they did not support them at all. Allah knew their hearts and exposed their lies in the Quran."
  },
  12: {
    "Indeed, if they are expelled, the hypocrites will never leave with them": "Allah prophesies exactly what will happen, proving the hypocrites' lies. When Banu An-Nadir were actually expelled, not a single hypocrite went with them into exile. They stayed comfortably in Medina, abandoning those they had promised to support. Their words meant nothing.",
    "And if they are fought against, the hypocrites will never help them": "Similarly, when the Muslims besieged Banu An-Nadir, the hypocrites sent no military aid whatsoever. They hid behind their claims of Islam and did nothing. All their brave promises evaporated when action was required.",
    "And even if the hypocrites did so, they would certainly flee": "Even hypothetically, if the hypocrites had somehow gathered the courage to help, they would have fled at the first sign of real danger. Cowardice is a hallmark of hypocrisy. They lack true conviction and will never sacrifice themselves for anyone.",
    "then the disbelievers would be left with no help": "The end result would be the same: Banu An-Nadir would be abandoned and helpless. Their supposed allies would desert them, leaving them to face the consequences alone. This is the fate of those who put their trust in people who oppose Allah—ultimately, they find themselves without support."
  },
  13: {
    "Indeed, there is more fear in their hearts for you ˹believers˺ than for Allah": "Both the hypocrites and Banu An-Nadir feared the Muslims more than they feared Allah. This is a profound spiritual sickness. When someone fears creation more than the Creator, their priorities are completely inverted. They might avoid displeasing powerful people while having no concern about disobeying Allah. True faith means fearing Allah above all else.",
    "That is because they are a people who do not comprehend": "Their misplaced fear stems from a fundamental lack of understanding. If they truly understood Allah's power, knowledge, and ability to punish, they would fear Him more than any human force. But disbelief and hypocrisy cloud the mind and prevent real comprehension of spiritual realities. They see the immediate threat of Muslim swords but are blind to the far greater threat of Allah's punishment."
  },
  14: {
    "Even united, they would not ˹dare˺ fight against you except ˹from˺ within fortified strongholds or from behind walls": "Despite their numbers and resources, the hypocrites and Banu An-Nadir would never face the Muslims in open battle. They would only fight from behind fortifications and walls, showing their cowardice. True courage comes from faith, and these groups lacked genuine conviction. They relied on physical barriers because they had no spiritual strength.",
    "Their malice for each other is intense": "Outwardly, they appeared united against the Muslims, but internally they harbored intense hatred, jealousy, and rivalry among themselves. The hypocrites and Banu An-Nadir did not truly trust or like each other—they were only temporarily united by their common enemy. This internal conflict is a weakness Allah exposes.",
    "you think they are united, yet their hearts are divided": "Looking from outside, you might assume these groups are a unified force because they coordinate against Muslims. But in reality, their hearts are completely fragmented. Each group has its own agenda, its own interests, and its own suspicions about the others. Unity built on opposing truth is always fragile and will eventually collapse.",
    "That is because they are a people with no ˹real˺ understanding": "Again, Allah attributes their condition to lack of true understanding. If they had reason and wisdom, they would recognize that their coalition is weak and their cause is doomed. But disbelief impairs judgment and prevents people from seeing reality clearly."
  },
  15: {
    "They are ˹both just˺ like those who recently went down before them": "The hypocrites and Banu An-Nadir are compared to those who were recently punished before them. This likely refers to the Quraysh who were defeated at the Battle of Badr, or possibly Banu Qaynuqa (another Jewish tribe expelled from Medina earlier). History keeps repeating—those who oppose Allah and His Messenger meet the same fate.",
    "they tasted the evil consequences of their doings": "Those earlier groups experienced the bitter results of their choices in this world. Defeat, humiliation, loss of life and property—these were the immediate consequences of their opposition to Islam. The phrase \"tasted\" implies they directly experienced the bitterness of their actions.",
    "And they will suffer a painful punishment": "Beyond the worldly consequences, a painful punishment awaits them in the Hereafter. The punishment of this world, however severe, is temporary. But the punishment after death is eternal for those who die in disbelief. This comprehensive warning shows that opposing Allah brings loss in both worlds."
  },
  16: {
    "˹They are˺ like Satan when he lures someone to disbelieve": "Allah compares the hypocrites' behavior toward Banu An-Nadir to Satan's behavior toward humans. Satan constantly invites people to disbelief, sin, and disobedience. He makes evil attractive and promising. Similarly, the hypocrites encouraged Banu An-Nadir to resist the Muslims with promises of support they never intended to provide.",
    "Then after they have done so, he will say ˹on Judgment Day˺, \"I have absolutely nothing to do with you\"": "Once someone follows Satan's suggestions and commits sins or disbelief, Satan completely abandons them. He takes no responsibility whatsoever. On the Day of Judgment, Satan will openly disassociate himself from all his followers. The Quran records Satan saying: \"I had no power over you except to call you, and you responded to me. So do not blame me, but blame yourselves.\" (14:22) Similarly, the hypocrites abandoned Banu An-Nadir completely once the crisis came.",
    "I truly fear Allah—the Lord of all worlds": "In a shocking statement, Satan will claim to fear Allah and distance himself from his followers. This is the ultimate betrayal—after leading people to destruction, Satan pretends piety and abandons them to their fate. Of course, Satan's fear is not true God-consciousness that leads to obedience; it is mere acknowledgment of Allah's power when it is too late. This parable warns us not to follow those who promise support against truth, for they will abandon us just as Satan abandons his followers."
  },
  17: {
    "So they will both end up in the Fire": "Both the deceiver (Satan and, by analogy, the hypocrites) and the deceived (those who followed their call to disbelief) will share the same destination: the Hellfire. Following bad advice does not excuse someone from punishment. Each person is responsible for their choices, regardless of who influenced them.",
    "staying there forever": "The punishment is not temporary—it is eternal for those who die upon disbelief. There is no escape, no parole, no second chance after death. The permanence of Hell should terrify anyone who is tempted to follow the path of disbelief.",
    "That is the reward of the wrongdoers": "Allah calls it a \"reward\" in the sense that it is the just consequence of their actions. Those who wrong themselves and others through disbelief, hypocrisy, and leading people astray earn this terrible outcome. The word \"wrongdoers\" encompasses both the misleaders and those who chose to be misled."
  },
  18: {
    "O believers! Be mindful of Allah": "Allah addresses the believers directly with a command to maintain taqwa—conscious awareness of Allah that leads to obeying Him and avoiding His displeasure. This is the foundation of all righteousness. After showing what happened to disbelievers and hypocrites, Allah calls believers to ensure they remain on the right path.",
    "and let every soul look to what ˹deeds˺ it has sent forth for tomorrow": "\"Tomorrow\" here refers to the Day of Judgment. Each person should examine what they have prepared for that inevitable day. What good deeds have you sent ahead? What sins might you need to repent from? This is a call for daily self-accounting. Umar ibn al-Khattab said: \"Hold yourselves accountable before you are held accountable, and weigh your deeds before they are weighed for you.\" Taking time each day to reflect on our actions is essential.",
    "And fear Allah": "The command to have taqwa is repeated for emphasis. It bookends the verse, showing its supreme importance. God-consciousness should be our constant state—before action, during action, and after action.",
    "˹for˺ certainly Allah is All-Aware of what you do": "Nothing escapes Allah's knowledge. Every deed, every thought, every intention is known to Him. There are no secrets from Allah. This awareness should motivate us to be careful about all our actions, knowing they are all recorded and will be presented to us on the Day of Judgment."
  },
  19: {
    "And do not be like those who forgot Allah": "\"Forgetting Allah\" means living as if Allah does not exist or does not matter—ignoring His commands, neglecting worship, failing to remember Him in daily life. It does not mean literal memory loss but rather choosing to push Allah out of one's consciousness and priorities.",
    "so He made them forget themselves": "This is a profound consequence: when people forget Allah, He causes them to forget their own souls' welfare. They become blind to what truly benefits them. They neglect preparing for the Hereafter. They damage their own interests while thinking they are doing well. The one who forgets his Creator forgets his purpose, his destination, and his true self.",
    "It is they who are ˹truly˺ rebellious": "Allah classifies those who forget Him as \"fasiqoon\"—people who have departed from obedience and fallen into sinful rebellion. This is not a minor matter; forgetting Allah leads to a complete collapse of moral and spiritual life. Such people have abandoned the straight path entirely."
  },
  20: {
    "The residents of the Fire cannot be equal to the residents of Paradise": "Allah declares an absolute distinction between the two groups of humanity. Those destined for Hell and those destined for Paradise are fundamentally different. Their beliefs were different, their actions were different, their priorities were different, and their outcomes will be different. There is no equivalence between choosing faith and choosing disbelief.",
    "˹Only˺ the residents of Paradise will be successful": "True success is defined here: it is entering Paradise. All worldly measures of success—wealth, power, fame—are meaningless compared to this ultimate success. Someone might \"fail\" by worldly standards yet succeed eternally by entering Paradise. Conversely, the most \"successful\" person in worldly terms is an utter failure if they end up in Hell. This verse redefines success according to what truly matters."
  },
  21: {
    "Had We sent down this Quran upon a mountain": "Allah presents a hypothetical scenario to help us understand the magnitude of the Quran. Mountains are symbols of stability, firmness, and strength. They are the largest, most solid structures on earth. If the Quran were revealed to a mountain—if a mountain could understand and feel its weight—what would happen?",
    "you would have certainly seen it humbled and torn apart in awe of Allah": "The mountain would become humble and would crack and crumble from the overwhelming awe and fear of Allah generated by the Quran's message. The words, meanings, and divine presence in the Quran are so powerful that they would overwhelm even the mightiest mountain. This is a profound commentary on the Quran's weight.",
    "We set forth such comparisons for people": "Allah explains why He uses these analogies—they are teaching tools to help us grasp realities that might otherwise be beyond our comprehension. Comparisons make abstract concepts tangible and relatable.",
    "˹so˺ perhaps they may reflect": "The purpose is to make people think deeply. If mountains would crumble under the weight of the Quran, how should we—weak humans—approach it? With humility, reverence, and trembling hearts. If our hearts are harder than mountains and remain unmoved by the Quran, something is seriously wrong. This verse is a call to soften our hearts and receive the Quran as it deserves to be received."
  },
  22: {
    "He is Allah—there is no god ˹worthy of worship˺ except Him": "This is the declaration of tawheed—the absolute oneness of Allah. There is no deity, no being worthy of worship, obedience, love, or devotion except Allah alone. All other objects of worship are false. This is the foundation of Islam and the message of every prophet.",
    "Knower of the seen and unseen": "Allah's knowledge is complete and perfect. He knows everything that is visible and perceivable to creation (the seen), and He knows everything hidden from creation (the unseen). This includes the future, people's secrets, what is in the depths of oceans and the heights of heavens, what has passed and what will come. Nothing whatsoever is hidden from Him.",
    "He is the Most Compassionate, Most Merciful": "Despite His infinite knowledge of all our sins and faults, Allah is still Ar-Rahman (the Most Compassionate, whose mercy encompasses all creation) and Ar-Raheem (the Most Merciful, who shows special mercy to the believers). His mercy dominates His attributes. The Prophet (peace be upon him) said: \"When Allah created creation, He wrote above His Throne: 'My mercy prevails over My wrath.'\" (Bukhari)"
  },
  23: {
    "He is Allah—there is no god except Him": "Again, the declaration of oneness is repeated, emphasizing its centrality. Allah is introducing Himself through His beautiful names, and each introduction begins with this foundational truth.",
    "the King": "Al-Malik—Allah is the absolute King and Sovereign of all existence. All dominion belongs to Him. Human kings and rulers have limited, temporary authority, but Allah's kingship is complete, permanent, and extends over everything.",
    "the Most Holy": "Al-Quddus—Allah is completely pure and perfect, free from any deficiency, fault, or imperfection. He is holy beyond anything creation can imagine, transcendent above all limitations and weaknesses.",
    "the All-Perfect": "As-Salam—Allah is the source of peace and perfection, free from all defects. He is also the one who grants peace and safety to His creation. The greeting of Muslims, \"As-salamu alaykum,\" invokes this divine name.",
    "the Source of Serenity": "Al-Mu'min—Allah is the one who grants security and removes fear. He affirms the truth of His messengers with miracles and proofs. He is the one in whom believers place their ultimate trust and find peace.",
    "the Watcher ˹of all˺": "Al-Muhaymin—Allah watches over and preserves all creation. He is aware of everything, guards everything, and has authority over everything. Nothing escapes His vigilant care.",
    "the Almighty": "Al-Aziz—Allah possesses absolute might and honor. No one can overpower Him or resist His will. His might is combined with wisdom and justice.",
    "the Supreme in Might": "Al-Jabbar—Allah is the Compeller who mends what is broken and compels all creation to His will. He is also the one who restores and comforts the broken-hearted among His servants.",
    "the Majestic": "Al-Mutakabbir—Allah alone has the right to greatness and pride. Pride and arrogance belong only to Him, as He is truly above all creation. For any creature to be arrogant is to wrongfully claim what belongs only to Allah.",
    "Glorified is Allah far above what they associate with Him ˹in worship˺!": "Allah declares His complete transcendence above any partner, equal, or rival. Those who worship others alongside Allah or attribute partners to Him are committing the greatest injustice. Allah is infinitely beyond and above such false associations."
  },
  24: {
    "He is Allah: the Creator": "Al-Khaliq—Allah is the one who brings things into existence from nothing, who decrees and plans creation. He determines what will exist and its nature.",
    "the Inventor": "Al-Bari'—Allah originates and produces creation, bringing it into being according to His plan. He separates and distinguishes each creation from others, producing each thing uniquely.",
    "the Shaper": "Al-Musawwir—Allah fashions and forms each creation, giving it its specific shape, appearance, and characteristics. Every face, every leaf, every snowflake is shaped by Him with purpose and beauty. The progression from Khaliq to Bari' to Musawwir shows the stages of creation: planning, originating, and then shaping into final form.",
    "He ˹alone˺ has the Most Beautiful Names": "Allah's names are perfect and beautiful beyond description. The Prophet (peace be upon him) said: \"Allah has ninety-nine names—one hundred less one—and whoever counts them (understands and lives by them) will enter Paradise.\" (Bukhari and Muslim) These names reveal Allah's attributes and help us know and worship Him properly.",
    "Whatever is in the heavens and the earth ˹constantly˺ glorifies Him": "The surah ends as it began—with the universal glorification of Allah by all creation. This creates a beautiful symmetry. Everything in existence praises Allah, acknowledging His perfection and declaring His transcendence.",
    "And He is the Almighty, All-Wise": "The surah concludes with the same two names mentioned in the first verse: Al-Aziz (the Almighty) and Al-Hakeem (the All-Wise). Allah's might ensures His decrees are carried out, and His wisdom ensures they are perfect. With these attributes, the surah closes, having taken us on a journey from the expulsion of Banu An-Nadir to the contemplation of Allah's most beautiful names—showing that all events in history, all distribution of wealth, all rise and fall of nations, ultimately relate back to Allah's supreme power and perfect wisdom."
  }
};