var tafsirData_91 = {
  1: {
    "By the sun and its brightness": "Allah swears by the sun, one of His greatest creations, and its radiant morning light. The sun is a powerful sign of Allah's majesty and creative power. Just as the sun illuminates the physical world and makes everything visible, guidance from Allah illuminates the heart and makes truth clear. When Allah swears by something in the Quran, it is to draw our attention to its significance and to emphasize the importance of what follows. The brightness of the sun at mid-morning (dhuha) represents clarity, energy, and the peak of beneficial light—symbolizing how truth and guidance bring clarity to human life."
  },
  2: {
    "and the moon as it follows it": "Allah swears by the moon that follows the sun, appearing after sunset. The moon reflects the sun's light and provides gentle illumination in the darkness of night. This oath highlights the perfect harmony and order in Allah's creation—the sun and moon following a precise system that never fails. This is mentioned in Surah Ya-Sin (36:40): 'Neither is it for the sun to overtake the moon, nor does the night outrun the day. Each is traveling in an orbit of their own.' The alternation of sun and moon is a daily reminder of Allah's power and meticulous design, which should lead humans to recognize their Creator."
  },
  3: {
    "and the day as it unveils it": "Allah swears by the daytime when it reveals and exposes everything that was hidden in darkness. The day unveils the earth, showing its features, colors, and details clearly. This is a beautiful metaphor for how truth and guidance reveal reality, removing the darkness of ignorance and falsehood. Just as you cannot hide from the light of day, the truth of Allah's message exposes the reality of existence—that we are created beings accountable to our Creator. The day allows people to work, travel, and see clearly, representing the blessing of clarity and opportunity that Allah provides."
  },
  4: {
    "and the night as it conceals it": "Allah swears by the night when it covers and conceals the earth in darkness. The night wraps the world like a blanket, hiding what the day revealed. This contrast between day and night is one of Allah's greatest signs, as mentioned in Surah Al-Furqan (25:47): 'He is the One Who has made the night a cover for you, and sleep a rest.' The night provides rest and tranquility, while also representing how misguidance and corruption can cover the soul in spiritual darkness. The alternation between concealment and unveiling teaches us about the contrast between truth and falsehood, guidance and misguidance."
  },
  5: {
    "And by heaven and the One Who built it": "Allah swears by the sky and by Himself, the One who constructed it without pillars, raising it high with perfect precision. The word 'built' (bana) indicates strength, stability, and careful construction. Look at the sky—it has no cracks, no flaws, and it remains in place by Allah's command. As stated in Surah Qaf (50:6): 'Have they not looked at the sky above them—how We built it and adorned it, and it has no gaps?' This oath directs our attention to Allah's incredible power. If He can build the vast heavens with such perfection, surely He has the power to create the human soul and hold it accountable."
  },
  6: {
    "and the earth and the One Who spread it": "Allah swears by the earth and by Himself, the One who spread it out and made it suitable for life. The earth has been expanded and prepared with mountains, rivers, vegetation, and everything needed for human existence. Despite the earth being a sphere, Allah spread its surface in a way that makes it livable and walkable for humans. This is mentioned in Surah An-Nazi'at (79:30): 'And the earth, He spread it out as well.' The earth beneath our feet is a constant reminder of Allah's favor—stable ground to live upon, resources to benefit from, and beauty to appreciate. This should inspire gratitude and recognition of the Creator."
  },
  7: {
    "And by the soul and the One Who fashioned it": "Allah swears by the human soul and by Himself, the One who perfectly fashioned and proportioned it. The word 'sawwa' means to shape something with balance, harmony, and perfection. Allah created the soul with remarkable qualities—intelligence, emotions, conscience, and the capacity for both good and evil. As mentioned in Surah At-Tin (95:4): 'Indeed, We created humans in the best form.' The human soul is Allah's special creation, given abilities that other creatures do not possess. This oath emphasizes the honor Allah has given to human beings and prepares us for the crucial point about human choice that follows."
  },
  8: {
    "then with the knowledge of right and wrong inspired it": "After creating and fashioning the soul, Allah inspired within it the recognition of what is morally wrong (fujoor) and what is righteous (taqwa). Every human being has an innate sense of right and wrong—a moral compass placed by Allah. This is called the 'fitrah' (natural disposition). The Prophet Muhammad (peace be upon him) said: 'Every child is born upon the fitrah' (Sahih Muslim). This means humans naturally recognize basic morality: honesty is good, lying is bad; kindness is good, cruelty is bad. Allah did not leave humans without guidance—He built this recognition into the soul itself. This is why even people who never received a prophet still have a sense of conscience. However, this inspiration comes with responsibility: since you know right from wrong, you are accountable for your choices."
  },
  9: {
    "Successful indeed is the one who purifies their soul": "This is the answer to all the oaths that came before. After swearing by the sun, moon, day, night, heaven, earth, and soul, Allah declares the ultimate truth: true success belongs to the person who purifies and cleanses their soul. The word 'aflaha' (succeeded) in Arabic originally refers to a farmer whose crops flourish—indicating growth, prosperity, and achieving one's goal. The word 'zakka' means to purify, cleanse, and make something grow in goodness. Purifying the soul means cleansing it from sins, bad character, arrogance, envy, greed, and disobedience to Allah. It means filling the soul with faith, good deeds, remembrance of Allah, and noble character. The Prophet Muhammad (peace be upon him) used to supplicate: 'O Allah, grant my soul its taqwa and purify it, for You are the best to purify it. You are its Guardian and Master' (Sahih Muslim). This verse teaches us that real success is not about wealth, status, or worldly achievements—it is about the state of your soul before Allah."
  },
  10: {
    "and doomed is the one who corrupts it": "In contrast, the one who corrupts, buries, and degrades their soul is utterly lost and has failed. The word 'khaba' means to fail, lose, and be disappointed—the opposite of success. The word 'dassaha' comes from 'dass' which means to hide, bury, or conceal something. When a person corrupts their soul, they bury their innate goodness under layers of sin, arrogance, and disobedience. They suppress the voice of conscience that Allah placed within them. Each sin committed makes it harder to hear that inner voice of guidance. Think of a person who keeps lying—eventually, lying becomes easy and they no longer feel guilty. Their soul has become corrupted. This is a severe warning: no matter what a person achieves in this world, if they have corrupted their soul through disbelief, sin, and rejection of truth, they have truly failed. The choice is clear: purify your soul and succeed, or corrupt it and face doom."
  },
  11: {
    "Thamud rejected the truth out of arrogance": "Allah now provides a historical example of a people who corrupted their souls and faced destruction. Thamud was an ancient Arab tribe that lived in the rocky mountains of Al-Hijr (in present-day Saudi Arabia). They were given many blessings—strength, wealth, and the ability to carve impressive homes into mountains. Allah sent them the Prophet Salih (peace be upon him) to call them to worship Allah alone. But they rejected his message. The word 'taghwa' means transgression, rebellion, and arrogance. Their rejection was not due to confusion or lack of evidence—it was pure arrogance. They thought they were too powerful and too important to follow a prophet. This is an example of souls that chose corruption over purification. When arrogance fills the heart, a person cannot accept truth even when it is clear."
  },
  12: {
    "when the most wicked of them was roused to kill the she-camel": "The corruption of Thamud reached its peak when the most wretched and evil person among them was stirred up to commit a terrible crime. Allah had sent a miraculous she-camel as a sign for Thamud—it emerged from a rock by Allah's command. This camel was to have its turn drinking from the well on certain days, and Thamud would drink on other days. It was a clear test of their obedience. The 'most wicked' person refers to a man named Qudar ibn Salif, who was encouraged by others to kill the camel. He represents those who lead others in evil—people whose souls are so corrupted that they become tools for destruction. The word 'inba'atha' (was roused) shows he was incited and motivated by his evil companions, demonstrating how corrupt people encourage each other in wrongdoing."
  },
  13: {
    "But the messenger of Allah warned them, 'Do not disturb Allah's camel and her turn to drink!'": "Prophet Salih (peace be upon him) clearly warned his people not to harm the she-camel. He called it 'Allah's camel' to emphasize that it was sacred—a sign from Allah that belonged to Him and was under His protection. He also reminded them about 'her turn to drink'—the agreement that the camel would drink from the well on certain days. This warning was merciful and clear. Salih gave them every opportunity to obey and avoid destruction. He did not want them to be punished; he wanted them to be saved. This shows how prophets always deliver the message clearly and give people chances to repent. But the choice ultimately belongs to the people—they can purify their souls by obeying, or corrupt them by disobeying."
  },
  14: {
    "Still they defied him and slaughtered her": "Despite the clear warning, Thamud rejected Prophet Salih and killed the she-camel. The word 'kazzaboohu' (they denied him) shows they rejected his message and his prophethood. Then 'aqarooha' (they hamstrung/slaughtered her) describes the brutal killing of the camel. Although one man struck the fatal blow, the entire tribe shared in the guilt because they approved of it and encouraged it. This teaches us that supporting evil is the same as committing it. They chose to corrupt their souls by defying Allah's command.",
    "So their Lord crushed them for their crime, levelling all to the ground": "As a consequence of their sin, Allah sent upon them a devastating punishment. The word 'damdama' means to completely destroy with overwhelming force—a punishment that crushed them entirely. The phrase 'fasawwaha' means He leveled them to the ground—making the destroyed equal, with no distinction between rich and poor, powerful and weak. As described in Surah Al-A'raf (7:78): 'Then the earthquake seized them, and they fell lifeless in their homes.' This is the ultimate consequence of corrupting the soul: complete destruction in this world and punishment in the Hereafter. Allah gave them every chance, but they chose arrogance and wickedness."
  },
  15: {
    "He has no fear of consequences": "Allah, in His absolute power and majesty, has no fear of any consequences from His actions. When Allah punishes wrongdoers, He does not worry about anyone questioning Him, retaliating against Him, or holding Him accountable. Unlike human rulers who may fear rebellion or criticism, Allah is the Supreme Sovereign who does as He wills with perfect justice. Some scholars say this verse refers to the wicked person who killed the camel—he had no fear of the consequences of his crime. Either interpretation carries a powerful message: Allah's justice is certain and unstoppable, and the arrogant criminal who thinks he can escape accountability is deeply mistaken. This final verse serves as a warning to all who hear this surah: do not be like Thamud. Purify your soul, heed the warnings of the messengers, and do not let arrogance lead you to destruction."
  }
};