var tafsirData_104 = {
  1: {
    "Woe": "This is a severe warning of destruction, punishment, and misery. It signals that something terrible awaits the person being addressed. In the Quran, when Allah uses 'Woe,' it indicates His extreme displeasure and a promise of dire consequences. This word alone should make anyone pause and reflect on their behavior.",
    "to every backbiter, slanderer": "This refers to a person who habitually mocks, belittles, and speaks ill of others. A backbiter is someone who criticizes people behind their backs, spreading rumors and negative talk when the person is not present. A slanderer is someone who mocks people to their faces through gestures, facial expressions, eye-rolling, or hurtful words. The Prophet Muhammad (peace be upon him) explained backbiting by saying: 'Do you know what backbiting is?' The companions said, 'Allah and His Messenger know best.' He said, 'To mention your brother in a way he dislikes.' (Sahih Muslim). This verse was revealed in Mecca where some wealthy individuals would mock the early Muslims for their poverty and low social status. It teaches us that attacking someone's character, reputation, or dignity—whether openly or secretly—is a grave sin that brings Allah's wrath."
  },
  2: {
    "who amasses wealth ˹greedily˺": "This describes a person whose entire focus in life is accumulating more and more money and possessions. They gather wealth obsessively, never satisfied with what they have, always wanting more. Their love for wealth consumes them, and they become stingy, refusing to spend in the way of Allah or help those in need. This greed often leads them to look down on others who have less, which connects to the backbiting and slandering mentioned in the previous verse.",
    "and counts it ˹repeatedly˺": "This person counts their money over and over again, finding pleasure and security in the numbers. They are constantly calculating their net worth, obsessing over their bank balance, and taking pride in their growing fortune. This repetitive counting shows an unhealthy attachment to material things. Instead of using their wealth for good, they hoard it and derive their sense of identity and superiority from it. The Quran elsewhere warns: 'And you love wealth with immense love' (89:20). This obsession with counting wealth reveals a heart attached to this temporary world rather than preparing for the eternal life to come."
  },
  3: {
    "thinking that their wealth will make them immortal!": "This is the ultimate delusion—believing that money can somehow protect them from death or grant them eternal life. Such a person acts as if they will live forever, never considering that death can come at any moment. They think their wealth will shield them from all problems, including the inevitable end of life. This false sense of security makes them arrogant and careless about their actions toward others and their duties to Allah. History is filled with examples of wealthy tyrants who thought their power and riches made them invincible—Pharaoh, Qarun (Korah), and many others—yet they all perished, leaving their wealth behind. The Prophet (peace be upon him) said: 'The son of Adam says, \"My wealth, my wealth,\" but what is your wealth except what you eat and consume, what you wear and wear out, or what you give in charity and send ahead?' (Sahih Muslim). True immortality comes not from wealth but from righteous deeds."
  },
  4: {
    "Not at all!": "This is a strong rejection and refutation of their false belief. Allah is saying: 'Absolutely not! Their assumption is completely wrong!' Their wealth will not save them, protect them, or grant them immortality. This emphatic denial shatters the illusion they have built around their riches. It serves as a wake-up call that everything they relied upon will fail them when it matters most.",
    "Such a person will certainly be tossed into the Crusher": "The word 'tossed' or 'thrown' indicates humiliation and disregard—like garbage being thrown away. The same person who thought they were superior because of their wealth will be discarded like worthless trash into a place called 'the Crusher.' This name itself is terrifying—it suggests something that breaks, shatters, and pulverizes everything thrown into it. The certainty in this statement (emphasized in Arabic) leaves no room for escape. All their arrogance, all their money, all their mocking of others will lead them to this horrifying destination."
  },
  5: {
    "And what will make you realize what the Crusher is?": "This rhetorical question is used in the Quran to emphasize the magnitude and severity of something beyond human comprehension. When Allah asks 'What will make you realize?' it means this is something so immense, so terrifying, that no human imagination can fully grasp it. This style appears elsewhere in the Quran regarding the Day of Judgment, the striking calamity, and other realities of the unseen world. It creates a pause, building anticipation and commanding attention before the explanation follows. The listener or reader is meant to feel the weight of what is coming."
  },
  6: {
    "˹It is˺ Allah's kindled Fire": "The Crusher is now identified as the Fire of Hell, but not just any fire—it is attributed directly to Allah, emphasizing its unimaginable intensity and power. This is a fire that Allah Himself has ignited and prepared. The word 'kindled' means it is constantly burning, never dying down, always blazing at full intensity. Unlike worldly fires that need fuel and can be extinguished, this fire is sustained by Allah's command. The Prophet (peace be upon him) said: 'The fire that the son of Adam kindles is one-seventieth part of the Fire of Hell.' The companions said, 'By Allah, even ordinary fire is enough!' He said, 'It is sixty-nine parts more' (Sahih Bukhari). This fire is specifically prepared for those who commit the sins described earlier—mocking others and hoarding wealth arrogantly."
  },
  7: {
    "which rages over the hearts": "This fire does not merely burn the skin—it penetrates deep within, reaching the hearts. The heart is mentioned specifically because it is the center of a person's intentions, beliefs, arrogance, and evil thoughts. The backbiter and slanderer harbored hatred, jealousy, and contempt in their heart. The greedy hoarder had love of wealth and feelings of superiority in their heart. Now that very heart—the source of their sins—will be the target of this punishment. Some scholars explain that the fire will burn through the body until it reaches the heart, then the person will be restored, and the process will repeat. This is a punishment that matches the crime: they corrupted their hearts with arrogance and malice, so their hearts will face the torment."
  },
  8: {
    "It will be sealed over them": "After being thrown into this crushing, heart-penetrating fire, the exit will be completely closed and sealed. There is no escape, no way out, no hope of release. The doors of this prison will be shut tight, leaving them trapped inside forever. This sealing emphasizes the permanence and hopelessness of their situation. In this world, they thought their wealth gave them freedom and power over others. In the Hereafter, they will find themselves utterly powerless and confined. Allah describes a similar scene elsewhere: 'Indeed, it will be closed down upon them in extended columns' (90:20). The punishment is not temporary—it is an eternal sentence with no possibility of parole or escape."
  },
  9: {
    "˹tightly secured˺ with long braces": "The sealed doors are further reinforced with tall, extended pillars or columns, making the prison absolutely secure. These braces or pillars ensure that the closure is permanent and unbreakable. Some scholars explain these are columns of fire that stretch high, adding to the terror of the scene. Others say they are pillars that lock and secure the gates of Hell. Either way, the image is one of maximum security imprisonment—like being locked in a vault that can never be opened. This final verse drives home the message: the arrogant backbiters and greedy hoarders who thought they were untouchable will find themselves trapped forever in a punishment specifically designed for them. The surah ends on this powerful note of warning, urging the listener to abandon these destructive behaviors before it is too late."
  }
};