var tafsirData_81 = {
  1: {
    "When the sun is put out": "On that Day, the sun—the magnificent source of light and heat that sustains all life on earth—will be extinguished and wrapped up like a turban being folded away. This massive celestial body that rises every day without fail will lose its light completely. Imagine the terror of a world plunged into absolute darkness. The sun that humanity has relied upon since creation will simply cease to function, signaling that the laws of nature as we know them are being dismantled by Allah's command."
  },
  2: {
    "and when the stars fall down": "The countless stars scattered across the vast sky, which have guided travelers and adorned the night for millennia, will lose their light and come crashing down. These celestial bodies that seem so fixed and permanent will scatter and fall like dust. The entire cosmic order that Allah established will be undone. This imagery reminds us that everything in creation, no matter how grand or seemingly eternal, is temporary and subject to Allah's will."
  },
  3: {
    "and when the mountains are blown away": "The massive, towering mountains that seem so permanent and unshakeable will be set in motion, uprooted from their places, and blown away like dust or scattered wool. These symbols of strength and stability on earth will become weightless and insignificant. If the mightiest structures on earth cannot withstand that Day, how can any human being think they can escape accountability? This shows the absolute power of Allah over His creation."
  },
  4: {
    "and when pregnant camels are left untended": "In ancient Arabia, a pregnant camel about to give birth was considered the most prized possession—worth more than gold. Owners would never abandon such a valuable animal under any circumstance. Yet on that Day, even this most treasured wealth will be completely neglected and abandoned. People will be so overwhelmed with terror and consumed with concern for their own fate that worldly possessions, no matter how precious, will become utterly meaningless. This illustrates how material attachments will vanish in the face of the Day of Judgment."
  },
  5: {
    "and when wild beasts are gathered together": "Wild animals that normally flee from each other and from humans—predators and prey alike—will be gathered together in one place. The natural instincts of fear and aggression will be suspended. Lions and deer, wolves and sheep, will stand side by side, all overwhelmed by the terror of what is happening. Even the animal kingdom, which operates purely on instinct, will sense that something unprecedented and catastrophic is unfolding. This gathering may also indicate that animals will be assembled for justice before being returned to dust."
  },
  6: {
    "and when the seas are set on fire": "The vast oceans, which cover most of the earth and contain unimaginable depths of water, will be set ablaze with fire. Water and fire, which are opposites that cannot coexist, will merge as the seas boil over, overflow, and ignite. Some scholars explain this as the seas being filled with fire, while others say the waters will dry up and the seabeds will burn. Either way, this supernatural event defies everything we understand about nature, demonstrating that Allah controls all elements and can make them behave in ways beyond human comprehension."
  },
  7: {
    "and when the souls ˹and their bodies˺ are paired ˹once more˺": "On that Day, every soul will be reunited with its body for resurrection. The soul that departed at death will return to the same body it once inhabited, now reconstructed by Allah for judgment. Additionally, this pairing may also refer to souls being grouped with their like—the righteous with the righteous, the wicked with the wicked, believers with believers, and disbelievers with disbelievers. Each person will be gathered with those they resembled in faith and action. The Prophet (ﷺ) said: 'A person is with whom they love.' So on that Day, your companions will be determined by the choices you made in this life."
  },
  8: {
    "and when baby girls, buried alive, are asked": "In pre-Islamic Arabia, some tribes would bury their newborn daughters alive out of shame, fear of poverty, or misguided notions of honor. This horrific practice was widespread among the ignorant. On the Day of Judgment, these innocent victims will be brought forward and questioned—not as criminals, but as witnesses. Allah will ask them publicly about the crime committed against them. This verse powerfully condemns the practice and shows that Allah never forgets the oppressed. Every innocent victim will have their day of justice."
  },
  9: {
    "for what crime they were put to death": "The innocent baby girl will be asked: 'For what sin were you killed?' Of course, she committed no sin—she was a helpless infant. This rhetorical question exposes the absolute injustice of those who murdered her. The killers will stand humiliated, unable to justify their crime. This verse establishes that the taking of innocent life is among the gravest sins. It also shows Allah's care for the weak and voiceless. Islam came to abolish such barbaric practices and restore the honor and rights of women and girls that ignorant societies had stripped away."
  },
  10: {
    "and when the records ˹of deeds˺ are laid open": "Every person's complete record of deeds—every action, word, and even intention—will be spread open for examination. Nothing will be hidden or omitted. The angels who recorded everything throughout your life will present these scrolls. The righteous will receive their records in their right hands with joy, while the wicked will receive theirs in their left hands or behind their backs in shame. As Allah says elsewhere: 'And the record will be placed, and you will see the criminals fearful of what is in it, and they will say: Woe to us! What is this book that leaves nothing small or great except that it has counted it?' (18:49). Every secret will become public on that Day."
  },
  11: {
    "and when the sky is stripped away": "The magnificent sky above us, which appears so solid and protective like a canopy, will be peeled away and removed like skin being stripped from an animal. The barrier between the earthly realm and the unseen world will be torn apart. The sky that has sheltered creation since the beginning of time will be rolled up and removed from existence. This demonstrates that even the heavens themselves are created things that will come to an end when Allah decrees. Nothing in creation is permanent except Allah Himself."
  },
  12: {
    "and when the Hellfire is fiercely flared up": "The Hellfire, which already exists and burns intensely, will be stoked and intensified to its maximum fury in preparation for receiving the disbelievers and sinners. Its flames will be kindled to a level beyond imagination. The Prophet (ﷺ) said that the fire of this world is only one-seventieth of the heat of Hellfire. On that Day, it will be brought forward with seventy thousand reins, each rein held by seventy thousand angels. Its roaring and fury will cause all of creation to tremble in fear. This is the destination prepared for those who rejected Allah's guidance."
  },
  13: {
    "and when Paradise is brought near": "In contrast to the Hellfire, Paradise—the eternal garden of bliss—will be brought close to the righteous believers. It will be made visible and accessible to them, so near that they can almost see its beauty, smell its fragrances, and anticipate its rewards. This nearness represents Allah's mercy and encouragement to the believers after the terrifying events they have witnessed. While the disbelievers will see the Hellfire awaiting them, the believers will see their eternal reward brought close, filling their hearts with joy and relief after the difficulties of the Day of Judgment."
  },
  14: {
    "˹on that Day˺ each soul will know what ˹deeds˺ it has brought along": "This is the conclusion and climax of all the preceding events. After all these cosmic catastrophes unfold, every single soul—without exception—will know with absolute certainty what deeds it has brought forward for judgment. There will be no confusion, no excuses, and no denial possible. Every person will see clearly the good and evil they did, the opportunities they took and wasted, and the consequences that await them. The veil of self-deception that people maintain in this world will be completely removed. On that Day, you will face the reality of every choice you ever made."
  },
  15: {
    "I do swear by the receding stars": "Allah takes an oath by a magnificent celestial phenomenon—the stars that recede and withdraw. These are likely the planets, which appear to move backward in their orbits from the perspective of Earth (what astronomers call retrograde motion), or stars that disappear during the day when the sun rises. When Allah swears by something in His creation, it draws attention to His power and wisdom in creating it, and emphasizes the importance of what follows. This oath introduces a powerful testimony about the truth of the Quran and the integrity of the Prophet (ﷺ)."
  },
  16: {
    "which travel and hide": "These celestial bodies travel across the sky in their ordained paths, then retreat and hide from view—either setting below the horizon or becoming invisible during daylight hours. The precise movements of these stars and planets, appearing and disappearing with perfect regularity, demonstrate Allah's masterful design of the universe. Nothing in the cosmos moves randomly; everything follows the laws Allah has set. This consistent, orderly system testifies to the existence of an All-Knowing Creator and adds weight to the oath about the Quran's divine origin."
  },
  17: {
    "and the night as it falls": "Allah also swears by the night as it approaches with its darkness, covering the earth like a blanket. The coming of night is a daily sign of Allah's power—He alternates day and night with perfect precision, providing rest for His creation. The transition from light to darkness is a reminder of how Allah controls all affairs. Some scholars say this phrase could also mean 'as the night departs,' referring to the last portion of the night before dawn. Either meaning highlights the changing phases that Allah orchestrates continuously."
  },
  18: {
    "and the day as it breaks": "And Allah swears by the morning as it breathes forth with light, when the first rays of dawn spread across the horizon. The beautiful imagery describes dawn as if it were a living being taking its first breath, bringing life, light, and activity to the world. After the stillness of night, the morning comes with renewed energy and opportunity. These daily transitions—night falling and day breaking—are signs that point to Allah's existence and His complete control over creation. After these magnificent oaths, Allah presents the testimony about the Quran."
  },
  19: {
    "Indeed, this ˹Quran˺ is the Word of ˹Allah delivered by Gabriel,˺ a noble messenger-angel": "After those powerful oaths, here is what Allah is affirming: This Quran is truly a message delivered by a noble messenger—Angel Jibreel (Gabriel), peace be upon him. The Quran originates from Allah, and Jibreel is the trusted carrier who brought it down to Prophet Muhammad (ﷺ). Jibreel is described as 'noble' (kareem), meaning he possesses honor, dignity, and excellence in his position before Allah. He is the greatest of all angels, entrusted with the most important mission: delivering divine revelation to the prophets throughout history."
  },
  20: {
    "full of power, held in honour by the Lord of the Throne": "Jibreel possesses immense power and strength given to him by Allah. He is not a weak being but one of tremendous might—he was able to overturn entire cities with a single wing, as he did with the people of Prophet Lut (Lot). Furthermore, he holds a high, secure position with Allah, the Lord of the Throne. He has an established rank and honored status in the heavens. This description assures us that the one who delivered this Quran is no ordinary being, but the mightiest and most honored of angels, ensuring the message reached humanity intact and uncorrupted."
  },
  21: {
    "obeyed there ˹in heaven˺, and trustworthy": "In the heavens, Jibreel is obeyed by the other angels—he holds a position of authority and leadership among the angelic beings. When he conveys Allah's commands, the angels follow his direction. Most importantly, he is 'ameen' (trustworthy)—absolutely reliable and faithful in delivering the message exactly as Allah revealed it, without adding, removing, or altering a single letter. This trustworthiness guarantees that what Prophet Muhammad (ﷺ) received is precisely what Allah intended to reveal. The Quran's authenticity is thus secured at every stage of its transmission."
  },
  22: {
    "And your fellow man is not insane": "Here Allah directly addresses the Quraysh and refutes their false accusations against Prophet Muhammad (ﷺ). They called him crazy, possessed, or insane to dismiss his message. But Allah calls him 'your companion' (sahibukum)—someone who has lived among you his entire life. You know his character, his honesty, his wisdom. He is not a stranger! Before prophethood, they called him 'Al-Amin' (The Trustworthy) and 'As-Sadiq' (The Truthful). How can someone they trusted with their valuables and disputes suddenly be insane? This argument uses their own knowledge of him against their baseless claims."
  },
  23: {
    "And he did see that ˹angel˺ on the clear horizon": "Prophet Muhammad (ﷺ) actually saw Angel Jibreel in his true form on the clear horizon. This occurred twice—once at the beginning of revelation, when Jibreel appeared in his original form, so magnificent that he filled the entire horizon with his six hundred wings. The second time was during the Night Journey (Isra and Mi'raj). The Prophet (ﷺ) was not hallucinating or imagining things; he genuinely witnessed this noble angel with his own eyes in clear view. This was a real, verified experience that confirms the truth of his prophethood and the reality of the revelation he received."
  },
  24: {
    "and he does not withhold ˹what is revealed to him of˺ the unseen": "The Prophet (ﷺ) is not stingy or secretive about the revelation he receives. He faithfully conveys everything Allah reveals to him, hiding nothing and adding nothing. Some people might be tempted to withhold certain revelations if they were difficult or might cause opposition, but the Prophet (ﷺ) delivered every verse, including those that were personally challenging or brought him hardship. He is completely transparent and generous in sharing divine guidance. He was sent as a mercy to all of humanity, and he fulfilled that mission by openly teaching everything he received from Allah."
  },
  25: {
    "And this ˹Quran˺ is not the word of an outcast devil": "Another false claim is demolished here. Some pagans accused the Prophet (ﷺ) of receiving his message from devils or evil spirits. Allah categorically denies this: the Quran is absolutely not the speech of a devil who has been cursed and expelled from Allah's mercy. Devils call to evil, immorality, and disbelief—but the Quran calls to righteousness, justice, worship of Allah alone, and moral excellence. The content of the Quran itself proves its divine origin. Furthermore, Allah protects His revelation from any satanic interference, as He states: 'Indeed, it is We who sent down the reminder, and indeed, We will be its guardian' (15:9)."
  },
  26: {
    "So what ˹other˺ path would you take?": "This is a powerful rhetorical question directed at those who reject the Quran. After all the evidence has been presented—the trustworthy angel, the honest Prophet (ﷺ), the divine origin of the message—where else could you possibly go? What other guidance could you follow? What alternative path makes any sense? If you reject the truth that comes from the Creator of the universe, delivered by the most noble angel to the most truthful man, then what is left? This question exposes the irrationality of disbelief. There simply is no better option than following Allah's guidance. Every other path leads to misguidance and ruin."
  },
  27: {
    "Surely this ˹Quran˺ is only a reminder to the whole world": "The Quran is not limited to one tribe, one nation, or one time period—it is a reminder (dhikr) for all of creation, for all worlds, for all of humanity until the Day of Judgment. It contains guidance, warnings, and lessons for everyone. Whether you are Arab or non-Arab, rich or poor, scholar or layman, the Quran speaks to you. It reminds humans of their purpose, their Creator, their accountability, and their final destination. The Prophet (ﷺ) was sent as a mercy to all the worlds, and his message is universal and timeless. No one can claim the Quran does not apply to them."
  },
  28: {
    "to whoever of you wills to take the Straight Way": "The guidance of the Quran is available to anyone who sincerely wants to be guided and to walk the straight path leading to Allah's pleasure and Paradise. Allah does not force anyone; He presents the truth clearly and then gives people the choice. Whoever genuinely desires guidance and makes the effort to seek it will find it in the Quran. This establishes human responsibility—you cannot blame anyone else for your choices. If you want to be upright and righteous, the path is clear before you. The decision to walk upon it is yours to make."
  },
  29: {
    "But you cannot will ˹to do so˺, except by the Will of Allah, the Lord of all worlds": "This final verse brings the discussion to its profound conclusion by establishing the perfect balance between human choice and divine will. Yes, you have the ability to choose—but your will operates within the greater Will of Allah, the Lord of all worlds. He is the ultimate authority over all things. This does not negate human responsibility; rather, it reminds us that our ability to even want guidance is itself a blessing from Allah. We should humbly ask Allah to guide our hearts and enable us to choose righteousness. Nothing happens in the universe except by His permission. This verse teaches us to combine our efforts with reliance upon Allah, seeking His help in every step of our journey toward Him."
  }
};