var tafsirData_65 = {
  1: {
    "O Prophet! ˹Instruct the believers:˺ When you ˹intend to˺ divorce women, then divorce them with concern for their waiting period,": "Allah addresses the Prophet Muhammad (peace be upon him) directly, but the instruction is for all Muslim men. When a man decides to divorce his wife, he must do so at the proper time—meaning when she is in a state of purity (not menstruating) and he has not had intimate relations with her during that period of purity. This ensures the waiting period can be calculated accurately. The Prophet (peace be upon him) became upset when Ibn Umar divorced his wife while she was menstruating, and he was commanded to take her back and wait for the proper time. This shows Islam does not encourage hasty or emotionally-driven divorces but rather a thoughtful, regulated process.",
    "and count it accurately.": "The waiting period (iddah) must be carefully tracked. This is typically three menstrual cycles for women who menstruate. Counting accurately serves multiple purposes: it determines when the divorce becomes final, ensures there is no pregnancy from the marriage, and gives time for possible reconciliation. This is a practical command that protects the rights of both spouses and any potential children.",
    "And fear Allah, your Lord.": "This reminder to be conscious of Allah comes in the middle of divorce instructions, emphasizing that even in difficult emotional situations like ending a marriage, believers must remember that Allah is watching. Divorce should not become an occasion for injustice, revenge, or harm. A person who fears Allah will treat their spouse fairly even when separating from them.",
    "Do not force them out of their homes ˹during the waiting period˺, nor should they leave—": "During the waiting period, the wife has the right to remain in the marital home. The husband cannot evict her, and she should not leave on her own. This serves several purposes: it maintains her dignity, provides her with shelter and security, keeps the family structure intact for any children, and most importantly, allows proximity that might lead to reconciliation. Living together during this period often softens hearts and reminds both parties of the good in their relationship.",
    "unless they commit a blatant misconduct.": "The only exception to the wife remaining in the home is if she commits a clear, obvious sin such as adultery or severely abusive behavior. This exception protects the husband from being forced to live with someone who has violated the marriage in an extreme way. However, this must be a clear and proven misconduct, not mere suspicion or minor disagreements.",
    "These are the limits set by Allah.": "All these regulations—proper timing, counting the waiting period, not evicting the wife—are boundaries established by Allah Himself. They are not arbitrary cultural rules but divine legislation meant to protect everyone involved and ensure justice during a difficult transition.",
    "And whoever transgresses Allah's limits has truly wronged his own soul.": "When a person violates these divorce regulations—perhaps by divorcing improperly, evicting the wife, or acting unjustly—they are ultimately harming themselves. They will face consequences in this life through family breakdown and social problems, and accountability in the Hereafter. Sin always harms the sinner first and foremost.",
    "You never know, perhaps Allah will bring about a change ˹of heart˺ later.": "This beautiful ending to the verse reveals divine wisdom behind all these regulations. By requiring a waiting period, keeping the couple in the same home, and slowing down the process, Allah creates opportunities for reconciliation. Hearts can change. Anger can subside. The couple might remember their love and the good times. Many marriages have been saved during the waiting period when both parties had time to reflect. This shows that Allah's laws are not just rules but are designed with human psychology and mercy in mind."
  },
  2: {
    "Then when they have ˹almost˺ reached the end of their waiting period,": "As the waiting period nears its completion, a critical decision point arrives. The word 'almost' is significant—the decision should be made before the period fully ends, not after. This prevents the divorce from automatically becoming final while the husband is still undecided, which could lead to regret and complications.",
    "either retain them honourably": "If the husband decides to reconcile and keep the marriage, he must do so with honor, kindness, and good treatment. Taking her back cannot be done to harm her, control her, or extend her suffering. The Prophet (peace be upon him) warned against men who would take their wives back just before the waiting period ends, then divorce them again, repeating this cycle to keep them in limbo. Retaining must be with genuine intention to be a good husband.",
    "or separate from them honourably.": "If the husband decides to finalize the divorce, this too must be done with dignity and respect. There should be no insults, no spreading of her secrets, no attempts to harm her reputation, and all her rights (financial and otherwise) must be fulfilled. Islam teaches that even ending a relationship should be done with grace. The Prophet (peace be upon him) said that the best of you are those who are best to their families, and this extends to how one treats a former spouse.",
    "And call two of your reliable men to witness ˹either way˺—": "Whether reconciling or finalizing the divorce, two trustworthy Muslim men should witness the decision. This serves as official documentation, prevents future disputes about what actually happened, and adds seriousness to the process. It also protects both parties—the wife from a husband later denying he took her back, and the husband from claims about the marriage status.",
    "and ˹let the witnesses˺ bear true testimony for ˹the sake of˺ Allah.": "The witnesses must testify truthfully, remembering that they are doing so for Allah's sake, not as a favor to either party. They will be accountable to Allah for their testimony. This prevents false testimony that could harm either spouse and ensures the integrity of the process.",
    "This is enjoined on whoever has faith in Allah and the Last Day.": "These instructions about honorable treatment and truthful witnessing are directed specifically at believers. Those who truly believe in Allah and the Day of Judgment will take these commands seriously because they know they will be held accountable. This connects family law directly to faith—how you treat your spouse, even in divorce, reflects your belief in Allah.",
    "And whoever is mindful of Allah, He will make a way out for them,": "This profound promise appears in the context of divorce, one of life's most difficult situations. When a person maintains consciousness of Allah and follows His commands even during painful times, Allah promises to provide a way out of their difficulties. This 'way out' could mean reconciliation, finding peace after separation, or unexpected blessings and opportunities. The key is trusting Allah and obeying Him even when emotions are overwhelming."
  },
  3: {
    "and provide for them from sources they could never imagine.": "Continuing the promise from the previous verse, Allah assures that those who are mindful of Him will receive provision from unexpected sources. A divorced woman might worry about her financial future, and a man might fear the costs of separation. But Allah can open doors no one anticipated—a new job, an inheritance, a business opportunity, generous support from the community, or a better marriage in the future. This verse has brought comfort to countless people going through difficult transitions.",
    "And whoever puts their trust in Allah, then He ˹alone˺ is sufficient for them.": "When a person truly relies on Allah, submitting their affairs to Him while doing their best, Allah becomes enough for them. This doesn't mean being passive or not taking action, but rather doing what is required while trusting the outcome to Allah. A divorced person who trusts Allah will find inner peace even amid uncertainty, knowing that their Lord will take care of them.",
    "Certainly Allah achieves His Will.": "Whatever Allah intends will surely come to pass. No difficulty can prevent Allah's plan, and no obstacle can stop what He has decreed as good for His servants. This gives believers confidence that their current hardship is temporary and that Allah's purpose will be fulfilled.",
    "Allah has already set a destiny for everything.": "Everything has a measure and a time appointed by Allah. The marriage had its destined duration, and what comes after also has its decreed time. This understanding helps believers accept life's changes with patience, knowing that nothing is random and that Allah's wisdom encompasses all events."
  },
  4: {
    "As for your women past the age of menstruation, in case you do not know, their waiting period is three months,": "Since the standard waiting period is based on menstrual cycles (three cycles), Allah provides guidance for women who no longer menstruate due to menopause. Their waiting period is three lunar months. The phrase 'in case you do not know' shows Allah's mercy in anticipating the community's questions and providing clear answers. This ensures older women are not left in uncertainty about their status.",
    "and those who have not menstruated as well.": "This refers to women who have not yet begun menstruating or those who for medical reasons do not have regular cycles. They also observe a three-month waiting period. Islamic law considers various situations to ensure no woman is left without clear guidance regarding her waiting period after divorce.",
    "As for those who are pregnant, their waiting period ends with delivery.": "For pregnant women, the waiting period concludes when they give birth, regardless of how long or short that time may be. If a woman is divorced and gives birth the next day, her waiting period is complete. If she is in early pregnancy, her waiting period extends until delivery. This ruling serves the important purpose of clearly establishing the parentage of the child and ensuring the father's responsibilities are defined.",
    "And whoever is mindful of Allah, He will make their matters easy for them.": "This reassurance appears again, emphasizing that those who follow Allah's commands regarding divorce and waiting periods will find ease in their affairs. Following divine guidance, even when it seems difficult, ultimately leads to simplicity and resolution. Those who try to circumvent Allah's laws often create more complications for themselves."
  },
  5: {
    "This is the commandment of Allah, which He has revealed to you.": "Allah reminds the believers that these divorce regulations are not human inventions or cultural traditions, but divine commandments revealed from above. This elevates the status of these laws and makes following them an act of worship and obedience to Allah, not merely social compliance.",
    "And whoever is mindful of Allah, He will absolve them of their sins": "Those who remain conscious of Allah and follow His commands will have their sins erased. Going through divorce with patience, fairness, and adherence to Islamic guidelines becomes a means of purification. Difficulties endured with faith and obedience wipe away sins, so even painful experiences like divorce can become spiritually beneficial when handled correctly.",
    "and reward them immensely.": "Beyond just erasing sins, Allah promises great reward for those who are mindful of Him during difficult times. The person who treats their spouse fairly during divorce, who fulfills all rights, who maintains patience and trust in Allah, will receive abundant reward. This transforms what could be merely a painful experience into an opportunity for immense spiritual gain."
  },
  6: {
    "Let them live where you live ˹during their waiting period˺, according to your means.": "The divorced wife must be provided housing during her waiting period in a manner similar to how the husband lives, within his financial capacity. A wealthy man should provide comfortable accommodation, while a man of modest means provides what he can reasonably afford. The key is that she should not be degraded or placed in substandard conditions to pressure her.",
    "And do not harass them to make their stay unbearable.": "This direct prohibition addresses a harmful practice where some men would make life so difficult for their divorced wives that the women would leave the home on their own, thereby forfeiting their rights. Such harassment—whether through insults, neglect, bringing in another wife to create conflict, or other means—is forbidden. Islam closes this loophole for abuse and ensures the woman's waiting period is spent in dignity.",
    "If they are pregnant, then maintain them until they deliver.": "Pregnant divorced women have extended rights to financial support (nafaqah) throughout their pregnancy. The husband must provide for her food, clothing, housing, and medical needs until the child is born. The child she carries is his, and he is responsible for both mother and child during this period. This continues even after the standard waiting period would have ended for a non-pregnant woman.",
    "And if they nurse your child, compensate them,": "After divorce, if the mother chooses to breastfeed the child, the father must pay her for this service. This is remarkable—she is being compensated for nursing her own child because after divorce, she is no longer obligated to do so without payment. This ruling honors the mother's work and sacrifice, ensures the child receives the best nutrition (mother's milk), and maintains the mother's financial independence.",
    "and consult together courteously.": "Even after divorce, when it comes to matters concerning their children, the former spouses must communicate with respect and work together for the child's best interests. Divorce ends the marriage but does not end the co-parenting relationship. Islam encourages cooperation and civil discussion, not ongoing conflict that harms the children.",
    "But if you fail to reach an agreement, then another woman will nurse ˹the child˺ for the father.": "If the parents cannot agree on breastfeeding arrangements—perhaps the mother demands excessive payment, or the father refuses to pay fairly—then the father may hire another woman to nurse the child. This provides a practical solution and prevents the child from being caught in parental disputes. However, this should be a last resort, as mother's milk and the mother-child bond are best for the baby."
  },
  7: {
    "Let the man of wealth provide according to his means.": "A wealthy man is expected to provide generously for his divorced wife and children. His wealth comes with greater responsibility. He cannot claim poverty to avoid his obligations when Allah has blessed him with abundance. The level of support should reflect his actual financial status.",
    "As for the one with limited resources, let him provide according to whatever Allah has given him.": "A man of modest means is only required to provide what he can reasonably afford. Islam does not burden people beyond their capacity. If a man is genuinely poor, he provides according to his situation. This balanced approach ensures women's rights are protected while not crushing men with impossible demands.",
    "Allah does not require of any soul beyond what He has given it.": "This is a foundational principle in Islamic law: no one is burdened beyond their capacity. If a man truly cannot afford more, he is not sinful for providing less, as long as he gives what he can. This principle applies to all of life's obligations—Allah's demands never exceed what He has enabled a person to do. This gives comfort to those struggling financially while still emphasizing the obligation to provide what is possible.",
    "After hardship, Allah will bring about ease.": "This promise concludes the financial discussion with hope. Those going through the hardship of divorce—with its emotional pain and financial strain—are assured that ease will come. This is a repeated Quranic promise (also found in Surah Ash-Sharh 94:5-6). The current difficulty is temporary. Better times are ahead for those who remain patient and faithful. Many people have experienced this promise firsthand—difficult divorces eventually giving way to better circumstances, new marriages, or simply peace and stability."
  },
  8: {
    "˹Imagine˺ how many societies rebelled against the commandments of their Lord and His messengers,": "After discussing family laws, Allah shifts to a powerful warning. Throughout history, many cities, nations, and civilizations arrogantly rejected Allah's commands delivered by His messengers. They thought they knew better, or they simply preferred their desires over divine guidance. The people of Noah, the people of Lot, Pharaoh's nation, and many others chose rebellion over obedience.",
    "so We called each ˹society˺ to a severe account": "These rebellious societies were not ignored. Allah held them strictly accountable for their rejection of guidance. Just as individuals will be questioned on the Day of Judgment, entire societies faced divine reckoning in this world. Their arrogance and disobedience were precisely recorded and fully addressed.",
    "and subjected them to a horrible punishment.": "The punishment was severe and unprecedented—floods, earthquakes, storms, complete destruction. The ruins of these civilizations remain as signs for later generations. This serves as a warning: Allah's laws, including those about family and divorce discussed earlier in this surah, are not optional suggestions. Societies that systematically reject divine guidance face consequences."
  },
  9: {
    "So they tasted the evil consequences of their doings,": "These nations experienced the bitter results of their own choices. The word 'tasted' implies a direct, undeniable experience—they could not ignore or escape the consequences. Their rebellion, which seemed enjoyable and liberating at first, turned into a source of destruction and regret.",
    "and the outcome of their doings was ˹total˺ loss.": "The final result of their rebellion was complete loss—loss of their wealth, their power, their civilization, and most importantly, their opportunity for salvation. They gained nothing from rejecting Allah's guidance and lost everything. This stands as a timeless lesson: defying Allah never leads to success, no matter how prosperous the defiant appear temporarily."
  },
  10: {
    "Allah has ˹also˺ prepared for them a severe punishment.": "Beyond the worldly destruction they experienced, these rebellious nations also face punishment in the Hereafter. Their suffering did not end with death; a severe punishment awaits them on the Day of Judgment. This emphasizes that escaping consequences in this world does not mean escaping divine justice.",
    "So fear Allah, O people of reason and faith.": "After describing the fate of past nations, Allah addresses the believers directly. Those who possess intelligence and faith should take this lesson to heart. The stories of destroyed nations are not entertainment but warnings. People of reason will connect the dots: if Allah punished entire civilizations for rejecting His guidance, individuals who do the same should expect similar accountability.",
    "Allah has indeed revealed to you a Reminder,": "The Quran is described here as a 'reminder'—it reminds humans of their purpose, their Lord, and their accountability. Allah has blessed this community with clear guidance, unlike those who may claim ignorance. Having received this reminder, believers have both a privilege and a responsibility to follow it, including the family laws discussed earlier in this surah."
  },
  11: {
    "˹and sent˺ a messenger reciting to you Allah's revelations, making things clear": "Along with the Quran, Allah sent Prophet Muhammad (peace be upon him) to recite and explain the divine verses. The Quran is not meant to be confusing; the Prophet's role was to make everything clear through his words, actions, and explanations. This is why the Sunnah (prophetic tradition) is essential for understanding the Quran properly. The divorce laws discussed earlier, for example, are explained in detail through the Prophet's teachings and practical examples.",
    "so that He may bring those who believe and do good out of darkness and into light.": "The purpose of revelation and the messenger is transformation—taking people from the darkness of ignorance, misguidance, injustice, and despair into the light of knowledge, guidance, justice, and hope. Before Islam, Arabs had oppressive practices regarding women and divorce. The guidance in this surah brought them into the light of fair treatment and clear rights. This journey from darkness to light continues for everyone who sincerely embraces faith and righteous action.",
    "And whoever believes in Allah and does good will be admitted by Him into Gardens under which rivers flow,": "The ultimate reward for faith and good deeds is Paradise—beautiful gardens with rivers flowing beneath them. This imagery represents the most perfect existence: beauty, peace, abundance, and joy beyond imagination. The connection between belief and action is emphasized; faith must be accompanied by righteous deeds, including following the family laws and ethical guidelines of Islam.",
    "to stay there for ever and ever.": "Unlike worldly pleasures that fade and end, Paradise is eternal. The believers will never be asked to leave, never face death again, and never experience the decline that affects everything in this world. This permanence is part of what makes Paradise the ultimate success—complete security forever.",
    "Allah will have indeed granted them an excellent provision.": "Allah describes the reward of Paradise as the best provision. Throughout this surah, provision (rizq) has been mentioned in the context of divorce, maintenance, and financial support. Here, Allah promises that those who follow His guidance will receive the ultimate provision—not just sustenance for a few years but eternal blessings in the most perfect form. Whatever difficulties believers face in this world, including the hardships of divorce, pale in comparison to this excellent provision awaiting them."
  },
  12: {
    "Allah is the One Who created seven heavens ˹in layers˺,": "The surah concludes by directing attention to Allah's magnificent creation. The seven heavens, layered one above another, demonstrate Allah's power and the vastness of His creation. When we look up at the sky, we see only the nearest heaven; beyond it are six more, each grander than the one before. This cosmic perspective reminds believers that the One who created such immensity certainly has the wisdom to guide human affairs, including marriage and divorce.",
    "and likewise for the earth.": "Just as there are seven heavens, there are also layers or realms of the earth. Whether this refers to literal layers beneath the surface or multiple earth-like realms, it demonstrates the completeness and balance of Allah's creation. The One who designed such complexity surely knows what is best for human relationships and society.",
    "The ˹divine˺ command descends between them": "Allah's commands, decrees, and management of affairs flow throughout His creation—from the highest heaven to the earth and everything in between. This includes the revelation of the Quran, the descent of angels, the sending of provisions, and the execution of divine decrees. Nothing in the universe operates without Allah's command and control.",
    "so you may know that Allah is Most Capable of everything": "The purpose of reflecting on creation is to gain certainty in Allah's power. The One who created and sustains the seven heavens and earths can certainly fulfill His promises, provide for the divorced woman, bring ease after hardship, and execute justice on the Day of Judgment. No problem in your life is too big for Allah, and no promise from Him will fail. This knowledge should give believers confidence to trust Allah's guidance in all matters, including the challenging situations of divorce and family difficulties.",
    "and that Allah certainly encompasses all things in ˹His˺ knowledge.": "Finally, the surah ends with the assurance of Allah's complete knowledge. Nothing escapes His awareness—not the private struggles of a divorced woman, not the injustice done behind closed doors, not the sincere efforts to follow His commands. He knows every detail of every situation. This knowledge means He will judge with perfect justice and reward with perfect accuracy. For the believer following the guidance of this surah, this is tremendously comforting: Allah sees their struggles, knows their circumstances, and will never let their efforts go to waste."
  }
};