var tafsirData_103 = {
  1: {
    "By the ˹passage of˺ time!": "Allah takes an oath by time itself—the ages, the hours, the moments that pass by relentlessly. When Allah swears by something in the Quran, it highlights its immense importance and draws our attention to reflect upon it. Time is one of the most precious resources given to every human being. It is constantly passing, never returning, and every moment that goes by is a moment closer to our meeting with Allah. This oath serves as a wake-up call: Are you paying attention to how you spend your time? The Prophet Muhammad ﷺ said: \"There are two blessings that many people are deceived into losing: health and free time\" (Sahih al-Bukhari). Just as a merchant who wastes his capital ends up bankrupt, a person who wastes their time ends up in loss. Think of time like ice melting in your hands on a hot day—if you don't use it wisely, it simply disappears."
  },
  2: {
    "Surely humanity is in ˹grave˺ loss": "This is a powerful declaration that all of mankind—without exception—is in a state of loss, failure, and ruin. The word 'surely' (inna) emphasizes certainty, and 'grave loss' indicates not just any loss, but a deep, devastating loss. What kind of loss is this? It is the loss of one's purpose, one's time, one's eternal destiny. Every day that passes without fulfilling our purpose brings us closer to this loss. Imagine a businessman who has a shop full of valuable goods, but instead of selling them profitably, he watches them rot and decay—that is the state of a person who wastes their life without faith and good deeds. This verse establishes a universal rule: by default, every human being is heading toward loss. The next verse will tell us who is exempted from this loss."
  },
  3: {
    "except those who have faith": "The first condition to escape loss is having true faith (iman). This means believing in Allah, His angels, His books, His messengers, the Day of Judgment, and divine destiny—both good and bad. But faith is not merely a claim on the tongue; it must settle deep in the heart and manifest in actions. True faith transforms a person's worldview, priorities, and behavior. A person with faith sees this life as a test and prepares for the eternal life ahead. Without this foundation of faith, nothing else a person does will save them from ultimate loss. It is like building a house without a foundation—no matter how beautiful it looks, it will eventually collapse.",
    "do good": "The second condition is performing righteous deeds (amal salih). Faith alone, without action, is incomplete. Allah consistently pairs faith with good deeds throughout the Quran because beliefs must translate into behavior. Good deeds include prayers, charity, kindness to parents, honesty in dealings, helping the needy, and every action done sincerely for Allah's pleasure. The Prophet ﷺ said: \"The most beloved deeds to Allah are those done consistently, even if they are small\" (Sahih al-Bukhari). A person who claims to believe but does not pray, does not give charity, and does not act righteously is like someone who claims to be a doctor but never treats patients—the claim is meaningless without practice.",
    "and urge each other to the truth": "The third condition is mutual encouragement toward truth (tawasi bil-haqq). Islam is not an individualistic religion where you only worry about yourself. Believers are part of a community, and they have a responsibility to remind, advise, and encourage one another toward what is true and right. Truth here includes correct beliefs, justice, honesty, and following Allah's guidance. This means gently correcting someone when they make a mistake, teaching those who don't know, and standing firm on principles even when it's unpopular. The Prophet ﷺ said: \"Religion is sincere advice\" (Sahih Muslim). Just as a good friend would stop you from walking off a cliff, believers stop each other from walking toward spiritual destruction.",
    "and urge each other to perseverance": "The fourth condition is mutual encouragement toward patience and steadfastness (tawasi bis-sabr). Following the truth is not easy—it comes with challenges, hardships, and opposition. People may mock you, temptations will arise, and life will test you with difficulties. That is why believers need to support each other in remaining patient and steadfast. Patience here includes patience in obeying Allah, patience in avoiding sins, and patience during trials and hardships. When one believer feels weak, another strengthens them. When one is about to give up, another reminds them of Allah's promise. This creates a supportive community where everyone helps each other reach Paradise. Imam Shafi'i said: \"If Allah had only revealed this surah as a proof for His creation, it would have been sufficient for them.\" This short surah contains the complete formula for success in this life and the next."
  }
};