var tafsirData_111 = {
  1: {
    "May the hands of Abu Lahab perish": "This is a declaration of utter ruin and loss upon Abu Lahab, whose real name was Abd al-Uzza ibn Abd al-Muttalib, an uncle of the Prophet Muhammad (ﷺ). The mention of 'hands' refers to all his efforts, actions, and schemes against Islam and the Prophet (ﷺ). Everything he worked for with his hands—his plots, his wealth-gathering, his opposition—will come to nothing. When the Prophet (ﷺ) first called his family to Islam on Mount Safa, Abu Lahab responded by saying, 'May you perish! Is this why you gathered us?' So Allah responded with this verse, turning his own curse back upon him. This shows that those who oppose Allah's message and His Messenger will ultimately be the ones who are destroyed.",
    "and he ˹himself˺ perish": "This confirms that not only will his efforts and actions fail, but Abu Lahab himself will be utterly ruined and lost. The repetition emphasizes the completeness of his destruction—both his deeds and his own self are condemned. This came true when Abu Lahab died shortly after the Battle of Badr from a contagious disease called al-Adasah (a type of plague), and his own family members were afraid to approach his body. He was left for days until his corpse began to rot, and eventually servants were hired to throw stones over him from a distance to bury him. His end was humiliating, just as this verse promised."
  },
  2: {
    "Neither his wealth": "Abu Lahab was one of the wealthiest men in Quraysh. He took great pride in his riches and used his financial power to oppose the Prophet (ﷺ). Yet all his money could not save him from Allah's decree. Wealth, no matter how abundant, cannot protect a person from divine punishment or grant them salvation. This is a powerful reminder that material possessions have no value when it comes to one's ultimate fate. The Prophet (ﷺ) said: 'Wealth is not in having many possessions, but true wealth is the richness of the soul.' (Sahih al-Bukhari). Abu Lahab's wealth gave him arrogance but brought him no benefit in the end.",
    "nor ˹worldly˺ gains will benefit him": "This refers to everything Abu Lahab earned or acquired throughout his life—his children, his status, his business profits, his influence among the Quraysh. Some scholars say 'what he earned' also refers to his children, as Arabs would say children are what a man earns. Indeed, his own sons eventually accepted Islam, showing that even his family legacy did not remain in his control. All the worldly gains he accumulated were useless in protecting him from Allah's punishment. This teaches us that on the Day of Judgment, nothing will help a person except their faith and good deeds. As Allah says elsewhere: 'The Day when neither wealth nor children will benefit anyone, except one who comes to Allah with a sound heart.' (Quran 26:88-89)"
  },
  3: {
    "He will burn in a flaming Fire": "This verse announces the certain future punishment awaiting Abu Lahab—he will enter and burn in a fire that has intense, blazing flames. There is a profound connection here: his nickname was 'Abu Lahab' (Father of Flames) because of his reddish, glowing complexion which the Arabs considered handsome. He was proud of this nickname. Yet Allah decreed that the very thing he was named after—flames—would become his eternal punishment. The fire he will burn in is described as 'dhat lahab' (possessing flames), matching his own title. This is divine justice and a form of poetic retribution. What he was proud of in this world becomes his torment in the next. This verse also serves as a prophecy: it was revealed while Abu Lahab was still alive, declaring that he would die as a disbeliever. Had he accepted Islam even outwardly, he could have challenged the Quran's truthfulness. But he never did, proving the Quran's divine origin. He remained in disbelief until his miserable death, exactly as Allah foretold."
  },
  4: {
    "and ˹so will˺ his wife": "Abu Lahab's wife, Umm Jamil bint Harb (also known as Arwa), was the sister of Abu Sufyan. She was equally hostile to the Prophet (ﷺ) and actively participated in persecuting him. She would walk alongside her husband in their campaign against Islam. In the Hereafter, she will share his fate and burn alongside him in the Hellfire. This shows that each person is accountable for their own actions. She was not condemned simply because of her husband, but because of her own evil deeds against the Prophet (ﷺ) and Islam. Spouses who partner in wrongdoing will also partner in punishment. This is similar to how Pharaoh's wife Asiyah was saved despite her husband's evil, while Noah's wife was condemned despite her husband's righteousness. What matters is one's own faith and actions.",
    "the carrier of ˹thorny˺ kindling": "This description has both a literal and metaphorical meaning. Literally, Umm Jamil used to gather thorny branches and wood and place them in the path where the Prophet (ﷺ) would walk, intending to harm his blessed feet. She did this at night out of her intense hatred. Metaphorically, 'carrying firewood' in Arabic idiom also means spreading slander, gossip, and causing conflict between people—like someone who carries fuel to ignite fires of dispute. Umm Jamil was known for spreading rumors and lies about the Prophet (ﷺ), going from house to house to turn people against him. So she carried 'firewood' in both senses: physical thorns to hurt him and verbal poison to harm his reputation. In the Hereafter, the firewood she carried in this world becomes the fuel for her own punishment."
  },
  5: {
    "around her neck will be a rope of palm-fibre": "In this world, Umm Jamil was a wealthy, proud woman who wore expensive jewelry and precious necklaces around her neck. She even once boasted about a valuable necklace she owned, saying she would sell it to spend against Muhammad (ﷺ). Yet in the Hereafter, instead of pearls and gold, she will have a rough, coarse rope made of palm-fiber twisted around her neck. Some scholars say this rope will be made of iron chains in Hellfire, and it is called 'masad' to emphasize its coarseness and the pain it will cause. The image is one of utter humiliation: from a noblewoman adorned with jewels to a prisoner in Hell with a rough rope like that used on animals. Another interpretation is that this rope connects her to the firewood she carries, making her like a beast of burden in Hell, forever carrying fuel for the fire. This is the ultimate reversal of her worldly status and pride. The same neck she adorned with precious jewelry will be bound with the rope of her own punishment. It teaches us that worldly status and beauty mean nothing before Allah if not accompanied by faith and righteous deeds."
  }
};