var tafsirData_85 = {
  1: {
    "By the sky full of constellations": "Allah takes an oath by the magnificent sky that contains the great constellations—the stars arranged in distinct patterns and formations. This oath draws attention to the vastness and beauty of Allah's creation. When you look up at the night sky and see the stars arranged in their positions, you witness a sign of Allah's supreme power and precise design. The Arabs were familiar with the constellations and used them for navigation, so this oath connected with something they deeply understood and respected. When Allah swears by something, it is to emphasize the great importance of what comes next."
  },
  2: {
    "and the promised Day ˹of Judgment˺": "Allah also swears by the Day of Judgment—the Day that has been promised and will certainly come. This is the Day when all of creation will stand before Allah to be held accountable for their deeds. It is called 'the promised Day' because Allah has promised it repeatedly through His messengers, and Allah never breaks His promise. Just as the constellations remain fixed in their positions by Allah's command, the Day of Judgment is fixed in Allah's decree and will arrive at its appointed time. This oath reassures the believers who are being persecuted that justice will come."
  },
  3: {
    "and the witness and what is witnessed": "Allah swears by the witness and the witnessed. Scholars have given several interpretations: the witness could refer to Friday (the day Muslims gather to witness the prayer), and the witnessed could be the Day of Arafah when pilgrims gather. Others say the witness is the Prophet Muhammad ﷺ who will testify about his nation, and the witnessed refers to the Day of Judgment itself. It could also mean that Allah witnesses everything, and all of creation—including our deeds—are what is witnessed. The broader meaning is that nothing escapes Allah's knowledge; every action, every injustice, and every act of faith is witnessed and recorded."
  },
  4: {
    "Condemned are the makers of the ditch": "Allah pronounces a curse and condemnation upon those who made the ditch (or trench). This refers to a historical event where tyrants persecuted believers by digging a large trench. The phrase 'condemned are' (literally 'killed are' or 'cursed are') is an expression of severe divine anger against those who harmed innocent believers. This story, as narrated in authentic hadith by the Prophet ﷺ, tells of a tyrannical king who tried to force believers to abandon their faith. When they refused, he ordered trenches to be dug, filled with fire, and had the believers thrown in. This verse serves as a warning to all oppressors throughout history that they will face Allah's wrath."
  },
  5: {
    "the fire ˹pit˺, filled with fuel": "This describes the horrific nature of the ditch—it was a pit filled with blazing fire, stoked with abundant fuel to keep it burning intensely. The persecutors prepared this fire meticulously to torture and kill the believers. The image is deeply disturbing: a fire so intense and well-fueled that it would consume anyone thrown into it. This detail emphasizes the cruelty and premeditation of the oppressors. They did not act in a moment of anger; they planned and prepared this method of execution. The irony that Allah highlights is that these people who burned believers in fire will themselves be burned in the Fire of Hell—a fire far more severe and eternal."
  },
  6: {
    "when they sat around it": "The oppressors sat around the fire pit, watching the scene of their crime. This adds another layer to their evil—they were not just giving orders from afar; they sat and observed the believers being burned alive. They watched as a form of entertainment or to ensure their commands were carried out. This behavior shows the hardness of their hearts and the depth of their cruelty. They felt no shame, no mercy, and no guilt. Instead, they sat comfortably witnessing the torture. This detail is mentioned to show that on the Day of Judgment, Allah will likewise witness their punishment, and they will have no escape from His justice."
  },
  7: {
    "watching what they had ˹ordered to be˺ done to the believers": "They were witnesses to their own crime against the believers. They saw with their own eyes what was being done to innocent people whose only 'crime' was their faith in Allah. This verse emphasizes their full awareness and intentionality—they cannot claim ignorance on the Day of Judgment. They witnessed the suffering they caused and felt no remorse. In Islamic understanding, being a witness to an act and approving of it makes one complicit in that act. These oppressors will be held accountable not only for ordering the persecution but also for witnessing it with satisfaction. Their own witnessing will testify against them before Allah."
  },
  8: {
    "who they resented for no reason other than belief in Allah": "The only reason these believers were tortured and killed was because they believed in Allah. They had committed no crime, harmed no one, and done nothing wrong. Their 'offense' in the eyes of the tyrants was simply their faith. This is the purest form of religious persecution—punishing people solely for their beliefs. This verse exposes the irrationality and evil of such persecution. The believers were not rebels or criminals; they were peaceful people who chose to worship Allah alone.",
    "the Almighty, the Praiseworthy": "Allah describes Himself with two powerful names: Al-Aziz (the Almighty, the One with supreme power and honor) and Al-Hamid (the Praiseworthy, the One deserving of all praise). The tyrants thought they had power, but true power belongs only to Allah. The believers were praising the One who is truly worthy of praise, while the tyrants were fighting against the Creator of the heavens and earth. This description reminds us that despite temporary persecution, ultimate victory belongs to Allah and those who believe in Him."
  },
  9: {
    "˹the One˺ to Whom belongs the kingdom of the heavens and earth": "Allah is the true King and Owner of everything in the heavens and the earth. Those petty tyrants who thought they owned their small kingdoms and had absolute power were deluded. They controlled nothing compared to Allah, who owns all of existence. Every king, emperor, and ruler is merely a temporary custodian of a tiny portion of Allah's vast dominion. The believers understood this truth—that is why they refused to submit to the tyrants and instead submitted only to the true King.",
    "And Allah is a Witness over all things": "Allah sees and knows everything. Nothing is hidden from Him. He witnessed what the tyrants did to the believers, and He will bring them to account. This phrase provides comfort to the oppressed: even if no human witness survives to testify, Allah Himself is the Witness. The tyrants may have thought they could burn the evidence and silence the victims, but Allah recorded everything. On the Day of Judgment, He will bring forth every detail of what happened."
  },
  10: {
    "Those who persecute the believing men and women": "Allah addresses those who put believers—both men and women—through trials, torture, and persecution because of their faith. The Arabic word 'fatanu' includes the meaning of testing through fire, torture, and any form of persecution. This applies not only to the people of the ditch but to all persecutors throughout history who harm believers for their faith. The specific mention of both men and women shows that the persecution targeted everyone, and Allah's warning applies to those who harm any believer.",
    "and then do not repent": "Allah, in His infinite mercy, still leaves the door of repentance open even for such terrible criminals. If they sincerely repent and turn back to Allah, seeking His forgiveness, they can be forgiven. This shows the vastness of Allah's mercy—even those who burned believers alive can be forgiven if they truly repent before death. However, this also serves as a warning: if they do not repent, there is no escape from punishment.",
    "will certainly suffer the punishment of Hell and the torment of burning": "Those who persecuted believers and did not repent will face two punishments: the general punishment of Hell and specifically the torment of burning. This is divine justice—they burned believers in this world, so they will be burned in the Hereafter. But the fire of Hell is incomparably more severe than any worldly fire. The Prophet ﷺ said that the fire of this world is one-seventieth part of the fire of Hell. The punishment fits the crime, but its intensity is multiplied beyond imagination."
  },
  11: {
    "Surely those who believe and do good": "This verse pivots to the beautiful reward awaiting the believers. Those who have faith in their hearts and demonstrate that faith through righteous actions will be rewarded. Belief and good deeds are mentioned together because true faith must be accompanied by action. The believers who were thrown into the fire pit had both: they believed in Allah so firmly that they accepted death rather than disbelief, and their steadfastness was itself a righteous deed of the highest order.",
    "will have Gardens under which rivers flow": "Their reward is Paradise—gardens of unimaginable beauty with rivers flowing beneath them. While the tyrants burned them with fire, Allah will grant them gardens with cooling rivers. The contrast is powerful: temporary fire in this world versus eternal gardens in the Hereafter. The rivers of Paradise, as mentioned in other verses, include rivers of water, milk, honey, and pure wine. This is the eternal home prepared for those who remained faithful despite persecution.",
    "That is the greatest triumph": "This is the true success—not worldly power, wealth, or escaping persecution in this life, but achieving Allah's pleasure and entering Paradise. The tyrants may have thought they triumphed by killing the believers, but in reality, the believers achieved the greatest victory. They traded a few moments of pain in this world for eternal bliss. The Prophet ﷺ said that a person from the people of Paradise will be dipped once in Paradise and asked, 'Did you ever experience any hardship?' and he will say, 'No, I never experienced any hardship.' This is the perspective believers should have."
  },
  12: {
    "Indeed, the ˹crushing˺ grip of your Lord is severe": "Allah warns that when He seizes wrongdoers in punishment, His grip is severe and inescapable. The word 'batsh' refers to seizing with overwhelming force. The tyrants thought they were powerful, but Allah's power is infinitely greater. When Allah decides to punish a nation or individual, nothing can protect them. The Prophet ﷺ said: 'Allah gives respite to the wrongdoer, but when He seizes him, He does not let him escape.' Then he recited this verse. This serves as a warning to all oppressors: you may escape human justice, but you cannot escape Allah's grip."
  },
  13: {
    "˹For˺ He is certainly the One Who originates and resurrects ˹all˺": "Allah is the One who creates everything from nothing and then brings it back to life after death. He originated all of creation, and He will resurrect everyone for judgment. Those who died in the fire pit—their bodies reduced to ashes—will be brought back to life by Allah. And those who burned them will also be resurrected to face justice. This attribute of Allah should fill oppressors with fear: death is not an escape. Allah will bring everyone back, and the scores will be settled."
  },
  14: {
    "And He is the All-Forgiving, All-Loving": "Despite His severe grip on wrongdoers, Allah is also the Most Forgiving and the Most Loving. These attributes are mentioned together to show the perfect balance in Allah's nature. He forgives those who repent and loves those who turn to Him. The name Al-Wadud (the All-Loving) indicates not just that Allah loves, but that He is the source of all love and affection. He loves His righteous servants with a pure and perfect love. For the believers who suffered, this is comforting—Allah loves them. For the persecutors, this is an invitation to repent and seek that love and forgiveness before it is too late."
  },
  15: {
    "Lord of the Throne, the All-Glorious": "Allah is the Lord of the Throne, which is the greatest of all created things, encompassing the heavens and the earth. The Throne represents Allah's sovereignty and majesty over all creation. He is Al-Majid—the All-Glorious, full of honor, nobility, and greatness. Earthly kings sit on thrones to display their authority, but their thrones are nothing compared to the Throne of Allah. The tyrants who sat around the fire pit, feeling powerful, were nothing before the Lord of the Throne. His glory is perfect and eternal, while their power was temporary and illusory."
  },
  16: {
    "Doer of whatever He wills": "Allah does whatever He wills, and nothing can prevent Him or question Him. When He decides something, it happens. This attribute distinguishes Allah from all created beings. Humans may want to do something but face obstacles; Allah faces no obstacles. He willed to reward the believers with Paradise—it will happen. He willed to punish the oppressors—it will happen. This verse should give believers confidence: if Allah wills to protect and honor you, no one can prevent it. And it should terrify oppressors: if Allah wills to punish you, no one can save you."
  },
  17: {
    "Has the story of the ˹destroyed˺ forces reached you ˹O Prophet˺": "Allah asks the Prophet ﷺ a rhetorical question to draw attention to an important lesson from history. The word 'junud' (forces/armies) refers to powerful nations and armies that opposed Allah's messengers. They had military might, wealth, and numbers, yet they were destroyed. This question is meant to make the listener think: if you have heard these stories, have you learned from them? The Quraysh, who were persecuting the early Muslims, should have taken heed from these historical examples."
  },
  18: {
    "˹the forces of˺ Pharaoh and Thamûd": "Allah mentions two famous examples of destroyed nations. Pharaoh was the powerful ruler of Egypt who claimed divinity and persecuted the Children of Israel. Despite his massive army and kingdom, he was drowned in the sea when he pursued Prophet Musa (Moses). Thamud was an ancient Arab nation blessed with the ability to carve homes into mountains. They rejected Prophet Salih and killed the she-camel that was a sign from Allah, so they were destroyed by a terrible blast. Both had power that seemed unshakeable, yet both were utterly destroyed. The message to the Quraysh was clear: you are not more powerful than Pharaoh or Thamud."
  },
  19: {
    "Yet the disbelievers ˹still˺ persist in denial": "Despite knowing these stories and the clear evidence before them, the disbelievers continue to deny the truth. The word 'takdhib' means persistent denial and rejection. They heard about Pharaoh's drowning and Thamud's destruction, yet they refused to learn the lesson. This is the nature of stubborn disbelief—even clear proofs do not penetrate hearts that are sealed. They saw the same patterns repeating: a messenger comes with truth, people reject him, and destruction follows. Yet they continued the same path, thinking they would somehow be different."
  },
  20: {
    "But Allah encompasses them from all sides": "While the disbelievers think they are in control, Allah surrounds them completely. They cannot escape His knowledge, His power, or His decree. The image is of someone completely encircled with no way out. They may feel safe in their denial, but Allah's knowledge encompasses their every thought and action, and His power can seize them at any moment. Pharaoh thought he was in control until the sea closed over him. The Quraysh thought they were secure in Makkah until Allah's decree reached them. No one can escape Allah's encompassing power."
  },
  21: {
    "In fact, this is a glorious Quran": "After all the warnings and lessons, Allah affirms the nature of this Book. It is a Quran—a recitation—that is Majid (glorious, noble, and full of honor). The Quran is not poetry, magic, or human invention as the disbelievers claimed. It is glorious in its source (from Allah), glorious in its content (guidance for humanity), and glorious in its effects (transforming hearts and societies). Every verse, every word carries weight and significance. The disbelievers' denial does not diminish its glory; rather, their denial only harms themselves."
  },
  22: {
    "˹recorded˺ in a Preserved Tablet": "The Quran is recorded in Al-Lawh Al-Mahfuz—the Preserved Tablet. This is a tablet in the heavens where Allah has written everything that will occur in creation, and where the Quran is preserved in its original, perfect form. This means the Quran is protected from any alteration, corruption, or loss. Previous scriptures were changed by human hands, but Allah has guaranteed the preservation of the Quran. It was preserved in the Tablet before it was revealed, and it remains preserved on earth through the hearts of those who memorize it and through written copies. This is Allah's promise: 'Indeed, it is We who sent down the reminder, and indeed, We will be its guardian' (15:9). The Quran you read today is exactly what was revealed to Prophet Muhammad ﷺ over 1400 years ago."
  }
};