var tafsirData_28 = {
  1: {
    "Ṭâ-Sĩn-Mĩm": "These are disconnected Arabic letters (Huroof Muqatta'at) that appear at the beginning of some chapters of the Quran. Their exact meaning is known only to Allah. Scholars say they serve to capture attention and demonstrate the miraculous nature of the Quran—that despite being composed of the same letters Arabs used daily, no one could produce anything like it. They remind us that the Quran contains mysteries and depths of knowledge beyond human comprehension."
  },
  2: {
    "These are the verses of the clear Book": "This refers to the Quran itself—a Book that makes everything clear. It clarifies truth from falsehood, guidance from misguidance, and lawful from unlawful. The word 'clear' (Mubeen) indicates that its message is plain, evident, and leaves no room for confusion for those who sincerely seek the truth. Unlike obscure texts, the Quran speaks directly to the heart and mind of every reader."
  },
  3: {
    "We narrate to you ˹O Prophet˺ part of the story of Moses and Pharaoh": "Allah is informing Prophet Muhammad (peace be upon him) that He will reveal portions of the historical account of Prophet Moses (Musa) and the tyrannical ruler Pharaoh. This story was not known to the Prophet before revelation—he had no access to previous scriptures—yet Allah revealed it to him with perfect accuracy, proving the divine origin of the Quran.",
    "in truth": "This narrative is absolutely true and accurate, free from the distortions and alterations found in other sources. Unlike myths or legends, this is the authentic account as it actually happened, coming directly from Allah who witnessed and controlled all events.",
    "for people who believe": "The primary beneficiaries of this story are the believers—those whose hearts are open to accepting truth and learning lessons. While the story is available to all, only those with faith will truly benefit from its profound lessons about patience, trust in Allah, and the ultimate defeat of tyranny."
  },
  4: {
    "Indeed, Pharaoh ˹arrogantly˺ elevated himself in the land": "Pharaoh was not just a political ruler—he claimed divinity and absolute power. He said to his people, 'I am your most exalted lord' (Quran 79:24). His arrogance made him believe he was above everyone and everything, answerable to no one. This is the ultimate corruption of power: when a human being, who is himself created and dependent, claims the status of God.",
    "and divided its people into ˹subservient˺ groups": "Pharaoh used the classic strategy of tyrants throughout history: 'divide and conquer.' He split Egyptian society into different classes and groups, playing them against each other to maintain control. Some groups were privileged while others were marginalized. This division prevented unity and made it easier for him to rule unopposed. This tactic is still used by oppressors today—creating divisions based on race, tribe, class, or religion to maintain power.",
    "one of which he persecuted, slaughtering their sons and keeping their women": "The Children of Israel (Bani Israel) were specifically targeted for brutal persecution. Pharaoh ordered the killing of all newborn boys among them while keeping the girls alive. The boys were killed to prevent any male from growing up to challenge his rule (some say because of a prophecy that an Israelite would end his kingdom), while the women were kept alive to serve as slaves and servants. This was systematic genocide and enslavement of an entire people.",
    "He was truly one of the corruptors": "Pharaoh was not merely a political tyrant—he was a corruptor of the entire land. He spread corruption in beliefs (by claiming to be god), in governance (through oppression), in society (through division and injustice), and in morality (through murder and enslavement). The Arabic word 'Mufsideen' (corruptors) indicates those who cause widespread destruction and ruin wherever they have influence."
  },
  5: {
    "But it was Our Will to favour those who were oppressed in the land": "While Pharaoh was busy with his schemes of oppression, Allah had His own plan. Allah intended to show special favor and mercy to the very people Pharaoh sought to destroy. This is a powerful message of hope: no matter how dark the situation appears, Allah's plan is always in motion. The oppressed should never despair, and the oppressor should never feel secure in their tyranny.",
    "making them models ˹of faith˺ as well as successors": "Allah's plan was to transform the oppressed Israelites into leaders (Imams) whom others would follow in faith and righteousness. They would become examples for humanity. Additionally, they would inherit authority and leadership—the very thing Pharaoh feared and tried to prevent. This shows that Allah's decree cannot be stopped by human plotting. The Prophet Muhammad (peace be upon him) and the early Muslims found great comfort in this story, as they too were oppressed in Mecca before eventually becoming leaders."
  },
  6: {
    "and to establish them in the land": "Allah planned to give the Children of Israel firm establishment, security, and power in the land. They would have their own homeland where they could practice their faith freely and live with dignity. This was the complete opposite of their current state of slavery and humiliation.",
    "and through them show Pharaoh, Hamân, and their soldiers ˹the fulfilment of˺ what they feared": "Hamân was Pharaoh's chief minister or vizier—his right-hand man in implementing tyranny. Together with their armies, they feared that an Israelite would rise to overthrow their power. Ironically, all their efforts to prevent this—killing babies, enslaving people—would prove futile. Allah would bring about exactly what they feared, through the very people they oppressed. This is divine justice: the oppressor's worst nightmare comes true through the hands of those they wronged."
  },
  7: {
    "We inspired the mother of Moses": "Allah placed a strong inspiration (ilham) in the heart of Moses' mother. This was not prophethood but a special divine guidance that gave her certainty about what to do. Sometimes Allah guides His servants through such inner inspiration, giving them peace and clarity in the most difficult circumstances.",
    "Nurse him, but when you fear for him, put him then into the river": "She was instructed to breastfeed her baby normally at first. But when the danger of Pharaoh's soldiers discovering him became imminent, she should place him in a basket and set it floating in the Nile River. Logically, this seems dangerous—how could throwing a baby into a river save him? But this was a test of her faith and trust in Allah. Sometimes Allah's commands seem counterintuitive, but obedience brings miraculous results.",
    "and do not fear or grieve": "Allah comforted her heart with two prohibitions: do not fear (about what might happen in the future) and do not grieve (about being separated from your child). Fear and grief are natural human emotions, especially for a mother, but Allah was reassuring her that He was in complete control.",
    "We will certainly return him to you, and make him one of the messengers": "This is Allah's promise—and Allah never breaks His promises. Not only would her baby be safe, but he would be returned to her. And there was an even greater honor: this child would grow up to become one of the greatest prophets and messengers in human history. What mother could have imagined such a destiny for her child while hiding him from murderous soldiers?"
  },
  8: {
    "And ˹it so happened that˺ Pharaoh's people picked him up": "The basket carrying baby Moses floated down the Nile and was discovered by members of Pharaoh's own household. The very family that was killing Israelite babies ended up rescuing one and bringing him into their palace. This is the beautiful irony of Allah's plan—He used the enemy's own hands to protect His chosen one.",
    "only to become their enemy and source of grief": "Allah reveals the ultimate outcome from the very beginning. They picked him up, but little did they know that this baby would grow up to be the instrument of their downfall. The one they raised in their palace would become their greatest enemy and the cause of their destruction. All their killing of babies was to prevent this, yet the very child they feared was nurtured in their own home.",
    "Surely Pharaoh, Hamân, and their soldiers were sinful": "Their sin was multifold: they killed innocent babies, enslaved a people, spread corruption, and claimed divine authority. Their sinfulness blinded them to Allah's plan unfolding right before their eyes. Sin creates spiritual blindness—the more one persists in wrongdoing, the less they can perceive the truth."
  },
  9: {
    "Pharaoh's wife said ˹to him˺, \"˹This baby is˺ a source of joy for me and you": "Pharaoh's wife, known in Islamic tradition as Asiyah, immediately felt love for this beautiful baby. She saw him as a blessing, a 'coolness of the eyes'—an Arabic expression meaning something that brings immense joy and comfort. Asiyah is mentioned by the Prophet (peace be upon him) as one of the greatest women in history. Her heart was pure despite being married to the worst tyrant.",
    "Do not kill him": "She pleaded with Pharaoh to spare this baby's life. This was risky—she was asking the man who ordered the death of all Israelite baby boys to make an exception. But Allah had placed love for Moses in her heart and gave her courage to speak.",
    "Perhaps he may be useful to us or we may adopt him as a son": "She gave practical reasons to convince Pharaoh: the child might grow up to be useful to them, or they could raise him as their own son since they may not have had children of their own. Little did she know how 'useful' he would be—but not in the way she imagined.",
    "They were unaware ˹of what was to come˺": "Neither Pharaoh, nor Asiyah, nor anyone in the palace knew that this baby would grow up to be the prophet who would challenge Pharaoh, demand the freedom of the Israelites, and ultimately cause the destruction of Pharaoh and his army. Allah's plan was hidden from them completely."
  },
  10: {
    "And the heart of Moses' mother ached so much that she almost gave away his identity": "After putting her baby in the river, Moses' mother was overwhelmed with worry and grief. Her heart became 'empty'—meaning empty of everything except thoughts of her son. The anxiety was so intense that she nearly exposed the secret and revealed that the baby in Pharaoh's palace was hers. This would have been catastrophic, potentially leading to both their deaths.",
    "had We not reassured her heart": "Allah intervened by strengthening her heart and giving her patience. He tied her heart firmly to faith and trust in His promise. This is how Allah helps His servants in moments of extreme difficulty—by sending tranquility (sakeenah) to their hearts.",
    "in order for her to have faith ˹in Allah's promise˺": "The purpose of this divine support was to maintain her faith. Allah had promised to return Moses to her and make him a messenger. She needed to hold onto that promise despite everything her emotions were telling her. Faith sometimes means trusting Allah's promise even when circumstances seem impossible."
  },
  11: {
    "And she said to his sister, \"Keep track of him!\"": "Moses' mother sent his older sister to follow the basket and find out what happened to the baby. This was both a practical step and a mother's desperate need to know her child's fate. It shows that trusting in Allah does not mean being passive—we should still take reasonable actions while relying on Allah for results.",
    "So she watched him from a distance, while they were unaware": "The sister skillfully observed from afar, careful not to draw attention to herself or reveal any connection to the baby. She watched as he was taken into the palace, keeping track of everything without anyone suspecting her. This required great composure and intelligence from a young girl."
  },
  12: {
    "And We had caused him to refuse all wet-nurses at first": "Baby Moses would not accept milk from any Egyptian wet-nurse they brought. He refused to feed, which caused great concern in the palace. This was not natural—it was Allah's divine intervention. Allah 'prohibited' the wet-nurses upon him, making it impossible for the baby to accept anyone except his own mother. This shows how Allah controls even the most basic instincts when He wills.",
    "so his sister suggested, \"Shall I direct you to a family who will bring him up for you and take good care of him?\"": "Seeing the opportunity, Moses' sister approached the palace servants with a solution. She cleverly offered to find a woman who could nurse the baby successfully. Notice her wisdom: she didn't say 'I know his mother' or show any personal connection. She simply presented herself as someone who could help solve their problem. Her composure and quick thinking were remarkable."
  },
  13: {
    "This is how We returned him to his mother": "Allah fulfilled His promise exactly as He said He would. Moses was returned to his own mother, who was now officially hired as his wet-nurse. Not only was she reunited with her son, but she was also paid to nurse her own child! The baby she had cast into the river in fear was now legally in her care, protected by Pharaoh's own household.",
    "so that her heart would be put at ease, and not grieve": "Her eyes were cooled and her heart was comforted. The grief and anxiety she had experienced were now replaced with joy and relief. This shows Allah's kindness to His servants—He doesn't just deliver them from hardship, He also heals their hearts.",
    "and that she would know that Allah's promise is ˹always˺ true": "This experience strengthened her faith through lived experience. She now knew with certainty that when Allah makes a promise, it will absolutely come true, no matter how impossible it seems. Her faith moved from belief to conviction through witnessing Allah's plan unfold.",
    "But most people do not know": "Most people are unaware of how Allah's plans work. They see only the surface of events, not the divine wisdom behind them. They don't understand that Allah's promises are certain and that He is always in control, even when situations appear hopeless."
  },
  14: {
    "And when he reached full strength and maturity": "Moses grew up in Pharaoh's palace, receiving the best education and training available in Egypt. He reached physical maturity (full strength) and mental maturity (sound judgment). This period of growth prepared him for the enormous mission ahead. Scholars say 'full strength' refers to around 30-40 years of age when a person reaches complete physical and intellectual maturity.",
    "We gave him wisdom and knowledge": "Allah blessed Moses with special wisdom (the ability to make sound judgments and understand deep truths) and knowledge (understanding of religion, law, and life). This was divine preparation for prophethood. True wisdom and beneficial knowledge are gifts from Allah, granted to those He chooses.",
    "This is how We reward the good-doers": "This statement establishes a universal principle: those who do good (Muhsineen—those who excel in faith and righteousness) are rewarded by Allah with wisdom, knowledge, and guidance. Moses was righteous in his character, and Allah rewarded him accordingly. This encourages all believers to strive for excellence in their conduct, knowing that Allah rewards the good-doers in ways beyond their imagination."
  },
  15: {
    "˹One day˺ he entered the city unnoticed by its people": "Moses entered the city during a time when people were resting or inattentive—perhaps during the midday heat or siesta time. He was not seeking trouble; he simply happened to enter at a quiet moment when few people were around to notice him.",
    "There he found two men fighting: one of his own people, and the other of his enemies": "Moses came upon a conflict between an Israelite (one of his own people, whom he identified with despite being raised in the palace) and an Egyptian (from the oppressing class). This situation immediately presented him with a moral dilemma.",
    "The man from his people called to him for help against his foe": "The Israelite, recognizing Moses, called out for his assistance against the Egyptian who was attacking him. Moses, seeing injustice and feeling solidarity with his oppressed people, decided to intervene.",
    "So Moses punched him, causing his death": "Moses struck the Egyptian with his fist, intending only to stop the aggression—not to kill. But Moses was strong, and the blow proved fatal. This was unintentional; Moses did not plan or desire to kill anyone. It was a defensive action that had tragic consequences.",
    "Moses cried, \"This is from Satan's handiwork": "Moses immediately recognized that the situation that led to this killing was orchestrated by Satan. While Moses' intention was to help the oppressed, Satan had maneuvered the circumstances to lead to this terrible outcome. Satan uses our good intentions and leads us into situations we never planned.",
    "He is certainly a sworn, misleading enemy\"": "Moses acknowledged Satan's true nature: an enemy who has sworn to mislead humanity, and who clearly leads people astray from the right path. This is an important lesson—Satan doesn't always tempt us with obvious evil; sometimes he uses our emotions and good intentions to lead us to harmful outcomes."
  },
  16: {
    "He pleaded, \"My Lord! I have definitely wronged my soul, so forgive me.\"": "Moses immediately turned to Allah in sincere repentance. He acknowledged his mistake honestly, saying 'I have wronged myself.' He didn't make excuses or blame others—he took responsibility and sought Allah's forgiveness. This is the model of true repentance: immediate acknowledgment of sin and turning to Allah.",
    "So He forgave him": "Allah accepted Moses' repentance and forgave him. The forgiveness was immediate and complete. This shows Allah's mercy—when a servant sincerely repents, Allah forgives, regardless of the severity of the mistake.",
    "˹for˺ He is indeed the All-Forgiving, Most Merciful": "Allah's names Al-Ghafoor (the All-Forgiving) and Ar-Raheem (the Most Merciful) are mentioned together to emphasize that forgiveness is part of Allah's essential nature. He loves to forgive, and His mercy encompasses everything. No sin is too great for Allah to forgive when repentance is sincere."
  },
  17: {
    "Moses pledged, \"My Lord! For all Your favours upon me, I will never side with the wicked\"": "After receiving forgiveness, Moses made a commitment to Allah. Recognizing all the blessings Allah had given him—saving him as a baby, raising him in the palace, and now forgiving his sin—Moses vowed never to support or assist wrongdoers and criminals. This was not just regret but a transformation in behavior. True repentance leads to a change in how we live. Moses promised to be careful about whom he helps and never to lend support to evil, even unintentionally."
  },
  18: {
    "And so Moses became fearful, watching out in the city": "The morning after the incident, Moses was in a state of anxiety and vigilance. He feared that the killing might have been discovered and that he could be arrested and executed. He moved cautiously through the city, constantly looking around for any sign of danger. This was a natural human reaction—even prophets experience fear.",
    "when suddenly the one who sought his help the day before cried out to him again for help": "Incredibly, the same Israelite man who had called Moses for help the previous day was now in another fight and again calling for Moses' assistance. This was either extreme bad luck or this man had a habit of getting into conflicts.",
    "Moses rebuked him, \"Indeed, you are clearly a trouble-maker\"": "Moses was frustrated and rebuked the man. He recognized a pattern—this Israelite was someone who frequently caused problems and got into disputes. Moses was already in danger because of helping him yesterday, and now he was in trouble again. Moses' words show his exasperation: 'You are clearly someone who goes astray and causes trouble.'"
  },
  19: {
    "Then when Moses was about to lay his hands on their foe": "Despite his frustration, Moses was still about to help by confronting the Egyptian aggressor. He moved toward the enemy to intervene, perhaps to restrain him or stop the fight.",
    "the enemy said, \"O Moses! Do you intend to kill me as you killed a man yesterday?": "The Egyptian, seeing Moses approaching aggressively, revealed that he knew about yesterday's killing. This was a shocking revelation—the secret was out. Either the Israelite had told someone, or word had spread. Now Moses' crime was publicly known, and he was exposed.",
    "You only want to be a tyrant in the land": "The Egyptian accused Moses of wanting to be a violent oppressor—someone who kills people at will. This was an ironic accusation, given that Pharaoh was the real tyrant. But the accusation was dangerous because it could turn public opinion against Moses.",
    "You do not intend to make peace!\"": "The Egyptian claimed Moses was not interested in justice or reconciliation—only in violence. This accusation painted Moses as a dangerous criminal rather than someone defending the oppressed. The situation had completely turned against Moses."
  },
  20: {
    "And there came a man, rushing from the farthest end of the city": "Allah sent help through an unexpected source. A man came running urgently from the far side of the city to warn Moses. This man had somehow learned of the plot against Moses and risked himself to deliver a warning. Allah always provides ways out for His servants, sometimes through people we don't expect.",
    "He said, \"O Moses! The chiefs are actually conspiring against you to put you to death": "The warning was clear and urgent: the elite leaders of Egypt were meeting and plotting to have Moses killed. This was not just a rumor—it was an active conspiracy at the highest levels of government. Moses' life was in immediate danger.",
    "so leave ˹the city˺. I really advise you ˹to do so˺\"": "The man gave sincere advice (naseeha): Moses must leave immediately. There was no time for delay or planning. This advice came from genuine concern for Moses' wellbeing. In times of danger, sometimes the wisest action is to leave and live to serve Allah another day."
  },
  21: {
    "So Moses left the city in a state of fear and caution": "Moses heeded the warning and immediately fled Egypt. He left in a state of fear, constantly looking around for pursuers. He was leaving behind everything he knew—the palace, his family, his entire life. He had no plan, no provisions, and no clear destination. He was a fugitive running for his life.",
    "praying, \"My Lord! Deliver me from the wrongdoing people\"": "Even in this desperate situation, Moses turned to Allah in prayer. He asked for salvation and protection from the oppressive people who sought to kill him. This shows the believer's response to crisis: turn to Allah first. Moses didn't complain or despair—he prayed with trust that Allah would save him."
  },
  22: {
    "And as he made his way towards Midian": "Moses headed toward Midian, a region located across the Sinai Peninsula, probably because it was outside Egyptian territory and thus beyond Pharaoh's immediate reach. The journey was long and dangerous—crossing desert wilderness with no supplies.",
    "he said, \"I trust my Lord will guide me to the right way\"": "Despite having no map, no guide, and no experience of travel, Moses expressed complete trust in Allah. He believed that Allah would guide him to the correct path—both physically to safety and spiritually to what was best for him. This statement shows beautiful reliance on Allah (tawakkul). Moses had lost everything worldly, but his faith remained strong. He knew that as long as Allah was guiding him, he would reach where he needed to be."
  },
  23: {
    "When he arrived at the well of Midian, he found a group of people watering ˹their herds˺": "After a long, exhausting journey through the desert, Moses finally reached Midian and came upon a well. This was a gathering place where shepherds brought their animals to drink. Moses saw a crowd of men busy watering their flocks.",
    "Apart from them, he noticed two women holding back ˹their herd˺": "Standing apart from the men, Moses noticed two women keeping their animals away from the well. They were waiting rather than joining in the watering. This immediately caught Moses' attention as unusual—why weren't they watering their animals like everyone else?",
    "He asked ˹them˺, \"What is the problem?\"": "Despite being a tired stranger, Moses showed concern for others. He approached the women and politely inquired about their situation. This shows his noble character—even in his own difficulty, he noticed others who might need help.",
    "They replied, \"We cannot water ˹our animals˺ until the ˹other˺ shepherds are done": "The women explained their predicament: being female, they couldn't compete with the crowd of male shepherds at the well. They had to wait until all the men finished before they could approach. This meant they were always last and at a disadvantage.",
    "for our father is a very old man\"": "They explained why they were doing this work at all—their father was elderly and couldn't do it himself. They had no brothers or other male relatives to help, so they had to take on this difficult task themselves. Their modest explanation revealed a family in need."
  },
  24: {
    "So he watered ˹their herd˺ for them": "Without hesitation, Moses stepped forward and watered their animals for them. He used his strength to help these strangers, pushing through the crowd to get water for their flock. He asked for nothing in return—it was pure generosity and chivalry.",
    "then withdrew to the shade": "After helping them, Moses didn't linger or try to start a conversation with the women. He respectfully withdrew to sit in the shade of a tree. This shows his modesty and propriety—he helped without any ulterior motive and maintained appropriate boundaries.",
    "and prayed, \"My Lord! I am truly in ˹desperate˺ need of whatever provision You may have in store for me\"": "Sitting alone in the shade, Moses prayed to Allah. He was exhausted, hungry, homeless, and a fugitive. He had nothing. He expressed his complete need and dependence on Allah, asking for any good that Allah might send his way. This is one of the most beautiful prayers in the Quran—short, humble, and completely trusting. Moses didn't specify what he needed; he simply acknowledged his poverty and trusted Allah to provide whatever was best."
  },
  25: {
    "Then one of the two women came to him, walking bashfully": "Shortly after Moses' prayer, one of the women returned—but not boldly or casually. She walked with modesty and shyness (haya), her demeanor showing her good character and upbringing. This description highlights the virtue of modesty, which is praised in Islam for both men and women.",
    "She said, \"My father is inviting you so he may reward you for watering ˹our animals˺ for us\"": "She conveyed her father's invitation with brevity and clarity—no unnecessary conversation, just the message. Her father wanted to thank Moses properly for his kindness. This invitation was the answer to Moses' prayer, coming almost immediately.",
    "When Moses came to him and told him his whole story": "Moses went to meet the old man (identified in Islamic tradition as Prophet Shu'ayb, though the Quran doesn't name him). Moses told him everything—his background, the killing, his escape from Egypt, and his current situation as a fugitive with nothing.",
    "the old man said, \"Have no fear! You are ˹now˺ safe from the wrongdoing people\"": "The old man reassured Moses with comforting words. Moses was now in a different land, outside Pharaoh's jurisdiction. The oppressors could not reach him here. This statement must have brought immense relief to Moses' worried heart."
  },
  26: {
    "One of the two daughters suggested, \"O my dear father! Hire him\"": "One of the daughters spoke up with a suggestion. She addressed her father respectfully and recommended that he employ Moses. This would solve their family's need for help with the herds while also providing Moses with work and stability.",
    "The best man for employment is definitely the strong and trustworthy ˹one˺\"": "She gave the reason for her recommendation: Moses possessed two essential qualities for a good worker—strength (qawi) and trustworthiness (ameen). She had witnessed his strength when he watered their animals. She had observed his trustworthiness when he helped them without expecting anything and withdrew modestly afterward. These two qualities—capability and integrity—are what any employer should look for. The daughter's wisdom in recognizing these traits is noteworthy."
  },
  27: {
    "The old man proposed, \"I wish to marry one of these two daughters of mine to you": "The old man made an extraordinary offer. He wanted Moses to marry one of his daughters. This was not just hospitality—it was an offer of family, belonging, and a new start in life. For Moses, who had lost everything, this was beyond what he could have imagined.",
    "provided that you stay in my service for eight years": "The condition was that Moses would work for him for eight years. This would be Moses' mahr (dowry) for the marriage—his service in lieu of payment. This arrangement gave Moses meaningful work and purpose while honoring the marriage with a proper commitment.",
    "If you complete ten, it will be ˹a favour˺ from you": "The old man added flexibility: if Moses chose to work for ten years instead of eight, that would be voluntary generosity on Moses' part, not a requirement. This showed the old man's fairness—he didn't want to burden Moses.",
    "but I do not wish to make it difficult for you": "He explicitly stated his intention not to impose hardship. He wanted the arrangement to be fair and comfortable for Moses. This reflects excellent character in business dealings—clarity, fairness, and consideration for the other party.",
    "Allah willing, you will find me an agreeable man\"": "The old man concluded with humility, saying 'In sha Allah' (Allah willing), acknowledging that only Allah knows the future. He promised to be a good, fair, and righteous person in their dealings. This phrase shows his reliance on Allah and his commitment to good conduct."
  },
  28: {
    "Moses responded, \"˹Then˺ it is ˹settled˺ between you and I": "Moses accepted the proposal. He agreed to the terms of the arrangement—marriage and service. This sealed the agreement between them. What started as a simple act of kindness at a well had now led to Moses finding a wife, a family, employment, and safety.",
    "Whichever term I fulfill, there will be no ˹further˺ obligation on me": "Moses clarified the terms: whether he completed eight years or ten, once done, there would be no additional demands or claims against him. This shows the importance of clear agreements—both parties understood exactly what was expected.",
    "And Allah is a Witness to what we say\"": "Moses concluded by invoking Allah as the witness to their agreement. This elevates a business contract to a sacred covenant. When Allah is made witness, both parties are reminded of their accountability to Him. This is the Islamic way of conducting agreements—with honesty, clarity, and consciousness of Allah's observation."
  },
  29: {
    "When Moses had completed the term": "Moses fulfilled his commitment to his father-in-law, completing the agreed period of service. According to hadith, Moses completed the full ten years, choosing the longer term out of his noble character. This shows Moses' integrity—he honored his word completely.",
    "and was travelling with his family": "After completing his service, Moses decided to return to Egypt with his wife. Perhaps he felt a longing for his homeland, or perhaps Allah placed this inclination in his heart as part of the divine plan. They set out on the long journey through the desert.",
    "he spotted a fire on the side of Mount Ṭûr": "During the journey, likely on a cold, dark night, Moses noticed a fire burning on the mountainside. Mount Ṭûr (also known as Mount Sinai) would become one of the most significant locations in religious history—the place where Allah spoke directly to Moses.",
    "He said to his family, \"Stay here, ˹for˺ I have spotted a fire\"": "Moses instructed his family to wait while he investigated. He was being a responsible leader of his family, going ahead to check the situation rather than leading them into unknown circumstances.",
    "Perhaps from there I can bring you some directions or a torch from the fire so you may warm yourselves\"": "Moses had practical intentions: he hoped to either get directions (since they may have been lost in the desert) or bring back a burning branch to warm his family on the cold night. He had no idea that this fire would change his life and human history forever."
  },
  30: {
    "But when he came to it, he was called from the bush in the sacred ground to the right side of the valley": "As Moses approached the fire, something extraordinary happened. A voice called out to him—not from a person, but from a bush on blessed, sacred ground. This was holy ground, sanctified by Allah's presence. The location was on the right side of the valley, specified precisely by Allah.",
    "\"O Moses! It is truly I. I am Allah—the Lord of all worlds\"": "The voice identified itself directly and unmistakably. This was Allah Himself speaking to Moses without any intermediary. Allah declared His identity: He is the Lord, Creator, and Sustainer of all worlds and all creation. This moment made Moses one of the very few prophets to whom Allah spoke directly, earning him the title 'Kaleemullah' (the one who spoke with Allah). Imagine the overwhelming awe Moses must have felt—the Creator of the universe was addressing him by name."
  },
  31: {
    "Now, throw down your staff!\"": "Allah commanded Moses to throw down his walking stick. This staff, an ordinary shepherd's tool that Moses had carried for years, was about to become a miraculous sign.",
    "But when he saw it slithering like a snake, he ran away without looking back": "The moment the staff hit the ground, it transformed into a living, moving snake. Moses' natural human reaction was fear—he turned and fled without looking back. This was not cowardice; it was a normal human response to something terrifying and unexpected. Even prophets experience fear; they are human beings.",
    "˹Allah reassured him,˺ \"O Moses! Draw near, and have no fear. You are perfectly secure\"": "Allah called Moses back with words of comfort and reassurance. He told Moses not to be afraid and assured him of complete safety. When Allah grants security, there is nothing to fear. This teaches us that Allah's presence brings peace, not terror, to the believers."
  },
  32: {
    "Now put your hand through ˹the opening of˺ your collar, it will come out ˹shining˺ white, unblemished": "Allah gave Moses a second miraculous sign. When Moses placed his hand inside his garment and withdrew it, his hand would emerge glowing with brilliant white light—but this was not a disease like leprosy; it was pure, radiant light. This miracle demonstrated Allah's power over the human body itself.",
    "And cross your arms tightly to calm your fears": "Allah gave Moses a practical technique to overcome his fear: drawing his arms close to his body would help calm his nerves. Some scholars interpret this as pressing his hand to his side to stop trembling. Allah understands human psychology and provides means to overcome our weaknesses.",
    "These are two proofs from your Lord to Pharaoh and his chiefs": "The staff-turning-to-snake and the glowing hand were two clear miracles that Moses would present to Pharaoh. These were not magic tricks but divine signs proving Moses' prophethood and Allah's power.",
    "They have truly been a rebellious people\"": "Allah described Pharaoh and his elite as 'fasiqeen'—those who have transgressed all bounds, rebelled against Allah, and left the path of righteousness. Their corruption was complete, affecting their beliefs, governance, and treatment of people."
  },
  33: {
    "Moses appealed, \"My Lord! I have indeed killed a man from them, so I fear they may kill me\"": "Moses honestly expressed his concern to Allah. He remembered that he had killed an Egyptian man years ago and fled as a wanted fugitive. He feared that if he returned to Egypt, they would execute him for that crime before he could even deliver Allah's message. This shows that prophets are human—they have genuine fears and concerns. Moses didn't hide his worry from Allah; he expressed it openly, seeking Allah's help."
  },
  34: {
    "And my brother Aaron is more eloquent than I": "Moses acknowledged his own weakness—he had difficulty speaking fluently. Some scholars say he had a speech impediment from childhood. Moses recognized that his brother Harun (Aaron), who had remained in Egypt, was a better speaker.",
    "so send him with me as a helper to support what I say": "Moses requested that Aaron be appointed as his assistant and supporter. He wanted someone who could articulate the message clearly and back him up. This shows wisdom in leadership: recognizing one's weaknesses and seeking help from those who have complementary strengths.",
    "for I truly fear they may reject me\"": "Moses feared that Pharaoh and his people would deny his message. Having a supporting voice would strengthen his mission. Moses was not doubting Allah's plan; he was asking for the means to accomplish it more effectively."
  },
  35: {
    "Allah responded, \"We will assist you with your brother": "Allah granted Moses' request completely. Aaron would be appointed as a prophet alongside Moses, strengthening and supporting him. Allah listens to the sincere requests of His servants and grants what is best for them.",
    "and grant you both authority": "Allah promised to give both Moses and Aaron a special authority and protection that would shield them from harm. This divine authority meant that despite Pharaoh's worldly power, he would be unable to touch them.",
    "so they cannot harm you": "Allah gave a direct guarantee of safety. No matter what Pharaoh planned, he would not be able to reach or harm Moses and Aaron. When Allah protects someone, no force on earth can overcome that protection.",
    "With Our signs, you and those who follow you will ˹certainly˺ prevail\"": "Allah promised ultimate victory. Armed with divine signs (miracles), Moses, Aaron, and their followers would triumph over Pharaoh and his entire system. This was a guarantee of success before the mission even began—giving Moses confidence to proceed."
  },
  36: {
    "But when Moses came to them with Our clear signs": "Moses returned to Egypt and presented the miraculous signs Allah had given him. These were clear, undeniable proofs of divine origin—the staff becoming a snake, the glowing hand, and other miracles.",
    "they said ˹arrogantly˺, \"This is nothing but conjured magic ˹tricks˺\"": "Despite witnessing obvious miracles, Pharaoh and his people dismissed them as mere magic—tricks that Moses had fabricated. This is the response of arrogant hearts: when truth conflicts with their desires, they deny it with whatever excuse they can find.",
    "We have never heard of this in ˹the history of˺ our forefathers\"": "They used tradition as an excuse for rejection. Because their ancestors didn't believe in Allah or follow a messenger, they refused to accept anything new. This is a dangerous mentality: blindly following forefathers even when they were wrong. Truth doesn't become false just because previous generations rejected it."
  },
  37: {
    "Moses responded, \"My Lord knows best who has come with ˹true˺ guidance from Him": "Moses didn't argue endlessly. He simply stated that Allah knows the truth—He knows who is genuinely bringing divine guidance and who is lying. Moses was confident in his truthfulness and left the judgment to Allah.",
    "and will fare best in the end": "Moses pointed to the ultimate outcome. Regardless of what happens in this world, the final result belongs to the righteous. The one who will have a good end in the Hereafter is the one who follows truth.",
    "Indeed, the wrongdoers will never succeed\"": "Moses declared a universal truth: those who commit wrong and persist in injustice will never achieve true success. They may appear successful temporarily, but their end is always ruin. This applies to Pharaoh and every oppressor throughout history."
  },
  38: {
    "Pharaoh declared, \"O chiefs! I know of no other god for you but myself\"": "This is the height of arrogance and disbelief. Pharaoh claimed to be the only god his people should worship. He denied the existence of any deity besides himself. This was his consistent claim, as mentioned elsewhere in the Quran: 'I am your most exalted lord' (79:24). This is the ultimate corruption—a created being claiming to be the Creator.",
    "So bake bricks out of clay for me, O Hamân, and build a high tower": "Pharaoh ordered his minister Hamân to construct a tall tower using baked bricks. This was meant as a dramatic gesture of defiance and mockery.",
    "so I may look at the God of Moses": "Pharaoh sarcastically claimed he would climb this tower to 'look at' the God Moses spoke of—as if Allah were a physical being residing in the sky that could be seen from a tall building. This shows his complete misunderstanding (or deliberate mockery) of who Allah is.",
    "although I am sure he is a liar\"": "Pharaoh concluded by declaring Moses a liar. Despite all the miracles and clear evidence, Pharaoh chose to reject the truth. His arrogance blinded him to reality. When someone's heart is diseased with pride, even the clearest signs cannot penetrate it."
  },
  39: {
    "And so he and his soldiers behaved arrogantly in the land with no right": "Pharaoh and his entire military apparatus acted with unjustified arrogance. They had no legitimate authority for their tyranny—their power was built on oppression, not righteousness. They dominated the land through force, not through any divine right.",
    "thinking they would never be returned to Us": "This was their fundamental error: they believed there was no afterlife, no Day of Judgment, no accountability. They thought their power would last forever and they would never face consequences for their actions. This delusion is what allows tyrants to commit atrocities—they don't believe in ultimate justice."
  },
  40: {
    "So We seized him and his soldiers, casting them into the sea": "Allah's punishment came swiftly and decisively. When Pharaoh pursued Moses and the Israelites to the sea, Allah caused the waters to drown Pharaoh and his entire army. The mightiest military force of that era was destroyed in moments. The same sea that parted to save the believers closed upon the disbelievers.",
    "See then what was the end of the wrongdoers!": "Allah draws our attention to the lesson: look at how the oppressors ended. They who thought themselves invincible were utterly destroyed. Their palaces, their armies, their treasures—nothing could save them from Allah's punishment. This is the fate awaiting every tyrant."
  },
  41: {
    "We made them leaders inviting ˹others˺ to the Fire": "Pharaoh and his chiefs became examples—but negative examples. They became 'imams' (leaders) calling others toward Hell. Anyone who follows their path of arrogance, disbelief, and tyranny is following them toward the Fire. They lead by bad example, and their followers will share their fate.",
    "And on the Day of Judgment they will not be helped": "On the Day when everyone will desperately need help, Pharaoh and his followers will find no assistance. No one will intercede for them, no one will defend them, and no one will rescue them from the punishment they earned."
  },
  42: {
    "We caused a curse to follow them in this world": "Allah's curse pursued Pharaoh and his people even after death. They are remembered throughout history with disgrace and condemnation. Every time their story is told, they are cursed. Their legacy is one of shame, not honor.",
    "And on the Day of Judgment they will be among the outcasts": "Their punishment continues in the Hereafter. They will be among the 'maqbooheen'—those made hideous, despised, and rejected. They will be cast away from Allah's mercy, humiliated before all of creation."
  },
  43: {
    "Indeed, We gave Moses the Scripture—after destroying earlier nations": "After Pharaoh's destruction, Allah revealed the Torah to Moses. This came after previous rebellious nations had been destroyed for their disbelief. The pattern of history shows that Allah sends guidance, and when people reject it, destruction follows.",
    "as an insight for the people": "The Torah was given as 'basaa'ir'—sources of insight and enlightenment. It opened people's eyes to spiritual realities, helping them see truth clearly and understand the purpose of life.",
    "a guide, and mercy": "The Scripture served as guidance (huda)—showing the right path in all aspects of life. It was also a mercy (rahma)—a gift of compassion from Allah to help people succeed in this life and the next.",
    "so perhaps they would be mindful": "The ultimate purpose was that people would take heed, remember Allah, and live consciously. The Scripture was meant to awaken them from heedlessness and bring them to awareness of their Creator and their responsibilities."
  },
  44: {
    "You were not there ˹O Prophet˺ on the western side of the mountain when We entrusted the Commandments to Moses": "Allah addresses Prophet Muhammad (peace be upon him), pointing out that he was not physically present at Mount Sinai when Allah gave Moses the divine commandments. Muhammad was not there to witness these events.",
    "nor were you present ˹in his time˺": "The Prophet lived centuries after Moses and had no way of knowing these detailed historical events through ordinary means. He couldn't read or write, had no access to previous scriptures, and had never studied with religious scholars. Yet the Quran narrates these events with perfect accuracy."
  },
  45: {
    "But We ˹later˺ raised ˹several˺ generations, and the ages took their toll on them": "Many generations passed between Moses' time and Muhammad's time. Over these long centuries, the original teachings became distorted, knowledge was lost, and people forgot the lessons of history.",
    "Nor were you living among the people of Midian, rehearsing Our revelations with them": "The Prophet never lived in Midian where Moses spent years. He never learned these stories from the people there. He had no human source for this detailed knowledge.",
    "But it is We Who have sent ˹this revelation to you˺": "The only explanation for the Prophet's knowledge is divine revelation. Allah Himself sent this information to Muhammad. This is proof of the Quran's divine origin—how else could an unlettered man in Arabia know such detailed accounts of events from centuries past?"
  },
  46: {
    "And you were not at the side of Mount Ṭûr when We called out ˹to Moses˺": "Again, Allah emphasizes that the Prophet was not present at these miraculous events. He didn't witness Allah calling to Moses from the burning bush.",
    "But ˹you have been sent˺ as a mercy from your Lord": "The Prophet Muhammad (peace be upon him) was sent as an act of divine mercy. His mission was a gift to humanity—guidance for those who had gone astray.",
    "to warn a people to whom no warner has come before you": "The Arabs had not received a prophet in their own language from among themselves for a very long time. They had become deeply immersed in idolatry and ignorance. Muhammad came to fill this gap.",
    "so perhaps they may be mindful": "The purpose of sending the Prophet was to awaken the Arabs and all humanity to the truth, hoping they would reflect, remember Allah, and return to the right path."
  },
  47: {
    "Also so they would not say, if struck by an affliction for what their hands have done": "Allah sent messengers to remove all excuses. If punishment came to people for their sins, they might try to excuse themselves.",
    "\"Our Lord! If only You had sent us a messenger, we would have followed Your revelations and become believers\"": "Without messengers, people could claim ignorance on the Day of Judgment. They could say, 'We didn't know! If only You had sent someone to warn us, we would have believed!' By sending the Prophet, Allah removed this excuse. The message was delivered clearly; those who reject it have no one to blame but themselves."
  },
  48: {
    "But when the truth came to them from Us, they said, \"If only he was given the like of what Moses had been given\"": "When the Quran came to the disbelievers, they demanded that Muhammad receive exactly what Moses received—perhaps a complete book all at once, or the same type of miracles. They kept changing their demands, looking for excuses to reject.",
    "Did they not deny what had been given to Moses earlier?": "Allah exposes their inconsistency: these same people (or their spiritual predecessors) had rejected Moses' message too! If they had accepted Moses' teachings, they would recognize Muhammad as the prophet Moses foretold. Their objection about Moses was insincere.",
    "They claimed, \"Both ˹Scriptures˺ are works of magic, supporting each other!\"": "Some disbelievers dismissed both the Torah and the Quran as magic that reinforced each other. This shows they weren't sincere in their objections—they just wanted to reject everything.",
    "Adding, \"We truly deny both\"": "They openly declared their rejection of all divine revelation. This was not honest inquiry but stubborn denial of all guidance."
  },
  49: {
    "Say, ˹O Prophet,˺ \"Bring then a scripture from Allah which is a better guide than these two so I may follow it": "Allah instructs the Prophet to challenge the disbelievers: if they reject both the Torah and the Quran, let them produce something better. Let them bring a book that offers superior guidance to these two divinely revealed scriptures.",
    "if your claim is true\"": "This challenge exposes their inability. They cannot produce anything comparable because these scriptures are from Allah. If they were sincere seekers of truth, they would recognize the guidance in these books. Their rejection proves they have no alternative to offer."
  },
  50: {
    "So if they fail to respond to you, then know that they only follow their desires": "When they cannot meet the challenge, their true motive is exposed: they are not following reason, evidence, or sincere inquiry—they are simply following their whims and desires. They reject truth not because of logical objections but because it conflicts with how they want to live.",
    "And who could be more astray than those who follow their desires with no guidance from Allah?": "This is a rhetorical question emphasizing a profound truth: there is no one more lost than a person who makes their own desires their guide instead of divine guidance. Human desires are fickle, biased, and often lead to harm. Without Allah's guidance to correct and direct us, we are hopelessly lost.",
    "Surely Allah does not guide the wrongdoing people": "Allah does not force guidance upon those who persistently choose wrongdoing. When people insist on following their desires and rejecting truth, Allah leaves them in their misguidance as a consequence of their own choices. Guidance is a gift that Allah gives to those who sincerely seek it, not to those who deliberately turn away."
  },
  51: {
    "Indeed, We have steadily delivered the Word ˹of Allah˺ to the people": "Allah has continuously and consistently sent His message to humanity throughout history. The word 'wassalna' (delivered steadily) implies connection and continuity—Allah did not leave humanity without guidance at any time. Prophet after prophet, scripture after scripture, the divine message kept coming. The Quran itself was revealed gradually over 23 years, allowing people to absorb and understand it properly.",
    "so they may be mindful": "The purpose of this continuous revelation is to remind people and awaken their consciousness. Allah wants people to reflect, remember, and return to the truth. Every generation received reminders so that no one could claim ignorance. The question is: will people pay attention and take heed?"
  },
  52: {
    "˹As for˺ those ˹faithful˺ to whom We had given the Scripture before this ˹Quran˺, they do believe in it": "This refers to sincere Jews and Christians who, upon hearing the Quran, recognized it as truth from the same God who sent Moses and Jesus. People like Abdullah ibn Salam (a Jewish rabbi who accepted Islam), Salman al-Farisi (who searched for truth across religions), and the Negus of Abyssinia are examples. Their previous knowledge of divine scripture prepared them to recognize the Quran's authenticity."
  },
  53: {
    "When it is recited to them, they declare, \"We believe in it\"": "When these sincere people hear the Quran being recited, they immediately affirm their belief. The beauty, truth, and consistency of the Quran resonates with what they already knew from their scriptures.",
    "This is definitely the truth from our Lord": "They recognize the Quran as coming from the same Lord who sent previous revelations. The message is consistent—calling to the worship of One God, righteousness, and accountability. They see the Quran as a continuation and confirmation of earlier truth.",
    "We had already submitted ˹even˺ before this\"": "They claim to have been 'Muslims' (those who submit to Allah) even before the Quran came. This doesn't mean they followed Muhammad's specific teachings, but that they were already surrendered to God's will. True followers of Moses and Jesus were essentially Muslims in the sense of submission to God. Islam is the universal religion of all prophets."
  },
  54: {
    "These ˹believers˺ will be given a double reward": "Those who believed in their previous scripture and then believed in the Quran will receive twice the reward. This is confirmed in a hadith where the Prophet (peace be upon him) said: 'Three persons will get their reward twice...' including 'a person from the People of the Book who believed in his prophet and then believed in Muhammad' (Bukhari). Their faith journey was longer and harder, so their reward is multiplied.",
    "for their perseverance": "They showed patience in holding onto truth despite opposition from their own communities. When Jews or Christians accepted Islam, they often faced rejection from family and society. Their steadfastness in the face of pressure is rewarded.",
    "responding to evil with good": "When people treat them badly, they respond with kindness rather than retaliation. This is a high level of character—not repaying evil with evil, but transforming negative situations through positive responses. This takes great self-control and spiritual maturity.",
    "and for donating from what We have provided for them": "They are generous with their wealth, spending in Allah's cause and helping others. They recognize that everything they have is from Allah and share it freely. This combination of patience, good character, and generosity marks them as exceptional believers."
  },
  55: {
    "When they hear slanderous talk, they turn away from it": "When people speak nonsense, insults, or foolishness to them, they simply turn away. They don't engage in arguments with those who want to provoke them. They protect their peace and dignity by refusing to participate in worthless exchanges.",
    "saying, \"We are accountable for our deeds and you for yours\"": "They establish clear boundaries: 'We are responsible for our actions, and you are responsible for yours.' There's no benefit in endless debates with those who don't want to understand. Each person will answer for their own choices before Allah.",
    "Peace ˹is our only response˺ to you!": "Instead of returning insults with insults, they offer peace (salam). This is the beautiful Islamic response to hostility—wishing peace even to those who are antagonistic. It shows moral superiority without arrogance.",
    "We want nothing to do with those who act ignorantly\"": "They choose not to associate closely with people who persist in ignorance and foolishness. This isn't arrogance—it's wisdom. Spending time in pointless arguments with stubborn people wastes energy that could be used for good. They seek the company of those who are thoughtful and sincere."
  },
  56: {
    "You surely cannot guide whoever you like ˹O Prophet˺": "This verse was revealed about Abu Talib, the Prophet's beloved uncle who protected and supported him but never accepted Islam. Despite the Prophet's intense desire for his uncle's guidance, and despite being at his deathbed urging him to say the shahada, Abu Talib died without accepting Islam. This shows that even the Prophet, with all his love and effort, cannot put faith into someone's heart.",
    "but it is Allah Who guides whoever He wills": "Guidance is ultimately Allah's domain. A person can present the truth beautifully, but the actual opening of hearts belongs to Allah alone. This is why we pray 'Guide us to the straight path' (1:6)—because we need Allah's help for guidance.",
    "and He knows best who are ˹fit to be˺ guided": "Allah knows the inner state of every heart. He knows who is sincere and receptive, and who is arrogant and closed. He guides those whom He knows are worthy and willing. This doesn't mean Allah is arbitrary—He guides those who truly want guidance and turn to Him sincerely."
  },
  57: {
    "They say ˹to the Prophet˺, \"If we were to follow ˹true˺ guidance with you, we would certainly be snatched away from our land\"": "The Quraysh made a political excuse for rejecting Islam. They claimed that if they abandoned their idols and followed Muhammad, the surrounding Arab tribes would unite against them and expel them from Mecca. They prioritized worldly security over eternal truth—a common excuse throughout history.",
    "Have We not established for them a safe haven ˹in Mecca˺": "Allah refutes their excuse by pointing out an obvious reality: Mecca was already a safe sanctuary! While Arabs everywhere fought and raided each other, Mecca enjoyed peace and security. This wasn't because of their idols—it was because Allah had made it a sacred territory (Haram) where fighting was forbidden.",
    "to which fruits of all kinds are brought as a provision from Us?": "Despite being in a barren valley with no agriculture, Mecca received fruits and goods from everywhere. Merchants brought produce from fertile lands. This abundance was Allah's provision, not the work of their false gods.",
    "But most of them do not know ˹this favour˺": "They failed to recognize that their security and prosperity came from Allah, not from their idols. They were blind to the source of their blessings, attributing to statues what only Allah had given them."
  },
  58: {
    "˹Imagine˺ how many societies We have destroyed that had been spoiled by their ˹comfortable˺ living!": "Allah warns about nations that became arrogant due to their prosperity. When people have too much comfort without gratitude, they often become ungrateful and rebellious. History is full of civilizations that were destroyed at the peak of their luxury because they forgot Allah.",
    "Those are their residences, never inhabited after them except passingly": "Their homes and cities remained as ruins—empty reminders of their fate. Travelers might pass through, but no one lived there permanently anymore. The Arabs knew of such ruins; they passed by the remains of Thamud and other destroyed peoples during their trade journeys.",
    "And We ˹alone˺ were the Successor": "After these nations perished, Allah remained. All their wealth, power, and possessions returned to Allah's ownership. They thought they owned everything, but in the end, they owned nothing. Allah inherits the earth and everything in it."
  },
  59: {
    "Your Lord would never destroy a society until He had sent to its capital a messenger, reciting Our revelations to them": "This establishes Allah's perfect justice. He never punishes a people without first sending them clear guidance. A messenger comes to the main city (the center of influence), recites Allah's verses, and gives them the chance to accept truth. Only after they reject the message does punishment come.",
    "Nor would We ever destroy a society unless its people persisted in wrongdoing": "Destruction only comes after persistent, deliberate wrongdoing. A single sin doesn't bring collective punishment. It's when a society embraces corruption, rejects truth, and continues in oppression that Allah's punishment descends. This should serve as both a warning and a reassurance: warning for the arrogant, reassurance that Allah is never unjust."
  },
  60: {
    "Whatever ˹pleasure˺ you have been given is no more than ˹a fleeting˺ enjoyment and adornment of this worldly life": "Everything we possess or enjoy in this world—wealth, health, beauty, status, pleasures—is temporary. It's like decoration (zeena) that looks attractive but doesn't last. A beautiful house eventually crumbles; youth fades; wealth can be lost overnight. This isn't saying worldly things are evil, but that they are limited and temporary.",
    "But what is with Allah is far better and more lasting": "The rewards of the Hereafter are superior in quality and eternal in duration. Paradise is not just 'good'—it's beyond our imagination. And unlike worldly pleasures that end, the pleasures of Paradise never fade or diminish. Why would anyone choose temporary enjoyment over eternal bliss?",
    "Will you not then understand?": "Allah appeals to human reason. Any rational person comparing a few years of worldly pleasure to an eternity of divine reward would choose the latter. Yet many people are so absorbed in the immediate that they forget the eternal. This verse calls us to think deeply about our priorities."
  },
  61: {
    "Can those to whom We have made a fine promise—which they will see fulfilled": "Allah describes the believers: they have been promised something beautiful (Paradise), and they will definitely receive it. Allah's promises are guaranteed—unlike worldly promises that often fall through.",
    "be like those who We have allowed to enjoy the pleasures of this worldly life": "This refers to disbelievers who may have worldly success and enjoyment. They might seem to be doing well, living comfortably, enjoying life's pleasures.",
    "but on the Day of Judgment will be brought ˹for punishment˺?": "Despite their temporary enjoyment, these disbelievers will be brought to account on the Day of Judgment. 'Brought' (muhdareen) implies they will be dragged or summoned forcefully to face consequences. How can these two groups—one promised eternal reward, the other facing eternal punishment—ever be considered equal?"
  },
  62: {
    "˹Watch for˺ the Day He will call to them, \"Where are those you claimed were My associate-gods?\"": "On the Day of Judgment, Allah will directly question the disbelievers about their false gods. This is a rhetorical question meant to expose and humiliate them. Where are the idols they worshipped? Where are the saints they invoked? Where are the beings they claimed could help them? The answer is obvious: they are nowhere to be found, completely powerless."
  },
  63: {
    "Those ˹misleaders˺ against whom the decree ˹of torment˺ is justified will cry, \"Our Lord! These ˹followers˺ are the ones we caused to deviate\"": "The leaders of misguidance—those who invented false religions, promoted idolatry, or led others astray—will speak up. They admit they misled people, but they try to shift blame.",
    "We led them into deviance, for we ourselves were deviant": "They offer an excuse: 'We were already lost, so naturally we led others astray.' This is an attempt to minimize their responsibility, as if being misguided themselves excuses misleading others.",
    "We disassociate ourselves ˹from them˺ before You": "Now, in front of Allah, these leaders abandon their followers completely. The bonds between them dissolve. Those who followed them blindly will find their leaders denying any responsibility.",
    "It was not us that they used to worship\"": "The misleaders claim that ultimately, people weren't worshipping them but their own desires. This mutual rejection between leaders and followers on the Day of Judgment is a recurring Quranic theme—showing that false alliances crumble when they matter most."
  },
  64: {
    "It will be said ˹to the disbelievers˺, \"Call upon your associate-gods ˹for help˺\"": "The disbelievers will be challenged to call upon the gods they worshipped for help. This is the ultimate test of their false beliefs.",
    "So they will call them, but will receive no response": "They will cry out to their idols, saints, or whatever they associated with Allah—and there will be absolute silence. No help comes. No response. Their 'gods' cannot help themselves, let alone their worshippers.",
    "And they will face the punishment": "With no one to help them, they will see the punishment approaching. The reality of their situation will become inescapably clear.",
    "wishing they had been ˹rightly˺ guided!": "In that moment of terror, they will desperately wish they had followed the truth. They will wish they had listened to the prophets, accepted the message, and chosen the right path. But it will be too late for wishes."
  },
  65: {
    "And ˹watch for˺ the Day He will call to them, asking, \"What response did you give to the messengers?\"": "Allah will ask another critical question: How did you respond when My messengers came to you? Did you believe and follow? Did you reject and oppose? Did you ignore and turn away? This question cuts to the heart of human accountability—we will be judged on how we treated Allah's message and messengers."
  },
  66: {
    "They will be too dumbstruck on that Day to ask one another ˹for answers˺": "The disbelievers will be completely confused and speechless. All the excuses and arguments they prepared will vanish. They won't even be able to consult with each other or coordinate their responses. The terror and clarity of that Day will leave them unable to think or speak coherently. All their worldly cleverness will be useless."
  },
  67: {
    "As for those who repent, believe, and do good ˹in this world˺": "After describing the fate of disbelievers, Allah gives hope to those who choose the right path. Three things are mentioned: repentance (turning back to Allah from sin), belief (having faith in Allah and His messengers), and good deeds (putting faith into action). These three elements together constitute the path to salvation.",
    "it is right to hope that they will be among the successful": "Allah uses the word 'asaa' (it is hoped/expected) which in Arabic, when used by Allah, indicates certainty. Those who fulfill these conditions have a strong expectation of success. 'Muflihoon' (the successful) are those who achieve ultimate success—salvation in the Hereafter and entry into Paradise. This verse is immensely hopeful: no matter what sins one has committed, the door of repentance is open."
  },
  68: {
    "Your Lord creates and chooses whatever He wills": "Allah has absolute freedom in creation and selection. He creates what He wants and chooses whom He wills for specific roles and honors. He chose certain prophets over others, certain lands as sacred, certain times as blessed. These choices are His alone to make.",
    "the choice is not theirs": "Human beings do not get to dictate to Allah whom He should honor or what He should do. The Arabs objected that Muhammad was chosen as a prophet instead of a wealthy chief. This verse clarifies that such choices belong exclusively to Allah. We don't get to vote on who should be a prophet or what should be sacred.",
    "Glorified and Exalted is Allah above what they associate ˹with Him˺!": "Allah is far above any partners or equals. He is glorified beyond any deficiency and exalted above any comparison. Associating others with Allah in worship or authority is a tremendous insult to His majesty."
  },
  69: {
    "And your Lord knows what their hearts conceal and what they reveal": "Nothing is hidden from Allah. He knows the secrets people hide in their hearts—their true intentions, hidden jealousies, secret plots—and He knows what they openly express. Some people say one thing but mean another; Allah knows both. This knowledge makes Him the perfect judge, as no deception can work on Him."
  },
  70: {
    "He is Allah. There is no god ˹worthy of worship˺ except Him": "This is the fundamental declaration of Islamic monotheism (Tawheed). Allah alone deserves worship. All other so-called gods are false—they have no power, no authority, and no right to be worshipped.",
    "All praise belongs to Him in this life and the next": "In both worlds—the current temporary world and the eternal Hereafter—all praise and gratitude are due to Allah alone. Everything good comes from Him, so all thanks return to Him.",
    "All authority is His": "Ultimate judgment and decision-making belong to Allah. He is the final authority on all matters. No one can override His decisions or appeal His judgments.",
    "And to Him you will ˹all˺ be returned": "Every soul will return to Allah after death. There is no escaping this return. This fact should make every person consider how they are living and what they will present to Allah when they meet Him."
  },
  71: {
    "Ask ˹them, O Prophet˺, \"Imagine if Allah were to make the night perpetual for you until the Day of Judgment": "Allah presents a thought experiment: What if the night never ended? What if darkness covered the earth permanently? This would be catastrophic—plants couldn't grow, temperatures would plummet, life would become impossible.",
    "which god other than Allah could bring you sunlight?": "If this happened, could any idol, any false god, any power bring back the sun? Of course not. Only Allah controls the cosmic order. This question exposes the utter helplessness of everything besides Allah.",
    "Will you not then listen?": "Will people not hear this reasoning and understand? The question appeals to their sense of hearing—pay attention to this logical argument and accept the truth of Allah's exclusive power."
  },
  72: {
    "Ask ˹them also˺, \"Imagine if Allah were to make the day perpetual for you until the Day of Judgment": "Now consider the opposite: What if the sun never set? What if it was always daytime? The heat would become unbearable, sleep would be disrupted, the earth would become inhospitable in a different way.",
    "which god other than Allah could bring you night to rest in?": "Who could bring the relief of cool darkness for rest? No one but Allah. The alternation of day and night is a mercy most people take for granted.",
    "Will you not then see?": "This question appeals to their sense of sight—look around at the obvious signs of Allah's power and recognize the truth. The evidence is visible everywhere for those willing to see."
  },
  73: {
    "It is out of His mercy that He has made for you the day and night": "The cycle of day and night is not random—it is a deliberate mercy from Allah. He designed this system specifically for human benefit. This is one of countless mercies we experience daily without thinking about it.",
    "so that you may rest ˹in the latter˺": "The night provides darkness and coolness for rest and sleep. Our bodies are designed to need this recovery time. Sleep is a blessing that rejuvenates us physically and mentally.",
    "and seek His bounty ˹in the former˺": "The day provides light and energy for work and productivity. We can see, travel, trade, farm, and accomplish our tasks during daylight. This is when we seek our livelihood—Allah's bounty.",
    "and perhaps you will be grateful": "The purpose behind these blessings is to inspire gratitude. When we recognize how perfectly Allah has designed our world for our benefit, we should naturally feel thankful. Gratitude leads to more blessings, as Allah says: 'If you are grateful, I will surely increase you' (14:7)."
  },
  74: {
    "And ˹watch for˺ the Day He will call to them, \"Where are those you claimed were My associate-gods?\"": "This verse repeats the earlier question (verse 62) for emphasis, as it is such a critical moment. Allah will directly confront the polytheists on the Day of Judgment, demanding to know where their false gods are. The repetition drives home the point: this question will be asked, and there will be no satisfactory answer. The disbelievers will stand exposed, their entire belief system shown to be a lie."
  },
  75: {
    "And We will bring forth a witness from every faith-community": "From every nation and community, a witness will be brought forward—their prophet or messenger who delivered Allah's message to them. These witnesses will testify about whether the message was conveyed and how the people responded. Prophet Muhammad (peace be upon him) will be a witness for his ummah, as will Moses, Jesus, and all other prophets for their respective peoples.",
    "and ask ˹the polytheists˺, \"Show ˹Us˺ your proof\"": "The disbelievers will be challenged to present evidence for their false beliefs. Where is the proof that their idols deserved worship? What evidence did they have that partners existed alongside Allah? This demand for proof will leave them speechless because they had no proof—only inherited traditions and blind following.",
    "Then they will ˹come to˺ know that the truth is with Allah ˹alone˺": "At that moment, all doubts will vanish. The reality that Allah alone is true and worthy of worship will become absolutely clear to everyone, including those who denied it in worldly life. But this knowledge will come too late to benefit them.",
    "And whatever ˹gods˺ they fabricated will fail them": "All the false deities they invented and worshipped will completely abandon them. These fabricated gods will be of no use whatsoever—they cannot help, intercede, or save. The word 'dalla' (fail/lose) indicates that these false gods will be utterly lost to them, vanishing when needed most."
  },
  76: {
    "Indeed, Korah was from the people of Moses": "Qarun (Korah in Biblical tradition) was an Israelite, from the same community as Prophet Moses. Some reports say he was Moses' cousin. He was not an outsider or an enemy—he was one of them, which made his betrayal and arrogance even worse.",
    "but he behaved arrogantly towards them": "Despite being from the oppressed Israelite community, Qarun turned against his own people. His wealth made him feel superior, and he began to oppress and look down upon them. Wealth can corrupt a person to the point where they forget their roots and mistreat their own community.",
    "We had granted him such treasures that even their keys would burden a group of strong men": "Allah describes the extent of Qarun's wealth in vivid terms: just the keys to his treasure chests were so numerous and heavy that a group of strong men would struggle to carry them. Imagine the treasures themselves! This wasn't wealth he earned entirely by himself—Allah 'granted' it to him, though Qarun forgot this fact.",
    "˹Some of˺ his people advised him, \"Do not be prideful! Surely Allah does not like the prideful\"": "Sincere believers from his community tried to counsel him. They warned him against arrogant joy (farah)—the kind of happiness that makes a person boastful and forgetful of Allah. Being happy with blessings is fine, but being arrogantly proud and thinking you're better than others because of wealth is what Allah dislikes."
  },
  77: {
    "Rather, seek the ˹reward˺ of the Hereafter by means of what Allah has granted you": "The advisors gave Qarun beautiful, balanced guidance. Use your wealth to earn rewards in the Hereafter—through charity, helping others, supporting good causes. Wealth is a tool that can be used to build eternal rewards if spent in Allah's way.",
    "without forgetting your share of this world": "Islam doesn't demand that you abandon worldly life entirely. You can enjoy lawful pleasures, take care of yourself and family, and live comfortably. The key is balance—neither obsessing over this world nor completely neglecting it. This verse establishes the Islamic middle path regarding wealth.",
    "And be good ˹to others˺ as Allah has been good to you": "Allah has been generous to you, so be generous to others. This is a beautiful principle: we should pass on the goodness we receive. If Allah blessed you with wealth, bless others with your generosity. If Allah gave you knowledge, share it. Kindness should flow through us to others.",
    "Do not seek to spread corruption in the land": "Wealth can be used for good or evil. Using it to oppress people, spread immorality, or cause harm is corruption (fasad). Qarun was using his wealth to create divisions, show off, and harm his community.",
    "for Allah certainly does not like the corruptors": "Those who spread corruption are despised by Allah. This applies to any kind of corruption—financial, moral, social, or political. The sincere advisors gave Qarun a complete roadmap for using wealth righteously."
  },
  78: {
    "He replied, \"I have been granted all this because of some knowledge I have\"": "Qarun rejected the sincere advice with arrogance. He claimed his wealth came from his own knowledge and abilities—perhaps business skills, or in some interpretations, knowledge of alchemy. He gave himself all the credit and gave Allah none. This is a dangerous mindset: believing that our success is entirely our own doing, forgetting that Allah gave us the ability, opportunity, and resources in the first place.",
    "Did he not know that Allah had already destroyed some from the generations before him who were far superior to him in power and greater in accumulating ˹wealth˺?": "Allah reminds Qarun (and us) of history. Many before him had more power and more wealth—yet Allah destroyed them. The people of 'Aad were physically stronger; other civilizations had greater treasures. None of it saved them from Allah's punishment when they transgressed. If wealth and power couldn't save them, why would Qarun think he was safe?",
    "There will be no need for the wicked to be asked about their sins": "Allah knows the sins of the criminals without needing to ask. This may also mean that on the Day of Judgment, certain criminals will be punished without a lengthy trial because their guilt is so obvious. Their sins are known, their faces will reveal their guilt, and their own limbs will testify against them."
  },
  79: {
    "Then he came out before his people in all his glamour": "Qarun made a grand public appearance, displaying all his wealth and splendor. He rode out with his servants, his fine clothes, his ornaments—a deliberate show of wealth designed to impress and create envy. This was his way of saying, 'Look how successful I am.'",
    "Those who desired the life of this world wished, \"If only we could have something like what Korah has been given\"": "Some people, upon seeing his display, were filled with envy and longing. They wished they had similar wealth and status. These were people whose hearts were attached to worldly life—they measured success by material possessions. They saw Qarun's wealth and thought he was blessed.",
    "He is truly a man of great fortune!\"": "They considered Qarun extremely lucky, a man of great fortune (hadh adheem). They didn't see his arrogance, his rejection of truth, or his mistreatment of others. They only saw the outward glitter and mistook it for genuine success."
  },
  80: {
    "But those gifted with knowledge said, \"Shame on you!": "The people of knowledge had a completely different reaction. They rebuked those who envied Qarun with 'Wailakum!' (Shame on you! / Woe to you!). They were alarmed that people would envy such a man and desire his situation.",
    "Allah's reward is far better for those who believe and do good": "The knowledgeable ones reminded everyone of the true measure of success: Allah's reward in the Hereafter is infinitely better than any worldly wealth. What is a few decades of luxury compared to eternal Paradise? Those who believe and do righteous deeds will receive something Qarun's wealth cannot buy.",
    "But none will attain this except the steadfast\"": "This understanding—that the Hereafter is better—is not easily achieved. Only those who are patient and steadfast can truly internalize this truth and live by it. It takes patience to resist envying the wealthy when you have less, to stay focused on eternal rewards when worldly temptations are everywhere."
  },
  81: {
    "Then We caused the earth to swallow him up, along with his home": "Allah's punishment came suddenly and completely. The earth literally opened up and swallowed Qarun along with his magnificent house and all his treasures. Everything he had boasted about disappeared into the ground in an instant. The man who had just paraded in glory was now buried beneath the earth.",
    "There was no one to help him against Allah": "All his servants, followers, and admirers were powerless. No group (fi'ah) could come to his defense against Allah's decree. The wealth that he thought gave him power meant nothing when Allah decided to punish him.",
    "nor could he even help himself": "Qarun himself was utterly helpless. He couldn't use his knowledge, his wealth, or his influence to save himself. The one who had claimed self-sufficiency was shown to be completely dependent and vulnerable before Allah's power."
  },
  82: {
    "And those who had craved his position the previous day began to say, \"Ah!": "The very people who had envied Qarun just yesterday now exclaimed in shock and realization. The Arabic 'Waika'anna' expresses amazement and sudden understanding—as if they're saying, 'Oh! Now we understand!'",
    "It is certainly Allah Who gives abundant or limited provisions to whoever He wills of His servants": "They realized that wealth is not a sign of Allah's approval. Allah gives abundantly to some and restricts for others according to His wisdom, not according to who deserves it more. Having wealth doesn't mean Allah loves you, and lacking wealth doesn't mean He's displeased with you.",
    "Had it not been for the grace of Allah, He could have surely caused the earth to swallow us up!": "They recognized how close they came to a similar fate. If Allah had granted their wish and made them like Qarun, they might have suffered the same end. Allah's 'refusal' to give them that wealth was actually His mercy protecting them.",
    "Oh, indeed! The disbelievers will never succeed": "They concluded with a fundamental truth: no matter how successful disbelievers appear, they ultimately fail. True success is with Allah, and those who reject Him cannot achieve it, regardless of worldly appearances."
  },
  83: {
    "That ˹eternal˺ Home in the Hereafter We reserve ˹only˺ for those who seek neither tyranny nor corruption on the earth": "Paradise is for the humble, not the arrogant. It's for those who don't want to dominate and oppress others ('uluww'—seeking to be above others), and who don't spread corruption (fasad). This includes tyrants like Pharaoh and the arrogantly wealthy like Qarun. The common thread is arrogance and harm. True believers seek to serve, not to dominate.",
    "The ultimate outcome belongs ˹only˺ to the righteous": "Al-'Aaqibah (the final outcome) is for the muttaqeen—those who are conscious of Allah and careful to obey Him. No matter what happens in between, the final victory, the lasting success, belongs to the righteous. The story of Qarun proves this: he had everything worldly, but his end was destruction."
  },
  84: {
    "Whoever comes with a good deed will be rewarded with what is better": "Allah's generosity is shown in His reward system. A good deed is not just repaid equally—it's multiplied. One good deed can bring ten rewards, or seventy, or seven hundred, or more. This 'better' reward is Allah's grace to the believers.",
    "And whoever comes with an evil deed, then the evildoers will only be rewarded for what they used to do": "In contrast, evil deeds are punished only according to their actual weight—no more, no less. Allah is just: He doesn't add to the punishment beyond what was earned. This shows Allah's mercy even in punishment: good deeds are multiplied, but bad deeds are counted exactly."
  },
  85: {
    "Most certainly, the One Who has ordained the Quran for you will ˹ultimately˺ bring you back home ˹to Mecca˺": "This verse was revealed when the Prophet (peace be upon him) was migrating from Mecca to Medina, leaving his beloved hometown. Allah comforted him with a promise: the same God who gave you the Quran will bring you back to Mecca. This promise was fulfilled when the Prophet returned victoriously during the Conquest of Mecca. Some scholars also interpret 'ma'ad' as the Hereafter—Allah will return him to the ultimate home of Paradise.",
    "Say, \"My Lord knows best who has come with ˹true˺ guidance and who is clearly astray\"": "The Prophet is instructed to respond to his opponents by leaving judgment to Allah. Allah knows who is truly guided and who is lost. The Prophet doesn't need to argue endlessly—the truth will become clear eventually."
  },
  86: {
    "You never expected this Book to be revealed to you": "Before prophethood, Muhammad (peace be upon him) had no expectation of becoming a prophet or receiving scripture. He was a merchant, living a normal life. The Quran was not something he planned or anticipated—it came as a complete surprise.",
    "but ˹it came˺ only ˹as˺ a mercy from your Lord": "The Quran's revelation was purely Allah's mercy—to the Prophet and to all humanity. It was Allah's gift, not the Prophet's own production. This point refutes those who accused him of inventing it.",
    "So never side with the disbelievers ˹in their disbelief˺": "Now that you have received this blessing, remain firm. Don't support or assist the disbelievers in their opposition to the truth. No matter what pressures or temptations come, stay committed to the message."
  },
  87: {
    "Do not let them turn you away from the revelations of Allah after they have been sent down to you": "The disbelievers will try everything to distract, discourage, or derail the Prophet from his mission. Allah warns him not to let their opposition succeed. Once the truth has come, stay firm upon it regardless of pressure.",
    "Rather, invite ˹all˺ to ˹the Way of˺ your Lord": "The Prophet's mission is to call people to Allah—not to himself, not to a tribe, not to nationalism, but to the Lord of all creation. This is the essence of prophetic work: inviting humanity to their Creator.",
    "and never be one of the polytheists": "A final warning against any form of shirk (associating partners with Allah). The Prophet himself is reminded, emphasizing that no one is beyond needing this reminder. Tawheed (monotheism) must be protected absolutely."
  },
  88: {
    "And do not invoke any other god with Allah": "Worship belongs to Allah alone. No other being—angel, prophet, saint, idol, or anything else—deserves to be called upon in worship alongside Allah.",
    "There is no god ˹worthy of worship˺ except Him": "This is the kalimah, the statement of faith. Only Allah is truly divine, truly worthy of worship, truly deserving of devotion.",
    "Everything is bound to perish except He Himself": "Everything in existence will eventually cease to exist—every person, every creature, every star, every civilization. Only Allah is eternal, without beginning or end. His 'Face' (Wajh) refers to His essence and being. This reality should put everything in perspective: why attach yourself to things that will vanish when you can connect with the One who is eternal?",
    "All authority belongs to Him": "Ultimate power, judgment, and sovereignty belong to Allah. All human authority is temporary and delegated; Allah's authority is absolute and permanent.",
    "And to Him you will ˹all˺ be returned": "The surah ends as it began—with a reminder of the return to Allah. Every soul will go back to its Creator for judgment. This return is certain and unavoidable. How we live in this temporary world determines our fate in the eternal life to come."
  }
};