var tafsirData_89 = {
  1: {
    "By the dawn": "Allah swears by the dawn, the time when light breaks through the darkness of night. The dawn is a powerful sign of Allah's ability to bring life after stillness, hope after despair, and resurrection after death. Just as the dawn marks a new beginning each day, it reminds us of the Day of Judgment when all souls will be brought back to life. This oath draws attention to the greatness of Allah's creation and His control over time itself."
  },
  2: {
    "and the ten nights": "Allah swears by ten special nights, which most scholars identify as the first ten nights of Dhul-Hijjah, the month of pilgrimage. The Prophet (ﷺ) said: 'There are no days in which righteous deeds are more beloved to Allah than these ten days' (Bukhari). These nights are sacred because they include the Day of Arafah and lead up to Eid al-Adha. By swearing by them, Allah highlights their immense spiritual value and calls attention to the importance of worship and good deeds during blessed times."
  },
  3: {
    "and the even and the odd": "Allah swears by things that come in pairs (even) and things that are singular (odd). This can refer to many things in creation—day and night, male and female, or specific acts of worship. Some scholars say 'the even' refers to the Day of Sacrifice (10th of Dhul-Hijjah) and 'the odd' refers to the Day of Arafah (9th of Dhul-Hijjah). Others say it refers to all of creation which comes in pairs, while Allah alone is the One (odd). This oath reminds us of the perfect order and balance Allah has placed in the universe."
  },
  4: {
    "and the night when it passes": "Allah swears by the night as it moves along and eventually gives way to morning. The night's passing is a daily sign of Allah's power over all things. Just as the night cannot remain forever and must yield to the light of day, the darkness of disbelief and wrongdoing cannot escape the light of Allah's judgment. This oath reassures believers that no matter how long oppression or falsehood seems to last, it will eventually pass away."
  },
  5: {
    "Is all this not a sufficient oath for those who have sense": "After these powerful oaths, Allah asks: Isn't this enough evidence for someone who has intelligence and understanding? The word 'hijr' refers to the intellect that restrains a person from foolishness—like a barrier that protects one from harmful choices. People of reason can look at these signs—the dawn, the sacred nights, the patterns in creation, the passing of time—and recognize that there must be a Creator who will hold everyone accountable. This question challenges the deniers: if you have any sense at all, these signs should be enough to convince you of the truth."
  },
  6: {
    "Did you not see how your Lord dealt with 'Ȃd": "Allah directs the Prophet (ﷺ) and all listeners to reflect on what happened to the ancient people of 'Ȃd. Though the Prophet (ﷺ) did not witness this himself, the ruins and reports of their destruction were well-known among the Arabs. The people of 'Ȃd were the descendants of Prophet Nuh (Noah) and lived in the region of Yemen and Oman. They rejected their prophet, Hud (peace be upon him), and were arrogant in their power. This question serves as a warning: if Allah destroyed such a mighty nation, the Quraysh of Makkah should take heed."
  },
  7: {
    "the people of Iram—with their great stature": "Iram was a legendary city built by the people of 'Ȃd, known for its towering pillars and magnificent structures. The phrase 'great stature' can refer either to the tall pillars of their buildings or to the people themselves, who were known to be giants—physically powerful and imposing. Their city was a marvel of ancient engineering, a symbol of their worldly success. Yet all their physical strength and architectural achievements could not save them from Allah's punishment when they persisted in disbelief and arrogance."
  },
  8: {
    "unmatched in any other land": "The civilization of 'Ȃd was unlike anything else that existed at that time. No other nation could compare to them in terms of physical power, architectural skill, or worldly resources. They were the superpower of their era. This description emphasizes that worldly greatness means nothing if one disobeys Allah. Their unmatched status in the world did not protect them from destruction. This is a powerful lesson for the Quraysh and for all powerful nations throughout history: no empire is too great for Allah to bring down."
  },
  9: {
    "and Thamûd who carved their homes into the rocks in the Stone Valley": "The people of Thamûd lived in the northwestern region of Arabia, in an area known as Al-Hijr or Madain Salih. They were master craftsmen who carved elaborate homes and palaces directly into the mountains. Their prophet was Salih (peace be upon him), who brought them a miraculous she-camel as a sign from Allah. Despite this clear miracle, they killed the camel and rejected Salih. Their rock-carved homes, which they thought would protect them forever, could not save them from Allah's punishment. The ruins of their dwellings still stand today as a warning to all who pass by."
  },
  10: {
    "and the Pharaoh of mighty structures": "Pharaoh of Egypt was known for his massive monuments, pyramids, and structures that were held up by great stakes or pillars driven into the ground. Some scholars say 'awtad' (stakes/pegs) refers to the large armies he commanded, which held his kingdom firmly like pegs hold a tent. Others say it refers to his cruel practice of torturing people by nailing them to stakes. Pharaoh considered himself a god and declared, 'I am your most exalted lord' (Quran 79:24). Despite his immense power and the civilization he commanded, he was drowned in the sea when he pursued Prophet Musa (Moses) and the Children of Israel."
  },
  11: {
    "They all transgressed throughout the land": "All three groups—'Ȃd, Thamûd, and Pharaoh—shared a common sin: they exceeded all limits in their wrongdoing across the lands they inhabited. 'Transgression' (tughyan) means going beyond the boundaries set by Allah, refusing to submit to His laws, and oppressing others. They used their power not for justice but for tyranny. They rejected the prophets sent to them and persecuted those who believed. This verse unites these different nations under one common trait: arrogant rebellion against Allah and His messengers."
  },
  12: {
    "spreading much corruption there": "Their transgression was not limited to disbelief alone; they actively spread corruption (fasad) in the land. Corruption includes all forms of evil: injustice, immorality, exploitation of the weak, destruction of family values, economic fraud, and violence. They made evil common and goodness rare. When corruption becomes widespread and leaders promote it rather than prevent it, destruction becomes inevitable. This is a universal law: societies that embrace corruption eventually face consequences, either in this world or the next."
  },
  13: {
    "So your Lord unleashed on them a scourge of punishment": "The word 'sabba' means to pour down heavily, like rain falling in torrents. The 'scourge of punishment' (sawt 'adhab) literally means a whip of torment—a powerful image of severe, continuous punishment that strikes repeatedly. Allah's punishment came upon each of these nations in different forms: 'Ȃd was destroyed by a violent wind that lasted seven nights and eight days, Thamûd was struck by a thunderous blast, and Pharaoh was drowned in the sea. Each punishment was tailored to humble their specific form of arrogance, yet all shared the characteristic of being overwhelming and inescapable."
  },
  14: {
    "For your Lord is truly vigilant": "Allah is 'bil-mirsad'—always watching, always aware, always ready to hold wrongdoers accountable. The mirsad is a place where someone lies in wait to observe and catch others. Nothing escapes Allah's knowledge; no crime goes unnoticed; no oppressor can hide from Him. This verse serves as both a warning to the disbelievers and a comfort to the believers. The wrongdoers should fear because Allah sees everything they do. The believers should take comfort because Allah will certainly bring justice, even if it seems delayed. The Prophet (ﷺ) said: 'Allah gives respite to the oppressor, but when He seizes him, He does not let him escape' (Bukhari and Muslim)."
  },
  15: {
    "Now, whenever a human being is tested by their Lord through His generosity and blessings": "Allah tests people in different ways. One form of test is blessing a person with wealth, health, status, or comfort. Many people fail to recognize this as a test. They assume that because they have been given good things, it must mean Allah is pleased with them or that they deserve it.",
    "they boast, \"My Lord has deservedly honoured me!\"": "When blessed, the ungrateful person proudly declares that they have been honored because they are special or deserving. They attribute the blessings to their own merit rather than recognizing them as a test from Allah. They do not think about using these blessings to please Allah through charity, helping others, or expressing gratitude. The Quraysh leaders were like this—they assumed their wealth proved their superiority, even as they rejected the Prophet (ﷺ). This attitude reflects a fundamental misunderstanding: blessings are not always a sign of Allah's pleasure, just as hardship is not always a sign of His anger."
  },
  16: {
    "But when He tests them by limiting their provision": "The other form of test is restricting a person's sustenance—reducing their wealth, causing them hardship, or taking away their comfort. This too is a test to see how the person responds: Will they remain patient? Will they continue to trust Allah? Will they turn to Him in prayer?",
    "they protest, \"My Lord has undeservedly humiliated me!\"": "Instead of recognizing this as a test and an opportunity to develop patience and draw closer to Allah, the ungrateful person complains that Allah has humiliated them. They feel entitled to constant ease and become resentful when difficulties come. They fail to understand that the prophets—the most beloved people to Allah—often faced the greatest hardships. The Prophet (ﷺ) said: 'The most severely tested people are the prophets, then those closest to them in righteousness' (Tirmidhi). Poverty and difficulty are not signs of disgrace; what matters is how one responds to them."
  },
  17: {
    "Absolutely not! In fact, you are not even gracious to the orphan": "Allah rejects the false reasoning mentioned in the previous verses with a firm 'Kalla!' (Absolutely not!). The real measure of a person's character is not whether they are rich or poor, but how they treat others—especially the vulnerable. Orphans, who have lost their fathers and have no one to protect them, deserve special care and kindness. Yet the wealthy Quraysh neglected and exploited orphans instead of honoring them. The Prophet (ﷺ) himself was an orphan, and he taught: 'I and the one who sponsors an orphan will be like this in Paradise'—and he held his two fingers close together (Bukhari). True honor comes from caring for those whom society often forgets."
  },
  18: {
    "nor do you urge one another to feed the poor": "It is not enough to simply feed the poor oneself; a righteous society actively encourages this practice among its members. The verse criticizes those who not only fail to feed the needy but also do not motivate others to do so. This shows that social responsibility in Islam is communal, not just individual. When people see poverty and hunger yet remain silent, when they have the means to help but choose not to, and when they fail to create a culture of generosity, they have failed a fundamental test. The Prophet (ﷺ) said: 'He is not a believer whose stomach is filled while his neighbor goes hungry' (Bayhaqi)."
  },
  19: {
    "And you devour others' inheritance greedily": "This verse condemns those who consume inheritance unlawfully and greedily. 'Lamman' means gathering everything together without distinguishing between what is rightfully theirs and what belongs to others. In pre-Islamic Arabia, women and orphans were often denied their share of inheritance, and powerful relatives would seize everything for themselves. Some would even rush to consume the wealth of the deceased before the rightful heirs could claim it. Islam came to establish clear rules of inheritance that protect the rights of all family members. Taking more than one's rightful share or denying others their rights is a serious sin."
  },
  20: {
    "and love wealth fervently": "The root problem behind all these social failures is an excessive, overwhelming love of wealth. 'Hubban jamman' describes a love that is intense, all-consuming, and insatiable—a person who can never have enough and whose heart is attached to accumulating more and more. This obsession with wealth leads people to neglect orphans, ignore the hungry, steal inheritance, and forget their duties to Allah. Wealth itself is not evil; it is a tool that can be used for good or bad. The problem is when the love of wealth dominates the heart and becomes the primary motivation in life. The Prophet (ﷺ) said: 'Richness is not having many possessions, but richness is the richness of the soul' (Bukhari and Muslim)."
  },
  21: {
    "Enough! When the earth is entirely crushed over and over": "Allah again says 'Kalla!' (Enough! No!)—a strong rejection of their heedless behavior. Then He turns their attention to the Day of Judgment. The earth, which people walk upon with such confidence and upon which they build their empires, will be completely crushed and leveled. The repetition 'dakkan dakka' emphasizes the thoroughness of this destruction—the mountains will crumble, the buildings will fall, and the entire landscape will become flat. Everything that humans worked so hard to build, every structure they were proud of, will be reduced to nothing. This powerful imagery should shake anyone out of their complacency about the afterlife."
  },
  22: {
    "and your Lord comes to judge with angels, rank upon rank": "On that Day, Allah will come in a manner befitting His majesty to judge all of creation. We believe in this coming without asking 'how' because Allah's nature is beyond human comprehension. The angels will be arranged in rows upon rows—a scene of unimaginable order and grandeur. The Prophet (ﷺ) described that the angels will surround the earth in ranks. This verse creates a vivid picture of the Day of Judgment: the earth leveled, Allah present to judge, and countless angels witnessing. No one will be able to hide, escape, or argue. The case of every soul will be laid bare."
  },
  23: {
    "and Hell is brought forth on that Day": "Hell will be brought forward so that everyone can see it. The Prophet (ﷺ) said: 'Hell will be brought on that Day with seventy thousand reins, each rein held by seventy thousand angels' (Muslim). The sight of Hell will be so terrifying that it will cause people to finally wake up from their heedlessness.",
    "this is when every disbelieving person will remember their own sins. But what is the use of remembering then": "At that moment, the person who denied the truth, ignored the warnings, and wasted their life will suddenly remember everything—every missed prayer, every act of cruelty, every opportunity to do good that was wasted. But this remembrance comes too late. 'Anna lahudh-dhikra' asks: What good is remembering now? The time for action was in the worldly life. The time for repentance has passed. This is like a student who ignored their studies all year and only starts studying after the exam is over. Remembering then is useless."
  },
  24: {
    "They will cry, \"I wish I had sent forth something good for my true life\"": "This is the cry of regret that every negligent person will make on that Day. Notice that Allah calls the afterlife 'my true life' (hayati)—because the real, eternal life is the one that comes after death. The worldly life, which seemed so important, was actually temporary and fleeting. The person will wish they had invested in their real future by doing good deeds, giving charity, being kind, praying, and obeying Allah. But wishing cannot change anything at that point. This verse teaches us to prioritize: send forward good deeds now, while you still can, for the life that truly matters."
  },
  25: {
    "On that Day He will punish them severely, like no other": "The punishment that Allah will inflict on the disbelievers on that Day will be unlike any punishment in this world. No human authority, no government, no torturer in history has ever been able to punish as severely as Allah will punish those who rejected Him and oppressed others. This is because Allah's punishment is perfectly just and complete. The tyrants of this world—like Pharaoh, and the leaders of 'Ȃd and Thamûd—thought their power was great, but their punishments were nothing compared to what they will face in the Hereafter."
  },
  26: {
    "and bind them tightly, like no other": "The wrongdoers will be bound with chains and restraints that no one else can match. In this world, even the strongest chains can be broken, and prisoners can sometimes escape. But the binding of the Hereafter will be inescapable. Those who lived freely, doing whatever they pleased without regard for Allah's commands, will find themselves completely restrained. The fire will be around them, and they will have no freedom, no comfort, and no escape. This is the ultimate consequence of a life lived in disobedience to Allah."
  },
  27: {
    "Allah will say to the righteous, \"O tranquil soul!\"": "After describing the terrifying fate of the disbelievers, Allah now turns to the beautiful ending that awaits the believers. The 'nafs al-mutma'innah' is the soul that has found complete peace and contentment through faith in Allah. This soul is not disturbed by the trials of life or the temptations of the world because it is anchored in certainty about Allah's promises. It is the soul that remembers Allah often, as Allah says: 'Verily, in the remembrance of Allah do hearts find rest' (Quran 13:28). On the Day of Judgment, while others are in terror, this soul will be addressed with honor and love."
  },
  28: {
    "Return to your Lord, well pleased with Him and well pleasing to Him": "This is the most beautiful invitation a soul can receive. 'Return to your Lord'—come back to the One you always belonged to, the One you worshipped and loved throughout your life. 'Radiyah'—you are pleased with Allah, content with His decree, grateful for His blessings, and satisfied with His reward. 'Mardiyyah'—and Allah is pleased with you, satisfied with your faith and your deeds. This mutual pleasure between the servant and the Lord is the ultimate success. There is no greater achievement than earning Allah's pleasure. The Prophet (ﷺ) said that Allah will say to the people of Paradise: 'I shall bestow My pleasure upon you and shall never be displeased with you after this' (Bukhari and Muslim)."
  },
  29: {
    "So join My servants": "Allah honors this soul by including it among His special servants—the prophets, the truthful, the martyrs, and the righteous of all ages. After a lifetime of striving to be a true servant of Allah, the soul is now formally welcomed into this noble company. This is like being invited to join an elite group of the best human beings who ever lived. The loneliness that a believer might have felt in the world—when people mocked them for their faith or when they stood alone in doing what was right—is now replaced by the company of the greatest souls in history."
  },
  30: {
    "and enter My Paradise": "The final and ultimate reward: entry into Paradise, which Allah calls 'My Paradise' (jannati), emphasizing that it belongs to Him and that He personally grants entry to it. After all the tests of life, after patience in hardship and gratitude in ease, after caring for orphans and feeding the poor, after resisting the excessive love of wealth, after remaining steadfast in faith—the journey ends in eternal bliss. Paradise contains what no eye has seen, no ear has heard, and no human heart has imagined (Bukhari and Muslim). This is the destination that makes every sacrifice in this world worthwhile. The surah began with warnings and examples of destroyed nations, but it ends with this beautiful promise for those who believe and do good."
  }
};