var tafsirData_38 = {
  1: {
    "Ṣãd.": "This is one of the mysterious letters (Huruf Muqatta'at) that Allah uses to open certain chapters of the Quran. These letters remind us that the Quran, though composed of letters known to the Arabs, is a miraculous book that humans cannot replicate. It captures attention and signals that something important is about to be revealed.",
    "By the Quran, full of reminders!": "Allah takes an oath by the Quran itself, emphasizing its supreme importance and truth. The Quran is described as 'full of reminders' because it contains lessons, warnings, stories of past nations, guidance for life, and reminders of the Day of Judgment. It reminds humanity of their purpose, their Creator, and their ultimate return to Him. When Allah swears by something, it highlights its significance and the certainty of what follows."
  },
  2: {
    "˹This is the truth,˺ yet the disbelievers are ˹entrenched˺ in arrogance": "Despite the clear truth of the Quran and its powerful reminders, those who reject faith do so not because of any weakness in the message, but because of their own pride. Their arrogance blinds them from accepting the truth. They consider themselves too important or too wise to follow a message that challenges their lifestyle and beliefs. This is similar to how Pharaoh rejected Moses despite witnessing clear miracles—his pride prevented him from submitting.",
    "and opposition.": "Along with their arrogance, the disbelievers are in a state of constant opposition and hostility. They actively resist the message and the messenger, not out of genuine intellectual disagreement, but out of stubborn defiance. They oppose for the sake of opposing, creating division and conflict rather than seeking truth."
  },
  3: {
    "˹Imagine˺ how many peoples We destroyed before them,": "Allah reminds the disbelievers of Makkah that they are not the first to reject a messenger. Many powerful nations before them—such as the people of Noah, 'Ad, Thamud, and others—also rejected their prophets and were subsequently destroyed. This serves as a stern warning: if Allah destroyed those mighty civilizations, what makes these disbelievers think they are immune from the same fate?",
    "and they cried out when it was too late to escape.": "When Allah's punishment finally came upon those past nations, they desperately called out for help and mercy. They screamed and begged, but it was too late. The time for repentance had passed, and there was no escape from the divine punishment. This is like a student who wastes the entire semester and then cries on exam day—regret at that moment cannot undo months of neglect. The lesson here is to turn back to Allah while there is still time, before the door of repentance closes."
  },
  4: {
    "Now, the pagans are astonished that a warner has come to them from among themselves.": "The disbelievers of Makkah expressed surprise that a prophet came from their own people—someone they knew, someone who grew up among them, someone without royal lineage or extraordinary worldly status. They expected a messenger to be an angel or a king, not Muhammad, the orphan they had known all his life. Yet this was actually a mercy from Allah—sending a human messenger who could relate to them, speak their language, and serve as a living example. Their astonishment was misplaced and showed their misunderstanding of prophethood.",
    "And the disbelievers say, \"This is a magician, a total liar!": "Unable to explain the profound impact of the Quran and the Prophet's message, the disbelievers resorted to slander. They called him a magician—claiming his words were spells that enchanted people—and a liar, despite having called him 'Al-Amin' (the trustworthy) for forty years before his prophethood. This contradiction exposed their dishonesty; they knew he was truthful but rejected him out of arrogance and self-interest."
  },
  5: {
    "Has he reduced ˹all˺ the gods to One God?": "The pagan Arabs worshipped hundreds of idols, each supposedly controlling different aspects of life. When the Prophet proclaimed that there is only One God worthy of worship, they found this concept bewildering. They were so accustomed to their polytheistic system—inherited from their ancestors—that monotheism seemed radical and impossible to them. Yet this message of Tawhid (oneness of God) is the most logical and pure concept: one Creator, one Sustainer, one God.",
    "Indeed, this is something totally astonishing.\"": "They expressed shock at the idea of monotheism, calling it strange and astonishing. But their astonishment was misplaced. What is truly astonishing is worshipping stones and idols that cannot hear, see, or help anyone. Their reaction reveals how deeply rooted false beliefs can become when inherited through generations without critical thinking."
  },
  6: {
    "The chiefs among them went forth saying, \"Carry on,": "The wealthy and influential leaders of the Quraysh—men like Abu Jahl, Abu Lahab, and others—actively campaigned against the Prophet. Instead of listening to the message with open hearts, they encouraged their followers to continue in their old ways and ignore the new teachings. They walked away from gatherings where the Prophet spoke and urged others to do the same.",
    "and stand firm in devotion to your gods.": "They commanded their people to remain steadfast in idol worship, holding tightly to the religion of their forefathers. This shows how leaders can sometimes be the greatest obstacles to truth when their power and status are threatened by a new message. They feared losing their influence if people accepted Islam.",
    "Certainly this is just a scheme ˹for power˺.": "The chiefs accused the Prophet of having ulterior motives. They claimed he was preaching monotheism not because it was true, but because he wanted to gain power over them and become their leader. This accusation was baseless—the Prophet had rejected offers of wealth, kingship, and marriage to the most beautiful women if he would just stop preaching. His sincerity was evident, but the chiefs projected their own love of power onto him."
  },
  7: {
    "We have never heard of this in the previous faith.": "The disbelievers claimed that the concept of One God was unheard of in recent religious traditions. They referenced the distorted Christianity of their time or their ancestral practices, saying monotheism as preached by Muhammad was something new and unfamiliar. Yet they ignored that Abraham, the father they claimed to honor, was a strict monotheist who had smashed idols. Their claim showed their selective memory and willful ignorance.",
    "This is nothing but a fabrication.": "They dismissed the entire Quran and its message as a made-up story, an invention of Muhammad's own mind. This was their way of avoiding serious engagement with the message. Rather than examining the evidence and reflecting on the truth, they simply labeled it as lies—a defense mechanism that people still use today when confronted with uncomfortable truths."
  },
  8: {
    "Has the Reminder been revealed ˹only˺ to him out of ˹all of˺ us?\"": "The chiefs questioned why Muhammad, specifically, was chosen for prophethood. Why not one of the wealthy leaders from Makkah or Ta'if? This objection stemmed from their materialistic worldview—they assumed prophets should be the richest and most powerful. But Allah chooses His messengers based on their hearts, character, and readiness for the mission, not their worldly status. Allah says in another verse that He knows best where to place His message (6:124).",
    "In fact, they are ˹only˺ in doubt of My ˹revealed˺ Reminder.": "Allah exposes the real issue: their problem is not with the Prophet personally, but with the message itself. They are in doubt about divine revelation altogether. Their questions about why Muhammad was chosen are just smokescreens hiding their deeper skepticism about God, accountability, and the afterlife.",
    "In fact, ˹they do so because˺ they have not yet tasted My punishment.": "Allah reveals the true reason for their arrogance—they have not experienced divine punishment yet. If they had witnessed or tasted what befell previous nations, they would not be so casual in their rejection. Their comfort and safety have made them heedless. This is a warning that punishment may come when they least expect it."
  },
  9: {
    "Or ˹is it because˺ they possess the treasuries of the mercy of your Lord": "Allah asks a rhetorical question: Do these disbelievers control Allah's mercy? Do they decide who receives prophethood and guidance? Of course not. They have no authority over who Allah chooses to bless with His message. The treasuries of Allah's mercy—including guidance, prophethood, and all blessings—are in His hands alone.",
    "—the Almighty, the Giver ˹of all bounties˺.": "Allah is Al-Aziz (the Almighty, the One who cannot be overcome) and Al-Wahhab (the One who gives generously without being asked and without expectation of return). He gives freely to whom He wills. The disbelievers cannot dictate or limit His generosity. If Allah chose to honor Muhammad with prophethood, that is His prerogative, and no one can question His wisdom."
  },
  10: {
    "Or ˹is it because˺ the kingdom of the heavens and the earth and everything in between belongs to them?": "Another rhetorical question challenging the disbelievers' presumption. Do they own the heavens and earth? Do they control creation? If not, then who are they to question Allah's decisions? Their objection to Muhammad's prophethood is as absurd as an employee questioning the company owner's hiring decisions when the employee owns nothing.",
    "Let them then climb their way ˹to heaven, if their claim is true˺.": "If they think they have any authority or power over divine matters, let them climb up to the heavens and try to change Allah's decree. Let them ascend to where decisions are made and alter the divine plan. This is a challenge exposing their utter powerlessness. They cannot even control their own death, let alone challenge Allah's sovereignty. This statement silences their arrogance with the reality of their weakness."
  },
  11: {
    "This is just another ˹enemy˺ force bound for defeat out there.": "Allah dismisses the coalition of disbelievers opposing the Prophet as just another group in a long line of forces that opposed divine messengers. Despite their numbers, wealth, and apparent strength, they are destined for defeat. This verse was revealed when the Muslims were weak and persecuted in Makkah, yet Allah assured them of ultimate victory. History proved this true—within years, the same people who persecuted Muslims were defeated, and Islam spread throughout Arabia and beyond."
  },
  12: {
    "Before them, the people of Noah denied ˹the truth˺,": "The people of Noah rejected their prophet for 950 years of his preaching. Despite his patience and continuous calling, only a handful believed. Eventually, Allah destroyed them with a great flood, saving only Noah and the believers in the ark. Their denial serves as a timeless warning.",
    "as did 'Âd,": "The people of 'Ad were known for their physical strength and impressive buildings. They rejected Prophet Hud and were destroyed by a furious wind that lasted for days, leaving nothing standing. Their power could not save them from Allah.",
    "Pharaoh of the mighty structures,": "Pharaoh was one of the most powerful rulers in history, commanding vast armies and building magnificent monuments and pyramids (the 'structures' or 'stakes' refer to the pegs of his grand tents or the pyramids themselves). Despite his might, he drowned in the sea while chasing Moses and the Israelites. His body was preserved as a sign for future generations."
  },
  13: {
    "Thamûd,": "The people of Thamud carved homes out of mountains, thinking their dwellings made them invincible. They rejected Prophet Salih and killed the miraculous she-camel Allah sent as a sign. A terrible blast destroyed them all.",
    "the people of Lot,": "The people of Lot were destroyed for their immorality and rejection of their prophet. Allah rained upon them stones of baked clay and turned their cities upside down. Their fate remains a stark warning about moral corruption.",
    "and the residents of the Forest.": "These were the people of Madyan, also known as the companions of the thicket (a dense forest). They rejected Prophet Shu'ayb and cheated in their business dealings. Allah destroyed them with a punishment from above—some scholars say it was extreme heat followed by a cloud that rained fire.",
    "These were ˹all˺ enemy forces.": "All these nations formed coalitions against their prophets, just as the Quraysh were doing against Muhammad. They were all enemy forces of truth, and they all met the same end—destruction. The pattern is clear and consistent throughout history."
  },
  14: {
    "Each rejected their messenger,": "Every single one of these nations denied and rejected the prophet sent to them. The messengers came with clear signs and sincere advice, but the people chose disbelief.",
    "so My punishment was justified.": "Because they rejected the truth after it was made clear to them, Allah's punishment became inevitable and justified. This is divine justice—warning comes first, then punishment for those who refuse to heed. Allah never punishes a people without first sending them a messenger with clear guidance (17:15)."
  },
  15: {
    "These ˹pagans˺ are awaiting nothing but a single Blast": "The disbelievers of Makkah, like those before them, are simply waiting for the inevitable punishment. It will come in the form of a single Blast—a reference to either a worldly punishment or the trumpet blast of the Day of Judgment. Either way, their time is limited.",
    "that cannot be stopped.": "When this Blast comes, there will be no pause, no delay, no second chance. It will be sudden and unstoppable. This emphasizes the urgency of accepting the truth while there is still time. Unlike worldly events that can sometimes be postponed or avoided, Allah's decree is final."
  },
  16: {
    "They say ˹mockingly˺, \"Our Lord! Hasten for us our share ˹of the punishment˺ before the Day of Reckoning.\"": "In their arrogance and mockery, the disbelievers sarcastically asked for their punishment to come immediately, before the Day of Judgment. They said this to ridicule the Prophet's warnings, not believing that any punishment would actually come. This is like someone mocking a fire alarm, saying 'bring on the fire'—foolish bravado that will turn to regret when the flames actually appear. Their mockery only added to their sins and made their eventual punishment more severe."
  },
  17: {
    "Be patient ˹O Prophet˺ with what they say.": "After mentioning the mockery and rejection of the disbelievers, Allah consoles Prophet Muhammad by commanding him to be patient. Patience (sabr) is one of the greatest qualities a believer can have, especially when facing opposition and insults. The Prophet is reminded that he is not alone—other prophets faced similar trials.",
    "And remember Our servant, David, the man of strength.": "Allah directs the Prophet's attention to David (Dawud) as a source of comfort and inspiration. David is described as 'Our servant'—a title of honor in the Quran. He was 'the man of strength' (literally 'possessor of hands'), meaning he had great physical strength, strength in worship, and strength in implementing Allah's commands. He was a warrior, a king, and a devoted worshipper.",
    "Indeed, he ˹constantly˺ turned ˹to Allah˺.": "David was 'awwab'—one who constantly turned back to Allah in repentance, remembrance, and devotion. Despite being a powerful king, he never let his status make him arrogant. He would fast every other day and spend much of his night in prayer. The Prophet Muhammad said that the most beloved fasting to Allah is the fasting of David, and the most beloved prayer is the prayer of David, who would sleep half the night, pray for a third, and then sleep for a sixth (Bukhari)."
  },
  18: {
    "We truly subjected the mountains to hymn ˹Our praises˺ along with him": "Allah gave David an extraordinary miracle: the mountains would glorify Allah along with him when he recited his psalms. This was not mere metaphor—the mountains literally joined in his praise of Allah. David had such a beautiful voice that creation itself responded to his worship. This shows that all of creation glorifies Allah, though we may not perceive it (17:44).",
    "in the evening and after sunrise.": "These times—evening and the time after sunrise—are blessed times for worship. David would engage in remembrance of Allah during these hours, and the mountains would echo his glorification. This teaches us the importance of consistent worship at regular times, especially during the spiritually significant parts of the day."
  },
  19: {
    "And ˹We subjected˺ the birds, flocking together.": "Not only the mountains, but also the birds were subjected to David. They would gather around him in flocks when he praised Allah. Imagine the scene: a king reciting the praises of Allah, mountains echoing his hymns, and birds assembling to join in the glorification. This was a kingdom unlike any other—built on worship and submission to Allah.",
    "All turned to him ˹echoing his hymns˺.": "Each of the birds was 'awwab'—returning to David, responding to his worship, joining in the praise of Allah. Some scholars say this means each bird turned to Allah in its own way of glorification. The harmony between David, the mountains, and the birds represents the perfect state of existence: all creation unified in the worship of their Creator."
  },
  20: {
    "We strengthened his kingship,": "Allah made David's kingdom strong and stable. He was given military power, political authority, and the loyalty of his people. His reign was one of justice and prosperity. Allah strengthens those who are devoted to Him—this is a promise that applies to believers in every age.",
    "and gave him wisdom": "Beyond worldly power, Allah blessed David with wisdom (hikmah)—the ability to understand the truth of matters, to make right decisions, and to guide his people properly. Wisdom is more valuable than wealth or power because it allows one to use those blessings correctly.",
    "and sound judgment.": "David was given 'fasl al-khitab'—decisive speech or sound judgment. This means he could settle disputes justly and speak in a way that clearly distinguished truth from falsehood. When he judged between people, his verdicts were fair and final. This quality is essential for any leader and is a gift from Allah."
  },
  21: {
    "Has the story of the two plaintiffs, who scaled the ˹wall of David's˺ sanctuary, reached you ˹O Prophet˺?": "Allah now narrates an important story to Prophet Muhammad about a trial that David faced. The 'sanctuary' (mihrab) was David's private chamber where he would worship Allah in seclusion. Two individuals climbed over the walls to reach him—an unusual and alarming entrance that startled David. This story teaches profound lessons about self-reflection and justice."
  },
  22: {
    "When they came into David's presence, he was startled by them.": "David was alarmed when these two men suddenly appeared in his private quarters. As a king, he was protected by guards, so this unexpected intrusion was shocking. His human reaction of fear shows that even prophets experience normal human emotions.",
    "They said, \"Have no fear.": "The two men quickly reassured David that they meant no harm. They had not come to hurt him but to seek his judgment.",
    "˹We are merely˺ two in a dispute: one of us has wronged the other.": "They explained that they were disputants—two parties in a conflict, where one had wronged the other. They needed David, known for his wisdom and just judgment, to settle their matter.",
    "So judge between us with truth—do not go beyond ˹it˺—and guide us to the right way.": "They asked David to judge with complete fairness, without any excess or bias, and to guide them to what was right. This request shows the proper attitude when seeking judgment: wanting truth and justice, not just victory for oneself."
  },
  23: {
    "This is my brother.": "One of the plaintiffs began presenting his case, referring to the other as his 'brother'—either a literal brother or a metaphor indicating they were close associates or fellow community members.",
    "He has ninety-nine sheep while I have ˹only˺ one.": "He explained the gross inequality between them: the other man owned ninety-nine sheep, representing great wealth, while he himself had only a single sheep. The contrast highlights the greed of someone who has so much yet wants even more.",
    "˹Still˺ he asked me to give it up to him, overwhelming me with ˹his˺ argument.": "Despite having ninety-nine sheep, the wealthy brother demanded the poor brother's only sheep. He used his eloquence and power of argument to pressure his brother into giving up his sole possession. This represents how the powerful sometimes use their influence to take from the weak, justifying their greed with clever words."
  },
  24: {
    "David ˹eventually˺ ruled, \"He has definitely wronged you in demanding ˹to add˺ your sheep to his.": "David immediately recognized the injustice and ruled in favor of the poor brother. Demanding someone's only possession when you already have ninety-nine is clear oppression. David's quick judgment shows his natural sense of justice.",
    "And certainly many partners wrong each other,": "David made a general observation that among business partners, associates, and even family members, many wrong each other. Greed and selfishness often damage relationships between people who should be supporting one another.",
    "except those who believe and do good—but how few are they!\"": "The exception to this pattern of wrongdoing are those who have genuine faith and act righteously. Their belief in Allah and the Day of Judgment prevents them from wronging others. However, David sadly noted that such people are few. This remains true today—true justice and fairness are rare qualities.",
    "Then David realized that We had tested him": "At this moment, David had a profound realization: this entire scenario was a test from Allah. The story was a mirror reflecting something back to David about his own life. Scholars have different opinions about what exactly David realized, but the important point is that David understood that Allah was teaching him something through this incident.",
    "so he asked for his Lord's forgiveness, fell down in prostration, and turned ˹to Him in repentance˺.": "Upon this realization, David's immediate response was to seek forgiveness from Allah. He fell into prostration (sujood)—the position of ultimate humility before Allah—and turned to Him in sincere repentance. This shows the character of a true servant of Allah: when reminded of a shortcoming, they do not defend themselves or make excuses but immediately return to Allah in humility. This verse is a verse of prostration (sajdah), and Muslims prostrate when reciting or hearing it."
  },
  25: {
    "So We forgave that for him.": "Allah, in His mercy, forgave David completely. Whatever the matter was, it was erased. This shows that sincere repentance wipes away sins. When David turned to Allah with a humble heart, Allah responded with forgiveness. This is Allah's way—He loves the repentant and forgives those who turn to Him.",
    "And he will indeed have ˹a status of˺ closeness to Us": "Not only was David forgiven, but he was also promised a special closeness to Allah in the Hereafter. His status with Allah was elevated because of his sincere repentance. This teaches us that turning back to Allah after a mistake can actually increase our rank with Him.",
    "and an honourable destination!": "David's final abode will be one of honor—Paradise. His beautiful return to Allah and his lifetime of worship, justice, and devotion earned him an honorable place in the Hereafter. This is the ultimate success."
  },
  26: {
    "˹We instructed him:˺ \"O David! We have surely made you an authority in the land,": "Allah reminded David of the great responsibility He had given him: authority and leadership over the land. Being a ruler or a person of authority is an amanah (trust) from Allah, not a privilege for personal gain. David was not made a king for his own glory but to serve Allah's purpose on earth.",
    "so judge between people with truth.": "With authority comes the responsibility of justice. David was commanded to judge between people with absolute truth and fairness, regardless of who was involved—rich or poor, friend or foe. Justice must be blind to everything except the truth.",
    "And do not follow ˹your˺ desires": "This is the greatest danger for anyone in power: following personal desires, biases, or inclinations instead of the truth. Desires can cloud judgment and lead to injustice. David was warned—and through him, all those in positions of authority—to guard against letting their own wishes influence their decisions.",
    "or they will lead you astray from Allah's Way.": "Following desires is a path that leads away from Allah. What seems appealing in the moment can take a person far from guidance. This applies to everyone, not just rulers. Whenever we prioritize our desires over Allah's commands, we risk going astray.",
    "Surely those who go astray from Allah's Way will suffer a severe punishment": "The consequence of straying from Allah's path is severe punishment. This is not a minor matter—deviation from truth leads to serious consequences in this life and the next.",
    "for neglecting the Day of Reckoning.": "The root cause of going astray is forgetting or neglecting the Day of Judgment. When people remember that they will stand before Allah and account for every decision, they judge justly and resist their desires. Forgetting this reality leads to corruption and injustice."
  },
  27: {
    "We have not created the heavens and earth and everything in between without purpose": "Allah declares that creation is not meaningless or random. The heavens, the earth, and everything between them—every star, every mountain, every creature—was created with purpose and wisdom. There is design, meaning, and intention behind all existence. Life is not a cosmic accident; it is a deliberate act of the All-Wise Creator.",
    "—as the disbelievers think.": "Those who reject faith often believe that existence is purposeless—that we live, die, and that's the end. This worldview leads to moral chaos because if there is no purpose, there are no consequences, and nothing ultimately matters. But this is a false assumption that stems from disbelief.",
    "So woe to the disbelievers because of the Fire!": "Allah warns of the terrible fate awaiting those who deny purpose and accountability. 'Woe' (wayl) is a word expressing severe punishment and destruction. The Fire of Hell awaits those who reject Allah, deny the purpose of creation, and live as if there are no consequences. This is a stern warning to wake people up from heedlessness."
  },
  28: {
    "Or should We treat those who believe and do good like those who make mischief throughout the land?": "This rhetorical question challenges the notion that there is no accountability. Should a person who spends their life worshipping Allah, helping others, and doing good be treated the same as someone who spreads corruption, oppression, and evil? Basic human justice says no—and divine justice is infinitely more perfect. If there were no Day of Judgment, the oppressors and the righteous would have the same fate, which would be the greatest injustice.",
    "Or should We treat the righteous like the wicked?": "Allah asks: Is it fair to treat the God-conscious people (muttaqeen) the same as the sinful and rebellious (fujjar)? This question answers itself—of course not. The existence of the Day of Judgment is necessary for justice to be complete. In this world, sometimes the wicked prosper and the righteous suffer. But there must be a Day when accounts are settled, when every good deed is rewarded and every wrong is addressed. This is the Day of Reckoning, and it is coming."
  },
  29: {
    "˹This is˺ a blessed Book which We have revealed to you ˹O Prophet˺": "Allah describes the Quran as a 'blessed Book'—meaning it is filled with goodness, benefits, and divine guidance that never runs out. Every time you read it, you find new meanings and blessings. It was revealed to Prophet Muhammad as a mercy for all of humanity. Unlike any other book, its blessings extend to those who recite it, listen to it, memorize it, teach it, and act upon it.",
    "so that they may contemplate its verses,": "The purpose of revealing the Quran is not just for recitation without understanding, but for deep contemplation (tadabbur). This means reflecting on the meanings, pondering the lessons, and allowing the verses to penetrate the heart. Reading the Quran without reflection is like receiving a letter from someone you love and never opening it. Allah wants us to think deeply about His words, understand them, and apply them to our lives.",
    "and people of reason may be mindful.": "Those who have sound intellect and understanding—'people of reason' (ulul albab)—will take heed and be reminded. The Quran speaks to the mind and the heart together. Those who use their intellect properly will recognize the truth of the Quran and allow it to change them. This verse encourages us to engage our minds when reading the Quran, not to read it passively but actively seek its guidance."
  },
  30: {
    "And We blessed David with Solomon": "Allah granted Prophet David a tremendous blessing: his son Solomon (Sulayman). This was not just a biological gift but a continuation of prophethood in his family. Solomon would become one of the greatest prophets and kings in history, inheriting his father's wisdom and kingdom.",
    "—what an excellent servant ˹he was˺!": "Allah Himself testifies to Solomon's excellence as a servant. This is the highest praise—to be called an 'excellent servant' by the Lord of the worlds. Solomon, despite having unprecedented power and wealth, remained humble and devoted to Allah. His servitude to Allah defined him more than his kingship.",
    "Indeed, he ˹constantly˺ turned ˹to Allah˺.": "Like his father David, Solomon was 'awwab'—one who constantly returned to Allah in repentance, remembrance, and worship. No matter how busy he was with his kingdom, he always turned his heart back to Allah. This is a quality of the greatest servants of Allah: they never let worldly responsibilities distract them from their Creator."
  },
  31: {
    "˹Remember˺ when the well-trained, swift horses were paraded before him in the evening.": "Allah recalls a specific incident involving Solomon and his horses. These were not ordinary horses—they were magnificent, well-trained steeds that stood still when at rest (safinat) and were incredibly fast when running (jiyad). In Solomon's time, horses were essential for both warfare and displaying royal power. One evening, these beautiful horses were presented to Solomon for his review and admiration."
  },
  32: {
    "He then proclaimed, \"I am truly in love with ˹these˺ fine things out of remembrance for Allah,\"": "Solomon declared that his love for these beautiful horses was connected to his remembrance of Allah. He appreciated them not for worldly pride or vanity, but because they were blessings from Allah and tools for jihad (striving in Allah's cause). This shows the mindset of a true believer: even when enjoying worldly blessings, they connect everything back to Allah. Solomon saw these horses and thought of the Giver, not just the gift.",
    "until they went out of sight.": "Solomon was so absorbed in admiring the horses and connecting this appreciation to Allah that the parade continued until the horses disappeared from view (behind the horizon or a barrier). Some scholars say this refers to the sun setting (the horses of time, metaphorically), while others take it literally as the horses going out of sight. Either way, Solomon was deeply engaged in this moment of reflection and gratitude."
  },
  33: {
    "˹He ordered,˺ \"Bring them back to me!\"": "Solomon commanded that the horses be brought back to him. He wanted to see them again—not out of excessive attachment, but to continue appreciating Allah's blessings and perhaps to personally care for them.",
    "Then he began to rub down their legs and necks.": "Solomon personally began stroking and rubbing down the horses' legs and necks. This was an act of care and affection for the animals. Some scholars say he was grooming them as an act of kindness and appreciation. This shows Solomon's humility—despite being the greatest king of his time, he personally tended to his animals. It also shows the Islamic principle of caring for animals and treating them well. The Prophet Muhammad said that a woman entered Hell for mistreating a cat, while another was forgiven for giving water to a thirsty dog (Bukhari). Solomon's care for his horses reflects this same ethic of compassion."
  },
  34: {
    "And indeed, We tested Solomon,": "Allah tested Solomon, as He tests all His servants. Tests are not punishments but opportunities for growth, purification, and demonstration of faith. Even the greatest prophets were tested to elevate their ranks and serve as examples for others.",
    "placing a ˹deformed˺ body on his throne,": "The exact nature of this test is described metaphorically. A 'body' (jasad) was placed on Solomon's throne. Scholars have various interpretations: some say Solomon temporarily lost his kingdom or authority; others mention traditions about a jinn or an imposter. The point is that Solomon experienced a significant trial that shook him and made him realize his dependence on Allah. Whatever he had was from Allah and could be taken away in an instant.",
    "then he turned ˹to Allah in repentance˺.": "After this trial, Solomon immediately turned back to Allah. This is the mark of the righteous—when tested, they don't complain or despair but return to their Lord seeking forgiveness and guidance. Solomon's response to the trial was repentance, not arrogance or denial."
  },
  35: {
    "He prayed, \"My Lord! Forgive me,": "Solomon began his supplication by asking for forgiveness. Even though he was a prophet, he sought Allah's pardon. This teaches us that no matter how righteous we are, we should always seek forgiveness. The Prophet Muhammad himself sought forgiveness more than seventy times a day.",
    "and grant me an authority that will never be matched by anyone after me.": "Solomon asked for a unique kingdom—one that no one else would ever have after him. This was not a request born of arrogance but of aspiration to serve Allah in a way no one else could. He wanted to use this unparalleled authority to establish justice, worship Allah, and demonstrate divine power on earth. Allah granted this request, giving Solomon control over the wind, the jinn, and other miracles that no other human being has ever possessed.",
    "You are indeed the Giver ˹of all bounties˺.": "Solomon acknowledged that everything comes from Allah, who is Al-Wahhab—the Giver who bestows gifts freely and generously. By ending his prayer this way, Solomon showed his understanding that he was asking the One who gives without limit, and that whatever he received was purely from Allah's grace, not his own merit."
  },
  36: {
    "So We subjected to him the wind, blowing gently at his command": "Allah granted Solomon control over the wind. It would blow gently and obediently according to Solomon's commands. This was a miraculous power given to no one else. The wind could carry Solomon's throne and his armies across vast distances in short periods of time.",
    "to wherever he pleased.": "The wind would take Solomon wherever he wished to go. A journey of a month could be covered in a morning or an evening (as mentioned in other verses). This demonstrates the incredible kingdom Allah gave Solomon—one that transcended normal human limitations. Yet Solomon used this power for Allah's cause, not for personal amusement."
  },
  37: {
    "And ˹We subjected to him˺ every builder and diver of the jinn,": "Allah also gave Solomon authority over the jinn. Among them were builders who constructed magnificent structures, palaces, and places of worship for Solomon. Others were divers who would plunge into the seas to retrieve pearls, precious stones, and other treasures. The jinn, who are typically invisible and powerful beings, were made subservient to Solomon—working under his command by Allah's permission."
  },
  38: {
    "and others bound together in chains.": "Some of the jinn—particularly the rebellious or dangerous ones—were bound in chains under Solomon's authority. These were restrained and could not cause harm or mischief. This shows that Solomon's kingdom included not just loyal servants but also the control and containment of evil forces. He maintained order over both the obedient and the rebellious."
  },
  39: {
    "˹Allah said,˺ \"This is Our gift,": "Allah declared that everything Solomon possessed—the wind, the jinn, the kingdom—was a gift from Him. Solomon did not earn or create this power; it was bestowed upon him by divine grace.",
    "so give or withhold ˹as you wish˺,": "Allah gave Solomon complete discretion over how to use his gifts. He could give freely to others or withhold as he saw fit. He could release the jinn or keep them bound, grant favors or hold back. This was an extraordinary level of trust and authority given to Solomon.",
    "never to be called to account.": "Solomon would not be questioned about how he used this authority. This does not mean he was free from moral responsibility, but that Allah trusted him completely in managing these affairs. Solomon had proven himself to be just and God-fearing, so he was given this freedom. This is a unique honor that shows Allah's pleasure with Solomon's character and devotion."
  },
  40: {
    "And he will indeed have ˹a status of˺ closeness to Us": "Despite all his worldly power and kingdom, Solomon's greatest reward is his closeness to Allah in the Hereafter. Worldly success means nothing if it doesn't lead to nearness to Allah. Solomon achieved both—he had an unmatched kingdom in this world and a special status with Allah in the next.",
    "and an honourable destination!": "Solomon's final destination is Paradise—an honorable return to his Lord. This confirms that all his power and wealth did not corrupt him; he remained a devoted servant of Allah throughout his life. His story teaches us that it is possible to have worldly success while maintaining spiritual excellence, as long as one keeps their heart attached to Allah."
  },
  41: {
    "And remember Our servant Job,": "Allah now turns our attention to another remarkable prophet: Job (Ayyub). He is called 'Our servant'—a title of honor indicating his devotion to Allah. Job's story is one of the most powerful examples of patience in human history.",
    "when he cried out to his Lord,": "After enduring unimaginable trials, Job finally called out to Allah. He did not complain to people or lose faith, but directed his plea to the only One who could help him. This teaches us that when we are afflicted, our first and primary recourse should be to Allah.",
    "\"Satan has afflicted me with distress and suffering.\"": "Job acknowledged that Satan was behind his suffering—causing him physical illness, loss of wealth, and death of his children. However, Job understood that Satan could only afflict him with Allah's permission, and that there was wisdom in his trial. Job's statement is not a complaint but a humble acknowledgment of his situation while seeking Allah's help. Even in his lowest moment, Job did not curse his fate or blame Allah; he simply asked for relief."
  },
  42: {
    "˹We responded,˺ \"Stomp your foot:": "Allah answered Job's prayer with a simple command: strike the ground with your foot. After years of patient suffering, relief came through this single act of obedience. This shows that Allah's solutions often come in unexpected ways, and that following His commands—even when they seem simple—brings miraculous results.",
    "˹now˺ here is a cool ˹and refreshing˺ spring for washing and drinking.\"": "When Job stomped his foot, a miraculous spring gushed forth from the earth. This water was cool and refreshing—perfect for washing his diseased body and drinking to restore his health. Job bathed in it and drank from it, and Allah healed him completely. What seemed like an impossible situation was resolved instantly by Allah's command. This teaches us to never lose hope, no matter how long the trial lasts, for Allah's relief can come in the blink of an eye."
  },
  43: {
    "And We gave him back his family, twice as many,": "Allah not only healed Job but also restored his family. Some scholars say his deceased children were returned to him (in the Hereafter or through new children), and he was given twice as many as before. His wealth was also restored and multiplied. Everything Satan had taken was returned manifold.",
    "as a mercy from Us": "This restoration was an act of divine mercy. Job had remained patient through his trial, and Allah rewarded him abundantly. Mercy from Allah is not earned—it is a gift that Allah bestows upon His grateful servants.",
    "and a lesson for people of reason.": "Job's story is preserved as a reminder for those who reflect. People of reason learn from his example that patience in hardship leads to relief, that trials are temporary while rewards are eternal, and that Allah never abandons those who remain faithful to Him. When you face difficulty, remember Job—if he could remain patient through the loss of everything, you too can endure your trials with faith."
  },
  44: {
    "˹And We said to him,˺ \"Take in your hand a bundle of grass, and strike ˹your wife˺ with it, and do not break your oath.\"": "During his illness, Job had made an oath to discipline his wife (some say she had made a minor mistake or shown momentary weakness during his trial). As a prophet, breaking an oath was not an option. Allah, in His mercy, provided a solution: Job was told to take a bundle of grass or twigs and lightly strike with it. This fulfilled the letter of the oath without causing any real harm. This shows Allah's wisdom in providing ways out of difficult situations while maintaining principles. It also demonstrates Islam's emphasis on mercy and finding the gentlest solution.",
    "We truly found him patient.": "Allah Himself testifies that Job was patient (sabir). This divine certification of Job's patience is the highest endorsement possible. Job endured years of suffering—losing his health, wealth, children, and social standing—yet he never complained against Allah or lost faith.",
    "What an excellent servant ˹he was˺!": "For the third time in this surah (after David and Solomon), Allah praises a prophet as an 'excellent servant.' This title emphasizes that the highest achievement is not worldly success but being a true servant of Allah.",
    "Indeed, he ˹constantly˺ turned ˹to Allah˺.": "Like David and Solomon before him, Job is described as 'awwab'—one who constantly returns to Allah. Whether in ease or hardship, Job's heart was always oriented toward his Lord. This quality of returning to Allah repeatedly is what made these prophets excellent in Allah's sight."
  },
  45: {
    "And remember Our servants: Abraham, Isaac, and Jacob": "Allah commands us to remember these three great prophets—a grandfather, son, and grandson who formed a blessed lineage. Abraham (Ibrahim) is the father of the prophets, the one who built the Kaaba and was tested with the sacrifice of his son. Isaac (Ishaq) was his son through Sarah, and Jacob (Yaqub), also known as Israel, was Isaac's son and the father of the twelve tribes.",
    "—the men of strength and insight.": "These prophets are described as possessing 'ayd' (strength/hands) and 'absar' (insight/vision). 'Hands' symbolizes their strength in worship, action, and implementation of Allah's commands. 'Vision' represents their spiritual insight, deep understanding, and ability to see the truth clearly. They were not just strong physically or intellectually—they combined power with wisdom, action with understanding. This is the ideal balance for a believer."
  },
  46: {
    "We truly chose them for the honour of proclaiming the Hereafter.": "Allah selected these prophets and purified them with a special quality: they were devoted to reminding people about the Hereafter. While others were absorbed in worldly matters, these prophets kept their focus—and directed others' focus—on the eternal home. Their primary message was about accountability, the Day of Judgment, and the lasting consequences of our choices. This focus on the Hereafter purified them from worldly attachments and made their call sincere and powerful."
  },
  47: {
    "And in Our sight they are truly among the chosen and the finest.": "Allah affirms the exalted status of Abraham, Isaac, and Jacob. They are 'mustafayn' (chosen/selected by Allah) and 'akhyar' (the finest/best of humanity). Being chosen by Allah is the greatest honor any human can receive. These prophets represent the cream of humanity—role models whose lives we should study and whose qualities we should strive to embody."
  },
  48: {
    "Also remember Ishmael,": "Ishmael (Ismail) was the son of Abraham through Hagar. He is the father of the Arab lineage and an ancestor of Prophet Muhammad. He was the son whom Abraham was commanded to sacrifice, and he submitted willingly to Allah's command. He helped his father build the Kaaba and was known for his patience and devotion.",
    "Elisha,": "Elisha (Al-Yasa') was a prophet from the Children of Israel, mentioned briefly in the Quran. He succeeded Prophet Elijah and continued the mission of calling people to Allah. Though less is known about him in Islamic sources, his mention here confirms his status as one of the righteous prophets.",
    "and Ⱬul-Kifl.": "Dhul-Kifl is a prophet whose identity is debated among scholars. Some say he was Ezekiel, others say he was a righteous man who took responsibility (kifl) for his people. The name means 'the one of the portion/responsibility,' suggesting someone who fulfilled his duties completely. Regardless of his exact identity, he is confirmed as one of the righteous.",
    "All are among the best.": "Allah confirms that all these prophets—Ishmael, Elisha, and Dhul-Kifl—are among the finest of humanity (akhyar). They represent excellence in faith, character, and devotion to Allah. Mentioning them together emphasizes the unity of the prophetic message and the consistent standard of righteousness across all messengers."
  },
  49: {
    "This is ˹all˺ a reminder.": "Everything mentioned so far—the stories of the prophets, the trials they faced, and the rewards they received—serves as a reminder for humanity. These are not mere historical accounts but lessons meant to guide us, inspire us, and help us stay on the straight path.",
    "And the righteous will certainly have an honourable destination:": "After reminding us of these examples, Allah turns to the eternal reward awaiting the righteous (muttaqeen—those who are conscious of Allah and guard themselves against sin). Their destination is described as 'husna ma'ab'—a beautiful, honorable return. This is Paradise, and what follows describes some of its blessings."
  },
  50: {
    "the Gardens of Eternity,": "The righteous will enter 'Jannaat Adn'—Gardens of Eternity or Perpetual Residence. These are gardens where believers will live forever, never facing death, illness, or expulsion. The word 'Adn' implies permanent settlement—a true home where one belongs forever.",
    "whose gates will be open for them.": "The gates of Paradise will be opened wide for the righteous. They will not have to knock, wait, or struggle to enter. The doors will already be open in welcome, and angels will greet them saying, 'Peace be upon you! You have done well, so enter to abide eternally' (39:73). This is the honor of those who lived righteously—Paradise eagerly awaits them."
  },
  51: {
    "There they will recline,": "The inhabitants of Paradise will be in a state of complete relaxation and comfort. Reclining indicates luxury, rest, and the absence of any need to work or struggle. All toil is over; this is the time of enjoyment.",
    "calling for abundant fruit and drink.": "Whatever the people of Paradise desire will be brought to them. They will simply call for fruit—abundant varieties beyond imagination—and drinks of pure, delicious beverages. Unlike this world where we work for our food, in Paradise every desire is fulfilled effortlessly. The Prophet Muhammad said that in Paradise there is what no eye has seen, no ear has heard, and no human heart has imagined (Bukhari)."
  },
  52: {
    "And with them will be maidens of modest gaze": "Among the blessings of Paradise for the righteous men are pure companions described as 'qasirat al-tarf'—those who lower their gaze and look only at their husbands, devoted and modest. These are the Hur, created by Allah as perfect companions in Paradise.",
    "and equal age.": "These companions will be of similar age (atrab), meaning they will be youthful and well-matched with the inhabitants of Paradise. In Paradise, there is no aging, no decline—everyone remains in their prime forever. This description emphasizes harmony, compatibility, and eternal youth among the people of Paradise."
  },
  53: {
    "This is what you are promised for the Day of Reckoning.": "Allah confirms that these blessings—the gardens, the open gates, the reclining, the fruits, the drinks, and the companions—are the promise awaiting believers on the Day of Judgment. This is not fantasy or wishful thinking; it is Allah's promise, and Allah never breaks His promise. The Day of Reckoning, which the disbelievers mocked, will be the day when these rewards become reality for those who believed and lived righteously."
  },
  54: {
    "This is indeed Our provision": "Allah calls these blessings 'Our provision'—rizq that comes directly from the Lord of the worlds. In this life, our provision is limited and temporary. But in Paradise, the provision comes from Allah's infinite treasuries.",
    "that will never end.": "Unlike worldly pleasures that are depleted, the pleasures of Paradise are eternal and inexhaustible. The fruits never run out, the drinks are never finished, the joy never fades. This endless provision is one of the greatest blessings of Paradise—there is no fear of loss, no anxiety about the future, only eternal abundance and contentment."
  },
  55: {
    "That is that.": "After describing the beautiful reward of the righteous, Allah transitions with this phrase to indicate a shift in topic. The blessings of Paradise have been mentioned; now comes the contrasting fate of those who rejected the truth.",
    "And the transgressors will certainly have the worst destination:": "The 'tagheen' (transgressors/those who exceeded all bounds) will have 'sharr ma'ab'—the worst possible destination. These are people who not only disbelieved but actively transgressed, oppressed others, and rebelled against Allah. Their destination is the opposite of the honorable return of the righteous."
  },
  56: {
    "Hell, where they will burn.": "The destination of the transgressors is Jahannam (Hell), where they will be burned. The word 'yaslawnaha' means they will enter it and be exposed to its heat and flames. This is not a metaphor but a terrifying reality that awaits those who rejected Allah and His messengers.",
    "What an evil place to rest!": "In bitter irony, Hell is called their 'mihad' (resting place/bed). While the righteous recline in comfort in Paradise, the transgressors will have Hell as their resting place. What an evil, terrible abode! The contrast between the two destinations could not be starker—eternal comfort versus eternal torment."
  },
  57: {
    "Let them then taste this: boiling water": "The inhabitants of Hell will be given 'hameem'—water so hot it is boiling and scalding. When they become desperate from thirst, this is what they will drink. It will burn their insides, yet they will have no choice but to drink it. This is a horrifying contrast to the pure, refreshing drinks of Paradise.",
    "and ˹oozing˺ pus,": "They will also taste 'ghassaq'—which scholars describe as the pus, blood, and filthy discharge that flows from the wounds of the inhabitants of Hell. The exact nature is known only to Allah, but it represents the most disgusting and repulsive drink imaginable. This is their provision, in contrast to the abundant fruits and pure drinks of the believers."
  },
  58: {
    "and other torments of the same sort!": "The punishment does not end with boiling water and pus. There are other torments 'of the same sort'—pairs and varieties of punishment that match these in their severity. The Arabic word 'azwaj' (pairs/types) indicates that the punishments come in multiple forms and categories, each one terrible in its own way. Allah does not detail all of them, but the suggestion is that Hell contains horrors beyond human imagination. This is meant as a severe warning to turn away from transgression while there is still time."
  },
  59: {
    "˹The misleaders will say to one another,˺ \"Here is a crowd ˹of followers˺ being thrown in with us.": "When the leaders of disbelief—those who misguided others—are already in Hell, they will see groups of their followers being pushed into the Fire alongside them. These are the people they deceived, the masses they led astray. Now, in Hell, they will see the consequences of their misguidance as waves of people join them in punishment.",
    "They are not welcome, ˹for˺ they ˹too˺ will burn in the Fire.\"": "The misleaders will express displeasure at the arrival of their followers, saying they are not welcome. But this is not out of mercy for them—rather, it is because they know these followers will share in the same torment. There is no camaraderie in Hell, no comfort in company. Each person's punishment is individual, and seeing others join only adds to the misery and regret. In this world, the corrupt leaders gathered followers; in the Hereafter, they will wish they had never known them."
  },
  60: {
    "The followers will respond, \"No! You are not welcome!": "The followers will immediately turn on their leaders, throwing the unwelcome back at them. In this world, they blindly followed these leaders; in the Hereafter, they will curse them. The bond between leader and follower, built on falsehood, will completely disintegrate in Hell.",
    "You brought this upon us.": "The followers will blame their leaders for their fate. 'You are the ones who led us here! You taught us disbelief, you encouraged us in sin, you blocked us from the truth!' This blame, however, will not reduce anyone's punishment. Each person chose to follow, and each will bear responsibility. But the leaders will have additional punishment for every person they misguided.",
    "What an evil place for settlement!\"": "The followers describe Hell as the worst possible dwelling place. The word 'qarar' (settlement/abode) is used sarcastically—Hell is their permanent residence, and what a terrible residence it is. Unlike Paradise where the believers settle in peace and joy, the disbelievers settle in torment and regret."
  },
  61: {
    "Adding, \"Our Lord! Whoever brought this upon us, double their punishment in the Fire.\"": "The followers will call out to Allah, praying against those who misled them. They will ask Allah to double the punishment of their leaders—those who 'prepared' this fate for them by teaching them disbelief and sin. This shows the complete reversal of relationships in Hell: those who were once admired and followed will be cursed by their own followers. The Prophet Muhammad warned against misguiding others, saying that whoever introduces a bad practice will bear its sin plus the sin of everyone who follows it (Muslim). The leaders of misguidance will indeed face multiplied punishment."
  },
  62: {
    "The tyrants will ask ˹one another˺, \"But why do we not see those we considered to be lowly?": "The arrogant disbelievers will look around Hell and notice that certain people are missing—the believers whom they used to mock and look down upon in the world. They called them 'lowly' and 'evil' because they followed the Prophet and rejected the ways of the elite. Now, in Hell, they search for these believers but cannot find them."
  },
  63: {
    "Were we wrong in mocking them ˹in the world˺?": "A moment of terrible realization dawns on them. They wonder: 'Were we wrong to mock those people? Were they actually right?' In this world, the wealthy and powerful often ridicule those who prioritize faith over worldly success. But in Hell, they will realize their mockery was foolishness. The people they ridiculed are now in Paradise while they burn.",
    "Or do our eyes ˹just˺ fail to see them ˹in the Fire˺?\"": "They entertain another possibility: maybe the believers are in Hell too, but they just cannot see them? But deep down they know the truth—the believers are not in Hell. They are in Paradise, enjoying eternal blessings. This verse powerfully illustrates the reversal of fortunes in the Hereafter: those mocked on earth are honored in Paradise, and those who mocked are humiliated in Hell."
  },
  64: {
    "This dispute between the residents of the Fire will certainly come to pass.": "Allah confirms that this scene—the arguments, the blame, the curses between leaders and followers, the searching for the believers they mocked—will definitely happen. It is not a parable or metaphor but a certain reality. The word 'haqq' (truth/certain) emphasizes that these disputes in Hell are guaranteed events. This should serve as a powerful warning: choose your leaders and companions wisely in this life, for the bonds built on falsehood will become sources of additional torment in Hell."
  },
  65: {
    "Say, ˹O Prophet,˺ \"I am only a warner.": "Allah commands Prophet Muhammad to clarify his role: he is a warner sent to alert people about the consequences of disbelief and sin. He does not claim to be divine, does not control people's destinies, and does not perform miracles at will. His job is to deliver the message and warn humanity—the response is up to each individual.",
    "And there is no god ˹worthy of worship˺ except Allah": "The core message of Islam is declared: there is no deity worthy of worship except Allah. All other objects of worship—idols, saints, nature, desires—are false gods. Only Allah deserves worship because only He is the true Creator and Sustainer.",
    "—the One, the Supreme.": "Allah is 'Al-Wahid' (the One)—unique, without partner or equal. He is also 'Al-Qahhar' (the Supreme, the Subduer)—the One who overpowers all things and before whom everything is humbled. His oneness and supreme power mean that nothing can challenge Him, resist Him, or share in His divinity. This is the foundation of Islamic monotheism (Tawhid)."
  },
  66: {
    "˹He is the˺ Lord of the heavens and the earth and everything in between": "Allah is the Lord (Rabb) of all that exists—the heavens with their stars and galaxies, the earth with all its creatures and features, and everything in between. His lordship means He created all of it, owns all of it, and sustains all of it. Nothing exists outside His dominion.",
    "—the Almighty, Most Forgiving.\"": "Two beautiful divine attributes are combined here: 'Al-Aziz' (the Almighty, the Invincible) and 'Al-Ghaffar' (the Repeatedly Forgiving). Allah has the power to punish anyone instantly, yet He chooses to forgive repeatedly. His might could crush all transgressors, but His mercy offers them countless chances to repent. This combination of power and forgiveness should inspire both awe and hope in the hearts of believers."
  },
  67: {
    "Say, \"This ˹Quran˺ is momentous news,": "The Prophet is commanded to declare that the Quran is not ordinary speech—it is 'naba'un 'adheem' (momentous news, a great announcement). It contains information about Allah, the unseen world, the Day of Judgment, Paradise, Hell, and guidance for all aspects of life. There is nothing trivial about it. Every verse carries weight and significance. The Quran announces realities that will affect every human being for eternity."
  },
  68: {
    "from which you ˹pagans˺ are turning away.\"": "Despite the magnitude of this news, the disbelievers turn away from it. They ignore the Quran, dismiss its warnings, and busy themselves with worldly distractions. This is the greatest tragedy—being offered the most important information in existence and choosing to look away. This verse is also a subtle warning: turning away from the Quran is a grave mistake with eternal consequences."
  },
  69: {
    "˹And say,˺ \"I had no knowledge of the highest assembly ˹in heaven˺ when they differed ˹concerning Adam˺.": "The Prophet is told to clarify that he had no prior knowledge of what happened in the heavens—the discussion among the angels, the story of Adam's creation, and Iblis's refusal to prostrate. This information came to him only through divine revelation. He was not present in the heavenly assembly; he is simply conveying what Allah revealed to him. This proves that the Quran is not Muhammad's own invention—how could an unlettered man in the desert know about conversations in the highest heavens? This knowledge could only come from Allah."
  },
  70: {
    "What is revealed to me is that I am only sent with a clear warning.\"": "The Prophet explains the essence of his mission: he receives revelation from Allah, and the core message he is commanded to deliver is a clear warning to humanity. He is not claiming special powers or asking for worldly benefits. His role is to warn people clearly about the consequences of rejecting Allah, so that no one can claim ignorance on the Day of Judgment."
  },
  71: {
    "˹Remember, O Prophet˺ when your Lord said to the angels, \"I am going to create a human being from clay.": "Allah takes us back to the very beginning of human history. Before Adam was created, Allah announced His plan to the angels: He would create a human being from clay (teen). This shows that Allah's creation of humanity was deliberate and announced—not random or accidental. The angels were informed because they would be involved in what followed."
  },
  72: {
    "So when I have fashioned him": "Allah described the process: He would fashion and perfect the human form. The word 'sawwaytuhu' indicates careful shaping and proportioning—Adam was not a crude creation but a being fashioned with divine precision and care.",
    "and had a spirit of My Own ˹creation˺ breathed into him,": "The soul that would animate Adam is attributed to Allah ('min ruhi'—of My spirit). This does not mean Allah's essence entered Adam, but that the soul is something special and honored, directly created by Allah and breathed into the human form. This soul is what distinguishes humans from other creatures and gives us our unique status.",
    "fall down in prostration to him.\"": "Allah commanded the angels to prostrate to Adam. This was not worship—worship is only for Allah—but a prostration of honor and respect, acknowledging Adam's special status as Allah's khalifah (vicegerent) on earth. This command was a test, and the angels were expected to obey."
  },
  73: {
    "So the angels prostrated all together—": "The angels obeyed Allah's command completely. Every single angel, without exception, prostrated to Adam. The repetition ('kulluhum ajma'oon'—all of them, altogether) emphasizes that not a single angel hesitated or refused. This is the nature of angels: they do not disobey Allah and they do exactly what they are commanded (66:6). Their obedience highlights the gravity of what comes next."
  },
  74: {
    "but not Iblîs, who acted arrogantly,": "One being refused: Iblis (Satan). He was among the company of angels (though he was from the jinn, as stated in 18:50) and was commanded to prostrate, but he refused. His refusal was rooted in arrogance (istakbara)—he considered himself too great, too superior to bow before Adam. This pride was his downfall.",
    "becoming unfaithful.": "Through his arrogance, Iblis became a disbeliever (kafir). His disobedience was not a momentary lapse but a conscious rejection of Allah's command based on pride. This teaches us that arrogance is one of the most dangerous spiritual diseases—it can lead even someone who worshipped Allah for thousands of years to become a disbeliever in an instant. The Prophet said: 'No one who has an atom's weight of arrogance in his heart will enter Paradise' (Muslim)."
  },
  75: {
    "Allah asked, \"O Iblîs! What prevented you from prostrating to what I created with My Own Hands?": "Allah questioned Iblis directly, giving him a chance to explain. Allah mentioned that He created Adam 'with My Own Hands'—a phrase indicating special honor and direct divine attention. This was not like other creations; Adam was specially fashioned by Allah Himself. What could possibly justify refusing to honor such a creation?",
    "Did you ˹just˺ become proud? Or have you always been arrogant?\"": "Allah's question exposes the root of the problem: pride. Was this arrogance something new that suddenly emerged, or was it always hidden within Iblis? Either way, the arrogance was now exposed. This teaches us that pride can be concealed for a long time but will eventually surface when tested."
  },
  76: {
    "He replied, \"I am better than he is:": "Instead of repenting or seeking forgiveness, Iblis defended his disobedience with a claim of superiority: 'I am better than him.' This is the essence of arrogance—considering oneself above others and above obeying commands that apply to everyone.",
    "You created me from fire and him from clay.\"": "Iblis presented his flawed reasoning: fire is superior to clay, therefore I am superior to Adam. This logic was wrong on multiple levels. First, superiority is not determined by the material of creation but by obedience and character. Second, Iblis was comparing what Allah had chosen to honor—he was rejecting Allah's judgment with his own opinion. Third, his reasoning ignored that Allah explicitly commanded the prostration, regardless of the materials involved. This teaches us that no human reasoning can override divine commands."
  },
  77: {
    "Allah commanded, \"Then get out of Paradise,": "The consequence was immediate: expulsion. Iblis was removed from his honored position and cast out of Paradise. One moment of arrogance cost him everything he had built over thousands of years of worship. This is a stark warning about the destructive power of pride.",
    "for you are truly cursed.": "Iblis became 'rajeem'—cursed, pelted, driven away from divine mercy. The curse was not temporary but permanent. He went from being in the company of angels to being the most cursed creature in existence. All because he refused to obey out of pride."
  },
  78: {
    "And surely upon you is My condemnation until the Day of Judgment.\"": "Allah declared that His curse would remain upon Iblis until the Day of Judgment. Every moment of his existence, from that point until the end of time, he would be under divine condemnation. He would have no respite, no forgiveness, no return to grace. This is the eternal consequence of arrogant disobedience."
  },
  79: {
    "Satan appealed, \"My Lord! Then delay my end until the Day of their resurrection.\"": "Iblis made a request: grant him a reprieve until the Day when humans are resurrected. He wanted time—not to repent, but to pursue his mission of vengeance. He blamed Adam for his downfall and wanted the opportunity to prove that humans were not worthy of the honor Allah gave them. This shows that Iblis was not simply ignorant; he was deliberately evil."
  },
  80: {
    "Allah said, \"You will be delayed": "Allah granted Iblis's request—but not out of honor or mercy. This was part of Allah's divine plan: Iblis would be a test for humanity. His existence would separate the sincere believers from the followers of falsehood."
  },
  81: {
    "until the appointed Day.\"": "Iblis would live until a specific appointed time known only to Allah. Some scholars say this is the Day of Judgment; others say it is the first Trumpet blast that will end all life. Either way, Iblis has been given his time—but it is limited. His end is certain, only its timing is known to Allah."
  },
  82: {
    "Satan said, \"By Your Glory! I will certainly mislead them all,": "Iblis swore by Allah's glory (izzah) that he would dedicate his existence to misleading humanity. He declared war on the children of Adam, vowing to deceive all of them. This shows his determination and his evil mission. He knows Allah is great and powerful, yet he persists in rebellion—this is the depth of his arrogance and corruption."
  },
  83: {
    "except Your chosen servants among them.\"": "Iblis acknowledged one exception: he cannot mislead Allah's sincere, chosen servants (mukhlaseen). These are people who have purified their hearts, devoted themselves entirely to Allah, and are protected by divine guidance. Iblis knows his limits—he can only affect those who open their hearts to his whispers. The sincere believers are beyond his reach. This should motivate every believer to strive for sincerity (ikhlas) in all their actions."
  },
  84: {
    "Allah concluded, \"The truth is—and I ˹only˺ say the truth—:": "Allah responded to Iblis's declaration with a statement of absolute truth. Allah only speaks truth; there is no falsehood in anything He says. What He is about to declare is a certain decree that will definitely come to pass."
  },
  85: {
    "I will surely fill up Hell with you and whoever follows you from among them, all together.\"": "Allah declared the ultimate fate of Iblis and his followers: Hell will be filled with them. This is not a possibility but a certainty. Iblis will enter Hell, and every human being who chose to follow him—who accepted his whispers, pursued his path of arrogance, and rejected divine guidance—will join him there. This verse clarifies that following Satan leads to only one destination: eternal punishment. The choice is ours."
  },
  86: {
    "Say, ˹O Prophet,˺ \"I do not ask you for any reward for this ˹Quran˺,": "The Prophet is commanded to declare his sincerity: he is not asking for money, power, or any worldly benefit in exchange for delivering the message. This is crucial because it removes any suspicion of ulterior motives. Throughout history, false leaders have exploited religion for personal gain. The Prophet's position was clear: he sought nothing from the people except that they believe in Allah for their own salvation.",
    "nor do I pretend to be someone I am not.": "The Prophet clarifies that he is not pretending or putting on an act. He is not an imposter claiming to be a prophet for attention or status. He is not exaggerating or making things up. What he says is genuine, and his message is authentic. The word 'mutakallif' refers to someone who pretends or puts on false airs—the Prophet was none of that. He was the same person in public and private, before prophethood and after."
  },
  87: {
    "It is only a reminder to the whole world.": "The Quran is not meant for one tribe, one nation, or one era—it is a reminder for all of humanity (al-'alameen—all worlds/peoples). Arabs and non-Arabs, ancient and modern, East and West—the Quran speaks to everyone. Its message of monotheism, morality, and accountability is universal. This verse confirms the global mission of Islam and the Prophet Muhammad as a messenger to all of mankind."
  },
  88: {
    "And you will certainly know its truth before long.\"": "The surah ends with a powerful warning and promise: the truth of this message will become clear. Whether in this life—through witnessing the victory of Islam, the fulfillment of prophecies, or personal experiences—or in the Hereafter when everyone faces the reality of Judgment Day, the truth of the Quran will be known to all. Those who rejected it will realize their mistake, but by then it may be too late. This verse encourages the believers to remain steadfast and warns the disbelievers that their denial will not last forever. Time will prove everything."
  }
};