var tafsirData_35 = {
  1: {
    "All praise is for Allah, the Originator of the heavens and the earth": "All gratitude and praise belong exclusively to Allah, Who brought the heavens and the earth into existence from nothing. He is the One who initiated creation without any prior model or example. This opening reminds us that everything we see around us—the sky above, the ground beneath our feet, and all that exists between them—was designed and brought into being by Allah alone. When we look at the vastness of the universe with its billions of galaxies, we should recognize that all of this came from Allah's creative command.",
    "Who made angels ˹as His˺ messengers with wings—two, three, or four": "Allah created angels as noble beings who serve as His messengers, carrying out His commands throughout the universe. These angels have wings—some with two, some with three, and some with four wings—which they use to travel and fulfill their duties. The Prophet Muhammad (peace be upon him) saw the angel Jibreel (Gabriel) in his true form with six hundred wings, showing that angels can have even more wings than mentioned here. Angels are created from light and are completely obedient to Allah, never disobeying His commands. They deliver revelation to prophets, record our deeds, protect us, and carry out countless other tasks assigned by Allah.",
    "He increases in creation whatever He wills": "Allah is not limited in His creative ability. He adds to His creation in any way He chooses—whether in beauty, size, strength, wings, or any other quality. This shows that Allah's creative power has no boundaries. For example, some creatures have extraordinary beauty, others have unique abilities, and the diversity in creation is endless. This phrase also teaches us that we should never be surprised by the wonders of creation because Allah can create anything He desires.",
    "Surely Allah is Most Capable of everything": "Allah has complete and unlimited power over all things. Nothing is difficult for Him, and nothing is beyond His ability. Whether it is creating the universe, giving life, causing death, or bringing about the Day of Judgment—all of it is easy for Allah. This should give believers comfort and confidence, knowing that the One they worship is capable of answering their prayers and fulfilling His promises."
  },
  2: {
    "Whatever mercy Allah opens up for people, none can withhold it": "When Allah decides to bless someone with His mercy—whether it be health, wealth, guidance, rain, children, success, or any other blessing—no one in the entire creation can prevent that mercy from reaching them. No king, no army, no system, and no circumstance can block what Allah has decreed to give. This is deeply comforting because it means that when Allah wants good for you, nothing can stop it. The Prophet (peace be upon him) taught us to say: \"What Allah wills happens, and what He does not will does not happen.\"",
    "And whatever He withholds, none but Him can release it": "Similarly, if Allah decides to withhold something from someone, no one else can provide it. If Allah withholds rain, no technology can produce it. If He withholds guidance from a stubborn heart, no preacher can guide it. If He withholds health, no doctor can restore it without His permission. This teaches us complete dependence on Allah and that we should always turn to Him first in all our needs.",
    "For He is the Almighty, All-Wise": "Allah possesses ultimate power and perfect wisdom. His might means He can do whatever He wills, and His wisdom means everything He does has a purpose and is done in the best possible way. When we do not understand why something happens or does not happen, we trust in His wisdom. Sometimes what we want is not good for us, and what we dislike is actually better for us. Allah knows, and we do not know."
  },
  3: {
    "O humanity! Remember Allah's favours upon you": "Allah addresses all of mankind—not just believers—calling them to reflect on the countless blessings He has given them. These favors include life itself, the air we breathe, water, food, shelter, family, health, intellect, and guidance through prophets and scriptures. Most of these blessings we take for granted every single day. The purpose of remembering these favors is to develop gratitude and to recognize the One who provided them. When someone gives you a gift, you naturally feel thankful toward them. How much more should we feel toward Allah, who has given us everything?",
    "Is there any creator other than Allah who provides for you from the heavens and the earth?": "This is a rhetorical question meant to make us think deeply. Allah challenges humanity: Can you name any other being that creates and provides for you? Rain comes down from the sky, and crops grow from the earth. Who sends the rain? Who makes the seeds sprout? Who causes the sun to shine and the seasons to change? The answer is obvious—only Allah does all of this. No idol, no human being, no false god has ever created anything or provided sustenance. This logical argument destroys the foundation of idol worship and polytheism.",
    "There is no god ˹worthy of worship˺ except Him": "Since Allah alone creates and provides, He alone deserves to be worshipped. This is the declaration of Tawheed (monotheism)—the core message of Islam and every prophet before Muhammad (peace be upon him). Worship includes prayer, supplication, trust, love, fear, hope, and obedience. All of these should be directed to Allah alone.",
    "How can you then be deluded ˹from the truth˺?": "After presenting such clear evidence, Allah expresses wonder at how people can still turn away from the truth. How can anyone worship idols that cannot create or provide? How can anyone deny Allah when His signs are everywhere? This question is meant to shake people out of their heedlessness and make them realize the absurdity of disbelief and polytheism."
  },
  4: {
    "If you are rejected by them, so too were messengers before you": "Allah comforts Prophet Muhammad (peace be upon him) by reminding him that he is not alone in facing rejection. Every prophet before him—Nuh (Noah), Ibrahim (Abraham), Musa (Moses), Isa (Jesus), and all others—faced denial and hostility from their people. This is the nature of prophethood; the truth is often rejected by those who prefer their desires and traditions over divine guidance. The Prophet should not feel discouraged or think that he has failed. Rejection by stubborn people is not a reflection of the messenger's worth but of the rejectors' blindness.",
    "And to Allah ˹all˺ matters will be returned ˹for judgment˺": "Ultimately, everything will return to Allah for final judgment. Those who rejected the prophets will be held accountable, and those who believed will be rewarded. This reminder gives patience to the believers and serves as a warning to the disbelievers. Justice will be served, even if not in this world. The Prophet (peace be upon him) does not need to worry about punishing the disbelievers—Allah will handle that matter perfectly."
  },
  5: {
    "O humanity! Indeed, Allah's promise is true": "Allah's promise of the Day of Judgment, resurrection, accountability, Paradise for the believers, and Hell for the disbelievers—all of it is absolutely true and will certainly happen. There is no doubt in Allah's promise. He has never broken a promise, and He never will. This truth should be the foundation of how we live our lives, making choices based on the reality of the Hereafter.",
    "So do not let the life of this world deceive you": "The worldly life, with its pleasures, wealth, entertainment, and temporary enjoyments, can easily distract us from preparing for the Hereafter. People get so absorbed in chasing money, status, and comfort that they forget death and what comes after. Allah warns us not to be fooled by this temporary life. The Prophet (peace be upon him) said: \"The world is a prison for the believer and a paradise for the disbeliever.\" This does not mean we cannot enjoy lawful things, but we should not let them distract us from our ultimate purpose.",
    "nor let the Chief Deceiver deceive you about Allah": "The Chief Deceiver is Satan (Iblis). He whispers false ideas to people, such as: \"Allah is too merciful to punish you,\" or \"You have plenty of time to repent later,\" or \"Everyone is doing it, so it must be fine.\" Satan tries to make people feel secure in their sins and delays their repentance until it is too late. We must recognize these tricks and not fall for them. Allah is indeed merciful, but He is also just, and we must not presume upon His mercy while continuing in sin."
  },
  6: {
    "Surely Satan is an enemy to you, so take him as an enemy": "Allah makes it absolutely clear: Satan is our sworn enemy. He has dedicated his existence to leading humans astray. Since he is our enemy, we must treat him as such—being constantly on guard against his whispers, tricks, and temptations. We do not negotiate with enemies or trust them. Many people underestimate Satan or forget about his enmity, which makes them easy targets. A believer should always be aware of Satan's tactics and seek refuge in Allah from him.",
    "He only invites his followers to become inmates of the Blaze": "Satan's ultimate goal is to drag as many people as possible into the Hellfire with him. He knows he is doomed, and out of envy and hatred, he wants humanity to share his fate. Every temptation he presents, every sin he beautifies, every doubt he plants—all of it is designed to lead people to eternal punishment. His followers—those who obey him and ignore Allah's guidance—will end up as companions of the Blaze. This stark warning should make us extremely cautious about following desires that Satan makes appealing."
  },
  7: {
    "Those who disbelieve will have a severe punishment": "Those who reject Allah, deny His messengers, and refuse to follow His guidance will face a terrible punishment in the Hereafter. This punishment is described as severe, indicating intense suffering that is beyond our imagination. The disbelievers chose to ignore the truth despite clear signs and warnings, so they will bear the consequences of their choice.",
    "But those who believe and do good will have forgiveness and a great reward": "In contrast, those who believe in Allah and His messengers and follow up their faith with righteous deeds will receive two things: forgiveness for their sins and a great reward. The forgiveness covers their shortcomings and mistakes, while the great reward refers to Paradise and all its unimaginable pleasures. Notice that belief alone is mentioned alongside good deeds—true faith must be accompanied by action. The Prophet (peace be upon him) said that faith is not merely a claim but what settles in the heart and is proven by actions."
  },
  8: {
    "Are those whose evil-doing is made so appealing to them that they deem it good ˹like those who are rightly guided˺?": "This rhetorical question highlights a dangerous spiritual condition: some people have their sins beautified for them so that they see evil as good. They think their path is correct when it is actually leading them to destruction. Such people cannot be compared to those who are genuinely guided and can distinguish right from wrong. This condition often results from persistent sinning, which hardens the heart and distorts one's moral compass. For example, someone who keeps lying eventually sees nothing wrong with lying.",
    "˹It is˺ certainly Allah ˹Who˺ leaves to stray whoever He wills, and guides whoever He wills": "Guidance and misguidance are ultimately in Allah's hands. However, this does not mean Allah arbitrarily guides or misguides people. Rather, Allah guides those who sincerely seek guidance and turn to Him, while He leaves astray those who arrogantly reject the truth and persist in sin. It is a consequence of their own choices. When someone repeatedly rejects guidance, Allah seals their heart as a form of justice. The Quran says elsewhere: \"So when they deviated, Allah caused their hearts to deviate\" (61:5).",
    "So do not grieve yourself to death over them ˹O Prophet˺": "The Prophet (peace be upon him) was deeply concerned about his people's rejection of Islam. He felt immense sadness seeing them choose a path leading to destruction. Allah tells him not to let this grief consume him or harm his health. The Prophet has done his duty by conveying the message; he cannot force people to believe. This teaches all believers, especially those who do dawah (invite others to Islam), that their job is only to convey the message, not to guarantee results.",
    "Surely Allah is All-Knowing of what they do": "Allah knows everything people do—their actions, intentions, and secrets. Nothing escapes His knowledge. The disbelievers will be held accountable for everything, and Allah is fully aware of their plots and mockery. This serves as both a warning to the disbelievers and a comfort to the Prophet and believers: justice will be served based on Allah's perfect knowledge."
  },
  9: {
    "And it is Allah Who sends the winds, which then stir up ˹vapour, forming˺ clouds": "Allah controls the winds, directing them according to His will. These winds move water vapor and stir up clouds in the sky. This is a natural phenomenon we observe regularly, yet behind it is Allah's precise command and control. Scientists describe the water cycle, but the One who designed and sustains this cycle is Allah. Every drop of rain is sent by His command.",
    "and then We drive them to a lifeless land, giving life to the earth after its death": "Allah directs the rain clouds to land that is dry, barren, and seemingly dead. When the rain falls, the dead earth comes back to life—plants sprout, flowers bloom, and the land becomes green and productive. This transformation from death to life is a profound sign of Allah's power. Just as He brings dead land to life, He will bring dead bodies back to life on the Day of Resurrection.",
    "Similar is the Resurrection": "Allah draws a direct parallel between the revival of dead land and the resurrection of human beings. Just as we see barren land becoming alive after rain, we will witness the dead rising from their graves on the Day of Judgment. Those who doubt the resurrection should look at this sign that occurs every year. The One who can revive dead earth can certainly revive dead bodies. This analogy makes the concept of resurrection easy to understand and believe."
  },
  10: {
    "Whoever seeks honour and power, then ˹let them know that˺ all honour and power belongs to Allah": "Many people seek honor, respect, and power through wealth, status, political position, or worldly achievements. Allah tells us that all true honor belongs to Him alone. If you want real, lasting honor, seek it from Allah through obedience to Him. The Quran states: \"Honor belongs to Allah, His Messenger, and the believers\" (63:8). Those who seek honor through disobedience to Allah will only find humiliation, while those who humble themselves before Allah will be elevated.",
    "To Him ˹alone˺ good words ascend": "Good words—such as remembrance of Allah, recitation of Quran, words of praise, supplication, and speaking the truth—ascend to Allah. These words are beloved to Him and are recorded and rewarded. The Prophet (peace be upon him) said: \"Two words are light on the tongue, heavy on the scales, and beloved to the Most Merciful: SubhanAllahi wa bihamdihi, SubhanAllahil-Azeem.\" Our good words rise up to Allah, so we should be mindful of what we say.",
    "and righteous deeds are raised up by Him": "Good deeds elevate and give value to good words. Faith and righteous actions go together. Saying good things is important, but backing them up with good actions makes them meaningful and accepted. Some scholars say righteous deeds raise the person who does them in status, while others say good words and good deeds support each other. Both meanings are beautiful and true.",
    "As for those who plot evil, they will suffer a severe punishment": "Those who scheme and plan evil—whether against Islam, the Prophet, or believers—will face a painful punishment. Their plots may seem to succeed temporarily in this world, but Allah sees everything, and His punishment will reach them either in this life or the next.",
    "And the plotting of such ˹people˺ is doomed ˹to fail˺": "The evil schemes of the plotters will ultimately fail and come to nothing. History is full of examples of tyrants and enemies of truth whose plots eventually collapsed. Pharaoh plotted against Musa, but he drowned. The Quraysh plotted against the Prophet, but they were defeated. Allah's plan always prevails over the plans of His enemies."
  },
  11: {
    "And ˹it is˺ Allah ˹Who˺ created you from dust": "The origin of humanity traces back to Adam (peace be upon him), who was created from dust or clay. This reminds us of our humble origins and that we should not be arrogant. We came from the earth, we live on the earth, and we will return to the earth. This basic material—dust—was transformed by Allah's power into a complex, intelligent, conscious human being.",
    "then ˹developed you˺ from a sperm-drop": "After Adam, human beings are created through reproduction. Each person develops from a tiny sperm-drop—something so small it is invisible to the naked eye. The fact that a complete human being with bones, flesh, organs, and a soul develops from this tiny drop is a miracle that points to Allah's creative power. The Quran describes the stages of embryonic development in remarkable detail.",
    "then made you into pairs": "Allah created humans as males and females, pairs that complement each other. This pairing allows for reproduction, companionship, and the continuation of the human race. Marriage between man and woman is a natural institution established by Allah. The diversity of human pairs—different appearances, personalities, and abilities—is also part of Allah's design.",
    "No female ever conceives or delivers without His knowledge": "Every pregnancy and every birth happens with Allah's complete knowledge. He knows when a woman conceives, what the baby's gender is, what it will look like, what its future holds, and when it will be born. Nothing about the process is hidden from Allah. This knowledge belongs to Him alone, and it is a comfort to expecting mothers that Allah is fully aware of what they are going through.",
    "And no one's life is made long or cut short but is ˹written˺ in a Record": "Every person's lifespan is already recorded in a divine Record (Al-Lawh Al-Mahfuz). Allah knows exactly how long each person will live. Some people live long lives, and some lives are cut short—all according to what Allah has decreed. This teaches us that our time is limited and precious, and we should use it wisely in obedience to Allah.",
    "That is certainly easy for Allah": "Keeping track of every conception, birth, and lifespan of billions of humans throughout history—all of this is easy for Allah. Nothing is difficult for Him. His knowledge is infinite, and His power is unlimited. What seems overwhelming to us is simple for the Creator of the universe."
  },
  12: {
    "The two bodies of water are not alike: one is fresh, palatable, and pleasant to drink and the other is salty and bitter": "Allah points out the difference between fresh water (rivers, lakes) and salt water (oceans, seas). Fresh water is sweet and drinkable, essential for human survival. Salt water is bitter and not suitable for drinking. Yet both exist on the same earth, side by side in some places, and they do not mix completely due to natural barriers Allah has placed. This difference is a sign of Allah's design and wisdom.",
    "Yet from them both you eat tender seafood and extract ornaments to wear": "Despite their differences, both types of water provide benefits to humans. From both fresh and salt water, we get fresh fish and seafood to eat. From the seas, we also extract pearls and coral, which are used as jewelry and ornaments. These are blessings from Allah that we often take for granted.",
    "And you see the ships ploughing their way through both, so you may seek His bounty and give thanks ˹to Him˺": "Ships travel through both rivers and oceans, carrying people and goods. This maritime travel enables trade, exploration, and connection between different lands. The ability to build ships and navigate waters is a blessing from Allah that has allowed civilizations to prosper. The purpose of all these blessings is that we recognize them as coming from Allah and express gratitude to Him."
  },
  13: {
    "He merges the night into the day and the day into the night": "Allah causes the night to gradually enter into the day and the day to gradually enter into the night. This is the beautiful transition we see at dawn and dusk. The length of day and night also changes throughout the year. This precise, orderly system happens by Allah's command every single day without fail. It is so regular that we set our clocks by it, yet we rarely stop to appreciate the One who controls it.",
    "and has subjected the sun and the moon, each orbiting for an appointed term": "The sun and moon are made subservient to Allah's command. They follow precise orbits that Allah has set for them. The sun provides light and heat essential for life, while the moon provides light at night and helps mark the months. Each continues its course until an appointed time—the Day of Judgment—when the sun will be folded up and the moon will lose its light.",
    "That is Allah—your Lord! All authority belongs to Him": "This is Allah, your true Lord and Master. All dominion, sovereignty, and authority belong to Him alone. He controls the universe and everything in it. Recognizing this should lead us to worship Him alone and submit to His commands.",
    "But those ˹idols˺ you ˹pagans˺ invoke besides Him do not possess even the skin of a date stone": "In contrast to Allah's absolute power, the idols and false gods that people worship possess nothing at all—not even something as insignificant as the thin membrane on a date stone. This comparison highlights the utter powerlessness of idols. They cannot create, provide, or control anything. Worshipping them is pure foolishness."
  },
  14: {
    "If you call upon them, they cannot hear your calls": "The idols and false deities people pray to cannot hear their prayers. They are lifeless objects or beings with no power to perceive or respond. People may cry out to them desperately, but their calls fall on deaf ears. This is the tragic reality of idol worship.",
    "And if they were to hear, they could not respond to you": "Even hypothetically, if these idols could somehow hear, they would have no ability to answer prayers or help anyone. They have no power to benefit or harm. Worshippers of idols are essentially calling out to nothing—wasting their worship on beings that cannot help them.",
    "On the Day of Judgment they will disown your worship ˹of them˺": "On the Day of Judgment, these false objects of worship will reject and disown their worshippers. They will deny any association with those who worshipped them. This will be a shocking betrayal for the polytheists, who will realize too late that their worship was completely misplaced. Even righteous people who were wrongly worshipped (like Jesus or certain saints) will testify against those who worshipped them instead of Allah.",
    "And no one can inform you ˹O Prophet˺ like the All-Knowledgeable": "This information comes from Allah, the All-Knowing, who knows the reality of all things. No one can give you truer, more reliable information than Allah Himself. His word is the ultimate truth, and His knowledge encompasses everything that was, is, and will be."
  },
  15: {
    "O humanity! It is you who stand in need of Allah": "Allah addresses all of mankind with a fundamental truth: we are completely dependent on Allah for everything. We need Him for our existence, sustenance, guidance, health, and salvation. We are poor and needy in relation to Him. We cannot survive a single moment without His sustenance. This is not meant to belittle us but to remind us of reality so that we turn to Him in humility.",
    "but Allah ˹alone˺ is the Self-Sufficient, Praiseworthy": "While we are needy, Allah is completely Self-Sufficient. He needs nothing and no one. He does not need our worship—our worship benefits us, not Him. He is Praiseworthy in Himself, deserving of all praise whether anyone praises Him or not. This contrast should inspire us to worship Allah out of gratitude and need, knowing that He is the source of all good."
  },
  16: {
    "If He willed, He could eliminate you and produce a new creation": "Allah has the power to remove all of humanity and replace us with an entirely new creation. Our existence is not necessary for Allah—He chose to create us out of His will and mercy. If we are ungrateful and disobedient, He could easily replace us with others who would worship and obey Him. This is a warning against arrogance and ingratitude. The Quran mentions elsewhere: \"If you turn away, He will replace you with another people, and they will not be like you\" (47:38)."
  },
  17: {
    "And that is not difficult for Allah ˹at all˺": "Eliminating all of humanity and creating an entirely new species is not difficult or burdensome for Allah in the slightest. Creating the entire universe was not hard for Him—He simply said \"Be\" and it was. His power is unlimited, and nothing is challenging for Him. This should instill both awe and humility in our hearts."
  },
  18: {
    "No soul burdened with sin will bear the burden of another": "On the Day of Judgment, every person will carry only their own sins. No one will be punished for someone else's sins. This is divine justice—each person is accountable only for what they themselves did. This refutes the false concept that one person can bear the sins of others or that inherited sin exists. Each soul will answer for its own choices.",
    "And if a sin-burdened soul cries for help with its burden, none of it will be carried—even by a close relative": "Even if a person weighed down by sins desperately asks for help on the Day of Judgment, no one—not even their closest family member—will be able to carry any of their burden. Parents will not help children, and children will not help parents on that Day. Everyone will be too concerned with their own fate. The Prophet (peace be upon him) warned his own daughter Fatimah that he could not save her from Allah—she would have to save herself through her own faith and deeds.",
    "You ˹O Prophet˺ can only warn those who stand in awe of their Lord without seeing Him and establish prayer": "The Prophet's warning truly benefits those who already have some fear of Allah in their hearts—those who believe in the unseen and worship Allah even though they have not seen Him. These people also establish regular prayer, which shows their commitment to Allah. Those whose hearts are completely sealed will not benefit from any warning, no matter how eloquent or sincere.",
    "Whoever purifies themselves, they only do so for their own good": "When a person purifies their soul through faith, repentance, good deeds, and avoiding sins, the benefit of that purification returns to them alone. Allah does not need our purification—He is already perfect. We are the ones who benefit from becoming better people. Our spiritual growth is an investment in our own eternal future.",
    "And to Allah is the final return": "Everyone will ultimately return to Allah for judgment. There is no escaping this meeting with our Creator. This reminder should motivate us to prepare for that Day by living righteously and seeking Allah's forgiveness."
  },
  19: {
    "Those blind ˹to the truth˺ and those who can see are not equal": "People who are spiritually blind—unable or unwilling to see the truth of Islam—cannot be compared to those who have spiritual insight and recognize the truth. The difference between a believer and a disbeliever is like the difference between a blind person and one who can see clearly. This comparison emphasizes that faith gives a person clarity and direction, while disbelief leaves a person stumbling in confusion."
  },
  20: {
    "nor are the darkness and the light": "Disbelief and faith are as different as darkness and light. Darkness represents ignorance, misguidance, and sin, while light represents knowledge, guidance, and righteousness. Just as you cannot say darkness and light are the same, you cannot equate the path of disbelief with the path of faith. One leads to confusion and destruction, the other to clarity and salvation."
  },
  21: {
    "nor the ˹scorching˺ heat and the ˹cool˺ shade": "The comfort of shade on a hot day versus the suffering in scorching heat illustrates the difference between believers and disbelievers. Believers will enjoy the shade of Allah's mercy and eventual Paradise, while disbelievers will suffer in the heat of punishment. This worldly comparison helps us understand the stark contrast in the outcomes of faith and disbelief."
  },
  22: {
    "Nor are the dead and the living equal": "Believers are spiritually alive—their hearts are receptive to guidance and truth. Disbelievers are spiritually dead—their hearts are sealed and unresponsive. These two groups cannot be considered equal. A living person can hear, respond, and act, while a dead person cannot. Similarly, a believer can receive guidance, while a stubborn disbeliever's heart is as unresponsive as a corpse.",
    "Indeed, Allah ˹alone˺ makes whoever He wills hear": "Only Allah can truly open hearts and make people receptive to guidance. The Prophet delivers the message, but the ability to truly \"hear\" and accept it comes from Allah. This is why we should always ask Allah for guidance and an open heart.",
    "but you ˹O Prophet˺ can never make those in the graves hear ˹your call˺": "Just as you cannot make dead people in their graves hear you, you cannot make spiritually dead hearts accept the truth. The Prophet is told that his role is limited to delivering the message. He cannot force guidance into hearts that are completely closed. This is a comfort to the Prophet and all who do dawah: do your best to convey the message, but leave the results to Allah."
  },
  23: {
    "You are only a warner": "The Prophet's mission is clearly defined: he is a warner, alerting people to the consequences of disbelief and sin. He does not have the power to force people to believe, nor is he responsible for their choices. His job is to deliver the message faithfully and clearly. The outcome is in Allah's hands."
  },
  24: {
    "We have surely sent you with the truth as a deliverer of good news and a warner": "Allah confirms that He sent Prophet Muhammad (peace be upon him) with the truth—the Quran and the message of Islam. The Prophet brings both good news (of Paradise and Allah's mercy for believers) and warnings (of Hell and Allah's punishment for disbelievers). His message is balanced, offering hope and instilling caution.",
    "There is no community that has not had a warner": "Every nation and community throughout history has received a messenger or warner from Allah. No people were left without guidance. This shows Allah's justice—He does not punish a people without first sending them clear guidance. From the earliest humans to the last community, Allah has sent prophets to guide mankind to the straight path."
  },
  25: {
    "If they deny you, so did those before them": "The Prophet is again comforted by being reminded that rejection is nothing new. Previous nations also denied their messengers. This is a pattern throughout history—the truth is often rejected by those who prefer their old ways.",
    "Their messengers came to them with clear proofs, divine Books, and enlightening Scriptures": "Those earlier messengers did not come empty-handed. They brought clear signs and miracles, written revelations, and scriptures filled with guidance and light. Despite all this evidence, many people still rejected them. This shows that rejection is often not about lack of evidence but about stubbornness and refusal to change."
  },
  26: {
    "Then I seized those who persisted in disbelief": "After giving them time and sending them messengers, Allah eventually seized the disbelievers with punishment. Nations like the people of Nuh, Ad, Thamud, and Pharaoh were all destroyed when they persisted in their rejection despite clear warnings.",
    "How severe was My response!": "Allah asks a rhetorical question to make people reflect on history. How terrible was the punishment that befell those nations! Their stories serve as warnings to later generations. The ruins of some of these civilizations still exist as reminders of what happens when people reject Allah's guidance."
  },
  27: {
    "Do you not see that Allah sends down rain from the sky with which We bring forth fruits of different colours?": "Look at how the same rain water produces fruits of countless colors—red apples, yellow bananas, green grapes, orange oranges, and so many more. The same water, the same soil, yet such diversity in the results. This is a sign of Allah's creative power and wisdom. He could have made everything uniform, but He chose to create variety and beauty for us to enjoy and reflect upon.",
    "And in the mountains are streaks of varying shades of white, red, and raven black": "Even the mountains display Allah's artistry. They have streaks and layers of different colors—white, red, deep black, and many shades in between. This geological diversity is not random; it is part of Allah's purposeful creation. Mountains serve practical purposes (stability, water sources, minerals), but they are also beautiful reminders of the Creator's power."
  },
  28: {
    "just as people, living beings, and cattle are of various colours as well": "The diversity continues in living creatures. Humans come in different skin colors, heights, and features. Animals and livestock also display incredible variety in their appearances. All of this diversity comes from the same Creator using the same basic materials. This should make us appreciate Allah's limitless creativity and wisdom.",
    "Of all of Allah's servants, only the knowledgeable ˹of His might˺ are ˹truly˺ in awe of Him": "True awe and fear of Allah comes from knowledge. Those who understand Allah's power, His signs in creation, His attributes, and His commands are the ones who truly fear Him. This does not mean academic knowledge alone, but knowledge that leads to humility and obedience. A scholar who knows about Allah but does not act on that knowledge does not have true khashyah (reverential awe). The more one learns about Allah and His creation, the more one should be humbled and awed.",
    "Allah is indeed Almighty, All-Forgiving": "Allah combines might with forgiveness. He has the power to punish immediately, but He is also incredibly forgiving. Those who truly know Him fear His might but also hope in His forgiveness. This balance of fear and hope is the essence of a healthy relationship with Allah. He forgives those who repent sincerely, no matter how grave their sins."
  },
  29: {
    "Surely those who recite the Book of Allah": "Those who regularly recite the Quran, reading it properly, reflecting on its meanings, and following its guidance, are engaged in one of the most beloved acts of worship. Recitation here means more than just reading words—it includes understanding, pondering, and living by what is recited. The Prophet (peace be upon him) said: \"The best of you are those who learn the Quran and teach it.\" Making the Quran a daily companion brings light to the heart and guidance to one's life.",
    "establish prayer": "Along with reciting the Quran, these righteous people establish regular prayer. Establishing prayer means more than just performing it—it means praying on time, with proper focus (khushu), fulfilling all its conditions and pillars, and making it a consistent part of one's life. Prayer is the direct connection between a servant and Allah, and it is the first thing a person will be asked about on the Day of Judgment.",
    "and donate from what We have provided for them—secretly and openly": "These believers also spend from what Allah has given them in charity. They give both secretly (to maintain sincerity and protect the dignity of recipients) and openly (to encourage others and fulfill public obligations like zakat). The phrase \"what We have provided for them\" reminds us that our wealth is not truly ours—it is a trust from Allah, and we should use it in ways that please Him.",
    "˹can˺ hope for an exchange that will never fail": "All these acts of worship—recitation, prayer, and charity—are described as a trade or investment that will never lose value or fail. Unlike worldly businesses that can go bankrupt or investments that can lose money, this spiritual commerce with Allah is guaranteed to succeed. Allah promises returns that far exceed what was invested. This metaphor appeals to human understanding of profit and loss, showing that the real profitable deal is with Allah."
  },
  30: {
    "so that He will reward them in full": "Allah promises to give these believers their complete reward without any decrease or injustice. Every good deed will be fully compensated. Allah never cheats or shortchanges anyone. In fact, He multiplies good deeds by ten times at minimum, and up to seven hundred times or more depending on sincerity and circumstances.",
    "and increase them out of His grace": "Beyond the full reward they deserve, Allah will add even more from His boundless grace and generosity. This increase is a gift, not something earned—it is purely from Allah's favor. We can never truly deserve Paradise, but Allah's mercy and generosity make it possible. The Prophet (peace be upon him) said: \"No one will enter Paradise by their deeds alone.\" Even he said he would only enter by Allah's mercy.",
    "He is truly All-Forgiving, Most Appreciative": "Allah is All-Forgiving (Ghafoor), meaning He covers and forgives the sins and shortcomings of His servants. He is also Most Appreciative (Shakoor), meaning He appreciates and generously rewards even the smallest good deeds. Imagine—the Creator of the universe appreciates our humble efforts! This should motivate us to do more good, knowing that nothing is wasted with Allah."
  },
  31: {
    "The Book We have revealed to you ˹O Prophet˺ is the truth": "The Quran revealed to Prophet Muhammad (peace be upon him) is absolutely true—every word, every verse, every teaching. It contains no falsehood, no contradictions, and no errors. It is the pure word of Allah, preserved exactly as it was revealed. In a world full of confusion and false claims, the Quran stands as the ultimate source of truth.",
    "confirming what came before it": "The Quran confirms and validates the previous scriptures—the Torah, Psalms, and Gospel—in their original forms. It affirms the core message that all prophets brought: worship Allah alone. However, the Quran also serves as a criterion to distinguish what has been preserved from what has been changed in earlier scriptures. This shows the continuity of Allah's message throughout history.",
    "Surely Allah is All-Aware, All-Seeing of His servants": "Allah has complete knowledge of all His servants—their conditions, needs, and what guidance suits them. He is All-Aware (Khabeer) of their inner states and All-Seeing (Baseer) of their outer actions. This is why He chose Muhammad (peace be upon him) as the final messenger and revealed the Quran as the final guidance—because He knew this was what humanity needed."
  },
  32: {
    "Then We granted the Book to those We have chosen from Our servants": "Allah gave the Quran as an inheritance to the Muslim ummah—the community chosen to receive and preserve the final revelation. Being chosen for this responsibility is an immense honor and blessing. It also comes with the duty to learn the Quran, act upon it, and convey its message to others.",
    "Some of them wrong themselves": "Among the Muslims who inherited the Quran, some wrong themselves by committing sins, being negligent in their duties, or falling short of what Allah requires. These are believers who have faith but struggle with consistent obedience. They believe in the Quran but do not always live up to its standards. Despite their shortcomings, they are still part of the chosen community and have hope for Allah's forgiveness.",
    "some follow a middle course": "Another group follows a moderate path—they fulfill their obligatory duties and avoid major sins, but they may not go beyond the minimum requirements. They do what is required but do not exert themselves in extra worship or voluntary good deeds. They are neither at the highest level nor falling into sin—they are in the middle.",
    "and some are foremost in good deeds by Allah's Will": "The best category consists of those who race ahead in doing good. They not only fulfill obligations but excel in voluntary worship, charity, and service to others. They are the first to respond to any call for good and the most eager to please Allah. This excellence is \"by Allah's Will,\" meaning their success comes from Allah's guidance and enabling grace, not just their own effort. We should all strive to be in this category.",
    "That is ˹truly˺ the greatest bounty": "Being part of the community that inherited the Quran and having the opportunity to be among those foremost in good deeds—this is the greatest blessing one can receive. Material wealth, fame, and power are nothing compared to being guided to Islam and given the chance to earn eternal Paradise."
  },
  33: {
    "They will enter the Gardens of Eternity": "All three categories of believers mentioned—even those who wronged themselves—will ultimately enter Paradise, the Gardens of Eternity (Jannatu Adn). This is a place of permanent residence where they will live forever, never to leave or die. The word \"Adn\" implies settling and remaining, giving believers the assurance of eternal security and peace.",
    "where they will be adorned with bracelets of gold and pearls": "In Paradise, the believers will be beautified with jewelry of gold and pearls. These adornments represent honor and beauty. Interestingly, gold jewelry is forbidden for Muslim men in this world, but in Paradise, such restrictions no longer apply. Everyone will be adorned with the finest decorations, reflecting their elevated status as honored guests of Allah.",
    "and their clothing will be silk": "The clothing in Paradise will be made of silk—the finest, most luxurious fabric. Like gold, silk is forbidden for men in this world, but Paradise has different rules. The Prophet (peace be upon him) said: \"Whoever wears silk in this world will not wear it in the Hereafter.\" Those who sacrificed worldly luxuries for Allah's sake will be compensated with far superior versions in Paradise."
  },
  34: {
    "And they will say, \"Praise be to Allah, Who has kept away from us all ˹causes of˺ sorrow": "Upon entering Paradise, the believers will express profound gratitude to Allah for removing all grief and worry from their lives. In this world, everyone faces sorrows—loss of loved ones, financial stress, health problems, fear of death, and countless other worries. In Paradise, all of this is gone forever. There will be no sadness, no anxiety, no fear, and no regret. This is the ultimate relief.",
    "Our Lord is indeed All-Forgiving, Most Appreciative": "The believers will acknowledge Allah's forgiveness that allowed them to enter Paradise despite their sins, and His appreciation that rewarded their humble deeds so generously. They will realize that their entry into Paradise was due to Allah's mercy, not their own worthiness. This produces deep gratitude and praise."
  },
  35: {
    "˹He is the One˺ Who—out of His grace—has settled us in the Home of Everlasting Stay": "The believers will recognize that their residence in Paradise is purely from Allah's grace and favor. They did not earn it through their deeds alone—it was a gift from their generous Lord. The \"Home of Everlasting Stay\" (Dar al-Muqamah) emphasizes permanence. Unlike worldly homes that we eventually leave, Paradise is forever.",
    "where we will be touched by neither fatigue nor weariness": "In Paradise, there will be no tiredness, exhaustion, or boredom. In this world, even pleasurable activities eventually become tiring. Work exhausts us, and even rest can become boring. But Paradise is designed differently—its pleasures never diminish, and its residents never tire. This is a state of eternal, effortless bliss that is hard for us to fully comprehend but wonderful to anticipate."
  },
  36: {
    "As for the disbelievers, they will have the Fire of Hell": "In stark contrast to the believers' reward, the disbelievers will face the Fire of Hell (Jahannam). This is not a metaphor—it is a real place of punishment prepared for those who rejected Allah and His messengers. The contrast between Paradise and Hell highlights the importance of faith and the gravity of disbelief.",
    "where they will not be ˹allowed to be˺ finished by death": "The disbelievers in Hell will not be granted the relief of death. They will wish to die to escape the torment, but death will not come to them. They will exist in a state of perpetual suffering without end. In this world, even the worst suffering eventually ends with death, but in Hell, there is no such escape.",
    "nor will its torment be lightened for them": "The punishment will never be reduced or eased. There will be no breaks, no moments of relief, and no gradual lessening of pain. The severity will remain constant forever. This emphasizes the eternal and unchanging nature of Hell's punishment for those who persist in disbelief until death.",
    "This is how We reward every ˹stubborn˺ disbeliever": "This punishment is the just recompense for those who stubbornly rejected the truth despite clear evidence and warnings. The word \"kafoor\" (stubborn disbeliever) implies someone who persistently covered up and denied the truth, not someone who was genuinely ignorant. Allah's justice ensures that everyone receives what they deserve."
  },
  37: {
    "There they will be ˹fervently˺ screaming, \"Our Lord! Take us out ˹and send us back˺": "The people of Hell will desperately cry out to Allah, begging to be taken out and given another chance. Their screaming reflects intense anguish and regret. They will finally acknowledge Allah as their Lord—something they denied or ignored in the worldly life—but by then it will be too late.",
    "We will do good, unlike what we used to do.\"": "They will promise to live differently if given another chance—to do good deeds instead of the evil they used to do. But this promise is made under duress and is not sincere repentance. Allah knows that if they were sent back, they would return to their old ways. The Quran says elsewhere: \"If they were returned, they would go back to what they were forbidden\" (6:28).",
    "˹They will be told,˺ \"Did We not give you lives long enough so that whoever wanted to be mindful could have done so?": "Allah responds by reminding them that they had sufficient time in the worldly life to reflect and change. Whether they lived twenty years or eighty years, they had opportunities to recognize the truth and follow it. The length of life given was enough for anyone who sincerely wanted guidance to seek it and find it.",
    "And the warner came to you": "Not only did they have time, but they also received clear warnings through prophets, books, and signs. The messenger came to them with guidance, but they rejected him. They cannot claim ignorance or lack of opportunity. They were warned, but they chose to ignore the warning.",
    "So taste ˹the punishment˺, for the wrongdoers have no helper": "The response is final and decisive: taste the punishment you earned through your choices. No one will come to help or rescue the wrongdoers. No intercessor, no advocate, no powerful ally will save them from what they brought upon themselves. This is the ultimate loneliness—abandoned by everything they used to rely on."
  },
  38: {
    "Indeed, Allah is the Knower of the unseen of the heavens and the earth": "Allah has complete knowledge of everything hidden in the heavens and earth—things that no creature can perceive. He knows what has happened, what is happening, and what will happen. Nothing in the entire universe is hidden from Him. This includes the plots of the disbelievers, the secrets people keep, and events that have not yet occurred.",
    "He surely knows best what is ˹hidden˺ in the heart": "More specifically, Allah knows the innermost thoughts, feelings, and intentions hidden in every heart. We can hide our thoughts from other people, but we cannot hide anything from Allah. He knows our sincere intentions and our hypocritical pretenses. This knowledge will be the basis of judgment—we will be held accountable not just for our actions but for the intentions behind them."
  },
  39: {
    "He is the One Who has placed you as successors on earth": "Allah has made human beings successors and caretakers on earth. Each generation inherits the earth from the previous one. This position comes with responsibility—we are being tested in how we use this trust. We are not the ultimate owners; we are temporary stewards who will be held accountable for how we managed what was given to us.",
    "So whoever disbelieves will bear ˹the burden of˺ their own disbelief": "The consequences of disbelief fall on the disbeliever alone. Their rejection of Allah harms no one but themselves. Allah is not affected by their disbelief—He remains the Almighty, and His kingdom is not diminished in the slightest. The loss is entirely theirs.",
    "The disbelievers' denial only increases them in contempt in the sight of their Lord": "With each act of disbelief and rejection, the disbelievers accumulate more of Allah's displeasure and anger. Instead of gaining anything through their denial, they only earn more contempt from their Creator. This is the opposite of what they think they are achieving.",
    "and it will only contribute to their loss": "Their disbelief adds to their loss in both worlds—loss of guidance and peace in this life, and loss of Paradise in the Hereafter. They think they are winning by rejecting faith, but in reality, they are bankrupting themselves spiritually and eternally."
  },
  40: {
    "Ask ˹them, O Prophet˺, \"Have you considered your associate-gods which you invoke besides Allah?": "Allah instructs the Prophet to challenge the polytheists about their false gods. Make them think critically about what they worship. Who are these beings they call upon instead of Allah? What have they actually done to deserve worship?",
    "Show me what they have created on earth!": "This is a powerful challenge: present evidence of your gods' creative power. Have they created any land, any creature, any plant? The answer is obviously no. They have created nothing. Only Allah creates, so only Allah deserves worship. This argument is simple and irrefutable.",
    "Or do they have a share in ˹the creation of˺ the heavens?": "Did these false gods participate in creating the heavens? Did they help Allah in any way? Again, the answer is no. They had no role in creation whatsoever. How can something that did not create anything be worthy of worship alongside the Creator?",
    "Or have We given the polytheists a Book, which serves as a clear proof for them?": "Is there any divine scripture that commands or justifies worshipping these idols? Has Allah ever revealed a book authorizing polytheism? No such book exists. The polytheists have no textual evidence for their beliefs—they are following baseless assumptions and inherited traditions.",
    "In fact, the wrongdoers promise each other nothing but delusion": "The reality is that the polytheists only offer each other empty promises and false hopes. Their leaders tell them their gods will help them, and they pass these lies to each other. But it is all delusion—self-deception that will be exposed on the Day of Judgment."
  },
  41: {
    "Indeed, Allah ˹alone˺ keeps the heavens and the earth from falling apart": "Allah maintains the entire universe in its precise order. The heavens and earth continue to exist and function because Allah holds them in place. The gravitational forces, the orbits of planets, the balance of ecosystems—all of this is sustained by Allah's continuous command. Without His support, everything would collapse into chaos.",
    "If they were to fall apart, none but Him could hold them up": "If Allah were to release His hold on the universe, no one else could prevent its destruction. No human technology, no false god, no force in existence could maintain cosmic order. This demonstrates Allah's absolute power and the complete dependence of all creation on Him.",
    "He is truly Most Forbearing, All-Forgiving": "Despite humanity's sins, ingratitude, and disobedience, Allah continues to sustain the universe and provide for His creation. He does not immediately destroy the world because of our wrongdoing. His forbearance (Hilm) gives people time to repent, and His forgiveness (Ghufran) is available to those who turn back to Him. These attributes show Allah's mercy alongside His power."
  },
  42: {
    "They swore by Allah their most solemn oaths that if a warner were to come to them, they would certainly be better guided than any other community": "Before the Prophet came, the Arab polytheists used to criticize Jews and Christians for rejecting their prophets. They would swear by Allah that if a prophet came to them, they would be the best followers—more guided than any previous nation. They were confident in their own righteousness and critical of others.",
    "Yet when a warner did come to them, it only drove them farther away": "But when Prophet Muhammad (peace be upon him) actually came with clear guidance, instead of accepting him as they claimed they would, they rejected him and moved even further from the truth. Their earlier oaths were exposed as empty words. This shows the danger of self-righteousness and how easy it is to criticize others while failing oneself."
  },
  43: {
    "behaving arrogantly in the land and plotting evil": "Their rejection was rooted in arrogance—they were too proud to follow a prophet from among themselves. They also engaged in evil plotting against the Prophet and the believers, trying to harm them and stop the spread of Islam.",
    "But evil plotting only backfires on those who plot": "A fundamental divine law is that evil schemes ultimately harm the schemers themselves. The Quraysh plotted against the Prophet, but their plots failed and they were defeated. Throughout history, tyrants who plotted against truth ended up destroyed by their own schemes. This should give comfort to believers and warning to plotters.",
    "Are they awaiting anything but the fate of those ˹destroyed˺ before?": "Are these disbelievers waiting for the same destruction that befell previous nations who rejected their prophets? Do they think they are exempt from Allah's punishment? History is full of examples of destroyed civilizations.",
    "You will find no change in the way of Allah, nor will you find it diverted ˹to someone else˺": "Allah's way of dealing with nations does not change. Those who reject prophets and persist in arrogance face destruction. This divine law applied to previous nations and will apply to current and future ones as well. No one is exempt, and the pattern never changes."
  },
  44: {
    "Have they not travelled throughout the land to see what was the end of those ˹destroyed˺ before them?": "Allah encourages people to travel and observe the ruins of ancient civilizations that were destroyed because of their disbelief. The remains of Ad, Thamud, Pharaoh's people, and others serve as physical evidence of Allah's punishment. Traveling and seeing these ruins should be a source of reflection and lesson.",
    "They were far superior in might": "Those previous nations were stronger, more powerful, and more advanced than the Quraysh. They built impressive structures and had vast resources. Yet all their power could not save them from Allah's punishment when it came. If mightier nations were destroyed, what makes the Quraysh think they are safe?",
    "But there is nothing that can escape Allah in the heavens or the earth": "Nothing can escape Allah's power or knowledge—whether in the heavens or on earth. No matter how powerful or clever someone is, they cannot outrun Allah's decree. When He decides to punish, nothing can prevent it.",
    "He is certainly All-Knowing, Most Capable": "Allah combines perfect knowledge with complete power. He knows who deserves punishment and has the full ability to carry it out. These two attributes together mean that justice is inevitable and inescapable."
  },
  45: {
    "If Allah were to punish people ˹immediately˺ for what they have committed, He would not have left a single living being on earth": "This powerful statement reveals the extent of human sin and Allah's immense mercy. If Allah punished every sin immediately, no creature would survive on earth—the consequences of human wrongdoing would affect all living things. This shows how serious sins are and how dependent we all are on Allah's patience and forgiveness.",
    "But He delays them for an appointed term": "Instead of immediate punishment, Allah gives people time—time to reflect, repent, and change their ways. This delay is not because Allah is unaware or unable; it is a mercy giving people opportunities to return to Him. Every day we live without being punished is a gift and a chance to seek forgiveness.",
    "And when their time arrives, then surely Allah is All-Seeing of His servants": "When the appointed time comes—whether individual death or collective destruction—Allah will act with full knowledge of what each person deserves. He sees everything: the public actions and the private secrets, the arrogant rejections and the humble repentance. His judgment will be based on complete and perfect knowledge, and no one will be wronged."
  }
};