var tafsirData_41 = {
  1: {
    "Ḥâ-Mĩm": "These are disconnected Arabic letters that appear at the beginning of some chapters of the Quran. Their precise meaning is known only to Allah. Scholars suggest they serve to capture attention, demonstrate the miraculous nature of the Quran (composed of letters Arabs knew, yet they could not produce anything like it), and to affirm that this Book is divinely revealed. These letters remind us that the Quran contains depths of meaning and wisdom that human intellect may not fully grasp."
  },
  2: {
    "˹This is˺ a revelation": "This Quran is not a product of human imagination or invention. It is a divine communication sent down from above the heavens, carrying absolute truth and guidance for all humanity.",
    "from the Most Compassionate, Most Merciful": "The source of this revelation is Allah Himself, Who is characterized by boundless mercy. The fact that He sent this guidance is itself an act of mercy—He did not leave humanity to wander in darkness but provided a clear light to guide them to success in this life and the next."
  },
  3: {
    "˹It is˺ a Book whose verses are perfectly explained": "Every verse of this Quran has been made clear and distinct. Its meanings are elaborated, its rulings are detailed, and its stories are told with purpose. There is no ambiguity or confusion in its core message—it distinguishes between right and wrong, lawful and unlawful, and truth and falsehood.",
    "a Quran in Arabic": "It was revealed in the Arabic language, the tongue of the Prophet Muhammad (peace be upon him) and his people, so they could understand it directly without any barrier. Arabic was chosen for its richness and precision in conveying the profound meanings of divine guidance.",
    "for people who know": "This Book is especially beneficial for those who use their intellect, reflect deeply, and sincerely seek understanding. It is not that others cannot benefit, but those who approach it with knowledge and a sincere heart will grasp its treasures most fully."
  },
  4: {
    "delivering good news and warning": "The Quran serves two essential purposes: it gives glad tidings of Paradise, Allah's pleasure, and eternal rewards to those who believe and do righteous deeds. Simultaneously, it warns of Hellfire, Allah's punishment, and severe consequences for those who reject faith and persist in wrongdoing. This balanced approach of hope and fear is meant to motivate people toward good and away from evil.",
    "Yet most of them turn away": "Despite the clarity and mercy embedded in this revelation, the majority of people choose to ignore it. They deliberately avert their attention from the truth, preferring their old ways, desires, and false beliefs over divine guidance.",
    "so they do not hear": "Their turning away is so complete that it is as if they cannot hear at all. This is not physical deafness but a spiritual blockage—they refuse to let the message enter their hearts. When someone is determined not to accept the truth, even the clearest evidence becomes meaningless to them."
  },
  5: {
    "They say, \"Our hearts are veiled against what you are calling us to": "The disbelievers mockingly tell the Prophet (peace be upon him) that their hearts are completely sealed and covered, preventing his message from reaching them. They claim there is a barrier around their hearts that blocks any influence from his teachings about monotheism and the Hereafter. This is their way of expressing total unwillingness to even consider the truth.",
    "there is deafness in our ears": "They further claim that their ears are blocked, as if they have a hearing impairment that prevents them from understanding his words. Of course, they could hear him physically, but they are saying they have no interest in listening or comprehending his message spiritually.",
    "and there is a barrier between us and you": "They declare that an insurmountable wall exists between themselves and the Prophet—a barrier of beliefs, values, and ways of life. They are essentially saying: 'We are on completely different paths, and there is no meeting point between us.'",
    "So do ˹whatever you want˺ and so shall we!": "This is a statement of defiance and challenge. They tell the Prophet to continue doing what he does, and they will continue doing what they do. It reflects arrogance and a refusal to engage with the message. It is as if they are saying: 'You go your way, and we will go ours—we are not interested in your guidance.' This attitude of stubborn rejection is one of the greatest obstacles to accepting truth."
  },
  6: {
    "Say, ˹O Prophet,˺ \"I am only a man like you": "Allah instructs His Messenger to clarify his nature to the people. The Prophet is a human being, not an angel or a divine figure. He eats, drinks, sleeps, and experiences human conditions. This statement removes any misconception about worshipping the Prophet or attributing divine qualities to him. His humanity makes him relatable—he is an example for people to follow, showing that a human can live according to Allah's guidance.",
    "˹but˺ it has been revealed to me that your God is only One God": "The key distinction between the Prophet and other people is that he receives divine revelation. The core message revealed to him is simple and profound: there is only One God worthy of worship—Allah. There are no partners, no intermediaries, and no other deities. This is the essence of Islam and the foundation of all prophetic messages throughout history.",
    "So take the Straight Way towards Him": "Once you know that there is only One God, the logical response is to direct yourself entirely toward Him. This means following the path of obedience, sincere worship, and righteous conduct. It requires consistency and steadfastness in faith, not wavering between truth and falsehood.",
    "and seek His forgiveness": "Human beings are prone to mistakes and sins. Therefore, an essential part of the journey to Allah is constantly seeking His forgiveness. No matter how much one strays, the door of repentance is always open. Allah loves those who turn back to Him sincerely.",
    "And woe to the polytheists": "A severe warning is issued to those who associate partners with Allah. 'Woe' indicates destruction, severe punishment, and loss. Polytheism (shirk) is the greatest sin in Islam because it contradicts the very foundation of monotheism that all prophets were sent to establish."
  },
  7: {
    "those who do not pay alms-tax": "The polytheists are further described by their refusal to give zakah (obligatory charity). Zakah is not just a financial obligation; it is a means of purifying wealth and the soul, and it demonstrates care for the community. Their refusal shows selfishness, greed, and a lack of social responsibility—all stemming from their rejection of Allah's commands. True faith manifests in actions, and refusing to help others is a sign of a diseased heart.",
    "and are in denial of the Hereafter": "They also reject belief in the Day of Judgment, the resurrection, and accountability before Allah. This denial is at the root of their immoral behavior—if one does not believe they will face consequences for their actions, they feel free to do as they please. Belief in the Hereafter is a powerful motivator for good conduct and restraint from evil."
  },
  8: {
    "˹But˺ those who believe and do good": "In contrast to the polytheists, Allah describes the believers. True faith is not merely a claim in the heart; it must be accompanied by righteous actions. Belief and good deeds go hand in hand in Islam—one without the other is incomplete. The believers worship Allah alone and translate that belief into positive actions in their daily lives.",
    "will certainly have a never-ending reward": "Their reward is described as 'never-ending' (ghayru mamnoon), meaning it will never be cut off, diminished, or interrupted. Unlike worldly rewards that are temporary, the rewards of the Hereafter—Paradise and its blessings—are eternal. This is the ultimate success and the greatest motivation for believers to remain steadfast in their faith and deeds."
  },
  9: {
    "Ask ˹them, O Prophet˺, \"How can you disbelieve in the One Who created the earth in two Days?": "The Prophet is instructed to pose a thought-provoking question to the disbelievers. How is it possible to deny the One Who brought the earth into existence in two Days? The creation of the earth—with all its complexity, beauty, and systems—is a clear sign of Allah's power and wisdom. The 'Days' mentioned here refer to periods of time known to Allah, not necessarily 24-hour days as we understand them.",
    "And how can you set up equals with Him?": "After acknowledging that Allah created the earth, how can anyone logically worship others besides Him? The idols and false gods they worship did not create anything. This rhetorical question exposes the absurdity of polytheism—attributing divine qualities to things that have no power whatsoever.",
    "That is the Lord of all worlds": "This Creator is not just a local deity or a god among many gods. He is the Lord (Rabb) of all that exists—every universe, every creature, every atom. He alone deserves worship, obedience, and devotion."
  },
  10: {
    "He placed on the earth firm mountains, standing high": "Allah anchored the earth with mountains that tower above the landscape. These mountains serve to stabilize the earth, preventing excessive shaking and providing balance. Modern geology confirms the role of mountains in stabilizing tectonic plates. This is one of the many signs of Allah's perfect design.",
    "showered His blessings upon it": "Allah blessed the earth with everything needed for life to flourish—water, vegetation, animals, minerals, and countless other resources. Every provision we enjoy is a blessing from Allah, placed on this earth for our benefit.",
    "and ordained ˹all˺ its means of sustenance": "Allah determined and proportioned the sustenance for all creatures on earth. Every living being has its provision allocated by Allah—from the smallest insect to the largest whale. Nothing is left to chance; everything is planned with divine wisdom.",
    "totaling four Days exactly": "The creation of the earth (two Days) plus the establishment of mountains, blessings, and provisions brings the total to four Days. This is a precise measurement emphasizing that Allah's creation follows a deliberate plan and timeline, not randomness.",
    "for all who ask": "This sustenance is available to all who seek it. Allah provides for every creature, and His provisions are sufficient for all. Those who ask Allah sincerely will find their needs met according to His wisdom."
  },
  11: {
    "Then He turned towards the heaven when it was ˹still like˺ smoke": "After creating the earth, Allah directed His will toward the heaven (the sky and everything above). At that stage, the heaven was in a state resembling smoke—perhaps a primordial gaseous state. Modern science speaks of the early universe being filled with gas and dust, which aligns with this description. This shows the Quran's remarkable accuracy in describing creation.",
    "saying to it and to the earth, 'Submit, willingly or unwillingly.'": "Allah commanded both the heaven and the earth to come into being and function according to His will. The choice given—'willingly or unwillingly'—demonstrates Allah's absolute power. Nothing can resist His command. Whether creation obeys joyfully or is compelled, the result is the same: Allah's will prevails.",
    "They both responded, 'We submit willingly.'": "The heaven and earth responded with complete obedience, declaring their willing submission to Allah. This personification teaches us that all creation recognizes Allah's authority and submits to Him. Unlike some humans who rebel, the rest of creation obeys without hesitation. This should humble us and encourage us to submit willingly to our Creator."
  },
  12: {
    "So He formed the heaven into seven heavens in two Days": "Allah completed the formation of the seven heavens in two Days. These seven heavens are layers above us, each with its own characteristics and inhabitants (such as angels). The total creation period of the heavens and earth is six Days, as mentioned elsewhere in the Quran. This shows order and deliberation in creation, not haste.",
    "assigning to each its mandate": "Each heaven received its own set of functions, laws, and responsibilities. Allah revealed to each heaven what it needed to fulfill its role in the grand design of creation. Everything in the universe operates according to Allah's precise commands.",
    "And We adorned the lowest heaven with ˹stars like˺ lamps ˹for beauty˺": "The sky we see—the lowest heaven—is beautified with stars that shine like lamps. Looking at the night sky, we witness the stunning beauty of Allah's creation. These stars serve as decoration, making the universe aesthetically pleasing.",
    "and for protection": "The stars also serve a protective function. In Islamic understanding, shooting stars (meteors) are used to repel devils (shayateen) who try to eavesdrop on the heavens. This protection ensures the purity of divine revelation and the order of the heavens.",
    "That is the design of the Almighty, All-Knowing": "This magnificent creation is the work of Allah, Who is Al-Aziz (the Almighty, possessing all power) and Al-Aleem (the All-Knowing, possessing perfect knowledge). Only One with infinite power and knowledge could design and execute such a flawless creation. This should inspire awe, gratitude, and submission in every human heart."
  },
  13: {
    "If they turn away": "If these disbelievers persist in their rejection despite all the clear evidence of Allah's existence and power in creation, then the Prophet is instructed to deliver a stern warning.",
    "then say, ˹O Prophet,˺ \"I warn you of a ˹mighty˺ blast": "The Prophet is to warn them of a devastating punishment—a thunderbolt or destructive blast that will annihilate them. This is not an empty threat but a promise based on historical precedent.",
    "like the one that befell 'Ȃd and Thamûd.\"": "The punishment that will come is similar to what destroyed the ancient peoples of 'Ȃd and Thamûd. These were powerful civilizations in Arabia that were completely wiped out due to their rejection of Allah's messengers. The pagan Arabs were familiar with these stories and even passed by the ruins of these peoples during their trade journeys. This reference makes the warning very real and relatable to them."
  },
  14: {
    "The messengers had come to them from all angles": "Prophets and messengers were sent to 'Ȃd and Thamûd repeatedly, approaching them from different directions and times. The message was delivered consistently and comprehensively—they had no excuse for ignorance. 'From before them and behind them' indicates that guidance was available from previous generations and their own time.",
    "˹proclaiming,˺ \"Worship none but Allah.\"": "The core message of every prophet was the same: pure monotheism. Worship Allah alone, without associating any partners with Him. This was the message of Hud to 'Ȃd and Salih to Thamûd, just as it was the message of Muhammad (peace be upon him) to the Quraysh.",
    "They responded, \"Had our Lord willed, He could have easily sent down angels ˹instead˺.": "Their response was full of arrogance and excuses. They argued that if Allah truly wanted to send a message, He would have sent angels, not human messengers. This excuse was a way to avoid accepting the truth. They held human messengers in contempt, not realizing that sending humans was actually a mercy—someone they could relate to and learn from.",
    "So we totally reject what you have been sent with.\"": "Despite all evidence and reasoning, they declared total rejection of the message. This stubborn denial, not based on logic but on pride and desire, sealed their fate."
  },
  15: {
    "As for 'Ȃd, they acted arrogantly throughout the land with no right": "The people of 'Ȃd were known for their physical power and impressive civilization. However, they used their strength for arrogance and oppression, not justice. They behaved as if they were above all laws—divine or moral. Their arrogance had no justification; it was 'without right.'",
    "boasting, \"Who is superior to us in might?\"": "They became so proud of their strength that they challenged anyone to match them. This boastful attitude blinded them to their own vulnerability. They forgot that all power ultimately belongs to Allah and that He could take it away in an instant.",
    "Did they not see that Allah ˹Himself˺, Who created them, was far superior to them in might?": "This rhetorical question exposes their foolishness. The very One who created them—who gave them their strength in the first place—is infinitely more powerful than they could ever be. How could they think they were mighty when compared to the Creator of the universe?",
    "Still they persisted in denying Our signs": "Despite the clear logic and evidence, they continued to reject Allah's signs—both the signs in nature and the signs brought by the messengers. Their denial was deliberate and persistent, which made their punishment inevitable."
  },
  16: {
    "So We sent against them a furious wind": "Allah's punishment came in the form of a violent, freezing, and destructive wind. This was not an ordinary storm but a divinely sent catastrophe. The wind was so powerful that it lifted people and threw them down, destroying everything in its path.",
    "for ˹several˺ miserable days": "This wind lasted for seven nights and eight days continuously, as mentioned in Surah Al-Haqqah (69:7). These were days of utter misery, disaster, and doom for the people of 'Ȃd. They had no escape and no relief.",
    "to make them taste a humiliating punishment in this worldly life": "The punishment was not just physical destruction but also humiliation. Those who had boasted of their might were now completely helpless against the wind. Their pride was shattered along with their civilization. This humiliation in the worldly life was a direct consequence of their arrogance.",
    "But far more humiliating will be the punishment of the Hereafter": "As terrible as their worldly destruction was, it is nothing compared to what awaits them in the Hereafter. The punishment of Hell is far more severe, lasting, and humiliating. The worldly punishment was temporary, but the Hereafter's punishment is eternal.",
    "And they will not be helped": "On the Day of Judgment, no one will be able to help or intercede for them. The allies and false gods they relied upon will abandon them. Only those whom Allah allows to intercede will be able to speak, and that will not be granted for those who died in disbelief."
  },
  17: {
    "As for Thamûd, We showed them guidance": "Allah provided Thamûd with clear guidance through their prophet Salih (peace be upon him). He showed them the truth, gave them signs (including the miraculous she-camel), and warned them of the consequences of disbelief. Guidance was made available to them; they were not left in ignorance.",
    "but they preferred blindness over guidance": "Despite having access to guidance, they chose to remain in misguidance. They 'preferred' blindness—they actively chose to reject the truth because it conflicted with their desires and pride. This is the tragedy of free will misused: when people deliberately choose darkness over light.",
    "So the blast of a disgracing punishment overtook them": "Their punishment came as a terrifying blast—a thunderbolt or earthquake that destroyed them completely. This punishment was 'disgracing' because it exposed their weakness and humiliated them before all creation. They had rejected Allah's guidance, so they received Allah's punishment.",
    "for what they used to commit": "The punishment was not arbitrary or unjust. It was a direct consequence of their actions—their arrogance, their rejection of the prophet, their killing of the she-camel, and their persistent sins. Allah is just; He punishes based on what people earn through their deeds."
  },
  18: {
    "And We delivered those who were faithful": "While the disbelievers were destroyed, Allah saved the believers from among them. This shows Allah's justice and mercy—He does not punish the innocent along with the guilty. Those who believed in Prophet Salih and followed his guidance were rescued before the punishment descended.",
    "and were mindful ˹of Allah˺": "The saved ones were not just believers in name; they were also people of taqwa—those who were conscious of Allah, feared His punishment, and strove to obey His commands. True faith is accompanied by mindfulness and righteousness. This is a message of hope: no matter how corrupt a society becomes, the sincere believers will always have Allah's protection."
  },
  19: {
    "˹Consider˺ the Day ˹when˺ the enemies of Allah will be gathered for the Fire": "On the Day of Judgment, those who opposed Allah, rejected His messengers, and fought against His religion will be assembled for their final destination: the Hellfire. Being described as 'enemies of Allah' is the most severe condemnation—these are people who actively worked against divine guidance throughout their lives.",
    "all driven in ranks": "They will be organized and driven in rows, like prisoners being led to their punishment. There will be no escape, no hiding, and no delay. Angels will herd them toward the Fire in a humiliating procession. The order and organization show that Judgment Day will be conducted with precision and justice."
  },
  20: {
    "When they reach it": "When these enemies of Allah finally arrive at the Hellfire, a shocking event will occur. Their own bodies will turn against them.",
    "their ears, eyes, and skin will testify against what they used to do": "Their own body parts—the very organs they used to commit sins—will speak and bear witness against them. The ears will testify about what they listened to: forbidden conversations, backbiting, lies, and rejection of truth. The eyes will testify about what they looked at: forbidden sights, evil they witnessed but did not prevent, and truth they refused to see. The skin will testify about what they touched and did with their bodies: physical sins and crimes. This is a terrifying concept that shows nothing will remain hidden on Judgment Day."
  },
  21: {
    "They will ask their skin ˹furiously˺, \"Why have you testified against us?\"": "In shock and anger, the disbelievers will turn to their own skin and demand an explanation. They will be outraged that their own bodies have betrayed them. This shows the depth of their denial—even at this stage, they are upset about being exposed rather than remorseful for their sins.",
    "It will say, \"We have been made to speak by Allah, Who causes all things to speak.": "The skin will respond that it had no choice in the matter. Allah, Who has power over all things, gave it the ability to speak. If Allah can cause all things to speak—the heavens, the earth, the animals—then certainly He can cause body parts to testify. Nothing is beyond Allah's power.",
    "He ˹is the One Who˺ created you the first time": "Allah created them initially from nothing. If He could create them the first time, He can certainly resurrect them and give their organs the ability to speak. Creation from nothing is a greater feat than making organs testify.",
    "and to Him you were bound to return.\"": "The return to Allah was always inevitable. Death and resurrection were never in doubt for those with true understanding. They will now face the consequences of everything they did, with witnesses they never anticipated."
  },
  22: {
    "You did not ˹bother to˺ hide yourselves from your ears, eyes, and skin": "When they committed their sins, they never thought to hide from their own body parts. They may have hidden from other people, locked doors, and committed sins in secret. But they never considered that their own organs were witnessing everything. This is a profound reminder: we are never truly alone when we sin.",
    "to prevent them from testifying against you": "They made no effort to conceal their actions from these witnesses because they never imagined that ears, eyes, and skin could speak. The concept never occurred to them.",
    "Rather, you assumed that Allah did not know much of what you used to do": "Here lies the root of their problem: a faulty assumption about Allah. They thought Allah did not see, did not know, or did not care about much of what they did. This mistaken belief allowed them to sin freely. They underestimated Allah's knowledge, which encompasses everything—every thought, every whisper, every secret deed."
  },
  23: {
    "It was that ˹false˺ assumption you entertained about your Lord": "The wrong belief they held about Allah—that He was unaware of their deeds—was the cause of their destruction. Our assumptions about Allah shape our behavior. If we believe Allah is All-Knowing, All-Seeing, and Just, we will act accordingly. If we downplay His knowledge, we become careless in our conduct.",
    "that has brought about your doom": "This false assumption ruined them. It led them to sin without fear, reject guidance without concern, and live as if there were no consequences. The assumptions we hold about Allah are critical—they can lead us to Paradise or to destruction.",
    "so you have become losers.\"": "The ultimate outcome of their false beliefs and subsequent sins is loss—complete and total loss. They lost the opportunity for guidance in this life, lost their chance for Paradise, and earned eternal punishment instead. This is the worst type of loss, for it is irreversible."
  },
  24: {
    "Even if they endure patiently, the Fire will ˹always˺ be their home": "Whether they bear the punishment with patience or cry out in desperation, it makes no difference. The Fire will be their permanent abode. Unlike worldly trials where patience is rewarded and brings relief, in Hell there is no relief from patience. The punishment is eternal, and their residence there is permanent.",
    "And if they ˹beg to˺ appease ˹their Lord˺, they will never be allowed to.": "If they try to seek forgiveness, make amends, or ask for another chance, their requests will be denied. The time for repentance was in the worldly life. Once death comes and Judgment is passed, the door of forgiveness closes for those who died in disbelief. This is a sobering warning for those still alive: the opportunity to repent exists only now, in this life. Once it is over, no amount of pleading will help."
  },
  25: {
    "We placed at their disposal ˹evil˺ associates": "Allah, as part of His divine decree, assigned evil companions to these disbelievers. These companions include devils from among the jinn and corrupt humans who reinforce each other in misguidance. This is not injustice from Allah; rather, it is a consequence of the disbelievers' own choices. When someone persistently chooses evil, Allah allows them to be surrounded by those who further lead them astray. The Prophet (peace be upon him) said: 'A person is upon the religion of his close friend, so let each of you look at whom he befriends.' (Abu Dawud). This shows the critical importance of choosing righteous companions.",
    "who made their past and future ˹misdeeds˺ appealing to them": "These evil associates beautified sins for them—both the sins they had already committed and those they planned to commit. They made past wrongdoings seem acceptable ('It wasn't that bad') and future sins seem attractive ('There's no harm in this'). This is how evil companions operate: they normalize sin and make righteousness seem outdated or unnecessary.",
    "˹So˺ the fate of earlier communities of jinn and humans has been justified against them ˹as well˺": "The same divine decree of punishment that applied to previous rebellious nations of jinn and humans now applies to these disbelievers too. They followed the same path of rejection, so they deserve the same end. The word of Allah's punishment became binding upon them, just as it did upon those before them.",
    "˹for˺ they were truly losers": "Their ultimate outcome is loss—complete and irreversible loss. They lost guidance in this world and salvation in the Hereafter. Despite having the opportunity to believe, they chose denial, and thus they lost everything that truly matters."
  },
  26: {
    "The disbelievers advised ˹one another˺, \"Do not listen to this Quran": "The leaders among the disbelievers instructed their followers to avoid listening to the Quran altogether. They knew the Quran was powerful and persuasive—they feared that if people truly listened to it, they would be moved to believe. This was a deliberate strategy to prevent the truth from reaching hearts.",
    "but drown it out so that you may prevail.\"": "Their tactic was to make noise, create distractions, and interrupt the recitation so that no one could hear and reflect upon the Quran's message. They would clap, whistle, shout, and make all kinds of disturbances when the Prophet (peace be upon him) recited. They thought that by drowning out the message, they could defeat Islam. This shows their desperation—they couldn't refute the Quran intellectually, so they resorted to disruption. This tactic continues today in various forms whenever truth is being conveyed."
  },
  27: {
    "So We will certainly make the disbelievers taste a severe punishment": "Allah responds to their plotting with a firm promise: they will definitely experience a harsh punishment. The word 'taste' indicates they will feel it intensely and personally. There is no escaping this consequence for their deliberate rejection and obstruction of the truth.",
    "and We will surely repay them according to the worst of their deeds": "Their recompense will be based on their most evil actions. While Allah, in His mercy, may overlook some sins for believers, for persistent disbelievers who die in that state, their worst deeds become the standard of their punishment. Every scheme against Islam, every effort to prevent others from guidance, will be accounted for."
  },
  28: {
    "That is the reward of Allah's enemies: the Fire": "Being labeled an 'enemy of Allah' is the most severe condemnation. These are people who actively opposed divine guidance, fought against the truth, and worked to extinguish Allah's light. Their appropriate recompense is the Fire of Hell.",
    "which will be their eternal home": "This is not a temporary punishment but a permanent residence. The word 'eternal' (khuld) emphasizes that there is no end to their stay in Hell. They will dwell there forever, with no hope of release or relief.",
    "a ˹fitting˺ reward for their denial of Our revelations": "This punishment is perfectly just—it matches their crime. They denied Allah's clear signs and revelations despite understanding them. They weren't ignorant; they were deliberately rejecting. Therefore, their punishment is proportional to their persistent denial."
  },
  29: {
    "The disbelievers will ˹then˺ cry, \"Our Lord! Show us those jinn and humans who led us astray": "In the depths of Hell, the disbelievers will cry out to Allah, demanding to see those who misled them. They will want to identify the evil companions—both jinn (devils) and humans (corrupt leaders, friends, and influencers)—who beautified sin for them and led them away from the truth.",
    "we will put them under our feet so that they will be among the lowest ˹in Hell˺.\"": "They express their rage by wanting to trample these misleaders underfoot, wishing them to be in the lowest and most severe levels of Hell. This shows the hostility that will exist between former allies in evil on Judgment Day. Those who were friends in sin will become bitter enemies. As Allah says elsewhere: 'Close friends will be enemies to one another on that Day—except for the righteous.' (43:67). This is a warning to choose our companions wisely in this life."
  },
  30: {
    "Surely those who say, \"Our Lord is Allah,\"": "These are people who declare their faith in Allah as their only Lord—the Creator, Sustainer, and the only One worthy of worship. This declaration is not merely verbal; it comes from the heart with full conviction and sincerity.",
    "and then remain steadfast": "After making this declaration, they follow it with consistent action. They remain firm on the straight path, not deviating to the right or left. Steadfastness (istiqamah) means continuing to practice Islam through all circumstances—in ease and hardship, in youth and old age, in private and public. Abu Bakr (may Allah be pleased with him) explained istiqamah as 'not associating anything with Allah.' Umar ibn al-Khattab (may Allah be pleased with him) said it means 'being steadfast on the commands and prohibitions, not being cunning like a fox.' The Prophet (peace be upon him) said: 'Say: I believe in Allah, then be steadfast.' (Muslim).",
    "the angels descend upon them": "For such believers, angels come down to them. Scholars mention this happens at the time of death, in the grave, and on the Day of Resurrection. These are comforting angels who bring peace and reassurance during the most frightening moments.",
    "˹saying,˺ \"Do not fear, nor grieve": "The angels address their two greatest concerns: fear of the future (what lies ahead after death) and grief over the past (what they are leaving behind—family, possessions, worldly life). The angels reassure them that there is nothing to fear in what is coming and nothing to grieve over what is being left.",
    "Rather, rejoice in the good news of Paradise, which you have been promised.\"": "Instead of fear and grief, they are given a reason for joy: Paradise awaits them. This is the fulfillment of Allah's promise to the believers. What greater news could there be than confirmation that one has earned eternal bliss?"
  },
  31: {
    "We are your supporters in this worldly life and in the Hereafter": "The angels declare their protective companionship of the believers. In this world, the angels support believers by recording their good deeds, protecting them from harm by Allah's permission, and inspiring them toward good. In the Hereafter, they continue this support by welcoming them to Paradise, honoring them, and serving them. The believer is never alone—Allah's noble angels are always near.",
    "There you will have whatever your souls desire": "In Paradise, every wish and desire of the believers will be fulfilled. Whatever their hearts long for—delicious food, beautiful scenery, reunion with loved ones, endless peace—it will all be available without limit or end.",
    "and there you will have whatever you ask for": "Beyond even their desires, anything they request will be granted. If they ask for something they hadn't even thought of, it will be provided. Paradise is the ultimate fulfillment of every legitimate wish, and even things beyond imagination will be offered to its inhabitants."
  },
  32: {
    "an accommodation from the All-Forgiving, Most Merciful ˹Lord˺": "All of these blessings are described as 'nuzul'—a welcoming gift or hospitality offered to an honored guest. When an important guest arrives, the host prepares the finest accommodation and treats them with generosity. The believers in Paradise will be treated as honored guests of the Most High. And Who is their Host? Al-Ghafoor (the All-Forgiving)—the One Who forgave their sins and overlooked their shortcomings; and Ar-Raheem (the Most Merciful)—the One whose special mercy is reserved for the believers. This combination of forgiveness and mercy is the reason believers enter Paradise in the first place—not merely because of their deeds, but because of Allah's grace."
  },
  33: {
    "And whose words are better than someone who calls ˹others˺ to Allah": "This is a rhetorical question with an obvious answer: no speech is better than calling people to Allah. The one who invites others to worship Allah alone, to follow His guidance, and to prepare for the Hereafter is doing the noblest work with their tongue. The Prophet (peace be upon him) said: 'Whoever guides someone to good will have a reward similar to the one who does it.' (Muslim). This includes scholars, teachers, parents, and anyone who sincerely shares Islamic guidance.",
    "does good": "The caller to Allah does not merely speak; they also act. Their life is a demonstration of what they preach. This prevents hypocrisy—how can one call others to pray while neglecting prayer themselves? The most effective dawah (invitation to Islam) is through exemplary conduct combined with words.",
    "and says, \"I am truly one of those who submit.\"?": "The caller proudly identifies as a Muslim—one who submits to Allah. They are not ashamed of their faith or trying to hide their identity. This open declaration, combined with their good deeds and invitation to others, makes them the best of speakers. Aisha (may Allah be pleased with her) said this verse refers to those who call the adhan (call to prayer) and also applies to anyone who calls to Allah's path."
  },
  34: {
    "Good and evil cannot be equal": "There is a fundamental difference between good and evil, right and wrong, kindness and cruelty. They cannot be treated the same or produce the same results. Someone who does good deserves different treatment than someone who does evil. This is a universal truth that applies to deeds, words, and intentions.",
    "Respond ˹to evil˺ with what is best": "When someone wrongs you, the recommended response is not to retaliate with equal evil, but to respond with something better—patience, forgiveness, kindness, or even a favor. This is not weakness; it is strength and nobility. The Prophet (peace be upon him) exemplified this throughout his life, forgiving even his worst enemies when he had power over them.",
    "then the one you are in a feud with will be like a close friend": "The remarkable outcome of responding to evil with good is the transformation of relationships. Your enemy may become your closest friend. When someone expects hostility and receives kindness instead, it often softens their heart and changes their attitude. This is the power of good character—it wins hearts and removes enmity. History is filled with examples of people who entered Islam because of the Prophet's noble treatment of them despite their past hostility."
  },
  35: {
    "But this cannot be attained except by those who are patient": "Responding to evil with good is not easy. It requires tremendous patience and self-control. When someone insults you, your natural instinct is to respond in kind. Overcoming this instinct requires inner strength that comes from faith, discipline, and a higher perspective on life.",
    "and who are truly fortunate": "Those who can achieve this noble character are described as having 'a great fortune' or 'immense good fortune.' This refers to their good character being a great blessing, and it also points to their reward in the Hereafter. In terms of worldly success, people with such character earn respect, love, and influence. In terms of the Hereafter, they earn Allah's pleasure and high ranks in Paradise."
  },
  36: {
    "And if you are tempted by Satan": "Even as you strive to maintain good character, Satan will try to provoke you. He whispers anger, resentment, and desire for revenge. He tries to make you abandon patience and respond to evil with evil. This satanic temptation (nazgh) is like a poke or jab meant to push you toward bad behavior.",
    "then seek refuge with Allah": "The remedy for satanic whispers is simple and powerful: turn to Allah for protection. Say 'A'udhu billahi min ash-shaytan ir-rajeem' (I seek refuge in Allah from the accursed Satan). This acknowledgment of your own weakness and reliance on Allah's strength defeats Satan's schemes. The Prophet (peace be upon him) taught this as the defense against anger and satanic provocation.",
    "Indeed, He ˹alone˺ is the All-Hearing, All-Knowing": "Allah hears your plea for help and knows the struggle you are facing. He is aware of every whisper Satan makes and every effort you make to resist. This should give comfort—you are not fighting alone. Allah responds to those who seek His refuge and provides them with the strength they need."
  },
  37: {
    "Among His signs are the day and the night, the sun and the moon": "Allah draws our attention to celestial phenomena that we witness daily. The alternation of day and night, the rising and setting of the sun, and the phases of the moon are all signs of Allah's power and wisdom. They operate with perfect precision, never failing, never colliding—demonstrating a Master Designer behind them. These are not random occurrences but deliberate signs for reflection.",
    "Do not prostrate to the sun or the moon": "Despite their grandeur and importance, the sun and moon are merely creations. Some ancient peoples worshipped them, mistaking the creation for the Creator. Allah explicitly forbids this. These celestial bodies have no power of their own; they follow the course set for them by Allah.",
    "but prostrate to Allah, Who created them ˹all˺": "Instead of worshipping these magnificent creations, direct your worship to their Creator. Prostration (sujood) is the ultimate act of submission and humility, and it belongs only to Allah. He is the One Who brought the sun, moon, day, and night into existence. He alone deserves this honor.",
    "if you ˹truly˺ worship Him ˹alone˺": "This conditional statement challenges the listener: if you claim to worship Allah, then prove it by directing all worship exclusively to Him. True worship of Allah means rejecting all false objects of worship, no matter how impressive they may seem."
  },
  38: {
    "But if the pagans are too proud": "If these polytheists and disbelievers are too arrogant to prostrate to Allah, thinking themselves above submission, then let them know they are not needed for Allah's glorification to continue.",
    "then ˹let them know that˺ those ˹angels˺ nearest to your Lord glorify Him day and night": "The noble angels who are closest to Allah—beings of immense honor and status—continuously glorify and praise Him without interruption. Day and night, they declare His perfection and worship Him with complete devotion.",
    "and never grow weary": "Unlike humans who tire, become bored, or need rest, these angels never grow weary of worshipping Allah. Their worship is constant, enthusiastic, and never diminishes. This shows that Allah does not need human worship—His glorification continues perpetually through countless angels. Human worship benefits the worshipper, not Allah."
  },
  39: {
    "And among His signs is that you see the earth devoid of life": "Another sign of Allah's power is the barren, dry earth that appears dead and lifeless. During drought, the ground is hard, cracked, and nothing seems to grow. It looks as though life has completely abandoned it.",
    "but as soon as We send down rain upon it, it begins to stir ˹to life˺ and swell": "The moment rain falls, the earth transforms dramatically. It becomes soft, swells with moisture, and vegetation begins to emerge. Seeds that lay dormant suddenly sprout. The earth 'stirs to life' as if waking from sleep. This miraculous transformation happens every year, yet we often take it for granted.",
    "Indeed, the One Who revives it can easily revive the dead": "This is the key lesson: if Allah can bring a dead, barren earth back to life, He can certainly resurrect dead human beings. The logic is undeniable—the same power that causes plants to emerge from dry soil can cause bodies to rise from their graves. Resurrection is not difficult for Allah.",
    "He is certainly Most Capable of everything": "Nothing is beyond Allah's ability. Creating, destroying, giving life, causing death, resurrection, judgment—all of it is within His power. This should inspire both hope (in His mercy) and fear (of His punishment)."
  },
  40: {
    "Indeed, those who abuse Our revelations are not hidden from Us": "Those who distort, misinterpret, mock, or reject Allah's verses are completely known to Him. They may think their mockery is private or their rejection goes unnoticed, but Allah sees and knows everything. 'Ilhaad' (abuse/deviation) includes twisting the meanings of verses, taking them out of context, ridiculing them, or denying them altogether. None of this escapes Allah's knowledge.",
    "Who is better: the one who will be cast into the Fire or the one who will be secure on Judgment Day?": "This rhetorical question presents a stark choice. Which outcome would you prefer: to be thrown into Hellfire or to arrive on Judgment Day in complete safety? The answer is obvious, yet people's actions suggest they prefer the Fire. Those who abuse Allah's revelations are heading toward the Fire, while those who believe and follow guidance will be secure.",
    "Do whatever you want": "This is not permission but a warning—a statement of giving them rope to hang themselves. It means: 'You have been warned; now the choice is yours. Do whatever you wish, but know there will be consequences.' This is similar to a parent telling a disobedient child, 'Fine, do what you want,' knowing the natural consequences will follow.",
    "He is certainly All-Seeing of what you do": "Every action, public or private, is fully observed by Allah. Nothing escapes His sight. This should inspire caution in every choice we make."
  },
  41: {
    "Indeed, those who deny the Reminder after it has come to them ˹are doomed˺": "The Reminder (Dhikr) is another name for the Quran, because it reminds people of their Lord, their purpose, and their final destination. Those who reject it after it has been clearly presented to them are in a state of doom. The sentence of their fate is implied—they are headed for destruction. Their rejection is not based on ignorance but on stubborn denial after knowledge.",
    "for it is truly a mighty Book": "The Quran is described as 'Aziz'—mighty, noble, precious, and invincible. It cannot be overcome, corrupted, or matched. Its honor is preserved by Allah Himself. This mighty Book that they reject will be a witness against them on Judgment Day."
  },
  42: {
    "It cannot be proven false from any angle": "Falsehood cannot approach the Quran from any direction—not from before it (in the sense of previous scriptures contradicting it) nor from behind it (in the sense of future discoveries disproving it). Every attempt to find contradictions, errors, or falsehoods in the Quran has failed. It has withstood 1400+ years of scrutiny and remains unchallenged.",
    "˹It is˺ a revelation from the ˹One Who is˺ All-Wise, Praiseworthy": "The Quran comes from Al-Hakeem (the All-Wise)—every word and law in it reflects perfect wisdom—and Al-Hameed (the Praiseworthy)—He is praised in His essence, attributes, and actions. A book from such a Source could only be perfect and protected from error."
  },
  43: {
    "˹O Prophet!˺ Nothing is said to you ˹by the deniers˺ except what was already said to the messengers before you": "This verse consoles the Prophet Muhammad (peace be upon him). The insults, mockery, and accusations he faces are nothing new. Every prophet before him heard similar things: accusations of being a madman, a magician, a liar, or being motivated by personal gain. This was the pattern with Noah, Abraham, Moses, Jesus, and all the prophets. The Prophet is not alone in his struggle; he walks a well-trodden path.",
    "Surely your Lord is ˹the Lord˺ of forgiveness and painful punishment": "Allah possesses both forgiveness and punishment. He forgives those who repent and turn to Him sincerely. But He also administers painful punishment to those who persist in denial and die in that state. Both attributes are true and operate according to His wisdom. This dual reminder serves as hope for believers and warning for deniers."
  },
  44: {
    "Had We revealed it as a non-Arabic Quran, they would have certainly argued, \"If only its verses were made clear ˹in our language˺.": "If Allah had revealed the Quran in a foreign language to the Arab audience, they would have complained that they couldn't understand it. They would have demanded: 'Why isn't this in our language? How can we follow something we cannot comprehend?' This shows that disbelievers will always find excuses—whatever form the message takes, they will find fault with it.",
    "What! A non-Arabic revelation for an Arab audience!\"": "They would have expressed disbelief at receiving a scripture in a foreign tongue. This would have been used as another excuse to reject the message. The point is that rejection is not about the language or format—it is about the unwillingness of the heart.",
    "Say, ˹O Prophet,˺ \"It is a guide and a healing to the believers.": "For those who believe, the Quran serves as guidance (showing the right path) and healing (curing spiritual diseases like doubt, anxiety, envy, and hardness of heart). The same Quran that disbelievers reject is a source of light and health for believers. The difference lies in the state of the heart, not in the Quran itself.",
    "As for those who disbelieve, there is deafness in their ears and blindness to it ˹in their hearts˺.": "The disbelievers' problem is internal, not external. Their ears are blocked from receiving the truth, and their hearts are blind to its light. This is a spiritual condition resulting from their rejection—the more they turn away, the more sealed their hearts become.",
    "It is as if they are being called from a faraway place.\"": "Because of their spiritual deafness, it is as though the message is being called to them from a great distance—they cannot hear it clearly or understand it. The message is near and clear, but their rejection makes it seem distant and incomprehensible. This is the tragic consequence of persistent denial."
  },
  45: {
    "Indeed, We had given Moses the Scripture, but differences arose regarding it": "Moses was given the Torah, a clear scripture from Allah. Yet even regarding such a clear revelation, people disagreed and disputed. Some accepted it, some rejected it, and others distorted its meanings. This is the recurring pattern with divine revelations—people create divisions around them.",
    "Had it not been for a prior decree from your Lord": "Allah had already decreed that judgment would not be rushed in this world but would be delayed until the Day of Judgment. This divine decision to give people time is a mercy, allowing opportunity for repentance and guidance.",
    "their differences would have been settled ˹at once˺": "Without this decree of delay, Allah would have immediately judged between the disputants, destroying the wrongdoers on the spot. But His wisdom includes patience and giving time.",
    "They are truly in alarming doubt about it": "Those who dispute about the scripture remain in deep, troubling doubt. Their doubt is not honest questioning but stubborn uncertainty that causes them anxiety yet does not lead them to sincerely seek truth. This doubt is spiritually dangerous—it prevents them from accepting guidance."
  },
  46: {
    "Whoever does good, it is to their own benefit": "Every good deed a person performs primarily benefits themselves. The rewards—both immediate (peace of heart, good reputation, baraka in life) and ultimate (Paradise)—return to the doer. Allah does not need our good deeds; we are the ones who benefit from them.",
    "And whoever does evil, it is to their own loss": "Similarly, every sin harms the sinner themselves. The consequences—spiritual darkness, loss of blessings, punishment—fall upon the evildoer. No one else bears the burden of another's sins. This establishes complete personal responsibility.",
    "Your Lord is never unjust to ˹His˺ creation": "Allah does not wrong anyone in the slightest. He does not punish someone for another's sin, nor does He withhold reward from one who deserves it. His judgment is perfectly fair. Any suffering in the Hereafter is a result of one's own choices, not divine injustice. This should eliminate any excuse for those who blame others for their fate."
  },
  47: {
    "With Him ˹alone˺ is the knowledge of the Hour": "The exact timing of the Day of Judgment is known only to Allah. No angel, no prophet, no human has access to this knowledge. This is one of the keys of the unseen that Allah has reserved for Himself. Anyone claiming to know when the Hour will come is lying.",
    "No fruit comes out of its husk": "Allah's knowledge extends to the smallest details of creation. He knows when every fruit emerges from its covering, when every bud opens into a flower. This level of detail demonstrates His comprehensive awareness.",
    "nor does a female conceive or deliver without His knowledge": "Every pregnancy, whether of humans or animals, occurs within Allah's knowledge. He knows the moment of conception, the development of the fetus, and the exact time of birth. Nothing happens without His awareness and permission. The Prophet (peace be upon him) informed us that an angel is assigned to every womb, recording the provision, lifespan, and destiny of the child.",
    "And ˹consider˺ the Day He will call to those ˹pagans˺, \"Where are My ˹so-called˺ associate-gods?\"": "On Judgment Day, Allah will question the polytheists about the partners they associated with Him. This is a humiliating question meant to expose the foolishness of their beliefs. Where are those idols now? Can they help? Can they intercede?",
    "They will cry, \"We declare before you that none of us testifies to that ˹any longer˺.\"": "The polytheists will completely disown their former claims. They will deny ever believing in partners with Allah, or they will abandon their false gods, realizing their powerlessness. The false gods themselves will also deny being worthy of worship. Everyone will try to distance themselves from shirk when its consequences become apparent."
  },
  48: {
    "Whatever ˹idols˺ they used to invoke besides Allah will fail them": "All the false deities they worshipped will disappear, abandon them, and prove utterly useless. The idols cannot help themselves, let alone their worshippers. Everything they relied upon besides Allah will vanish like a mirage.",
    "And they will realize that they will have no escape": "At that moment, the disbelievers will finally understand with certainty that there is no way out—no refuge, no rescue, no alternative. The realization will be crushing, but it will come too late. The time for escape was in the worldly life through repentance and faith. On Judgment Day, that door is closed."
  },
  49: {
    "One never tires of praying for good": "Human beings naturally keep asking Allah for good things—wealth, health, success, family, comfort. This desire for good never diminishes; people always want more blessings. This is not necessarily wrong, but it shows the nature of human ambition.",
    "And if touched with evil, they become desperate and hopeless": "When afflicted with hardship—illness, poverty, loss—many people fall into despair and lose hope in Allah's mercy. Instead of turning to Allah with patience and trust, they become pessimistic and assume the worst. This extreme swing from endless desire to utter hopelessness reveals a weakness in faith. The believer, in contrast, is patient in hardship and grateful in ease."
  },
  50: {
    "And if We let them taste a mercy from Us after being touched with adversity, they will certainly say, \"This is what I deserve.": "When Allah relieves their hardship and grants them blessings, instead of thanking Him, they attribute the blessing to themselves. They say, 'This is mine; I earned it through my own effort and merit.' This is the height of arrogance—taking credit for what Allah has given.",
    "I do not think the Hour will ˹ever˺ come": "They further deny the Day of Judgment. Their prosperity makes them complacent and deluded. They think worldly success proves they are on the right path and that there will be no accountability. This is a dangerous illusion.",
    "And if in fact I am returned to my Lord, the finest reward with Him will definitely be mine.\"": "Even if they momentarily consider the possibility of resurrection, they arrogantly assume they will receive the best reward from Allah. They think their worldly success indicates divine favor. This assumption has no basis—worldly wealth does not indicate spiritual status.",
    "But We will surely inform the disbelievers of what they used to do": "Allah will expose all their deeds on Judgment Day. Every act of ingratitude, every moment of arrogance, every sin will be laid bare before them.",
    "And We will certainly make them taste a harsh torment": "Their arrogance will be answered with severe punishment. The torment will be 'harsh' (ghaleedh)—intense, heavy, and unbearable. This is the consequence of attributing Allah's blessings to oneself and denying the Hereafter."
  },
  51: {
    "When We show favour to someone, they turn away, acting arrogantly": "When Allah blesses a person with health, wealth, or success, instead of drawing closer to Allah in gratitude, they turn away. They become arrogant, thinking they no longer need Allah or His guidance. They distance themselves from worship and religious obligations.",
    "And when touched with evil, they make endless prayers ˹for good˺": "But when hardship strikes—illness, financial loss, danger—suddenly they remember Allah. They pray constantly, making lengthy supplications, begging for relief. This inconsistency exposes a transactional attitude toward faith: they only turn to Allah when they need something, not out of genuine love and devotion. True faith means remaining connected to Allah in ease and difficulty alike."
  },
  52: {
    "Ask ˹them, O Prophet˺, \"Imagine if this ˹Quran˺ is ˹truly˺ from Allah and you deny it": "The Prophet is instructed to pose a thought-provoking question: Consider the possibility that this Quran actually is from Allah. What if you are wrong in rejecting it? What then would be your fate? This question forces reflection on the consequences of denial.",
    "who can be more astray than those who have gone too far in opposition ˹to the truth˺?\"": "If the Quran is indeed from Allah and you reject it, then you are in the deepest misguidance. You have opposed the ultimate truth and gone far astray. There is no one more lost than someone who rejects genuine divine guidance. This question should cause any sincere person to reconsider their position and investigate the Quran with an open heart."
  },
  53: {
    "We will show them Our signs in the universe": "Allah promises to reveal evidence of the truth through signs in the external world—the heavens, the earth, the stars, the oceans, the mountains, and all of creation. Scientific discoveries, natural phenomena, and the order of the cosmos all point to a Creator. As time passes, more and more signs become apparent, confirming what the Quran stated centuries ago.",
    "and within themselves": "Allah will also show signs within the human being—in their own bodies, psychology, and experiences. The complexity of the human body, the miracle of consciousness, the process of development from a single cell to a full human being—all of these are signs of Allah's creative power. Reflecting on oneself leads to recognizing the Creator.",
    "until it becomes clear to them that this ˹Quran˺ is the truth": "The purpose of showing these signs is to make the truth of the Quran undeniable. Over time, evidence accumulates until sincere seekers can no longer deny that this Book is from Allah. History has shown that many scientific facts mentioned in the Quran were only confirmed centuries later.",
    "Is it not enough that your Lord is a Witness over all things?": "Even beyond external signs, Allah Himself is a witness over everything. He sees all, knows all, and testifies to the truth. For the believer, this should be sufficient. The one who truly knows Allah does not need additional proof—Allah's testimony is the ultimate validation."
  },
  54: {
    "They are truly in doubt of the meeting with their Lord!": "The root of all their problems is doubt about the Day of Judgment and meeting Allah. If they truly believed they would stand before Allah and account for their deeds, they would behave very differently. Their denial of this meeting allows them to continue in sin without concern. This doubt is the source of their misguidance.",
    "˹But˺ He is indeed Fully Aware of everything": "The surah concludes with a powerful reminder: Allah's knowledge is comprehensive and all-encompassing. He surrounds everything with His knowledge. Nothing escapes Him—not a thought, not a deed, not a whisper. Whether they doubt or not, whether they believe or not, Allah knows everything about them and will hold them accountable. This final statement serves as both a warning to the disbelievers and a comfort to the believers: Allah is always watching, and ultimate justice will prevail."
  }
};