import sys
sys.path.append(".")
from scripts.intro_utils import insert_surah_intro

intros = {}

# -------------------------------------------------------------
# SURAH 6: AL-ANʿĀM
# -------------------------------------------------------------
intros[6] = """**The Manifesto of Pure Monotheism and Cosmic Sovereignty**

Al-Anʿām, "The Cattle," is the sixth chapter of the Qur'an, comprising 165 verses, and it represents the first major Makkan sūrah encountered in the codex arrangement. It takes its name from verses 136–144, which systematically dismantle the arbitrary pagan taboos and superstitions regarding livestock—superstitions by which the polytheists consecrated certain animals to their idols and forbade others to women. Classical exegetes, including Ibn ʿAbbās, recorded that Sūrah al-Anʿām was revealed all at once in Makkah during a single night, accompanied by an escort of seventy thousand angels glorifying Allah, so immense was its theological gravity. Where the preceding Medinan sūrahs (al-Baqarah through al-Mā'idah) elaborated communal legislation, civil statutes, and covenantal relations with the People of the Book, al-Anʿām returns with volcanic power to the bedrock of faith: the absolute unicity of God (*tawḥīd*), the reality of resurrection (*baʿth*), the repudiation of polytheism (*shirk*), and the defense of prophetic revelation against obstinate skepticism.

**The Crucible of Late Makkan Persecution**

Revealed in the late Makkan period, when the opposition of the Quraysh had hardened into entrenched hostility and economic and social boycott, al-Anʿām addresses an atmosphere of acute spiritual confrontation. The Quraysh were demanding physical miracles—that an angel descend visibly, or that a parchment inscribed by God fall from the sky into their hands (6:7–8). Al-Anʿām meets these demands not with concessions, but with a total philosophical reframing: physical signs do not produce faith in minds darkened by arrogance; if an angel were sent down, the decree of destruction would be executed without respite. Instead, the sūrah turns their gaze toward the living cosmos: the alternating rhythms of night and day, the splitting of the seed and the date-stone, the rotation of the celestial spheres, and the sovereign order that governs life and death. It presents the Prophet ﷺ as an unyielding herald of truth who seeks no earthly recompense, commands him to declare his distinct identity, and consoles him by demonstrating that messengers before him were mocked, denied, and persecuted, yet truth prevailed.

**The Shape of the Sūrah**

The movement of al-Anʿām unfolds as a relentless, rhythmic dialectic between cosmic evidence and divine interrogations. The opening movement (1–32) establishes God as the sole Creator of darkness and light, warns against taking divine signs lightly, exposes the psychology of denial, and depicts the sorrowful regret of the deniers when stood before the Fire. The second movement (33–73) consoles the Prophet, asserting that his opponents do not reject him personally but deny the signs of Allah, while presenting the cosmic panorama of divine omniscience: *“With Him are the keys of the unseen; none knows them except Him. And He knows what is on the land and in the sea; not a leaf falls but that He knows it”* (6:59). The third movement (74–90) introduces the intellectual and spiritual climax of the sūrah: the dramatic narrative of Abraham using celestial observation—the setting of the star, the moon, and the sun—to demonstrate the absurdity of worshipping ephemeral, declining phenomena, declaring: *“I have turned my face toward Him who created the heavens and the earth, truly devout, and I am not of the polytheists”* (6:79), followed by the grand roll-call of eighteen prophets united in a single line of guidance. The fourth movement (91–140) attacks the Quraysh's failure to estimate Allah with His true measure (*qadr*), refutes their concocted dietary taboos and infant sacrifice, and contrasts their fabricated customs against the true lawful provisions granted by the Creator. The fifth movement (141–153) provides the supreme moral charter of Islam: the Ten Universal Commandments of verses 151–153, which prohibit association of partners with God, mandate honor to parents, forbid infanticide and indecency, protect orphan wealth, and demand absolute justice in weighing and speech. The epilogue (154–165) contrasts the sectarian fractures of human religions against the pure, undivided faith of Abraham, culminating in the triumphant personal manifesto of verse 162: *“Say, 'Indeed, my prayer, my rites of sacrifice, my living and my dying are for Allah, Lord of the worlds.'”*

**The Philosophy of Cosmic Evidentialism**

What distinguishes al-Anʿām among all chapters of scripture is its relentless integration of theology and cosmology. It does not treat nature as an inert backdrop, but as a vast, continuous symphony of divine speech. Every sprouting grain, every gathering storm, every animal that walks the earth and bird that flies on two wings is identified as a distinct community (*umamun amthālukum*, 6:38) witnessing to the wisdom of the Fashioner. Polytheism is therefore indicted not merely as a moral crime, but as a colossal failure of cosmic observation. By demanding that the skeptic look up at the heavens and down into the soil, al-Anʿām shows that pure monotheism is the only posture compatible with the facts of existence."""

# -------------------------------------------------------------
# SURAH 8: AL-ANFĀL
# -------------------------------------------------------------
intros[8] = """**The Criterion of Badr and the Anatomy of Divine Victory**

Al-Anfāl, "The Spoils of War," is the eighth chapter of the Qur'an, comprising 75 verses of early Medinan revelation. It takes its name from the opening verse, which interrogates the distribution of the spoils (*al-anfāl*) captured after the Battle of Badr in the second year of the Hijrah (624 CE). Classical authorities, including Saʿīd ibn Jubayr, record that when he questioned Ibn ʿAbbās about Sūrah al-Anfāl, the Companion replied without hesitation: *“That is Sūrat Badr.”* Badr was not merely the first major military encounter between the fledgling Muslim commonwealth and the pagan aristocracy of Makkah; it was the historic crucible in which the survival of Islam was determined. The sūrah addresses this watershed moment not with jingoistic triumphalism, but with a profound spiritual audit. It strips away human pride, demonstrates that victory is not a product of numerical superiority or tactical brilliance, and redirects the community's attention toward moral discipline, psychological purification, and absolute reliance upon the unseen intervention of God.

**The Crisis of the Caravans and the Plains of Badr**

The historical canvas of al-Anfāl is the barren valley of Badr, roughly eighty miles southwest of Madinah, in Ramaḍān of 2 AH. A Muslim force of approximately 313 lightly armed men, riding fewer than seventy camels and possessing only two horses, had marched out originally to intercept a rich Qurayshi merchant caravan led by Abū Sufyān, seeking compensation for the wealth confiscated in Makkah. However, the caravan escaped via the coastal route, and the Qurayshi nobility—led by the arrogant Abū Jahl—marched north with a heavily armored army of nearly one thousand seasoned warriors, determined to annihilate the Muslims once and for all. Caught between an unexpected total war and the temptation to retreat, the believers experienced severe internal trepidation. The Prophet ﷺ spent the night before battle in tearful, agonizing supplication under a makeshift canopy, praying: *“O Allah, if this small band of believers is destroyed today, You will not be worshipped on this earth.”* The ensuing clash resulted in a stunning rout of the pagan aristocracy: seventy of their chief leaders were slain (including Abū Jahl) and seventy captured, while only fourteen Muslims fell as martyrs. When disputes arose among the victors concerning the distribution of the abandoned armor and weapons, Sūrah al-Anfāl descended to settle the dispute by declaring that all spoils belong primarily to Allah and His Messenger.

**The Structure and Thematic Arc**

The architecture of al-Anfāl moves from internal moral reform to battlefield phenomenology, and from military jurisprudence to communal solidarity. The opening movement (1–4) swiftly subordinates material gain to spiritual virtue, declaring that true believers are those whose hearts tremble with awe when Allah is remembered and whose faith increases when His signs are recited. The second movement (5–19) recounts the psychological and physical realities of Badr: the believers' initial reluctance, the descent of one thousand reinforcing angels (*murdifīn*), the refreshing rain that cleansed their bodies and consolidated the sand beneath their feet, and the terror cast into the hearts of the enemy. It delivers the stunning theological verdict on human agency: *“You did not kill them, but Allah killed them. And you threw not, ˹O Prophet˺, when you threw, but Allah threw”* (8:17). The third movement (20–40) warns against the disease of disobedience, demanding that the believers never turn their backs in battle or emulate those who say *“we hear”* while hearing nothing, while warning of trials (*fitnah*) that afflict both the oppressor and the bystander. The fourth movement (41–54) codifies the legal distribution of war booty—allocating one-fifth (*al-khumus*) to Allah, the Messenger, near relatives, orphans, the needy, and the wayfarer—and contrasts the humility of the believers with the boastful ostentation of the Quraysh, deserted on the field by Satan himself. The fifth movement (55–71) addresses international relations: the treatment of persistent treaty-breakers, the duty to prepare deterrent defense capability to intimidate aggressors, the command to incline toward peace if the enemy inclines toward it, and the moral treatment of captives of war. The closing movement (72–75) defines the constitutional solidarity of the community, forging a sacred fraternity between the Emigrants (*Muhājirūn*) and Helpers (*Anṣār*) who supported them, establishing mutual guardianship based on active faith and shared struggle.

**The Theology of Invisible Reinforcement**

The primary thesis of Sūrah al-Anfāl is that worldly triumph is an illusion when divorced from spiritual submission. Material preparations are mandatory (*“prepare against them whatever you are able of power,”* 8:60), but physical weapons do not deliver victory; victory descends exclusively from the Sovereign Lord (*“and there is no victory except from Allah,”* 8:10). By rebuking greed, sanctifying treaties, mandating peace at the earliest opportunity, and exalting the bond of faith above tribal bloodlines, al-Anfāl established the ethical framework of warfare in Islam: not an instrument of territorial conquest or plundering, but a defensive shield to uphold justice and secure the freedom of worship."""

# -------------------------------------------------------------
# SURAH 9: AL-TAWBAH
# -------------------------------------------------------------
intros[9] = """**The Severing of Alliances and the Ultimatum of Sincerity**

Al-Tawbah, "The Repentance"—also widely designated in classical exegesis as *Barā'ah* (The Immunity or Repudiation)—is the ninth chapter of the Qur'an, comprising 129 verses. It is universally distinguished by a striking, unique feature: it is the only sūrah in the entire Qur'anic corpus that does not open with the *Basmalah* (*“In the Name of Allah, the Most Compassionate, Most Merciful”*). When the caliph ʿUthmān ibn ʿAffān was questioned regarding this omission, he noted that al-Tawbah was revealed near the very end of the prophetic era, that its themes were intimately intertwined with Sūrah al-Anfāl, and that the Prophet ﷺ passed away without explicitly indicating whether it constituted an independent chapter or a continuation. The Companion ʿAlī ibn Abī Ṭālib provided the classical spiritual rationale: *“The Basmalah is a guarantee of security and mercy, whereas Barā'ah was revealed with the sword, stripping away security from treaty-breaking polytheists.”* It is also named *al-Fāḍiḥah* (The Exposer) by ʿAbdullāh ibn ʿAbbās, because it mercilessly exposed the clandestine plots, psychological cowardice, and treacherous cynicism of the hypocrites, leaving no facade intact.

**The Aftermath of Makkah's Conquest and the Expedition to Tabūk**

Chronologically situated in the ninth year of the Hijrah (9 AH), al-Tawbah reflects the final political realignment of the Arabian peninsula. The conquest of Makkah in 8 AH had definitively shattered pagan power, but treacherous tribal elements continued to violate their pacts whenever opportunity arose, and pagan pilgrims still performed indecent, idolatrous rites around the Kaʿbah. In response, verses 1–28 were promulgated as a sovereign ultimatum during the Pilgrimage of 9 AH, led by Abū Bakr, with ʿAlī dispatching the proclamation across the plains of Minā: a four-month grace period was granted, after which all mutual pacts with chronic treaty-violators were dissolved, and polytheists were permanently barred from the Sacred Mosque. The second vast theater of the sūrah (verses 38–129) concerns the grueling Campaign of Tabūk in late 9 AH—a grueling march through scorching desert heat to confront a rumored Byzantine imperial invasion on the northern frontier. Known as the *Ghazwat al-ʿUsrah* (The Expedition of Hardship), it served as an unsparing furnace that separated authentic, self-sacrificing faith from hollow hypocrisy. While sincere believers donated their last possessions, the hypocrites fabricated excuses, stayed behind, and mocked those who marched forth.

**The Structure and Thematic Movements**

The architecture of al-Tawbah unfolds in two colossal, sweeping movements. The first movement (1–37) announces the definitive termination of idolatrous treaties (*Barā'ah*), delineates the treatment of honorable versus treacherous tribes, commands the defense of monotheistic sanctuaries, and articulates the principles governing warfare with hostile polytheists and scriptural factions who refused peaceful submission. It contains the celebrated decree of safe passage (*istijārah*, 9:6), mandating that any polytheist seeking asylum must be protected, allowed to hear the Word of God, and escorted to his place of safety. The second and larger movement (38–129) conducts an exhaustive psychological autopsy of the Tabūk mobilization. It rebukes the spiritual paralysis that struck some believers when commanded to march (*“What is the matter with you that when you are told to go forth, you cling heavily to the earth?”*, 9:38), immortalizes the divine rescue of the Prophet ﷺ and Abū Bakr in the cave during the migration (*“Do not grieve; indeed Allah is with us,”* 9:40), and dissects the rationalizations of the hypocrites who built the subversive “Mosque of Harm” (*Masjid al-Ḍirār*) to fracture the community. It codifies the eight definitive categories of Zakat beneficiaries (9:60), contrasts the mutual loyalty of true believing men and women against the mutual cynicism of hypocrites, and narrates the poignant story of the three sincere believers who stayed behind from Tabūk without excuse—whose social ostracization ended in triumphant divine forgiveness when *“the earth, despite its vastness, seemed to close in on them”* (9:118). The sūrah concludes (128–129) with a luminous tribute to the character of the Messenger ﷺ: *“There has certainly come to you a Messenger from among yourselves; grievous to him is what you suffer; [he is] concerned over you and to the believers is kind and merciful.”*

**The Radiography of the Heart**

The ultimate argument of Sūrah al-Tawbah is that religion cannot survive on ambiguity. When the existential survival of truth is at stake, neutrality is an impossibility; every soul must choose where its true allegiances lie. By tearing away the disguises of tribal sentimentality, financial greed, and fear of sacrifice, al-Tawbah demonstrates that divine acceptance (*tawbah*) is not an empty verbal formula, but a total realignment of the will. It remains the great purgative text of the Qur'anic canon: burning away the dross of compromise so that the sanctuary of faith may stand immaculate and resolute."""

# -------------------------------------------------------------
# SURAH 10: YŪNUS
# -------------------------------------------------------------
intros[10] = """**The Book of Wisdom and the Providence of Repentance**

Yūnus (Jonah) is the tenth chapter of the Qur'an, comprising 109 verses of late Makkan revelation. It is the first of a magnificent contiguous sequence of six chapters (Sūrahs 10 through 15) that open with the mystical disconnected letters *Alif-Lām-Rā*, and it takes its name from verse 98, which commemorates the unique historical deliverance of the people of Jonah. Alone among all the ancient communities cited across prophetic history, the community of Jonah repented sincerely upon the very threshold of catastrophic divine punishment, whereupon the torment was averted from them and they were granted worldly reprieve. Classical authorities, including Ibn ʿAbbās and al-Zuhrī, count Yūnus among the mature Makkan sūrahs revealed immediately following Sūrah al-Isrāʾ (Chapter 17) and shortly before the Hijrah. Positioned directly after the intense, martial Medinan realities of al-Anfāl and al-Tawbah, Yūnus reorients the reader's contemplation back to foundational cosmic theology: the miraculous nature of revelation, the signs of God in cosmic order, the certainty of eschatological reckoning, and the psychological mechanisms that blind humans to their own mortality.

**The Late Makkan Wilderness and the Taunt of Signs**

Revealed during the intensely bitter years following the deaths of the Prophet's beloved wife Khadījah and his protective uncle Abū Ṭālib—a period marked by the abortive mission to al-Ṭā'if and unrelenting Qurayshi harassment—Yūnus reflects a context of ideological stagnation. The Makkan idolaters were trapped in a paradox: they marveled that a mortal human from among their own streets had been chosen to receive celestial revelation (*“Is it a wonder to the people that We revealed to a man from among them?”*, 10:2), yet they demanded that the promised divine chastisement be brought upon them instantly if his warnings were genuine. Sūrah Yūnus confronts this obstinacy with majestic philosophical calm. It demonstrates that the Prophet ﷺ has no power to alter the scripture on his own initiative (*“It is not for me to change it of my own accord; I only follow what is revealed to me,”* 10:15) and that the delaying of judgment is not divine impotence, but divine mercy granting humanity time to reflect.

**The Shape and Narrative Arc**

The architecture of Yūnus unfolds in three grand movements. The opening movement (1–30) establishes the divine authority of the *Kitāb al-Ḥakīm* (the Book Rich in Wisdom), drawing evidence from the natural theater: the sun as a radiant lamp (*ḍiyāʾ*), the moon as a measured light (*nūr*), the alternating cycle of day and night, and the provision poured from heaven. It introduces the striking parable of worldly life (verse 24): a lush garden watered by rain that flourishes until its owners imagine they possess absolute mastery over it, whereupon divine command strikes it by night or day, leaving it desolate as though it had never bloomed yesterday. The second movement (31–70) engages in a relentless cross-examination of polytheist psychology. It challenges them to identify who sustains them from sky and earth, who created their hearing and sight, and who brings the living from the dead; when they concede that it is Allah, it asks: *“Then how are you turned away?”* It issues the standing literary challenge to produce a single sūrah like it (10:38), exposes their reliance on pure conjecture (*ẓann*), and offers the soothing reassurance that God is a witness over every movement, conversation, and deed. The third movement (71–109) marshals the evidence of sacred history: the defiance of Noah against his mocking elders, the long liberation struggle of Moses and Aaron against Pharaoh and his sorcerers, and the dramatic drowning of Pharaoh in the Red Sea—whereupon Pharaoh attempts a deathbed conversion, but is told that repentance is invalid when mortality is breached, and his corpse is preserved as a physical sign for future generations (10:90–92). The climax highlights the people of Jonah (10:98), before concluding with the sovereign rule of belief: *“If your Lord had willed, all those on earth would have believed together. Will you then compel the people until they become believers?”* (10:99).

**The Sovereignty of Divine Grace and the Limits of Compulsion**

The core message of Sūrah Yūnus is that faith cannot be coerced by human tyranny, nor can it be demanded through sensational miracles; it is a spiritual realization born of moral reflection. By juxtaposing the drowning Pharaoh—who repented only when the waves engulfed his throat, too late to avail him—with the people of Jonah, who humbled themselves before the storm struck and were saved, Yūnus defines the true nature of repentance (*tawbah*). It teaches that time is a sacred canopy of mercy, and that the greatest tragedy of human existence is to mistake God's patience for His absence."""

for ch in [6, 8, 9, 10]:
    insert_surah_intro(ch, intros[ch])
print("Batch 1 (Part B: 6, 8, 9, 10) inserted successfully.")
