import sys
sys.path.append(".")
from scripts.intro_utils import insert_surah_intro

intros = {}

# -------------------------------------------------------------
# SURAH 11: HŪD
# -------------------------------------------------------------
intros[11] = """**The Sūrah of Prophetic Burden and Moral Uprightness**

Hūd is the eleventh chapter of the Qur'an, comprising 123 verses of late Makkan revelation. It takes its name from the Arabian prophet Hūd, sent to the towering, arrogant civilization of ʿĀd, whose dramatic confrontation occupies verses 50–60. In prophetic tradition, Sūrah Hūd carries an extraordinary emotional and spiritual gravity: when Abū Bakr remarked on the premature whitening of the Prophet's hair, the Messenger of Allah ﷺ replied: *“Sūrah Hūd and its sisters have aged me”* (Jāmiʿ al-Tirmidhī 3297). Exegetes note that this holy trembling was specifically induced by verse 112: *“So stand firm as you have been commanded, along with those who have turned to Allah with you, and do not transgress.”* This command demanded unswerving, lifelong uprightness (*istiqāmah*) without bending toward compromise, tyranny, or fatigue. Preceded by Yūnus and succeeded by Yūsuf, Hūd stands as a terrifyingly vivid courtroom of prophetic sacred history, where the covenantal relationship between prophets and their recalcitrant communities is laid bare with uncompromising moral clarity.

**The Year of Sorrow and the Stiffening of Deniers**

Revealed in the agonizing interval of the late Makkan mission following the lifting of the three-year clan boycott and the deaths of Khadījah and Abū Ṭālib (the Year of Sorrow, *ʿĀm al-Ḥuzn*), Hūd addressed a Prophet whose physical sanctuary had dissolved. The Quraysh were actively plotting either his assassination, imprisonment, or exile, while scoffing at the promise of divine resurrection and retribution. Sūrah Hūd speaks directly to this isolation: it consoles the Messenger ﷺ, warning him not to let his breast be constricted when the deniers mock that no physical treasure was dropped on him or no angel arrived in his company (11:12). Instead of offering comforting illusions, the sūrah presents an unblinking historical record: no prophet before him was received with rose petals; every herald of monotheism was branded an imposter, a madman, or a destabilizer by the entrenched economic and political elites of their day.

**The Architecture and Movement of the Discourse**

The structure of Sūrah Hūd is built around a majestic doctrinal frame enclosing six epic narrative suites. The prologue (1–24) opens with the *Alif-Lām-Rā* of the Decisive Book, presenting the universal call to monotheism, exposing the absurdity of those who wrap their chests to hide from God, celebrating the divine guarantee of sustenance for every crawling creature on earth (11:6), and challenging the skeptics to produce ten fabricated sūrahs like it (11:13). The second movement (25–49) presents the longest and most emotionally devastating account of Noah in the Qur'an: the building of the Ark under the mockery of his chieftains, the bursting forth of the subterranean ovens and torrential skies, and the heartbreaking dialogue between Noah and his disbelieving son, who seeks refuge on a mountain only to be swept away by the surging wave, prompting the divine rebuke that an unrighteous offspring is no true part of a prophet's spiritual household. The third movement (50–95) rolls out the successive destructions of ancient civilizations: Hūd and the catastrophic wind that shattered the giants of ʿĀd; Ṣāliḥ and the sacred she-camel hamstrung by the insolent elders of Thamūd; Abraham receiving the angelic messengers bound for Sodom; the terrifying twilight confrontation of Lot with the depraved mob surrounding his guests; Shuʿayb warning the merchants of Midian against fraud and economic injustice; and Moses confronting Pharaoh's tyranny. The fourth movement (96–123) extracts the universal moral laws of history: that God never destroys a town unjustly while its people are actively reforming (*muṣliḥūn*, 11:117), culminating in the thunderous injunction to stand firm (*fa-staqim*, 11:112), to establish the prayer at both ends of the day and in the watches of the night to erase evil deeds (11:114), and sealing the chapter with the serene assurance: *“And to Allah belongs the unseen of the heavens and the earth, and to Him the whole matter will be returned; so worship Him and rely upon Him.”*

**The Philosophy of Unbending Istiqāmah**

The central spiritual argument of Sūrah Hūd is that truth is not evaluated by consensus, nor is prophetic duty conditioned on immediate worldly success. Noah preached for nine and a half centuries and was mocked by his own family; Hūd, Ṣāliḥ, Lot, and Shuʿayb were rejected by the vast majority of their contemporaries. Yet the sūrah declares that they were the true victors, while their persecutors became dry stubble and cursed memories. The believer is commanded not to incline toward the oppressors (*“and do not incline toward those who do wrong, lest the Fire touch you,”* 11:113), but to maintain absolute moral integrity (*istiqāmah*) regardless of the prevailing political or cultural weather."""

# -------------------------------------------------------------
# SURAH 12: YŪSUF
# -------------------------------------------------------------
intros[12] = """**The Masterpiece of Sacred Narrative and the Triumph of Patience**

Yūsuf (Joseph) is the twelfth chapter of the Qur'an, comprising 111 verses of late Makkan revelation. It occupies a unique, peerless station within the Qur'anic canon: while sacred history is elsewhere presented in episodic fragments and thematic suites across multiple chapters, Sūrah Yūsuf dedicates its entire narrative breadth to a single, continuous, chronologically unfolding biography. In verse 3, divine speech designates this account as *Aḥsan al-Qaṣaṣ* (The Most Beautiful of Stories)—a title vindicated by its sublime psychological depth, its dramatic narrative tension, its intricate plot symmetries, and its profound theological orchestration. In classical tradition, exegetes like Ibn ʿAṭā'illāh noted that whenever a sorrowful or distressed person reads Sūrah Yūsuf, peace and consolation descend upon their heart, because it demonstrates with unmatched poetic beauty how divine benevolence (*luṭf*) works through betrayal, enslavement, slander, imprisonment, and famine to fulfill the divine decree.

**The Year of Sorrow and the Jewish Challenge**

Revealed during the darkest days of the Prophet's Makkan mission—shortly after the catastrophic loss of Khadījah and Abū Ṭālib and the physical brutalization suffered at al-Ṭā'if—Yūsuf descended as a celestial balm upon a grieving Messenger. Historical reports transmitted by al-Baghawī and al-Qurṭubī indicate that the Jewish scholars of Yathrib (Madinah) prompted the Quraysh to test Muḥammad's prophetic credentials by asking him: *“Why did the family of Jacob migrate from Canaan to the land of Egypt?”* It was an obscure, detailed historical question inaccessible to an unlettered merchant in the pagan desert. Sūrah Yūsuf descended in response, not merely answering the historical inquiry with breathtaking historical precision, but providing an intentional spiritual mirror for the Prophet ﷺ himself: just as Joseph was envied by his brothers, cast into a pit, exiled, and falsely accused, only to eventually forgive them from a throne of supreme power, so too would Muḥammad ﷺ be driven from his home by his Qurayshi brethren, only to grant them sweeping, gracious pardon on the day Makkah was conquered.

**The Shape and Narrative Symmetry**

The architecture of Sūrah Yūsuf is crafted with astonishing dramatic and literary symmetry. The prologue (1–6) opens with Joseph as a young boy recounting to his loving father, Jacob (Yaʿqūb), his luminous dream of eleven stars, the sun, and the moon prostrating before him—a vision Jacob warns him to keep secret from his brothers. The first act (7–20) depicts the toxic jealousy of the brothers, their conspiracy to murder him, his casting into the subterranean well, the false blood stained upon his tunic, and Jacob's immortal response: *“So patience is most fitting (*fa-ṣabrun jamīl*), and Allah is the one sought for help”* (12:18), followed by Joseph's sale into Egyptian bondage for a paltry sum. The second act (21–35) stages the moral furnace of youth: Joseph adopted into the palace of the *ʿAzīz* (the Egyptian minister), his ripening into radiant beauty, the attempted seduction by the minister's wife (Zulaykhā), his desperate flight to the door where his shirt is torn from behind, the testimony of the infant witness, and his heroic choice of incarceration over moral corruption: *“My Lord, prison is more dear to me than that to which they invite me”* (12:33). The third act (36–57) details his prison life: his interpretation of the dreams of the baker and the cupbearer, his unyielding call to monotheism in the dungeon, the forgotten plea, the king's baffling dream of seven fat cows eaten by seven lean ones, Joseph's providential economic planning, his vindication and clearing of all charges, and his elevation to supreme economic treasurer of Egypt. The fourth act (58–93) dramatizes the return of the starving brothers: their failure to recognize Joseph, the testing through Benjamin, the planting of the royal drinking cup, the profound grief of Jacob who weeps until his eyes turn white from sorrow yet never despairs of God's spirit (*rawḥ Allāh*), and the electrifying moment of self-revelation: *“I am Joseph, and this is my brother!”* (12:90). The fifth act (94–101) brings the grand reconciliation: the fragrant shirt cast over Jacob's eyes restoring his sight, the arrival of the parents in Egypt, the raising of the parents onto the throne, and the prostration of the entire family, fulfilling the childhood dream. Joseph's closing prayer (12:101) is one of the most serene supplications in scripture: renouncing worldly majesty to pray: *“Cause me to die a Muslim and join me with the righteous.”* The epilogue (102–111) reflects on the reality of revelation, confirming that prophetic history is not fabricated myth, but an instructional lesson for minds endowed with deep insight.

**The Invisible Weaver: Al-Laṭīf**

The theological heart of Sūrah Yūsuf is the declaration made by Joseph at the climax of his life: *“Indeed, my Lord is subtle (*Laṭīf*) in what He wills”* (12:100). *Al-Laṭīf* is the Divine Name that describes God's subtle, invisible orchestration of affairs—achieving magnificent decrees through causes so delicate, imperceptible, or seemingly contrary that human intellect cannot trace the thread until the tapestry is complete. Had the brothers not envied Joseph, he would not have been thrown into the well; had he not been cast into the well, the caravan would not have found him; had he not been sold in Egypt, he would not have entered the minister's palace; had he not been slandered, he would not have entered the prison; had he not entered the prison, he would not have interpreted the dreams that saved the civilization of Egypt from starvation. Sūrah Yūsuf teaches that human betrayal and suffering are never outside the sovereign, benevolent providence of God, and that *Ṣabr Jamīl* (beautiful patience without bitterness) is always rewarded with honor, vindication, and divine grace."""

# -------------------------------------------------------------
# SURAH 13: AL-RAʿD
# -------------------------------------------------------------
intros[13] = """**The Thunder of Truth and the Architecture of Divine Signs**

Al-Raʿd, "The Thunder," is the thirteenth chapter of the Qur'an, comprising 43 verses. It is uniquely categorized in classical exegesis: while many early authorities (including Mujāhid and Qatādah) consider it an early Medinan composition due to its profound civil and theological formulations, other eminent scholars (including Ibn ʿAbbās in certain transmissions) view it as a late Makkan revelation transitioning into the Medinan era. It takes its name from verse 13, which delivers the astonishing cosmic image of the thunderbolt glorifying Allah with praise, accompanied by the trembling awe of the angels (*“And the thunder exalts [Allah] with praise of Him, and the angels [as well] from fear of Him”*). Blending the majesty of the cosmos with the psychological landscape of human doubt, Sūrah al-Raʿd is a masterpiece of dialectical theology, demonstrating that just as the invisible laws of nature govern rain, lightning, vegetation, and gravity, so too do immutable moral and spiritual laws govern the rise and fall of human societies.

**The Skeptic's Demand for Spectacle**

The historical climate of al-Raʿd is marked by the persistent, obstinate cynicism of those who demanded sensational, coercive signs: *“Why has not a sign been sent down to him from his Lord?”* (13:7, 27). The opponents mocked the reality of bodily resurrection (*“When we are dust, will we indeed be in a new creation?”*, 13:5) and challenged the Prophet to hasten the divine punishment upon them rather than warning them of it. Sūrah al-Raʿd meets this intellectual cynicism with an overwhelming display of cosmic evidence. It tells the deniers that the universe itself is an unbroken tapestry of signs for those who reflect: the invisible pillars that suspend the celestial bodies, the sun and moon running their appointed courses, the earth spread out with firm mountains and rivers, and diverse fruit trees growing side by side, watered by the same rain yet differing in taste. A society that cannot perceive God in the daily rising of the sun or the sprouting of a date-palm will never believe even if an angel were to speak to them or the mountains were moved from their places.

**The Shape and Rhythmic Cadence**

The architecture of Sūrah al-Raʿd moves between cosmic contemplation, psychological radiography, and eschatological certainty. The opening movement (1–4) declares the Book to be the undeniable Truth (*al-ḥaqq*), anchoring revelation in the observable architecture of nature. The second movement (5–16) exposes the absurdity of idolatry: how can men worship partners who have no power to benefit or harm even themselves? It introduces the stunning question of spiritual perception: *“Are the blind and the seeing equal, or are darkness and light equal?”* (13:16). The third movement (17) presents one of the most celebrated parables in the Qur'an: rain falling into valley beds according to their measure, bearing on its surface a swelling foam, contrasted with the dross that rises when metals are smelted for jewelry or tools—the foam and dross vanish as useless scum, while what benefits humanity endures upon the earth. The fourth movement (18–29) contrasts the spiritual mindset of the mindful (*ulū al-albāb*)—who fulfill the covenant of God, join what Allah has commanded to be joined, endure patiently, and repel evil with good—against the covenant-breakers who spread corruption. It is here that the immortal verse 28 appears: *“Those who believe and whose hearts find rest in the remembrance of Allah. Unquestionably, by the remembrance of Allah hearts are assured.”* The fifth movement (30–43) delivers the famous socio-historical law of verse 11: *“Indeed, Allah will not change the condition of a people until they change what is in themselves,”* and closes with the sovereign testimony of verse 43: when the disbelievers say *“You are not a messenger,”* the Prophet is instructed to reply: *“Sufficient is Allah as witness between me and you, and whoever has knowledge of the Book.”*

**The Weight of Truth and the Fleeting Scum of Falsehood**

The central thesis of Sūrah al-Raʿd is the ontological reality of *Al-Ḥaqq* (The Truth) versus the ephemeral vanity of *Al-Bāṭil* (Falsehood). Like the torrential foam that covers the river after a downpour, falsehood may appear vast, loud, and dominant upon the surface of culture, but it lacks substance and is destined to evaporate into nothingness. Truth, like the clear water beneath the foam or the pure gold beneath the slag, remains to nourish and enrich human existence. By anchoring societal transformation not in political machinations but in the inner moral state of human consciousness (13:11), Sūrah al-Raʿd establishes that genuine peace and victory are found only when the heart aligns itself with the remembrance of its Creator."""

# -------------------------------------------------------------
# SURAH 14: IBRĀHĪM
# -------------------------------------------------------------
intros[14] = """**The Paradigm of the Patriarch and the Architecture of Gratitude**

Ibrāhīm (Abraham) is the fourteenth chapter of the Qur'an, comprising 52 verses of mature Makkan revelation. It belongs to the sequence of *Alif-Lām-Rā* chapters and takes its title from verses 35–41, which immortalize the profound personal supplication of Abraham upon settling his infant son Ishmael and wife Hagar in the barren, uncultivated valley of Makkah beside the Sacred House. In the broader Qur'anic discourse, Abraham is the supreme archetype of the *Ḥanīf*—the primordial, uncompromising monotheist who surrendered his entire intellect, lineage, and emotional attachment to the sovereign Lord. Revealed in the late Makkan period when the believers were enduring social siege and physical threats of expulsion, Sūrah Ibrāhīm establishes a profound theological contrast between the fragile, bankrupt foundations of tyranny and the unshakeable, eternal stability of faith, grounded in the cosmic reality of gratitude (*shukr*).

**The Threat of Banishment and the Prophetic Horizon**

The immediate historical setting of Sūrah Ibrāhīm is reflected in verse 13, where the arrogant oligarchies of the past declare to their messengers: *“We will surely drive you out of our land, or you must return to our religion!”* This was the exact ultimatum being formulated by the Quraysh against Muḥammad ﷺ and his companions in Makkah. The sūrah addresses this acute geopolitical anxiety by showing that the threat of exile is the ancient reflex of tyranny throughout sacred history: every prophet was threatened with banishment, yet in every era, divine revelation answered: *“We will surely destroy the wrongdoers, and We will surely settle you in the land after them”* (14:13–14). The sūrah thus provided an indispensable spiritual compass: teaching the beleaguered believers that true power does not reside in ancestral real estate or tribal hegemony, but in the divine decree that upholds the righteous.

**The Structural Development and Parables**

The movement of Sūrah Ibrāhīm unfolds from the foundational purpose of scripture to the eschatological confrontation of Satan, and from cosmic parables to Abraham's historic prayer. The opening movement (1–8) defines the mission of the Qur'an: a Book revealed to bring humanity out of darkness into the light by the leave of their Lord, recalling Moses reminding his people of the *Days of Allah* (*Ayyām Allāh*), and proclaiming the immutable spiritual law of verse 7: *“If you are grateful, I will surely increase you [in favor]; but if you are ungrateful, indeed, My punishment is severe.”* The second movement (9–23) narrates the universal confrontation between the ancient nations (Noah, ʿĀd, Thamūd) and their messengers, depicting the horrifying reality of the arrogant tyrants in Hell, forced to drink festering water (*mā'in ṣadīd*) that they swallow with difficulty while death approaches them from every side yet they cannot die (14:16–17). It culminates in the astonishing eschatological sermon of Satan on the Day of Judgment (14:22): when reckoning is complete, Satan disavows his followers, declaring: *“Indeed, Allah promised you the promise of truth, and I promised you, but I betrayed you. I had no authority over you except that I invited you, and you responded to me. So do not blame me; blame yourselves!”* The third movement (24–27) delivers the celebrated parable of the Two Trees: the Good Word (*Kalimah Ṭayyibah*—the declaration of faith) compared to a noble tree whose root is firmly fixed deep in the earth and whose branches reach high into the heavens, yielding its fruit in every season; contrasted against the Evil Word (*Kalimah Khabīthah*—idolatry and falsehood) compared to a rotten tree uprooted from the surface of the earth, possessing no stability. The fourth movement (28–41) examines the tragedy of those who exchange God's favor for ingratitude and lead their people into ruin, leading directly into Abraham's sublime prayer: begging God to make Makkah a sanctuary of peace, to preserve his descendants from idol-worship, to incline human hearts with love toward them, to provide them with fruits so that they may be grateful, and supplicating for forgiveness for himself, his parents, and all believers on the Day of Reckoning. The epilogue (42–52) issues a terrifying warning against assuming that God is heedless of injustice (*“Do not think that Allah is unaware of what the wrongdoers do; He only delays them for a Day when eyes will stare in horror,”* 14:42), concluding with the earth being replaced by another earth, and humanity standing exposed before the One, the Irresistible.

**The Fruit of the Firmly Rooted Word**

The overarching thesis of Sūrah Ibrāhīm is the radical ontological difference between that which is rooted in truth and that which is built upon falsehood. Tyranny, oppression, and polytheism resemble the uprooted tree: they may seem towering and menacing today, but they have no subterranean roots in reality, and a single gust of divine judgment will topple them into oblivion. In contrast, the life founded on *Tawḥīd* and gratitude resembles the Abrahamic tree: immovably rooted in the bedrock of truth, ascending toward the divine heavens, and perpetually bearing fruit across all generations."""

# -------------------------------------------------------------
# SURAH 15: AL-ḤIJR
# -------------------------------------------------------------
intros[15] = """**The Protected Reminder and the Valley of the Stonemasons**

Al-Ḥijr is the fifteenth chapter of the Qur'an, comprising 99 verses of late Makkan revelation. It is the final sūrah in the six-chapter sequence opening with the mystical letters *Alif-Lām-Rā*, and it takes its name from verse 80, which mentions *Aṣḥāb al-Ḥijr* (the Companions of the Rocky Tract)—the ancient people of Thamūd who hewed out palatial dwellings directly from the sandstone cliffs of northwestern Arabia, imagining their stone-carved architecture could shield them from the judgment of God. Sūrah al-Ḥijr is universally celebrated for verse 9, which constitutes the definitive, immortal divine guarantee of the text's textual preservation: *“Indeed, it is We who sent down the Qur'an and indeed, We will be its guardian (*wa-innā lahū la-ḥāfiẓūn*).”* Emerging from the crucible of late Makkan derision, the sūrah serves as a divine fortress: exposing the vanity of human arrogance, charting the cosmic roots of human disobedience in the envy of Iblīs, and providing intimate spiritual solace to the Messenger ﷺ against the mocking tongues of his contemporaries.

**The Taunts of Madness and the Consolation of the Prophet**

The historical context of al-Ḥijr reflects the brazen insolence of the Qurayshi aristocracy, who dismissed the Prophet's warnings as hallucinations and ridiculed his prophetic office, crying: *“O you upon whom the message has been sent down, indeed you are mad! Why do you not bring us the angels if you are of the truthful?”* (15:6–7). The sūrah addresses this hostility with majestic reassurance. It reminds the Prophet ﷺ that no messenger ever walked the earth without being subjected to mockery (*“There never came to them a messenger except that they used to mock him,”* 15:11), and that the day will inevitably arrive when those who denied will desperately wish they had surrendered to Islam (15:2). The delay in divine intervention is not impotence, but the unfolding of a pre-measured decree; every community has a known, determined term (*kitābum maʿlūm*) which can neither be anticipated nor delayed.

**The Structural Unfolding of the Chapter**

The movement of Sūrah al-Ḥijr proceeds from cosmic defense to primordial drama, and from historical ruins to devotional serenity. The opening movement (1–25) establishes the incorruptibility of revelation, shows the heavens adorned with constellations (*burūj*) and protected by shooting stars from eavesdropping devils, and displays the earth balanced with towering mountains and life-giving winds that fertilize the clouds. The second movement (26–48) stages the primeval creation of humanity: God fashioning Adam from sounding clay altered from black mud (*ṣalṣāl min ḥama'in masnūn*), breathing into him of His Spirit, and commanding the angels to prostrate. It dramatizes the haughty rebellion of Iblīs, who claims superiority based on fire, his expulsion from the divine presence, and his sworn oath to adorn vanity on earth and mislead humanity—except the sincere, purified servants (*ʿibādukumu al-mukhlaṣīn*), over whom he possesses no authority. The third movement (49–84) transitions into historical validation: Abraham receiving the angels who bring news of a righteous son and announce the imminent annihilation of the people of Sodom; the catastrophic morning blast and raining stones that buried the towns of Lot; the destruction of the forest dwellers (*Aṣḥāb al-Aykah*); and the tragic fate of the stonemasons of al-Ḥijr (Thamūd), whose engineered mountain fortresses could not avail them when the screaming blast (*al-ṣayḥah*) seized them at sunrise. The closing movement (85–99) returns to the Prophet's heart with exquisite tenderness: reminding him of the cosmic purpose of creation, bestowing upon him the *Seven Oft-Repeated Verses* and the Great Qur'an (15:87), commanding him to proclaim truth openly without fear (*fa-ṣdaʿ bi-mā tu'mar*, 15:94), comforting him for the constriction he feels in his breast from their insults (15:97), and providing the immortal divine prescription: *“So exalt [Allah] with praise of your Lord and be of those who prostrate, and worship your Lord until there comes to you the certainty [of death]”* (15:98–99).

**The Incorruptible Fortress and the True Sanctuary**

The profound message of Sūrah al-Ḥijr is the futility of seeking security in physical engineering or earthly fortification. The stonemasons of Thamūd carved their homes into the living bedrock, confident that stone would outlast mortality, yet a single sonic vibration shattered their lungs in the night. The only true fortress in the universe is the sanctuary built upon prostration (*sujūd*), divine praise, and fidelity to the Protected Book (*al-Dhikr*). By grounding the Prophet's resilience not in worldly defenses but in continuous liturgical worship, al-Ḥijr teaches that the servant of God is invincible so long as his heart remains anchored at the threshold of prayer."""

for ch in [11, 12, 13, 14, 15]:
    insert_surah_intro(ch, intros[ch])
print("Batch 2 (Part A: 11-15) inserted successfully.")
