import sys
sys.path.append(".")
from scripts.intro_utils import insert_surah_intro

intros = {}

# -------------------------------------------------------------
# SURAH 51: ADH-DHĀRIYĀT
# -------------------------------------------------------------
intros[51] = """**The Winnowing Winds and the Purpose of Creation**

Adh-Dhāriyāt, "The Winnowing Winds," is the fifty-first chapter of the Qur'an, comprising 60 verses of early-to-mid Makkan revelation. It takes its name from its opening meteorological oath: *“By the [winds] scattering dust dispersingly (*wa-l-dhāriyāti dharwā*), and those carrying loads [of clouds], and those sailing with ease, and those distributing [divine] command—indeed, what you are promised is true!”* (51:1–5). Sūrah adh-Dhāriyāt is universally celebrated in Islamic theology for containing the ultimate, foundational charter of human and jinn existence in verse 56: *“And I did not create the jinn and mankind except to worship Me (*illā li-yaʿbudūn*).”* Emerging from the intense poetic and spiritual furnace of early Makkah, the sūrah sweeps across the cosmic phenomena of atmosphere, cloud dynamics, and celestial orbits, demonstrating that just as the winds disperse pollen and drive rain across the globe under sovereign mathematical command, so too is human life directed toward a certain, unavoidable moral reckoning.

**The Cynical Questioning and the Signs in the Self**

The historical context of adh-Dhāriyāt reflects the mocking skepticism of the Qurayshi polytheists regarding the reality of the Final Judgment. They asked with derisive irony: *“When is the Day of Recompense?”* (51:12), treating the concept of divine accounting as an intellectual fable. Sūrah adh-Dhāriyāt responds not with defensive apologetics, but by redirecting their attention to the profound architecture of reality. It points to the earth filled with signs for those endowed with certainty (*fī al-arḍi āyātun li-l-mūqinīn*), and delivers the penetrating spiritual challenge of verse 21: *“And in your own selves! Then will you not see?”* It establishes that the provision (*rizq*) of every human being is not an accident of earthly commerce, but a cosmic decree anchored in the heavens: *“And in the heaven is your provision and whatever you are promised. Then by the Lord of the heaven and earth, indeed, it is truth—just as [it is truth] that you speak!”* (51:22–23).

**The Structural Modulation and the Midnight Ascetics**

The architecture of Sūrah adh-Dhāriyāt unfolds across three distinct thematic movements. The opening movement (1–23) swears by the dynamic atmospheric forces of wind, cloud, sea, and angels that the promised Resurrection is absolute truth, indicts those who drown in conjecture and falsehood, and contrasts their doom against the luminous reward of the righteous in Paradise. It provides an exquisite portrait of their earthly spiritual lifestyle: *“They used to sleep but little of the night, and in the hours before dawn they would seek forgiveness, and in their wealth there was a known right for the beggar and the deprived”* (51:17–19). The second movement (24–46) reviews the sacred history of divine visitation: the honored guests of Abraham—the angels who arrived bringing news of a knowledgeable son to his astonished, elderly wife who cried: *“A barren old woman!”* (51:29), and announced their mission to rain stones of baked clay upon the criminals of Sodom; the confrontation of Moses with Pharaoh who turned away in his arrogance, claiming Moses was a magician or madman, drowned in the sea; the screaming wind that left the giants of ʿĀd like decaying bones; the thunderbolt that seized Thamūd while they looked on; and the people of Noah destroyed before them as an iniquitous folk. The closing movement (47–60) returns to the cosmic canvas with breathtaking power: *“And the heaven We constructed with strength, and indeed, We are [its] expanders (*wa-innā la-mūsiʿūn*)”* (51:47)—a verse celebrating the expanding cosmos centuries before modern astrophysics—and earth spread out as a magnificent cradle. It issues the urgent divine imperative: *“So flee to Allah! Indeed, I am to you from Him a clear warner”* (51:50), affirms that God demands no provision or sustenance from humanity (*“Indeed, Allah is the Provider, the Possessor of strength, the Firm,”* 51:58), and warns the oppressors that their portion of punishment will inevitably match the portion of their ancient predecessors.

**The Flight to the Divine: Fa-firrū ilā Allāh**

The supreme spiritual thesis of Sūrah adh-Dhāriyāt is the immortal command of verse 50: *Fa-firrū ilā Allāh* ("So flee to Allah!"). When a human being is terrified by earthly dangers, he flees *away* from the threat to find refuge; but when the soul awakens to the terror of its own mortality, sin, and spiritual bankruptcy, it can find refuge only by fleeing *to* the Very One whose majesty it fears. By revealing that the singular purpose of human existence is *ʿIbādah* (the knowing, loving, and humble worship of God), Sūrah adh-Dhāriyāt liberates humanity from the anxiety of material sustenance, reminding every heart that its provision is guaranteed by the Almighty, while its only true task is to surrender to the Lord of the worlds."""

# -------------------------------------------------------------
# SURAH 52: AṬ-ṬŪR
# -------------------------------------------------------------
intros[52] = """**The Sacred Mountain and the Inevitable Judgment**

Aṭ-Ṭūr, "The Mount," is the fifty-second chapter of the Qur'an, comprising 49 verses of early Makkan revelation. It opens with five solemn cosmic and historical oaths: *“By the Mount [Sinai], and by a Book inscribed, in a parchment unrolled, and by the Frequented House [in the heavens], and by the canopy raised [the sky], and by the sea set on fire—indeed, the punishment of your Lord will occur; of it there is no preventer!”* (52:1–8). In prophetic tradition, Sūrah aṭ-Ṭūr holds a legendary place as the catalyst that shattered the skeptical resistance of Jubayr ibn Muṭʿim before his conversion to Islam: Jubayr reported in Ṣaḥīḥ al-Bukhārī (4854) that he arrived in Madinah as an envoy of the pagan Quraysh while the Prophet ﷺ was leading the sunset prayer (*Maghrib*), reciting Sūrah aṭ-Ṭūr: *“When I heard him recite: 'Were they created by nothing, or were they themselves the creators? Or did they create the heavens and the earth? Nay, they have no certainty!' (52:35–36), my heart almost flew from my chest, and that was the first time faith settled in my heart.”* With rhythmic, chiseled verses that resound like thunder, Sūrah aṭ-Ṭūr is an uncompromising intellectual and spiritual trial of human skepticism.

**The Assembly of the Sacred Landmarks**

The historical context of aṭ-Ṭūr is the fierce, defensive cynicism of the Makkan aristocracy, who accused the Prophet ﷺ of being a soothsayer (*kāhin*), an insane poet (*shāʿir majnūn*), or an imposter forging speech for political ambition. Sūrah aṭ-Ṭūr grounds its discourse in five sacred landmarks that link terrestrial history with cosmic realities: Mount Sinai (*aṭ-Ṭūr*), where Moses received the Torah; the inscribed celestial parchment; the *Bayt al-Maʿmūr* (the Frequented House in the celestial heavens directly above the Kaʿbah, circumambulated perpetually by seventy thousand angels who never return); the celestial sky; and the ocean set ablaze (*al-baḥr al-masjūr*). It confronts the Makkans with the absolute irreversibility of the coming Judgment: when the sky rolls with terrifying convulsion and the mountains move like drifting clouds, no worldly defense, wealth, or tribal alliance can avert the decree.

**The Structural Movement and the Litany of Interrogations**

The architecture of Sūrah aṭ-Ṭūr moves across three distinct, powerful movements. The opening movement (1–28) announces the certainty of retribution, describes the deniers pushed forcefully into the Fire which they had branded an illusion, and contrasts their agony against the serene bliss of the righteous in the Gardens of Delight: reclining on couches lined in ranks, wed to companions of pure beauty, their righteous offspring joined with them in Paradise without their deeds being diminished in the least (52:21). It records their touching conversation in Paradise, reflecting on their earthly lives: *“Indeed, we were previously, among our families, fearful [of God's displeasure]. But Allah conferred favor upon us and protected us from the punishment of the Scorching Fire. Indeed, we used to call upon Him; indeed, He is the Beneficent, the Merciful”* (52:26–28). The second movement (29–47) forms the intellectual climax of the sūrah—a relentless barrage of fifteen rhetorical questions that leave the skeptic intellectually stripped:
- Reminding the Prophet that he is, by the favor of his Lord, neither a soothsayer nor a madman.
- Answering their wish that he die of misfortune: *“Say, 'Wait, for indeed I am with you among those who wait'”* (52:31).
- Challenging them: *“Or do their minds command them to this, or are they a transgressing people? Or do they say, 'He has made it up'? Nay, they do not believe! Then let them produce a statement like it, if they should be truthful!”* (52:32–34).
- Delivering the four devastating existential dilemmas of verses 35–37: Were they created from nothing? Are they themselves the creators? Did they create the heavens and the earth? Do they possess the treasuries of your Lord, or are they the controllers?
- Asking if they have a stairway into heaven to eavesdrop on divine secrets, or if God has daughters while they have sons, or if the Prophet asks them for a fee that weighs them down with debt.
The closing movement (48–49) turns to the Prophet with sublime, intimate tenderness: *“So be patient for the decision of your Lord, for indeed, you are in Our eyes (*fa-innaka bi-aʿyuninā*). And exalt with praise of your Lord when you arise, and of the night exalt Him, and at the setting of the stars.”*

**In the Eyes of God: Bi-Aʿyuninā**

The foundational spiritual consolation of Sūrah aṭ-Ṭūr is contained in the tender divine assurance of verse 48: *Fa-innaka bi-aʿyuninā* ("For indeed, you are in Our eyes / under Our watchful, loving gaze"). The Prophet ﷺ was mocked, slandered, and surrounded by hostile conspiracies, yet he was told that he was dwelling permanently within the protective gaze of the Almighty. Sūrah aṭ-Ṭūr teaches that no matter how loud the mockery of skepticism becomes, the soul that anchors itself in the midnight remembrance of God and the dawn setting of the stars is sheltered in the fortress of divine love."""

# -------------------------------------------------------------
# SURAH 53: AN-NAJM
# -------------------------------------------------------------
intros[53] = """**The Descent of the Star and the Vision at the Lote Tree**

An-Najm, "The Star," is the fifty-third chapter of the Qur'an, comprising 62 verses of early Makkan revelation. It takes its name from its breathtaking opening oath: *“By the star when it descends! Your companion [Muḥammad] has not strayed, nor has he erred, nor does he speak from [his own] desire; it is not but a revelation revealed!”* (53:1–4). In the history of the prophetic mission, Sūrah an-Najm marks an extraordinary, legendary watershed: it was the very first chapter of the Qur'an that the Messenger of Allah ﷺ recited publicly, aloud, in the courtyard of the Kaʿbah before the gathered assembly of the Quraysh. Recorded by ʿAbdullāh ibn Masʿūd in Ṣaḥīḥ al-Bukhārī (1067), when the Prophet concluded the recitation with the thunderous final command of verse 62: *“So fall in prostration to Allah and worship Him!”*—the entire assembly, including the most hardened pagan chieftains (such as ʿUtbah, Shaybah, and Umayyah ibn Khalaf), was so completely overwhelmed by the volcanic linguistic majesty and spiritual power of the verses that they all spontaneously fell prostrate to the earth alongside the Muslims. Sūrah an-Najm is celebrated for containing the supreme scriptural eyewitness account of the *Miʿrāj*—the Prophet's celestial ascension and his unmediated vision of the Angel Gabriel at the *Sidrat al-Muntahā* (The Lote Tree of the Utmost Boundary).

**The Eye That Never Wavered**

The historical climate of an-Najm was the Qurayshi attempt to dismiss prophetic revelation as hallucination, poetry, or demonic whisperings. Sūrah an-Najm deconstructs this skepticism by presenting the sensory and metaphysical reality of the prophetic encounter. Gabriel was not an imaginary phantom; the Prophet saw him in his true celestial form endowed with six hundred wings: first on the clear horizon, drawing near until he was at a distance of two bow-lengths or nearer (*qāba qawsayni aw adnā*, 53:9), and a second time beside the *Sidrat al-Muntahā*, near the Garden of Abode (*Jannat al-Ma'wā*), when the tree was enveloped in unearthly divine light: *“The sight [of the Prophet] did not swerve, nor did it transgress [its limit]! He certainly saw of the greatest signs of his Lord”* (53:17–18).

**The Structural Symphony and the Classical Pagan Idols**

The architecture of Sūrah an-Najm moves across three distinct, powerful movements. The opening movement (1–18) establishes the absolute purity of prophetic speech, free from personal ego or psychological distortion, detailing the two historic celestial visions of Gabriel during the *Miʿrāj*. The second movement (19–32) directly attacks the central trinity of the pagan Arabian pantheon: *al-Lāt* (the idol of al-Ṭā'if), *al-ʿUzzā* (the idol of Nakhlah), and *Manāt* (the idol of Qudayd). It exposes them as empty, manufactured names invented by ancestral custom without divine authority: *“They are not but [mere] names you have named, you and your forefathers, for which Allah has sent down no authority; they follow not except assumption and what [their] souls desire”* (53:23). It exposes the absurdity of their claim that angels are female daughters of God, and defines the true nature of divine justice: that God rewards those who avoid major sins and immoralities, even if they commit minor lapses (*al-lamam*), for *“indeed, your Lord is vast in forgiveness”* (53:32). The third movement (33–62) reviews the ancient theological scrolls of Abraham and Moses (*Ṣuḥuf Mūsā wa-Ibrāhīm*), setting forth the universal moral principles of sacred history:
- That no bearer of burdens shall bear the burden of another (*lā taziru wāziratun wizra ukhrā*).
- That humanity will have nothing except that for which it has actively striven (*wa-an laysa li-l-insāni illā mā saʿā*).
- That his effort will soon be seen and fully recompensed.
- That to your Lord is the final destination (*wa-anna ilā Rabbika al-muntahā*).
- That it is He who causes laughter and weeping, causes death and life, created the pairs of male and female from a drop of sperm, and that He is the Lord of the dog-star Sirius (*Rabb al-Shiʿrā*).
The sūrah concludes with the destruction of ʿĀd, Thamūd, the people of Noah, and the overturned cities of Sodom, ending with the apocalyptic warning: *“The Approaching Day has approached! Of it, [none] besides Allah can dispel it. Do you then marvel at this statement, and you laugh and do not weep, while you amuse yourselves? So fall in prostration to Allah and worship Him!”* (53:57–62).

**The Ultimate Horizon: Ilā Rabbika al-Muntahā**

The supreme philosophical core of Sūrah an-Najm is summarized in verse 42: *Wa-anna ilā Rabbika al-muntahā* ("And that to your Lord is the ultimate destination"). Everything in the cosmos—every galaxy, every human striving, every sorrow, every joy, and every historical epoch—runs inexorably toward the Divine Court. Human beings spend lifetimes pursuing empty names (*asmā'an sammaytumūhā*)—wealth, prestige, and false idols—only to discover that they are pursuing illusions. By concluding with universal prostration, Sūrah an-Najm demands that the human soul bow its head before the Sovereign Lord who guides the stars and resurrects the dead."""

# -------------------------------------------------------------
# SURAH 54: AL-QAMAR
# -------------------------------------------------------------
intros[54] = """**The Splitting of the Moon and the Accessible Reminder**

Al-Qamar, "The Moon," is the fifty-fourth chapter of the Qur'an, comprising 55 verses of early Makkan revelation. It opens with an electrifying historical and eschatological spectacle: *“The Hour has drawn near, and the moon has split (*iqtarabati al-sāʿatu wan-shaqqa al-qamar*)! And if they see a sign, they turn away and say: 'Passing magic!'”* (54:1–2). In authentic prophetic tradition documented in Ṣaḥīḥ al-Bukhārī (3636) and Ṣaḥīḥ Muslim (2800) by multiple Companions—including ʿAbdullāh ibn Masʿūd, Anas ibn Mālik, and Ibn ʿAbbās—the Quraysh demanded that the Prophet Muḥammad ﷺ demonstrate a visible cosmic miracle. The Prophet pointed toward the night sky, and by divine command, the full moon cleaved into two distinct halves: one half standing directly over Mount Abū Qubays and the other behind it, visible across the Arabian desert. Rather than submitting to the sign, the pagan aristocracy scoffed: *“Muḥammad has cast sorcery over our eyes!”* Characterized by rapid, dramatic staccato verses ending in the resonant rhyme *-ur*, Sūrah al-Qamar is celebrated for its unforgettable, fourfold refrain in verses 17, 22, 32, and 40: *“And We have certainly made the Qur'an easy to remember / easy for reminder, so is there any who will remember? (*Fa-hal min muddakir*)”*.

**The Rejection of the Cleaved Moon**

The historical atmosphere of al-Qamar is defined by the absolute obstinacy of the human ego when confronted with undeniable truth. The splitting of the moon was not a subjective internal vision; it was a physical, cosmic event witnessed by travelers outside Makkah who confirmed seeing the identical phenomenon. Sūrah al-Qamar exposes the psychological root of denial: when the heart is enslaved to pride and desire (*wa-ttabaʿū ahwā'ahum*, 54:3), no miracle in heaven or earth can compel belief. If the skies open and the moon splits in two, the skeptic merely mutters: *“Continuous sorcery!”* Sūrah al-Qamar therefore shifts its focus from physical spectacle to historical demonstration: warning the Quraysh that the true, terrifying consequence of denial is not a future abstraction, but an established historical pattern.

**The Fourfold Warning and the Ease of Scripture**

The architecture of Sūrah al-Qamar is built around a symmetrical sequence of historical catastrophism:
1. The Prologue and the Day of Emerging (1–8): The moon split, the warning ignored, and the sudden arrival of the Day when the Caller will summon humanity to a terrible event, emerging from the graves with downcast eyes like scattered locusts (*ka-annahum jarādun muntashir*), racing toward the Caller, while the deniers cry: *“This is a difficult day!”*
2. Noah and the Deluge (9–17): Branded mad and threatened with expulsion, Noah prayed: *“Indeed, I am overcome, so help [me]!”* God opened the gates of heaven with torrential rain and caused the earth to burst forth with springs, meeting at a pre-decreed measure, carrying Noah upon an ark of planks and nails (*dhāti alwāḥin wa-dusur*), sailing under divine eyes, sealed with the refrain: *“And We have certainly made the Qur'an easy for reminder, so is there any who will remember?”*
3. ʿĀd and the Screaming Gale (18–22): Denying their warner, struck by a furious, roaring wind on an unceasing day of disaster, plucking people up as though they were uprooted trunks of date palms.
4. Thamūd and the She-Camel (23–32): Objecting that Ṣāliḥ was merely a mortal human from among them, hamstrung the camel, whereupon a single blast (*ṣayḥatan wāḥidah*) reduced them to the dry, trampled twigs of a sheepfold builder (*ka-hashīmi al-muḥtaẓir*).
5. The People of Lot (33–40): Demanding the assault of his angelic guests, their eyes blinded, and struck in the morning by an abiding punishment of raining stones.
6. Pharaoh and his Dynasty (41–42): Seized with the grasp of the Exalted in Might, the Omnipotent.
The climactic movement (43–55) turns directly upon the Quraysh: *“Are your disbelievers better than those, or have you an immunity in the scriptures?”* It delivers the stunning military prophecy of verse 45—which ʿUmar ibn al-Khaṭṭāb recalled reciting at the Battle of Badr when the Qurayshi army was routed: *“Their assembly will soon be defeated, and they will turn their backs [in flight]!”* It declares that all things have been created with pre-measured decree (*qadar*, 54:49), and concludes with the sublime eternal reward of the pious: *“Indeed, the righteous will be among gardens and rivers, in a seat of truth (*fī maqʿadi ṣidq*) near an All-Powerful Sovereign (*ʿinda Malīkin Muqtadir*)”* (54:54–55).

**The Accessibility of Divine Remembrance: Al-Muddakir**

The foundational pedagogical message of Sūrah al-Qamar is contained in its celebrated fourfold refrain: *Wa-laqad yassarnā al-Qur'āna li-l-dhikri fa-hal min muddakir* ("And We have certainly made the Qur'an easy for reminder; then is there any who will remember?"). The Qur'an is not an esoteric, impenetrable puzzle reserved for an elite priesthood; its language is clear, its rhythms are accessible, its warnings are vivid, and its guidance is open to every human heart that seeks truth. Sūrah al-Qamar asks with urgent love: if God has split the moon, made the scripture easy, and preserved the historical warnings of the past, what excuse remains for the human soul to remain asleep?"""

# -------------------------------------------------------------
# SURAH 55: AR-RAḤMĀN
# -------------------------------------------------------------
intros[55] = """**The Bride of the Qur'an and the Cosmic Symphony of Grace**

Ar-Raḥmān, "The Most Compassionate," is the fifty-fifth chapter of the Qur'an, comprising 78 verses. Classical authorities debate its chronological categorization: while many early scholars (including Ibn Masʿūd and al-Ḥasan) hold it to be an early Makkan revelation, others (including Ibn ʿAbbās in certain transmissions) consider it an early Medinan composition. It is the only chapter in the entire sacred canon that opens with a Divine Name standing alone as an independent, single-word verse: *“Al-Raḥmān”* (55:1). In prophetic tradition, Sūrah ar-Raḥmān is celebrated across the Islamic world as *ʿArūs al-Qur'ān* (The Bride of the Qur'an), a title transmitted by al-Bayhaqī from ʿAlī ibn Abī Ṭālib, celebrating its sublime aesthetic beauty, its jewel-like linguistic ornamentation, and its breathtaking symphonic symmetry. Sūrah ar-Raḥmān is uniquely addressed to a dual audience: speaking simultaneously to the twin rational species of creation—humanity (*al-ins*) and the unseen spirits (*al-jinn*)—punctuating its discourse with an astonishing, thirty-one-fold liturgical refrain: *“So which of the favors of your Lord will you twain [jinn and men] deny? (*Fa-bi-ayyi ālā'i Rabbikumā tukadhdhibān*)”*.

**The Recitation to the Jinn and the Reproach of Humanity**

The historical and devotional atmosphere of Sūrah ar-Raḥmān is illuminated by an authentic report in Jāmiʿ al-Tirmidhī (3291), where Jābir reported that the Prophet ﷺ recited Sūrah ar-Raḥmān to his human Companions, and they listened in quiet, reverent silence. When he concluded, the Messenger of Allah looked at them and said: *“I recited this chapter to the Jinn on the Night of the Jinn, and their response was better than yours! Whenever I came to the verse: 'So which of the favors of your Lord will you twain deny?', they replied without hesitation: 'There is not one of Your favors, O our Lord, that we deny, and to You belongs all praise!'”* The sūrah confronts both species with the staggering generosity of the Creator: demonstrating that existence itself, revelation, speech, cosmic order, agricultural bounty, oceanic commerce, and eternal salvation are all unearned gifts flowing from the boundless fountain of Divine Mercy (*al-Raḥmān*).

**The Architectural Symmetries of the Symphony**

The architecture of Sūrah ar-Raḥmān is an astonishing masterwork of literary and theological engineering, divided into four grand, balanced movements:
1. Terrestrial and Cosmic Order (1–30): God taught the Qur'an, created man, taught him articulate speech (*al-bayān*), aligned the sun and moon in precise mathematical calculation, caused the stars and trees to prostrate, raised the heaven and established the Balance (*al-mīzān*) so that humans do not transgress in justice. It describes the earth laid out with fruit, date-palms with sheaths, grain with husk, and fragrant plants. It contrasts human origin from sounding clay like pottery (*ṣalṣāl ka-l-fakhkhār*) against jinn origin from a smokeless flame of fire (*mārij min nār*), and presents the two seas meeting side by side, separated by an unbreachable barrier, yielding pearls and coral, and the majestic ships gliding like mountains across the sea.
2. The Extinction of All Beings (26–36): Delivering the immortal metaphysical reality of mortality in verses 26–27: *“Everyone upon [the earth] will perish, and there will remain the Face of your Lord, Owner of Majesty and Honor (*wa-yabqā wajhu Rabbika Dhū al-Jalāli wa-l-Ikrām*).”* All in heaven and earth ask of Him, and every day He is bringing about a matter. It challenges jinn and men to breach the zones of the heavens and earth if they can—they cannot breach them except with divine authority.
3. The Cataclysm of the Sky and the Judgment (37–45): Describing the sky splitting open and turning crimson like charred leather or molten red oil, the criminals recognized by their marks and seized by their forelocks and feet, cast into Hell, cycling between scalding fire and boiling water.
4. The Four Gardens of Paradise (46–78): For the one who feared the standing before his Lord are two sublime Gardens (46–61): having spreading branches, two running springs, pairs of every fruit, reclining upon couches lined with rich brocade, with fruit hanging within arm's reach, accompanied by pure companions who look upon none but their spouses, like rubies and coral. It delivers the supreme axiom: *“Is the reward for excellence anything other than excellence? (*Hal jazā'u al-iḥsāni illā al-iḥsān*, 55:60).”* Beneath these two Gardens are *two other Gardens* (62–78): dark green in lushness, with two gushing springs, dates, pomegranates, and companions sheltered in pavilions, concluding with the glorious seal of verse 78: *“Blessed is the name of your Lord, Owner of Majesty and Honor!”*

**The Omnipresence of Grace and the Measure of the Balance**

The central philosophical thesis of Sūrah ar-Raḥmān is that the entire universe is held together by two divine principles: *Al-Raḥmah* (Mercy) and *Al-Mīzān* (The Balance). Mercy is the origin of existence; the Balance is the moral and physical harmony that sustains it. When human beings act with injustice, cheat in measurements, or deny God, they violate the cosmic harmony that the stars and trees maintain through prostration. By repeating the refrain thirty-one times—challenging both humans and jinn to name a single element of reality that is not a gift of grace—Sūrah ar-Raḥmān cures the soul of ingratitude, inviting the creation to lose itself in wonder, praise, and adoration before the Owner of Majesty and Honor."""

for ch in [51, 52, 53, 54, 55]:
    insert_surah_intro(ch, intros[ch])
print("Batch 6 (Part A: 51-55) inserted successfully.")
