import sys
sys.path.append(".")
from scripts.intro_utils import insert_surah_intro

intros = {}

# -------------------------------------------------------------
# SURAH 26: ASH-SHUʿARĀʾ
# -------------------------------------------------------------
intros[26] = """**The Rhythms of Prophetic Witness and the Deconstruction of Poetry**

Ash-Shuʿarāʾ, "The Poets," is the twenty-sixth chapter of the Qur'an, comprising 227 verses of mid-to-late Makkan revelation. It is the second longest chapter in the sacred canon by verse count (surpassed only by al-Baqarah), though its verses are characterized by concise, rapid, rhyming musicality. It takes its name from verses 224–227, which deliver a devastating critique of pagan Arabian poets—celebrated culture-heroes who wandered aimlessly through every valley of rhetoric, praised vanity, incited tribal bloodshed, and said that which they did not practice—contrasting them sharply against believers who remember God and seek justice. Positioned as the first of three contiguous sūrahs (26, 27, and 28) opening with the letters *Ṭā-Sīn-Mīm*, Sūrah ash-Shuʿarāʾ is an epic dramatic oratorio: repeating seven successive historical narratives of prophets confronting tyrannical oligarchies, each closed with the haunting, identical liturgical refrain: *“Indeed, in that is a sign, but most of them were not to be believers. And indeed, your Lord—He is the Exalted in Might, the Merciful.”*

**The Prophet's Anguish and the Challenge of Rhetoric**

The historical climate of ash-Shuʿarāʾ reflects the profound psychological grief of the Prophet ﷺ over the persistent stubbornness of his people. Verse 3 opens with touching intimacy: *“Perhaps, [O Muḥammad], you would kill yourself with grief that they will not be believers.”* The Quraysh were dismissing his divine message as mere *shiʿr* (poetry) or the inspired ravings of a possessed bard (*kāhin*). In pre-Islamic Arabia, poetry was the ultimate weapon of psychological warfare, political propaganda, and tribal self-aggrandizement. By naming the sūrah after the poets, the Qur'an confronts this cultural idolatry head-on: demonstrating that while the poet is driven by fickle emotion, vanity, and verbal deception, the Prophet speaks eternal, unchanging truth anchored in moral reality and divine revelation brought down by the *Trustworthy Spirit* (*al-Rūḥ al-Amīn*, 26:193).

**The Sevenfold Prophetic Drama**

The architecture of ash-Shuʿarāʾ is structured with extraordinary literary symmetry. The prologue (1–9) consoles the Prophet's compassionate heart, declares that God could easily send down a sign from heaven that would force their necks to bow in humiliation, but divine pedagogical wisdom requires voluntary moral choice. The central body (10–191) unfolds seven successive historical dramas:
1. Moses and Aaron (10–68): Confronting Pharaoh's court, Pharaoh reminding Moses of his childhood upbringing in the palace, the staff turning into a serpent, the white hand, the contest with the sorcerers who instantly fall prostrate in faith upon seeing the staff swallow their illusions, the parting of the sea into towering walls of water, the rescue of the Israelites, and the drowning of the Egyptian hosts.
2. Abraham (69–104): Debating his father and people regarding the futility of idols that cannot hear or benefit, uttering the glorious confession: *“The Lord of the worlds, who created me, and He guides me. And it is He who feeds me and gives me drink. And when I am ill, it is He who cures me...”* (26:78–80), and praying for a *tongue of truth* among later generations and an untarnished heart on the Day of Judgment.
3. Noah (105–122): Enduring the contempt of the aristocratic elders who mock his impoverished followers, steadfastly proclaiming: *“I am to you a trustworthy messenger... My reward is only from the Lord of the worlds.”*
4. Hūd (123–140): Confronting the giants of ʿĀd, who built lofty monuments on every high place for sport and seized people with unrestrained cruelty.
5. Ṣāliḥ (141–159): Warning the skilled stonemasons of Thamūd who carved secure palaces into cliffs, presenting the she-camel as a public test of water rights, and their catastrophic doom after hamstrung rebellion.
6. Lot (160–175): Confronting the public sexual transgression and assault of his townsmen, saved with his family except his complicit wife.
7. Shuʿayb (176–190): Rebuking the commercial corruption, fraudulent scales, and highway robbery of the forest-dwellers (*Aṣḥāb al-Aykah*), who were crushed by the shadow of the canopy cloud (*Yawm al-Ẓullah*).
The epilogue (192–227) brings the sūrah to an electrifying climax: affirming that the Qur'an was brought down by the *Trustworthy Spirit* upon the Prophet's heart in clear Arabic tongue, foretold in the scriptures of the ancients, and contrasting this divine speech against devils who whisper into the ears of wandering poets.

**The Refrain of Sovereign Justice and Boundless Mercy**

The profound rhetorical power of Sūrah ash-Shuʿarāʾ lies in its relentless, eightfold repetition of the dual divine attributes: *Al-ʿAzīz* (The Almighty) and *Al-Raḥīm* (The Merciful). Through this cadence, the sūrah hammers an immutable historical truth into human consciousness: tyrants may amass wealth, carve stone mountains, construct monuments, and hire eloquent poets to glorify their empires, but they cannot escape the moral governance of the universe. When nations choose arrogance over truth, the Almighty (*al-ʿAzīz*) dismantles their civilizations; yet even in judgment, He is the Merciful (*al-Raḥīm*) who always delivers the humble, beleaguered messengers and their righteous companions."""

# -------------------------------------------------------------
# SURAH 27: AN-NAML
# -------------------------------------------------------------
intros[27] = """**The Language of Creation and the Throne of Sheba**

An-Naml, "The Ant," is the twenty-seventh chapter of the Qur'an, comprising 93 verses of mature Makkan revelation. It is the middle chapter of the *Ṭā-Sīn* tri-sūrah cluster and takes its title from the delightful and profound scene in verses 18–19, where an ordinary female ant (*namlah*), observing the advancing legions of Solomon, warns her colony to enter their subterranean dwellings lest they be crushed unawares by Solomon and his soldiers—prompting Solomon to smile in joy and offer a profound prayer of gratitude for the divine favors bestowed upon him and his parents. Sūrah an-Naml is also unique in scriptural codex geography as containing the second *Basmalah* of the Qur'anic text: appearing not as a chapter header, but inside verse 30 within the diplomatic letter sent by King Solomon to Bilqīs, the Queen of Sheba: *“Indeed, it is from Solomon, and indeed, it is: 'In the name of Allah, the Most Compassionate, Most Merciful.'”* Sūrah an-Naml is a magnificent theological celebration of divine knowledge, illustrating how absolute worldly power, technological mastery, and knowledge of the natural world can be harmonized with supreme spiritual humility and surrender to the One God.

**The Contrast Between Worldly Power and Divine Wisdom**

The historical context of an-Naml reflects the late Makkan confrontation between the Prophet ﷺ and the wealthy, self-satisfied Qurayshi leadership. The Quraysh viewed worldly power as an excuse for arrogance, tribal domination, and the oppression of the weak. Sūrah an-Naml shatters this worldview by staging the historical spectacle of David and Solomon—prophets who were granted vast imperial dominion, mastery over metallurgy, comprehension of the language of birds (*manṭiq al-ṭayr*), and command over jinn, humans, and winds. Yet far from intoxicating them with pride, this supreme wealth produced the deepest humility: *“This is from the favor of my Lord to test me whether I will be grateful or ungrateful”* (27:40). The sūrah asks the Makkans: if a monarch possessing the dominion of Solomon could bow his forehead to the ground in gratitude before an ant, what excuse has an ordinary merchant in the desert to strut with arrogance?

**The Structural Architecture and the Court of Solomon**

The architecture of Sūrah an-Naml moves from prophetic signs to imperial diplomacy, and from geological cosmology to eschatological reckoning. The opening movement (1–14) proclaims the Qur'an as good tidings for the believers, recounts Moses at the burning bush where his staff becomes a serpent and his hand becomes radiantly white without disease, and depicts Pharaoh's obstinate rejection: *“And they rejected them unjustly and arrogantly, while their souls were convinced of them”* (27:14). The second and celebrated movement (15–44) presents the court of David and Solomon: Solomon inheriting the kingdom, marching with his hosts through the Valley of the Ants, missing the lapwing (*al-Hudhud*), and receiving the bird's extraordinary intelligence report regarding the wealthy Queen of Sheba (*Bilqīs*) who, along with her people, worshipped the sun instead of Allah. It traces the diplomatic exchange: Solomon's monotheistic letter, the Queen's gift rejected by Solomon, the miraculous transportation of the Queen's massive throne in the twinkling of an eye by a courtier endowed with knowledge of the Scripture (*ʿindahu ʿilmun min al-Kitāb*), the test of the modified throne, the palace courtyard paved with crystalline glass that the Queen mistakes for a pool of water, and her triumphant declaration of faith: *“My Lord, indeed I have wronged myself, and I submit with Solomon to Allah, Lord of the worlds”* (27:44). The third movement (45–58) reviews the fate of Thamūd, where nine conspirators who plotted to assassinate Ṣāliḥ and his family were wiped out overnight, followed by the rescue of Lot from his depraved town. The fourth movement (59–93) delivers the magnificent litany of cosmic rhetorical questions: *“Is not He [better] who created the heavens and the earth and sent down for you rain... Is there a deity with Allah?”* (repeated five times, 27:60–64), introduces the mysterious apocalyptic sign of the *Beast of the Earth* (*Dābbat al-Arḍ*, 27:82) who will speak to humanity when judgment is near, describes the mountains passing away like clouds on that Day (27:88), and concludes with the Prophet's personal manifesto: *“I have only been commanded to worship the Lord of this city [Makkah], who made it sacred, and to Him belongs all things, and I have been commanded to be of the Muslims, and to recite the Qur'an.”*

**The Omnipresence of Divine Sovereignty**

The central spiritual philosophy of Sūrah an-Naml is that true intelligence perceives the sacred speech woven throughout all creation. The ant in her subterranean burrow has an articulate voice; the bird in the sky carries moral discernment; the glass floor reflects the light of truth; and the human soul is summoned to read these signs. By contrasting the enlightened surrender of the Queen of Sheba—who yielded her sovereignty to the Creator the moment truth became manifest—against the blind obstinacy of the Qurayshi chieftains who denied signs they inwardly knew to be true, Sūrah an-Naml demonstrates that nobility is found only in the surrender of the ego to the Lord of all worlds."""

# -------------------------------------------------------------
# SURAH 28: AL-QAṢAṢ
# -------------------------------------------------------------
intros[28] = """**The Narrative of the Oppressed and the Mirage of Tyranny**

Al-Qaṣaṣ, "The Stories," is the twenty-eighth chapter of the Qur'an, comprising 88 verses of late Makkan revelation. It is the final and most detailed of the three *Ṭā-Sīn-Mīm* chapters, taking its title from verse 25, where Moses arrives exhausted at the wells of Midian and recounts *al-qaṣaṣ* (the narrative of his life) to the venerable elder (traditionally identified with Shuʿayb or a righteous Midianite patriarch), who consoles him with the words: *“Do not fear; you have escaped from the wrongdoing people.”* Sūrah al-Qaṣaṣ is particularly renowned in Islamic history for verse 85, traditionally revealed at the station of Juḥfah during the Prophet's dangerous, sorrowful emigration (*Hijrah*) from Makkah to Madinah: *“Indeed, He who has mandated upon you the Qur'an will surely return you to an appointment / place of return (*maʿād*)”*—a divine guarantee that he would return victorious to the city from which he was being driven. The sūrah provides the most emotionally intimate, biographical account of the infancy, youth, exile, and prophetic commissioning of Moses found in the entire sacred text, framed as an explicit, living mirror for the persecuted Prophet Muḥammad ﷺ and his companions.

**The Arrogance of Oligarchs and the Consolation of the Exiled**

The historical canvas of al-Qaṣaṣ is defined by the absolute asymmetrical confrontation between imperial tyranny and vulnerable faith. In Makkah, a tiny band of disenfranchised believers was surrounded by the arrogant Qurayshi oligarchy, who boasted of their wealth, mercantile networks, and military power, threatening the Muslims with extermination. Sūrah al-Qaṣaṣ opens with a revolutionary divine charter in verses 4–5: Pharaoh exalted himself in the land and divided his people into factions, slaughtering their male infants and keeping their women alive; yet the divine decree states: *“And We wished to confer favor upon those who were oppressed in the land, and make them leaders, and make them the inheritors, and establish them in the land, and show Pharaoh and Hāmān and their soldiers through them that which they feared.”* This was a thunderous reassurance to the early Muslims: the God who brought down the greatest superpower of the ancient world through a helpless infant floating in a wooden basket upon the Nile was the very same God watching over the believers in the rocky alleys of Makkah.

**The Epic Biography of Moses and the Fall of Qārūn**

The architecture of Sūrah al-Qaṣaṣ is built around two monumental historical portraits: the political tyranny of Pharaoh versus the divine empowerment of Moses, and the financial hubris of Korah (*Qārūn*) versus the spiritual wealth of the righteous. The first movement (1–43) delivers the gripping, cinematic narrative of Moses: Pharaoh's murderous decree, the desperate mother of Moses inspired to cast her infant into the Nile, the baby fetched by the family of Pharaoh, the intervention of Moses' sister watching from afar, Moses refusing all wet-nurses until his own mother's breast is restored to him *“so that her eye might be comforted and she might not grieve and that she might know that the promise of Allah is true”* (28:13). It traces his youth: the accidental manslaughter of the Egyptian while defending an Israelite, the secret warning from a man running from the furthest end of the city that the council was plotting his execution, Moses fleeing in terror across the desert to Midian, watering the flocks for the two modest daughters of the elderly sage, being hired for eight or ten years of service, traveling with his family in the cold, seeing the divine fire at the side of Mount Ṭūr, receiving the staff and radiant hand, returning to confront Pharaoh, and Pharaoh's minister Hāmān ordered to build a lofty brick tower to view the God of Moses, culminating in the drowning of the tyrant and his armies cast into the sea like refuse. The second movement (44–75) turns to the Prophet Muḥammad ﷺ, confirming that he was not present on the western slope of Sinai when the decree was given, nor among the people of Midian, but this revelation is a direct mercy from his Lord. It rebukes the pagan excuses that following guidance would cause them to be snatched from their land, and presents the tragic narrative of Qārūn (76–84): an Israelite possessed of such vast treasures that the mere keys to his vaults weighed down a band of strong men, who boasted that his riches were acquired through his own scientific intellect (*“I was only given it because of knowledge I have,”* 28:78). The sūrah describes the catastrophic climax: the earth splitting open and swallowing Qārūn, his palatial estate, and his gold into the subterranean void, leaving the materialistic onlookers who had previously envied him to reflect with horror on their folly. The epilogue (85–88) delivers the promise of return to Makkah, commands the Prophet never to be an assistant to the disbelievers, and concludes with the immortal metaphysical declaration of verse 88: *“Everything will perish except His Face. To Him belongs the judgment, and to Him you will be returned.”*

**The Ultimate Law of Historical Inversion**

The foundational thesis of Sūrah al-Qaṣaṣ is the divine principle of historical inversion: that worldly power divorced from moral righteousness contains the seeds of its own destruction, while vulnerable faith nurtured in patience is destined to inherit the earth. Pharaoh tried to murder all male infants to prevent a savior from rising, yet God made Pharaoh pay for that savior's milk and raise him inside his own royal bedchambers. Qārūn imagined his financial genius made him immortal, yet the very earth from which he extracted his gold opened up to swallow him whole. Sūrah al-Qaṣaṣ teaches that the only reality that survives the wreck of time and empires is that which is attached to the Eternal Face of God (*kullu shay'in hālikun illā wajhah*)."""

# -------------------------------------------------------------
# SURAH 29: AL-ʿANKABŪT
# -------------------------------------------------------------
intros[29] = """**The Web of Delusion and the Crucible of Tribulation**

Al-ʿAnkabūt, "The Spider," is the twenty-ninth chapter of the Qur'an, comprising 69 verses. While primarily a late Makkan revelation, classical authorities (including al-Qurṭubī and Ibn ʿAbbās) record that its opening eleven verses were revealed in connection with early events in Madinah or during the painful departures of the *Hijrah*, when converts were subjected to brutal familial and physical trials. It takes its memorable name from the striking ecological and theological parable in verse 41: *“The example of those who take allies other than Allah is like that of the spider who builds a house. And indeed, the flimsiest of houses is the house of the spider, if they only knew!”* Sūrah al-ʿAnkabūt is the great psychological manual on *Fitnah*—the fiery testing and examination of human conviction—opening with the penetrating existential question that cuts through all superficial religious sentiment: *“Do the people think that they will be left to say, 'We believe' and they will not be tested?”* (29:2).

**The Crucible of Persecution and the Agony of Families**

The historical atmosphere of al-ʿAnkabūt reflects the acute agony of early Muslims whose embrace of Islam tore apart the sacred fabric of Arab kinship. Young men and women who accepted the faith—such as Saʿd ibn Abī Waqqāṣ, whose mother went on a public hunger strike, threatening to starve herself to death unless he renounced Muḥammad—found their deepest filial bonds weaponized against their conscience. Sūrah al-ʿAnkabūt legislates the delicate, revolutionary balance: honor your parents, treat them with boundless kindness, but if they strive to make you associate partners with God of which you have no knowledge, *do not obey them* (29:8). The sūrah addresses those who were physically tortured, forced to flee across deserts, and mocked by their elders who promised: *“Follow our way, and we will carry your sins”* (29:12). It exposed the fair-weather believers and hypocrites who treat the persecution of men as if it were the punishment of God (29:10), retreating from the frontline of conviction at the first whisper of discomfort.

**The Structural Architecture and the House of Silk**

The movement of Sūrah al-ʿAnkabūt weaves between existential diagnostic questions, prophetic endurance through time, and cosmic reassurance. The opening movement (1–13) defines the universal law of spiritual examination (*al-ibtilāʾ*): faith is not an inherited badge or an empty verbal claim; it is a metal that must be thrust into the furnace of life to burn away the slag of hypocrisy and prove the gold of sincerity. The second movement (14–40) conducts an unblinking historical survey of prophetic testing:
- Noah (14–15): Preaching for 950 years in an agonizing, slow struggle without visible societal transformation, yet persevering until the Deluge cleansed the earth and the Ark was preserved as a sign.
- Abraham (16–27): Thrown into the blazing fire by his own father and community, delivered by divine decree, and declaring: *“Indeed, I will emigrate to [the service of] my Lord; He is the Exalted in Might, the Wise.”*
- Lot (28–35): Bearing witness against the grotesque public depravity of Sodom, standing entirely alone until the angelic messengers arrived to execute divine judgment.
- Shuʿayb (36–37), ʿĀd, Thamūd, and the archetypal trinity of arrogance: Qārūn (plutocracy), Pharaoh (autocracy), and Hāmān (technocracy and propaganda), all seized in their sins—some struck by a violent windstorm, some by the screaming blast, some swallowed by the earth, and some drowned in the sea (29:40).
The third movement (41–55) delivers the supreme parable of the Spider's Web: analyzing polytheism and reliance on worldly powers. A spider weaves an intricate, beautifully geometric web that appears elaborate and protective, yet it is completely flimsy, possessing no walls, offering no protection against heat, cold, rain, or physical impact, and functioning as a site of domestic cannibalism where the female often slays the male. Such is the fragile delusion of anyone who anchors his ultimate security in wealth, military pacts, or false gods. It balances this with the command to recite the Scripture, establish the prayer—for *“indeed, prayer deters from indecency and wickedness”*—and declare that the remembrance of God is greatest (*wa-la-dhikru Allāhi akbar*, 29:45). The closing movement (56–69) comforts the oppressed with the vastness of God's earth, reminding them that exile is better than compromise (*“O My servants who have believed, indeed My earth is spacious, so worship only Me,”* 29:56), reminding all souls that every soul shall taste death (29:57), and concluding with the glorious divine promise of verse 69: *“And those who strive for Us—We will surely guide them to Our ways. And indeed, Allah is with the doers of good.”*

**The Fragility of the Earthly Citadel**

The central spiritual message of Sūrah al-ʿAnkabūt is the radical distinction between the fragile web of worldly reliance and the unshakeable reality of divine companionship. Human beings spend lifetimes spinning elaborate spider-webs of social connections, financial accounts, and political alliances, convincing themselves that their silk houses are impregnable castles. But at the first breath of mortality or divine shaking, the web dissolves into nothingness. Sūrah al-ʿAnkabūt calls humanity to abandon the spider's illusion, step into the spacious reality of God's guidance, and realize that no struggle endured for the sake of the Divine is ever lost: *“We will surely guide them to Our ways.”*"""

# -------------------------------------------------------------
# SURAH 30: AR-RŪM
# -------------------------------------------------------------
intros[30] = """**The Geopolitical Miracle and the Primordial Blueprint**

Ar-Rūm, "The Romans" (the Byzantine Empire), is the thirtieth chapter of the Qur'an, comprising 60 verses of late Makkan revelation. It opens with the mysterious letters *Alif-Lām-Mīm* followed immediately by one of the most audacious, internationally significant prophecies in the history of sacred scripture: *“The Romans have been defeated in the nearer land, but they, after their defeat, will overcome within three to nine years (*fī biḍʿi sinīn*)”* (30:2–4). In prophetic tradition, this astonishing prophecy is documented in Jāmiʿ al-Tirmidhī (3193) and historical chronicles as a stunning vindication of revelation: when the pagan Persians conquered the Christian Byzantine territories of the Levant and sacked Jerusalem in 614 CE, the pagan Quraysh rejoiced, gloating that their fellow polytheists had crushed a monotheistic scriptural empire. They taunted the Muslims that they would similarly wipe out Islam. Abū Bakr boldly placed a wager against the Qurayshi nobility that Byzantium would rise again within the decade. Within nine years, the Byzantine Emperor Heraclius launched a miraculous counter-offensive, penetrating the heart of Persia and routing the Sasanian forces in 624 CE—coinciding exactly with the Muslim victory over the Quraysh at the Battle of Badr! Sūrah ar-Rūm conjoins this stunning geopolitical turnaround with an exhaustive contemplation of the *Fiṭrah*—the innate, pristine spiritual constitution imprinted by God upon every human soul.

**The Superpowers of Late Antiquity and the Qurayshi Blindness**

The historical canvas of ar-Rūm transcends the regional confines of the Arabian desert, placing early Islam directly within the high-stakes clash of the two global superpowers of Late Antiquity: the Eastern Roman (Byzantine) Empire and the Sasanian Persian Empire. The Quraysh, engrossed in their caravan profits, viewed world events with shallow materialism, assuming that military might and imperial dominance were arbitrary rolls of the dice. Sūrah ar-Rūm exposes their superficiality: *“They know what is apparent of the worldly life, but of the Hereafter they are heedless”* (30:7). It teaches that geopolitical empires do not rise and fall by military mechanics alone; they are governed by transcendent moral laws established by the Lord of the worlds.

**The Structural Modulation and the Hymn of Signs**

The architecture of Sūrah ar-Rūm unfolds in four tightly woven movements. The opening movement (1–19) announces the geopolitical prophecy, declares that ultimate authority belongs to Allah before and after (*lillāhi al-amru min qablu wa-min baʿd*), and predicts that on the day of Roman victory the believers will rejoice in the help of Allah. It then stages the bifurcation of humanity on the Day of Resurrection, when the wicked are plunged into despair while the righteous rejoice in verdant gardens. The second movement (20–27) delivers the celebrated *Hymn of Divine Signs* (*Āyāt Allāh*), repeating the majestic phrase *“And of His signs is that...”* across six magnificent cosmic realities:
1. Creating humanity from dust, then multiplying them as conscious human beings.
2. Creating spouses from among yourselves that you may find tranquility in them, placing between you love and mercy (*mawaddatan wa-raḥmah*, 30:21).
3. The creation of the heavens and earth, and the magnificent diversity of human languages and skin colors (30:22).
4. Sleep by night and day, and the pursuit of livelihoods.
5. Showing lightning as fear and hope, and sending down rain to revive the dead earth.
6. The heavens and earth standing firm by His command, and all creatures in heaven and earth obediently submitting to Him.
The third movement (28–45) introduces the profound concept of the *Fiṭrah* in verse 30: *“So direct your face toward the religion, inclining to truth—the nature of Allah (*Fiṭrat Allāh*) upon which He has created mankind. No change should there be in the creation of Allah. That is the correct religion, but most of the people do not know.”* It warns against fracturing religion into sectarian factions, exposes human fickleness in times of distress versus ease, and forbids the predatory injustice of usury (*ribā*), contrasting it against the pure wealth given in Zakat. The closing movement (46–60) returns to the winds carrying rain as tidings of grace, reflects upon the stages of human biological existence—weakness in infancy, strength in youth, and weakness and gray hair in old age (30:54)—and concludes with the supreme command of endurance to the Prophet: *“So be patient. Indeed, the promise of Allah is truth. And let not those who have no certainty shake your firmness / discourage you”* (30:60).

**The Symphony of Cosmic Order and Innate Soul**

The central philosophical message of Sūrah ar-Rūm is the profound harmony between the outer cosmos and the inner human spirit. The same God Who resurrects the dead earth through rain, Who guides the celestial orbits, and Who orchestrates the rise and fall of great empires, has planted an innate moral compass (*al-Fiṭrah*) within every human heart. Polytheism, injustice, and materialism are unnatural distortions that run contrary to the very grain of creation. By summoning humanity to align its will with its primordial nature, Sūrah ar-Rūm teaches that peace—both psychological and geopolitical—can only be realized when the soul surrenders to the Living God Who sustains the universe."""

for ch in [26, 27, 28, 29, 30]:
    insert_surah_intro(ch, intros[ch])
print("Batch 3 (Part B: 26-30) inserted successfully.")
