import sys
sys.path.append(".")
from scripts.intro_utils import insert_surah_intro

intros = {}

# -------------------------------------------------------------
# SURAH 1: AL-FĀTIḤAH
# -------------------------------------------------------------
intros[1] = """**The Gate of Revelation and the Mother of the Book**

Al-Fātiḥah, "The Opening," is the first chapter of the Qur'an by liturgical and codex arrangement, though not the first in the chronological order of descent. Comprising seven distinct verses, it is universally acclaimed across classical exegesis as *Umm al-Kitāb* (the Mother of the Book) and *Umm al-Qur'ān* (the Mother of the Qur'an), designations rooted in the principle that the entire metaphysical, moral, and eschatological corpus of divine revelation is folded into its concise phrasing. It is also termed *al-Sabʿ al-Mathānī* (the Seven Oft-Repeated Verses), directly referenced in divine speech (*“And We have certainly given you the seven often-repeated verses and the great Qur'an,”* 15:87), because no valid unit of the daily canonical prayer (*ṣalāh*) can be offered without its recitation. Other classical titles include *al-Kāfiyah* (the Sufficient), *al-Shāfiyah* (the Healing), *al-Wāfiyah* (the Complete), and *al-Ṣalāh* (the Prayer), the latter deriving from the famous *ḥadīth qudsī* in Ṣaḥīḥ Muslim wherein Allah declares: *“I have divided the prayer between Myself and My servant into two equal halves.”* In seven short lines, the sūrah gathers the primary dimensions of theology: the Divine Essence and Attributes, universal Lordship, gratuitous and sustaining mercy, the reality of the Final Judgment, uncompromised monotheistic worship, human vulnerability and petition, and the bifurcation of human destinies between grace and self-destruction.

**A Foundational Makkan Descent**

The preponderant view of classical scholars, including Ibn ʿAbbās, Qatādah, and al-Ṭabarī, is that al-Fātiḥah is an early Makkan revelation, sent down in its entirety near the beginning of the prophetic mission when regular communal and solitary prayer was established. Some early reports suggested a Medinan repetition—giving rise to the opinion that it was revealed twice, once in Makkah to establish the prayer and once in Madinah when the *qiblah* was altered—yet its status as the indispensable core of the Makkan prayer remains normative. Its original audience was the fledgling band of believers who needed a complete theological grammar before the detailed legal statutes of the later years were promulgated. It addressed souls surrounded by idolatry and ancestral fatalism, training the tongue to divest itself of tribal deities and attach itself directly to the transcendent yet intimately close Lord of All Worlds. It established a spiritual sanctuary: before a single law, prohibition, or civic statute was handed down, the believer was taught how to stand before the Divine, acknowledge sovereign mercy, and beg for the gift of perseverance upon the straight path.

**The Shape of the Sūrah**

The seven verses of al-Fātiḥah describe a luminous, symmetrical trajectory that ascends from divine praise to human petition, dividing precisely at its fourth verse. Verses 1–3 form the opening doxology: verse 1 inaugurates all existence in the comprehensive Name of Allah, conjoining supreme authority with universal benevolence (*al-Raḥmān*) and enduring, specific care (*al-Raḥīm*); verse 2 proclaims all praise (*al-ḥamd*) as the inherent, exclusive property of the Lord and Nurturer of all realms of creation (*Rabb al-ʿālamīn*); and verse 3 reiterates Divine compassion before the majestic terror of accountability. Verse 4 introduces the eschatological pivot, designating Allah as the sole Sovereign and Arbiter of the Day of Recompense (*Mālik Yawm al-Dīn*), stripping away all earthly delusions of autonomy. Verse 5 is the mathematical and spiritual center of the chapter, shifting the grammatical address from third-person description to direct second-person dialogue (*iltifāt*): *“You alone we worship, and You alone we ask for help.”* This conjoins exclusive devotional commitment with an admission of radical creaturely helplessness. Finally, verses 6–7 unfold the covenantal request: the plea for inward and outward rectitude (*al-ṣirāṭ al-mustaqīm*), defined historically and existentially as the path trodden by those upon whom divine grace has descended (prophets, righteous saints, and martyrs), contrasted against the twin tragedies of willful rebellion (*al-maghḍūb ʿalayhim*) and ignorant wandering (*al-ḍāllīn*).

**The Dialectic of Praise and Petition**

What distinguishes al-Fātiḥah from every other chapter in scripture is its liturgical posture: it is revelation revealed in the voice of the servant. Where the rest of the Qur'an is Allah speaking directly to humanity, al-Fātiḥah is divine speech teaching humanity how to address the Divine. Exegetes note that Allah placed praise before petition because the protocol of the spiritual court demands that the servant acknowledge the majesty, benevolence, and sovereignty of the Monarch before presenting his personal petition. Yet the only petition granted vocal expression in this chapter is not for food, longevity, victory, or worldly ease; it is exclusively for *hidāyah* (guidance). Guidance is recognized as the singular human necessity that conditions all temporal and eternal felicity. By closing with the collective plural (*“we worship,” “we ask,” “guide us”*), al-Fātiḥah dissolves the atomized ego into the grand communion of worshippers, uniting all who seek the Straight Path across time and space."""

# -------------------------------------------------------------
# SURAH 2: AL-BAQARAH
# -------------------------------------------------------------
intros[2] = """**The Citadel of the Law and the Comprehensive Covenant**

Al-Baqarah, "The Cow," is the second and longest chapter of the Qur'an, spanning 286 verses and functioning as the foundational constitution of the nascent Muslim community (*ummah*). The chapter takes its name from the extended narrative in verses 67–73 regarding the heifer commanded to be slaughtered by the Children of Israel under Moses—a confrontation that exposed the psychological hazards of hair-splitting legalism, spiritual evasion, and the latent veneration of the golden calf. Revered as the *Sinām al-Qur'ān* (the Crest or Pinnacle of the Qur'an), the Prophet ﷺ described it as a fortress of spiritual protection, stating in Ṣaḥīḥ Muslim that Satan flees from any house in which Sūrah al-Baqarah is recited. Within its immense breadth, the sūrah gathers every major division of Islamic doctrine and jurisprudence: the transition of religious leadership from the ancestral line of the Israelites to the Abrahamic-Isma'ilitic lineage; comprehensive civil, penal, and domestic legislation; financial ethics culminating in the categorical abolition of usury (*ribā*); and the celebrated Verse of the Throne (*Āyat al-Kursī*, 2:255), the loftiest theological exposition of absolute Divine sovereignty in the entire sacred text.

**The Early Medinan Dawning and the Reordering of Society**

Revealed predominantly during the first two to four years following the *Hijrah* (migration) to Madinah—with certain verses, notably 2:281, traditionally held to be among the very final fragments of revelation sent down near the Prophet's Farewell Pilgrimage—al-Baqarah marks the historic pivot from an underground, persecuted fraternity in Makkah to a sovereign, self-governing commonwealth. Its immediate setting was a fractured urban oasis populated by three distinct constituencies: the Makkan Emigrants (*Muhājirūn*) who had forfeited home and property for faith; the Medinan Helpers (*Anṣār*) who pledged life and wealth in their defense; the indigenous Jewish tribes possessive of ancient scriptural prestige; and the emergent faction of hypocrites (*munāfiqūn*) led by ʿAbdullāh ibn Ubayy, whose outward declarations masked covert sabotage. To this complex social matrix, al-Baqarah brought an authoritative charter. It exposed the pathology of bad-faith compromise, audited the historic failures of prior scriptural communities, and established an autonomous institutional framework for the new community, anchored in prayer, charity, justice, and moral rectitude.

**The Shape and Movement of the Discourse**

The architecture of al-Baqarah is organized as a monumental grand synthesis. The prologue (1–39) opens with the enigmatic letters *Alif-Lām-Mīm*, delineating the threefold typology of human responses to revelation—the mindful (*muttaqūn*), the obdurate deniers, and the hypocrites—before staging the primordial creation of Adam as earth's viceregent (*khalīfah*) and his triumph over Satan's envy through repented knowledge. The second movement (40–141) delivers an exhaustive polemical and pastoral address to the Children of Israel, recalling the exodus, the favors at Sinai, the sabbath-breaking, and the slaughter of the cow, culminating in the spiritual pedigree of Abraham and Ishmael building the Kaʿbah as a universal sanctuary. The third movement (142–242) enacts the formal independence of the new community, inaugurated by the redirection of the prayer direction (*qiblah*) from Jerusalem to Makkah (142–152), followed immediately by statutory laws governing social life: retaliation and homicide, bequests, fasting in Ramadan, fighting in self-defense, pilgrimage rites, marriage, divorce, nursing, and orphan care. The fourth movement (243–260) contemplates the psychology of collective struggle, illustrating through Saul, Goliath, and David that spiritual fidelity triumphs over numerical superiority, and anchoring this struggle in the metaphysical immensity of *Āyat al-Kursī* (2:255). The climax (261–283) constructs the economic architecture of Islam, contrasting voluntary philanthropic spending (*infaq*) against the predatory exploitation of usury (*ribā*), and legislating the detailed contract law of verse 282 (the longest single verse in the Qur'an). The epilogue (285–286) provides a serene, triumphant confession of faith by the Messenger and the faithful, beseeching divine forgiveness and deliverance from unbearable burdens.

**The Transfer of the Universal Stewardship**

The enduring theological argument of al-Baqarah is that spiritual election is neither an ethnic monopoly nor a genealogical entitlement, but a moral covenant preserved solely through obedient practice. By presenting the mirror of Israel's scriptural history directly beside the inauguration of Islamic sacred institutions, the sūrah issues an urgent prophylactic warning to the Muslim community: covenantal honor is maintained only through vigilance, integrity, and unswerving adherence to the Divine command. Through its balance of soaring theological contemplation and exacting legal regulation, al-Baqarah proves that true piety (*al-birr*) does not consist in sterile exterior forms, but in a living synthesis of deep faith, generous economic solidarity, social equity, and absolute surrender to the Lord of the worlds."""

# -------------------------------------------------------------
# SURAH 3: ĀLI ʿIMRĀN
# -------------------------------------------------------------
intros[3] = """**The Family of Imran and the Crucible of Steadfastness**

Āli ʿImrān, "The Family of Imran," is the third chapter of the Qur'an, comprising 200 verses of late-early Medinan revelation. Named after the pious lineage of Imran—the father of Maryam (Mary) and grandfather of ʿĪsā (Jesus)—the sūrah stands as the fraternal twin to Sūrah al-Baqarah. In prophetic tradition, the two chapters are jointly venerated as *al-Zahrāwayn* (the Two Radiant Ones), which the Prophet ﷺ promised would arrive on the Day of Resurrection like two dense clouds, two canopies of shade, or two flocks of birds in flight, pleading for the souls of those who recited and internalized them (Ṣaḥīḥ Muslim 804). While al-Baqarah engaged predominantly with the Mosaic legacy and the establishment of communal law following the triumphant victory at Badr, Āli ʿImrān addresses the Christian theological landscape and navigates the psychological trauma and internal fractures that followed the catastrophic setback at the Battle of Uḥud in 3 AH. It is a sūrah of ideological clarification and moral resilience, forging an unyielding spiritual temper capable of withstanding theological seduction from without and battlefield despair from within.

**The Deputation of Najrān and the Aftermath of Uḥud**

The historical canvas of Āli ʿImrān is anchored in two defining moments of the Medinan period. The first is the interfaith theological summit held in the Prophet's mosque around 9 AH with the prominent Christian delegation from Najrān (in southern Arabia), who engaged in extensive dialectical debates concerning the nature, divinity, and sonship of Jesus. Verses 1–80 offer a devastatingly lucid, compassionate, yet uncompromising correction of Christian Christology, reasserting Christ's pure prophetic humanity and miraculous birth while exposing the philosophical incoherence of trinitarian dogma. The second historical theater occupies the latter half of the sūrah (verses 121–180), which conducts an agonizing post-mortem of the Battle of Uḥud. At Uḥud, a breach of prophetic discipline by archers seeking war booty transformed an imminent Muslim victory into military calamity, leading to the wounding of the Prophet ﷺ, the martyrdom of seventy eminent Companions (including Hamzah), and a dangerous surge in enemy morale. The sūrah confronts this collective bereavement not with despair, but with penetrating divine therapy: purifying the believers' motives, rebuking cowardice, and explaining the pedagogical role of worldly defeat in sifting true conviction from self-serving delusion.

**The Structure and Thematic Modulation**

The architecture of Āli ʿImrān moves from metaphysical epistemic principles to historical narrative, and from polemical discourse to the psychology of military struggle. The opening section (1–32) establishes the hermeneutics of divine scripture, famously distinguishing between foundational, clear verses (*muḥkamāt*) and allegorical verses (*mutashābihāt*), while exposing how diseased hearts pursue ambiguity to foment discord. The second movement (33–63) details the sacred history of the Imranic house: the barren wife of Imran dedicating her unborn child to God, the dedicated sanctuary life of Maryam nurtured with miraculous fruit, the miraculous birth of Yahya to elderly Zechariah, and the sublime conception of ʿĪsā through the divine word *Kun* ("Be!"). Verses 64–99 summon the People of the Book to a common platform of absolute monotheism (*“Come to a word that is equitable between us and you,”* 3:64), deconstructing sectarian claims by demonstrating that Abraham preceded both the Torah and the Gospel. The fourth movement (100–120) charges the Muslim community with institutional vigilance, establishing them as *“the best community brought forth for humanity”* through the imperative of enjoining good and forbidding evil. The fifth and largest movement (121–189) provides the sweeping commentary on Uḥud: unmasking the whispering of the hypocrites, comforting the bereaved, forbidding predatory interest (*ribā*) in the midst of military struggle, and celebrating the immortal life of the martyrs (*“Never think of those killed in the cause of Allah as dead,”* 3:169). The epilogue (190–200) closes with the famous contemplation of the cosmic signs by those of deep intellect (*ulū al-albāb*), concluding with the comprehensive moral imperative: *“Be patient, encourage endurance, station yourselves, and be mindful of Allah, that you may prosper.”*

**Steadfastness as the Ultimate Virtue**

The unifying core of Āli ʿImrān is *thabāt*—unyielding steadfastness in conviction and action. Whether standing before theological sophistry that blurs the transcendence of the Creator, or facing physical iron and blood upon the mountain ridges of Uḥud, the believer is summoned to look past worldly circumstance to the sovereign decree of the Ever-Living, Self-Sustaining God (*al-Ḥayy al-Qayyūm*). The chapter teaches that earthly setbacks do not signify divine abandonment, but are providential tests designed to cleanse the spirit of arrogance and detach the heart from reliance upon personalities. By grounding ultimate victory not in human perfection but in Divine grace, Āli ʿImrān transforms grief into enduring strength, leaving the community anchored in intellectual clarity and unwavering spiritual resolve."""

# -------------------------------------------------------------
# SURAH 4: AL-NISĀʾ
# -------------------------------------------------------------
intros[4] = """**The Defense of the Vulnerable and the Social Fabric**

Al-Nisāʾ, "The Women," is the fourth chapter of the Qur'an, spanning 176 verses of rich Medinan legislation. It derives its title from its unprecedented and pervasive concern with the legal rights, familial status, economic autonomy, and social protections accorded to women. Classical scholars categorized it as one of the seven long sūrahs (*al-Sabʿ al-Ṭiwāl*) that establish the institutional foundation of Islamic civilization. Where prior pagan and imperial societies treated women and minor dependents as chattel or legal nonentities, Sūrah al-Nisāʾ systematically dismantled patriarchal hegemony, legislating compulsory shares of inheritance for women, establishing consent and financial endowments (*mahr*) in marriage, criminalizing the usurpation of widows' property, and instituting strict judicial oversight over the estates of orphans. Far from being a mere dry legal code, the sūrah grounds every legal obligation in the absolute sovereignty of Allah and the sanctity of common human origin, reminding humanity in its very first breath that the entire species was engendered *“from a single soul”* (4:1).

**A Society in Crisis Following Uḥud**

Revealed across the mid-Medinan epoch, primarily between 3 AH and 5 AH, al-Nisāʾ arose out of an acute social crisis. The disaster at Uḥud had left dozens of Muslim men dead, resulting in a sudden, overwhelming demographic emergency: hundreds of vulnerable widows and fatherless children were left without breadwinners in an austere tribal economy. Men of predatory instincts eyed the wealth of these affluent orphan girls, seeking marriage without fair dowries or embezzling their estates under the guise of guardianship. Al-Nisāʾ intervened with legislative thunder. It permitted limited polygyny specifically as a social welfare mechanism to absorb orphans and widows under conditions of absolute justice (*“and if you fear that you will not deal justly with the orphan girls, then marry those that please you of other women,”* 4:3), while immediately warning that if equitable treatment could not be maintained, monogamy was strictly mandatory. Simultaneously, the sūrah confronted the hostile maneuvers of the Medinan Jewish leadership and the treacherous double-agents among the hypocrites, formulating the military, intelligence, and civil laws required to protect the community from external annihilation and internal subversion.

**The Structural Fabric of the Sūrah**

The architecture of al-Nisāʾ unfolds in several interlocking legislative and political movements. The opening movement (1–14) lays the domestic bedrock: the rights of orphans, guardianship ethics, marriage contracts, and the mathematically rigorous distribution of inheritance estates, closed with solemn divine warnings that consuming orphan wealth is tantamount to swallowing fire into one's belly. The second movement (15–35) tackles sexual morality, incest prohibitions, legal repentance, property theft, domestic discord, and arbitration, emphasizing mutual consultation between spouses. The third movement (36–59) synthesizes individual piety with civic duty, mandating benevolence to parents, kin, orphans, neighbors, and wayfarers, while confronting religious envy and ordaining the fundamental charter of governance and judiciary: *“Indeed, Allah commands you to render trusts to whom they are due and when you judge between people to judge with justice”* (4:58). The fourth movement (60–104) examines national security, the psychology of cowardice and hypocrisy, the duty of military mobilization, protective intelligence handling, the tragedy of accidental manslaughter, and the rules of engagement during warfare, famously interrupted by the sublime prescription for the Prayer of Fear (*Ṣalāt al-Khawf*, 4:102) to demonstrate that liturgical communion must never be abandoned even in the trenches. The fifth movement (105–136) turns to judicial integrity, immortalized by the case of a Jewish man falsely framed for theft by a Muslim clan, whereupon revelation descended to clear the innocent outsider and forbid the Prophet from advocating for deceitful partisans (4:105–107), culminating in the monumental command to uphold justice even against oneself, parents, or kin (4:135). The final movement (137–176) exposes hypocritical alliances, corrects extreme Christian doctrines regarding Jesus and the Trinity, and concludes with a definitive legal postscript on lateral inheritance (*al-kalālah*).

**Justice as the Indivisible Seal of Faith**

The primary theological argument of al-Nisāʾ is that worship of the Transcendent God is indivisible from the protection of vulnerable humanity. A society that offers prayers while expropriating the property of helpless orphans, or that claims belief while denying justice to women and marginal strangers, stands condemned by the Divine Law. By linking spiritual salvation directly to equitable contracts, domestic compassion, and fearless judicial objectivity, al-Nisāʾ transformed tribal customs into a universal ethic of accountability. It insists that justice is not a political expediency, but a sacred trust held under the gaze of an All-Hearing, All-Seeing Creator."""

# -------------------------------------------------------------
# SURAH 5: AL-MĀ'IDAH
# -------------------------------------------------------------
intros[5] = """**The Charter of Covenants and the Table of Communion**

Al-Mā'idah, "The Table Spread," is the fifth chapter of the Qur'an, comprising 120 verses of late Medinan revelation. It takes its name from the miraculous supper requested by the disciples of Jesus in verses 112–115—a heavenly banquet sought as a physical token of reassurance, which Jesus inaugurates with prayer and which Allah grants under the solemn condition that anyone who denies truth thereafter will suffer unprecedented retribution. Known in classical scholarship as *Sūrat al-ʿUqūd* (the Chapter of Contracts) from its striking opening imperative (*“O believers! Fulfil your obligations,”* 5:1), al-Mā'idah is universally recognized as the final comprehensive legal sūrah revealed to the Prophet ﷺ. In prophetic tradition, ʿĀ'ishah advised believers to hold fast to al-Mā'idah because *“whatever you find in it of lawful (*ḥalāl*), consider it lawful, and whatever you find in it of unlawful (*ḥarām*), consider it unlawful,”* reflecting the fact that its legal rulings were un-abrogated (*muḥkam*) and represented the ultimate maturation of the Islamic legal order.

**The Summit of Revelation and the Completion of Religion**

The chronological setting of al-Mā'idah occupies the final years of the prophetic mission (between 6 AH and 10 AH), culminating in the momentous events of the Farewell Pilgrimage (*Ḥajjat al-Widāʿ*) in the tenth year of the Hijrah. It was during this pilgrimage, on the plain of ʿArafāt on a Friday afternoon, that verse 3 descended: *“This day I have perfected for you your religion and completed My favor upon you and have approved for you Islam as your religion.”* So weighty was this revelation that reports in Musnad Aḥmad state the Prophet's camel knelt under the sheer physical gravity of its descent. Madinah was no longer an embattled enclave; Islam had unified the Arabian peninsula, the pagan sanctuaries were purified, treaties were consolidated, and the Muslim community stood as an established civilizational power. The historical task of al-Mā'idah was therefore twofold: to ratify the finalized moral, dietary, and ritual boundaries for this mature commonwealth, and to enter into a definitive, sweeping audit of previous covenant-holders—the Jews and Christians—warning the new community against replicating their theological distortion, factional jealousy, and covenantal infidelity.

**The Structural Architecture of the Sūrah**

The movement of al-Mā'idah weaves seamlessly between sacred ritual law, penal statutes, interfaith polemics, and cosmic eschatology. The opening movement (1–11) establishes the foundational sanctity of agreements, detailing dietary permissions and prohibitions, the ritual laws of purification (*wuḍūʾ* and *tayammum*), the marriageability of chaste believing and scriptural women, and the solemn covenant taken at the spring of guidance, anchored by the command: *“Do not let hatred of a people lead you to injustice; be just, that is closer to righteousness”* (5:8). The second movement (12–26) reviews the broken covenants of the Children of Israel and the Christians, demonstrating how the forgetting of divine admonitions spawned enduring enmity among them, punctuated by the tragedy of their refusal to enter the Holy Land under Moses (*“Go, you and your Lord, and fight! We are sitting right here,”* 5:24). The third movement (27–40) investigates the origins of human violence through the primeval fratricide of Cain and Abel (*Qābīl and Hābīl*), deriving from it the immortal sanctification of life: *“Whoever kills a soul... it is as if he had slain all mankind, and whoever saves one, it is as if he had saved all mankind”* (5:32), followed by the penal ordinances for banditry (*ḥirābah*) and theft. The fourth movement (41–50) forms the great judicial charter of revelation, comparing the Torah, the Gospel, and the Qur'an as divine lights and criteria, concluding that each scriptural community must be held to divine standards, culminating in the repudiation of pre-Islamic pagan ignorance (*ḥukm al-jāhiliyyah*). The fifth movement (51–86) regulates political alliances, denounces the mockery of prayer by hypocrites, refutes the Christian deification of Mary and Jesus (*“The Messiah, son of Mary, was not but a messenger,”* 5:75), and notes the spiritual tenderness of Christian monks contrasted with the hostility of dogmatic deniers. The sixth movement (87–108) legislates prohibitions against intoxicants, gambling, idolatrous altars, and divination arrows, sets the expiation for broken oaths, sanctifies the pilgrim state (*iḥrām*), and governs deathbed bequests. The grand finale (109–120) stages the awe-inspiring eschatological interrogation of Jesus on the Day of Judgment, wherein Christ categorically disavows that he ever commanded his followers to worship him or his mother beside Allah, sealing the discourse in verse 120: *“To Allah belongs the dominion of the heavens and the earth and whatever is within them, and He is over all things competent.”*

**The Ethics of Covenantal Integrity**

At its core, Sūrah al-Mā'idah is a profound meditation on the word *ʿAqd*—the knot that ties humanity to God and humans to one another. It argues that civilization collapses not from a lack of physical resources, but from the corrosion of fidelity: treaties signed and broken, scriptures acknowledged and altered, oaths uttered and betrayed, and justice sacrificed on the altar of tribal bias. By placing dietary purity, ethical restraint, and judicial incorruptibility under the single banner of covenantal obedience, al-Mā'idah demands that the believer's inner conscience and public institutions be held together by an unbreakable bond of integrity."""

for ch in [1, 2, 3, 4, 5]:
    insert_surah_intro(ch, intros[ch])
print("Batch 1 (Part A: 1-5) inserted successfully.")
