import sys
sys.path.append(".")
from scripts.intro_utils import insert_surah_intro

intros = {}

# -------------------------------------------------------------
# SURAH 16: AN-NAḤL
# -------------------------------------------------------------
intros[16] = """**The Symphony of Divine Favors and the Ministry of the Bee**

An-Naḥl, "The Bee," is the sixteenth chapter of the Qur'an, comprising 128 verses. In classical exegetical literature, it is universally designated as *Sūrat al-Niʿam* (The Chapter of Blessings or Favors), a title originating from early authorities including Qatādah and al-Baghawī because no other chapter in scripture enumerates with such comprehensive, luminous detail the inventory of divine gifts bestowed upon creation. It takes its specific scriptural name from verses 68–69, where the humble honeybee is revealed as the recipient of divine inspiration (*wa-awḥā rabbuka ilā al-naḥl*), instructed to build geometric dwellings in the mountains, trees, and human structures, and to extract nectar from diverse blooms, yielding a multi-hued fluid *“wherein is healing for humanity.”* Primarily a late Makkan composition, the sūrah captures the historic transition of the Muslim community, with its closing verses (124–128) reflecting the dawn of the Medinan epoch when ethical rules of legal retaliation and gracious patience were finalized.

**The Inventory of Grace Before an Ungrateful City**

Revealed during the twilight of the Makkan period when the idolatrous Quraysh maintained an obstinate refusal of the Prophet's mission, Sūrah an-Naḥl confronts a culture trapped in cosmological blindness. The Makkans enjoyed peace, mercantile wealth, and ancestral prestige within the sacred valley, yet ascribed their prosperity to wooden and stone idols carved with their own hands. An-Naḥl systematically demolishes this delusion by presenting an awe-inspiring, encyclopedic catalogue of cosmic provisions: livestock that yield warmth, beauty, and transport (16:5–8); rain descending from the clouds to produce olives, dates, grapes, and grains (16:10–11); the sun, moon, and stars subjugated for human navigation; the oceanic deeps providing fresh meat and lustrous pearls (16:14); and the miraculous production of pure, digestible milk flowing from between excrement and blood (*min bayni farthin wa-damin*, 16:66). The sūrah asks with devastating moral force: how can rational humans drink the milk, eat the honey, navigate by the stars, and breathe the air created by the One God, and then bow their heads before powerless partners?

**The Structural Modulation and Pastoral Guidance**

The architecture of Sūrah an-Naḥl moves in a rhythmic, undulating cadence between the physical cosmos, theological refutation, and civic ethics. The opening movement (1–21) delivers a startling beginning: *“The decree of Allah has come, so do not hasten it!”* (16:1), asserting absolute monotheism and contrasting the living Creator against mute idols who cannot create a fly and are themselves created. The second movement (22–40) investigates the inner psychology of the arrogant deniers whose hearts are closed, contrasting their haughty rejection against the serene reception of the pious by the angels of death, and confirming the immutable divine law that every community was sent a messenger proclaiming: *“Worship Allah and shun false gods”* (16:36). The third movement (41–83) unfolds the great hymn of natural blessings—rain, vegetation, livestock, milk, bees, and the blessing of marriage, offspring, and homes that provide rest—interrupted by the striking parable of the two men: a disenfranchised slave possessing no resources, compared to a free man endowed with generous provision who spends openly and secretly (16:75). The fourth movement (84–111) contemplates eschatological accountability: the witnessing of the prophets against their peoples, the repudiation of false deities on Judgment Day, the command to uphold covenants without deceit, and the sublime revelation of verse 90—traditionally recited in every Friday sermon across the Islamic world—commanding justice (*ʿadl*), excellence (*iḥsān*), and generosity to kin, while forbidding indecency, wickedness, and oppression. The closing movement (112–128) presents the parable of the prosperous, secure town that displayed ungratefulness for God's blessings, whereupon God enveloped it in hunger and terror (16:112), sets Abraham forward as an *Ummah* (an entire nation in a single man) who was perpetually grateful for divine favors, and concludes with the golden rule of Islamic discourse: *“Invite to the way of your Lord with wisdom and good instruction, and argue with them in a way that is best”* (16:125), sealing the chapter with the majestic promise: *“Indeed, Allah is with those who fear Him and those who are doers of good.”*

**The Philosophy of Conscious Gratitude**

The supreme theological message of Sūrah an-Naḥl is that *Shukr* (gratitude) is not an emotional sentiment, but an intellectual and spiritual duty. To live on this earth, enjoying its fruits and breathing its oxygen, while denying the Creator, is the ultimate form of cosmic injustice. By taking the bee—an insect that works selflessly, follows divine inspiration, organizes a harmonious community, and produces sweet healing for others—the sūrah provides an immortal ecological and spiritual parable: the human being must emulate the bee, receiving the pure blessings of God and transforming them into works of healing, justice, and illumination upon the earth."""

# -------------------------------------------------------------
# SURAH 17: AL-ISRĀʾ
# -------------------------------------------------------------
intros[17] = """**The Nocturnal Ascent and the Charter of Moral Excellence**

Al-Isrāʾ, "The Night Journey"—equally renowned across classical scholarship as *Sūrat Banī Isrā'īl* (The Children of Israel)—is the seventeenth chapter of the Qur'an, comprising 111 verses of late Makkan revelation. It derives its primary name from its electrifying opening declaration: *“Glory be to Him who took His servant by night from the Sacred Mosque to the Farthest Mosque, whose surroundings We have blessed, that We might show him of Our signs”* (17:1). This commemorates the historic *Isrāʾ* and *Miʿrāj*—the miraculous nocturnal journey of the Prophet Muḥammad ﷺ from Makkah to Jerusalem (Bayt al-Maqdis), and his subsequent ascension through the celestial spheres into the unmediated Divine Presence, where the five daily prayers were instituted. Revealed approximately one year prior to the Hijrah, at the absolute nadir of prophetic persecution in Makkah, Sūrah al-Isrāʾ stands as a monumental theological bridge: linking the Abrahamic sanctuary of Makkah with the prophetic sanctuary of Jerusalem, and issuing a comprehensive ethical manifesto that would form the civilizational foundation of the coming Medinan state.

**The Crucible of Isolation and the Cosmic Vindication**

The historical moment of al-Isrāʾ was one of profound human vulnerability and ultimate celestial honor. The Prophet's earthly protectors were gone, the mission to al-Ṭā'if had ended in blood and stoning, and the Qurayshi elite believed Islam was on the verge of extinction. In that moment of intense earthly helplessness, the heavens opened: the Prophet ﷺ was transported across space and time, led the entire assembly of prior prophets in prayer at the Temple Mount, and ascended beyond the Lot Tree of the Utmost Boundary (*Sidrat al-Muntahā*). When the Prophet recounted this journey the next morning, the Quraysh erupted in derisive laughter, demanding physical descriptions of Jerusalem to expose him as a fraud. Al-Isrāʾ descends not to defend the mechanics of the miracle, but to reveal its prophetic meaning: the mantle of universal spiritual leadership had been transferred. Jerusalem was no longer the exclusive monopoly of an ethnic dynasty that had repeatedly broken its covenant; it was now irrevocably bound to the final, universal revelation of Islam.

**The Structural Architecture and the Ethical Code**

The architecture of Sūrah al-Isrāʾ is designed around a dramatic shift from sacred geography to ethical legislation, and from epistemic critique to theological transcendence. The opening movement (1–8) conjoins the Night Journey with the scripture of Moses, delivering the celebrated prophecy regarding the Children of Israel: that they would twice cause corruption in the Holy Land and twice suffer catastrophic military ruin at the hands of powerful invaders, establishing the eternal rule: *“If you return [to righteousness], We will return [with mercy]; and if you return [to corruption], We will return [with punishment]”* (17:8). The second movement (9–22) establishes the Qur'an as the guide to that which is most upright (*yahdī lillatī hiya aqwam*), warns that every human being's destiny is fastened to his own neck, and introduces the famous universal moral charter of verses 23–39. This ethical code, often compared to the Decalogue, legislates the absolute worship of One God; filial piety toward aging parents (*“say not to them so much as 'uff' and do not repel them, but speak to them a noble word,”* 17:23); economic justice without squandering or tight-fistedness; the prohibition of infanticide out of poverty; the criminalization of adultery (*zinā*); the sanctification of human life; the protection of orphan property; and honesty in weights and measures. The third movement (40–70) critiques the pagan claim that angels are God's daughters, reminds humanity of the cosmic rebellion of Iblīs who refused Adam, and celebrates the intrinsic dignity bestowed upon the human species: *“And We have certainly honored the children of Adam and carried them on the land and sea and provided for them of the good things and preferred them over much of what We have created”* (17:70). The fourth movement (71–89) dramatizes the Quraysh's attempts to seduce the Prophet into compromise, commands the establishment of the night vigil (*Tahajjud*) and the prayer at the decline of the sun, and answers the Jewish inquiry regarding the Spirit (*al-Rūḥ*): *“Say, 'The Spirit is of the affair of my Lord, and mankind have not been given of knowledge except a little'”* (17:85). The closing movement (90–111) refutes the pagan demand for physical wonders (rivers gushing from earth, skies falling in pieces, gold houses), presents the magnificent discourse on the revelation being sent down in truth and descending with truth, and concludes with the sublime doxology of verse 111, instructing the Prophet to praise God who has taken no son, possesses no partner in dominion, and has no protector out of weakness.

**The Dignity of Man and the Ascent of the Soul**

The core philosophical insight of Sūrah al-Isrāʾ is that the Prophet's physical ascension (*Miʿrāj*) through the heavens is a model for the spiritual ascension of every human soul. Humanity has been intrinsically honored above much of creation (*wa-laqad karramnā banī Ādam*, 17:70), but this nobility is not an entitlement of pride; it is a capacity for transcendent communion with the Divine. By embedding the charter of human ethics—filial tenderness, social justice, and economic modesty—directly within the narrative of the celestial journey, al-Isrāʾ teaches that human beings cannot ascend to the heights of spiritual illumination without first walking upon the earth with humility, justice, and compassion."""

# -------------------------------------------------------------
# SURAH 18: AL-KAHF
# -------------------------------------------------------------
intros[18] = """**The Sanctuary of the Cave and the Antidotes to Tribulation**

Al-Kahf, "The Cave," is the eighteenth chapter of the Qur'an, comprising 110 verses of mature Makkan revelation. Positioned precisely at the mathematical center of the thirty parts (*juz'*) of the sacred text, Sūrah al-Kahf is universally celebrated for its profound eschatological and spiritual virtues. In authentic prophetic traditions, the Prophet Muḥammad ﷺ strongly urged its regular recitation every Friday, promising in Ṣaḥīḥ Muslim that *“Whoever memorizes ten verses from the beginning of Sūrah al-Kahf will be protected from the trial of the Anti-Christ (*al-Dajjāl*).”* It takes its name from the miraculous sanctuary of the cave (*al-kahf*) in which a small band of monotheistic youths took refuge to escape the lethal religious tyranny of a Roman emperor, where God caused them to sleep for over three centuries. Within its luminous tapestry, the sūrah presents four legendary narrative suites, each diagnosing and providing an invincible spiritual antidote to one of the four foundational temptations (*fitnah*) that threaten human civilization: the trial of faith (*dīn*), the trial of wealth (*māl*), the trial of knowledge (*ʿilm*), and the trial of power (*sulṭān*).

**The Jewish Riddle and the Makkan Crisis**

The historical occasion of al-Kahf is intimately tied to the intellectual struggles of the Makkan period. Troubled by the growing influence of the Prophet's message, the Quraysh dispatched an emissary delegation—including al-Naḍr ibn al-Ḥārith and ʿUqbah ibn Abī Muʿayṭ—to the rabbis of Yathrib (Madinah), seeking definitive questions to expose Muḥammad as a false claimant. The rabbis instructed them: *“Ask him about three matters that none know except a true prophet: ask him about the young men who disappeared in the ancient times; ask him about the traveler who journeyed from the east to the west; and ask him about the Spirit (*al-Rūḥ*).”* When the Quraysh posed these questions, the Prophet ﷺ promised an answer the following day without uttering the conditional phrase *In shā' Allāh* ("If Allah wills"). In response, revelation ceased for fifteen days, casting the Prophet into profound grief and causing the pagan aristocracy to boast that God had abandoned him. Sūrah al-Kahf descended at the end of this testing silence: delivering the answers to the historical riddles with breathtaking metaphysical depth, gently reproaching the Prophet in verses 23–24 (*“And never say of anything, 'I will do that tomorrow,' except [adding], 'If Allah wills'”*), and exposing the spiritual superficiality of his inquisitors.

**The Four Parables and the Grand Synthesis**

The architecture of Sūrah al-Kahf is an astonishing four-part symphonic masterpiece, structured around four primary stories interspersed with theological commentaries. The prologue (1–8) opens with fervent praise of Allah Who revealed the Book without crookedness (*lam yajʿal lahū ʿiwajā*), declaring that everything on earth has been made as an ephemeral ornament to test who is best in deed. The first narrative (9–26) recounts the Sleepers of the Cave (*Aṣḥāb al-Kahf*): young men who abandoned aristocratic families and social status to preserve their pure monotheism, sheltering in a mountain cave with their faithful dog, where God preserved their bodies for 309 solar/lunar years, demonstrating the ultimate victory of faith over political persecution. The second narrative (32–44) delivers the parable of the Two Gardens: an affluent agriculturalist who boasts of his orchards, wealth, and lineage, denying the resurrection, whose companion warns him to say *Mā shā' Allāh* ("What Allah wills; there is no power except in Allah"), before a cosmic whirlwind strikes his paradise, leaving him wringing his hands in regret over ruined vines—the archetype of the trial of wealth. The third narrative (60–82) stages the unforgettable odyssey of Moses and the mysterious, enlightened sage Khidr: Moses seeks spiritual knowledge and is tested by three perplexing, seemingly unethical actions—the scuttling of a poor fisherman's boat, the slaying of a young boy, and the rebuilding of a crumbling wall in a hostile town. Khidr subsequently unveils the hidden divine wisdom behind each event: protecting the boat from a predatory king, sparing the righteous parents from a tyrannical son, and preserving the buried treasure of two orphan boys, teaching the limits of human perception and the reality of the trial of knowledge. The fourth narrative (83–98) presents Dhū al-Qarnayn: the righteous global ruler endowed with supreme technology and military resources, who travels to the far west where the sun sets in a murky spring, the far east, and the mountainous barrier between two peaks, where he builds a massive iron and copper rampart to wall off the chaotic forces of Gog and Magog (*Ya'jūj wa-Ma'jūj*), attributing his monumental technological achievement not to personal genius, but to divine grace: *“This is a mercy from my Lord”* (18:98)—the antidote to the trial of power. The epilogue (102–110) warns against the ultimate losers in deeds: those whose effort is lost in worldly life while they imagine they are doing good, concluding with the cosmic metaphor of the ocean as ink: *“Say, 'If the sea were ink for the words of my Lord, the sea would be exhausted before the words of my Lord were exhausted'”* (18:109), and sealing the discourse with the call to pure, uncorrupted monotheism.

**The Reality Behind the Veil**

The profound spiritual philosophy of Sūrah al-Kahf is that the physical surface of reality is often the exact opposite of its spiritual truth. The cave that appeared to be a dark tomb was actually a sanctuary of resurrection; the damaged boat was actually saved from confiscation; the slain child was a mercy preventing parental destruction; and the crumbling wall concealed divine generosity. Sūrah al-Kahf trains the believer to look through the illusions of materialism, power, and surface phenomena—the very illusions by which the Anti-Christ (*al-Dajjāl*) will deceive humanity in the end times—and to anchor the heart in the sovereign, unseen wisdom of the All-Wise, All-Knowing Lord."""

# -------------------------------------------------------------
# SURAH 19: MARYAM
# -------------------------------------------------------------
intros[19] = """**The Sanctuary of Mercy and the Miracle of the Word**

Maryam (Mary) is the nineteenth chapter of the Qur'an, comprising 98 verses of early-to-mid Makkan revelation. It is the only chapter in the sacred scripture titled after a woman, honoring Maryam bint ʿImrān, the mother of Jesus, who is recognized in Islamic tradition as the pinnacle of female spiritual perfection across all human history (*“O Mary! Indeed Allah has chosen you, purified you, and chosen you above the women of the worlds,”* 3:42). Opening with the mysterious letters *Kāf-Hā-Yā-ʿAyn-Ṣād*, the sūrah is immersed from its first syllable in the radiant atmosphere of divine compassion, carrying the word *al-Raḥmān* (The Most Compassionate) sixteen times—a density unmatched by any other chapter in the Qur'an. Sūrah Maryam is an exquisite, lyrical symphony of divine grace, showing how the Almighty intervenes in the biological, social, and physical impossibilities of human life to bring forth life from barrenness, speech from silence, and redemption from despair.

**The Emigration to Abyssinia and the Shield of Negus**

The historical setting of Sūrah Maryam occupies a sacred, dramatic crossroads in early Islamic history. In the fifth year of the prophetic mission (approx. 615 CE), escalating torture and economic persecution by the Quraysh prompted the Prophet ﷺ to command a vulnerable group of early converts to seek political asylum across the Red Sea in the Christian Empire of Aksum (Abyssinia), advising them: *“In that land is a King under whom no one is wronged; it is a land of truth.”* The Quraysh dispatched two cunning diplomats, ʿAmr ibn al-ʿĀṣ and ʿAbdullāh ibn Abī Rabīʿah, bearing rich gifts of leather and luxury to convince the Christian monarch, the Negus (*al-Najāshī*), to extradite the refugees. Summoned before the royal court and the assembled bishops, Jaʿfar ibn Abī Ṭālib, the cousin of the Prophet, stood forward as the spokesman for the Muslims. When the Negus asked to hear what revelation their Prophet had brought regarding Jesus and Mary, Jaʿfar recited the opening passage of Sūrah Maryam (verses 1–36) in his sonorous, melodious voice. Historical chronicles record that the Negus wept until his beard was drenched, and his bishops wept until their scrolls were wet with tears. The Negus picked up a small splinter of wood from the floor and proclaimed: *“By God, the difference between what your Prophet has brought and what Jesus son of Mary taught is not more than the thickness of this twig!”* He granted the Muslims permanent diplomatic immunity, shattering the Qurayshi plot and securing the first sovereign sanctuary in Islamic history.

**The Structural Fabric of Prophetic Mercy**

The architecture of Sūrah Maryam unfolds in three sweeping, interconnected movements. The first movement (1–40) celebrates the miraculous genesis of two sacred lives: the elderly, white-haired prophet Zechariah (Zakariyyā), whose bones were frail and whose wife was barren, whispering a secret, desperate prayer for a righteous heir, answered instantly by the birth of Yahya (John the Baptist), endowed with wisdom and compassion while still a child; and Maryam retreating from her family to an eastern sanctuary, visited by the angel Gabriel (*Jibrīl*) in the form of a well-proportioned man, miraculously conceiving ʿĪsā through the Divine Word. It stages her agonizing labor pains beside the trunk of the date palm, her cry of mortal vulnerability (*“Oh, I wish I had died before this and was in oblivion, forgotten!”*, 19:23), her divine nourishment with fresh ripe dates and a running brook, her vow of sacred silence, and the climactic miracle of the infant Jesus speaking from the cradle to defend his mother's chastity: *“Indeed, I am the servant of Allah. He has given me the Scripture and made me a prophet”* (19:30). The second movement (41–65) reviews the prophetic lineage of pure monotheism: Abraham gently debating his idol-making father Azar with profound filial tenderness (*“O my father! Why do you worship that which does not hear and does not see?”*), enduring banishment to receive Isaac and Jacob; Moses summoned at the right side of the mountain; Ishmael commanding his people to prayer and charity; and Idris raised to a lofty station, culminating in the grief of later generations who abandoned prayer and pursued lusts. The third movement (66–98) turns with devastating polemical force upon the stubborn deniers who scoff at resurrection, demolishing the blasphemous assertion that the Most Compassionate has taken a son: *“You have said an atrocious thing! The heavens almost rupture therefrom and the earth splits open and the mountains collapse in devastation that they attribute to the Most Compassionate a son”* (19:89–91). The sūrah concludes with the glorious promise of divine love for the righteous: *“Indeed, those who have believed and done righteous deeds—the Most Compassionate will appoint for them affection (*wudd*)”* (19:96).

**The God of Tenderness and Absolute Transcendence**

The defining theological genius of Sūrah Maryam is its seamless reconciliation of profound intimacy with absolute cosmic majesty. The God of Maryam is not a cold, detached prime mover; He is *Al-Raḥmān*—the Loving Creator Who hears the whispered, trembling sigh of a childless old prophet in the night, Who comforts a frightened, isolated young mother beneath a date palm, and Who places sweet affection (*wudd*) in the hearts of humanity for those who walk in righteousness. Yet this tender God is simultaneously the Supreme Sovereign before Whom no entity in the heavens or earth can approach except as a humble servant (*“There is no one in the heavens and earth but that he comes to the Most Compassionate as a servant,”* 19:93). By tearing away the anthropomorphic myths of divine offspring while sanctifying the prophetic dignity of Jesus and Mary, the sūrah establishes the golden mean of true monotheism."""

# -------------------------------------------------------------
# SURAH 20: ṬĀ-HĀ
# -------------------------------------------------------------
intros[20] = """**The Celestial Consolation and the Burning Bush**

Ṭā-Hā is the twentieth chapter of the Qur'an, comprising 135 verses of early-to-mid Makkan revelation. It opens with the mysterious, tender disconnected letters *Ṭā-Hā*, which classical commentators such as Ibn ʿAbbās and al-Kalbī identified as an affectionate vocative address in the ancient dialect of Quraysh meaning *“O Man!”* or a direct, loving title bestowed upon the Prophet Muḥammad ﷺ himself. The opening lines of the sūrah contain one of the most sublime statements regarding the psychological and spiritual purpose of divine revelation: *“Ṭā-Hā. We have not sent down to you the Qur'an that you should be distressed (*li-tashqā*), but only as a reminder for those who fear [Allah]”* (20:1–3). Standing as the magnificent prophetic centerpiece of the mid-Makkan period, Sūrah Ṭā-Hā dedicates more than two-thirds of its text to the most extensive, intimate, and emotionally detailed biography of Moses (Mūsā) found anywhere in the sacred scripture.

**The Conversion of ʿUmar and the Transformation of History**

In the annals of early Islam, Sūrah Ṭā-Hā is immortalized as the catalyst that triggered the conversion of ʿUmar ibn al-Khaṭṭāb—an event that fundamentally altered the political destiny of the prophetic mission. In the sixth year of prophethood, ʿUmar, then a fierce and implacable persecutor of the faith, set out with a drawn sword through the streets of Makkah, determined to assassinate the Messenger of Allah ﷺ and terminate the division of his tribe. Intercepted by a secret convert who informed him that his own sister Fāṭimah and brother-in-law Saʿīd had embraced the new creed, ʿUmar stormed into their home, finding them listening to a parchment being recited by the Companion Khabbāb ibn al-Aratt. In a fit of fury, ʿUmar assaulted his brother-in-law and struck his sister across the face, drawing blood. Shamed by the sight of her blood and moved by her unshakeable defiance, ʿUmar demanded to read the parchment. Fāṭimah refused until he performed ritual ablution. When ʿUmar unrolled the scroll and read the opening verses of Sūrah Ṭā-Hā—*“Indeed, I am Allah. There is no deity except Me, so worship Me and establish prayer for My remembrance”* (20:14)—his heart melted, his intellectual arrogance shattered, and he exclaimed: *“How noble and sublime is this speech! Guide me to Muḥammad!”* He marched to the house of al-Arqam, where his public declaration of faith struck terror into the Quraysh and allowed the believers to pray openly beside the Kaʿbah for the first time.

**The Epic Narrative of Moses and Aaron**

The architecture of Sūrah Ṭā-Hā moves from celestial reassurance to the dramatic mountain encounter, and from the palace confrontation to the psychological collapse of Adam in the Garden. The opening movement (1–8) establishes that the Qur'an was not revealed to cause distress or exhaustion, affirming that the Most Compassionate has established Himself upon the Throne (*al-Raḥmānu ʿalā al-ʿarshi stawā*), owning all that is in the heavens, earth, and beneath the subterranean soil. The second and vast movement (9–98) presents the sacred epic of Moses: wandering with his family through the frigid darkness of Sinai, seeing a fire upon the slope of Mount Ṭūr, and hearing the Voice from the burning bush commanding him to cast down his staff and draw forth his radiant white hand. It records Moses' famous, deeply vulnerable supplication: *“My Lord, expand for me my breast, and ease for me my task, and untie the knot from my tongue that they may understand my speech, and appoint for me a minister from my family, Aaron my brother”* (20:25–30). The narrative proceeds through the historic liberation struggle: the confrontation with Pharaoh, the dramatic contest against the imperial magicians whose optical illusions are swallowed by Moses' living staff, the instantaneous conversion of the magicians who choose crucifixion over apostasy (*“So decree whatever you will decree; you can only decree for this worldly life,”* 20:72), the nocturnal flight through the parted sea, the drowning of Pharaoh's hosts, and the subsequent tragedy of the golden calf sculpted by the demagogue al-Sāmirī while Moses was communing on the mountain. The third movement (99–114) warns against turning away from the Reminder (*al-Dhikr*), describing the Day of Judgment when the mountains will be blasted into level dust and all voices will be hushed before the Most Compassionate (*wa-khashaʿati al-aṣwātu li-l-Raḥmān*), followed by the divine command to the Prophet: *“And do not hasten with the Qur'an before its revelation is completed to you, and say, 'My Lord, increase me in knowledge'”* (20:114). The fourth movement (115–127) recounts the primordial fall of Adam: forgetting the covenant, deceived by Satan's whisper of the tree of eternity, stripped of his garments, repenting to receive divine election, and descending to earth under the promise: *“Whoever follows My guidance will neither go astray nor suffer, but whoever turns away from My reminder will have a depressed, constricted life (*maʿīshatan ḍankā*).”* The sūrah concludes (128–135) with the command to endure the deniers patiently, to glorify Allah before the rising of the sun and before its setting, and to bid one's family to prayer and be steadfast therein.

**The Divine Symphony of Ease and Expansion**

The supreme spiritual thesis of Sūrah Ṭā-Hā is that divine revelation is not an oppressive yoke, but the ultimate liberator of the human spirit. Religion does not come to produce misery (*mā anzalnā ʿalayka al-Qur'āna li-tashqā*); it comes to unfasten the knots of the tongue, expand the constriction of the chest, and guide humanity out of the suffocating, anxious wilderness of materialism into the spacious tranquility of divine remembrance. The sūrah teaches that no tyrant is too menacing to be confronted with gentle words (*qawlan layyinā*, 20:44), no sin is too deep to be erased by sincere repentance, and no task is too heavy when undertaken under the watchful, loving gaze of the Lord Who declares to His servants: *“Fear not, indeed I am with you both; I hear and I see”* (20:46)."""

for ch in [16, 17, 18, 19, 20]:
    insert_surah_intro(ch, intros[ch])
print("Batch 2 (Part B: 16-20) inserted successfully.")
