import sys
sys.path.append(".")
from scripts.intro_utils import insert_surah_intro

intros = {}

# -------------------------------------------------------------
# SURAH 31: LUQMĀN
# -------------------------------------------------------------
intros[31] = """**The Wisdom of the Sage and the Architecture of Moral Education**

Luqmān is the thirty-first chapter of the Qur'an, comprising 34 verses of mid-to-late Makkan revelation. It belongs to the *Alif-Lām-Mīm* family of sūrahs and takes its title from the legendary African sage Luqmān, whose immortal parental counsel to his son occupies verses 12–19. In classical Islamic tradition, Luqmān is celebrated as the archetype of *Ḥikmah* (Wisdom)—divine insight granted to an unlettered, pious servant who walked in absolute humility, gratitude, and moral rectitude. Revealing a profound educational pedagogy, Sūrah Luqmān addresses the perennial problem of human distraction and frivolity, demonstrating that authentic wisdom consists not in verbose philosophical speculation or sensory amusement, but in recognizing the sovereign majesty of God, honoring parents, establishing prayer, promoting social justice, and walking upon the earth without arrogance.

**The Merchant of Distraction and the Makkan Vacuum**

The historical occasion of Sūrah Luqmān is preserved in accounts by Ibn ʿAbbās and al-Kalbī regarding al-Naḍr ibn al-Ḥārith, a wealthy Qurayshi merchant who traveled to Persia and Iraq, purchasing romantic epics, exotic musical instruments, and singing slave-girls. Returning to Makkah, whenever he saw a person inclining toward the recitation of the Qur'an, he would bring them to his home, offering them music, wine, and tales of ancient Persian kings, mocking: *“Muḥammad tells you tales of ʿĀd and Thamūd, but I tell you tales of Rustam, Isfandiyār, and the Chosroes!”* Verse 6 descended in direct exposure of this strategy: *“And of the people is he who buys idle tales (*lahw al-ḥadīth*) to mislead from the way of Allah without knowledge and takes it in ridicule. For those there will be a humiliating punishment.”* Sūrah Luqmān exposes this commercialized escapism as a pathetic attempt to distract human consciousness from its ultimate destiny.

**The Structural Anatomy of Luqmān's Counsel**

The architecture of Sūrah Luqmān is built around the jewel of Luqmān's wisdom, framed by cosmological proofs and eschatological realities. The opening movement (1–11) establishes the Scripture as a Book of Wisdom (*Kitāb al-Ḥakīm*) and a mercy for the doers of good, condemns those who trade in frivolous amusement, and points to the visible universe created without pillars, stabilized by firm mountains, and watered to bring forth noble pairs of vegetation. The second movement (12–19) presents the core pedagogy of Luqmān to his son:
1. Grounding all consciousness in absolute *Tawḥīd*, warning that polytheism (*shirk*) is the greatest possible cosmic injustice (*iniquitous outrage*, *ẓulmun ʿaẓīm*).
2. Intercalating divine speech commanding gratitude to parents—especially the mother who carried her child in weakness upon weakness (*wahnan ʿalā wahn*) and nursed him for two years—yet maintaining that obedience to parents must never override obedience to the Creator.
3. Teaching cosmic accountability: that if an action were as infinitesimal as a mustard seed buried within a solid rock or hidden in the heavens or earth, God will bring it forth: *“Indeed, Allah is Subtle and Acquainted”* (31:16).
4. Practical moral duties: establishing regular prayer, enjoining the good, forbidding the evil, and enduring with patient fortitude whatever adversity strikes (*inqilāb al-umūr*).
5. Interpersonal etiquette: *“And do not turn your cheek [in contempt] toward people, and do not walk through the earth exultantly. Indeed, Allah does not like everyone self-deluded and boastful. And be moderate in your pace and lower your voice; indeed, the most disagreeable of sounds is the voice of donkeys”* (31:18–19).
The third movement (20–34) returns to cosmic signs: the subjugation of the oceans, the ships gliding by divine grace, the merging of night into day, and the five ultimate mysteries known exclusively to God: the timing of the Hour, the sending of rain, what is hidden in the wombs, what soul will earn tomorrow, and in what land any soul will die (31:34).

**The Anatomy of True Wisdom**

The central spiritual philosophy of Sūrah Luqmān is that true wisdom (*ḥikmah*) is synonymous with *Shukr* (active gratitude to God). The fool is not one who lacks technical knowledge or artistic talent; the fool is one who lives in God's universe, enjoys His provisions, and uses his tongue to boast and his wealth to distract others from the Truth. By embedding the loftiest social etiquette within a father's intimate advice to his child, Sūrah Luqmān proves that a flourishing civilization is built from the nursery outward: on awe of God, filial tenderness, and unpretentious humility in the street."""

# -------------------------------------------------------------
# SURAH 32: AS-SAJDAH
# -------------------------------------------------------------
intros[32] = """**The Ecstasy of Prostration and the Two Dispatches**

As-Sajdah, "The Prostration," is the thirty-second chapter of the Qur'an, comprising 30 verses of mature Makkan revelation. It belongs to the *Alif-Lām-Mīm* sequence and derives its title from verse 15, which delivers a magnificent description of the true believers: *“Only those believe in Our verses who, when they are reminded by them, fall down in prostration (*kharru sujjadā*) and exalt [Allah] with praise of their Lord, and they are not arrogant.”* Liturgically, this verse requires a mandatory prostration of recitation (*sajdat al-tilāwah*). In authentic prophetic tradition, Sūrah as-Sajdah held an indispensable place in the daily devotional rhythm of the Messenger of Allah ﷺ: Jābir ibn ʿAbdillāh reported that the Prophet ﷺ would never go to sleep at night until he had recited Sūrah as-Sajdah and Sūrah al-Mulk (Jāmiʿ al-Tirmidhī 2892), and Abū Hurayrah recorded in Ṣaḥīḥ al-Bukhārī (891) that the Prophet regularly recited Sūrah as-Sajdah in the first cycle and Sūrah al-Insān in the second cycle of the dawn prayer (*Fajr*) every Friday. In thirty concise, intensely concentrated verses, the sūrah captures the complete cycle of existence: cosmic creation, the biological miracle of human origin, the descent of revelation, the secret devotion of the night vigil, and the bifurcation of humanity into the Gardens of Abode and the blazing Fire.

**The Cynicism of the Dust and the Answer of Creation**

The historical context of as-Sajdah reflects the intellectual obstinacy of the Makkan skeptics regarding bodily resurrection. They argued with visceral incredulity: *“When we are lost within the earth, will we indeed be in a new creation?”* (32:10). They could not fathom how decomposed bones, scattered dust, and decayed flesh could ever be reconstituted into a living, conscious, accountable being. Sūrah as-Sajdah meets this skepticism by drawing their attention to the first creation: God perfected everything He created, began the creation of man from clay, made his progeny from an extraction of humble fluid (*sulālah min mā'in mahīn*), fashioned him, breathed into him of His Spirit, and endowed him with hearing, sight, and hearts—yet little is the gratitude humanity returns (32:7–9). The God Who engineered the human soul out of lifeless mud and water requires no greater effort to reconstitute that soul after death.

**The Structural Modulation and the Midnight Vigil**

The movement of Sūrah as-Sajdah is swift, symmetrical, and profoundly focused. The opening movement (1–14) proclaims the Book to be without doubt from the Lord of the worlds, affirms the creation of the heavens and earth in six periods, and introduces the staggering cosmic timescale of verse 5: *“He directs the affair from the heaven to the earth; then it will ascend to Him in a Day whose measure is a thousand years of what you count.”* It describes the Angel of Death (*Malak al-Mawt*) assigned to take each soul at its appointed term, and portrays the terrifying posture of the criminals on the Day of Judgment: bowing their heads before their Lord and crying: *“Our Lord, we have seen and heard, so return us; we will do righteousness; indeed, we are [now] certain”* (32:12), only to be told that the forgotten meeting of their Day has arrived. The second movement (15–22) forms the luminous, emotional centerpiece of the sūrah, contrasting the arrogance of the deniers against the believers: souls who fall in prostration when reminded of God's signs, and whose *“sides forsake their beds, as they supplicate their Lord in fear and aspiration, and from what We have provided them, they spend”* (32:16). It rewards them with the immortal promise of verse 17: *“And no soul knows what has been hidden for them of comfort for eyes (*qurrat aʿyun*) as reward for what they used to do.”* The third movement (23–30) connects this revelation to the scripture granted to Moses, noting that righteous leaders were appointed from among the Israelites when they maintained patient endurance (*ṣabr*) and possessed absolute certainty (*yaqīn*) in divine signs. It concludes with the parable of rain sent to barren land, bringing forth crops from which livestock and humans eat, and answers the mocking taunt: *“When is this victory, if you are truthful?”* with the sovereign command to turn away from them and wait, for they too are waiting.

**The Prostration as the Antidote to Arrogance**

The supreme theological argument of Sūrah as-Sajdah is that arrogance (*kibr*) is the root of all spiritual blindness, while prostration (*sujūd*) is the supreme posture of human truth. The deniers bow their heads in humiliation only when standing before the Fire, when repentance is useless; the believers voluntarily bow their foreheads to the dust in the dark watches of the night while the rest of the world sleeps. In that midnight prostration—where the body forsakes the comfort of the mattress and the heart cries out in hope and awe—the human soul enters into communion with its Creator and qualifies for the unimaginable delights (*qurrat aʿyun*) prepared in the eternal realm."""

# -------------------------------------------------------------
# SURAH 33: AL-AḤZĀB
# -------------------------------------------------------------
intros[33] = """**The Siege of the Trench and the Exalted Paradigm**

Al-Aḥzāb, "The Confederates," is the thirty-third chapter of the Qur'an, comprising 73 verses of late Medinan revelation. It takes its name from verses 9–27, which chronicle the epic geopolitical crisis of the Battle of the Trench (*Khandaq*) or the Battle of the Confederates (*al-Aḥzāb*) in Shawwāl of 5 AH (627 CE), when a massive coalition of ten thousand pagan and tribal warriors besieged the Muslim commonwealth in Madinah. Sūrah al-Aḥzāb is celebrated for containing some of the most foundational constitutional, prophetic, and domestic verses in the sacred canon: the establishment of the Prophet's spiritual fatherhood over the believers (*“The Prophet is closer to the believers than their own selves, and his wives are their mothers,”* 33:6); the immortal declaration of prophetic exemplarity (*“There has certainly been for you in the Messenger of Allah an excellent pattern (*uswah ḥasanah*),”* 33:21); the eternal seal of prophethood (*Khātam al-Nabiyyīn*, 33:40); the cosmic trust (*al-Amānah*, 33:72); and the divine command for all creation to shower blessings upon the Prophet (*“Indeed, Allah and His angels confer blessings upon the Prophet. O you who have believed, ask [Allah to confer] blessings upon him and ask [Allah to grant him] peace,”* 33:56).

**The Ten Thousand Warriors and the Terror of the Trench**

The historical furnace out of which Sūrah al-Aḥzāb emerged was the greatest existential threat faced by early Islam. Incited by the exiled Jewish leadership of Banū al-Naḍīr, the Quraysh united with the fierce desert tribes of Ghaṭafān and others, assembling an unprecedented coalition army of ten thousand men to wipe out the Muslim community. Defending an oasis of only three thousand fighters, the Prophet ﷺ, upon the brilliant advice of Salmān al-Fārisī, ordered the digging of a massive trench across the open northern perimeter of Madinah. As freezing winds, near-starvation, and sleepless exhaustion gripped the defenders, the Jewish tribe of Banū Qurayẓah inside Madinah violated their mutual defense pact, conspiring to open the city's gates to the enemy from behind. Verse 10 captures this psychological terror: *“When they came at you from above you and from below you, and when eyes shifted [in terror], and the hearts reached the throats, and you assumed about Allah [various] assumptions.”* The sūrah depicts how the hypocrites panicked, claiming the Prophet's promises were delusions, while the true believers said: *“This is what Allah and His Messenger promised us... and it only increased them in faith and submission”* (33:22). After a month-long siege, God sent a freezing, howling hurricane that tore down the Confederates' tents, overturned their cooking pots, and drove them into frantic retreat, breaking the siege without military engagement.

**The Structural Unfolding of the Community Charter**

The architecture of Sūrah al-Aḥzāb moves from civil-legal reforms to battlefield psychology, and from the domestic life of the Prophet's household to the cosmic drama of human existence. The opening movement (1–8) dismantles pagan social fictions: declaring that God has not made for any man two hearts inside his breast, abolishing the pagan practice of *ẓihār* (a form of abusive divorce), and outlawing legal adoption that erases biological lineage, commanding that adopted children be called by their real fathers' names to safeguard inheritance and identity. The second movement (9–27) conducts the exhaustive military autopsy of the Trench and the subsequent reckoning of the treasonous Banū Qurayẓah, celebrating the steadfastness of the men *“who were true to what they promised Allah; of them is he who has fulfilled his vow [by martyrdom], and of them is he who awaits, and they have not altered in the least”* (33:23). The third movement (28–59) establishes the sacred etiquette of the Prophet's household and the community: offering the Mothers of the Believers (*Ummahāt al-Mu'minīn*) the choice between worldly luxury or devotion to Allah and His Messenger; affirming their unique spiritual station; purifying the Prophet's household (*Ahl al-Bayt*, 33:33); celebrating the absolute spiritual equality of men and women across ten virtues in verse 35; settling the sensitive marriage of the Prophet to Zaynab bint Jaḥsh to definitively shatter the taboo of marrying the former wife of an adopted son; proclaiming Muḥammad ﷺ as the Seal of the Prophets (*Khātam al-Nabiyyīn*, 33:40); and legislating the outdoor cloak (*jilbāb*, 33:59) to protect believing women from harassment. The climax (60–73) rebukes the hypocrites who spread malicious rumors, reminds humanity of the tragedy of those who followed corrupt leaders in history, and concludes with the breathtaking metaphysical mystery of the Cosmic Trust (*al-Amānah*, 33:72): offered to the heavens, the earth, and the towering mountains, which all recoiled from its terrifying weight in awe, yet borne by humanity, who proved unjust and ignorant, yet capable of ultimate redemption.

**The Exalted Paradigm and the Sacred Trust**

The defining theological insight of Sūrah al-Aḥzāb is that the Prophet Muḥammad ﷺ is the living center of the Muslim community's identity. He is the *Uswah Ḥasanah* (the Excellent Pattern)—the leader who swung the pickaxe in the freezing ditch with hunger-stones strapped to his stomach, the statesman who upheld absolute justice, the husband who treated his wives with boundless compassion, and the prophet upon whom God and His angels send perpetual blessings. Sūrah al-Aḥzāb teaches that when external enemies lay siege and internal hypocrites plot betrayal, victory is secured not by panic, but by gathering around the moral leadership of the Prophet and carrying the sacred Trust of moral responsibility with unyielding fidelity."""

# -------------------------------------------------------------
# SURAH 34: SABAʾ
# -------------------------------------------------------------
intros[34] = """**The Ruins of Sheba and the Illusion of Self-Sufficiency**

Sabaʾ (Sheba) is the thirty-fourth chapter of the Qur'an, comprising 54 verses of mid-to-late Makkan revelation. It opens with the majestic, universal doxology: *“Praise be to Allah, to whom belongs whatever is in the heavens and whatever is in the earth, and to Him belongs praise in the Hereafter; and He is the Wise, the Acquainted”* (34:1). It takes its title from verses 15–21, which recount the historic rise and catastrophic fall of the ancient South Arabian kingdom of Sabaʾ (Sheba, modern Yemen). Endowed with unmatched agricultural wealth through their monumental irrigation dam at Ma'rib, the people of Sabaʾ grew arrogant, took their security and prosperity for granted, and refused gratitude to God, whereupon the dam breached in the catastrophic Flood of the Dams (*Sayl al-ʿArim*), transforming their luxuriant gardens into barren scrubland bearing bitter fruit, tamarisk, and thorny lote-trees. Juxtaposing the humble, grateful power of David and Solomon against the ungrateful, ruined kingdom of Sheba, Sūrah Sabaʾ is an unsparing philosophical audit of civilization, demonstrating that worldly prosperity is an unstable illusion when detached from moral accountability and gratitude.

**The Mockery of the Hour and the Skeptic's Contempt**

The historical context of Sūrah Sabaʾ reflects the disdainful arrogance of the Qurayshi merchant princes. Engrossed in the lucrative north-south spice trade—which retraced the ancient caravan routes of the ruined kingdom of Sheba—the Quraysh dismissed the Prophet's warnings of a Final Judgment with open contempt, declaring: *“The Hour will not come to us!”* (34:3). They scoffed at the Prophet as a madman who fabricated lies about resurrection: *“Shall we direct you to a man who will inform you that when you have been completely disintegrated into dust, indeed, you will be in a new creation?”* (34:7). Sūrah Sabaʾ meets this cynicism by turning their eyes to the desert around them: every journey they took to Syria or Yemen carried them past the crumbling ruins, broken terraces, and abandoned wells of civilizations that were once far wealthier, more numerous, and more militarily powerful than Quraysh, yet vanished into ghost stories when divine judgment struck.

**The Structural Contrast of Grateful and Ungrateful Powers**

The architecture of Sūrah Sabaʾ is designed around a dramatic comparative study of power, gratitude, and economic destruction. The opening movement (1–9) establishes God's absolute omniscience: not an atom's weight in heaven or earth escapes His knowledge, and all deeds are recorded in a clear Book. It rebukes those who strive to invalidate divine signs, warning that if God willed, He could cause the earth to swallow them or drop fragments of the sky upon their heads. The second movement (10–21) constructs the central, stunning historical contrast:
- David and Solomon (10–14): Granted supreme miracles—mountains and birds echoing David's psalms, iron made malleable like wax in his hands to weave interlocking coats of mail, the wind blowing at Solomon's command a month's journey in a morning and evening, a fountain of molten copper gushing forth, and jinn crafting lofty sanctuaries, sculptures, and basins like reservoirs. Yet divine speech commands them: *“Work, O family of David, in gratitude. And few of My servants are grateful”* (34:13). It records Solomon's unpretentious mortality: dying while leaning upon his staff, while the jinn continued laboring in agonizing torment unaware of his death until an earthworm gnawed through his staff, demonstrating that jinn have no knowledge of the unseen.
- The Kingdom of Sabaʾ (15–21): Endowed with two lush gardens on the right and left, commanded to eat from their Lord's provision and be grateful to a good land and a forgiving Lord (*baldatun ṭayyibatun wa-rabbun ghafūr*). They turned away in boredom with ease, praying arrogant prayers to lengthen the distance between their caravan stations, whereupon the flood of the dam (*Sayl al-ʿArim*) destroyed their agriculture, scattering them into dispersed remnants and proverbial tales across the earth (*jaʿalnāhum aḥādīth*).
The third movement (22–42) dismantles the illusion of intercession and idolatry, challenging the polytheists to demonstrate that their partners possess an atom's weight of power or partnership in creation. It stages the dramatic mutual blame game of the Day of Judgment, where the oppressed masses cry out to their aristocratic masters: *“Were it not for you, we would have been believers!”* while the arrogant elites retort: *“Did we avert you from guidance after it came to you? Nay, you were criminals!”* (34:31–32). The closing movement (43–54) strips away the excuse of wealth and children (34:37), and presents the Prophet's profound invitation to single-minded contemplation: *“Say, 'I only advise you of one thing: that you stand for Allah, in pairs and singly, and then reflect; there is not in your companion any madness'”* (34:46). The sūrah concludes with the tragic realization of the deniers at death: attempting to grasp faith from a place far removed, separated forever from what they desire (*wa-ḥīla baynahum wa-bayna mā yashtahūn*).

**The Fragility of Ungrateful Civilization**

The foundational thesis of Sūrah Sabaʾ is that ingratitude (*kufrān al-niʿmah*) is a civilizational suicide note. When a society becomes infatuated with its own technological and economic achievements, treating its wealth as a natural right rather than a divine trust, the moral fabric rots from within. The dam of Ma'rib was breached not merely by water, but by arrogance. By presenting David and Solomon—who ruled with swords of iron and palaces of copper yet worked in tearful gratitude—against the ruined orchards of Sheba, the sūrah teaches that only the society anchored in *Shukr* can endure."""

# -------------------------------------------------------------
# SURAH 35: FĀṬIR
# -------------------------------------------------------------
intros[35] = """**The Originator of the Heavens and the Inheritors of the Book**

Fāṭir, "The Originator"—also titled in classical exegesis as *Sūrat al-Malā'ikah* (The Chapter of the Angels)—is the thirty-fifth chapter of the Qur'an, comprising 45 verses of mid-to-late Makkan revelation. It takes its name from its soaring, magnificent opening doxology: *“All praise is for Allah, Originator of the heavens and the earth (*Fāṭir al-samāwāti wa-l-arḍ*), who made the angels messengers having wings, two or three or four. He increases in creation what He wills. Indeed, Allah is over all things competent”* (35:1). *Fāṭir* signifies the initial, unborrowed Creator who splits open the void to bring forth new existence without prior model or blueprint. Sūrah Fāṭir is an exhilarating metaphysical journey into the absolute, radical dependence of all created things upon God, containing the celebrated theological axiom of verse 15: *“O humanity! It is you who are in absolute need of Allah, while Allah is the Free of need, the Praiseworthy (*Antum al-fuqarā'u ilā Allāh*).”* In an atmosphere of intense Makkan denial, the sūrah strips away the delusions of creaturely autonomy, demonstrating that human beings are radical paupers before the boundless wealth of the Creator.

**The Delusion of Human Self-Sufficiency**

The historical canvas of Fāṭir reflects the entrenched complacency of the Quraysh, who imagined their mercantile wealth, noble lineage, and political control over the Kaʿbah rendered them invincible. They treated the Prophet's warnings as negligible inconveniences, assuming that existence would continue indefinitely without disruption or reckoning. Sūrah Fāṭir shatters this complacency by exposing the fragility of human existence: reminding mankind that they were fashioned from dust, then from a sperm-drop, then made pairs; that no female conceives or gives birth except with His knowledge; and that no aged person is granted long life or has their life shortened except as it is written in a clear register (35:11). If God willed, He could wipe out the entire human species in an instant and replace them with a brand new creation—and that is not difficult for Allah (35:16–17).

**The Structural Modulation and the Threefold Inheritance**

The architecture of Sūrah Fāṭir moves between cosmic theology, biological diversity, the psychology of scholars, and the threefold typology of the believers. The opening movement (1–14) proclaims God as the sole Opener of mercy: whatever mercy God opens for humanity, none can withhold, and whatever He withholds, none can release thereafter (35:2). It warns humanity not to let the worldly life deceive them or the Deceiver (Satan) deceive them concerning God, and contrasts the blind with the seeing, the darkness with the light, and the living with the dead, stating: *“Indeed, Allah causes to hear whom He wills, but you cannot make hear those in the graves”* (35:22). The second movement (15–28) establishes the radical poverty of all creation before the Self-Sufficient God (*al-Ghānī*), and introduces the stunning geological and biological tapestry of verse 27: rain descending from heaven to produce fruits of diverse colors, mountains marked with pathways of white and red of varying hues and intense raven-black, and humans, beasts, and livestock in all their colorful diversity. It derives from this cosmic diversity the famous epistemic principle of verse 28: *“Only those fear Allah, from among His servants, who have knowledge (*innamā yakhshā Allāha min ʿibādihi al-ʿulamā'*).”* The third movement (29–38) celebrates those who recite the Scripture, establish prayer, and spend secretly and openly, hoping for a commerce that will never perish (*tijāratan lan tabūr*). It reveals the celebrated threefold division of the Muslim community in verse 32: *“Then We caused to inherit the Book those We have chosen of Our servants; and among them is he who wrongs himself, and among them is he who is moderate, and among them is he who is foremost in good deeds by permission of Allah. That is what is the great favor!”* Classical commentators, including ʿUmar ibn al-Khaṭṭāb, wept with joy over this verse, noting that all three categories—even the one who wrongs himself—are included among the chosen inheritors destined for the Gardens of Eden, where they will cry: *“Praise be to Allah, who has removed from us all sorrow!”* (35:34). The closing movement (39–45) challenges the polytheists to show what their idols have created of the earth, reminds them of the sovereign stability of the cosmos: *“Indeed, Allah holds the heavens and the earth, lest they cease,”* and concludes with the profound mercy of verse 45: if God were to punish humanity instantly for what they earn, He would not leave a single crawling creature upon the surface of the earth, but He grants them respite until an appointed term.

**The Radical Poverty of Creation and the True Scholar**

The core philosophical insight of Sūrah Fāṭir is the concept of *Faqr*—existential poverty before the Divine. To be a creature is to be a beggar at the door of the Creator; every breath, every heartbeat, every ray of sunlight, and every drop of water is a gift bestowed by *Al-Fāṭir*. True knowledge (*ʿilm*) is not the accumulation of dry facts or legal pedantry; true knowledge is the shivering awe (*khashyah*) that grips the human intellect when it perceives the staggering beauty, diversity, and majesty of the cosmos. The true scholar is one whose study of the rocks, the clouds, the animals, and the scripture leads directly to the prostration of the heart before the unshared sovereignty of God."""

for ch in [31, 32, 33, 34, 35]:
    insert_surah_intro(ch, intros[ch])
print("Batch 4 (Part A: 31-35) inserted successfully.")
