import sys
sys.path.append(".")
from scripts.intro_utils import insert_surah_intro

intros = {}

# -------------------------------------------------------------
# SURAH 42: ASH-SHŪRĀ
# -------------------------------------------------------------
intros[42] = """**The Council of Faith and the Transcendent Unity of Revelation**

Ash-Shūrā, "The Consultation," is the forty-second chapter of the Qur'an, comprising 53 verses of late Makkan revelation. It belongs to the celebrated *Ḥawāmīm* septet and is uniquely distinguished by its opening two verses, which contain a five-letter mystic sequence: *Ḥā-Mīm; ʿAyn-Sīn-Qāf* (42:1–2). It takes its title from verse 38, which designates *Shūrā* (mutual consultation) as an indispensable, permanent mark of the believing community: *“And those who have responded to their Lord and established prayer and whose affair is [determined by] consultation among themselves (*wa-amruhum shūrā baynahum*), and from what We have provided them, they spend.”* Sūrah ash-Shūrā is a monumental theological treatise on the metaphysical mechanics of revelation (*al-Waḥy*) and the absolute transcendence of the Creator, containing the definitive negative-theology axiom of Islam: *“There is nothing like unto Him (*laysa ka-mithlihī shay'*), and He is the Hearing, the Seeing”* (42:11).

**The Sectarian Fracture and the Call to Unity**

The historical context of ash-Shūrā reflects the deep sorrow of the Prophet ﷺ over the religious fracturing of humanity. The Makkans claimed that their ancestral idolatry was an authentic tradition, while the Jewish and Christian factions of Arabia claimed exclusive titles to salvation. Sūrah ash-Shūrā intervenes to declare that the religion of God has always been a single, unified, unbroken covenant: *“He has ordained for you of religion what He enjoined upon Noah and that which We have revealed to you, [O Muḥammad], and what We enjoined upon Abraham and Moses and Jesus: to establish the religion and not be divided therein”* (42:13). The sūrah explains that sectarian division did not arise from a lack of evidence, but from mutual envy and rivalry (*baghyan baynahum*) after knowledge had come to them. The Prophet is therefore commanded not to engage in partisan sectarianism, but to stand firm upon the center, judge with justice, and proclaim: *“Allah is our Lord and your Lord; for us are our deeds, and for you your deeds. There is no [need for] argument between us and you. Allah will bring us together, and to Him is the final destination”* (42:15).

**The Structural Modulation and the Vessels of Revelation**

The architecture of Sūrah ash-Shūrā moves between cosmic transcendence, the social ethics of the believers, and the theology of divine speech. The opening movement (1–22) establishes the majestic chain of inspiration: *“Thus reveals to you, and to those before you, Allah, the Exalted in Might, the Wise”* (42:3), reveals the angels swimming in the heights of heaven glorifying God and seeking forgiveness for those upon the earth, and introduces the celebrated theological definition: *“Creator of the heavens and the earth. He has made for you from yourselves mates, and among the cattle, mates... There is nothing like unto Him, and He is the Hearing, the Seeing”* (42:11). It contrasts the seeker of the eternal harvest against the seeker of the worldly harvest: *“Whoever desires the harvest of the Hereafter—We increase for him in his harvest; and whoever desires the harvest of this world—We give him thereof, but there is not for him in the Hereafter any share”* (42:20). The second movement (23–43) presents the sublime portrait of the believers: those who avoid major sins and indecencies, who forgive when they are angry, who establish prayer, whose affairs are conducted by mutual consultation (*Shūrā*), and who, when tyranny strikes them, defend themselves with proportionate justice while recognizing that whoever pardons and reconciles has their reward directly with Allah (42:37–40). It presents cosmic signs: the towering ships gliding through the ocean like mountains, which God can cause to stand motionless upon the water's surface if He stills the wind. The closing movement (44–53) delivers the definitive Qur'anic discourse on how God communicates with mortal humanity in verse 51: *“And it is not for any human that Allah should speak to him except by revelation (*waḥyan*) or from behind a veil (*min warā'i ḥijāb*) or by sending a messenger [an angel] to reveal by His permission what He wills.”* It concludes with the personal revelation to the Prophet: *“And thus We have revealed to you an inspiration/spirit (*Rūḥan*) of Our command. You did not know what is the Book or what is faith, but We have made it a light by which We guide whom We will of Our servants”* (42:52).

**The Ethic of Consultation and the Transcendence of God**

The supreme philosophical synthesis of Sūrah ash-Shūrā is the pairing of absolute Divine Transcendence (*Tanzīh*) with collective human humility (*Shūrā*). Because God is utterly beyond creaturely likeness (*laysa ka-mithlihī shay'*), no human dictator, monarch, or scholar can claim to be an absolute, infallible embodiment of the Divine will. Human governance must therefore be collegiate, humble, and consultative. By embedding *Shūrā* directly between the establishment of prayer and the payment of charity, the sūrah teaches that mutual consultation is not a secondary political luxury; it is a sacred religious duty that protects communities from the catastrophic arrogance of tyranny."""

# -------------------------------------------------------------
# SURAH 43: AZ-ZUKHRUF
# -------------------------------------------------------------
intros[43] = """**The Ornaments of Gold and the Crucible of Worldly Vanity**

Az-Zukhruf, "The Ornaments of Gold," is the forty-third chapter of the Qur'an, comprising 89 verses of mature Makkan revelation. It is the fourth chapter of the *Ḥā-Mīm* sequence, taking its name from verse 35, where God declares that silver roofs, stairways, couches, doors, and *zukhruf* (ornaments of gold and glittering luxury) are nothing more than the ephemeral, perishable trinkets of the worldly life (*matāʿ al-ḥayāt al-dunyā*), while the eternal honor of the Hereafter with your Lord is reserved exclusively for the righteous. Characterized by sharp, penetrating irony and profound socio-economic diagnosis, Sūrah az-Zukhruf attacks the superficial materialism of human cultures that judge spiritual authority by the possession of gold, jewelry, and social rank. It deconstructs the pagan obsession with prestige, exposes the irrationality of ancestral blind-following, and presents Abraham and Jesus as pure prophetic paradigms who renounced the idolatrous glitter of their societies to proclaim the uncompromised worship of God alone.

**The Elitist Objection and the Gold Bracelets**

The historical climate of az-Zukhruf reflects the snobbish class prejudice of the Qurayshi aristocracy. The chieftains of Makkah could not comprehend why God would bestow prophetic revelation upon an orphaned, modestly circumstanced man like Muḥammad ﷺ, rather than upon the multi-millionaire oligarchs of the two commercial metropolises of Arabia. Verse 31 preserves their petulant objection: *“And they said: 'Why was this Qur'an not sent down to a great man of the two cities [Makkah and al-Ṭā'if]?'”* Furthermore, they echoed the ancient imperial prejudice of Pharaoh, who had mocked Moses' rough clothing and stammering tongue, sneering: *“Why have bracelets of gold not been cast down upon him, or angels accompanied him in procession?”* (43:53). Sūrah az-Zukhruf responds with devastating divine sarcasm: *“Do they distribute the mercy of your Lord? It is We who have apportioned between them their livelihood in the life of this world and raised some of them above others in degrees, so that they may employ one another in service; but the mercy of your Lord is better than what they amass”* (43:32).

**The Structural Anatomy of the Sūrah**

The movement of Sūrah az-Zukhruf unfolds in five distinct thematic movements. The opening movement (1–14) exalts the Qur'an as a clear Arabic scripture originating from the *Umm al-Kitāb* (the Mother of the Book) in the Divine Presence, reminders of how past nations were destroyed for mocking messengers, and presents the foundational prayer of travel when mounting beasts or vehicles: *“Exalted is He who has subjected this to us, and we could not have [otherwise] subdued it. And indeed, to our Lord we will return”* (43:13–14). The second movement (15–25) exposes the grotesque hypocrisy of the pagan Arabs who attributed daughters to God—claiming angels were female deities—while if one of them was given news of the birth of a female child, his face darkened with suppressed rage (43:17). It exposes the intellectual bankruptcy of their universal excuse: *“Indeed, we found our forefathers upon a path, and we are guided in their footsteps”* (43:22). The third movement (26–56) reviews sacred prophetic history: Abraham renouncing the idols of his father, making monotheism an enduring word among his posterity (*kalimatan bāqiyatan fī ʿaqibih*); the divine warning that whoever turns away from the remembrance of the Most Compassionate has a devil assigned to him as an inseparable, intimate companion (*qarīn*); and Moses confronting Pharaoh, whose contempt for Moses and reliance on his irrigation canals ended in Pharaoh and his hosts being drowned into a precedent and an example for future generations. The fourth movement (57–67) addresses the controversy surrounding Jesus: clarifying that ʿĪsā was not a divine being to be worshipped beside God, but a noble servant favored with signs (*in huwa illā ʿabdun anʿamnā ʿalayh*), warning of the Hour, and stating the immortal law of human relationships in verse 67: *“Close friends, that Day, will be enemies to each other, except for the righteous.”* The closing movement (68–89) contrasts the joy of the believers in Paradise, served with golden trays and cups containing whatever the soul desires and the eyes delight in (*wa-fīhā mā tashtahīhi al-anfusu wa-taladhdhu al-aʿyun*), against the damned criminals in Hell pleading with the angelic warden, Mālik, to let their Lord terminate their existence, only to be answered: *“Indeed, you are to remain!”* (43:77). It concludes with the Prophet's pained sigh: *“O my Lord, indeed these are a people who do not believe!”* and the divine parting instruction: *“So turn aside from them and say: 'Peace!' For they will soon know.”*

**The Illusions of Zukhruf and the Gold of the Soul**

The supreme philosophical argument of Sūrah az-Zukhruf is that human civilization perpetually confuses the container with the content, and the glitter of gold (*zukhruf*) with the reality of virtue. Had God not feared that all humanity would collapse into a single monolithic culture of disbelief, He would have made the roofs, doors, stairs, and beds of the wicked out of pure silver and gold (43:33–35)—because in the sight of God, all the gold in the universe has less value than the wing of a mosquito. Sūrah az-Zukhruf summons the human intellect to look past the gilded decorations of worldly power, reject the mindless imitation of ancestral customs, and seek the true, incorruptible treasure: the remembrance of the Most Compassionate."""

# -------------------------------------------------------------
# SURAH 45: AL-JĀTHIYAH
# -------------------------------------------------------------
intros[45] = """**The Kneeling Nations and the Mirage of Materialist Time**

Al-Jāthiyah, "The Kneeling," is the forty-fifth chapter of the Qur'an, comprising 37 verses of late Makkan revelation. It is the sixth chapter in the *Ḥā-Mīm* sequence and derives its title from the terrifying, cosmic courtroom spectacle described in verse 28: *“And you will see every nation kneeling (*kulla ummatin jāthiyah*); every nation will be called to its record. [It will be said], 'Today you will be recompensed for what you used to do.'”* *Jāthiyah* describes a posture of absolute vulnerability, awe, and dread—falling upon one's knees in the dust before the supreme, majestic bench of the Divine Judge, stripped of all earthly swagger, titles, and legal evasions. Sūrah al-Jāthiyah is the great scriptural confrontation with ancient and modern philosophical materialism (*al-Dahriyyah*), refuting those who claim that the material universe is a self-originating biological machine and that death is simply the extinguishing of life by blind, unguided physical time (*al-Dahr*).

**The Dogma of the Naturalists: Nothing but Life and Time**

The historical and philosophical context of al-Jāthiyah centers upon the worldview of the pre-Islamic Arab naturalists (*al-Dahriyyūn*), whose philosophy is captured with chilling modern accuracy in verse 24: *“And they say: 'There is not but our worldly life; we die and we live, and nothing destroys us except time (*wa-mā yuhlikunā illā al-dahr*).' And they have of that no knowledge; they are only assuming.”* This worldview denied the existence of a Creator, rejected divine revelation, mocked the concept of moral accountability, and treated human existence as an accidental flash between non-existence and non-existence, concluding that might makes right and that physical survival is the only law. Sūrah al-Jāthiyah dismantles this dogmatic materialism by demonstrating that it is not rooted in empirical science or rational knowledge, but in pure conjecture (*in hum illā yaẓunnūn*) and an unexamined lust for moral unaccountability.

**The Structural Architecture and the Record of Deeds**

The architecture of Sūrah al-Jāthiyah is organized around four clear movements. The opening movement (1–15) proclaims the descent of the Scripture from Allah, the Exalted in Might, the Wise, and directs the human observer to an unbroken landscape of empirical signs: in the heavens and earth, in the creation of human biology, in the diverse animal species scattered across the globe, in the alternation of night and day, in the rain reviving the dead soil, and in the shifting of the winds (45:3–5). It issues a severe indictment of the arrogant skeptic: *“Woe to every sinful liar who hears the verses of Allah recited to him, then persists arrogantly as if he had not heard them! So give him tidings of a painful punishment”* (45:7–8). The second movement (16–22) reviews the history of the Children of Israel: granted the Scripture, wisdom, and prophethood, favored above the nations of their era, yet falling into bitter schism solely out of sectarian jealousy after knowledge had come to them. It commands the Prophet Muḥammad ﷺ to follow a clear spiritual path (*sharīʿah*) and never yield to the desires of the ignorant, affirming that the wrongdoers are allies of one another, while Allah is the protector of the righteous. The third movement (23–26) introduces the profound psychological diagnosis of idolatry in verse 23: *“Have you seen he who has taken as his god his own desire (*hawāh*), and Allah has sent him astray due to knowledge and has set a seal upon his hearing and his heart and put over his vision a veil? So who will guide him after Allah?”* It refutes the materialist dogma of *al-Dahr*, affirming that God gives life, causes death, and gathers all humanity to the Day of Resurrection, about which there is no doubt. The climactic movement (27–37) stages the kneeling of all nations before the open registers of their deeds: *“This Our record speaks about you in truth. Indeed, We were having transcribed whatever you used to do”* (45:29). The deniers are told that their arrogant mockery in worldly life has left them forgotten in the Fire just as they forgot the meeting of their Day. The chapter closes with the majestic, universal doxology of verses 36–37: *“Then to Allah belongs all praise—Lord of the heavens and Lord of the earth, Lord of the worlds. And to Him belongs [all] majesty in the heavens and the earth, and He is the Exalted in Might, the Wise.”*

**The Deification of Desire and the Great Kneeling**

The foundational philosophical insight of Sūrah al-Jāthiyah is that atheism and materialism are rarely purely intellectual conclusions; they are almost always the philosophical rationalization of the ego seeking to deify its own desires (*ittakhadha ilāhahu hawāh*). When a man makes his personal lust, ego, or pride his supreme deity, his hearing, sight, and heart become sealed against the most glaring cosmic evidence. Sūrah al-Jāthiyah reminds humanity that the arrogant posture of denial is a temporary illusion: every human empire, every philosophical academy, and every proud denier who refused to bow their forehead in voluntary prayer will inevitably fall to their knees (*jāthiyah*) in the terrifying dawn of the Final Judgment, when all majesty (*al-Kibriyāʾ*) is acknowledged as the sole property of the Lord of the worlds."""

# -------------------------------------------------------------
# SURAH 46: AL-AḤQĀF
# -------------------------------------------------------------
intros[46] = """**The Wind-Swept Dunes and the Assembly of the Jinn**

Al-Aḥqāf, "The Sand Dunes," is the forty-sixth chapter of the Qur'an, comprising 35 verses of late Makkan revelation. It is the seventh and final sūrah of the magnificent *Ḥā-Mīm* sequence, bringing this majestic theological cluster to its climactic close. It takes its name from verse 21, which commemorates the prophet Hūd warning his people in *al-Aḥqāf*—the windswept, curved sand dunes of southern Arabia (in the Rubʿ al-Khālī and Ḥaḍramawt regions)—where the ancient, towering civilization of ʿĀd was annihilated by a catastrophic, eight-day hurricane after mocking their prophet's warnings. Sūrah al-Aḥqāf is celebrated for two historic milestones in the prophetic biography: the profound, tender legislation regarding filial piety and the mother's thirty months of pregnancy and weaning (verses 15–16), and the historic encounter in verses 29–32, where a delegation of the Jinn gathered in the wilderness of Nakhlah to listen to the Prophet's recitation, returning to their people as passionate heralds of monotheism.

**The Rejection at al-Ṭā'if and the Comfort of the Unseen**

The historical setting of al-Aḥqāf occupies the darkest, most agonizing chapter of the Prophet's life: the journey to al-Ṭā'if in the tenth year of prophethood (approx. 619 CE). Having lost both Khadījah and Abū Ṭālib, the Prophet ﷺ walked forty miles through rugged mountains to seek protection and alliance from the leaders of the Thaqīf tribe in al-Ṭā'if. The chieftains insulted him, rejected his message, and incited their street gangs, slaves, and youths to line the mountain pass, stoning the Messenger of Allah until his shoes were filled with his own blood. Bleeding, exhausted, and heartbroken, the Prophet took refuge in an orchard, offering his famous, tearful supplication: *“O Allah, to You I complain of my weakness, my lack of resources, and my lowliness before mankind...”* On his return journey, while praying the night prayer at the valley of Nakhlah, God dispatched a party of the Jinn to listen to his recitation. Sūrah al-Aḥqāf descended to provide celestial consolation: human beings in Makkah and al-Ṭā'if had hardened their hearts, but the invisible creatures of the spirit realm (*al-Jinn*) heard the word, trembled in awe, recognized its harmony with the scripture of Moses, and surrendered to God.

**The Structural Anatomy of the Chapter**

The architecture of Sūrah al-Aḥqāf unfolds in four tightly woven movements. The opening movement (1–14) affirms the creation of the heavens and earth in truth and for a specified term, challenges the polytheists to produce a single prior scripture or shred of ancient knowledge (*athāratin min ʿilm*) validating their idolatry, and delivers the Prophet's personal disclaimer: *“Say, 'I am not an innovation among the messengers, nor do I know what will be done with me or with you. I only follow that which is revealed to me, and I am not but a clear warner'”* (46:9). It presents the testimony of an honest scriptural witness from the Children of Israel who recognized the truth and believed, while the Quraysh arrogantly scoffed: *“If it were good, they would not have preceded us to it!”* (46:11). The second movement (15–20) contrasts two archetypal children: the righteous child who honors his mother who bore him with hardship and brought him forth with hardship, reaching forty years of age and praying the immortal prayer: *“My Lord, enable me to be grateful for Your favor which You have bestowed upon me and upon my parents and to do righteousness of which You approve, and make righteous for me my offspring”* (46:15); contrasted against the insolent, ungrateful child who sneers at his parents' warnings of resurrection: *“Uff to you both! Do you promise me that I will be brought forth when generations before me have passed on?”* (46:17). The third movement (21–28) recounts the catastrophic tragedy of ʿĀd in the sand dunes (*al-Aḥqāf*): seeing a dense black cloud advancing across the desert sky, they rejoiced, imagining it was a rain-cloud to water their valleys, only to be told: *“Nay, it is that which you were asking to be hastened—a wind wherein is a painful punishment!”* By dawn, nothing was visible except their empty, abandoned stone ruins. The closing movement (29–35) narrates the dramatic arrival of the Jinn: listening in profound silence to the Qur'an, testifying that it confirms the Torah of Moses, and warning their brethren to respond to the caller of God (*Dāʿī Allāh*), concluding with the supreme command of endurance to the Prophet in verse 35: *“So be patient, [O Muḥammad], as were the Messengers of Firm Resolve (*Ūlū al-ʿAzm*), and do not be in haste for them.”*

**The Resolve of the Messengers and the Lesson of the Dunes**

The ultimate spiritual lesson of Sūrah al-Aḥqāf is summarized in its final imperative: *Fa-ṣbir kamā ṣabara Ūlū al-ʿAzmi min al-rusul* ("So be patient as were the Messengers of Firm Resolve"). The Messenger of God had been stoned at al-Ṭā'if, rejected by his kin, and threatened with murder, yet he is commanded to maintain the monumental patience of Noah, Abraham, Moses, and Jesus. The sūrah teaches that human rejection does not mean divine abandonment; when human doors slam shut, the unseen realms of creation open in reverence. Empires as colossal as ʿĀd become silent dunes buried under the sand, but the word of patience endured for the sake of God remains eternal."""

# -------------------------------------------------------------
# SURAH 47: MUḤAMMAD
# -------------------------------------------------------------
intros[47] = """**The Standard of the Messenger and the Annihilation of Falsehood**

Muḥammad is the forty-seventh chapter of the Qur'an, comprising 38 verses of early Medinan revelation. It is one of only three chapters in the entire sacred text titled with the personal name of a prophet, and it is universally unique as bearing the personal name of the Final Messenger of Allah, Muḥammad ﷺ (*“And those who believe and do righteous deeds and believe in what has been sent down upon Muḥammad—and it is the truth from their Lord—He will remove from them their misdeeds and amend their condition,”* 47:2). In classical exegesis, it is also widely designated as *Sūrat al-Qitāl* (The Chapter of Fighting), because it was revealed immediately following the *Hijrah* to Madinah (approx. 1 or 2 AH) to articulate the decisive rules of military engagement, the treatment of prisoners of war, and the moral fortitude required to defend the new commonwealth against pagan aggression. Characterized by explosive, razor-sharp contrasts between the radiant clarity of faith and the spiritual bankruptcy of denial, Sūrah Muḥammad is an uncompromising ideological manifesto: declaring that all the deeds, wealth, and strategic maneuvers of the disbelievers are destined to be completely neutralized and brought to absolute futility (*aḍalla aʿmālahum*).

**The Threshold of Statehood and the Inevitability of Conflict**

The historical canvas of Sūrah Muḥammad is the tense, dangerous interlude between the arrival of the Muslim refugees in Madinah and the outbreak of the Battle of Badr. For over a decade in Makkah, the believers had been subjected to physical torture, confiscation of wealth, and relentless boycott without being permitted to retaliate. Upon reaching Madinah, the community was no longer an underground devotional circle; it was a sovereign sanctuary facing imminent, total military assault from the Quraysh, while surrounded by treacherous factions of hypocrites (*al-munāfiqūn*) within the oasis who sought every opportunity to sabotage the state. Sūrah Muḥammad descended to steel the resolve of the believers. It stripped away all pacifist illusions: when oppressors wage war to extinguish the freedom of faith, the believers must not falter or cry out for humiliating peace while they have the upper hand (*“So do not weaken and call for peace while you are superior; and Allah is with you,”* 47:35).

**The Structural Anatomy of the Discourse**

The architecture of Sūrah Muḥammad moves between military jurisprudence, psychological radiography, and eschatological realities. The opening movement (1–3) establishes the grand ontological divide: those who disbelieve and obstruct the path of God have their deeds rendered completely void, while those who believe in what was revealed to Muḥammad have their sins expiated and their inner state rectified (*aṣlaḥa bālahum*), because the deniers follow falsehood while the believers follow the truth from their Lord. The second movement (4–19) codifies the laws of active warfare: when meeting the combatant enemy in battle, strike with decisive firmness until the threat is broken, then secure the bonds of captives, after which they may be released either by gracious generosity (*mannan*) or by ransom (*fidā'an*), until the war lays down its burdens (47:4). It honors the fallen martyrs, promising that God will never let their deeds be lost, but will guide them, amend their state, and admit them into the Paradise He has already made known to them. It delivers the celebrated covenantal formula of victory in verse 7: *“O you who have believed, if you support Allah, He will support you and plant firmly your feet.”* It contrasts the rivers of Paradise—pure water that never stagnates, milk whose taste never changes, wine delicious to the drinkers, and purified honey—against the inmates of Hell forced to drink scalding water that tears their bowels to pieces. The third movement (20–34) conducts an unsparing psychological autopsy of the hypocrites: when an ordinary peaceful sūrah is revealed, they appear compliant, but the moment a decisive chapter mandating military defense descends, *“you see those in whose hearts is disease looking at you with a look of one overcome by death!”* (47:20). It exposes their secret conspiracies with the enemies of Islam, warning them that their treachery is known and that the angels of death will strike their faces and their backs at the moment of expiration. The closing movement (35–38) summons the community to financial mobilization, reminding them that worldly life is but play and diversion, and warning them that stinginess harms only the miser's own soul: *“And Allah is the Free of need, while you are the needy. And if you turn away, He will replace you with another people; then they will not be the likes of you!”* (47:38).

**The Rectification of the Soul: Aṣlaḥa Bālahum**

The profound spiritual thesis of Sūrah Muḥammad is encapsulated in the exquisite divine phrase *Aṣlaḥa Bālahum* (verses 2 and 5)—the total rectification, peace, and soundness of the inner mind and heart. Worldly success, military strength, and financial abundance are meaningless if the inner soul (*al-bāl*) is diseased by hypocrisy, cowardice, and guilt. By aligning one's loyalty unreservedly with the Messenger of Allah ﷺ and standing firm in defense of justice, the believer experiences a sublime psychological integration: sins are expiated, fear is transformed into courage, and the heart is crowned with tranquil certainty."""

# -------------------------------------------------------------
# SURAH 48: AL-FATḤ
# -------------------------------------------------------------
intros[48] = """**The Manifest Triumph and the Sanctuary of Tranquility**

Al-Fatḥ, "The Triumph" or "The Victory," is the forty-eighth chapter of the Qur'an, comprising 29 verses of late Medinan revelation. It takes its name from its electrifying opening proclamation: *“Indeed, We have granted you a clear triumph (*fatḥan mubīnā*)”* (48:1). In prophetic tradition, Sūrah al-Fatḥ holds an exalted, emotionally overwhelming station: ʿUmar ibn al-Khaṭṭāb reported in Ṣaḥīḥ al-Bukhārī (4833) that while riding with the Prophet ﷺ on the return journey from Ḥudaybiyah, the Messenger of Allah turned to him and declared: *“Tonight, a chapter has been revealed to me that is dearer to me than the entire world and everything within it!”*—and then recited the opening of Sūrah al-Fatḥ. Uniquely, the "clear triumph" celebrated in this chapter was not a military slaughter or the physical conquest of a citadel; it was the historic Treaty of Ḥudaybiyah in 6 AH—a peace pact that appeared to human eyes as a bitter diplomatic compromise, yet was recognized by Divine Wisdom as the greatest strategic and spiritual victory in early Islamic history.

**The Truce of Ḥudaybiyah and the Crisis of the Companions**

In Dhū al-Qaʿdah of 6 AH (628 CE), the Prophet ﷺ set out from Madinah with 1,400 unarmed Companions, dressed in the simple white garments of pilgrimage and driving seventy garlanded sacrificial camels, intending to perform the minor pilgrimage (*ʿUmrah*) at the sacred Kaʿbah. Halted by the Quraysh at the desert wells of Ḥudaybiyah on the outer limits of Makkah, the Prophet dispatched ʿUthmān ibn ʿAffān to negotiate peaceful entry. When a false rumor arrived that ʿUthmān had been murdered, the Prophet summoned his followers under an acacia tree, taking from each man the historic *Pledge of the Tree* (*Bayʿat al-Riḍwān*): pledging to fight beside him to the death. Shortly thereafter, ʿUthmān returned safely, accompanied by the Qurayshi diplomat Suhayl ibn ʿAmr. An austere peace agreement was signed: hostilities were suspended for ten years, but the Muslims were forced to return to Madinah without performing pilgrimage that year, returning only the following year for three days; and any Qurayshi who fled to Madinah without his guardian's permission had to be returned, while any Muslim who apostatized and fled to Makkah would not be extradited. Many Companions—including ʿUmar—were devastated by these terms, perceiving them as humiliating concessions. Sūrah al-Fatḥ descended upon their march home to correct their vision: Ḥudaybiyah was the *Clear Triumph* because peace dismantled the walls of prejudice. During the two years of truce, more people embraced Islam through peaceful dialogue, commerce, and reflection than in the entire prior history of the mission.

**The Structural Modulation and the Garden of the Companions**

The architecture of Sūrah al-Fatḥ moves from divine forgiveness to psychological tranquility, and from battlefield covenants to the glorious biblical portrait of the Companions. The opening movement (1–10) announces total divine forgiveness for the Prophet's past and future liabilities, the completion of divine favor, and the sending down of *al-Sakīnah* (Divine Tranquility) into the hearts of the believers to increase them in faith upon faith. It affirms that the angelic and cosmic hosts of the heavens and earth belong exclusively to Allah, condemns the hypocrites and polytheists who harbored evil suspicions of God, and defines the cosmic weight of the Pledge of the Tree in verse 10: *“Indeed, those who pledge allegiance to you, [O Muḥammad]—they are actually pledging allegiance to Allah. The Hand of Allah is over their hands.”* The second movement (11–17) exposes the cowardice of the bedouin tribes who stayed behind from the expedition, concocting transparent excuses about their wealth and families, and clarifies the legitimate exemptions for the blind, the lame, and the ill. The third movement (18–26) records God's eternal pleasure with the 1,400 believers who took the oath: *“Certainly was Allah pleased with the believers when they pledged allegiance to you under the tree, and He knew what was in their hearts, so He sent down tranquility upon them and rewarded them with an imminent conquest”* (48:18). It reveals why God restrained the Muslims' hands from fighting inside Makkah: to protect vulnerable, hidden believing men and women living unknown among the pagans, whom the Muslim army might have trampled unknowingly. It contrasts the blind tribal bigotry (*ḥamiyyat al-jāhiliyyah*) of the pagans against the serenity bestowed upon the Messenger and the faithful. The climactic movement (27–29) validates the Prophet's original vision of entering the Sacred Mosque with shaved heads and shortened hair in total security, declaring that Islam has been sent with guidance and the religion of truth to prevail over all religion. The chapter concludes with the magnificent, immortal portrait of the Companions in verse 29: *“Muḥammad is the Messenger of Allah; and those with him are forceful against the disbelievers, merciful among themselves. You see them bowing and prostrating, seeking bounty from Allah and [His] pleasure. Their mark is on their faces from the trace of prostration.”* It cites their description in the Torah and their parable in the Gospel: like a seed that puts forth its sprout, strengthens it, thickens, and stands firm upon its stem, delighting the sowers, sealed with the divine promise of forgiveness and an immense reward for those who believe and do good.

**The True Nature of Divine Triumph**

The foundational philosophical insight of Sūrah al-Fatḥ is that divine victory (*fatḥ*) is not measured by the annihilation of opponents, but by the conquest of human hearts through truth and peace. By accepting temporary diplomatic concessions to avoid bloodshed, the Prophet ﷺ opened the floodgates of spiritual persuasion. Sūrah al-Fatḥ teaches that true victory requires *Sakīnah*—that serene, transcendent tranquility of the heart that refuses to be provoked by the hysteria of tribal pride, trusting with absolute certainty that when peace is established, the truth of God will naturally illuminate the world."""

# -------------------------------------------------------------
# SURAH 49: AL-ḤUJURĀT
# -------------------------------------------------------------
intros[49] = """**The Inner Chambers and the Universal Charter of Human Brotherhood**

Al-Ḥujurāt, "The Private Chambers," is the forty-ninth chapter of the Qur'an, comprising 18 verses of late Medinan revelation. In classical Islamic scholarship, it is revered as *Sūrat al-Akhlāq* (The Chapter of Moral Etiquette) or the *Constitutional Charter of Social Ethics*. It takes its title from verse 4, which reprimands the crude desert bedouins who arrived in Madinah and began shouting loudly for the Prophet from outside *al-ḥujurāt* (the modest private living chambers of the Prophet's wives): *“Indeed, those who call out to you from behind the private chambers—most of them do not use reason.”* In eighteen masterly, intensely concentrated verses, Sūrah al-Ḥujurāt establishes the complete micro- and macro-sociology of the Islamic community: moving progressively from the sacred etiquette due to the Messenger of Allah, to the verification of media and news reports, the ethical rules of conflict resolution, the prohibition of social sins (mockery, sarcasm, spying, and backbiting), and culminating in the immortal declaration of universal human equality in verse 13: *“O humanity! Indeed We have created you from male and female and made you peoples and tribes that you may know one another. Indeed, the most noble of you in the sight of Allah is the most righteous of you.”*

**The Deputations of the Desert and the Maturation of Society**

Revealed in the ninth year of the Hijrah (9 AH)—celebrated in prophetic biography as the *Year of Delegations* (*ʿĀm al-Wufūd*)—al-Ḥujurāt reflects an era when tribes from every corner of the Arabian peninsula were streaming into Madinah to declare their allegiance to Islam. Many of these nomadic bedouins (such as the Banū Tamīm) were rugged, uncultured desert-dwellers accustomed to rough tribal egalitarianism, possessing no conception of the sublime reverence and refined etiquette due to the Messenger of God. They barged into the Prophet's courtyard during his rest hours, raised their voices boisterously above his, and treated the leader of the new commonwealth like a local tribal chieftain. Simultaneously, dangerous rumors were threatening to provoke communal violence: a tax-collector sent to the Banū al-Muṣṭaliq returned with a panic-stricken, unverified report that the tribe had apostatized and was massing an army to kill him. Sūrah al-Ḥujurāt intervened to prevent civil catastrophe, transforming a loose confederation of desert tribes into a refined, ethical, and spiritually disciplined global brotherhood.

**The Structural Fabric of Social Sanctity**

The architecture of Sūrah al-Ḥujurāt is structured as an ascending staircase of ethical maturation across five distinct movements:
1. Etiquette with Prophetic Leadership (1–5): Mandating that believers never place their own opinions ahead of Allah and His Messenger (*lā tuqaddimū bayna yaday Allāhi wa-rasūlih*), forbidding them from raising their voices above the voice of the Prophet, and warning that disrespect toward divine authority can nullify a lifetime of good deeds without one even perceiving it.
2. Epistemology and Media Verification (6–8): Delivering the foundational rule of journalism and civil intelligence: *“O you who have believed, if there comes to you a disobedient person with information, verify it, lest you harm a people out of ignorance and become, over what you have done, regretful”* (49:6).
3. Peace-Making and Civic Reconciliation (9–10): Establishing mandatory judicial arbitration: if two factions of believers fall into fighting, the community must intervene to make peace between them with justice and equity; if one faction aggresses against the other, the community must stand together against the oppressor until it complies with the command of God, proclaiming: *“The believers are but brothers, so make settlement between your brothers”* (49:10).
4. Social Sins and the Preservation of Human Dignity (11–12): Systematically criminalizing the subtle psychological poisons that destroy communal solidarity: forbidding men and women from ridiculing or mocking one another, outlawing defamatory insults and offensive nicknames, commanding the avoidance of negative assumptions (*ẓann*), criminalizing espionage and surveillance into the private lives of others (*wa-lā tajassasū*), and delivering the terrifying, visceral condemnation of backbiting (*ghībah*): *“And do not backbite one another. Would one of you like to eat the flesh of his brother when dead? You would detest it!”* (49:12).
5. Universal Human Brotherhood and True Faith (13–18): Dismantling all racial, ethnic, national, and tribal chauvinism, declaring that human diversity exists for mutual recognition (*li-taʿārafū*), not conflict, and that character (*Taqwā*) is the sole measure of human worth. The chapter closes by distinguishing between superficial verbal surrender (*Islām*) and deep, internalized faith (*Īmān*) that transforms the heart and proves itself through selfless striving in the path of God.

**The Sanctity of the Human Soul and Community**

The core philosophical genius of Sūrah al-Ḥujurāt is that the spiritual health of a society is measured by how it protects the dignity, privacy, and reputation of its individual members. A society that tolerates unverified rumors, engages in surveillance, normalizes sarcastic mockery, and permits the cannibalism of backbiting will rot into paranoia and civil war, regardless of how many mosques it builds. By conjoining reverent etiquette toward the Prophet with strict ethical safeguards for the ordinary neighbor, Sūrah al-Ḥujurāt establishes the sacred blueprint of a civilized human community."""

# -------------------------------------------------------------
# SURAH 50: QĀF
# -------------------------------------------------------------
intros[50] = """**The Majestic Scroll and the Throbbing Jugular Vein**

Qāf is the fiftieth chapter of the Qur'an, comprising 45 verses of early-to-mid Makkan revelation. It opens with the single, resonant, reverberating letter *Qāf*, sworn by the *al-Qur'ān al-Majīd* (The Glorious Qur'an). In prophetic tradition, Sūrah Qāf held an exceptionally prominent station in the public liturgical life of the Messenger of Allah ﷺ: Umm Hishām bint Ḥārithah reported in Ṣaḥīḥ Muslim (873) that *“I did not memorize Sūrah Qāf except from the mouth of the Messenger of Allah ﷺ, who would recite it every single Friday upon the pulpit when delivering the address to the people.”* Furthermore, the Prophet regularly recited Sūrah Qāf in the dawn prayer (*Fajr*) and during the great annual assemblies of the two ʿĪd prayers. Characterized by stunning cosmic imagery, deep psychological intimacy, and terrifying eschatological power, Sūrah Qāf is an unsparing awakening of human consciousness: tearing away the numbness of daily routine, charting the recording of every whispered word, and presenting the staggering proximity of the Creator, who is *“closer to him than his jugular vein”* (50:16).

**The Incredulity of the Dust and the Celestial Garden**

The historical climate of Sūrah Qāf is the universal human astonishment at the claim of physical resurrection. The Qurayshi elders scoffed: *“When we have died and become dust, [will we return]? That is a distant return!”* (50:3). Sūrah Qāf meets this skepticism by presenting the precision of divine memory: *“We already know what the earth consumes of them, and with Us is a book that preserves”* (50:4). It turns their eyes toward the heavens above them: how God built it without a single crack or fault, spread the earth, threw down firm mountains, and caused to grow every type of delightful plant as an eye-opener and a reminder for every servant who turns to God. The rain falling from the sky to revive dead, parched land is the observable, annual proof of the Resurrection: *“And We brought to life thereby a dead land; thus will be the emergence [from the graves]”* (50:11).

**The Structural Symphony from Creation to the Day of Threat**

The architecture of Sūrah Qāf unfolds across four breathtaking movements. The opening movement (1–15) establishes the majesty of the Qur'an, points to the unblemished celestial vault, the towering date-palms with clustered fruit, and reviews the ancient deniers who were destroyed by divine decree: the people of Noah, the dwellers of al-Rass, Thamūd, ʿĀd, Pharaoh, the brethren of Lot, and the Forest Dwellers. It concludes with the rhetorical triumph of verse 15: *“Were We then exhausted by the first creation? But they are in doubt about a new creation!”* The second movement (16–29) moves into the profound interior landscape of human consciousness: *“And We have certainly created man and We know what his soul whispers to him, and We are closer to him than his jugular vein (*ḥabl al-warīd*).”* It reveals the two recording angels seated on the right and left, writing down every single uttered word (*“Not a word does he utter except that with him is an observer prepared,”* 50:18). It stages the agonizing stupor of death arriving with truth (*sakratu al-mawti bi-l-ḥaqq*), the blowing of the Horn on the *Day of the Threat* (*Yawm al-Waʿīd*), and every soul arriving accompanied by a driver and a witness. The veil is ripped away: *“You were certainly heedless of this, and We have removed from you your veil, and your sight, this Day, is sharp!”* (50:22). It dramatizes the condemnation of the stubborn tyrant cast into Hell, and the terrifying dialogue with the abyss in verse 30: *“On the Day We will say to Hell, 'Are you full?' and it will say, 'Are there any more?'”* The third movement (31–35) contrasts this terror against the gentle reception of Paradise brought near to the righteous, who feared the Most Compassionate in the unseen and arrived with a heart turned in repentance (*qalb munīb*), entering in peace, where *“they will have whatever they desire therein, and with Us is even more”* (50:35). The closing movement (36–45) commands the Prophet to maintain patient fortitude against their slanders, to glorify his Lord before sunrise, before sunset, and in parts of the night, and after the prostrations (*adwār al-sujūd*). It concludes with the cosmic Call on the Day when humanity will hear the Blast in truth (*Yawm al-Khurūj*—the Day of Emerging from the earth), and delivers the definitive pastoral mandate to the Prophet: *“We know best what they say, and you are not over them a tyrant. So remind with the Qur'an whoever fears My threat”* (50:45).

**The Jugular Proximity and the Sharpness of Sight**

The core philosophical insight of Sūrah Qāf is that the boundary between this world and the eternal realm is paper-thin. God is not a remote celestial architect; He is closer to the human subject than the arterial vessel that pumps life into his brain. Every whispered desire, every passing thought, and every uttered syllable is registered in the cosmic ledger. Death is not the end of consciousness, but the tearing of the veil (*kashf al-ghiṭā'*), when the spiritual illusions of worldly life dissolve and reality is perceived with razor sharpness (*fa-baṣaruka al-yawma ḥadīd*). By reciting Sūrah Qāf every Friday from the pulpit, the Prophet ﷺ kept human consciousness permanently grounded in this ultimate reality: reminding the soul that life is a sacred, fleeting opportunity to cultivate a heart that turns to God in repentance."""

for ch in [42, 43, 45, 46, 47, 48, 49, 50]:
    insert_surah_intro(ch, intros[ch])
print("Batch 5 (42, 43, 45-50) inserted successfully.")
