import sys
sys.path.append(".")
from scripts.intro_utils import insert_surah_intro

intros = {}

# -------------------------------------------------------------
# SURAH 36: YĀ-SĪN
# -------------------------------------------------------------
intros[36] = """**The Heart of the Scripture and the Resurrection of the Bones**

Yā-Sīn is the thirty-sixth chapter of the Qur'an, comprising 83 verses of mature Makkan revelation. It opens with the mysterious, majestic letters *Yā-Sīn*, which classical commentators such as Ibn ʿAbbās interpreted as a divine address to the Prophet ﷺ in the ancient Ethiopic or Arabic dialect meaning *“O Perfect Human Being!”* In the devotional life of the Islamic world, Sūrah Yā-Sīn occupies a sacred, central throne: celebrated in prophetic tradition as *Qalb al-Qur'ān* (The Heart of the Qur'an). Anas ibn Mālik reported in Jāmiʿ al-Tirmidhī (2887) that the Messenger of Allah ﷺ said: *“Indeed, everything has a heart, and the heart of the Qur'an is Yā-Sīn; whoever recites Yā-Sīn, Allah records for them the reward of reciting the Qur'an ten times.”* Traditional practice across centuries has prescribed its recitation beside the sick, the dying, and the graves of the departed, because its rhythmic, pulsing verses infuse the soul with absolute certainty in bodily resurrection, divine omnipotence, and the reality of the World to Come.

**The City of Defiance and the Solitary Believer**

The historical canvas of Yā-Sīn reflects the fierce, entrenched obstinacy of the Makkan aristocracy, whose spiritual vision had calcified. Verses 8–10 describe them with unforgettable imagery: iron yokes fastened around their necks reaching to their chins so their heads are forced upward in blind arrogance, with barriers placed before them and behind them, veiled so they cannot see. To illustrate the lethal danger of this collective blindness, the sūrah presents the dramatic historical parable of *Aṣḥāb al-Qaryah* (The People of the Town, traditionally identified with Antioch): God sent two messengers to them, reinforced by a third, yet the town rejected them, threatening them with stoning. From the furthest perimeter of the city, a solitary common man—immortalized in tradition as Ḥabīb al-Najjār (the Carpenter)—came running in haste, begging his people to follow messengers who demand no financial reward and are rightly guided. The town martyred him, whereupon divine speech depicts him entering Paradise in the twinkling of an eye, crying with heartbreaking compassion: *“Oh, I wish that my people knew how my Lord has forgiven me and made me of the honored!”* (36:26–27). God dispatched no armies from heaven to punish the city; a single sonic blast (*ṣayḥatan wāḥidah*) extinguished their lives into silent ashes.

**The Cosmic Rhythm and the Decisive Argument**

The architecture of Sūrah Yā-Sīn moves with astonishing symphonic momentum across three great movements. The opening movement (1–32) affirms the prophetic mission of the Messenger upon the Straight Path, warns of the inherited heedlessness of nations, narrates the dramatic martyrdom of the Believer of the Town, and laments the tragic tragedy of humanity: *“How sorrowful for the servants! There never comes to them a messenger except that they used to mock him”* (36:30). The second movement (33–50) presents three cosmic signs of supreme divine power: the dead earth revived by water to bring forth grain, date palms, and vineyards; the night stripping away the day leaving humanity in darkness, with the sun running to its resting place (*mustaqarr*) by the decree of the Almighty, and the moon measured in phases until it returns like an ancient withered date-palm frond (*ka-l-ʿurjūn al-qadīm*), neither able to overtake the other; and the laden ship (*al-fulk al-mashḥūn*) carrying human ancestry across the abyss of the ocean. The third movement (51–83) delivers the climactic, terrifying staging of the Resurrection: the Horn blown, the graves burst open, and humanity crying: *“O woe to us! Who has raised us up from our sleeping place? This is what the Most Compassionate promised, and the messengers were true!”* (36:52). It contrasts the blissful inhabitants of Paradise, reclining in cool shade with fruit and peaceful greetings from a Merciful Lord (*Salāmun qawlan min rabbin raḥīm*), against the disgraced criminals commanded to stand apart (*Wamtāzū al-yawma ayyuhā al-mujrimūn*). It stages the horrifying moment when human mouths are sealed, and their hands speak and feet bear witness to their deeds (36:65). The climax answers the famous challenge of Ubayy ibn Khalaf, who brought a decayed bone, crumbled it into dust before the Prophet's face, and scoffed: *“Who will revive these bones when they have rotted away?”* The sūrah answers with thunderous logic: *“Say, 'He will revive them who produced them the first time; and He is, of all creation, Knowing'”* (36:79), concluding with the immortal, sovereign reality of the Divine Command: *“His command is only when He intends a thing that He says to it, 'Be,' and it is! So exalted is He in whose hand is the realm of all things, and to Him you will be returned”* (36:82–83).

**The Symphony of Life and Resurrection**

Sūrah Yā-Sīn is designated as the "Heart of the Qur'an" because it pumps the lifeblood of faith—the certainty of Resurrection (*al-Baʿth wa-l-Nushūr*)—into every spiritual artery of the reader. It demonstrates that life is not a meaningless biological accident ending in dust; it is a sacred drama governed by the Sovereign Creator whose Word *Kun* ("Be!") brought forth galaxies and will resurrect humanity in a single heartbeat. By showing that the God who extracts green fire from a moist tree and revives the frozen winter soil can effortlessly reconstitute human consciousness, Yā-Sīn frees the human soul from the paralyzing terror of death, anchoring it in the eternal peace of the Merciful Lord."""

# -------------------------------------------------------------
# SURAH 37: AṢ-ṢĀFFĀT
# -------------------------------------------------------------
intros[37] = """**The Ranks of the Angels and the Crucible of the Sacrifice**

Aṣ-Ṣāffāt, "Those Ranks-Aligned," is the thirty-seventh chapter of the Qur'an, comprising 182 verses of early-to-mid Makkan revelation. It takes its name from its breathtaking, rhythmic opening oaths: *“By those [angels] aligned in ranks, and those who drive [clouds] firmly, and those who recite the Reminder—indeed, your God is One!”* (37:1–4). It is the first chapter in the Qur'anic canon to open with oaths sworn by celestial angelic ranks. Characterized by rapid, hammering rhymes and swift, dramatic shifts of scene, Sūrah aṣ-Ṣāffāt delivers a total metaphysical repudiation of the pagan Arab myth that the angels were the "daughters of God" or that God possessed marital ties with the jinn. In prophetic tradition, ʿAbdullāh ibn ʿUmar recorded that the Prophet ﷺ would command the imams to shorten the prayers, yet he himself would lead them reciting Sūrah aṣ-Ṣāffāt (Sunan al-Nasā'ī 826), so sublime was its spiritual elevation. The sūrah is universally celebrated for containing the most emotionally intense, agonizing, and triumphant narrative of prophetic submission in world literature: the binding and attempted sacrifice of Abraham's son (*al-Dhabīḥ*).

**The Pagan Pantheon and the Cosmic Sky**

The historical context of aṣ-Ṣāffāt reflects the absurd theological myths of the Quraysh, who populated the celestial hierarchy with pagan superstitions: claiming that God had daughters, that the jinn had intermarried with divinity, and that soothsayers could consult devils who eavesdropped on heavenly secrets. Sūrah aṣ-Ṣāffāt sweeps away these fantasies with majestic cosmic reality. It reveals the lowest heaven adorned with the beauty of stars and fortified as an impenetrable defense against every rebellious devil; any demon attempting to listen to the Exalted Assembly (*al-Mala' al-Aʿlā*) is pursued and incinerated by a piercing, flaming meteor (*shihābun thāqib*, 37:10). The sūrah challenges the arrogance of human skeptics with a single existential question: *“Ask them: Are they harder to create, or the [other] things We created?”* (37:11).

**The Structural Architecture and the Great Sacrifice**

The architecture of Sūrah aṣ-Ṣāffāt moves from angelic astronomy to eschatological reunions, and from prophetic sacrifices to the final doxology of transcendence. The opening movement (1–39) establishes the absolute unicity of the Lord of the heavens, earth, and the Eastern horizons (*Rabb al-Mashāriq*), depicts the shooting stars defending the celestial realm, and stages the mockery of the deniers turned into horror on the Day of Reckoning, when they are herded with their spouses to the path of Hell and questioned: *“What is [the matter] with you that you do not help one another?”* (37:25). The second movement (40–74) presents an intimate, touching portrait of Paradise: the righteous reclining on thrones facing one another, drinking from cups of pure spring wine that causes no drunkenness or headache, accompanied by pure companions with modest gazes. One of them looks down through a window into the depths of Hell, recognizes an old earthly friend who had mocked his belief in resurrection, and exclaims with trembling relief: *“By Allah, you almost ruined me! Were it not for the favor of my Lord, I would have been of those brought [into Hell]!”* (37:56–57). The third movement (75–148) is the grand prophetic suite:
- Noah (75–82): Crying out in distress, answered by the Best of Responders, leaving his memory blessed among subsequent generations: *“Peace be upon Noah among the worlds!”*
- Abraham and the Sacrifice (83–113): Smashing the idols of his people, cast into the fire, emigrating for God, and praying for a righteous son. When the boy reaches the age of running and laboring with him, Abraham confesses his visionary dream: *“O my son, indeed I see in a dream that I must sacrifice you, so see what you think!”* The boy answers with sublime, unhesitating surrender: *“O my father, do as you are commanded; you will find me, if Allah wills, of the patient.”* The sūrah captures the ultimate moment of faith: *“And when they had both submitted (*aslamā*) and he put him down upon his forehead...”*—whereupon divine voice intervenes, declaring the trial fulfilled, and ransoming the child with a magnificent, momentous sacrifice (*wa-fadaynāhu bi-dhibḥin ʿaẓīm*, 37:107).
- Moses and Aaron (114–122): Favored and delivered from great distress.
- Elijah / Ilyās (123–132): Rebuking his people for worshipping the idol Baal and forsaking the Best of Creators.
- Lot (133–138): Delivered with his household while the remaining towns were buried.
- Jonah (139–148): Fleeing to the laden ship, drawing lots and being among the losers, cast into the churning sea, swallowed by the whale while blameworthy, saved because he was of those who perpetually glorified God, and cast upon the barren shore where a gourd vine (*shaJaratan min yaqṭīn*) shaded his exhausted body, before returning to guide a nation of over one hundred thousand souls.
The closing movement (149–182) delivers the devastating polemical cross-examination regarding the alleged daughters of God, culminating in the immortal three-verse doxology that closes countless Muslim prayers: *“Exalted is your Lord, the Lord of Might, above what they describe! And peace be upon the messengers! And all praise is for Allah, Lord of the worlds”* (37:180–182).

**The Meaning of Islam as Absolute Surrender**

The supreme theological core of Sūrah aṣ-Ṣāffāt is the word *Aslamā* (verse 103)—the simultaneous surrender of Abraham and his son. The sacrifice was never about human blood; God has no need of slaughtered flesh. It was the total, unconditional surrender of the human will: an elderly father surrendering his dearest earthly treasure, and a young son laying his throat to the earth in trust of God. In that terrifying, beautiful moment of absolute submission, the true meaning of *Islām* was born, establishing a covenant of peace and redemption that echoes through all eternity."""

# -------------------------------------------------------------
# SURAH 38: ṢĀD
# -------------------------------------------------------------
intros[38] = """**The Chronicle of Royal Penitence and the Anatomy of Arrogance**

Ṣād is the thirty-eighth chapter of the Qur'an, comprising 88 verses of mid-to-late Makkan revelation. It takes its name from the single, resonant Arabic letter *Ṣād* with which it opens, sworn by the *Qur'āni dhī al-Dhikr* (the Qur'an Full of Reminder). Characterized by immense dramatic power and psychological insight, Sūrah Ṣād is the great scriptural manual on *Inābah*—the continual, penitent turning of the heart back to God. It centers upon three monumental royal and prophetic figures—David, Solomon, and Job—who experienced supreme worldly tests of power, passion, and physical affliction, yet demonstrated their prophetic nobility by immediately prostrating before God in sincere repentance (*awwāb*). Framed between the haughty, bruised ego of the Qurayshi chieftains at its beginning and the primordial, cosmic envy of Iblīs at its conclusion, Sūrah Ṣād reveals that the fatal disease of the soul is *ʿIzzah* (false pride and stubborn arrogance), while the crown of spiritual greatness is the humble courage to confess one's vulnerability before the Almighty.

**The Chieftains in the Chamber of Abū Ṭālib**

The historical occasion of Sūrah Ṣād is recorded by Ibn ʿAbbās and al-Tirmidhī regarding the final illness of the Prophet's protective uncle, Abū Ṭālib. Sensing his imminent demise, twenty-five prominent chieftains of the Quraysh—including Abū Jahl, ʿUtbah ibn Rabīʿah, and Umayyah ibn Khalaf—came to his sickbed, demanding a negotiated settlement with his nephew: *“Let him leave us to our gods, and we will leave him to his!”* When the Prophet ﷺ arrived, he looked at them and said: *“O my uncle, I ask of them only a single sentence: if they utter it, the whole of Arabia will submit to them, and the non-Arabs will pay them tribute!”* Abū Jahl eagerly replied: *“By your father, we will give you that sentence and ten times more! What is it?”* The Prophet replied: *“Say: There is no deity worthy of worship except Allah, and abandon whatever you worship beside Him.”* The chieftains clapped their hands in outrage, rose, and stormed out, exclaiming: *“Has he made the gods into a single God? Indeed, this is a truly astonishing thing!”* (38:5). Verses 1–8 descended immediately, exposing their refusal not as intellectual doubt, but as wounded tribal pride (*bal al-ladhīna kafarū fī ʿizzatin wa-shiqāq*).

**The Structural Modulation and the Kings Who Repented**

The architecture of Sūrah Ṣād is organized around four distinct movements. The opening movement (1–16) refutes the conspiracy of the Qurayshi elite who marvel that a warner has come from among themselves, reminding them of the ruined ancient coalitions (Noah, ʿĀd, Pharaoh of the Stakes, Thamūd, Lot, and the Forest Dwellers) who were wiped out by a single screaming blast. The second movement (17–40) presents the royal paradigms of David and Solomon:
- David (17–26): Endowed with physical strength and continuous penitence (*awwāb*), accompanied by mountains and birds glorifying God at sunrise and evening, his kingdom strengthened with wisdom and decisive speech (*faṣl al-khiṭāb*). It recounts the dramatic parable of the two litigants who scaled the walls of his sanctuary: one possessing ninety-nine ewes demanding the single ewe of his brother. David judges swiftly that the demand is unjust, suddenly perceives that the situation is a divine test of his own heart, and falls down in prostration, turning to God in repentance (*wa-kharra rākiʿan wa-anāb*, 38:24). God forgives him and establishes his royal mandate: *“O David, indeed We have made you a viceregent upon the earth, so judge between the people in truth and do not follow [your own] desire”* (38:26).
- Solomon (30–40): Bestowed upon David as an excellent, penitent servant (*niʿma al-ʿabd, innahū awwāb*). Absorbed one evening in the review of noble, pure-bred war steeds until the sun slipped behind the veil of horizon, Solomon realized they had distracted him from the evening remembrance of his Lord; he ordered them returned, stroked their necks and legs in renunciation, and prayed for a unique sovereign kingdom: *“My Lord, forgive me and grant me a kingdom such as will not belong to anyone after me”* (38:35)—answered by God with the subjugation of the wind blowing gently at his command and the construction abilities of the jinn.
The third movement (41–48) portrays the supreme archetype of patience: Job (*Ayyūb*), struck with agonizing physical disease and the loss of family and wealth, crying out: *“Indeed, Satan has touched me with distress and torment!”* Commanded to strike the earth with his foot, a cool spring gushes forth for washing and drinking, restoring his health and doubling his family as a mercy, honored with the divine verdict: *“Indeed, We found him patient, an excellent servant. Indeed, he was one who repeatedly turned [to Us]”* (38:44). The fourth movement (49–88) contrasts the lush gardens of Eden against the scalding fluids of Hell, and concludes with the primordial drama of Adam and Iblīs: God commanding the angels to prostrate to the man fashioned from clay into whom the Divine Spirit was breathed, and Iblīs defiantly refusing out of racial arrogance: *“I am better than him! You created me from fire and created him from clay!”* (38:76). The sūrah closes with the Prophet disclaiming all worldly ambition: *“Say, 'I do not ask you for the Qur'an any payment, and I am not of the pretentious. It is but a reminder to the worlds'”* (38:86–87).

**The Courage of Inābah Versus the Prison of Pride**

The central spiritual argument of Sūrah Ṣād is the absolute dichotomy between *ʿIzzah* (arrogance) and *Inābah* (penitent return). Arrogance was the sin of the Qurayshi chieftains who stormed out of Abū Ṭālib's room, and it was the cosmic sin of Iblīs who claimed superiority based on fire. In contrast, the mark of prophetic nobility—embodied by David on his throne, Solomon in his palace, and Job upon his bed of affliction—is the total absence of pride. The moment they perceived a spiritual shortcoming, they dropped to their knees in tears and prostration. Sūrah Ṣād teaches that human perfection does not consist in never making an error; human perfection consists in the speed with which the soul shatters its own ego and runs back into the forgiving embrace of God."""

# -------------------------------------------------------------
# SURAH 39: AZ-ZUMAR
# -------------------------------------------------------------
intros[39] = """**The Crowds of Destiny and the Ocean of Absolute Mercy**

Az-Zumar, "The Crowds" or "The Groups," is the thirty-ninth chapter of the Qur'an, comprising 75 verses of late Makkan revelation. It takes its name from verses 71 and 73, which depict the breathtaking, climactic eschatological spectacle of humanity being driven toward their final eternal abodes in vast, surging throngs or crowds (*zumarā*): the unrepentant driven in crowds to the gates of Hell, and the God-conscious led in luminous, joyful crowds to the portals of Paradise, greeted by the angels: *“Peace be upon you; you have done well; so enter it to abide eternally.”* In prophetic tradition, ʿĀ'ishah recorded that the Prophet Muḥammad ﷺ would never sleep at night until he had recited both Sūrah Banī Isrā'īl (al-Isrāʾ) and Sūrah az-Zumar (Jāmiʿ al-Tirmidhī 3405). Sūrah az-Zumar is universally celebrated for containing what ʿAbdullāh ibn ʿAbbās designated as *the most hopeful verse in the entire Book of God* (verse 53): *“Say, 'O My servants who have transgressed against themselves [by sinning], do not despair of the mercy of Allah. Indeed, Allah forgives all sins. Indeed, it is He who is the Forgiving, the Merciful.'”* Characterized by soaring, passionate eloquence, the sūrah is a monumental treatise on *Ikhlāṣ*—the pure, unadulterated dedication of the human heart, worship, and obedience exclusively to the Living God.

**The Theater of Polytheistic Intercession**

The historical context of az-Zumar reflects the subtle, insidious psychology of the Makkan polytheists. Unlike crude atheists, the Quraysh acknowledged that Allah created the heavens and the earth, yet they rationalized their idolatry through the theology of intercession (*shafāʿah*), proclaiming in verse 3: *“We only worship them so that they may bring us nearer to Allah in position!”* They treated the Divine Court like a corrupt tribal monarchy, where favored courtier-idols could lobby or bribe the King on behalf of their clients. Sūrah az-Zumar deconstructs this delusion with sovereign force: God possesses no partners, needs no courtiers, and accepts no divided worship: *“Unquestionably, for Allah is the pure religion (*al-Dīn al-Khāliṣ*)”* (39:3). Intercession belongs entirely and exclusively to Allah (39:44), granted only to whom He permits, and the human being must stand in unmediated, naked vulnerability before his Lord.

**The Structural Cadence and the Trembling Skin**

The architecture of Sūrah az-Zumar moves in an emotional crescendo from cosmic monotheism to psychological examination, and from the oasis of absolute mercy to the gates of the eternal realms. The opening movement (1–22) establishes the descent of the Book in truth, mandating sincere worship (*mukhlisan lahu al-dīn*), displaying the cosmological cycle of night wrapping around day (*yukawwiru al-layla ʿalā al-nahār*) and the creation of humanity from a single soul, then fashioned in the darknesses of three veils within the womb (39:6). It introduces the profound psychological question of verse 9: *“Is one who is devoutly obedient during periods of the night, prostrating and standing, fearing the Hereafter and hoping for the mercy of his Lord, [like one who denies]? Say, 'Are those who know equal to those who do not know?' Only the people of understanding remember.”* The second movement (23–52) presents the celebrated description of the Qur'an in verse 23: *“Allah has sent down the best statement: a consistent Book wherein is paired reiteration. The skins shiver therefrom of those who fear their Lord; then their skins and their hearts relax to the remembrance of Allah.”* It introduces the striking parable of the two men: a slave owned by multiple, quarrelsome, competing partners pulling him in opposite directions, compared to a man belonging entirely to one master—asking: *“Are they equal in comparison?”* (39:29). The third movement (53–67) opens the floodgates of divine forgiveness: summoning the most broken, guilt-ridden, and despairing sinners never to despair of God's boundless mercy, commanding immediate repentance before punishment arrives unawares, and delivering the terrifying indictment of human pride in verse 67: *“They have not appraised Allah with true appraisal, while the earth entirely will be [within] His grip on the Day of Resurrection, and the heavens will be folded in His right hand!”* The climactic movement (68–75) stages the universal eschatological finale: the Horn blown and all in heaven and earth falling dead except whom God wills; blown a second time and humanity standing, watching; the earth shining with the light of its Lord (*wa-ashraqati al-arḍu bi-nūri Rabbihā*); the Book laid open; the prophets and witnesses brought forth; the crowds driven to Hell in fire; and the crowds led to Paradise in light, concluding with the angels encircling the Throne, glorifying their Lord, as the universe resounds with the final decree: *“All praise is for Allah, Lord of the worlds!”*

**The Philosophy of Pure Sincerity: Ikhlāṣ**

The supreme spiritual thesis of Sūrah az-Zumar is that God accepts nothing from human worship except that which is 100% pure (*khāliṣ*). A heart divided between God and the opinions of people, or between God and wealth, is a heart in agony—like the slave pulled apart by quarreling masters. True liberation is found only in *Ikhlāṣ*: emptying the inner sanctuary of all idols, turning the face to the One God in midnight vigil, and resting in the certainty that no sin is too colossal to be swallowed by the ocean of His forgiving mercy (*Inna Allāha yaghfiru al-dhunūba jamīʿā*)."""

# -------------------------------------------------------------
# SURAH 40: GHĀFIR
# -------------------------------------------------------------
intros[40] = """**The Forgiver of Sins and the Believer in the House of Pharaoh**

Ghāfir, "The Forgiver"—equally renowned across classical exegetical and hadith literature as *Al-Muʾmin* (The Believer)—is the fortieth chapter of the Qur'an, comprising 85 verses of late Makkan revelation. It holds a sacred, historic station as the majestic portal to the celebrated *Ḥā-Mīm* Septet: a contiguous sequence of seven sublime chapters (Sūrahs 40 through 46) that open with the mystical disconnected letters *Ḥā-Mīm*. In prophetic tradition, these seven chapters are revered as the *Ḥawāmīm*—designated by ʿAbdullāh ibn Masʿūd as *“the crowns of the Qur'an”* and by Ibn ʿAbbās as *“the aromatic silk gardens of scripture.”* It takes its primary name, *Ghāfir*, from verse 3, which presents a breathtaking cascade of divine attributes: *“The Forgiver of sin, the Accepter of repentance, the Severe in punishment, the Owner of abundance; there is no deity except Him; to Him is the final destination.”* Its alternative title, *Al-Muʾmin*, honors the heroic, anonymous Egyptian prince in verses 28–45: a secret believer from the royal household of Pharaoh who stepped forward during a royal council plotting the assassination of Moses, risking his life to deliver an impassioned, brilliant defense of faith and conscience.

**The Conspiracy to Assassinate the Messenger**

The historical climate of Sūrah Ghāfir reflects an acute escalation of the Makkan crisis. Following the public collapse of all Qurayshi boycott attempts, the pagan leadership reached a desperate, murderous consensus: they began openly conspiring to physically assassinate the Prophet Muḥammad ﷺ. Classical authorities, including al-Baghawī, record that Sūrah Ghāfir descended precisely when the Qurayshi council was actively plotting the Prophet's death. In this climate of lethal danger, revelation intervened with the dramatic historical parallel of Moses and the court of Pharaoh: just as Pharaoh shouted in his imperial council: *“Leave me to kill Moses, and let him call upon his Lord!”* (40:26), so too were the Qurayshi oligarchs boasting of their power. The sūrah descended to remind both the conspirators and the beleaguered Prophet that God does not abandon His messengers, and that divine protection can raise a champion of truth from inside the very walls of the tyrant's palace.

**The Structural Architecture and the Secret Prince**

The architecture of Sūrah Ghāfir is organized around four magnificent movements. The opening movement (1–22) establishes the Book revealed from the Almighty, the All-Knowing, warns against the intellectual vanity of those who dispute divine signs without authority, and unveils the awe-inspiring cosmic scene of the Throne: the supreme archangels carrying the Throne of God and those encircling it, glorifying their Lord with praise and continually weeping in intercessory supplication for the fallible believers on earth: *“Our Lord, You have encompassed all things in mercy and knowledge, so forgive those who have repented and followed Your way and protect them from the punishment of Hellfire”* (40:7). The second and dramatic movement (23–46) stages the confrontation between Moses, Pharaoh, Hāmān, and the *Believer of Pharaoh's House* (*Mu'min Āli Firʿawn*). The secret believer intervenes with masterly rhetoric: *“Would you kill a man merely because he says, 'My Lord is Allah,' while he has brought you clear proofs from your Lord?”* (40:28). He warns his court of the *Day of Mutual Calling* (*Yawm al-Tanād*), recalls how Joseph brought clear proofs to Egypt generations before, and exposes the absurdity of Pharaoh ordering Hāmān to build a lofty brick tower to reach the clouds and spy on the God of Moses. As the court turns against him, the noble believer declares his immortal reliance: *“And I entrust my affair to Allah. Indeed, Allah is Seeing of the servants”* (40:44), whereupon God shields him from their evil plots and drowns Pharaoh's regime, exposing them to the Fire morning and evening in their graves. The third movement (47–68) portrays the pathetic mutual recriminations of the damned in Hell, begging the guards of the Fire to ask their Lord for a single day's reduction of torment, only to be answered: *“Did there not come to you your messengers with clear proofs?”* It affirms the eternal divine decree of verse 51: *“Indeed, We will support Our messengers and those who believe during the life of this world and on the Day when the witnesses will stand.”* The closing movement (69–85) contrasts the immense creation of the heavens and earth against the fragile conceit of man, commands the Prophet to be patient for the promise of God is true, and delivers the famous invitation of verse 60: *“Call upon Me; I will answer you!”*, concluding with the catastrophic realization of ancient deniers whose deathbed faith availed them nothing when the overwhelming might of God descended.

**The Power of Hidden Faith and the Sovereign Shield**

The foundational spiritual thesis of Sūrah Ghāfir is that truth is invincible even when backed by a single unarmed voice against an entire empire. The secret believer in Pharaoh's palace had neither armies nor weapons; he possessed only eloquent reason, moral courage, and absolute reliance upon the Lord (*wa-ufawwiḍu amrī ilā Allāh*). His intervention paralyzed Pharaoh's murderous resolve and entered sacred history as an eternal paradigm of speaking truth to power. Sūrah Ghāfir reassures the beleaguered believer in every age that no matter how terrifying the plots of tyrants may appear, the Almighty (*al-ʿAzīz*) is the supreme shield of His servants, and that those who entrust their affairs to Him are forever safe beneath His watchful gaze."""

for ch in [36, 37, 38, 39, 40]:
    insert_surah_intro(ch, intros[ch])
print("Batch 4 (Part B: 36-40) inserted successfully.")
