import sys
sys.path.append(".")
from scripts.intro_utils import insert_surah_intro

intros = {}

# -------------------------------------------------------------
# SURAH 73: AL-MUZZAMMIL
# -------------------------------------------------------------
intros[73] = """**The Enshrouded Messenger and the Furnace of the Night Vigil**

Al-Muzzammil, "The Enshrouded One," is the seventy-third chapter of the Qur'an, comprising 20 verses. In the chronology of revelation, it occupies a primordial, sacred station: universally recognized by classical authorities (including ʿĀ'ishah, Ibn ʿAbbās, and Mujāhid) as the *third chapter* revealed to the Prophet Muḥammad ﷺ, descending immediately following the initial commission at Ḥirā' and the opening lines of al-Muddaththir. It opens with an intensely affectionate, tender divine vocative address: *“O you wrapped in garments (*Yā ayyuhā al-muzzammil*)! Stand [in prayer] all night, except for a little—half of it, or subtract from it a little, or add to it, and recite the Qur'an with measured, rhythmic recitation (*wa-rattili al-Qur'āna tartīlā*)”* (73:1–4). In twenty profound verses, Sūrah al-Muzzammil functions as the spiritual training academy for the fledgling Islamic mission: forging the Prophet's soul through the strenuous discipline of the night vigil (*Qiyām al-Layl*) to prepare him to carry the immense, mountain-crushing gravity of revelation (*Qawlan Thaqīlā*).

**The Weight of Revelation and the Midnight Sanctuary**

The historical canvas of al-Muzzammil is the immediate aftermath of the terrifying initial encounters with the Angel Gabriel. Overwhelmed by the celestial majesty of the Archangel, the Prophet ﷺ had returned to his home in Makkah shivering with spiritual fever, crying to Khadījah: *“Wrap me! Enshroud me! (*Zammilūnī! Zammilūnī!*)”* As he lay wrapped beneath his wool mantle seeking recovery, heaven called him to rise: the era of sleep had ended; the era of universal spiritual responsibility had begun. Verse 5 announces the existential purpose of the night vigil: *“Indeed, We will cast upon you a heavy Word (*Qawlan Thaqīlā*).”* The Word of God is heavy in its divine majesty, heavy in its moral demands, and heavy in the civilizational transformation it requires. To bear such weight without breaking, the Prophet's soul needed a spiritual counterweight—and that counterweight could only be forged in the silence of the night, when the senses are subdued and the heart is entirely aligned with divine speech.

**The Structural Modulation and the Mitigation of Hardship**

The architecture of Sūrah al-Muzzammil is divided into two distinct historical and spiritual movements:
1. The Makkan Crucible of the Night Prayer (1–19): The command to stand in prayer half the night, reciting the Qur'an slowly and deliberately (*tartīl*). Verse 6 delivers the profound psychological law of nocturnal devotion: *“Indeed, the rising by night is more effective for establishing internal harmony / grounding the soul (*ashaddu waṭ'ā*), and more upright in speech (*aqwamu qīlā*).”* It notes that by day the Prophet has prolonged business (*sabḥan ṭawīlā*), commanding him to remember the Name of his Lord and devote himself to Him with complete devotion (*wa-tabattal ilayhi tabtīlā*). It commands patient endurance against the insults of the Qurayshi elite (*wa-ṣbir ʿalā mā yaqūlūn*), leaving the affluent deniers to God's retribution, and painting the terrifying scene of the Day of Judgment when the earth and mountains shake and the mountains become dunes of shifting sand (*kathīban mahīlā*). It reminds the Makkans of Pharaoh rejecting the messenger sent to him, ending in catastrophic destruction, asking: *“Then how will you protect yourselves, if you disbelieve, on a Day that will turn children white-haired (*yawman yajʿalu al-wildāna shībā*)?”* (73:17).
2. The Medinan Mitigation and the Reality of Human Frailty (20): Chronologically revealed approximately one year later (with some authorities placing its finalization in the early Medinan period), the long, famous twentieth verse brought divine relief to a community that had stood in prayer until their feet swelled: *“Indeed, your Lord knows, [O Muḥammad], that you stand [in prayer] almost two-thirds of the night or half of it or a third of it, and [so do] a group of those with you. And Allah determines the night and the day. He has known that you [believers] cannot keep strict count of it, so He has turned to you in forgiveness, so recite what is easy [for you] of the Qur'an!”* It recognizes human vulnerability—that some are ill, some travel through the earth seeking God's bounty through trade, and some fight in the cause of Allah. It commands the community to establish regular prayer, pay the Zakat, and offer Allah a goodly loan, concluding with the luminous promise: *“And whatever good you put forward for yourselves—you will find it with Allah; it is better and greater in reward. And seek forgiveness of Allah. Indeed, Allah is Forgiving and Merciful.”*

**The Philosophy of Tartīl and Ashaddu Waṭ'ā**

The foundational spiritual insight of Sūrah al-Muzzammil is that internal spiritual capacity must precede external social action. Before a person can reform the marketplace, confront the tyrants, or establish justice in the city, he must conquer his own soul in the solitude of the night vigil (*Qiyām al-Layl*). The recitation of the Qur'an in *Tartīl*—slow, rhythmic, meditative articulation—allows the sacred text to saturate the subconscious mind, uniting the heart and tongue into an unbreakable pillar of spiritual strength (*ashaddu waṭ'ā*). Sūrah al-Muzzammil teaches that the light that illuminates the public square by day is ignited upon the prayer mat by night."""

# -------------------------------------------------------------
# SURAH 74: AL-MUDDATHTHIR
# -------------------------------------------------------------
intros[74] = """**The Cloaked Herald and the Furnace of Saqar**

Al-Muddaththir, "The Cloaked One," is the seventy-fourth chapter of the Qur'an, comprising 56 verses of early Makkan revelation. In the history of divine revelation, it holds a monumental, sacred station: universally recognized in authentic hadith as the *second primary revelation* that broke the agonizing pause (*Fatrat al-Waḥy*) and inaugurated the public mission of prophethood. Jābir ibn ʿAbdillāh reported in Ṣaḥīḥ al-Bukhārī (4) that the Messenger of Allah ﷺ recounted: *“While I was walking, I suddenly heard a voice from the sky. I looked up, and behold, the same Angel who had visited me at Ḥirā' was sitting upon a throne between heaven and earth! I was struck with terrifying awe of him until I fell to the ground. I returned home and cried: 'Cloak me! Cloak me! (*Daththirūnī! Daththirūnī!*)' Whereupon Allah revealed: 'O you cloaked in garments! Arise and warn!'”* Sūrah al-Muddaththir is the divine bugle-call of active prophetic ministry, delivering a blistering psychological indictment of aristocratic arrogance, unveiling the nineteen angelic wardens of Hellfire (*Saqar*), and contrasting the flight of terrified donkeys against the majesty of the Reminder.

**The Council of the Quraysh and the Calculus of al-Walīd**

The historical catalyst of the central section of al-Muddaththir (verses 11–26) is preserved in classical chronicles regarding al-Walīd ibn al-Mughīrah, the wealthiest, most eloquent elder of the Quraysh. As the pilgrimage season approached, al-Walīd gathered the chieftains of Makkah, warning them: *“The delegations of Arabia are arriving, and they will hear of Muḥammad's message. You must agree upon a single statement regarding him, lest you contradict one another!”* They suggested branding him a soothsayer (*kāhin*); al-Walīd replied: *“By God, his words do not resemble the rhymed murmuring of soothsayers!”* They suggested calling him mad (*majnūn*); he said: *“We see in him no choking or demonic seizures!”* They suggested calling him a poet (*shāʿir*); he replied: *“We know all forms of poetry, and his speech is not poetry!”* They suggested sorcerer (*sāḥir*); he said: *“He blows upon no knots!”* When they asked: *“What then shall we say?”*, al-Walīd frowned, thought deeply, calculated, and finally pronounced the cynical compromise: *“Say that he is a sorcerer who separates a man from his father, his brother, his wife, and his clan!”* Verses 11–26 descended in devastating, cinematic mockery of his mental gymnastics: *“Leave Me [to deal] with him whom I created alone, and to whom I granted extensive wealth and children present before him... Indeed, he thought and calculated! So may he be destroyed, how he calculated! Then he frowned and scowled, then turned back and was arrogant, saying: 'This is not but sorcery imitated; this is not but the speech of a human!' I will drive him into Saqar!”*

**The Structural Architecture and the Nineteen Wardens**

The architecture of Sūrah al-Muddaththir unfolds across four distinct movements:
1. The Seven Sacred Commands of Ministry (1–7): The divine commissioning: *“Arise and warn! And your Lord glorify! And your garments purify! And uncleanliness / idolatry shun! And do not confer favor to acquire more! And for your Lord be patient!”*
2. The Retribution of the Arrogant Oligarch (8–26): The sounding of the Horn (*al-Nāqūr*) on a Day difficult for the disbelievers, followed by the psychological dissection and doom of al-Walīd ibn al-Mughīrah, promised the agonizing torment of *Saqar*: *“It leaves nothing and spares nothing, scorching the human skin!”*
3. The Nineteen Angelic Wardens and the Parable of the Trial (27–37): Reveals that over Saqar are *nineteen* angelic guardians. Verse 31 delivers an extraordinary theological explanation of why this specific number was designated: as a trial (*fitnah*) for the disbelievers, so that the People of the Scripture may be convinced of the Qur'an's truth, the believers may increase in faith, all doubt may be removed from sincere hearts, and those in whose hearts is disease may ask in mockery: *“What does Allah intend by this example?”* It confirms: *“And none knows the soldiers of your Lord except Him; and it is not but a reminder to humanity.”*
4. The Interrogation of the Damned and the Stampeding Zebras (38–56): Delivers the solemn constitutional axiom: *“Every soul, for what it has earned, will be held in pledge (*kullu nafsin bi-mā kasabat rahīnah*), except the Companions of the Right.”* It stages the dramatic dialogue between the inhabitants of Paradise and the inmates of *Saqar*: *“What brought you into Saqar?”* They reply with the four fatal moral sins:
   - *“We were not of those who prayed.”*
   - *“We did not feed the impoverished.”*
   - *“We used to converse in vain discourse with those who conversed.”*
   - *“We used to deny the Day of Recompense until there came to us the certainty [of death].”*
The sūrah delivers the unforgettable, satirical portrait of the disbelievers fleeing from the Qur'an: *“As if they were alarmed donkeys / wild zebras fleeing from a lion!”* (74:50–51), concluding that whoever wills will remember it, and none will remember except if Allah wills: *“He is worthy of being feared and worthy of [granting] forgiveness.”*

**The Call to Rise: Qum fa-Andhir**

The supreme spiritual imperative of Sūrah al-Muddaththir is contained in its opening phrase: *Qum fa-andhir* ("Arise and warn!"). True spirituality cannot remain wrapped in a cozy blanket of private piety (*al-muddaththir*); it must rise, purify its garments, glorify its Lord, and step out into the noisy, hostile street to defend truth and protect humanity from the furnace of *Saqar*. Sūrah al-Muddaththir transforms the contemplative hermit of the cave into the fearless herald of universal human redemption."""

# -------------------------------------------------------------
# SURAH 75: AL-QIYĀMAH
# -------------------------------------------------------------
intros[75] = """**The Self-Accusing Soul and the Radiant Faces of the Vision**

Al-Qiyāmah, "The Resurrection," is the seventy-fifth chapter of the Qur'an, comprising 40 verses of early Makkan revelation. It opens with two colossal, deeply intimate divine oaths: *“I swear by the Day of Resurrection (*Lā uqsimu bi-yawmi al-qiyāmah*), and I swear by the self-reproaching / self-accusing soul (*wa-lā uqsimu bi-l-nafsi al-lawwāmah*)!”* (75:1–2). In moral psychology and Islamic spirituality, Sūrah al-Qiyāmah is universally celebrated for conjoining the macrocosmic reckoning of the universe (*al-Qiyāmah*) with the microcosmic reckoning of the human conscience (*al-Nafs al-Lawwāmah*). Characterized by rapid, dramatic staccato verses that beat like a racing pulse, the sūrah captures the terror of the physical disintegration of death, the reconstruction of the human fingertips, the prohibition of rushing the tongue during revelation, and the supreme, transcendent reward of Paradise: gazing directly upon the Unveiled Face of God (*ilā Rabbihā nāẓirah*, 75:23).

**The Challenge of the Fingertips and the Agony of Revelation**

The historical context of al-Qiyāmah reflects the insolent physical skepticism of the Quraysh, who scoffed at the possibility of decomposed dust being reassembled. Verse 3 quotes their mockery: *“Does man think that We will not assemble his bones?”* The sūrah answers with breathtaking biological precision in verse 4: *“Yes! [We are] Able even to proportion his fingertips (*banānah*)!”* Exegetes and modern readers marvel at this reference to the fingertips: the unique, individualized ridges of human fingerprints that distinguish every single human being across all time were highlighted by divine speech as the absolute proof of reconstructing unique human identity! Furthermore, the sūrah contains the famous parenthetical instruction to the Prophet ﷺ during the descent of revelation in verses 16–19: overwhelmed by the sheer velocity and beauty of Gabriel's recitation, the Prophet would rapidly move his tongue to memorize every syllable before it vanished; revelation intervened with loving tenderness: *“Do not move your tongue with it, [O Muḥammad], to hasten [recitation]! Indeed, upon Us is its collection and its recitation... Then upon Us is its clarification.”*

**The Structural Modulation and the Tangled Legs**

The architecture of Sūrah al-Qiyāmah moves across three dramatic, intensely focused movements:
1. The Awakening of the Conscience and the Reconstruction of Man (1–15): Swears by the Day of Resurrection and the self-accusing conscience (*al-nafs al-lawwāmah*). It asserts that man knows his own moral bankruptcy even as he puts forward excuses (*“Nay, man against himself is a seeing witness, even though he presents his excuses,”* 75:14–15). It describes the cosmic collapse: the vision dazed, the moon eclipsed, and the sun and moon joined together in celestial collision, while man cries on that Day: *“Where is the escape? (*Ayna al-mafarr?*)”* The answer thunders: *“No! There is no refuge! To your Lord, that Day, is the [place of] permanence.”*
2. The Preservation of Scripture and the Two Faces of Eternity (16–25): The divine guarantee of the Qur'an's textual preservation and clarity (75:16–19). It rebukes humanity for loving the fleeting, immediate world (*al-ʿājilah*) and abandoning the Hereafter (*al-ākhirah*). It presents the immortal, contrasting spectacle of the two faces:
   - *The Radiant Faces* (22–23): *“Faces, that Day, will be radiant (*nāḍirah*), looking at their Lord (*ilā Rabbihā nāẓirah*)!”* In authentic hadith (Ṣaḥīḥ al-Bukhārī 7434), the Prophet ﷺ confirmed that believers will see their Lord on the Day of Resurrection as clearly as they see the full moon in an unclouded night sky.
   - *The Gloomy Faces* (24–25): *“And faces, that Day, will be contorted in despair (*bāsirah*), anticipating that there will be done to them a back-breaking calamity (*fāqirah*)!”*
3. The Climax of Death and the Clattering of Shins (26–40): Delivers one of the most chilling, intimate descriptions of human mortality in world literature: the dying soul reaching the collarbone (*al-tarāqī*), the helpless family crying: *“Who can cure him?”*, the dying man realizing that this is the final departure, and his legs tangling with one another in the agony of death (*wa-l-taffati al-sāqu bi-l-sāq*)—*“To your Lord, that Day, will be the drive!”* It indicts the arrogant denier who neither believed nor prayed, but denied and turned away, then strutted back to his family in self-admiration (*yatamattā*), greeted by the fourfold death knell: *“Woe to you, and woe! Then woe to you, and woe!”* (75:34–35). The sūrah concludes by challenging human pride with its humble origin: *“Does man think that he will be left purposeless (*sudā*)? Was he not a drop of emitted sperm? Then a clinging clot, and He created and proportioned, and made of him two mates, male and female? Is not that [Creator] able to give life to the dead?”*

**The Nafs al-Lawwāmah and the Beatific Vision**

The supreme theological core of Sūrah al-Qiyāmah is the sacred dignity of the *Nafs al-Lawwāmah* (the self-accusing conscience). The human conscience is an internal courtroom planted by God within the soul—the spark that reproaches a person when he slips into sin and urges him to repentance. The soul that nurtures this internal reckoning in worldly life is transformed on the Day of Resurrection into a radiant, illuminated vessel, granted the supreme crown of all spiritual existence: the Beatific Vision—gazing upon the Unveiled Face of the Divine (*ilā Rabbihā nāẓirah*). Sūrah al-Qiyāmah teaches that humanity was not created to drift aimlessly through life (*sudā*); we are beings of eternal destiny, summoned to live with conscience so that we may open our eyes to the radiant presence of the Creator."""

# -------------------------------------------------------------
# SURAH 76: AL-INSĀN
# -------------------------------------------------------------
intros[76] = """**The Time of Nothingness and the Cup of Camphor**

Al-Insān, "Humanity"—also universally designated in classical exegesis as *Sūrat al-Dahr* (The Era/Time)—is the seventy-sixth chapter of the Qur'an, comprising 31 verses. While classical authorities debate its chronological origin (with some scholars viewing it as early Makkan and others, including Mujāhid and Qatādah, considering it early Medinan), the chapter opens with one of the most humbling, contemplative philosophical questions ever posed to the human mind: *“Has there [not] come upon man a period of time when he was not a thing mentioned? (*Hal atā ʿalā al-insāni ḥīnun min al-dahri lam yakun shay'an madhkūrā*)”* (76:1). In prophetic tradition, Sūrah al-Insān is paired with Sūrah as-Sajdah as the fixed, beloved recitation of the Prophet Muḥammad ﷺ in the dawn prayer (*Fajr*) every Friday (Ṣaḥīḥ al-Bukhārī 891). Characterized by luminous, serene, jewel-like descriptions of the heavenly paradise, Sūrah al-Insān is universally celebrated for verses 8–9, which immortalize the supreme, selfless charity of the righteous (*al-Abrār*): feeding the hungry out of pure love for God without demanding a shred of reward or thanks.

**The Primordial Void and the Gift of Consciousness**

The philosophical opening of al-Insān confronts human arrogance at its biological and cosmic root. Before an individual was born, named, clothed, and endowed with an ego, billions of years of cosmic history elapsed during which he was absolutely nothing—unmentioned, unconceived, and non-existent. God extracted humanity from an insignificant mixture of drops (*amshāj*), endowed him with hearing and sight, and laid open before him the clear path of moral agency: *“Indeed, We guided him to the way, whether he be grateful or whether he be ungrateful”* (76:3). The sūrah addresses a world obsessed with pedigree and power, demonstrating that the only nobility that endures past the grave is the nobility of the grateful servant who uses his fleeting moments of earthly existence to serve the vulnerable.

**The Structural Tapestry of the Righteous**

The architecture of Sūrah al-Insān is designed around a sublime contrast between the chains of the ungrateful and the luminous banquet of the *Abrār*:
1. The Creation and the Two Paths (1–4): Recalls the primordial non-existence of man, his biological creation to be tested, the gift of hearing, sight, and free will, and the contrasting outcomes: chains, shackles, and a blazing fire for the ungrateful deniers.
2. The Portrait of the Abrār and the Selfless Banquet (5–22): Unfolds the breathtaking reward of the righteous in Paradise: drinking from a cup mixed with fragrant camphor (*kāfūr*) from a spring gushing forth abundantly. Verses 7–9 define their earthly virtues:
   - They fulfill their vows (*yūfūna bi-l-nadhr*).
   - They fear a Day whose evil is widespread.
   - *“And they give food in spite of love for it to the needy, the orphan, and the captive, [saying], 'We feed you only for the face of Allah. We wish not from you reward or gratitude (*lā nurīdu minkum jazā'an wa-lā shukūrā*)!'”*
   God protects them from the terror of that Day, meets them with radiance and joy (*naḍratan wa-surūrā*), and rewards their patience with a Garden and garments of green silk and brocade. They recline on couches seeing neither burning heat nor freezing cold, clusters of fruit hanging within arm's reach, served in vessels of silver and transparent crystal goblets of silver (*qawārīra min fiḍḍah*) pre-measured with absolute precision. They drink from a cup mixed with ginger (*zanjabīl*) from a spring named *Salsabīl*, surrounded by immortal youths who look like scattered pearls (*lu'lu'an manthūrā*). When one looks there, *“you will see pleasure and a great kingdom!”* (76:20), adorned with bracelets of silver, their Lord giving them a pure drink (*sharāban ṭahūrā*): *“Indeed, this is for you a reward, and your effort has been appreciated (*saʿyukum mashkūrā*)!”*
3. The Revelation of the Quran and the Midnight Vigil (23–31): Consoles the Prophet: *“Indeed, it is We who have sent down upon you the Qur'an progressively.”* Commands him to be patient for the decision of his Lord, never obeying a sinful or ungrateful denier, and establishing the spiritual lifeline: *“And remember the name of your Lord [in prayer] morning and evening, and during the night prostrate to Him and glorify Him a long night through”* (76:25–26). It condemns those who love the immediate worldly life and leave behind them a heavy Day, reminding them that God created them and strengthened their forms, and could replace them at will. The chapter concludes by affirming that the Qur'an is a reminder for whoever wills to take a path to his Lord, under the sovereign umbrella of divine grace: *“He admits whom He wills into His mercy.”*

**The Purity of Inward Intention: Li-Wajhi Allāh**

The supreme moral and spiritual jewel of Sūrah al-Insān is the declaration of the righteous in verse 9: *Innamā nuṭʿimukum li-wajhi Allāhi lā nurīdu minkum jazā'an wa-lā shukūrā* ("We feed you only for the Face of Allah; we desire from you neither reward nor thanks"). True charity is not philanthropy performed for social acclaim, tax benefits, political leverage, or personal pride; true charity is the secret surrender of one's dearest sustenance to an orphan, a beggar, or a prisoner out of pure love for the Creator. By promising that God Himself will say to these selfless souls in Paradise: *“Your effort has been appreciated (*saʿyukum mashkūrā*)”*, Sūrah al-Insān reveals the highest station of human existence: the servant who forgot himself to feed others, remembered and thanked for eternity by the Lord of the worlds."""

# -------------------------------------------------------------
# SURAH 77: AL-MURSALĀT
# -------------------------------------------------------------
intros[77] = """**The Emissaries of the Storm and the Tenfold Woe**

Al-Mursalāt, "The Emissaries" or "Those Sent Forth," is the seventy-seventh chapter of the Qur'an, comprising 50 verses of early Makkan revelation. In the sequence of prophetic transmissions, it holds a poignant, historic station: ʿAbdullāh ibn Masʿūd reported in Ṣaḥīḥ al-Bukhārī (4932) and Ṣaḥīḥ Muslim (2804) that *“We were with the Messenger of Allah ﷺ in a cave at Minā when Sūrah al-Mursalāt was revealed to him. He was reciting it, and I was receiving it directly from his mouth while it was still moist with revelation, when suddenly a serpent leaped out at us! The Prophet cried: 'Kill it!' We rushed to kill it, but it escaped into its hole. The Prophet smiled and said: 'It was saved from your harm just as you were saved from its harm!'”* The sūrah opens with five majestic meteorological and angelic oaths: *“By those [winds or angels] sent forth in succession, and those that blow violently in storm, and those that scatter dispersingly, and those that separate decisively, and those that bring down a reminder—excusing or warning—indeed, what you are promised will occur!”* (77:1–7). Characterized by torrential, apocalyptic rhythm and an unyielding, hammering cadence, Sūrah al-Mursalāt is universally celebrated for its terrifying, ten-fold liturgical refrain: *“Woe, that Day, to the deniers! (*Waylun yawma'idhin li-l-mukadhdhibīn*)”*.

**The Gathering of the Appointed Day**

The historical context of al-Mursalāt reflects the hardened cynicism of the Quraysh, who persistently demanded that the promised divine judgment be brought immediately if it were real. Sūrah al-Mursalāt responds with cosmic finality: the delay in retribution is not divine hesitation, but the unfolding of an immovably fixed cosmic calendar—the *Day of Decision* (*Yawm al-Faṣl*). Verse 12 asks with chilling majesty: *“For what day was it postponed? For the Day of Decision! And what can make you know what is the Day of Decision? Woe, that Day, to the deniers!”*

**The Structural Architecture and the Ten Refrains**

The architecture of Sūrah al-Mursalāt is constructed as an ascending courtroom trial across four grand movements, punctuated by the ten repetitions of the refrain of woe:
1. The Cosmic Disintegration and the Appointed Hour (1–15): Swears by the winds, storms, and angelic messengers that the Promise is inevitable. It portrays the cosmic collapse: the stars extinguished, the sky rent asunder, the mountains blasted into dust, and the messengers brought to their appointed time for the Day of Decision (*Yawm al-Faṣl*).
2. The Evidence of History and Human Embryology (16–28):
   - *Historical Precedent*: Did We not destroy the former generations, and follow them with the later ones? Thus do We deal with the criminals! *Woe, that Day, to the deniers!*
   - *Biological Proof*: Did We not create you from a humble fluid (*mā'in mahīn*), placing it in a secure lodging (the womb) for a known determined measure? *“And We measured, and how excellent are the measurers! Woe, that Day, to the deniers!”*
3. The Ecology of the Earth and the Three-Pronged Shadow (29–40):
   - *Geological Mercy*: Did We not make the earth a container (*kifātā*) gathering the living and the dead, placing towering mountains upon it, and giving you sweet, fresh water to drink? *Woe, that Day, to the deniers!*
   - *The Reality of Saqar*: The deniers are commanded: *“Depart to that which you used to deny! Depart to a shadow of smoke having three columns, offering no cool shade and no protection from the blazing flame!”* It throws sparks as huge as fortress towers (*ka-l-qaṣr*), yellow as stampeding camels! *Woe, that Day, to the deniers!*
   - *The Day of Silence*: This is a Day they will not speak, nor will it be permitted for them to offer excuses. *Woe, that Day, to the deniers!*
4. The Bliss of the Righteous and the Refusal of Prostration (41–50): Contrasts the terror of Hell against the righteous in cool shades, flowing springs, and fruits of whatever they desire, told: *“Eat and drink in satisfaction for what you used to do; indeed, thus do We reward the doers of good!”* Yet immediately the warning strikes the wicked: *“Eat and enjoy yourselves a little; indeed, you are criminals!”* Verse 48 delivers the profound spiritual indictment of human arrogance: *“And when it is said to them, 'Bow down [in prayer]', they do not bow down! Woe, that Day, to the deniers!”* The chapter concludes with the ultimate existential challenge of verse 50: *“Then in what statement after this will they believe?”*

**The Refusal to Bow and the Day of Decision**

The supreme theological diagnosis of Sūrah al-Mursalāt is found in verse 48: *Wa-idhā qīla lahumu irkaʿū lā yarkaʿūn* ("And when it is said to them: 'Bow down in prayer', they do not bow down!"). Arrogance is the fatal sickness of the soul: the proud human being walks upon an earth designed as a cradle, drinks sweet water provided by clouds, was engineered from a drop of humble fluid, yet stubbornly refuses to bow his forehead before his Creator. Sūrah al-Mursalāt warns that the refusal to bow voluntarily in this world will lead inevitably to the terrifying silence of the Day of Decision, when excuses are terminated and reality reigns absolute."""

# -------------------------------------------------------------
# SURAH 78: AN-NABAʾ
# -------------------------------------------------------------
intros[78] = """**The Great News and the Trumpet of the Gathering**

An-Nabaʾ, "The Great News" or "The Tiding"—also widely designated in classical exegesis as *ʿAmma* (from its opening interrogative) or *Sūrat al-Muʿṣirāt*—is the seventy-eighth chapter of the Qur'an, comprising 40 verses of early Makkan revelation. It holds a monumental structural position in the sacred canon: it is the opening chapter of the thirtieth and final part (*Juz' ʿAmma*) of the Qur'an. It takes its name from verses 1–2: *“About what are they asking one another? About the Great News (*ʿani al-naba'i al-ʿaẓīm*)—that over which they are in disagreement!”* *Al-Naba' al-ʿAẓīm* is the monumental announcement of the Day of Resurrection, the prophethood of Muḥammad ﷺ, and the absolute reality of human accountability. With breathtaking majesty and relentless rhetorical power, Sūrah an-Nabaʾ takes the reader on a cosmic journey: from the stabilizing pegs of the mountain ranges and the solar furnace of the sun, to the blowing of the Trumpet, the opening of celestial portals, the boiling fluids of Hell, and the tragic cry of the condemned soul wishing it were mere dust.

**The Whispers in the Alleys of Makkah**

The historical context of an-Nabaʾ is the animated, skeptical buzz that gripped the alleys of Makkah whenever the Prophet ﷺ proclaimed the reality of the Final Judgment. The Qurayshi chieftains gathered in their clubs beside the Kaʿbah, whispering, debating, and laughing mockingly: *“Will we really be brought back to life after our bones are turned to dust? Is this man mad, or is he seeking prestige?”* Sūrah an-Nabaʾ descends to silence their frivolous chatter: *“Nay! They will soon know! Then, nay! They will soon know!”* (78:4–5). The sūrah makes it clear that the coming Judgment is not an open question for endless academic debate; it is an incoming, unshakeable cosmic reality that will overtake humanity like a roaring wave.

**The Structural Architecture and the Pegs of the Earth**

The architecture of Sūrah an-Nabaʾ moves across three magnificent movements:
1. The Nine Cosmic Proofs of Divine Mastery (6–16): Challenges the human observer to contemplate the physical engineering of the planet:
   - Did We not make the earth a resting place / cradle (*mihādā*)?
   - And the mountains as pegs / stakes (*awtādā*) stabilizing the continental crust?
   - And created you in pairs (*azwājā*)?
   - And made your sleep for rest (*subātā*)?
   - And made the night as a cloak / covering (*libāsā*)?
   - And made the day for livelihood (*maʿāshā*)?
   - And constructed above you seven strong heavens?
   - And placed therein a blazing, radiant lamp (the sun, *sirājan wahhājā*)?
   - And sent down from rain-clouds water pouring in abundance (*mā'an thajjājā*), to bring forth grain, vegetation, and luxuriant gardens entwined (*jannātin alfāfā*)?
2. The Day of Decision and the Opening of the Portals (17–30): Declares that the Day of Decision is an appointed time (*mīqātā*): the Day the Horn is blown and humanity arrives in surging crowds (*afwājā*); the sky opened until it becomes portals, and the mountains moved until they become a mirage (*sarābā*). It portrays *Jahannam* (Hell) lying in ambush (*mirṣādā*)—a home for the transgressors who will abide therein for endless ages (*aḥqābā*), tasting neither cool air nor drink except boiling water and dark purulence (*ḥamīman wa-ghassāqā*), a fitting recompense for those who expected no account and rejected divine signs with insolence.
3. The Gardens of Triumph and the Cry of the Dust (31–40): Contrasts the doom of the wicked against the radiant triumph of the righteous (*al-muttaqīn*): an attainment of supreme success (*mafāzā*)—orchards and grapevines, youthful companions of matched age, and full brimming cups, hearing no vain speech or falsehood. Verse 38 stages the awe-inspiring silence of the celestial court: *“The Day that the Spirit [Gabriel] and the angels will stand in rows, they will not speak except for one whom the Most Compassionate has permitted, and he will speak what is right.”* The chapter concludes with the chilling, immortal warning of verse 40: *“Indeed, We have warned you of a near punishment on the Day when a man will observe what his hands have put forward, and the disbeliever will cry: 'Oh, I wish that I were dust (*Yā laytanī kuntu turābā*)!'”*

**The Stakes of the Mountain and the Reality of Truth**

The central philosophical insight of Sūrah an-Nabaʾ is that the God Who engineered the mountains as deep pegs (*awtādā*) to stabilize the earth's crust, and Who ignited the sun as a cosmic furnace (*sirājan wahhājā*), has not created human moral consciousness to dissolve into nothingness. The same mathematical order that governs the rain-clouds and the celestial spheres governs the Day of Decision. The tragic irony of human denial is summarized in the final words of the sūrah: the arrogant denier who proudly strutted upon the earth will look upon his deeds on that Day and desperately wish that he had remained mere lifeless dust beneath the feet of beasts (*Yā laytanī kuntu turābā*). Sūrah an-Nabaʾ calls humanity to awaken to the Great News before that eternal regret is sealed."""

# -------------------------------------------------------------
# SURAH 79: AN-NĀZIʿĀT
# -------------------------------------------------------------
intros[79] = """**The Soul-Extractors and the Overwhelming Cataclysm**

An-Nāziʿāt, "The Soul-Extractors" or "Those Who Tear Out," is the seventy-ninth chapter of the Qur'an, comprising 46 verses of early Makkan revelation. It opens with five electrifying, mysterious oaths sworn by the specialized angelic forces that oversee human death and cosmic mechanics: *“By those [angels] who extract [the souls of the wicked] with violent tearing (*wa-l-nāziʿāti gharqā*), and those who draw out [the souls of the righteous] with gentle ease, and those who glide with effortless motion, and those who race with swift urgency, and those who arrange [every] divine affair!”* (79:1–5). Sūrah an-Nāziʿāt is an unsparing dramatic meditation on the boundary between mortality and the eternal world: contrasting the violent extraction of the arrogant tyrant's soul against the serene, gentle release of the believer's spirit, and staging the epic confrontation between Moses and the self-deified Pharaoh who proclaimed: *“I am your supreme Lord!”* (*Anā rabbukumu al-aʿlā*).

**The Arrogance of the Rotten Bones**

The historical climate of an-Nāziʿāt is marked by the mocking incredulity of the Quraysh, who rejected the possibility of bodily reconstruction after decomposition. Verses 10–12 preserve their words: *“They say: 'Will we indeed be returned to [our] former state [of life]? Even after we have become decayed, hollow bones?' They say: 'That, then, would be a losing return!'”* Sūrah an-Nāziʿāt answers this mockery by unveiling the sheer velocity of the divine decree: the Resurrection requires no prolonged engineering or laborious effort; it is merely a single, deafening cry or rebuke (*zajratun wāḥidah*), and behold, humanity is standing awake upon the white plain of the earth (*al-sāhirah*)!

**The Structural Symphony and the Overwhelming Disaster**

The architecture of Sūrah an-Nāziʿāt is organized across four dramatic movements:
1. The Angelic Extraction of Souls and the Quaking Day (1–14): Swears by the angelic extractors that the Day will shake: the first convulsion (*al-rājifah*) followed immediately by the second (*al-rādifah*), hearts trembling in terror on that Day, their eyes cast down in humiliation. It contrasts the mockers' words about decayed bones against the sudden reality of the single blast (*zajrah*).
2. The Paradigm of Tyranny: Moses and Pharaoh (15–26): Asks the Prophet with pastoral tenderness: *“Has there reached you the story of Moses?”* Recounts Moses summoned by his Lord in the sacred valley of Ṭuwā: *“Go to Pharaoh. Indeed, he has transgressed! And say to him: 'Would you like to purify yourself, and that I guide you to your Lord so you would fear [Him]?'”* Moses presented the greatest sign, but Pharaoh denied, disobeyed, turned his back in haste, gathered his magicians, and shouted to his people the supreme blasphemy: *“I am your supreme Lord (*Anā rabbukumu al-aʿlā*)!”* God seized him with the exemplary punishment of the Hereafter and the first life, sealing the narrative with the warning: *“Indeed, in that is a lesson for whoever would fear [Allah].”*
3. The Architecture of the Heavens and the Provision of the Earth (27–33): Challenges human conceit with the creation of the cosmos: *“Are you a more difficult creation or is the heaven? He constructed it; He raised its ceiling and proportioned it, darkened its night and brought forth its daylight!”* After that He spread out the earth, brought forth its water and pastures, and anchored the mountains firmly (*arsāhā*)—all as provision for you and your livestock.
4. The Great Overwhelming Disaster and the Question of the Hour (34–46): Delivers the terrifying climax: when there comes the *Overwhelming Cataclysm* (*al-Ṭāmmah al-Kubrā*), on that Day man will remember all that he strove for, and Hellfire will be displayed openly for all who see! It establishes the two ultimate destinies:
   - *The Transgressor* (37–39): As for him who transgressed and preferred the life of this world—indeed, Hellfire will be his refuge.
   - *The Mindful Soul* (40–41): *“And as for him who feared the standing before his Lord and restrained his soul from [unlawful] desire—then indeed, Paradise will be his refuge!”*
The chapter concludes with the cynical inquiry: *“They ask you, [O Muḥammad], about the Hour: 'When is its arrival?' In what are you to mention it? To your Lord is its finality.”* The Prophet is reminded that his only duty is to warn those who fear it, concluding with the breathtaking temporal perspective of verse 46: *“On the Day they see it, it will be as though they had not remained [in the world] except for an evening or a morning thereof (*ʿashiyyatan aw ḍuḥāhā*)!”*

**The Restraint of Desire: Nahā al-Nafsa ʿani al-Hawā**

The foundational spiritual thesis of Sūrah an-Nāziʿāt is contained in verse 40: *Wa-nahā al-nafsa ʿani al-hawā* ("And restrained his soul from unlawful desire"). The root of Pharaoh's tyranny—and the root of every human soul's destruction—is the deification of the ego: declaring *Anā rabbukumu al-aʿlā* ("I am my own supreme authority!"). In contrast, the gateway to Paradise is the courageous, vigilant mastery of one's own impulses in awe of standing before God. Sūrah an-Nāziʿāt teaches that when the Overwhelming Cataclysm (*al-Ṭāmmah al-Kubrā*) strikes, all the centuries of human worldly history will shrink into the blink of an eye—feeling like nothing more than a fleeting afternoon or its morning sunrise."""

# -------------------------------------------------------------
# SURAH 80: ʿABASA
# -------------------------------------------------------------
intros[80] = """**The Frown of the Prophet and the Blind Man's Sincerity**

ʿAbasa, "He Frowned," is the eightieth chapter of the Qur'an, comprising 42 verses of early Makkan revelation. It is universally famous for its dramatic, intimate opening: *“He frowned and turned away, because there came to him the blind man (*An jā'ahu al-aʿmā*)!”* (80:1–2). In prophetic history, this opening represents one of the most sublime, undeniable proofs of the divine origin of the Qur'an: it is a divine reprimand addressed directly to the Prophet Muḥammad ﷺ himself, recorded permanently in immutable scripture. Had the Prophet authored the Qur'an from his own ego or for political ambition, he would never have composed an immortal text publicly rebuking himself for a minor, inward facial expression of annoyance toward an impoverished blind follower! Sūrah ʿAbasa is the great egalitarian manifesto of Islam: shattering the worldly calculations of political expediency, establishing that the sincere soul seeking spiritual purification carries infinitely more value before God than all the wealthy oligarchs of the earth combined, and culminating in the terrifying eschatological day when every human being will flee from his own brother, mother, father, spouse, and children.

**The Blind Seeker and the Chieftains of Quraysh**

The historical occasion of Sūrah ʿAbasa is documented in authentic traditions in Jāmiʿ al-Tirmidhī (3331) and classical exegesis by ʿĀ'ishah and Ibn ʿAbbās. The Prophet ﷺ was deeply engaged in an intense, high-stakes dialogue with the top leaders of the Qurayshi aristocracy—including ʿUtbah ibn Rabīʿah, Shaybah, Abū Jahl, and Umayyah ibn Khalaf—desperately striving to convince them of Islam, knowing that their conversion would protect the vulnerable Muslims from persecution and transform Arabian society. In the midst of this delicate conversation, a poor, blind early Muslim named ʿAbdullāh ibn Umm Maktūm stumbled into the gathering. Unaware of who the Prophet was addressing, the blind man called out eagerly: *“O Messenger of Allah, teach me from that which Allah has taught you!”* Annoyed at the interruption and fearing the aristocratic chieftains would be disgusted by the presence of a blind beggar, the Prophet's brow furrowed in a brief, silent frown (*ʿabasa*) and he turned his shoulder away to continue his appeal to the elites. Revelation descended instantly from above the heavens: *“He frowned and turned away, because there came to him the blind man! But what would make you perceive, [O Muḥammad], that perhaps he might be purified, or be reminded and the reminder benefit him? As for he who considers himself free of need, to him you give attention—and not upon you is any blame if he does not purify himself! But as for he who came to you striving, while he fears [Allah], from him you are distracted! No! Indeed, these verses are a reminder!”* (80:1–11). The Prophet ﷺ internalized this divine correction so deeply that for the rest of his life, whenever he saw Ibn Umm Maktūm, he would spread his cloak on the ground for him, embrace him warmly, and say: *“Welcome to the one on whose account my Lord rebuked me!”*—and twice appointed the blind man as the acting governor of Madinah during military campaigns.

**The Structural Architecture and the Deafening Blast**

The architecture of Sūrah ʿAbasa unfolds across three distinct movements:
1. The Divine Reprimand and the Sacred Scrolls (1–16): Corrects the Prophet's priorities, establishes that divine revelation is recorded on honored, exalted, purified sheets (*ṣuḥufin mukarramah, marfūʿatin muṭahharah*), carried by the hands of noble, virtuous angelic scribes (*safarah, kirāmin bararah*).
2. The Ingratitude of Man and the Agricultural Canopy (17–32): Issues an anguished lament over human spiritual blindness: *“Destroyed is man; how ungrateful is he! From what thing did He create him? From a drop of semen He created him and proportioned him; then He made the path easy for him; then He causes him to die and provides a grave for him; then when He wills, He will resurrect him. No! Man has not yet accomplished what He commanded him!”* (80:17–23). It challenges human beings to look at their food: how God poured down water in torrents, split the soil in fissures, and produced grain, grapes, nutritious vegetation, olives, date palms, dense gardens of luxuriant growth, fruits, and fodder—all as provision for you and your livestock.
3. The Deafening Blast and the Severing of All Ties (33–42): Stages the arrival of the *Deafening Blast* (*al-Ṣākhkhah*): the Day when every social and biological bond of human kinship is violently severed:
   - *“The Day a man will flee from his brother,”*
   - *“And from his mother and his father,”*
   - *“And from his wife and his children!”*
   Verse 37 reveals the terrifying psychological reason for this abandonment: *“For every person among them, that Day, will be an affair sufficient to preoccupy him (*li-kulli imri'in minhum yawma'idhin sha'nun yughnīh*)!”* The chapter concludes by portraying the two eternal faces of humanity: radiant, laughing, joyful faces illuminated by divine grace (*wujūhun yawma'idhin musfirah, ḍāḥikatun mustabshirah*); and faces covered in dust, overtaken by black gloom (*tarhaquhā qatarah*)—the wicked, unrepentant deniers.

**The Eyes of the Heart and the Flight of Kinship**

The foundational philosophical and spiritual lesson of Sūrah ʿAbasa is that worldly sight is not spiritual vision. ʿAbdullāh ibn Umm Maktūm was physically blind, yet his heart was radiant with the light of faith and desire for purification; the Qurayshi chieftains possessed perfect eyesight, yet their hearts were blind and swollen with self-sufficiency (*istaghnā*). Sūrah ʿAbasa teaches that God judges human beings not by their social status, physical beauty, or political influence, but by the sincerity of their search for truth. By contrasting the blind man's devotion against the terrifying scene where mothers flee from their children on the Day of the Deafening Blast (*al-Ṣākhkhah*), Sūrah ʿAbasa reminds humanity that the only relationship that survives the wreck of time is the soul's relationship with its Creator."""

for ch in [73, 74, 75, 76, 77, 78, 79, 80]:
    insert_surah_intro(ch, intros[ch])
print("Batch 8 (73-80) inserted successfully.")
