import sys
sys.path.append(".")
from scripts.intro_utils import insert_surah_intro

intros = {}

# -------------------------------------------------------------
# SURAH 21: AL-ANBIYĀʾ
# -------------------------------------------------------------
intros[21] = """**The Assembly of the Prophets and the Approaching Reckoning**

Al-Anbiyāʾ, "The Prophets," is the twenty-first chapter of the Qur'an, comprising 112 verses of late-to-mid Makkan revelation. It takes its name from its glorious, panoramic assembly of sixteen named prophetic figures—along with Maryam—marching in a single, unbroken spiritual chain across verses 48–91. In classical hadith literature, Sūrah al-Anbiyāʾ is grouped alongside the earliest treasures of revelation: ʿAbdullāh ibn Masʿūd famously stated in Ṣaḥīḥ al-Bukhārī (4994) that *“Banī Isrā'īl (al-Isrāʾ), al-Kahf, Maryam, Ṭā-Hā, and al-Anbiyāʾ are among the ancient treasures (*min al-ʿitāq al-uwal*) and they are of my earliest acquisitions.”* Emerging from the intense intellectual clashes of the Makkan period, Sūrah al-Anbiyāʾ confronts human heedlessness with volcanic urgency: opening with the terrifying announcement that human reckoning has drawn dangerously near while mankind turns away in heedless play, and culminating in the magnificent declaration that the Prophet Muḥammad ﷺ is sent as nothing less than an all-encompassing mercy to all creation (*Raḥmatan li-l-ʿālamīn*, 21:107).

**The Slumber of Heedlessness and the Mockery of Truth**

The historical atmosphere of al-Anbiyāʾ is characterized by the frivolous cynicism of the Qurayshi elite. Whenever a new reminder from the Most Compassionate was recited, they listened to it while amusing themselves, whispering conspiratorially: *“Is this man anything more than a human being like yourselves? Will you then surrender to sorcery with your eyes wide open?”* (21:2–3). They dismissed the Qur'an as muddled dreams, invented poetry, or fabrications, demanding sensational physical miracles like those granted to the ancient messengers. Sūrah al-Anbiyāʾ shatters this frivolous attitude. It reminds the audience that the cosmos was not created as an idle game or sport (*wa-mā khalaqnā al-samā'a wa-l-arḍa wa-mā baynahumā lāʿibīn*, 21:16), but with absolute, terrifying purpose. Truth is an active, crushing reality: *“Nay, We hurl the truth against falsehood, and it smashes its head, and behold, it vanishes!”* (21:18).

**The Grand Prophetic Procession and Thematic Arc**

The architecture of Sūrah al-Anbiyāʾ moves from cosmic physics to prophetic history, and from the crucible of suffering to eschatological fulfillment. The opening movement (1–47) establishes the proximity of the Judgment, demonstrates the absurdity of polytheism (arguing that had there been gods other than Allah in heaven and earth, both would have been corrupted and ruined, 21:22), and presents profound cosmic signs: the heavens and earth joined together before being violently split apart, all living matter created from water (21:30), firm mountains stabilizing the crust, and every celestial sphere swimming in its appointed orbit (*kullun fī falakin yasbaḥūn*). The second movement (48–91) unfolds the glorious roll-call of the prophets, illustrating how each responded to intense existential crises: Moses and Aaron receiving the Criterion (*al-Furqān*); Abraham smashing the idols of his people, surviving the raging furnace transformed by divine command into coolness and peace (*kūnī bardan wa-salāmā*, 21:69); Isaac and Jacob gifted as leaders guiding by divine command; Lot delivered from the vile city; Noah saved from the great distress while his mockers drowned; David and Solomon gifted with wisdom, understanding the speech of birds and winds, and the mountains glorifying God with David; Job (*Ayyūb*) calling out in the depths of disease and poverty: *“Adversity has touched me, and You are the Most Merciful of the merciful,”* whereupon his health and family were restored; Ishmael, Idrīs, and Dhū al-Kifl praised for unyielding patience; Jonah (*Dhū al-Nūn*) crying out from the triple darkness of the night, the sea, and the belly of the whale: *“There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers,”* an immortal prayer guaranteed to deliver believers from distress (21:87); Zechariah crying out in loneliness, gifted John; and Maryam who guarded her chastity, into whom the divine spirit was breathed. The third movement (92–112) unites all these diverse messengers into a single spiritual fraternity: *“Indeed, this community of yours is one single community, and I am your Lord, so worship Me”* (21:92). It warns of the breaching of Gog and Magog (*Ya'jūj wa-Ma'jūj*), describes the sky being rolled up on the Last Day like a scribe rolling up a scroll, confirms that the righteous servants shall inherit the earth (21:105), and closes with the universal prophetic charter: *“And We have not sent you, [O Muḥammad], except as a mercy to the worlds”* (21:107).

**The Unity of the Prophetic Mission**

The core theological argument of Sūrah al-Anbiyāʾ is the indivisible unity of divine guidance. Across millennia, geographical divides, and varied trials, every prophet walked the identical path: calling humanity to *Tawḥīd*, enduring the mockery of their contemporaries, experiencing extreme human vulnerability, turning to God with desperate prayer, and finding miraculous deliverance through divine grace. Prophethood is not an ancient fairy tale; it is the living proof that God does not abandon humanity to the chaos of heedlessness. By framing Muḥammad ﷺ as the universal culmination of this mercy, al-Anbiyāʾ assures the believer that no furnace is too hot for God's coolness, no whale's belly is too dark for God's light, and no wound is too deep for God's healing."""

# -------------------------------------------------------------
# SURAH 22: AL-ḤAJJ
# -------------------------------------------------------------
intros[22] = """**The Cosmic Tremor and the Universal Gathering**

Al-Ḥajj, "The Pilgrimage," is the twenty-second chapter of the Qur'an, comprising 78 verses. It occupies a unique, hybrid status in Qur'anic chronology: classical authorities, including al-Suyūṭī and Ibn ʿAbbās, note that it contains verses revealed in Makkah, verses revealed in Madinah, verses revealed during travel, verses revealed during war, and verses revealed in peace. It takes its name from verses 26–37, which present the immortal Abrahamic proclamation of the annual pilgrimage to the Ancient House (*al-Bayt al-ʿAtīq*): *“And proclaim to the people the Ḥajj; they will come to you on foot and on every lean camel; they will come from every distant pass”* (22:27). Sūrah al-Ḥajj is also distinguished liturgically as containing two distinct verses of prostration (*sajdat al-tilāwah*, verses 18 and 77), highlighting its intense devotional demand. Bridging the twilight of Makkan persecution with the dawn of Medinan political independence, the sūrah conjoins the physical pilgrimage of the body with the ultimate eschatological migration of all human souls to the Divine Court.

**The Threshold of Migration and the Permission to Fight**

The historical axis of Sūrah al-Ḥajj is located at the critical pivot point of the *Hijrah* (approx. 622 CE). For thirteen years in Makkah, the believers had endured physical beatings, economic boycott, confiscation of property, and assassination attempts without being permitted to raise a hand in self-defense. In Sūrah al-Ḥajj, the historic turning point arrives with verse 39—the first verse in the Qur'an granting the oppressed permission to engage in armed defensive struggle: *“Permission [to fight] has been given to those who are being fought, because they were wronged. And indeed, Allah is competent to give them victory.”* Verse 40 articulates the profound philosophy of religious liberty underpinning this permission: had God not checked one group of people by means of another, monasteries, churches, synagogues, and mosques—sanctuaries wherein the Name of God is abundantly remembered—would have been utterly demolished. Armed resistance is thus sanctified not for imperial conquest or forced conversion, but as an indispensable shield to protect the universal human right to worship.

**The Structural Architecture of the Pilgrimage**

The architecture of Sūrah al-Ḥajj moves from apocalyptic terror to biological embryology, and from Abrahamic ritual to the defense of sacred spaces. The opening movement (1–25) strikes with apocalyptic force, warning humanity of the terrifying earthquake of the Final Hour (*Zalzalat al-Sāʿah*), which will cause nursing mothers to forget their infants and pregnant women to miscarry from sheer terror. It establishes the reality of resurrection through two observable proofs: the intricate stages of human embryological development in the womb (22:5), and the barren, dead earth that stirs, swells, and brings forth pairs of beautiful growth when touched by rain. The second movement (26–38) transports the reader to Makkah: Abraham purifying the House from idolatry and summoning mankind to the pilgrimage. It details the sacred rites: the slaughter of sacrificial livestock, feeding the impoverished and destitute, fulfilling vows, circumambulating the Ancient House, and honoring the symbols of God (*shaʿā'ir Allāh*), concluding with the famous spiritual maxim: *“Their meat will not reach Allah, nor will their blood, but what reaches Him is piety (*taqwā*) from you”* (22:37). The third movement (39–57) articulates the charter of defensive warfare, reviews the ruined dwellings of past deniers, and consoles the Prophet against the whisperings of Satan, affirming that God abolishes satanic interpolations and confirms His clear signs. The fourth movement (58–78) contrasts the majesty of divine creation—the ships gliding upon the oceans, the sky held from falling upon the earth except by divine leave—against the pathetic impotence of false gods in the famous parable of the fly: *“O people, an example is presented, so listen to it! Indeed, those you invoke beside Allah will never create a fly, even if they gathered together for that purpose. And if the fly should steal away from them a thing, they could not recover it from him. Weak are the seeker and the sought!”* (22:73). The chapter concludes (77–78) with the grand summons to the believers: to bow, prostrate, worship their Lord, and strive for Allah with the striving due to Him, reminding them: *“He has chosen you and has not placed upon you in the religion any difficulty—the religion of your father Abraham. He named you 'Muslims' before and in this [scripture].”*

**The Pilgrimage as an Eschatological Rehearsal**

The profound philosophical thesis of Sūrah al-Ḥajj is that the physical pilgrimage to Makkah is a live, earthly rehearsal for the Day of Resurrection. Just as the pilgrim strips away all markers of class, nationality, and wealth, donning two simple white unstitched cloths to stand among millions of equals upon the plain of ʿArafāt, so too will all humanity be stripped of worldly illusions to stand before the Sovereign Lord. By linking the sacred rituals of sacrifice, circumambulation, and self-restraint to the universal struggle for social justice, al-Ḥajj teaches that true worship transforms the human soul into a protector of the vulnerable and an unyielding servant of peace."""

# -------------------------------------------------------------
# SURAH 23: AL-MUʾMINŪN
# -------------------------------------------------------------
intros[23] = """**The Blueprint of Spiritual Prosperity and the Throne of Grace**

Al-Muʾminūn, "The Believers," is the twenty-third chapter of the Qur'an, comprising 118 verses of mid-to-late Makkan revelation. It derives its title from its majestic opening proclamation: *“Certainly, the believers have succeeded (*qad aflaḥa al-mu'minūn*)”* (23:1). In prophetic tradition, the opening ten verses of this sūrah are celebrated as the definitive portrait of spiritual felicity: ʿUmar ibn al-Khaṭṭāb reported in Jāmiʿ al-Tirmidhī (3173) that when revelation descended upon the Prophet ﷺ, a sound like the buzzing of bees was heard near his face, and after a moment of profound ecstasy, he turned to the Companions and recited these opening verses, stating: *“Ten verses have been revealed to me; whoever establishes them will enter Paradise.”* Coming at a time when the early Muslims in Makkah were socially ostracized, economically marginalized, and physically threatened, Sūrah al-Muʾminūn performs a radical transvaluation of values: it declares that true success (*falāḥ*) is not measured by pagan wealth, tribal lineage, or political dominion, but by the cultivation of inward humility in prayer, moral purity, sexual integrity, fidelity to trusts, and steadfastness upon truth.

**The Illusion of Pagan Prosperity**

The historical context of Sūrah al-Muʾminūn was marked by the boastful arrogance of the Qurayshi aristocracy. The chieftains looked down upon the Prophet's early followers—slaves like Bilāl, impoverished youths like ʿAmmār, and disenfranchised outcasts—mocking that if their new religion possessed any value, the affluent elites would have been the first to receive it. Sūrah al-Muʾminūn addresses this psychological confrontation directly: it warns the wealthy deniers not to imagine that their abundant wealth and children are a sign of divine favor or a hastening of good (*“Do they think that what We extend to them of wealth and children is because We hasten for them good things? Nay, they perceive not!”*, 23:55–56). True ruin lies in complacency; worldly riches without spiritual consciousness are merely a slow divine testing (*istidrāj*) that leads to catastrophic bankruptcy on the Day of Judgment.

**The Structural Anatomy of the Sūrah**

The architecture of Sūrah al-Muʾminūn is organized around four clear thematic movements. The opening movement (1–22) establishes the six ethical pillars of the true believer: inward humility and awe in prayer (*khushūʿ*), turning away from futile and vain speech (*laghw*), active purification through zakat and charity, guarding sexual modesty except within lawful marital bonds, honoring trusts and covenants, and punctually guarding the regular prayers, promising that such souls shall inherit *al-Firdaws* (the highest terrace of Paradise). This ethical code is immediately grounded in the biological miracle of human embryogenesis: the clay extraction, the drop of semen (*nuṭfah*), the clinging clot (*ʿalaqah*), the lump of flesh (*muḍghah*), the clothing of bones with flesh, and the miraculous fashioning into another creation, concluding: *“So blessed is Allah, the best of creators”* (23:14), followed by the cosmic signs of the seven layered heavens, life-giving rain, and the blessed olive tree that springs from Mount Sinai producing oil and seasoning for the eaters. The second movement (23–50) reviews sacred history through the lens of moral confrontation: Noah building the Ark under the mocking eyes of the chieftains who branded him an ambitious social climber; the successive generation destroyed by the screaming blast (*al-ṣayḥah*); Moses and Aaron confronting Pharaoh's arrogant refusal; and the universal dietary and moral command given to all messengers: *“O messengers, eat from the good things and work righteousness”* (23:51). The third movement (51–92) exposes the splintering of humanity into sectarian factions, each rejoicing in what it possesses, contrasts the terrified pleas of the dying sinner against the serenity of the mindful, and stages the dramatic reality of the *Barzakh*—the impenetrable spiritual barrier behind deceased souls preventing them from returning to earth to rectify their wasted lives (23:99–100). The closing movement (93–118) provides the Prophet with defensive prayers against demonic whispers (*“My Lord, I seek refuge in You from the incitements of the devils,”* 23:97), portrays the horror of the deniers whose faces are scorched in Hell while the believers are rewarded for their patient endurance, and asks humanity the penetrating existential question of verse 115: *“Did you then think that We created you without purpose, and that you would not be returned to Us?”*, sealing the chapter with the glorious prayer: *“My Lord, forgive and have mercy, and You are the best of the merciful.”*

**The Interior Architecture of Khushūʿ**

The foundational insight of Sūrah al-Muʾminūn is that ethical action flows from the interior sanctuary of *Khushūʿ*—the quiet trembling, focused awe of the heart standing conscious before its Creator. When prayer becomes a mechanical, hurried exterior ritual, moral life degrades; but when the soul learns to stand in stillness before the Lord of the Throne, worldly distractions (*laghw*) lose their grip, trusts are honored instinctively, and sexual desires are disciplined by sacred limits. Sūrah al-Muʾminūn offers a comprehensive roadmap of human flourishing: beginning with the whisper of the heart in prayer and culminating in the eternal inheritance of Paradise."""

# -------------------------------------------------------------
# SURAH 24: AN-NŪR
# -------------------------------------------------------------
intros[24] = """**The Architecture of Light and the Protection of the Sanctity of the Home**

An-Nūr, "The Light," is the twenty-fourth chapter of the Qur'an, comprising 64 verses of mature Medinan revelation. It takes its name from verse 35—universally celebrated as *Āyat al-Nūr* (The Verse of Light)—one of the most dazzling, profound mystical passages in all of sacred scripture, where God compares His light in the cosmos and in the human heart to a radiant lamp enclosed in crystalline glass, suspended within an arched niche, fueled by the oil of a blessed, unearthly olive tree that gleams even without the touch of fire: *“Light upon light! Allah guides to His light whom He wills.”* Uniquely, the chapter opens with an authoritative legislative preamble: *“[This is] a chapter which We have sent down and made obligatory, and We have revealed therein clear signs that you may remember”* (24:1). Revealing the social engineering of the Medinan commonwealth, Sūrah an-Nūr is the supreme charter of domestic sanctity, sexual ethics, social modesty, and the protection of female reputation, demonstrating that the transcendent Divine Light can only illuminate a society whose homes and public spaces are safeguarded from the darkness of slander, indecency, and moral decay.

**The Slander Against ʿĀ'ishah and the Crisis of the Commonwealth**

The historical furnace out of which Sūrah an-Nūr descended was the traumatic crisis of *Ḥadīth al-Ifk* (The Event of the Slander) in 5 or 6 AH, following the expedition of Banū al-Muṣṭaliq. ʿĀ'ishah, the young wife of the Prophet ﷺ and daughter of Abū Bakr, was accidentally left behind in the desert when her camel litter was carried away without anyone noticing her light weight, after she had stepped out to search for a dropped necklace. Found hours later by a young Companion, Ṣafwān ibn al-Muʿaṭṭal, who escorted her back to Madinah on his camel while walking respectfully ahead of her, their innocent arrival was seized upon by ʿAbdullāh ibn Ubayy and the hypocrites to fabricate a vile rumor of adultery. The poison circulated through the streets of Madinah for an entire month: the Prophet was weighed down with agonizing sorrow, ʿĀ'ishah fell grievously ill from grief, and even sincere Companions like Ḥassān ibn Thābit and Ḥamnah bint Jaḥsh were ensnared in the gossip. The community was on the brink of civil fracture. When all earthly avenues of verification were exhausted, verses 11–26 of Sūrah an-Nūr descended from above the seven heavens: passionately clearing ʿĀ'ishah of all false charges, severely reprimanding the community for not instantly rejecting the rumor with righteous indignation (*“Why, when you heard it, did you not say: 'It is not for us to speak of this! Exalted are You [O Allah]; this is a monstrous slander!'”*, 24:16), and legislating the penal sentence for false accusations against chaste women (*qadhf*).

**The Structural Modulation from Law to Mystical Illumination**

The architecture of Sūrah an-Nūr is a breathtaking synthesis of exacting penal law, domestic etiquette, and sublime mystical metaphysics. The opening movement (1–26) codifies the legal penalties for fornication (*zinā*), establishes the mandatory requirement of four eyewitnesses for allegations of adultery to protect society from reckless character assassination, institutes the procedure of mutual swearing (*liʿān*) between spouses, details the divine exoneration of ʿĀ'ishah, and commands Abū Bakr to forgive and continue supporting his relative who participated in the slander: *“Do you not love that Allah should forgive you? And Allah is Forgiving and Merciful”* (24:22). The second movement (27–34) establishes the sanctity of private life: mandating that believers never enter homes other than their own without seeking permission (*isti'nās*) and greeting the occupants with peace, commanding believing men and women to lower their gazes and guard their modesty, legislating the outer garment (*khimār*) over the bosom, and commanding the community to facilitate marriages for single men, women, and righteous slaves, assuring that God will enrich them from His bounty. The third movement (35–45) forms the luminous, metaphysical heart of the sūrah: the Verse of Light (24:35), the description of the mosques where the light is nurtured by men whom neither trade nor sale distracts from the remembrance of God, contrasted against the twin parables of disbelief—the mirage in the desert that the thirsty traveler imagines to be water until he reaches it and finds God there to pay him his account, and the terrifying darkness in a fathomless ocean, where wave rides upon wave beneath black clouds, such that if a man stretches out his hand he can barely see it: *“And he to whom Allah has not granted light has no light!”* (24:40). The fourth movement (46–64) examines civic obedience: exposing the hypocrisy of those who demand secular arbitration when they are guilty but rush to divine courts when they have a claim, commanding reverence and respect for the assembly of the Messenger ﷺ, and concluding with the sovereign reminder: *“Unquestionably, to Allah belongs whatever is in the heavens and the earth.”*

**The Social Sanctuary for the Divine Light**

The profound philosophical genius of Sūrah an-Nūr is that spiritual illumination cannot exist in a moral vacuum. The metaphysical Light of God (*Nūr Allāh*) does not descend into houses polluted by voyeurism, slander, and betrayal; it shines in homes whose thresholds are guarded by permission, whose eyes are lowered in modesty, whose tongues are disciplined against gossip, and whose hearts are purified by charity and prayer. By binding the strict protection of female dignity and privacy directly to the highest mystical contemplation of God's presence, Sūrah an-Nūr demonstrates that a healthy, dignified, and pure social order is the essential terrestrial vessel capable of holding the Light of Heaven."""

# -------------------------------------------------------------
# SURAH 25: AL-FURQĀN
# -------------------------------------------------------------
intros[25] = """**The Standard of Discrimination and the Servants of the Merciful**

Al-Furqān, "The Criterion," is the twenty-fifth chapter of the Qur'an, comprising 77 verses of mature Makkan revelation. It takes its name from the profound opening verse: *“Blessed is He who sent down the Criterion (*al-Furqān*) upon His servant that he may be to the worlds a warner”* (25:1). *Al-Furqān* is one of the most significant titles of the sacred scripture, derived from the Arabic root *f-r-q*, signifying that which cuts, divides, and decisively discriminates between truth and falsehood, light and darkness, justice and tyranny, and authentic worship and hollow superstition. Positioned as the majestic portal to the mid-Makkan theological discourse, Sūrah al-Furqān addresses the cynical intellectual objections raised by the pagan elite against the human nature of the Prophet and the oral descent of scripture, culminating in one of the most breathtaking moral descriptions in all of world literature: the portrait of the *ʿIbād al-Raḥmān* (The Servants of the Most Compassionate) in verses 63–77.

**The Skeptic's Contempt for a Human Prophet**

The historical setting of al-Furqān reflects the stubborn elitism of the Quraysh, who rejected Muḥammad ﷺ precisely because of his ordinary, unpretentious humanity. They scoffed: *“What is this messenger that eats food and walks through the marketplaces? Why was there not sent down to him an angel to be a warner with him? Or why is not a treasure dropped down to him, or why does he not have a garden from which he may eat?”* (25:7–8). Furthermore, they complained about the pedagogical method of revelation itself, asking why the Qur'an was not revealed as a single, monumental leather-bound codex all at once, rather than piecemeal across years (25:32). Sūrah al-Furqān confronts these objections with sublime philosophical dignity. It explains that all prior messengers—from Noah to Abraham and Moses—were mortal human beings who ate food, walked the streets, and shared the human condition. The piecemeal descent of revelation (*tanzīl*) was not a defect, but a deliberate divine therapy: designed to strengthen the Prophet's heart progressively against grief (*li-nuthabbita bihī fu'ādak*, 25:32) and to provide living, contextual answers to every trial as it unfolded.

**The Structural Symphony of the Criterion**

The architecture of Sūrah al-Furqān unfolds across three magnificent movements. The opening movement (1–34) exalts the unshared sovereignty of God Who has taken no son and possesses no partner in dominion, refutes the pagan claim that the Qur'an is an ancient fable dictated by others, and portrays the terrifying regret of the oppressor on the Day of Judgment: biting his own hands in despair and crying: *“Oh, I wish I had taken with the Messenger a way! Oh, woe to me! I wish I had not taken that person as an intimate friend! He led me astray from the message after it had come to me”* (25:27–29). It records the poignant complaint of the Messenger on that Day: *“O my Lord, indeed my people took this Qur'an as a thing abandoned (*mahjūrā*)”* (25:30). The second movement (35–62) reviews the tragic historical fate of past civilizations who treated truth as a joke: the people of Moses, the people of Noah drowned in the flood, the giants of ʿĀd and Thamūd, the dwellers of al-Rass, and the ruined cities of Sodom showered with stones. It presents cosmic signs: the elongation of the shadow, the night as a garment, sleep as rest, winds carrying good tidings before rain, and the miraculous oceanic barrier: two seas meeting side by side—one fresh and sweet, the other salty and bitter—separated by an impassable barrier (*barzakh*) and a partition that cannot be breached (25:53). The third movement (63–77) forms the radiant moral climax of the sūrah, detailing the twelve virtues of the *ʿIbād al-Raḥmān* (Servants of the Merciful): those who walk upon the earth with humility; who, when addressed by the ignorant, reply gently with words of peace (*qālū salāmā*); who spend the night prostrating and standing before their Lord; who beg for deliverance from the punishment of Hell; who are neither extravagant nor tight-fisted in spending, maintaining a noble balance; who never invoke partners with God, murder, or commit adultery; who never bear false witness; and who pray the immortal family prayer: *“Our Lord, grant us from among our spouses and offspring comfort to our eyes and make us a leader for the righteous”* (25:74). The sūrah concludes (77) by stripping away human self-importance: *“Say, 'My Lord would not care for you were it not for your prayer/supplication!'”*

**The Walking Manifestation of the Criterion**

The profound philosophical argument of Sūrah al-Furqān is that the ultimate proof of the divine origin of the Qur'an is not merely its linguistic majesty, but the kind of human being it produces. The Criterion is not just a theoretical book; it is embodied in the *ʿIbād al-Raḥmān*—souls who navigate an arrogant, noisy, and hostile world with profound dignity, gentleness, and mercy. While the tyrants boast of their power, the Servants of the Merciful walk lightly upon the earth, extinguish insults with prayers of peace, guard the night in tears of devotion, and transform their households into sanctuaries of righteousness. Sūrah al-Furqān proves that true human greatness consists not in dominating others, but in mastering oneself in the service of the All-Merciful."""

for ch in [21, 22, 23, 24, 25]:
    insert_surah_intro(ch, intros[ch])
print("Batch 3 (Part A: 21-25) inserted successfully.")
