import sys
sys.path.append(".")
from scripts.intro_utils import insert_surah_intro

intros = {}

# -------------------------------------------------------------
# SURAH 56: AL-WĀQIʿAH
# -------------------------------------------------------------
intros[56] = """**The Inevitable Cataclysm and the Three Tiers of Destiny**

Al-Wāqiʿah, "The Inevitable Event," is the fifty-sixth chapter of the Qur'an, comprising 96 verses of early Makkan revelation. It takes its name from its opening verse: *“When the Inevitable Event occurs (*Idhā waqaʿati al-wāqiʿah*), there is, at its occurrence, no denial!”* (56:1–2). In prophetic tradition, Sūrah al-Wāqiʿah holds a celebrated station as a divine protection against material and spiritual poverty: ʿAbdullāh ibn Masʿūd reported that the Messenger of Allah ﷺ said: *“Whoever recites Sūrah al-Wāqiʿah every night will never be afflicted by poverty (*faqr*)”* (Shuʿab al-Īmān by al-Bayhaqī 2498), and Ibn Masʿūd famously commanded his daughters to recite it every evening. With pulsating, dramatic urgency, Sūrah al-Wāqiʿah describes the total dismantling of the terrestrial order—the earth violently shaken and the mountains crumbled into scattered dust—and establishes the ultimate tripartite division of humanity into three eternal categories: *Al-Sābiqūn* (The Foremost in Faith), *Aṣḥāb al-Yamīn* (The Companions of the Right Hand), and *Aṣḥāb al-Shimāl* (The Companions of the Left Hand).

**The Reversal of Earthly Hierarchies**

The historical and existential setting of al-Wāqiʿah is the shocking, revolutionary reversal of human status that occurs at the threshold of the Hereafter. Verse 3 defines the event in two words: *Khāfiḍatun Rāfiʿah* ("Abasing [some] and exalting [others]"). In the worldly city of Makkah, social rank, aristocratic pride, and wealth elevated corrupt oligarchs while marginalizing righteous believers and impoverished slaves. Sūrah al-Wāqiʿah announces that the Day of Judgment will violently invert this false hierarchy: casting down the mighty tyrants into the lowest depths of humiliation, and raising the humble, sincere believers to thrones of eternal majesty. The sūrah confronts the stubborn deniers who mocked resurrection—asking incredulously: *“When we have died and become dust and bones, will we indeed be resurrected? And our forefathers of old?”* (56:47–48)—demonstrating that the God who engineered human life from a drop of fluid can effortlessly reconstitute human consciousness.

**The Structural Anatomy and the Threefold Assembly**

The architecture of Sūrah al-Wāqiʿah is built around four symmetrical movements:
1. The Cataclysm and the Tripartite Division (1–10): The earth shaken, mountains pulverized, and humanity divided into three groups: the Companions of the Right, the Companions of the Left, and the Foremost (*al-Sābiqūn al-Sābiqūn*).
2. The Rewards of the Two Righteous Tiers (11–40):
   - *Al-Sābiqūn* (11–26): The elite souls brought nearest to God in the Gardens of Pleasure, a multitude from the early generations and a few from later times; reclining on thrones woven with gold and precious stones, served by immortal youths with chalices of flowing wine causing no headache, with flesh of fowl they desire, companions with large beautiful eyes like hidden pearls (*ka-amthāli al-lu'lu'i al-maknūn*), hearing no vain speech or sinful talk, only the serene greeting: *“Salām! Salām!”*
   - *Aṣḥāb al-Yamīn* (27–40): The Companions of the Right in thornless lote trees, banana trees layered with fruit, extended shade, constantly flowing water, and abundant fruit never withheld, a multitude from the early and later generations.
3. The Torment of the Left and the Four Cosmic Questions (41–74):
   - *Aṣḥāb al-Shimāl* (41–56): Scorched by scorching winds and boiling water, in shadows of black smoke neither cool nor noble, forced to eat from the bitter tree of Zaqqūm, filling their bellies and drinking on top of it scalding water like thirsty camels (*shurba al-hīm*).
   - The Four Existential Interrogations (57–74): Did you create the human sperm-drop or are We the Creators? Did you plant the seed in the soil or do We cause it to grow? Did you send down the water from the rain-clouds or did We send it? Did you produce the wood of the fire or did We make it a reminder and a provision for travelers? Each question demands the response of verse 74: *“So exalt the name of your Lord, the Most Great (*Fa-sabbiḥ bi-ismi Rabbika al-ʿAẓīm*)!”*
4. The Oath of the Stars and the Dying Soul (75–96): A colossal oath sworn by the setting-places of the stars (*bi-mawāqiʿi al-nujūm*): that this is an honorable Qur'an in a well-guarded Book, touched only by the purified angels. It portrays the terrifying, intimate scene of the dying human soul when the breath reaches the collarbone (*al-ḥulqūm*), and family members stand by watching helplessly: *“And We are closer to him than you, but you do not see!”* (56:85). The sūrah concludes by confirming the three destinies, sealing the discourse with the final, sublime doxology: *“Indeed, this is the absolute truth of certainty! So exalt the name of your Lord, the Most Great!”*

**The Foremost in Faith: Al-Sābiqūn**

The supreme spiritual insight of Sūrah al-Wāqiʿah is the distinction between ordinary salvation (*Aṣḥāb al-Yamīn*) and absolute spiritual excellence (*Al-Sābiqūn*). The Companions of the Right are those who fulfilled the minimum obligations and avoided major sins; but the Foremost are those who ran ahead of humanity in every arena of self-sacrifice, knowledge, and love of God. They are the souls who established their worship in the dark watches of the night, spent their wealth before victory was guaranteed, and gave their lives for truth. Sūrah al-Wāqiʿah calls the believer to refuse moral mediocrity, to strive to be among the *Sābiqūn*, and to keep the reality of the dying breath perpetually before one's eyes."""

# -------------------------------------------------------------
# SURAH 57: AL-ḤADĪD
# -------------------------------------------------------------
intros[57] = """**The Miracle of Iron and the Loan to the Sovereign God**

Al-Ḥadīd, "The Iron," is the fifty-seventh chapter of the Qur'an, comprising 29 verses of early-to-mid Medinan revelation. It takes its name from verse 25, which delivers a profound geological, technological, and metaphysical revelation: *“And We sent down iron (*wa-anzalnā al-ḥadīda*), wherein is great military might and benefits for mankind, and so that Allah may make evident who supports Him and His messengers unseen. Indeed, Allah is Powerful and Exalted in Might.”* Classical and modern commentators note the precise wording *anzalnā* ("We sent down"): modern astrophysics has confirmed that the heavy element iron was not formed within the primordial earth, but was synthesized in the cores of exploding ancient supernovas and literally "sent down" to the cooling planet through meteoric bombardment! Positioned at the exact mathematical center of the Qur'anic codex, Sūrah al-Ḥadīd opens the sequence of the five *Musabbiḥāt* chapters (Sūrahs 57, 59, 61, 62, 64) that begin with the cosmic glorification of God. It is a monumental treatise on the mobilization of wealth and conviction, asking humanity the searching question: *“Who is it that will offer Allah a goodly loan (*qarḍan ḥasanan*) so that He will multiply it for him and grant him a noble reward?”* (57:11).

**The Hardening of Hearts and the Test of Spending**

The historical context of al-Ḥadīd reflects the consolidation of the Medinan community around 4 to 6 AH. The believers had endured warfare, migration, and economic hardship, yet as the community expanded and material conditions stabilized, the danger of spiritual complacency, consumerism, and the cooling of devotional fervor began to threaten the soul of the community. Sūrah al-Ḥadīd intervened with urgent pastoral power in verse 16: *“Has the time not come for those who have believed that their hearts should become humbly submissive at the remembrance of Allah and what has come down of the truth, and that they should not be like those who were given the Scripture before, and a long period passed over them, so their hearts hardened; and many of them are corrupt?”* The sūrah warns the Muslims not to repeat the tragic spiritual trajectory of prior scriptural communities, whose faith ossified into dry ritualism.

**The Structural Modulation and the Wall Between Believers and Hypocrites**

The architecture of Sūrah al-Ḥadīd moves across four distinct movements:
1. The Metaphysical Prologue (1–6): All that is in the heavens and earth glorifies Allah, the Exalted in Might, the Wise. Verse 3 articulates the sublime quartet of Divine Attributes: *“He is the First (*al-Awwal*) and the Last (*al-Ākhir*), the Ascendant (*al-Ẓāhir*) and the Intimate (*al-Bāṭin*), and He is, of all things, Knowing.”* He creates the cosmos, knows what enters the earth and what emerges from it, what descends from heaven and what ascends into it, and He is with you wherever you are (*wa-huwa maʿakum ayna mā kuntum*).
2. The Challenge of Spending and the Bridge of Light (7–15): Commanding belief and spending from that over which God has made humanity temporary trustees (*mustakhlafīna fīh*). It distinguishes between those who spent and fought before the conquest of Makkah and those who spent after, confirming the superior rank of the early sacrificers. It stages the terrifying scene of the Day of Judgment: believing men and women running across the bridge of the Hereafter with their radiant light gleaming before them and on their right hands, while the hypocrites cry out in pitch-black darkness: *“Wait for us that we may acquire some of your light!”* They are told to turn back, and a towering wall with a locked gate is dropped between them: on the inside is mercy, and on the outside is torment.
3. The Softening of Hearts and the Parable of Worldly Life (16–24): The piercing call to soften the heart before the remembrance of God, illustrated by the dead earth revived with spring rain. Verse 20 delivers the definitive Qur'anic diagnosis of worldly life: play, diversion, adornment, boasting among yourselves, and competition in increase of wealth and children—compared to a lush rain that delights the cultivators, then withers, turns yellow, and becomes dry chaff. The believers are commanded to race toward forgiveness and a Paradise as vast as the heavens and earth.
4. Iron, Apostles, and Monasticism (25–29): The descent of the Messengers with clear proofs, the Scripture, and the Balance (*al-mīzān*) so that humanity may uphold justice, conjoined with the descent of Iron (*al-ḥadīd*). It reviews Noah and Abraham, mentions Jesus who was granted the Gospel and whose followers had compassion and mercy placed in their hearts, while noting that monasticism (*rahbāniyyah*) was an ascetic innovation which they failed to uphold with its true observance. The sūrah concludes by calling the believers to mindfulness and faith in His Messenger, promising them a double portion of His mercy, a radiant light by which they will walk, and forgiveness, for *“grace is in the Hand of Allah; He gives it to whom He wills.”*

**The Balance of Scripture and Steel**

The supreme philosophical synthesis of Sūrah al-Ḥadīd is the integration of the *Kitāb* (The Scripture), the *Mīzān* (The Balance of Justice), and the *Ḥadīd* (Iron/Power). Revelation without justice becomes oppressive dogmatism; justice without revelation becomes subjective whim; and moral ideals without the strength of iron to protect the oppressed become a defenseless dream trampled by tyrants. Sūrah al-Ḥadīd teaches that true faith requires both spiritual tenderness in the heart (*layyin*) and resolute strength in the defense of justice (*ḥadīd*). By offering one's wealth and strength as a "goodly loan" to God, the believer escapes the hardened heart and steps into the radiant light of eternal grace."""

# -------------------------------------------------------------
# SURAH 58: AL-MUJĀDILAH
# -------------------------------------------------------------
intros[58] = """**The Pleading Woman and the All-Hearing Ear of Heaven**

Al-Mujādilah, "The Pleading Woman"—also known in classical exegesis as *Al-Mujādalah* (The Dispute)—is the fifty-eighth chapter of the Qur'an, comprising 22 verses of Medinan revelation. It takes its name from its astonishing opening verse: *“Allah has certainly heard the speech of the woman who pleads with you, [O Muḥammad], concerning her husband and directs her complaint to Allah; and Allah hears your dialogue. Indeed, Allah is Hearing and Seeing”* (58:1). This commemorates the historic case of Khawlah bint Thaʿlabah, an ordinary Muslim woman who challenged an abusive, archaic pagan divorce practice before the Prophet ﷺ. Sūrah al-Mujādilah is universally unique in the entire Qur'anic corpus by a stunning mathematical and structural phenomenon: *every single verse of its twenty-two verses explicitly contains the majestic name "Allāh"*—a total of forty occurrences across twenty-two lines! Sūrah al-Mujādilah is the great charter of the abolition of domestic abuse, the regulation of public meetings, the condemnation of clandestine conspiratorial whisperings (*al-najwā*), and the ultimate victory of the Party of God (*Ḥizb Allāh*).

**The Cry of Khawlah and the Abolition of Ẓihār**

The historical furnace of Sūrah al-Mujādilah is the domestic crisis of Khawlah bint Thaʿlabah and her elderly husband, Aws ibn al-Ṣāmit. In a fit of temper, Aws pronounced upon her the pre-Islamic formula of *Ẓihār*: *“You are to me like the back of my mother!”* In pagan Arab customary law, this phrase was a brutal legal loophole: it severed the marital bond sexually, but left the woman trapped without a formal divorce, unable to remarry, receive support, or leave the house—condemned to domestic limbo. Distraught, Khawlah came to the Prophet's room, weeping and arguing that she had spent her youth, wealth, and beauty on her husband, had borne him children, and now that she was old, he had cast her into destitution. The Prophet initially replied that according to prevailing custom, she was unlawful to him. Khawlah did not surrender; she turned her face to the sky, crying repeatedly: *“O Allah, I complain to You of my loneliness, my poverty, and the ruin of my young children!”* ʿĀ'ishah, who was in the room, recorded in Ṣaḥīḥ al-Bukhārī (4726) her sheer awe: *“Glory be to Him whose hearing encompasses all voices! I was in the corner of the room, and I missed parts of her speech, yet Allah heard her complaint from above the seven heavens!”* Verses 1–4 descended immediately: outlawing *Ẓihār* as a monstrous falsehood and an evil utterance (*munkaran min al-qawli wa-zūrā*), and legislating severe legal expiations (freeing a slave, fasting two consecutive months, or feeding sixty needy persons) before a husband could touch his wife again.

**The Structural Architecture and the Secret Assemblies**

The architecture of Sūrah al-Mujādilah moves from domestic justice to political counter-intelligence, and from social etiquette to cosmic allegiance:
1. The Protection of Women and the Abolition of Ẓihār (1–6): Exonerating Khawlah, criminalizing *Ẓihār*, codifying the tiered penalties, and warning those who defy Allah and His Messenger that their deeds are recorded in an incorruptible ledger by the God who was present at every moment.
2. The Omniscience of God and the Ethics of Secret Counsel (7–10): Delivering the celebrated verse of divine omnipresence: *“Have you not seen that Allah knows whatever is in the heavens and whatever is on the earth? There is in no private conversation three but that He is the fourth of them, nor are there five but that He is the sixth of them—and no less than that and no more except that He is with them wherever they are”* (58:7). It exposes the hypocrites and their Jewish conspirators who gathered in private cabals (*al-najwā*) to plot sin, aggression, and disobedience to the Messenger, and who greeted the Prophet with veiled insults (*“as-sāmu ʿalayka”*—death be upon you). It commands believers that if they must hold private counsel, it must be exclusively for righteousness and piety (*al-birri wa-l-taqwā*).
3. The Etiquette of Public Assemblies and Council Etiquette (11–13): Commanding believers to make room for others in public gatherings (*tafassaḥū fī al-majālis*), assuring that God will make room for them, and commanding them to rise when asked to rise, promising: *“Allah will raise those who have believed among you and those who were given knowledge, by degrees”* (58:11). It details the temporary test of giving charity before private consultations with the Prophet, gently easing the requirement when the community proved anxious.
4. The Two Parties: The Party of Satan vs. The Party of God (14–22): Exposing the hypocrites who took oaths of allegiance falsely, being terrified of exposure. Verse 19 defines their psychological state: *“Satan has overcome them and made them forget the remembrance of Allah. Those are the Party of Satan (*Ḥizb al-Shayṭān*). Unquestionably, the Party of Satan are the losers!”* Verse 21 proclaims the absolute divine decree: *“Allah has written: 'I will surely overcome, I and My messengers.' Indeed, Allah is Powerful and Exalted in Might.”* The sūrah concludes with the magnificent portrait of *Ḥizb Allāh* (The Party of God): souls whose allegiance to faith transcends all bloodlines, family ties, and ethnic bonds—in whose hearts God has inscribed faith and whom He has strengthened with a spirit from Him (*rūḥin minh*), entering the eternal gardens under the divine seal: *“Allah is pleased with them and they are pleased with Him. Those are the Party of Allah. Unquestionably, the Party of Allah are the successful!”* (58:22).

**The Ear That Hears the Helpless**

The supreme spiritual message of Sūrah al-Mujādilah is that in the kingdom of God, the desperate whisper of a broken, marginalized woman carries more weight than the arrogant councils of powerful men. Tyrants plot in secret assemblies, drafting laws to subjugate the weak, but they forget that God is the permanent, silent witness at every table. By mentioning the majestic name of *Allāh* in every single verse, Sūrah al-Mujādilah suffuses all human existence—from the bedchamber to the legislative hall—with the awe of divine presence, reminding humanity that ultimate victory belongs only to those whose hearts belong to *Ḥizb Allāh*."""

# -------------------------------------------------------------
# SURAH 59: AL-ḤASHR
# -------------------------------------------------------------
intros[59] = """**The Gathering of the Banished and the Mountain of Humility**

Al-Ḥashr, "The Gathering" or "The Banishment," is the fifty-ninth chapter of the Qur'an, comprising 24 verses of Medinan revelation. In the Companion tradition, ʿAbdullāh ibn ʿAbbās referred to this chapter without hesitation as *Sūrat Banī al-Naḍīr* (The Chapter of Banū al-Naḍīr), because its historical core (verses 2–17) chronicles the bloodless siege, surrender, and expulsion of the heavily fortified Jewish tribe of Banū al-Naḍīr from the environs of Madinah in 4 AH (625 CE). Positioned as the second of the five *Musabbiḥāt* chapters, Sūrah al-Ḥashr is universally celebrated for its breathtaking, peerless climax in verses 21–24: the majestic, awe-inspiring parable of the Qur'an descending upon a mountain, causing the granite crags to shatter in humility from the fear of God, followed by the grand, liturgical litany of the Most Beautiful Names of God (*al-Asmā' al-Ḥusnā*).

**The Fortress of Treachery and the Cold Dawn of Expulsion**

The historical catalyst of al-Ḥashr was an act of high treason that nearly cost the Prophet his life. In 4 AH, following the trauma of the Battle of Uḥud, the Prophet ﷺ, accompanied by Abū Bakr and ʿAlī, visited the settlements of the affluent, heavily fortified Jewish tribe of Banū al-Naḍīr to collect their treaty-mandated financial contribution toward blood-money. While the Prophet sat resting against the stone wall of one of their fortresses, the leadership of Banū al-Naḍīr conspired to assassinate him by having a man climb the roof and drop a massive millstone onto his head. Warned by divine inspiration, the Prophet rose instantly and returned to Madinah. Banū al-Naḍīr had repeatedly violated their mutual defense pact, harbored clandestine alliances with the pagan Quraysh, and were secretly promised military support by ʿAbdullāh ibn Ubayy and the hypocrites, who pledged: *“If you are expelled, we will surely leave with you, and we will not obey anyone concerning you, ever; and if you are fought, we will surely help you”* (59:11). The Prophet laid siege to their stone towers. Deserted by their hypocrite allies, their morale shattered by the cutting down of their date-palms, Banū al-Naḍīr surrendered without a sword being drawn. They were granted safe conduct to depart with whatever their camels could carry of possessions (excluding weapons), stripping the very doors and lintels from their homes. Verse 2 captures the historic verdict: *“He it is who expelled those who disbelieved among the People of the Scripture from their homes at the first gathering... So take heed, O you with eyes to see (*fa-ʿtabirū yā ulī al-abṣār*)!”*

**The Structural Architecture and the Names of Glory**

The architecture of Sūrah al-Ḥashr moves across three magnificent movements:
1. The Fall of the Fortresses and the Charter of Wealth (1–10): Opens with the cosmic glorification of God, recounts the expulsion of Banū al-Naḍīr whose stone fortresses could not shield them from God's decree, and codifies the revolutionary economic law of *al-Fay'* (war gains acquired without battle). Verses 7–8 decree that this wealth belongs to Allah, the Messenger, near relatives, orphans, the destitute, and the wayfarer, establishing the immortal socio-economic maxim of Islam: *“So that it may not be a perpetual circulation among the rich from among you (*kay lā yakūna dūlatan bayna al-aghniyā'i minkum*).”* It delivers the foundational constitutional principle of prophetic authority: *“And whatever the Messenger has given you—take; and what he has forbidden you—refrain from”* (59:7). It honors the impoverished Emigrants (*Muhājirūn*) who sacrificed their homes and wealth, and celebrates the Helpers (*Anṣār*) who loved those who migrated to them, harbored no jealousy in their breasts, and preferred others over themselves even when they were in dire poverty (*wa-yu'thirūna ʿalā anfusihim wa-law kāna bihim khaṣāṣah*, 59:9).
2. The Psychology of Betrayal and the Parable of Satan (11–17): Dissects the hollow promises of the hypocrites, exposing them as liars who never aid their allies in battle because fear of the believers is greater in their breasts than fear of God. It presents the striking military diagnosis: they will never fight you together except within fortified towns or from behind stone walls, their inner hatred among themselves is severe, and you imagine they are united, yet their hearts are utterly divided (59:14). It compares their deception to the parable of Satan, who commands man to disbelieve, but when man disbelieves, Satan says: *“Indeed, I am disassociated from you; indeed, I fear Allah, Lord of the worlds”* (59:16).
3. The Shattered Mountain and the Litany of Divine Names (18–24): Summons the believers to mindfulness (*Taqwā*), commanding every soul to look to what it has put forward for tomorrow, and warning them not to be like those who forgot God, so God made them forget their own souls (*fa-ansāhum anfusahum*, 59:19). It delivers the breathtaking image of verse 21: *“If We had sent down this Qur'an upon a mountain, you would have seen it humbled and split apart from the fear of Allah. And these examples We present to the people that perhaps they will give thought.”* The chapter concludes with the sublime, three-verse litany of the Most Beautiful Names of God: Allah, beside Whom there is no deity; the Knower of the unseen and seen; *al-Raḥmān, al-Raḥīm*; *al-Malik* (The Sovereign), *al-Quddūs* (The Pure/Holy), *al-Salām* (The Source of Peace), *al-Mu'min* (The Bestower of Security), *al-Muhaymin* (The Guardian), *al-ʿAzīz* (The Almighty), *al-Jabbār* (The Compeller), *al-Mutakabbir* (The Majestic); *al-Khāliq* (The Creator), *al-Bāri'* (The Originator), *al-Muṣawwir* (The Fashioner), to Whom belong the Most Beautiful Names, glorified by all in the heavens and earth.

**The Mountain of Granite and the Heart of Flesh**

The supreme philosophical and spiritual message of Sūrah al-Ḥashr is the tragedy of the hardened human heart. If the colossal, rigid granite of a mountain were endowed with consciousness and had the Qur'an recited upon it, it would disintegrate into dust from pure awe of the Divine Majesty. Yet human beings hear the word of God and remain distracted, cynical, and entrenched in material pride. Banū al-Naḍīr trusted in stone walls and imperial alliances, yet God entered their fortresses through their own psychology, casting terror into their hearts. Sūrah al-Ḥashr reminds humanity that true security is not found in high-walled compounds or hoarded wealth, but in taking heed (*fa-ʿtabirū*), softening the heart before the Reminder, and resting in the glorious names of the Sovereign Lord."""

# -------------------------------------------------------------
# SURAH 60: AL-MUMTAḤANAH
# -------------------------------------------------------------
intros[60] = """**The Examined Soul and the Boundaries of Sacred Loyalty**

Al-Mumtaḥanah, "The Examined Woman"—also pronounced classically as *Al-Mumtaḥinah* (The Examiner)—is the sixtieth chapter of the Qur'an, comprising 13 verses of late Medinan revelation. It takes its title from verse 10, which legislates the critical legal and spiritual protocol for examining (*fa-amtaḥinūhunna*) female refugees who fled from the pagan persecution of Makkah to the safety of Madinah following the Treaty of Ḥudaybiyah: testing their sincerity to ensure their migration was motivated purely by faith in God rather than marital discord or financial advantage. In classical scholarship, Sūrah al-Mumtaḥanah is revered as the definitive constitutional treaty on foreign relations, international alliances, and the ethics of loyalty (*al-Walā' wa-l-Barā'*). It navigates one of the most agonizing dilemmas in human sociology: how can a community of faith maintain political security against an existential enemy without succumbing to blanket xenophobia or severing the natural bonds of compassion toward peaceful, non-hostile outsiders?

**The Secret Letter of Ḥāṭib and the March on Makkah**

The dramatic historical catalyst of Sūrah al-Mumtaḥanah occurred in Ramaḍān of 8 AH (630 CE), as the Prophet ﷺ was secretly preparing a massive army of ten thousand men for the historic conquest and liberation of Makkah, following the Quraysh's breach of the Treaty of Ḥudaybiyah. To ensure a bloodless surrender, the destination was kept under absolute operational secrecy. However, Ḥāṭib ibn Abī Baltaʿah, a veteran Companion who had fought bravely at Badr, panicked over the safety of his vulnerable children and relatives who remained in Makkah without tribal protection. In a moment of acute human weakness, Ḥāṭib penned a secret letter warning the Quraysh of the impending mobilization, hiring a woman named Sārah to smuggle the letter in her braided hair. Divinely informed of the treason, the Prophet dispatched ʿAlī, al-Zubayr, and al-Miqdād, who intercepted the woman at the garden of Khākh, extracted the parchment from her hair, and brought it back to Madinah. ʿUmar ibn al-Khaṭṭāb drew his sword in fury, shouting: *“O Messenger of Allah, let me strike the neck of this hypocrite!”* The Prophet turned gently to Ḥāṭib, who wept and confessed: *“Do not be in haste with me, O Messenger of Allah! I have not disbelieved or apostatized; I only wished to establish a favor with the Quraysh so they might protect my family.”* The Prophet ﷺ turned to ʿUmar and said: *“He has spoken the truth. What do you know, O ʿUmar? Perhaps Allah looked upon the veterans of Badr and declared: 'Do whatever you will, for I have already forgiven you!'”* Verses 1–3 descended immediately: reprimanding the believers for extending clandestine affection to enemies actively waging war against them, but initiating a profound, nuanced legal framework for international relations.

**The Structural Modulation and the Golden Rule of Foreign Policy**

The architecture of Sūrah al-Mumtaḥanah is structured across three distinct movements:
1. The Reprimand of Compromised Loyalty and the Abrahamic Paradigm (1–6): Opens with the uncompromising command: *“O you who have believed, do not take My enemies and your enemies as allies, extending an offer of friendship to them while they have disbelieved in what came to you of the truth, having driven out the Messenger and yourselves [simply] because you believe in Allah, your Lord”* (60:1). It sets forward Abraham and his companions as the supreme, excellent model (*uswatun ḥasanah*): declaring to their idolatrous people their total disassociation from injustice until they believe in Allah alone, while recording Abraham's exceptional promise of forgiveness for his father as an exception that must not be imitated.
2. The Golden Rule of Peace and Engagement (7–9): Delivering a ray of prophetic hope: *“Perhaps Allah will put, between you and those to whom you have been enemies among them, affection. And Allah is competent, and Allah is Forgiving and Merciful”* (60:7)—a prophecy fulfilled when Makkah embraced Islam months later. Verses 8–9 establish the eternal, foundational charter of Islamic international relations:
   - *Positive Engagement*: *“Allah does not forbid you from those who do not fight you because of religion and do not expel you from your homes—from being righteous toward them and acting justly toward them. Indeed, Allah loves those who act justly (*al-muqsiṭīn*)”* (60:8).
   - *Hostile Non-Alliance*: *“Allah only forbids you from those who fight you because of religion and expel you from your homes and aid in your expulsion—[forbids] that you make allies of them. And whoever makes allies of them, then it is those who are the wrongdoers”* (60:9).
3. The Examination of Women and the Pledge of Allegiance (10–13): Regulating the refugee status of believing women fleeing Makkah, establishing that they cannot be returned to pagan husbands, returning their dowries to maintain economic fairness, and codifying the celebrated *Women's Pledge of Allegiance* (*Bayʿat al-Nisāʾ*, 60:12) directly to the Prophet ﷺ: pledging not to associate partners with God, not to steal, not to commit adultery, not to kill their children, not to produce slander fabricated between their hands and feet, and not to disobey the Prophet in that which is good. The sūrah concludes by reiterating the prohibition of allying with those who have incurred the wrath of God and despaired of the Hereafter.

**The Distinction Between Hostility and Humanity**

The supreme philosophical achievement of Sūrah al-Mumtaḥanah is its brilliant, surgical distinction between ideological disagreement and military belligerence. The Qur'an categorically refuses to allow political conflict to degenerate into indiscriminate hatred. Non-Muslims who do not wage war against the community, do not participate in ethnic cleansing, and do not aid oppressors are to be treated with *Birr* (the identical expansive, deep kindness commanded toward one's own parents) and *Qisṭ* (absolute judicial justice). Sūrah al-Mumtaḥanah teaches that authentic faith maintains ironclad security against active aggressors, while keeping its heart perpetually open to peace, justice, and reconciliation with all peaceful humanity."""

for ch in [56, 57, 58, 59, 60]:
    insert_surah_intro(ch, intros[ch])
print("Batch 6 (Part B: 56-60) inserted successfully.")
