import sys
sys.path.append(".")
from scripts.intro_utils import insert_surah_intro

intros = {}

# -------------------------------------------------------------
# SURAH 66: AT-TAḤRĪM
# -------------------------------------------------------------
intros[66] = """**The Sacred Household and the Four Archetypes of Womanhood**

At-Taḥrīm, "The Prohibition," is the sixty-sixth chapter of the Qur'an, comprising 12 verses of Medinan revelation. It takes its name from its opening verse: *“O Prophet, why do you prohibit [upon yourself] what Allah has made lawful for you, seeking the approval of your wives? And Allah is Forgiving and Merciful”* (66:1). In classical exegesis, Sūrah at-Taḥrīm is recognized as an intimate, profoundly sensitive domestic revelation, pulling back the veil upon the human household of the Messenger of Allah ﷺ. It demonstrates that even the most exalted prophetic home is not exempt from the subtle dynamics of jealousy, secrets, and emotional friction, and provides a timeless spiritual template for domestic harmony, sincere repentance (*Tawbah Naṣūḥah*), and individual moral responsibility. The sūrah concludes with one of the most celebrated and psychologically profound comparisons in sacred scripture: contrasting two corrupt women who lived under the roofs of righteous prophets against two righteous women who attained spiritual perfection in the face of tyranny and social isolation.

**The Honey, the Secret, and the Domestic Strain**

The historical occasions of Sūrah at-Taḥrīm are documented in authentic traditions in Ṣaḥīḥ al-Bukhārī (4912) and Ṣaḥīḥ Muslim (1474) across two famous incidents. In the first transmission, narrated by ʿĀ'ishah, the Prophet ﷺ was accustomed to lingering in the apartment of his wife Zaynab bint Jaḥsh, drinking a cup of honey she prepared for him. Driven by affectionate rivalry, ʿĀ'ishah and Ḥafṣah agreed between themselves that whichever of them the Prophet visited next would say: *“I smell the pungent odor of maghāfīr [a foul-smelling gum] on your breath!”* Sensitive to personal cleanliness and hating that any unpleasant aroma be detected on his person, the Prophet vowed: *“I will never drink honey again!”*—swearing Ḥafṣah to secrecy. In a second transmission involving his concubine Māriyah al-Qibṭiyyah, a private matter was similarly entrusted to Ḥafṣah under a pledge of confidentiality, yet she disclosed it to ʿĀ'ishah. When divine revelation informed the Prophet of the disclosure, he confronted Ḥafṣah, mentioning part of the secret and graciously passing over the rest (*ʿarrafa baʿḍahu wa-aʿraḍa ʿan baʿḍ*, 66:3). The domestic tension escalated until the Prophet separated himself from all his wives for an entire month, living in an upper chamber, prompting rumors throughout Madinah that the Prophet had divorced his wives. ʿUmar ibn al-Khaṭṭāb rushed to the chamber, weeping, and Sūrah at-Taḥrīm descended to resolve the crisis: expiating the Prophet's vow, admonishing the two noble wives to repent, and restoring the sanctity of the household.

**The Structural Architecture and the Four Archetypes**

The architecture of Sūrah at-Taḥrīm is structured across three distinct movements:
1. The Prophet's Household and the Admonition to Wives (1–5): Gently chiding the Prophet for prohibiting lawful provision to please his wives, and commanding the expiation of oaths. It addresses ʿĀ'ishah and Ḥafṣah directly in verse 4: *“If you two turn to Allah in repentance, [it is best], for your hearts have inclined [to deviate]; but if you cooperate against him—then indeed Allah is his protector, and Gabriel and the righteous of the believers and the angels, moreover, are [his] assistants.”* It warns that if the Prophet divorced them, his Lord might replace them with wives better than them: submissive, faithful, obedient, repenting, worshipping, fasting—previously married and virgins.
2. The Sanctity of the Home and Sincere Repentance (6–9): Delivers the monumental command to all heads of households in verse 6: *“O you who have believed, protect yourselves and your families from a Fire whose fuel is people and stones, over which are [appointed] angels, harsh and severe; they do not disobey Allah in what He commands them but do what they are commanded.”* It calls the believers to *Tawbah Naṣūḥah* (pure, unadulterated repentance) in verse 8, promising that God will expiate their sins and admit them into Gardens beneath which rivers flow, on a Day when God will not disgrace the Prophet and those who believed with him, their light shining before them and on their right hands as they pray: *“Our Lord, perfect for us our light and forgive us; indeed, You are over all things competent.”*
3. The Four Archetypes of Women (10–12): Constructs an unforgettable spiritual mirror:
   - *Two Disbelieving Women under Righteous Roofs* (10): The wife of Noah and the wife of Lot, who lived under the domestic care of two of God's righteous servants, yet betrayed them spiritually. Their marital proximity to prophets could not avail them an atom's weight against the judgment of God, and they were told: *“Enter the Fire with those who enter!”*
   - *The Wife of Pharaoh (Āsiyah)* (11): Living in the palace of the greatest tyrant in human history, surrounded by luxury and terror, who rejected his idolatry and prayed the immortal prayer: *“My Lord, build for me near You a house in Paradise, and save me from Pharaoh and his deeds, and save me from the wrongdoing people.”*
   - *Maryam bint ʿImrān* (12): The young virgin who guarded her chastity, into whom the divine Spirit was breathed, who believed in the words of her Lord and His scriptures, and was of the devoutly obedient (*al-qānitīn*).

**The Radical Autonomy of the Soul**

The supreme philosophical and spiritual message of Sūrah at-Taḥrīm is the absolute moral accountability of the individual soul. Spiritual status is neither contagious nor hereditary. Being the wife of a prophet (like the wives of Noah and Lot) cannot save an insincere soul from destruction; and being the wife of a bloodthirsty tyrant (like Āsiyah, wife of Pharaoh) cannot prevent a sincere soul from attaining the highest terrace of Paradise. Sūrah at-Taḥrīm teaches that every human being—man or woman—stands in direct, unmediated relationship with God. By setting forward two women (Āsiyah and Maryam) as the universal models of faith for all believing men and women, the sūrah establishes that spiritual perfection is achieved not by social privilege, but by the purity of one's repentance, the guarding of one's chastity, and the unyielding prayer for a house beside the Divine Presence."""

# -------------------------------------------------------------
# SURAH 67: AL-MULK
# -------------------------------------------------------------
intros[67] = """**The Sovereign Dominion and the Shield of the Grave**

Al-Mulk, "The Dominion" or "The Kingdom," is the sixty-seventh chapter of the Qur'an, comprising 30 verses of early-to-mid Makkan revelation. It opens with the soaring, majestic benediction: *“Blessed is He in whose hand is the dominion (*Tabāraka al-ladhī bi-yadihi al-mulk*), and He is over all things competent”* (67:1). In the liturgical and spiritual life of Islam, Sūrah al-Mulk occupies an exceptionally revered station: universally designated in prophetic traditions as *Al-Māniʿah* (The Preventer) and *Al-Munjiyah* (The Deliverer), because it shields its reciter from the trial and torment of the grave. ʿAbdullāh ibn Masʿūd reported in Sunan al-Nasā'ī (3407) that *“Whoever recites Sūrah al-Mulk every night, Allah will protect him thereby from the torment of the grave,”* and the Prophet ﷺ himself declared in Jāmiʿ al-Tirmidhī (2891): *“Indeed, there is a chapter in the Qur'an of thirty verses which intercedes for a man until he is forgiven: 'Blessed is He in whose hand is the dominion'!”* The chapter inaugurates the final, twenty-ninth *Juz'* of the Qur'an (commonly called *Juz' Tabārak*), setting forth the grand purpose of human creation—testing who is best in deed (*aḥsanu ʿamalā*)—and challenging the human eye to find a single flaw, rift, or imperfection in the cosmic architecture of the Almighty.

**The Gaze That Returns Exhausted**

The historical atmosphere of al-Mulk is marked by the cynical indifference of the Makkan polytheists toward the invisible reality of their Creator. They lived in an unthinking materialism, failing to perceive the profound wisdom woven into life and death. Sūrah al-Mulk confronts this spiritual stupor by issuing a direct, empirical challenge in verses 3–4: look up at the seven layered heavens created by the Most Compassionate: *“Do you see in the creation of the Most Compassionate any inconsistency? So return your vision [to the sky]; do you see any breaks? Then return your vision twice again; [your] vision will return to you humbled and exhausted (*khāsi'an wa-huwa ḥasīr*)!”* The sūrah argues that the flawless harmony of the celestial spheres, the flight of birds suspended in the air by none other than the Most Compassionate (67:19), and the stable earth spread out as an obedient cradle (*dhalūlā*) are living testimonies that human existence is not a meaningless accident.

**The Structural Modulation and the Sinking Water**

The architecture of Sūrah al-Mulk moves across four tightly integrated movements:
1. The Sovereign Creator and the Flawless Cosmos (1–5): Proclaims God's unshared dominion, defines the creation of death and life as an active test of moral excellence (*li-yabluwakum ayyukum aḥsanu ʿamalā*), challenges the human eye to detect any imperfection in the sky, and reveals the lowest heaven adorned with radiant lamps that serve as missiles against eavesdropping devils.
2. The Roar of the Abyss and the Confession of the Deniers (6–12): Stages the terrifying arrival of the disbelievers at the gates of Hell: when they are cast into it, they hear it gasping and inhaling with a terrifying boiling roar (*shahīqan wa-hiya tafūr*), almost bursting apart with fury. Its angelic keepers ask them: *“Did there not come to you a warner?”* They make the agonizing confession of verse 10: *“And they will say, 'If only we had been listening or reasoning, we would not be among the companions of the Blaze!'”* It contrasts this horror against the sublime promise of verse 12: *“Indeed, those who fear their Lord unseen will have forgiveness and great reward.”*
3. The Subjugation of the Earth and the Vulnerability of Man (13–22): Declares that God knows whether humanity speaks secretly or openly, asking the profound epistemic question: *“Does He who created not know, while He is the Subtle, the Acquainted?”* (67:14). It reminds humanity that God made the earth manageable, so walk through its paths and eat of His provision, but warns: are you secure that He who is in heaven will not cause the earth to swallow you while it convulses, or send upon you a storm of stones? It points to the birds above them, spreading their wings and folding them, held up exclusively by the Most Compassionate.
4. The Interrogations and the Vanishing Spring (23–30): Reminds humanity of the gifts of hearing, sight, and hearts, asks who has an army that can defend them besides the Most Compassionate, and who can provide for them if He withholds His provision. It presents the striking metaphor of guidance: *“Is he who walks fallen on his face more guided, or he who walks upright on a straight path?”* (67:22). The chapter closes with the chilling, haunting existential dilemma of verse 30: *“Say, 'Have you considered: if your water should become sunken into the earth [deep in the ground], then who could bring you flowing water?'”*

**Life as an Arena of Aḥsanu ʿAmalā**

The supreme philosophical core of Sūrah al-Mulk is found in verse 2: God created death and life *li-yabluwakum ayyukum aḥsanu ʿamalā* ("that He may test you which of you is best in deed"). The Qur'an does not say *aktharu ʿamalā* (who has the *most* deeds in quantity); it says *aḥsanu ʿamalā* (who has the *best* deeds in quality, sincerity, and excellence). Life is a temporary, beautifully engineered examination hall suspended beneath a flawless sky. By making the recitation of this sūrah an indispensable nightly devotion, the Prophet ﷺ trained the soul to remember its ultimate accountability before sleep—the minor death—so that when the final death arrives, the soul is shielded from the darkness of the grave by the intercession of the Sovereign King."""

# -------------------------------------------------------------
# SURAH 68: AL-QALAM
# -------------------------------------------------------------
intros[68] = """**The Cosmic Pen and the Defense of Prophetic Character**

Al-Qalam, "The Pen"—also known in classical scholarship as *Sūrat Nūn*—is the sixty-eighth chapter of the Qur'an, comprising 52 verses. In the chronological sequence of revelation, it holds a monumental, sacred station: universally agreed by early authorities (including Ibn ʿAbbās, Mujāhid, and al-Zuhrī) to be the *second revelation* sent down to the Prophet Muḥammad ﷺ, immediately following the opening five verses of Sūrah al-ʿAlaq (Chapter 96) at the Cave of Ḥirā'. It opens with the mysterious letter *Nūn*, sworn by the cosmic Pen and the sacred records: *“Nūn. By the pen and what they write! You are not, [O Muḥammad], by the favor of your Lord, a madman. And indeed, for you is a reward uninterrupted. And indeed, you are of a magnificent character (*wa-innaka la-ʿalā khuluqin ʿaẓīm*)!”* (68:1–4). Sūrah al-Qalam is the supreme divine defense of the Prophet's sanity, nobility, and moral perfection, delivering a terrifying psychological dissection of aristocratic arrogance and presenting the tragic parable of the Owners of the Blighted Garden.

**The Charge of Madness and the Consolation of the Pen**

The historical context of al-Qalam is the initial, brutal psychological shock of the prophetic commissioning. When the unlettered Muḥammad ﷺ descended from Mount Ḥirā' trembling, carrying the first words of revelation, the pagan Quraysh instantly reacted with vicious scorn. To neutralize his moral influence, they launched a smear campaign, branding him a *majnūn* (a demon-possessed lunatic). For a man known his entire life as *Al-Amīn* (The Trustworthy) and *Al-Ṣādiq* (The Truthful), this accusation was intensely painful. Sūrah al-Qalam descended directly from heaven as an unshakeable fortress of divine vindication. God swears by the primordial Pen (*al-Qalam*)—the first creation commanded by God to write down the destinies of all things until the Day of Resurrection—that Muḥammad ﷺ is not mad, but is endowed with *Khuluqun ʿAẓīm*: an exalted, magnificent, sublime moral character that towers over the pettiness of his abusers.

**The Structural Architecture and the Blighted Orchard**

The architecture of Sūrah al-Qalam moves across three powerful movements:
1. The Divine Vindication and the Anatomy of the Slanderer (1–16): Affirms the Prophet's exalted character and uninterrupted reward, predicting that both he and his opponents will soon see who is truly afflicted with madness. It warns the Prophet never to yield to their desire for compromise (*“They wish that you should compromise in speech, so they would compromise with you,”* 68:9), and paints a devastating, ten-point psychological caricature of the archetypal pagan oligarch (historically identified with al-Walīd ibn al-Mughīrah): *“And do not obey every worthless habitual swearer, scorner, going about with malicious gossip, preventer of good, transgressing, sinful, cruel, and moreover an illegitimate pretender (*zanīm*)—simply because he possesses wealth and children!”* (68:10–14). The sūrah delivers the humiliating prophecy: *“We will brand him upon the snout (*al-khurṭūm*)!”*
2. The Parable of the Owners of the Garden (17–33): Examines the ruin of economic greed through the story of the heirs of a lush agricultural estate: they plotted together to harvest all their fruit in the early morning darkness before any impoverished beggar could arrive to claim a share, failing to say *In shā' Allāh* ("If Allah wills"). While they slept, a cosmic whirlwind from your Lord struck the garden, leaving it like a pitch-black, barren ruin (*ka-l-ṣarīm*). When they arrived at dawn with baskets, they rubbed their eyes, crying: *“Indeed, we are lost! Nay, we have been deprived!”* The most moderate among them said: *“Did I not tell you, 'Why do you not glorify Allah?'”* They turned upon one another in mutual blame, confessing their transgression, and hoping their Lord would replace it with better. The sūrah warns: *“Such is the punishment [of this world]; and the punishment of the Hereafter is greater, if they only knew!”*
3. The Day the Shin is Unveiled and the Companion of the Whale (34–52): Contrasts the gardens of delight for the righteous against the arrogance of the criminals. It stages the terrifying moment of the Day of Judgment in verse 42: *“The Day the shin will be uncovered (*kashfu ʿan sāq*) and they are called to prostrate, but they will not be able; their eyes humbled, humiliation covering them—and they were previously called to prostrate while they were sound!”* It reminds the Prophet of the lesson of Jonah (*Ṣāḥib al-Ḥūt*): command him not to be like Jonah, who lost patience and fled before being swallowed by the whale in distress, saved only by divine grace. The sūrah concludes with the intense, venomous hatred of the Quraysh in verse 51: *“And indeed, those who disbelieve would almost make you slip with their eyes [in hatred] when they hear the message, and they say, 'Indeed, he is mad!' But it is not except a reminder to the worlds.”*

**The Radiance of Khuluqun ʿAẓīm**

The defining spiritual glory of Sūrah al-Qalam is the divine tribute bestowed upon the Prophet Muḥammad ﷺ: *Wa-innaka la-ʿalā khuluqin ʿaẓīm* ("And indeed, you are upon an exalted standard of character"). When ʿĀ'ishah was questioned by the Companions about the nature of the Prophet's character, she replied with the immortal words: *“His character was the Qur'an itself”* (Ṣaḥīḥ Muslim 746). He was the living, breathing translation of sacred scripture into human form. Sūrah al-Qalam teaches that while arrogant tyrants rely on wealth, gossip, and physical brutality—only to be branded like beasts upon their snouts—the moral character nurtured in patience, forgiveness, and unyielding fidelity to truth outlasts all worldly empires."""

# -------------------------------------------------------------
# SURAH 69: AL-ḤĀQQAH
# -------------------------------------------------------------
intros[69] = """**The Inevitable Reality and the Flying Record**

Al-Ḥāqqah, "The Inevitable Reality" or "The Indubitable Truth," is the sixty-ninth chapter of the Qur'an, comprising 52 verses of early Makkan revelation. It opens with three explosive, echoing, single-word interrogations: *“Al-Ḥāqqah! What is al-Ḥāqqah? And what can make you know what is al-Ḥāqqah?”* (69:1–3). Derived from the root *ḥ-q-q* (truth, reality, necessity), *Al-Ḥāqqah* is one of the most terrifying names of the Day of Resurrection: the Day when all illusions are vaporized, all masks are torn away, all hidden deeds are laid bare, and absolute reality asserts its sovereign, undeniable dominion. Characterized by apocalyptic thunder and visceral, emotional descriptions of the final reckoning, Sūrah al-Ḥāqqah presents the dramatic binary of human destiny: the soul that receives its record in its right hand crying out in ecstatic joy, contrasted against the soul that receives its record in its left hand, crying out in bitter despair that it had perished in dust.

**The Conversion of ʿUmar and the Defense of Divine Speech**

In early Islamic history, Sūrah al-Ḥāqqah is immortalized as another decisive encounter that shook the conscience of ʿUmar ibn al-Khaṭṭāb prior to his conversion. ʿUmar recounted in classical historical chronicles: *“I set out to confront Muḥammad before I embraced Islam, and I found he had preceded me to the Sacred Mosque. I stood behind him while he was praying, and he began reciting Sūrah al-Ḥāqqah. I listened to the astonishing rhythm of the Qur'an, and I thought to myself: 'By God, this man is a poet, just as the Quraysh say!' Immediately, the Prophet recited: 'Indeed, the Qur'an is the speech of a noble messenger. And it is not the speech of a poet; little is what you believe!' (69:40–41). I said to myself: 'Then he must be a soothsayer (*kāhin*), reading my mind!' Immediately, the Prophet recited: 'Nor is it the speech of a soothsayer; little is what you remember! [It is] a revelation from the Lord of the worlds' (69:42–43). At that moment, Islam took hold of the roots of my heart!”*

**The Structural Architecture and the Two Records**

The architecture of Sūrah al-Ḥāqqah moves across three magnificent movements:
1. The Ruins of Ancient Deniers (1–12): Reviews the sudden, catastrophic destructions of civilizations that denied the Inevitable Reality (*al-Qāriʿah*): Thamūd wiped out by the thunderous, overwhelming blast (*al-ṭāghiyah*); ʿĀd destroyed by a furious, freezing, unceasing gale subjugated over them for seven nights and eight days, leaving men lying fallen like the hollow trunks of uprooted date palms (*aʿjāzu nakhlin khāwiyah*); Pharaoh and the overturned cities of Lot; and the Deluge where God carried human ancestry upon the floating Ark to make it an enduring reminder for listening ears (*udhunun wāʿiyah*).
2. The Single Blast and the Staging of the Books (13–37): The single blast of the Horn (*nafkhatun wāḥidah*), the earth and mountains lifted and crushed with a single blow, the sky split open and frail on that Day, with the angels standing at its edges and eight angels bearing the Throne of your Lord above them! Verse 18 proclaims: *“On that Day you will be exhibited [for judgment]; not hidden among you is any secret.”* It stages the dramatic contrast of the two recipients:
   - *The Right Hand* (19–24): The triumphant believer waving his scroll in ecstasy, shouting to the crowds: *“Here, read my record! Indeed, I was certain that I would meet my account!”* He is admitted into pleasant living in a lofty Garden whose clusters of fruit hang within reach, told: *“Eat and drink in satisfaction for what you put forth in the days gone by!”*
   - *The Left Hand* (25–37): The horrified criminal crying: *“Oh, I wish I had not been given my record, and had not known what is my account! Oh, I wish death had been my end! My wealth has not availed me; my authority has departed from me!”* The divine decree falls upon him: *“Seize him and shackle him! Then into Hellfire burn him! Then into a chain whose length is seventy cubits insert him!”* It reveals the two moral sins that caused his doom: he did not believe in Allah the Most Great, and he never encouraged the feeding of the impoverished (*wa-lā yaḥuḍḍu ʿalā ṭaʿāmi al-miskīn*).
3. The Oath of Revelation and the Severed Aorta (38–52): God swears a colossal oath by all that you see and all that you cannot see: that this is the speech of a noble messenger, not of a poet or a soothsayer. It issues the ultimate theological guarantee of prophetic integrity in verses 44–46: *“And if [Muḥammad] had fabricated against Us some [false] sayings, We would have seized him by the right hand, then We would have severed his life-artery / aorta (*al-watīn*), and not one of you could have prevented [it] from him!”* The chapter concludes by affirming that the Qur'an is an immense regret for the disbelievers, yet it is the absolute truth of certainty (*ḥaqqu al-yaqīn*): *“So exalt the name of your Lord, the Most Great!”*

**The Sincerity of the Open Book: Hā'umu Iqra'ū Kitābiyah**

The supreme spiritual thesis of Sūrah al-Ḥāqqah is the transparency of the human soul. On earth, humans spend lifetimes hiding secrets behind pleasant clothes, polished smiles, and legal facades; but on the Day of *Al-Ḥāqqah*, every secret is dragged into the blazing light of divine justice (*lā takhfā minkum khāfiyah*). The righteous soul is one that lived with the constant, conscious expectation of this meeting (*annī mulāqin ḥisābiyah*), using its wealth to feed the hungry and its tongue to glorify God. Sūrah al-Ḥāqqah invites the reader to prepare for that Day so that when the books fly open, our souls may cry out in joy: *“Here, read my record!”*"""

# -------------------------------------------------------------
# SURAH 70: AL-MAʿĀRIJ
# -------------------------------------------------------------
intros[70] = """**The Ascending Stairways and the Anatomy of Human Anxiety**

Al-Maʿārij, "The Ascending Stairways" or "The Ways of Ascent," is the seventieth chapter of the Qur'an, comprising 44 verses of early Makkan revelation. It takes its name from verse 3, which designates God as *Dhū al-Maʿārij* (The Owner of the Ways of Ascent): the celestial stairways and cosmic dimensions through which the angels and the Spirit (Gabriel) ascend to the Divine Throne across a timescale whose earthly measure is fifty thousand years (*fī yawmin kāna miqdāruhū khamsīna alfa sanah*). Sūrah al-Maʿārij is celebrated in psychological and moral theology for containing the definitive Qur'anic radiography of the unregenerate human ego in verses 19–21: *“Indeed, mankind was created anxious and impatient (*halūʿā*): when evil touches him, he is fretful and despondent; and when good touches him, he is stingy and withholding”*—followed immediately by the eight sublime spiritual disciplines of the prayerful that cure this existential anxiety.

**The Sarcastic Challenge of al-Naḍr**

The historical catalyst of al-Maʿārij is preserved in classical chronicles regarding al-Naḍr ibn al-Ḥārith, the cynical Qurayshi chieftain who stood before the Kaʿbah and offered the arrogant, sarcastic prayer recorded in Sūrah al-Anfāl (8:32): *“O Allah, if this is indeed the truth from You, then rain down upon us stones from the sky, or bring us a painful punishment!”* Sūrah al-Maʿārij opens with an immediate, razor-sharp response to this challenge: *“A questioner asked about a punishment bound to happen (*sa'ala sā'ilun bi-ʿadhābin wāqiʿ*), to the disbelievers; of it there is no preventer, from Allah, Owner of the Ascending Stairways!”* (70:1–3). The sūrah warns the skeptic that his sarcastic wish for retribution will be granted with terrifying precision: on a Day when the sky becomes like molten brass, the mountains like carded wool, and no close friend will ask about his friend, though they are placed in full view of each other.

**The Structural Architecture and the Sanctuary of the Prayerful**

The architecture of Sūrah al-Maʿārij is organized across three distinct movements:
1. The Cosmic Dimension and the Unavailing Ransom (1–18): Opens with the inevitable punishment, commands the Prophet to maintain beautiful patience without complaint (*fa-ṣbir ṣabran jamīlā*), contrasting human short-sightedness (*“Indeed, they see it distant, but We see it near!”*, 70:6–7). It portrays the horrifying scene of the Day of Judgment: the criminal desperately wishing he could ransom himself from the torment by offering his children, his wife, his brother, his entire sheltering clan, and everyone upon the earth combined, just to save his own neck! The divine voice thunders: *“By no means! Indeed, it is the Flame of Hell (*Ladhā*), stripping away the scalp, inviting him who turned his back and amassed wealth and hoarded it!”*
2. The Pathology of the Ego and the Eightfold Sanctuary (19–35): Delivers the profound psychological diagnosis of human anxiety: man is created *Halūʿ* (fretful, panicked in adversity, tight-fisted in prosperity). It immediately presents the exceptional community that escapes this neurosis: *“Except the prayerful (*illā al-muṣallīn*)”* (70:22). It outlines their eight transformative spiritual characteristics:
   - Those who are constant in their prayers (*ʿalā ṣalātihim dā'imūn*).
   - In whose wealth is a recognized right for the beggar and the deprived.
   - Who believe in the Day of Recompense.
   - Who are fearful of the punishment of their Lord.
   - Who guard their sexual modesty except with spouses.
   - Who are faithfully attentive to their trusts and covenants.
   - Who stand firm in their testimonies without cowardice.
   - Who guard their prayers punctually.
   The movement seals their destiny: *“Those will be in gardens, honored.”*
3. The Deniers on the Horizon and the Race from the Graves (36–44): Rebukes the polytheists who rush toward the Prophet with craning necks, sitting on his right and left in mocking groups, asking sarcastically: *“Does every person among them aspire to enter a garden of pleasure? By no means! Indeed, We have created them from what they know!”* God swears a cosmic oath by the Lord of the Easts and the Wests that He is competent to replace them with a people better than them. The sūrah concludes by commanding the Prophet to leave them to converse and play until they meet their Day, portraying them emerging from their graves in haste as if racing toward an idol's shrine, eyes cast down, humiliation covering them: *“That is the Day which they were promised!”*

**The Beautiful Patience and the Constant Prayer**

The foundational spiritual insight of Sūrah al-Maʿārij is the pairing of *Ṣabr Jamīl* (Beautiful Patience) with *Ṣalāh Dā'imah* (Constant Prayer). The human ego is naturally trapped in the oscillation of panic (*jazaʿ*) and greed (*manaʿ*), torn apart by its own anxieties. The only force capable of stabilizing this volatile psychology is the anchor of constant prayer (*dā'imūn*): prayer that is not an occasional formality, but a perpetual, living connection with the Owner of the Ascending Stairways. By transforming the prayerful soul into a fountain of charity, justice, sexual integrity, and fidelity to covenants, Sūrah al-Maʿārij proves that true worship is the only medicine that heals the chronic anxiety of the human heart."""

for ch in [66, 67, 68, 69, 70]:
    insert_surah_intro(ch, intros[ch])
print("Batch 7 (Part B: 66-70) inserted successfully.")
