import sys
sys.path.append(".")
from scripts.intro_utils import insert_surah_intro

intros = {}

# -------------------------------------------------------------
# SURAH 61: AṢ-ṢAFF
# -------------------------------------------------------------
intros[61] = """**The Solid Structure and the Prophecy of the Paraclete**

Aṣ-Ṣaff, "The Battle Array" or "The Ranks," is the sixty-first chapter of the Qur'an, comprising 14 verses of Medinan revelation. It belongs to the sequence of the five *Musabbiḥāt* chapters and takes its title from verse 4, which delivers an unforgettable military, communal, and spiritual image: *“Indeed, Allah loves those who fight in His cause in a row / rank as though they were a structure joined firmly (*bunyānun marṣūṣ*)!”* Sūrah aṣ-Ṣaff is celebrated in prophetic biography and hadith literature: ʿAbdullāh ibn Salām reported in Jāmiʿ al-Tirmidhī (3309) that a gathering of Companions sat discussing what deed was most beloved to Allah so they might perform it, whereupon revelation descended upon the Prophet ﷺ in the form of Sūrah aṣ-Ṣaff, opening with the searching moral rebuke of verses 2–3: *“O you who have believed, why do you say that which you do not do? Most hateful it is in the sight of Allah that you say what you do not do!”* In fourteen concentrated, laser-sharp verses, the sūrah establishes the necessity of total alignment between verbal conviction and physical sacrifice, and contains the famous biblical prophecy of Jesus announcing the coming of the final Prophet under the name *Aḥmad* (61:6).

**The Crucible of Action and the Threat of Hypocrisy**

The historical setting of Sūrah aṣ-Ṣaff is located around the aftermath of the Battle of Uḥud (3 AH). Prior to the battle, many believers had proclaimed their eagerness to sacrifice their lives for the defense of the faith; yet when the iron of the enemy struck and the rumor of the Prophet's death spread, some wavered, fled the ridge, or questioned the divine promise. Sūrah aṣ-Ṣaff arrived as a stern, loving mirror: faith is not verified by fiery speeches in peaceful assemblies, but by standing shoulder-to-shoulder under enemy fire like bricks locked together with molten lead (*bunyānun marṣūṣ*). The sūrah warns the community against replicating the spiritual degradation of the Israelites under Moses, who tormented their prophet with bad-faith questioning until their hearts deviated: *“And when they deviated, Allah caused their hearts to deviate (*azzāghū azāgha Allāhu qulūbahum*)”* (61:5).

**The Structural Architecture and the Commerce of Salvation**

The architecture of Sūrah aṣ-Ṣaff unfolds across three distinct movements:
1. The Rebuke of Moral Inconsistency and the Prophetic Precedents (1–6): Opens with the cosmic glorification of God, rebukes the hypocrisy of preaching what one fails to practice, and proclaims God's love for the solid, united phalanx of believers. It reviews Moses enduring the unjust abuse of his people, and stages the historic proclamation of Jesus son of Mary: *“O Children of Israel, indeed I am the messenger of Allah to you confirming what came before me of the Torah and bringing good tidings of a messenger to come after me, whose name is Aḥmad”* (61:6).
2. The Extinguishing of Divine Light and the Inevitable Triumph (7–9): Exposes the futile attempt of the deniers to extinguish the Light of God with their mouths—promising that Allah will perfect His light even if the disbelievers detest it. It delivers the grand civilizational manifesto of verse 9: *“He it is who sent His Messenger with guidance and the religion of truth to make it manifest over all religion, even if the polytheists detest it.”*
3. The Supreme Transaction: Tijārah (10–14): Proffers the immortal divine investment in verse 10: *“O you who have believed, shall I guide you to a transaction (*tijārah*) that will save you from a painful punishment?”* The capital of this transaction is threefold: believing in Allah and His Messenger, striving in the cause of Allah with wealth, and striving with life. The return on investment is forgiveness of sins, eternal residences in the Gardens of Eden, and an immediate earthly blessing: *“Victory from Allah and an imminent conquest (*naṣrun min Allāhi wa-fatḥun qarīb*); and give good tidings to the believers!”* The sūrah concludes by summoning the believers to emulate the disciples (*al-Ḥawāriyyūn*) of Jesus, who unhesitatingly answered Christ's summons: *“Who are my supporters for Allah?”* by declaring: *“We are the supporters of Allah!”* (61:14).

**The Bunyān Marṣūṣ and the Integrity of Speech**

The foundational spiritual philosophy of Sūrah aṣ-Ṣaff is the absolute, non-negotiable imperative of *Sidq*—internal and external integrity. The greatest betrayal in the spiritual life is the chasm between the tongue and the hand: uttering pious slogans while evading sacrificial duty. A fragmented, individualistic community of eloquent speakers will be crushed by history; but a community that welds itself into a *Bunyān Marṣūṣ*—a living wall of mutual loyalty, unified discipline, and unshakeable sacrifice—becomes the terrestrial vessel through which the inextinguishable Light of God illuminates the earth."""

# -------------------------------------------------------------
# SURAH 62: AL-JUMUʿAH
# -------------------------------------------------------------
intros[62] = """**The Friday Congregation and the Donkey Laden with Books**

Al-Jumuʿah, "The Friday Gathering," is the sixty-second chapter of the Qur'an, comprising 11 verses of Medinan revelation. Positioned as the fourth of the *Musabbiḥāt* chapters, it takes its name from verse 9, which legislates the supreme weekly congregational prayer of the Muslim world: *“O you who have believed, when the call is proclaimed for the prayer on the day of Jumuʿah [Friday], then hasten to the remembrance of Allah and leave all trade! That is better for you, if you only knew.”* In prophetic tradition, Sūrah al-Jumuʿah is central to weekly liturgy: the Prophet Muḥammad ﷺ regularly recited Sūrah al-Jumuʿah in the first cycle and Sūrah al-Munāfiqūn in the second cycle of the Friday congregational prayer (Ṣaḥīḥ Muslim 877). In eleven concise, intensely concentrated verses, the sūrah establishes the fourfold mission of the Prophet to the unlettered (*al-ummiyyīn*), delivers one of the most devastating parables against dry, sterile intellectualism (the donkey carrying heavy scrolls), and commands the absolute suspension of commercial transactions when the call to the Friday prayer sounds.

**The Arrival of the Caravan and the Abandoned Pulpit**

The dramatic historical catalyst of Sūrah al-Jumuʿah is recorded in Ṣaḥīḥ al-Bukhārī (2058) and Ṣaḥīḥ Muslim (863) by Jābir ibn ʿAbdillāh. In the early Medinan period, during a season of severe economic scarcity and inflated prices, the Prophet ﷺ was delivering the sacred Friday sermon (*Khuṭbah*) from the pulpit. Suddenly, the drums and trumpets of a rich trade caravan led by Diḥyah al-Kalbī arriving from Syria resounded through the oasis. Fearing that the flour and provisions would be bought up by others, the congregation panicked: the vast majority of the worshippers rose and rushed out into the marketplace, leaving only twelve faithful men—including Abū Bakr, ʿUmar, ʿAlī, and Ibn Masʿūd—standing before the Prophet! Verse 11 descended in stinging divine rebuke: *“And when they saw a transaction or a diversion, they rushed to it and left you standing! Say, 'What is with Allah is better than diversion and than trade, and Allah is the best of providers.'”* The Prophet ﷺ remarked with solemn gravity: *“By Him in whose hand is my soul, had all of you deserted me, the valley would have overflowed with fire upon you!”*

**The Structural Modulation and the Donkey with Scrolls**

The architecture of Sūrah al-Jumuʿah is organized across three distinct movements:
1. The Mission to the Unlettered (1–4): Opens with the cosmic glorification of the Sovereign, the Holy, the Exalted in Might, the Wise. It proclaims the divine election of the Prophet Muḥammad ﷺ: sent to the unlettered Arabs (*al-ummiyyīn*) to execute four sacred functions: reciting His verses, purifying their souls (*yuzakkīhim*), and teaching them the Scripture (*al-Kitāb*) and the Wisdom (*al-Ḥikmah*), when they had previously been in manifest misguidance. It extends this mission across all future generations and ethnic nations: *“And [to] others among them who have not yet joined them”* (62:3).
2. The Parable of the Donkey and the Challenge of Death (5–8): Delivers the unforgettable polemical diagnosis of religious pedantry in verse 5: *“The example of those who were entrusted with the Torah and then did not bear it / act upon it is like that of a donkey carrying heavy volumes of books (*ka-mathali al-ḥimāri yaḥmilu asfārā*). Wretched is the example of the people who deny the signs of Allah!”* A donkey carrying a library of precious medical, legal, and theological manuscripts upon its back perceives nothing of their wisdom except dead physical weight. The sūrah challenges the Jewish claims of exclusive divine election: *“If you claim that you are allies of Allah to the exclusion of other people, then wish for death, if you should be truthful!”* It confirms that they will never wish for death because of what their hands have put forward, and delivers the immortal reality of verse 8: *“Say, 'Indeed, the death from which you flee—indeed, it will meet you. Then you will be returned to the Knower of the unseen and the witnessed, and He will inform you about what you used to do.'”*
3. The Sacred Pause of the Friday Assembly (9–11): Legislates the liturgical pause of Friday: when the prayer call is sounded, drop all commerce, close all shops, and hasten with focused intention to the remembrance of God and the prophetic sermon. Once the prayer is completed, the believers are granted permission to disperse through the earth, seek the bounty of God through lawful trade, and remember God abundantly that they may prosper, concluding with the rebuke of those who abandoned the Prophet standing upon the pulpit.

**The Danger of the Unassimilated Book**

The supreme philosophical and educational warning of Sūrah al-Jumuʿah is the terrifying peril of possessing divine scripture without moral transformation. To memorize, print, recite, and analyze the sacred text while failing to embody its justice, compassion, and humility is to reduce oneself to the spiritual level of the donkey laden with books (*al-ḥimār yaḥmilu asfārā*). Sūrah al-Jumuʿah demands that the Friday congregation be not an empty social ritual, but a sacred weekly sanctuary: a moment where commerce halts, the heart is purified from material greed (*tazkiyah*), and the human soul is realigned with the eternal remembrance of the Sovereign King."""

# -------------------------------------------------------------
# SURAH 63: AL-MUNĀFIQŪN
# -------------------------------------------------------------
intros[63] = """**The Mask of Deceit and the Treason of the Oasis**

Al-Munāfiqūn, "The Hypocrites," is the sixty-third chapter of the Qur'an, comprising 11 verses of Medinan revelation. It is the only chapter in the entire sacred canon titled after the fifth-column subversive faction of the hypocrites (*al-munāfiqūn*). Characterized by explosive political tension and profound psychological radiography, Sūrah al-Munāfiqūn was paired liturgically by the Prophet Muḥammad ﷺ with Sūrah al-Jumuʿah in the weekly Friday congregational service (Ṣaḥīḥ Muslim 877): while al-Jumuʿah summons the faithful to unity and purity in the mosque, al-Munāfiqūn unmasks the treacherous conspirators sitting in the very same prayer rows! In eleven masterly, dramatic verses, the sūrah strips away the polished rhetoric and imposing physical appearance of the hypocrites, documents the historic treason of their chief, ʿAbdullāh ibn Ubayy, and issues an urgent, loving pastoral warning to the sincere believers never to let wealth and children distract them from the remembrance of God until the sudden, irreversible strike of death.

**The Scuffle at the Well of Muraysīʿ and the Boast of Ibn Ubayy**

The dramatic historical catalyst of Sūrah al-Munāfiqūn occurred in 5 or 6 AH during the return march from the Expedition of Banū al-Muṣṭaliq (the Well of Muraysīʿ), recorded in Ṣaḥīḥ al-Bukhārī (4900) by Zayd ibn Arqam. A minor dispute broke out at the well between a servant of ʿUmar (an Emigrant) and an ally of the Khazraj (a Helper). The dispute was settled instantly, but ʿAbdullāh ibn Ubayy ibn Salūl, the chief of the hypocrites—who had been on the verge of being crowned king of Madinah before the arrival of Islam—saw an opportunity to ignite tribal civil war. In a private conclave, Ibn Ubayy erupted in venomous fury: *“Have they really done this? They challenge us and outnumber us in our own land! By Allah, the example between us and these destitute Emigrants is as the ancient proverb says: 'Fatten your dog and it will eat you!'”* He turned to his fellow Medinans and commanded an economic embargo: *“Do not spend on those who are with the Messenger of Allah until they disband and disperse!”* He concluded with the treasonous threat of verse 8: *“By Allah, if we return to Madinah, the more honorable [meaning himself] will surely expel therefrom the more lowly [meaning the Prophet]!”* A young teenage orphan Companion, Zayd ibn Arqam, overheard this treason and reported it directly to the Prophet. When summoned, Ibn Ubayy swore solemn oaths by Allah that he had never uttered such words, and some elders pleaded that the boy had misheard. The young Zayd was plunged into agonizing distress, ostracized by his relatives for allegedly slandering a chief. The Prophet walked in heavy silence. Suddenly, revelation descended upon the Prophet ﷺ: his face radiated with divine light, he took hold of Zayd's ear, smiled, and said: *“The boy's ear spoke the truth, and Allah has vindicated you, O Zayd!”* Sūrah al-Munāfiqūn descended, quoting Ibn Ubayy's treason verbatim and branding him a liar.

**The Structural Anatomy of the Sūrah**

The architecture of Sūrah al-Munāfiqūn is divided into two contrasting movements:
1. The Autopsy of Hypocrisy (1–8): Opens with the hollow verbal testimony of the hypocrites (*“We bear witness that you are indeed the Messenger of Allah”*), countered by heaven's verdict: *“And Allah knows that you are His Messenger, and Allah bears witness that the hypocrites are indeed liars!”* They take their oaths as a protective shield (*junnah*) to obstruct the path of God. Verse 4 delivers the famous, chilling physical description of their leadership: *“And when you see them, their forms please you, and if they speak, you listen to their speech. [Yet] they are like propped-up pieces of timber (*khushubun musannadah*). They think every shout is against them! They are the enemy, so beware of them; may Allah destroy them; how are they deluded!”* When invited to seek the Prophet's forgiveness, they arrogantly twist their heads in contempt. The sūrah quotes their economic boycott (63:7) and their boast of expelling the Prophet (63:8), responding with the sovereign constitutional axiom: *“And to Allah belongs all honor (*al-ʿizzah*), and to His Messenger, and to the believers, but the hypocrites do not know!”*
2. The Pastoral Admonition to the Believers (9–11): Shifts the lens from the enemy without to the vulnerability within: *“O you who have believed, let not your wealth or your children distract you from the remembrance of Allah. And whoever does that—then those are the losers!”* It commands spending in charity before the sudden strike of mortality, staging the desperate, terrified cry of the dying man in verse 10: *“My Lord, if only You would delay me for a short term so I would give charity and be among the righteous!”* The sūrah concludes with the immutable divine law of mortality: *“But never will Allah delay a soul when its term has come. And Allah is Acquainted with what you do.”*

**The Timber with No Roots and the True Source of Honor**

The foundational philosophical insight of Sūrah al-Munāfiqūn is the metaphor of the *Khushub Musannadah* (propped-up pieces of hollow timber). A tree planted in the soil possesses roots, sap, green leaves, and fruit; but a dead beam of cut wood has no life—it looks solid from the outside, but it must be propped against a wall to stand, and is hollow tinder ready for the fire. Such is the hypocrite: possessed of magnificent attire, impressive physical stature, and polished rhetorical eloquence, yet inwardly dead, cowardly, and consumed by paranoid guilt. By declaring that all true honor (*al-ʿIzzah*) belongs exclusively to Allah, His Messenger, and the believers, Sūrah al-Munāfiqūn teaches that worldly prestige built on treason and deceit will inevitably collapse into eternal disgrace."""

# -------------------------------------------------------------
# SURAH 64: AT-TAGHĀBUN
# -------------------------------------------------------------
intros[64] = """**The Mutual Dispossession and the Test of Affection**

At-Taghābun, "Mutual Loss and Gain" or "The Day of Mutual Dispossession," is the sixty-fourth chapter of the Qur'an, comprising 18 verses of Medinan revelation. It is the fifth and final chapter of the *Musabbiḥāt* sequence, taking its name from verse 9, which designates the Day of Resurrection as *Yawm al-Taghābun*: the Day when the true ledger of cosmic transactions is unveiled, exposing how the deniers sold their eternal souls for worthless worldly trinkets, while the believers exchanged temporal sacrifices for an eternal empire of light. Characterized by profound psychological realism and socio-familial wisdom, Sūrah at-Taghābun addresses the subtle emotional friction that arises within the believing household when the demands of faith conflict with the attachment to spouses and children, providing the definitive spiritual strategy for navigating the domestic trials of life.

**The Domestic Crossroad and the Hindrance to Migration**

The historical occasion of at-Taghābun is preserved in traditions recorded by Ibn ʿAbbās and al-Tirmidhī regarding early Muslim converts in Makkah who wished to perform the *Hijrah* to join the Prophet in Madinah. Their pagan or non-committal wives and children would weep, cling to their garments, and plead: *“By Allah, we adjure you not to leave us! How will we survive without you?”* Moved by emotional tenderness and familial love, some converts relented, staying behind in the pagan city and delaying their migration until long after the pivotal battles of Islam had been fought. When they eventually migrated to Madinah years later and saw how far the early Emigrants had surpassed them in sacred knowledge, spiritual elevation, and rank, they were filled with bitter regret and anger toward the families who had held them back, wishing to punish or sever relations with them. Verses 14–15 descended to heal and guide this crisis: *“O you who have believed, indeed, among your spouses and your children are enemies to you, so beware of them! But if you pardon and overlook and forgive—then indeed, Allah is Forgiving and Merciful. Your wealth and your children are only a trial (*fitnah*), and Allah has with Him an immense reward.”*

**The Structural Movement and the Economics of Sincerity**

The architecture of Sūrah at-Taghābun moves across three distinct movements:
1. Cosmic Glorification and the Certainty of the Gathering (1–10): Opens with the universal praise of the Sovereign King, affirming that God created humanity, yet among them is the disbeliever and among them is the believer. It points to the fashioning of human forms in beauty and the divine omniscience that knows what is hidden in the breasts. It exposes the false oath of the disbelievers who claimed they would never be resurrected, commanding the Prophet: *“Yes, by my Lord, you will surely be resurrected; then you will surely be informed of what you did; and that is easy for Allah!”* (64:7). It announces the *Day of Mutual Dispossession* (*Yawm al-Taghābun*), where those who believed and worked righteousness have their sins expiated and enter the rivers of Eden.
2. The Law of Affliction and the Inner Compass (11–13): Delivers the profound metaphysical axiom of suffering in verse 11: *“No disaster strikes except by permission of Allah. And whoever believes in Allah—He will guide his heart (*yahdi qalbah*). And Allah is Knowing of all things.”* It commands obedience to Allah and the Messenger, warning that the Messenger's only duty is clear delivery of the message, and that reliance belongs exclusively to Allah.
3. The Domestic Test and the Goodly Loan (14–18): Warns that spouses and children can become "enemies" when their love tempts a person to compromise moral integrity, consume unlawful wealth, or abandon sacred duties, yet commands that such domestic tensions be met with gracious pardon, forbearance, and forgiveness (*wa-in taʿfū wa-taṣfaḥū wa-taghfirū*). It issues the realistic moral imperative of verse 16: *“So be mindful of Allah as much as you are able (*fa-ttaqū Allāha mā staṭaʿtum*), and listen and obey and spend; that is better for your souls. And whoever is protected from the stinginess of his soul—it is those who will be successful.”* The sūrah concludes by inviting humanity to offer a goodly loan to God (*qarḍan ḥasanan*), for He is the Knower of the unseen and seen, the Exalted in Might, the Wise.

**The True Nature of Taghābun and the Guided Heart**

The core philosophical message of Sūrah at-Taghābun is that life is an ongoing economic exchange of time, love, and loyalty. In the commercial markets of this world, a trader is called successful if he amasses gold and land; but on the Day of *Taghābun*, the ultimate bankruptcy will be unveiled: the man who gained an empire but lost his soul will realize he made the most catastrophic trade in the universe. The sūrah teaches that true peace in the midst of worldly trials is found in the promise *Yahdi Qalbah* ("He will guide his heart"): when a soul submits to the decree of God, the Almighty pours into the heart a tranquil certainty that turns grief into gratitude and transforms domestic trials into stepping stones toward eternal felicity."""

# -------------------------------------------------------------
# SURAH 65: AṬ-ṬALĀQ
# -------------------------------------------------------------
intros[65] = """**The Jurisprudence of Parting and the Open Door of Deliverance**

Aṭ-Ṭalāq, "The Divorce," is the sixty-fifth chapter of the Qur'an, comprising 12 verses of Medinan revelation. In the Companion tradition, ʿAbdullāh ibn Masʿūd famously designated this chapter as *Sūrat al-Nisā' al-Ṣughrā* (The Shorter Chapter of the Women), highlighting its legal continuity with the fourth chapter (al-Nisāʾ) in establishing the sacred rights, financial maintenance, and legal protections guaranteed to women during domestic crises. Sūrah aṭ-Ṭalāq is universally celebrated for containing some of the most radiant, famous verses of spiritual hope, divine deliverance, and reliance found anywhere in sacred scripture: *“And whoever fears Allah—He will make for him a way out, and will provide for him from where he does not expect. And whoever relies upon Allah—then He is sufficient for him. Indeed, Allah will accomplish His purpose”* (65:2–3), and *“Allah will bring about, after hardship, ease”* (65:7). In twelve concentrated, legislative verses, the sūrah transforms the painful, volatile reality of marital dissolution from a theater of vengeance and acrimony into an arena of spiritual mindfulness, justice, and transcendent trust in the providence of God.

**The Crisis of the Home and the Abolition of Spiteful Divorces**

The historical context of Sūrah aṭ-Ṭalāq reflects the pervasive, cruel divorce customs of pre-Islamic Arabia that lingered into early Islam. Men would divorce their wives impulsively in fits of rage, throw them out of their homes instantly into the streets, withhold financial maintenance, prolong waiting periods maliciously to prevent them from remarrying, or attempt to defraud them of their nursing fees. Sūrah aṭ-Ṭalāq intervened with uncompromising legislative authority. It established that divorce is not a private, arbitrary weapon of male ego, but a judicial and moral procedure strictly regulated by God: divorce must only be pronounced at the beginning of the woman's prescribed period of purity (*li-ʿiddatihinna*); women must not be evicted from their marital homes during the waiting period (*lā tukhrijūhunna min buyūtihinna*); and the entire process must be supervised by two equitable witnesses (*wa-ash-hidū dhaway ʿadlin minkum*). The sūrah famously dictates the two ethical poles of marital life: *imsākun bi-maʿrūf aw firāqun bi-maʿrūf*—either retain each other in honorable kindness, or separate in honorable grace.

**The Structural Fabric of Legal Compassion**

The architecture of Sūrah aṭ-Ṭalāq moves across two tightly integrated movements:
1. The Jurisprudence of Separation and Child Welfare (1–7): Codifies the precise timing of divorce, the calculation of the waiting period (*al-ʿiddah*), and the strict prohibition of evicting the wife from the marital residence, reminding humanity: *“You know not; perhaps Allah will bring about after that a [different] matter”* (65:1). It commands that when the waiting term nears its end, the couple must either reconcile honorably or part honorably, taking two just witnesses. It legislates the waiting periods for women who do not menstruate and pregnant women whose term ends upon giving birth (65:4). Verses 6–7 codify the economic obligations of the husband: he must house the divorced wife according to his means, never harass or pressure her to leave, provide full financial support if she is pregnant until delivery, pay her fair compensation if she nurses the child, and consult together with mutual kindness (*wa'tamirū baynakum bi-maʿrūf*). The movement closes with the golden rule of economic equity: *“Let a man of wealth spend from his wealth, and he whose provision is restricted—let him spend from what Allah has given him. Allah does not charge a soul except [according to] what He has given it. Allah will bring about, after hardship, ease (*sayajʿalu Allāhu baʿda ʿusrin yusrā*)”* (65:7).
2. The Warning of Past Ruins and the Descent of the Seven Heavens (8–12): Warns the community that societal laws are not disconnected from cosmic order: many an ancient town insolently rebelled against the command of its Lord and His messengers, so God held them to a severe account and punished them with an awful punishment, tasting the evil consequence of their conduct. It commands those of understanding who believe to be mindful of God, reminding them that God has sent down a Reminder and a Messenger who recites clear verses to lead humanity out of darkness into light. The sūrah concludes with the magnificent cosmic doxology of verse 12: *“It is Allah who has created seven heavens and of the earth, the like of them. [His] command descends between them so that you may know that Allah is over all things competent and that Allah has encompassed all things in knowledge.”*

**The Sanctuary of Taqwā in the Midst of Broken Bonds**

The supreme philosophical achievement of Sūrah aṭ-Ṭalāq is that it repeats the word *Taqwā* (God-consciousness and moral mindfulness) five times in the context of divorce law. Marital breakdown is the ultimate test of human character: when romance dies and anger flares, human beings naturally incline toward cruelty, greed, and spite. Sūrah aṭ-Ṭalāq commands that precisely when the heart is bruised and the home is fracturing, the soul must cling to *Taqwā* with iron resolve. If a person maintains justice, honors the rights of the spouse, and refuses to use children as weapons of vengeance, God guarantees an exit from despair (*makhrajā*), uncalculated provision (*min ḥaythu lā yaḥtasib*), and the miraculous transformation of hardship into ease."""

for ch in [61, 62, 63, 64, 65]:
    insert_surah_intro(ch, intros[ch])
print("Batch 7 (Part A: 61-65) inserted successfully.")
