#!/usr/bin/env python3
"""Hand-written compact commentaries for the thin verse entries of Surah 37
(al-Saffat). Replaces the degenerate word-chain residue with real, simple
commentary; verse quotes are preserved verbatim from the existing data."""

import json

C = {}

C["78"] = """Wa-taraknā ʿalayhi — "and We left upon him" — is how the Qur'an describes a blessing that stays after a person dies: he was left among the later generations as a name spoken with honour. Ibn ʿAbbās explained it as being "remembered in a good way." The proof is that the greeting of this verse is still alive: the blessing did not remain written in one book but entered the mouth of every later generation, and it entered the prayer itself, where peace is sent upon Abraham in every tashahhud. Reward in the Qur'an is not measured by length of life or size of wealth; here a man's trial on one day became an honour that runs to the end of time. The verse closes the story it opened — the son was ransomed, the father was thanked, and both were left with a good name among the peoples who came after."""

C["79"] = """"Peace be upon Noah among all peoples" is scripture itself greeting a prophet. The greeting is not placed in the mouth of the angels or of the believers; Allah says it, which is why no greeting can be higher. It is "among all peoples" — not one nation only — because Noah was the messenger of a very long age and the father of the believers who came after the flood, so every later people inherit the duty to say this peace. Maududi notes that such greetings in the Qur'an are a form of continuing prayer: peace is asked for the prophet again and again, generation after generation. The sūrah has just told how his people were drowned and he was delivered; the greeting is the verdict on that whole history. A man opposed by his own household and mocked by his town for centuries is answered at last by his Lord's own salutation."""

C["80"] = """"Indeed, this is how We reward the good-doers" is the refrain of the sūrah. It comes after Noah, after Abraham, after Moses and Aaron, and after Jonah, because the same rule governs them all. The "reward" mentioned here is not only paradise; in these verses it names the things given in history — deliverance, a good name, lasting mention, a people who continue the truth. The Qur'an asks elsewhere: "Is the reward for good anything but good?" (55:60). Whoever does good is paid in kind: the good-doer who was patient with mockery receives honour that outlasts his mockers. The verse also teaches the reader how to hear the stories of the prophets — not as ancient history but as a repeated demonstration of a standing law of Allah. The law has not been suspended: the same words will be said over the faithful of every age."""

C["81"] = """"He was truly one of Our faithful servants" — the honour of Noah is stated in two words: servant, and believer. Servanthood (ʿubūdiyyah) is the highest rank the Qur'an gives a human being; it was given to the Prophet ﷺ at his greatest moments, in the night journey ("Glory to Him who took His servant by night," 17:1) and at the revelation of the sūrah of the stars. "Faithful" (muʾmin) adds trust: Noah believed Allah's promise while the flood had not yet come and while the whole society disbelieved it. Faith is measured at exactly this point — holding to the word of Allah when nothing around you supports it. The verse therefore tells the reader what to aim for. Not prophethood, which is not ours to choose, but faithful servanthood, which is. Whoever reaches that rank stands with Noah, and the reward of the good-doers is his by right."""

C["82"] = """"Then We drowned the others" compresses the end of a very long story into a single act. "The others" — the word does everything: those who mocked the ship, called the warning madness, and stood watching the animals board two by two. One sea, one command, and the whole argument of unbelief was closed. The verse deliberately keeps the lens on Allah's action, not on the drowning: "We drowned." The judgment of nations belongs to Allah alone, in His timing, and the believers are not asked to enact it. What the believers are asked is already stated in the verses before: board the ark when it is built, obey before the water rises. History after Noah teaches two lessons together — salvation came through visible, practical obedience (building a ship on dry land), and destruction came only to "the others," those who stayed apart from the believer's line."""

C["83"] = """"And indeed, one of those who followed his way was Abraham." The sūrah moves from one prophet to the next not by blood only but by succession of truth: Noah had a way (millah), and Abraham walked in it. The Qur'an elsewhere commands the Prophet ﷺ and every believer to follow "the creed of your father Abraham" (42:13), so his way is a standing model: pure monotheism, public argument against idols, trust in Allah under persecution, and worship carried out to the last detail when commanded. To be "one of those who followed his way" is presented here as the highest genealogy — better than descent from a prophet is obedience to a prophet's path. The verse also introduces the long Abraham passage that fills the rest of the sūrah's first half: Noah's story ended in drowning; Abraham's will end in ransom and greeting, because the following verses show how Allah rewards a servant who argues, migrates, and obeys."""

C["84"] = """"He came to his Lord with a pure heart" — the Arabic is qalb salīm, a heart that is safe and whole. Ibn ʿAbbās explained it as a heart that bears witness that there is no god but Allah and is free of doubt and pollution. The phrase names the only capital Abraham carried into his historic confrontation: no army, no wealth, no tribe standing behind him — one sound heart. Everything he did afterwards, the argument with his father, the mocking of the idols, the walk into the fire, the migration, the wait for a child, the knife on his son — all of it issued from that one inward purity. The verse turns the mirror on the reader: deeds are many in every age, but what enters the presence of the Lord is the heart carried to Him. A heart can be "safe" only when it is emptied of rivals to Allah and settled on Him; that settlement, not the noise of works, is the beginning of every true service."""

C["85"] = """Abraham begins his mission with a question, not a proclamation: "What are you worshipping?" The same dialogue is recorded at greater length in Sūrah 26 (26:70), and there his people answer honestly: "We worship idols and remain devoted to them." The question is a scalpel. It forces a society to look at its own practice and name it — and no idolater can name his practice without embarrassment, because the idols were known to be deaf, made, and traded. The first addressee is his father, which costs Abraham the most: the man who raised him is the first called out of idolatry, and kinship is not allowed to silence the truth. The verse teaches the method of every reformer since: before you preach, make people state what they actually worship — wealth, status, appetite, carved stone — because much idolatry survives only by never being named."""

C["86"] = """"Is it false gods that you desire instead of Allah?" — the question exposes the exchange. The idols are called "false" (āliha) precisely because they can claim worship but deliver nothing. Abraham's generation, like every generation, had made its preferences and dressed them as religion: gods nearer to hand, images easier to approach than the unseen Lord. The parallel verse (26:71) shows they had no defence ready — they could only say, "We found our fathers doing this." The verse therefore connects two sins that seem different: the theological error (worshipping what cannot benefit) and the social comfort (following ancestors). Abraham's question cuts both: you *desire* these — so the choice was desire, not knowledge. Every age repeats the exchange, replacing the unseen Lord with what it can see, manage, and carve. The verse asks the reader to check what he turns to first in hope and fear, because that, not the creed recited, is what he desires instead of Allah."""

C["87"] = """"What then do you expect from the Lord of all worlds?" — the question completes the argument. If you set up rivals, what is your estimate of the Lord you set them beside? Qatādah read the verse as a question of fear: do you fear these idols and not fear the Lord of the worlds? Either way — hope or fear — the idols have made the people small in their own religion. They expect little from the One who owns all worlds and much from stones that cannot speak. The phrase "Lord of all worlds" re-enters here deliberately: the sūrah used it to honour Allah at the head of a surah of the worshippers, and Abraham uses it in debate to measure the absurdity of the exchange. A person's religion is finally a set of expectations — what he truly thinks will act for him. The verse presses the reader to answer for his own expectations, for no one escapes the question: what do you expect?"""

C["88"] = """The scene changes to a plan. Abraham "looked to the stars" — the verse adds a bracket of interpretation, "in contemplation," because the look was a calculated move in an argument, not astrology. The Arabs knew the star-worshippers, and Abraham's people also read omens in the heavens; by fixing his eyes there, he prepares to use their own logic against them. The commentators remind the reader of the setting: a feast day when the whole town climbed to its idols, leaving the houses empty. Abraham, barred from the feast, stays behind — and the look at the stars is the first stroke of the plan that will end at the smashed idols. The lesson hidden in the staging: the prophet of pure monotheism is not naive. He reasons, plans, and times his action; truth in the Qur'an is armed with intelligence. Faith does not abolish strategy; it sanctifies it."""

C["89"] = """He turns to his people and announces: "I am really sick." The words are a plan, not a lie in the ordinary sense, and Ḥasan al-Baṣrī explained it as a device to be left behind from their idol-feast so that he could act on their gods. The scholars who discussed this verse drew the careful line: a believer does not lie, but a statement that turns the enemy away from harm — called in law tawriyah, an utterance with a true inner meaning (a sickness of heart over their idols) — is permitted in defence of faith. Abraham, the "intensely truthful" (ṣiddīq), is the one who does this, which itself proves the exception is narrow and need-based, not a licence. The verse also shows the prophet's patience of method: he does not storm the feast; he lets the people walk away from him. The next verses show why — the argument he is about to make needs an empty temple and an absent crowd."""

C["90"] = """"So they turned their backs on him and went away." The plan worked to the letter: the town, confident in its gods and dismissive of the young man who claimed sickness, leaves him alone. The verse is quiet, but it records one of the great turnarounds of the whole story: the moment a whole society stops watching the one man who has been threatening its religion. Qatādah and the commentators note the irony — they went to glorify their gods and thereby handed their gods over to their opponent. There is a standing lesson in how Allah prepares deliverance: the opening for truth often arrives dressed as an insult ("let him alone, he is sick"). The believer who is mocked out of a gathering may be being positioned by Allah for exactly the work that gathering could not afford to witness. The next verses open the temple door behind them."""

C["91"] = """Alone in the temple, Abraham turns to the idols with mock courtesy: "Will you not eat?" The question weaponises a known fact — offerings are laid before the gods, and the gods never touch them. The verse says he came "stealthily" (the bracket explains, quietly, by design), because the argument needs no audience of idolaters, only an audience of idols. In Sūrah 21 the fuller scene appears: Abraham asks them, "What is this you worship, you and your fathers?" and swears by Allah, "I will surely plot against your idols after you have gone away" (21:57–58). Here the sūrah keeps only the knife-edge of it: the offering question. It is the argument of common sense — worship is due to what gives, and what does not even take cannot give. The reader is meant to feel the silence of the temple: the gods eat nothing, and the silence is their whole biography."""

C["92"] = """The second question goes to the point: "What is wrong with you that you cannot speak?" An idol that cannot answer cannot guide, cannot warn, cannot thank, cannot curse — cannot do the least thing a worshipper needs a god to do. The Qur'an states the verdict plainly elsewhere: "Do they have legs to walk with, hands to strike with, eyes to see with, ears to hear with?" — "Say: Call upon your 'partners' and plot against me, and give me no respite" — for "those you call upon besides Allah are servants like you" (7:195–194). Abraham's mockery is not cruelty; it is the fastest route to make a whole people see what they have always seen and never looked at. Every idolater has heard his idol's silence. The verse asks the modern reader the same question with different objects: whatever cannot speak to you — wealth, image, faction — is standing in the place of a God who speaks."""

C["93"] = """"Then he swiftly turned on them, striking with the right hand" — Abraham breaks the idols, beginning the strike from the right, and the verb "turned" gives the movement of a man working through the temple. Sūrah 21 completes the picture: he left the largest idol standing and hung the axe's work on it — "Ask them, if they can speak" (21:63–64). The sūrah's version keeps only the act itself, the physical demolition of the sacred objects. Why the right hand? The commentators note the strength and decisiveness the phrase carries — this is no covert vandalism but an open, deliberate act of argument by deed. Idols had claimed lordship; a hand with an axe disproves the claim in public fact. The scene teaches that when speech is refused ("they turned their backs"), truth may still act, and that no object worshipped by men is too sacred to be broken by the command of the One who made men."""

C["94"] = """"His people came rushing towards him" — the word is "rushing" (aqsū), the speed of scandal. The news that the temple gods lie broken has emptied the feast, and the whole town arrives in a body. The verse does not hide the danger: a lone man, surrounded by an enraged crowd that has just seen its holiest objects destroyed. Yet within the rush the reader can see Allah's timing: Abraham wanted an audience, and now he has the whole city in one place. The rage that means to kill him will first have to hear him, and the argument he prepared in the empty temple will now be delivered at full volume to the very people who walked away from it. Prophetic history turns often on this hinge — the attempt to silence a voice becomes the assembly that hears it. The next verse shows Abraham completely unhurried, asking them a question as if nothing had happened."""

C["95"] = """The crowd asks who did this to their gods, and Abraham answers with the question that has already done its work: "How can you worship what you carve?" — then, with the irony already prepared in the temple, he points to the biggest idol: "Nay, it was this one, the largest of them, that did it — ask them, if they can speak" (21:63). The verse here keeps the core: worship is due to the Maker, not to the made, and carving is the confession of the made. An image is a receipt of human labour — someone designed it, chiselled it, carried it into the shrine. To bow to it is to bow to a fellow creature's workmanship. The argument has never expired: every religion of man-made objects and man-made ideas asks for worship while carrying its maker's fingerprints. Abraham's question remains the shortest test of any claim to divinity: did hands make you?"""

C["96"] = """The crowning argument: "when it is Allah Who created you and whatever you do." The verse settles in one line the oldest question of destiny: our acts are Allah's creation, and yet they are ours — we do them, and we are judged for them. The commentators balanced the two truths with the concept of acquisition (kasb): the ability, the limb, the opportunity, the outcome — all are created by Allah; the willing and the doing are attributed to the servant, who earns their weight. The verse in its context answers the idolaters first: your carving is also a created act — your gods are creatures of your own hands twice over, shaped by you and "created" in you by Allah. But the verse cannot be locked into that context, and the scholars refused to lock it: it is a full statement of the relationship between the Creator and every human deed. Man acts freely and is accountable; Allah wills all and is judged by none."""

C["97"] = """The debate lost, the people move to the fire: "they said, build for him a furnace and throw him into the blaze" (the fuller scene in 37:97). The verse before us records the counter-move of Heaven: "they sought to harm him" — the Arabic is a plot, an " deception aimed at him — "but We made them the inferior ones." The word al-āfilīn means those brought low, outdone, defeated. The same chapter that records the plan records its collapse: "We said, O fire, be cool and safe for Abraham" (21:69). The pattern is a law of the Qur'an: "they plot, and Allah plots, and Allah is the best of plotters" (the sense of 8:30). The servants of Allah may be out-numbered, out-argued by force, thrown into flames — and the plot itself becomes the stage of their vindication. The fire meant to end Abraham's message became the public miracle that crowned it."""

C["99"] = """Abraham leaves. "I am going to my Lord" — the Arabic is hijrah, migration, and Maududi notes the meaning: he emigrates for his faith, leaving father, homeland, and the valley of idols, going nowhere in particular because he goes to Allah. The statement contains a complete doctrine of trust: not "I am fleeing them" but "I am going to Him — He will guide me." A believer may leave a place without leaving the path, because the destination is not geography. The Qur'an honours this exact move elsewhere — "those who emigrate in the way of Allah... surely Allah will guide them" — and Abraham's hijrah ends not in exile but in a son, a sanctuary-line, and a name blessed among generations. The verse consoles every believer who has had to leave home, work, or companionship for the sake of religion: the road out, walked for Allah, is itself the road of guidance."""

C["100"] = """Settled in his new land, Abraham prays one prayer: "My Lord, grant me a righteous child." The wording matters — not a child, but a righteous one; Abraham asks for quality of faith, not only of lineage. The prayer is recorded again in Sūrah 14, where it continues with protection for his descendants from idolatry, and his fear that they might yet worship idols is stated there openly. Maududi draws the lesson of the order of the story: the man who argued with a nation, out-plotted a priesthood, and walked out of a fire now asks for a child with the humility of a beggar — "grant me" (hab lī). Great servants of Allah keep the smallness of supplication. The prayer also fixes the purpose of family in faith: children are asked for as a trust for righteousness, "of the righteous," so that the way of Noah and Abraham continues. The next verses show how completely the prayer was answered — beyond what he asked."""

C["101"] = """"So We gave him good news of a forbearing son" — the Arabic bashīr, news of joy, and the child is named by one quality: ḥalīm, forbearing, slow to anger, able to bear the hard command without bitterness. The commentators identify the son as Ismāʿīl, because the scene that follows fits the "patient, forbearing" character and because the early Muslims of the Prophet's ﷺ city, children of Ismāʿīl's line, understood it so; a minority read Isḥāq, and the difference of opinion is old and honest — the Qur'an's own sequence supports Ismāʿīl here and mentions Isaac's good news separately afterwards. What the verse teaches does not depend on the name: the answer to "grant me a righteous child" is a child whose defining trait is the ability to bear the command of Allah. The good news of heaven is not ease for the father but virtue in the son — and the next verse will show how far that virtue went."""

C["103"] = """"Then when they submitted" — the Arabic is aslamā, "both surrendered," father and son together, and the grammar of the sentence carries the whole story: the dream commanded Abraham to sacrifice the boy; the boy answered, "My father, do as you are commanded; you will find me, if Allah wills, among the patient" (37:102). Here the surrender is complete on both sides, and Abraham lays the son on the side of his forehead — face down, so as not to look into his eyes, and the blade passes over the neck's edge at once, the quickest mercy the act allowed. The commentators pause on the detail: the forehead, not the throat, tells of a hand shaking with love and obedience at once. Islam means this surrender — not the word only, but the will placed under the command at the exact point where it costs most. The whole religion of tawḥīd is named after what father and son did on that morning."""

C["104"] = """"We called out to him: O Abraham!" — a direct call from the Lord of the worlds, by name. In the Qur'an, the personal call marks the great moments: to Mūsā in the sacred valley ("O Mūsā!"), to Adam ("O Adam!"), and here to Abraham at the knife's edge. The commentators note what the call means: the trial is over, and the servant is not left in silence — Heaven speaks his name. Consider the timing: not after the trial began to spare him, but at its completion, when the surrender was total and the blade had reached its mark. The reward of tested obedience is audience. Every believer who says the prayer of Abraham in the tashahhud repeats the honorifics that grew from this moment, but the verse itself is more intimate than any liturgy: a man alone on a hill with his son, and the Lord of the worlds calls him by name to stay his hand."""

C["105"] = """"You have already fulfilled the vision" — the dream of a prophet is revelation, so the command was real, and the "fulfilment" was the whole-hearted going-forth with the act, not the shedding of blood. This is why the jurists say Abraham is the pattern of carrying out Allah's command to its brink: obedience is measured by the intention completed under the limb's obedience, and Allah stopped the blade. The verse then closes with the refrain: "Indeed, this is how We reward the good-doers." The reader should feel the scale of "reward": a knife stayed mid-air, a son returned alive, a name blessed to the end of time. No test commanded by Allah ends in pure loss; either the event is turned aside at the last instant, or it is repaid beyond counting on the other side. The trial of the vision asked for everything; the reward answered with everything. That is the standing law this refrain keeps repeating."""

C["106"] = """"That was truly a revealing test" — balāʾ mubīn, a trial made manifest. Jalālayn explains: an evident, plain trial, and the verse invites the reader to see how plain it was — the thing most precious to Abraham, requested by Allah, at the age when the son was his only companion and hope. The word "test" (balāʾ) in the Qur'an never means Allah needs to find out; it means the quality is brought out into the open, for the servant, for the people, for the generations. Abraham's monotheism was already famous; this trial exposed its depth — was the "pure heart" attached to Allah even against his own child? The test was "clear" in a second sense: it made clear to every later believer what Islam asks and what it is worth. The sūrah says of the trial what it says of the reward: both were public, both were real, and neither was a metaphor."""

C["107"] = """"And We ransomed him with a great sacrifice." The word "ransom" (fadaynāhu) means a life was taken as due and another given in its place; the "great sacrifice" (dhibḥ ʿaẓīm) is understood by the commentators as the ram sent from heaven, "great" because it came from Allah Himself, and great in what it would become. The scholars connect it to the sacrifice of the pilgrimage and of ʿĪd al-Aḍḥā, which the Prophet ﷺ called the sunnah of your father Abraham: every year the ummah repeats the ransom, and by it the humanity of the believer joins the obedience of Abraham. The deeper lesson stands behind the ritual: life belongs to Allah; the command proved the heart, and the blood of the animal, as the Prophet ﷺ said, does not reach Allah — "what reaches Him is the fear of you" (22:37). The ransom has never been about blood. It is about the surrendered heart, memorialised in every sacrifice offered since."""

C["108"] = """"and blessed Abraham with honourable mention among later generations" — the blessing is concrete and audible. In the prayers of the Jews ("in you all families of the earth shall be blessed" was the promise to Abraham), in the greetings of the Christians, and above all in the five daily prayers of the Muslims — "O Allah, send blessings upon Abraham and upon the family of Abraham" — the man is named with honour by billions, every day, centuries after his time. The Qur'an states the fact without mechanism: Allah "left" him a good name (the sense of 37:78), and the leaving was Allah's own act, not the world's accident. For the believer the verse is a window into how reward works: the currency of the hereafter can be paid out inside history as remembrance, influence, and honour that outlive death. Abraham asked for "a truthful tongue among the later generations" (26:84); the answer still runs in every mosque on earth."""

C["109"] = """"Peace be upon Abraham" — the greeting follows the blessing as its echo: he who is remembered with honour is greeted with peace. Yūsuf ʿAlī's translation doubles the phrase — "Peace and salutation to Abraham" — bringing out the Hebrew-style fullness of the salutation, salām plus ʿalayhi salām, the completeness of a wish that no harm ever touch the honoured servant. The greeting is now the permanent possession of the sūrah's readers: whoever recites al-Ṣāffāt recites it. In the prayer the Muslim says of Abraham, "upon him be peace and mercy of Allah," and in the pilgrimage the pilgrim walks the path of his hijrah and stands where he stood. The verse is short because a greeting is short; it is placed here so that the story of the knife ends not with trauma but with salutation — Allah's own etiquette for His friend: the trial told, and then the peace pronounced."""

C["110"] = """"This is how We reward the good-doers" — the refrain sounds again, now after the greeting, so that the reader ties the peace and the honour directly to the doing of good. The Arabic muḥsinīn — those who do good — is the broadest rank of virtue: not sinless perfection, but iḥsān, the doing of what is right with excellence and sincerity. The repetition through the sūrah (after Noah in 37:80, after Abraham here, after Moses and Aaron in 37:121) drills one law into the hearer: outcomes differ in this world, but the ledger of Allah never mispays. The reward already listed is staggering — ransom from death, a son, an eternal name, the greeting of Allah — and it was paid for one quality: he "came to his Lord with a pure heart" and obeyed at the point of greatest cost. The refrain is placed so that no reader can miss the application: this is how. The same standing reward waits on the same standing quality."""

C["111"] = """"He was truly one of Our faithful servants" — the pericope of Abraham ends where Noah's ended, with the same two-word rank: servant, believer (ʿabd, muʾmin). The repetition is deliberate: the sūrah's roll of honour does not advance by inventions or titles but by one qualification repeated. Abraham, the intimate friend of Allah (khalīl), the slayer of idols, the builder of the sanctuary, is summarised as a faithful servant — the same summary as Noah. The lesson for the reader is both humbling and bracing: nothing in the Qur'an's estimate of a human being outranks faithfulness. Genius, courage, and eloquence are all in the story, but the verdict line contains none of them; it contains trust obeyed. Whoever aspires to stand in this roll — and the sūrah's recitation is meant to create that aspiration — knows exactly the entry requirement, because it is printed after every name: servant of Allah, faithful."""

C["112"] = """"We ˹later˺ gave him good news of Isaac — a prophet, and one of the righteous." The word "later" (bashsharnāhu bi-isḥāq) settles a famous question: the son of the sacrifice passage has just concluded, so the sacrificial son and Isaac are two different sons, and the majority of the commentators — reading with the sequence — identify the ransomed son as Ismāʿīl. Isaac's news is given separately, as a second gift after the first trial: to the man who surrendered one son, Allah gives another, and marks this one with prophethood before his birth — "a prophet, one of the righteous." The verse teaches that Allah's giving is not impoverished by our trials: what was asked of Abraham did not close the door of joy against him. And the order of the titles is instructive — prophethood (the office) is joined to righteousness (the character), as if to say the second qualifies the first: in the Qur'an's estimate, a prophet must first be one of the righteous."""

C["113"] = """The blessing flows to both: "We blessed him and Isaac," and from their households came those who did good and those who "clearly wronged themselves." The verse states a truth the Qur'an insists on everywhere: righteousness is not inherited automatically. The children of prophets included believers and wrongdoers — Isaac's line carried both the Israelite prophets and those who "did wrong," and the Qur'an never hides it. "Wronged themselves" (ẓallama nafsah) is the Qur'an's exact idiom for sin: the sinner's real victim is his own soul, whatever harm reaches others; he traded lasting good for a moment's appetite. For the reader the verse is both comfort and warning in one line. Comfort: a righteous parent's blessing is a real gift sought by prayer. Warning: the gift must be received by each soul in faith and practice. No lineage, including the family of Abraham, carries anyone to paradise without the person's own surrender."""

path = "data/tafsir_037.json"
with open(path, encoding="utf-8") as f:
    d = json.load(f)
for vn, txt in C.items():
    assert vn in d["verses"], vn
    quote = d["verses"][vn].splitlines()[0][2:].strip()
    d["verses"][vn] = f"> {quote}\n\n{txt.strip()}"
with open(path, "w", encoding="utf-8") as f:
    json.dump(d, f, ensure_ascii=False, indent=2)
print(f"patched {len(C)} verses (batch 1: 78-113)")
