#!/usr/bin/env python3
"""Hand-written compact commentaries for thin Surah 37 verses, batch 2 (114-148)."""

import json

C = {}

C["114"] = """The sūrah now leaps from Abraham to his great descendants in prophethood: "And We certainly showed favour to Moses and Aaron." Maududi notes the honour of the pairing — two brothers made prophets together, the only such pairing in the Qur'an's history of messengers, so that the hardest mission of the Torah era was carried by mutual support. The "favour" (man) here names the whole sequence that follows in three compressed verses: deliverance, scripture, lasting mention. For the reader who knows the long Exodus narratives of Sūrahs 20, 26, and 28, the compression is the point: al-Ṣāffāt is a roll of honour, not a chronicle, and each name receives its medal in a line. The placement is also deliberate — the family of Abraham continues in Israel's prophets, so the chain of "those who followed his way" runs unbroken from Noah to Moses to the Prophet Muhammad ﷺ."""

C["115"] = """"and delivered them and their people from the great distress." Maududi explains the distress (karb al-ʿaẓīm) as the whole Egyptian captivity: the enslavement of a people, the killing of their sons, the tyranny of Pharaoh who said "I am your lord, most high" (79:24). Deliverance from it is the defining mercy of Moses' mission — the splitting of the sea, the destruction of the chariots, the passage of a broken nation into freedom. The verse keeps the theology exact: the deliverer was not Moses' staff but Allah — "We delivered them." Prophets are agents of rescue, never its author. For every community crushed under an unbearable order, the verse is a charter of hope: the "great distress" of history is real, and Allah has destroyed one before. The next verse adds the seal — "and We helped them, so they were the ones overpowered" — the rescued become the upper hand."""

C["117"] = """"We gave them the clear Scripture" — the Torah, described as kitāb mubīn, a writing that makes things plain. The Qur'an honours the revealed book of Moses even while correcting what hands did to it later, and the description "clear" carries both praise and a standard: revelation's work is to remove ambiguity about the two great matters — who Allah is, and what He requires. Elsewhere the same gift is called "the Criterion" (al-Furqān, 21:48), because a clear scripture judges between truth and its imitations. The verse sits between the deliverance from Egypt and the lasting blessing that follows it, teaching the order of Allah's gifts to a community: first freedom, then guidance — liberation that arrives without revelation collapses into a new slavery, as the episode of the golden calf showed within weeks. A people saved by Allah needs the book of Allah immediately, and Allah did not delay it to them."""

C["119"] = """The formula returns: "And We blessed them with honourable mention among later generations." What was said of Abraham is said of Moses and Aaron — the same words, the same currency of reward. This is the third time the sūrah has used the formula, and the reader should now feel its weight: heaven's gift to His faithful servants is a good name that survives them. For Moses, the promise is astonishingly literal — his story fills more of the Qur'an than any other prophet's; his name is spoken daily in the prayer alongside Abraham's; the Torah and the Qur'an together keep his memory alive among nations who never met him. The blessing cost him decades of confrontation with the strongest empire on earth. The verse quietly teaches the economics of the hereafter: what is spent of self for Allah's message is repaid in remembrance that does not decay, while the empire that resisted is remembered only as the background of his story."""

C["120"] = """"Peace be upon Moses and Aaron" — the same salutation pronounced over Noah, and soon over Elias and Jonah. The roll call of al-Ṣāffāt is punctuated by these greetings because the sūrah's subject is the company of the honoured, and in the etiquette of that company, peace is both protection and position: "peace" is the word of the Hereafter's safe-greeting (the believers are greeted with "peace" in paradise, 10:10), and it is spoken here over those who finished their term safely in faith. The pairing of the two brothers in one greeting mirrors their pairing in one mission — neither is greeted without the other, so close were their labours. For the reciter, the verse trains a habit: the men and women who carried Allah's word through history are not neutral figures in a textbook; they are to be greeted, loved, and asked-for in peace, because love of the prophets is part of the covenant of their Lord."""

C["121"] = """"Indeed, this is how We reward the good-doers" — after the greeting, the law is restated. The sūrah has now applied the identical formula to Noah, to Abraham, and to the two sons of Israel, and the monotony is the message: heaven does not have private arrangements with its favourites, only a public rule. What did Moses and Aaron "do good" with? They confronted the tyrant of their age without an army; they delivered a nation; they carried a scripture; they bore the ingratitude of their own people in the wilderness without seeking revenge. The reward — deliverance in history, salutation in scripture, honour among generations — is the same shape as Abraham's. The verse invites a simple examination: the rule is published; the entry conditions are published; the refrain reminds the reader after every story that the same door stands open. Between the refrains the sūrah keeps inserting the qualification: servant of Allah, faithful, patient, believing."""

C["122"] = """"They were truly of Our faithful servants" — the verdict formula closes the Moses-and-Aaron passage exactly as it closed Noah's and Abraham's. Maududi points to the singular standard behind the plural honour: different missions, different eras, one evaluation — faithfulness. Moses, who spoke with Allah, and Aaron, who bore the people's mockery beside him, are both filed in the register under the same two words used for the man who argued with idols in Ur. The Qur'an's system of honour is thus completely unlike the world's: the world files men by victory, wealth, and fame; the Qur'an files them by ʿubūdiyyah and īmān — servanthood and faith. The reader who has followed the roll this far — Noah, Abraham, Moses, Aaron — has seen kings of nations passed over in silence while servants are crowned. The next verse adds a new name to the roll, Elias, and the verdict lines continue unchanged."""

C["123"] = """"And Elias was indeed one of the messengers" — Ilyās, the prophet of the northern kingdom of Israel, sent to a people who had traded the worship of Allah for Baal. Qatādah is among those who identified Elias with Idrīs, a view some commentators transmit, though the majority keep them distinct; what the sūrah itself asserts is enough — he was truly a messenger, restored here to the honour his own generation denied him. The Bible remembers him confronting King Ahab and winning the great contest on Mount Carmel; the Qur'an compresses that ministry into the argument of the next verse. The naming is itself the vindication: a prophet hunted by his own king, "wearied" (as the Bible says) into the wilderness, is entered by Allah into the permanent roll of al-Ṣāffāt between Moses and the successors of Abraham. The world's verdict on a prophet and Heaven's verdict are two different documents."""

C["124"] = """"When he said to his people: Will you not fear Allah?" — the prophet's opening is a question of the heart, not a lecture of theology. Taqwā — fear that becomes avoidance of wrong — is the root Elijah attacks: a people who had stopped taking Allah seriously enough to fear Him could be sold any idol. The Baal cult he confronted offered rain, fertility, and empire — religion dressed as prosperity — and the prophets of Baal outnumbered him by hundreds (the Bible counts four hundred and fifty). The verse preserves the beginning of every reform: one man, one question, addressed to a whole society — will you not fear Allah? Not "will you not fear the consequences," nor "do you not see the ruins" — fear of Allah is the first and organizing repentance. The sūrah places the question here so that the reader hears it as still open: every generation is Elijah's audience now."""

C["127"] = """"But they rejected him, so they will certainly be brought." The word "brought" (l-muḥḍarūn) means escorted, driven into presence — the refused prophet's people will be marched to the reckoning whether they believe in it now or not. Maududi reads the verse as the standing consequence of national refusal: the prophets bring the only message by which a people can answer for themselves, and rejection postpones the accounting but never cancels it. Elijah's own history underlined the warning — the kingdom that mocked him sank into the collapse the prophets foretold, and the Assyrian conquest swept Baal's altars away with the dynasty that housed them. For the reader the verse fixes a fact about the future: no majority, no empire, no indifference is large enough to vote away the Day. The rejected messenger loses only the pleasure of their company; the rejecting people lose their final argument. The appointment stands — "they will certainly be brought."""

C["132"] = """"He was truly one of Our faithful servants" — the verdict falls on Lot, closing his passage as it closed the passages before him. The honour is startling on first reading: Lot, whose mission ended with his wife looking back, his city in ruins, and his guests fleeing before dawn — yet Heaven's register enters him as a faithful servant. The Qur'an thus separates the outcomes of prophethood from its faithfulness: Lot saved the believers with him (27:58), lost his society, and is not blamed for the loss. The commentators note that the phrase mirrors what was said of Noah — both prophets saw their peoples destroyed, and both are crowned with the same words. The lesson for every servant whose sincere work meets stubborn refusal is in the verdict: success in the Qur'an is faithfulness executed, not crowds converted. Heaven's audit asks what the servant was given and what he did with it — Lot did all his Lord commanded."""

C["135"] = """"except an old woman, who was one of the doomed." The angels' rescue of Lot's household had one exception, and the sūrah names it with the mercy of precision: the old woman — identified by the commentators as Lot's wife — "was of those who stayed behind" (the sense of 27:57). Her doom was not ignorance; she had lived under a prophet's teaching and shared his table, yet her heart had stayed in the city she was leaving, and the Glorious Qur'an makes her the standing example of the believer's own household who fall away — the Prophet's ﷺ own words about a man whose deeds are lightened by family ties apply to her case ("she will be of the doomed" was said of a wife who betrayed her husband's trust). The verse teaches the painful boundary of faith: salvation is never by proximity to the righteous. A wife of a prophet, a daughter of Noah (11:43) — both are named in the Book as lost. Each soul reaches its own belief."""

C["136"] = """"Then We destroyed the rest" — the final word on the Cities of the Plain. Maududi stresses the completeness: the corruption of Sodom was total — highway robbery, shaming of guests, public lust legislated as habit — and the punishment matched it, the cities overturned and rained with stones "layer upon layer" (11:82). The archaeological plain around the Dead Sea still offers the traveller burnt, overturned sites along the shore, and the Qur'an will point to them in the next verses as a sign passed on the road. Theologically the verse answers the question of collective doom: "the rest" — those who were not of the believing household, who did not leave with Lot, who laughed at his restraint — shared the city's guilt by choice and its ruin by justice. No age is entitled to think total corruption a stable condition; the Qur'an records its end once, in fire from the sky, as a lesson signed into geography."""

C["138"] = """"and night. Will you not then understand?" — the verse completes 37:137's image: "you pass by them in the morning, and by night." The ruins of the Dead Sea cities stood directly beside the caravan route between Madinah and Syria, and the Qur'an's audience passed them literally on business journeys. Allah turns the roadside into a classroom: the traveller who saw the overturned land, dead of vegetation, sunk below the surrounding plain, was looking at the consequence of a moral choice made by people who spoke, traded, and married like himself. "Will you not understand?" — the question is not rhetorical mockery but an invitation: the same eyes that take in the ruins are able to take in the lesson. The Qur'an makes this use of ruins its habit — "travel through the earth and see how was the end of the deniers" — and this particular ruin is the most visited of all, passed morning and night for three thousand years, still asking its question."""

C["139"] = """"And Jonah was indeed one of the messengers" — Yūnus, Dhū al-Nūn, "the man of the fish." The declaration matters because of the story that follows: Jonah fled his mission, was swallowed, and despaired of his people — conduct that might seem to disqualify a prophet. The sūrah asserts his rank first, then tells the failure, because the two together are the lesson: a true prophet can stumble, and his stumble does not unmake his prophethood; and a true prophet's stumble is itself repented in a way that becomes guidance. Jonah is also unique in another honour the Qur'an states elsewhere: the Prophet ﷺ said no one should say he is better than Jonah (a report in Bukhārī and Muslim), precisely because of this story's end. The roll of al-Ṣāffāt does not hide the weakness of its heroes — that is what makes the roll believable, and its verdicts ("faithful servant") trustworthy."""

C["142"] = """"Then the fish engulfed him while he was blameworthy." The word mulīm — blameworthy — is the Qur'an's own verdict on Jonah's flight: he boarded the ship, drew the lot, and was thrown to the sea as the storm demanded, and the fish received him as a man under blame, not as a martyr of circumstance. The three layers of the darkness he named in his prayer inside the fish — "darknesses" of the deep, of the night, of the belly (21:87) — begin with this verse's fact: the engulfing. Yet even the blame is framed with mercy: the fish was "commissioned" (the Qur'an says of it nūn, a fish that "swallowed him while he was blameworthy" — appointed, not accidental; the creature of Allah does the guarding while it does the punishing). For every servant who has run from a duty of religion, the verse states the anatomy of the consequence: the flight itself becomes the fish. And the next verse will show the single act that opens its mouth."""

C["143"] = """"Had he not been of those who glorify Allah" — the conditional that explains the rescue. Inside three darknesses, Jonah "called out in the darknesses: there is no god but You, glory be to You; I was of the wrongdoers" (21:87) — a confession containing tawḥīd, God's transcendence, and his own guilt, with no excuse offered. The Prophet ﷺ taught this verse as the prayer of the distressed: "The prayer of Dhū al-Nūn which he prayed inside the fish — no Muslim prays with it for anything but Allah answers it" (Tirmidhī). The sūrah's conditional teaches the mechanics: the glorification did not earn rescue as wages; it *was* the rescue, because "had he not been of the glorifiers, he would have remained in its belly until the Day they are resurrected" (37:144). A drowning man's tongue, remembering his Lord, weighs more than a life's course in the balance — such is the power of tasbīḥ issued from the bottom of need."""

C["147"] = """"We sent him to a hundred thousand or more." Ibn ʿAbbās explained the figure as the population of Nineveh, Jonah's city — "a hundred thousand or more," the Qur'an's wording allowing for the indefinite excess (the same phrase appears in Ṣaḥīḥ al-Bukhārī as a gloss on this verse, where the Prophet ﷺ was asked about "the people of the whale" and gave this number). The number matters theologically: Sūrah Yūnus laments that "no town has believed and its belief profited it — except the people of Jonah" (10:98). One man, freshly delivered from a fish, walks into an Assyrian capital of over a hundred thousand — the empire that would one day crush Israel — and the whole city believes. The verse stands in the roll of al-Ṣāffāt as the measure of Allah's power to turn hearts: the prophet who could not stand his own people at first became, by Allah's command, the single most successful preacher of warning in the recorded history of the prophets."""

C["148"] = """"So they believed, then We gave them enjoyment for a while." The belief of Nineveh is the exception the Qur'an underlines: an entire city, warned, believed at once — "and We removed from them the punishment of disgrace in the life of this world" (10:98). Maududi notes the order of events: belief first, reprieve after — the "enjoyment" (mutamattiʿīn) was not the reward of paradise but a postponement of worldly doom, life lived out to its natural term under Allah's lifted sentence. The verse teaches both the speed of mercy and its conditional nature: the reprieve of a warned people lasts while the belief lasts, and generations that forget return to the ordinary law of history. For the reader the verse completes Jonah's arc with its meaning: the prophet who despaired of his people was made the instrument of the largest collective repentance on record — Allah's answer to his premature verdict on hearts he did not own."""

path = "data/tafsir_037.json"
with open(path, encoding="utf-8") as f:
    d = json.load(f)
for vn, txt in C.items():
    assert vn in d["verses"], vn
    quote = d["verses"][vn].splitlines()[0][2:].strip()
    d["verses"][vn] = f"> {quote}\n\n{txt.strip()}"
with open(path, "w", encoding="utf-8") as f:
    json.dump(d, f, ensure_ascii=False, indent=2)
print(f"patched {len(C)} verses (batch 2: 114-148)")
