#!/usr/bin/env python3
"""Hand-written compact commentaries for thin Surah 37 verses, batch 3 (149-179)."""

import json

C = {}

C["149"] = """The sūrah turns to the theological scandal of the Makkans: "Ask them — does your Lord have daughters, while they prefer sons?" The pagan Arabs traced angels as Allah's daughters — "the daughters of Allah" — while they themselves, in their shame culture, resented the birth of daughters. The Qur'an exposes the double standard across half a dozen sūrahs: "When one of them is given news of a daughter, his face darkens and he chokes with grief" (16:58) — yet he assigns to Heaven the very sex he despises. The verse's method is the prophet's method: put the question to them directly and let their own convictions answer it. A man who believes his god has daughters must explain why daughters are dishonour among men but ornaments among gods. The question remains a standing test of every invented theology: does it honour Heaven — or merely relocate the prejudices of earth?"""

C["150"] = """"Or were the angels created as females before their eyes?" — the second question strikes at the supposed evidence. No one ever saw an angel at all, let alone a female angel; the "witnesses" of the pagan cosmology are pure invention, and the verse says so: "before their eyes" — they were present at their own fiction's birth. The Qur'an elsewhere states the truth of the angels' nature: "they say, the Most Compassionate has taken a son... they are but honoured servants who do not precede Him in speech and act at His command" (21:26–27) — beings of light, neither male nor female, neither eating nor sleeping. The Arabs made the unseen world a mirror of their own society, complete with marriages of the gods. The verse's lesson reaches every age: religions built on imagination rather than revelation end up describing heaven with the fashions of the street. What is unseen must be learned from the One who sees it, or not claimed at all."""

C["153"] = """"Has He chosen daughters over sons?" — the syllogism stated in its final absurdity. The pagan position, laid out by their own lips, amounted to this: Allah, the Greatest, has chosen for Himself exactly what the Arabs chose to despise — daughters. The verse asks it as a question of "choice" (iṣṭafā), the word the Qur'an uses for Allah's choosing of prophets and pure servants: does the Lord of the worlds "choose" for His own household the very thing His creatures would refuse? The question needs no formal refutation; its absurdity refutes it. The Qur'an comments on this species of blasphemy directly: "When the girl buried alive is asked, for what sin she was killed" (81:8–9) — the same society that invented divine daughters buried its own. The verse holds up the logic of invented religion until it collapses of its own weight: men fashion gods in the shape of their own double standards."""

C["154"] = """"What is the matter with you? How do you judge?" — the divine cross-examination. Jalālayn reads it as: what has corrupted your judgment, that you pass such verdicts? The question is addressed to the intellect before the conscience: the pagan claim about the angels is not only impious, it is irrational — it has no evidence, contradicts the majesty it pretends to honour, and offends the very values its makers held. The Qur'an habitually appeals to precisely this faculty — "affix your intellect; I am not, in the manner of your slanders, an insane poet," the sense of 68:36 — "What is the matter with you? How do you judge?" The verse teaches that faith in the Qur'an is never a surrender of judgment but its highest exercise; blasphemies survive only where judgment is asleep. And the question lingers past its first audience for every reader who has ever inherited a belief he has never once examined."""

C["155"] = """"Will you not then be mindful?" — tadhakkarūn, will you not receive reminder? The previous verse questioned their judgment; this one questions their receptivity. Between the two stands the whole purpose of warning: judgment can analyse, but only mindfulness turns analysis into change. The verse closes the daughters-of-Allah passage not with a proof but with an appeal, because the pagans' failure was finally not intellectual but moral — they had the questions answered in their hearing and returned to their idols. The Qur'an names this state in the verse after: "Has the Reminder been made to fall upon them?" (38:8, the sense) — the strange resentment of those who resent being reminded. For the reciter, the sequence is a mirror-check: proof heard, conscience addressed — will you not be mindful? The word is plural, and daily prayer repeats the sūrah; the reminder keeps arriving until the heart answers or refuses outright."""

C["159"] = """"Glory be to Allah, high above what they describe" — the verse of transcendence. The pagan claims about Allah — daughters, kinship with jinn, partners — are answered not with a detailed rebuttal but with one word: subḥān, the declaration that Allah is utterly beyond and free of every defect said of Him. The formula is the Qur'an's great guardrail of theology: whenever description risks dragging the Creator down to creaturely measure, "Glory be to Allah" lifts the line again. The Prophet ﷺ taught that when a servant says subḥān Allāh, he is answered from beneath the Throne with "you have spoken truly" (a report of Muslim in the ḥadīth of the ascension). The verse also states the principle of all sound speech about God: descriptions of the Unseen are received, not invented; what the tongue cannot prove from revelation should be returned to silence. High above what they describe — and above what any tongue will ever describe."""

C["160"] = """"Except the chosen servants of Allah" — the exception that saves the verse from despair. The previous verse declares the glorification of "the seven heavens, the earth, and whoever is in them"; this one removes from the condemnation a named class: ʿibād Allāh al-mukhlaṣūn, Allah's purified, chosen servants. The Qur'an uses the same exception elsewhere: "his chosen servants" are the ones who "do not speak until He has spoken" and "act at His command" (21:27). The commentators identify them as the angels among creatures and the sincere believers among men — all who worship Allah with exclusive devotion and purified intention. The verse carries a quiet consolation: in an age when religion itself was dressed in lies, Allah keeps an exception-list of His own, known fully to Him, who do not share the corruption. It also carries a question: would the exception include the reader? Purity of devotion — ikhlāṣ — is the entry requirement, and it is tested most where lies are fashionable."""

C["161"] = """"So you and what you worship" — the verse begins the sentence that concludes in 37:163: you and your idols together "cannot tempt anyone away" except the one bound for Hell. The structure is staggering in its contempt: the entire apparatus of Makkan idolatry — the 360 idols of the sanctuary, their priesthood, their processions — and it is gathered into one phrase, "you and what you worship," and assigned to the same court file. The Qur'an elsewhere seals the same verdict in the picture of the Hereafter: "Then they will be hurled into it upon their faces — they and the deviators, and the hosts of Iblīs, all of them" (26:94–97), where the idols disown their worshippers. The verse teaches the futility of the whole enterprise: a religion without revelation cannot save even its own gods, much less its followers. What follows in the next verses is the narrow, precise exception — and the fate of those outside it."""

C["163"] = """"Except those destined to burn in Hell" — the precision of the exception completes the verdict on the idolaters and their idols: the alliance "cannot lead astray" Allah's servants (the sense of the passage), except those who were already "of the destined" (l-āmin) — the ones for whom hell was written by their own persistent choice. The commentators note the justice in the wording: none is led astray by force; the idols "tempt" only those whose record had already resolved on refusal. Fate in the Qur'an is not a chain laid on the innocent; it is the seal on a history. The verse also removes an excuse the pagans might raise — "our gods overpowered us" — no: the temptation reached only those for whom the Fire was already the fit destination. Free choice, persistent refusal, and finally the sealed outcome: the three verses together state the Qur'an's whole doctrine of destiny, warning and warning again against reading it as compulsion."""

C["164"] = """"There is not one of us without an assigned station." The speaker changes: the angels answer the pagan slander of their nature. The word maqām maʿlūm — a known station — carries two truths at once. Order: heaven is not a chaos of spirits but a ranked service, every angel fixed at his post — the bearers of the Throne, the keepers of Paradise and Hell, the recorders, the rain-bearers — and none steps outside his assignment. Devotion: the "station" is a station of worship, as the bracket renders, for the angels' posts are prayers that never lapse. The pagan picture of angels as Allah's daughters made heaven a harem of favourites; the angels' own testimony corrects it: we are functionaries, bonded to our tasks. The verse dignifies the ordered life of religion: to have a "known station" — a fixed prayer, a fixed duty, a fixed place before Allah — is not limitation but angelic nobility, and the reversal of the pagan fantasy could not be more complete."""

C["165"] = """"And we are indeed the ones ranged in ranks" — the angels continue their testimony. Muslim records from Ḥudhayfah ibn al-Yamān that the Prophet ﷺ said, "You see what your Lord has sent down upon you — the angels do not cease, in a night and a day, from ranks" (Ṣaḥīḥ Muslim), and a report in Bukhārī describes the angels of the night and the day meeting at the prayers of dawn. The image is of disciplined hosts — ṣaff, the word used for a battle line and for a prayer row — standing shoulder to shoulder in the service of their Lord. The pagan Arabs made heaven a court of rival personalities; revelation shows a perfectly drilled order. The verse also sets the etiquette of congregational prayer on earth: the Prophet ﷺ commanded his followers to "straighten your rows, for the straightening of rows is from the completion of prayer" (the sense of Bukhārī and Muslim) — earth's worship taking its posture from heaven's hosts."""

C["166"] = """"And we are indeed the ones glorifying Him" — the third article of the angels' confession: fixed station, ranged order, unceasing praise. The Qur'an insists that glorification is not silence but speech: "the seven heavens and the earth and whatever is in them glorify Him, and there is nothing that does not glorify Him with praise, but you do not understand their glorification" (17:44). The angels' tasbīḥ is the perfect form of what human remembrance stammers at — praise that never tires, never wanders, never seeks anything back. And the pagans had slandered these very beings with kinship claims; the angels answer the slander with their office: the beings you call Allah's daughters are consumed, morning and night, in declaring His freedom from everything you say. The verse quietly sets the standard for the human worshipper too: the prayer of the sūrah's title row — al-Ṣāffāt, those ranged in ranks — is perfected when it becomes praise without interruption."""

C["167"] = """"They certainly used to say" — the speaker changes again, and the commentators read the verse as the confession of the pagan Arabs, quoted before their conversion, or as the admitted claim of the earlier idolaters among the "peoples of the Reminder." The next verse states what they said: "If only we had a Reminder like the peoples before, we would have been Allah's devoted servants." The verse that introduces this confession is short and deliberate: heaven records what the unbelievers used to say, word for word. Nothing a generation says against its own accountability is forgotten; the excuse they constructed for themselves is preserved and will be read back to them. The Qur'an does this repeatedly — quoting the disbelievers' own words as the evidence of their knowledge: they knew revelation came to earlier peoples, they knew what devotion meant, and they knew what they would have done. The verse teaches that language is recorded, and every "if only" is archived."""

C["168"] = """"If only we had a Reminder like the peoples before" — the hypothetical that damns its speakers. The "peoples of the Reminder" are the Jews and Christians, holders of earlier scriptures; the pagan Arabs knew it, and admitted in their councils that guidance required a book and that a book would be obeyed — by them, they claimed. The Qur'an freezes the wish here so that the next verse can confront it with the fact: the Reminder came, "and now they disbelieve in it." The passage is the Qur'an's standing answer to every generation that blames its circumstance for its unbelief — wrong prophet, wrong language, wrong century, insufficient evidence. The Arabs had the highest evidence a people ever received: an unlettered man among them, reciting a book none could imitate, with their own names and history in it. The verse teaches the worthlessness of unreal piety — devotion promised under conditions never met is not devotion but self-flattery awaiting its excuse."""

C["169"] = """"We would surely have been Allah's devoted servants" — the conclusion of the pagans' hypothetical confession, and its verdict is supplied by the next verse: "But they disbelieved in it, so they will come to know." The phrase "devoted servants" (ʿibād mukhliṣīn) is exactly the rank the angels claimed for themselves in 37:165–166 — ranged, praising, singly devoted. The pagans knew the rank and named it; the knowledge makes the refusal inexcusable. The Qur'an exposes here the anatomy of insincere religion: love of a virtue one declines to practise. It is easy to promise obedience to a revelation that never came; the test arrives with the revelation itself, and the promise dissolves. For the believer the verse is a warning against the same disease in subtle form — admiring the Path, describing the Path, praising the Path, while deferring the walking. The confession is preserved precisely so no one can claim the thought was ever the deed."""

C["170"] = """"But they disbelieved in it, so they will soon know" — the hypothetical is answered by fact: the Reminder came in their own tongue, by the tongue of one of their own, and they disbelieved. "So they will soon know" — the phrase carries the Qur'an's grim courtesy: knowledge will arrive, but by then it will be the knowledge of outcome rather than of invitation — they will know the truth of the message when its consequences stand before them. Elsewhere the Qur'an fixes the same formula at the moments of reckoning: "they will know when the iron collars are upon their necks" (40:71). The verse balances 37:168–169 perfectly: they knew enough to describe what they would do with a Reminder; now they refuse the Reminder itself; the knowledge that remains is the terrible kind. The verse teaches the reader to close the gap in his own life while the gap is still mercy — to know now, by believing, rather than then, by suffering."""

C["171"] = """"Our Word has already gone forth to Our servants, the messengers" — the sentence begun here runs to 37:173: the word is a decree, already issued, binding heaven's policy — "that they will be helped, and that Our army — they are the ones who will prevail." The decree is stated as settled history before its events: every messenger of Allah enters his mission with this verdict pre-written. The commentators read "Our Word" as the promise recorded since the first warnings — Noah assured against his people, Abraham rescued from the fire, Moses delivered from Pharaoh — the pattern sealed, in the sūrah's own roll, by verse after verse the reader has just passed. The verse addresses the Prophet ﷺ in his hardest Makkan years: boycotted, mocked, and outnumbered, he is told the outcome is not pending but decreed. For every servant of truth, the verse fixes the end of the story in advance: the help of Allah is not a possibility to be won but a fact to be waited through."""

C["172"] = """"That they will surely be helped" — the second clause of the decree. The Arabic lan-nunṣiranna is the strongest form of the future: "We will most certainly help." The help promised here is defined by the verse that follows — "and My army, they are the ones who will prevail" — and its meaning in the prophetic record was never victory in a single battle but the unstoppable survival and triumph of the message itself. Noah's message outlived his drowning people; Abraham's outlived the furnace; Moses' outlived Pharaoh; the Prophet's ﷺ outlived the Quraysh who planned his death at every stage of thirteen years. The verse therefore defines help the way heaven defines it: sometimes the servant is rescued from the fire, and sometimes the fire is made cool around him while the message walks out. The believer who serves Allah's cause is told in advance how the story ends — the only variable is the road, never the destination."""

C["174"] = """"So turn away from them for a while" — the command given to the Prophet ﷺ at the height of Makkan hostility. The verse is not a dismissal of the deniers; it is a strategy of patience: "for a while" (ḥattā ḥīn) — a term set by Allah, unknown to the servant. The Qur'an repeats the instruction in several forms — "leave Me with those who deny this speech" (73:11), "so turn away from them, you are not blameworthy" — and each verse teaches the same balance: the messenger delivers; the results belong to Allah; the denier is not pursued into coercion ("there is no compulsion in religion," 2:256). The Prophet ﷺ lived this verse for thirteen years in Makkah — preaching without retaliation — before Madinah. The verse consoles every caller to goodness who meets refusal: turning away is not defeat; it is obedience to a rhythm Allah Himself set — a "while" that belongs to Him, after which the decree of help arrives exactly as written."""

C["179"] = """"And see, then they will see" — the verse and its twin (37:175, 179) frame the sūrah's final warning. The first "see" is addressed to the Prophet ﷺ and the believers: watch the decree unfold — the help promised to the messengers, the outcome of the refusers. The second "they will see" is the deniers': what they now dismiss as tales will present itself as fact, and seeing will no longer be optional. The Qur'an uses this double-seeing formula repeatedly — "they see it far, and We see it near" (70:6–7) — because the entire dispute of unbelief is about which things are real. The verse teaches the believer the posture of certainty: not anxiety at the world's refusal, but a watching patience — "see" — anchored in the decrees already quoted. History kept the promise in the Prophet's ﷺ own lifetime; and the final seeing, the one the sūrah ultimately points to, remains on schedule for every soul that deferred it."""


path = "data/tafsir_037.json"
with open(path, encoding="utf-8") as f:
    d = json.load(f)
for vn, txt in C.items():
    assert vn in d["verses"], vn
    quote = d["verses"][vn].splitlines()[0][2:].strip()
    d["verses"][vn] = f"> {quote}\n\n{txt.strip()}"
with open(path, "w", encoding="utf-8") as f:
    json.dump(d, f, ensure_ascii=False, indent=2)
print(f"patched {len(C)} verses (batch 3: 149-179)")
